<!DOCTYPE html>
<html lang="en"><head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src=".00_files/libs/clipboard/clipboard.min.js"></script>
<script src=".00_files/libs/quarto-html/tabby.min.js"></script>
<script src=".00_files/libs/quarto-html/popper.min.js"></script>
<script src=".00_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href=".00_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href=".00_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href=".00_files/libs/quarto-html/quarto-syntax-highlighting-de84f8d6bb715db06a919283c2d1e787.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src=".00_files/libs/quarto-contrib/iconify-1.0.7/iconify-icon.min.js"></script><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <meta name="author" content="Ігор Мірошниченко">
  <title>Регресійний аналіз у прикладній статистиці</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href=".00_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href=".00_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href=".00_files/libs/revealjs/dist/theme/quarto-26a030a05c7f22f9b9eae400ebcceb06.css">
  <link href=".00_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href=".00_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href=".00_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href=".00_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href=".00_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href=".00_files/libs/revealjs/plugin/verticator/verticator.css" rel="stylesheet">
  <link href=".00_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
  
  <script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-iframe=".00_files/libs/colored-particles/index.html" class="quarto-title-block center">
  <h1 class="title">Регресійний аналіз у прикладній статистиці</h1>
  <p class="subtitle">Прикладний статистичний аналіз</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Ігор Мірошниченко 
</div>
        <p class="quarto-title-affiliation">
            КНУ імені Тараса Шевченка | ФІТ
          </p>
    </div>
</div>

</section><section id="TOC">
<nav role="doc-toc"> 
<h2 id="toc-title">Зміст</h2>
<ul>
<li><a href="#/кореляція" id="/toc-кореляція">Кореляція</a></li>
<li><a href="#/генеральна-сукупність-та-вибірка-у-задачі-регресії" id="/toc-генеральна-сукупність-та-вибірка-у-задачі-регресії">Генеральна сукупність та вибірка у задачі регресії</a></li>
<li><a href="#/оцінювання-параметрів-регресії" id="/toc-оцінювання-параметрів-регресії">Оцінювання параметрів регресії</a></li>
<li><a href="#/мнк-властивості-та-припущення" id="/toc-мнк-властивості-та-припущення">МНК: властивості та припущення</a></li>
<li><a href="#/невизначеність-та-помилки" id="/toc-невизначеність-та-помилки">Невизначеність та помилки</a></li>
<li><a href="#/довірчі-інтервали" id="/toc-довірчі-інтервали">Довірчі інтервали</a></li>
<li><a href="#/тестування-гіпотез" id="/toc-тестування-гіпотез">Тестування гіпотез</a></li>
<li><a href="#/оцінювання-моделі" id="/toc-оцінювання-моделі">Оцінювання моделі</a></li>
<li><a href="#/інтерпретація-коефіцієнтів" id="/toc-інтерпретація-коефіцієнтів">Інтерпретація коефіцієнтів</a></li>
</ul>
</nav>
</section>
<section id="правила-поведінки-при-сигналі-повітряна-тривога" class="title-slide slide level1 unnumbered unlisted smaller center" data-background-color="#eef3f8">
<h1>🚨Правила поведінки при сигналі “повітряна тривога”</h1>
<ol type="1">
<li>При отриманні сигналу “повітряна тривога” в місті Києві лекція буде призупинена, а студенти мають перейти до укриття. Після отримання сигналу “відбій повітряної тривоги” лекція продовжиться 📢</li>
<li>При отриманні сигнали “повітряна тривога” в інших регіонах України студенти мають від’єднатися від лекційного заняття та перейти до укриття за місцем перебування. Після отримання сигналу “відбій повітряної тривоги” студенти мають повернутися до навчання⚠️</li>
</ol>
</section>

<section>
<section id="кореляція" class="title-slide slide level1 center" data-background-color="#eef3f8">
<h1>Кореляція</h1>

</section>
<section id="поняття-кореляції" class="slide level2">
<h2>Поняття кореляції</h2>
<p><span class="hi">Коефіцієнт кореляції</span> у своєму статистичному сенсі позначає силу і характер <span class="hi-purple">взаємозв’язку</span> між двома кількісними змінними.</p>
<div id="cell-corr-1" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Код</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Set a random seed for reproducibility</span></span>
<span id="cb1-2"><a href="" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb1-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to generate datasets with specified correlation</span></span>
<span id="cb1-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> generate_dataset(correlation):</span>
<span id="cb1-6"><a href="" aria-hidden="true" tabindex="-1"></a>    mean <span class="op">=</span> [<span class="dv">0</span>, <span class="dv">0</span>]</span>
<span id="cb1-7"><a href="" aria-hidden="true" tabindex="-1"></a>    cov_matrix <span class="op">=</span> [[<span class="dv">1</span>, correlation], [correlation, <span class="dv">1</span>]]</span>
<span id="cb1-8"><a href="" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-9"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Generate random data with the specified correlation</span></span>
<span id="cb1-10"><a href="" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> np.random.multivariate_normal(mean, cov_matrix, <span class="dv">100</span>)</span>
<span id="cb1-11"><a href="" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-12"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create a DataFrame</span></span>
<span id="cb1-13"><a href="" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> pd.DataFrame(data, columns<span class="op">=</span>[<span class="st">'x'</span>, <span class="st">'y'</span>])</span>
<span id="cb1-14"><a href="" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-15"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df</span>
<span id="cb1-16"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate datasets with positive, negative, and no correlation</span></span>
<span id="cb1-18"><a href="" aria-hidden="true" tabindex="-1"></a>positive_corr_data <span class="op">=</span> generate_dataset(<span class="fl">0.8</span>)</span>
<span id="cb1-19"><a href="" aria-hidden="true" tabindex="-1"></a>negative_corr_data <span class="op">=</span> generate_dataset(<span class="op">-</span><span class="fl">0.8</span>)</span>
<span id="cb1-20"><a href="" aria-hidden="true" tabindex="-1"></a>no_corr_data <span class="op">=</span> generate_dataset(<span class="dv">0</span>)</span>
<span id="cb1-21"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the datasets with regression lines</span></span>
<span id="cb1-23"><a href="" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">4</span>))</span>
<span id="cb1-24"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Positive Correlation</span></span>
<span id="cb1-26"><a href="" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">131</span>)</span>
<span id="cb1-27"><a href="" aria-hidden="true" tabindex="-1"></a>sns.regplot(x<span class="op">=</span><span class="st">'x'</span>, y<span class="op">=</span><span class="st">'y'</span>, data<span class="op">=</span>positive_corr_data, color<span class="op">=</span><span class="st">'blue'</span>, ci<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb1-28"><a href="" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Позитивна кореляція'</span>)</span>
<span id="cb1-29"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Negative Correlation</span></span>
<span id="cb1-31"><a href="" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">132</span>)</span>
<span id="cb1-32"><a href="" aria-hidden="true" tabindex="-1"></a>sns.regplot(x<span class="op">=</span><span class="st">'x'</span>, y<span class="op">=</span><span class="st">'y'</span>, data<span class="op">=</span>negative_corr_data, color<span class="op">=</span><span class="st">'red'</span>, ci<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb1-33"><a href="" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Негативна кореляція'</span>)</span>
<span id="cb1-34"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># No Correlation</span></span>
<span id="cb1-36"><a href="" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">133</span>)</span>
<span id="cb1-37"><a href="" aria-hidden="true" tabindex="-1"></a>sns.regplot(x<span class="op">=</span><span class="st">'x'</span>, y<span class="op">=</span><span class="st">'y'</span>, data<span class="op">=</span>no_corr_data, color<span class="op">=</span><span class="st">'green'</span>, ci<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb1-38"><a href="" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Відсутня кореляція'</span>)</span>
<span id="cb1-39"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb1-41"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src=".00_files/figure-revealjs/corr-1-output-1.svg" id="corr-1" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="коваріація" class="slide level2 smaller">
<h2>Коваріація</h2>
<p><span class="hi">Коваріація</span> - це міра взаємозв’язку між двома змінними, яка визначається як очікуване значення добутку відхилень від середніх значень.</p>
<p>Припустимо, нам потрібно розрахувати коефіцієнт кореляції для двох кількісних величин <span class="math inline">\(X\)</span> і <span class="math inline">\(Y\)</span>. Відповідно, середнє за вибіркою для кожної з цих величин буде <span class="math inline">\(\bar{X}\)</span> і <span class="math inline">\(\bar{Y}\)</span>. Тоді коефіцієнт коваріації:</p>
<p><span class="math display">\[ \text{cov}(X, Y) = \frac{\sum_{i=1}^{n} (X_i - \bar{X})(Y_i - \bar{Y})}{N-1}  \]</span></p>
<p>де <span class="math inline">\(N\)</span> — кількість спостережень у вибірці;<br> <span class="math inline">\(X_i\)</span> — значення <span class="math inline">\(X\)</span> для <span class="math inline">\(i\)</span>-го спостереження;<br> <span class="math inline">\(Y_i\)</span> — значення <span class="math inline">\(Y\)</span> для <span class="math inline">\(i\)</span>-го спостереження;</p>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Коваріація змінюється в довільному розкиді значень <span class="math inline">\(\rightarrow\)</span> складно інтерпретувати силу взаємозв’язку.</p>
</div>
</div>
</div>
</section>
<section id="кореляція-1" class="slide level2 smaller">
<h2>Кореляція</h2>
<p><span class="hi">Кореляція</span> - це нормалізована міра взаємозв’язку між двома змінними.</p>
<p><span class="math display">\[ \text{corr}(X, Y) = \frac{\text{cov}(X, Y)}{\sigma_X \sigma_Y} \]</span></p>
<p>де <span class="math inline">\(\sigma_X\)</span> - стандартне відхилення <span class="math inline">\(X\)</span>;<br> <span class="math inline">\(\sigma_Y\)</span> - стандартне відхилення <span class="math inline">\(Y\)</span>.</p>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Коефіцієнт кореляції завжди лежить в діапазоні <span class="math inline">\([-1, 1]\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="кореляція-2" class="slide level2">
<h2>Кореляція</h2>
<p>Іноді можна зустріти таку формулу для коефіцієнта кореляції:</p>
<p><span class="math display">\[
r_{xy} = \frac{\sum{(x_i - \bar{x})(y_i - \bar{y})}}{\sqrt{\sum{(x_i - \bar{x})^2} \sum{(y_i - \bar{y})^2}}}
\]</span></p>
<p>У підручниках зі статистики часто зустрічається термін <span class="hi">кореляційний коефіцієнт Пірсона</span>, який є частковим випадком коефіцієнта кореляції.</p>
<div class="footer">
<p>Додаток, де можна погратися з кореляцією: 🔗<a href="https://rpsychologist.com/correlation/">Interpreting Correlations</a></p>
</div>
</section>
<section id="перевірка-гіпотези-про-кореляцію" class="slide level2 smaller">
<h2>Перевірка гіпотези про кореляцію</h2>
<p><span class="math display">\[
H_0: r = 0
\]</span></p>
<p><span class="math display">\[
H_1: r \neq 0
\]</span></p>
<p>Статистика критерію:</p>
<p><span class="math display">\[
t = \frac{r \sqrt{n-2}}{\sqrt{1 - r^2}} \sim t_{n-2}
\]</span></p>
<p>де <span class="math inline">\(r\)</span> — коефіцієнт кореляції Пірсона;<br> <span class="math inline">\(n\)</span> — кількість спостережень у вибірці.</p>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Критичне значення критерію Стьюдента для рівня значущості <span class="math inline">\(\alpha = 0.05\)</span> і <span class="math inline">\(n-2\)</span> ступенів свободи: <span class="math inline">\(t_{\alpha/2, n-2} = 2.045\)</span></p>
<p>Якщо <span class="math inline">\(|t| &gt; t_{\alpha/2, n-2}\)</span>, то нульову гіпотезу відхиляють.</p>
</div>
</div>
</div>
</section>
<section id="умови-застосування-критерію-стьюдента" class="slide level2 smaller">
<h2>Умови застосування критерію Стьюдента</h2>
<ol type="1">
<li>Взаємозв’язок між змінними має бути <strong>лінійним</strong> і <strong>монотонним</strong>.</li>
<li>Відсутність <strong>викидів</strong></li>
<li><strong>Нормальний розподіл</strong> змінних</li>
</ol>
<p>У разі порушення цих припущень можуть бути корисними коефіцієнти кореляції Спірмена й Кендалла, які замість реальних значень аналізують їхні ранги.</p>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Ні те, ні інше не є панацеєю, і за особливо сильних порушень припущень (особливо першого) вони також можуть бути неадекватними. Уважно вивчайте свої дані та їхній характер!</p>
</div>
</div>
</div>
</section>
<section id="порівняння-коефіцієнтів-кореляції" class="slide level2 smaller">
<h2>Порівняння коефіцієнтів кореляції</h2>
<div id="cell-corr-compare" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Код</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> pearsonr, spearmanr</span>
<span id="cb2-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> show_correlation(ax, x, y, title):</span>
<span id="cb2-6"><a href="" aria-hidden="true" tabindex="-1"></a>    pearson_corr, _ <span class="op">=</span> pearsonr(x, y)</span>
<span id="cb2-7"><a href="" aria-hidden="true" tabindex="-1"></a>    spearman_corr, _ <span class="op">=</span> spearmanr(x, y)</span>
<span id="cb2-8"><a href="" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-9"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.scatter(x, y, color<span class="op">=</span><span class="st">"teal"</span>, edgecolor<span class="op">=</span><span class="st">"k"</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb2-10"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.set_title(</span>
<span id="cb2-11"><a href="" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>title<span class="sc">}</span><span class="ch">\n</span><span class="ss">Пірсон: </span><span class="sc">{</span>pearson_corr<span class="sc">:.2f}</span><span class="ss">, Спірмен: </span><span class="sc">{</span>spearman_corr<span class="sc">:.2f}</span><span class="ss">"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb2-12"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"X"</span>)</span>
<span id="cb2-13"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">"Y"</span>)</span>
<span id="cb2-14"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>)</span>
<span id="cb2-15"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Створимо графіки</span></span>
<span id="cb2-17"><a href="" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">18</span>, <span class="dv">5</span>))</span>
<span id="cb2-18"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Лінійна залежність</span></span>
<span id="cb2-20"><a href="" aria-hidden="true" tabindex="-1"></a>x1 <span class="op">=</span> np.linspace(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">100</span>)</span>
<span id="cb2-21"><a href="" aria-hidden="true" tabindex="-1"></a>y1 <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> x1 <span class="op">+</span> np.random.normal(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">100</span>)</span>
<span id="cb2-22"><a href="" aria-hidden="true" tabindex="-1"></a>show_correlation(axes[<span class="dv">0</span>], x1, y1, <span class="st">"Лінійна залежність"</span>)</span>
<span id="cb2-23"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Нелінійна, але монотонна (логарифмічна)</span></span>
<span id="cb2-25"><a href="" aria-hidden="true" tabindex="-1"></a>x2 <span class="op">=</span> np.linspace(<span class="dv">1</span>, <span class="dv">100</span>, <span class="dv">100</span>)</span>
<span id="cb2-26"><a href="" aria-hidden="true" tabindex="-1"></a>y2 <span class="op">=</span> np.log(x2) <span class="op">+</span> np.random.normal(<span class="dv">0</span>, <span class="fl">0.2</span>, <span class="dv">100</span>)</span>
<span id="cb2-27"><a href="" aria-hidden="true" tabindex="-1"></a>show_correlation(axes[<span class="dv">1</span>], x2, y2, <span class="st">"Монотонна нелінійна залежність"</span>)</span>
<span id="cb2-28"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-29"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Нелінійна і немонотонна (синус)</span></span>
<span id="cb2-30"><a href="" aria-hidden="true" tabindex="-1"></a>x3 <span class="op">=</span> np.linspace(<span class="dv">0</span>, <span class="dv">4</span> <span class="op">*</span> np.pi, <span class="dv">100</span>)</span>
<span id="cb2-31"><a href="" aria-hidden="true" tabindex="-1"></a>y3 <span class="op">=</span> np.sin(x3)</span>
<span id="cb2-32"><a href="" aria-hidden="true" tabindex="-1"></a>show_correlation(axes[<span class="dv">2</span>], x3, y3, <span class="st">"Немонотонна нелінійна залежність"</span>)</span>
<span id="cb2-33"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-34"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout(rect<span class="op">=</span>[<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.95</span>])</span>
<span id="cb2-35"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src=".00_files/figure-revealjs/corr-compare-output-1.svg" id="corr-compare" class="r-stretch"></section>
<section id="квартер-енскомба" class="slide level2 tiny">
<h2>Квартер Енскомба</h2>
<p>Один із класичних прикладів необхідності перевірки припущень (і візуалізації даних перед аналізом) - <span class="hi">квартет Енскомба</span>.</p>
<p>У всіх чотирьох наборів даних однаковий коефіцієнт кореляції Пірсона, хоча їхній характер очевидно різний.</p>
<div id="cell-anscombe" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Код</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the data</span></span>
<span id="cb3-2"><a href="" aria-hidden="true" tabindex="-1"></a>anscombe <span class="op">=</span> sns.load_dataset(<span class="st">'anscombe'</span>)</span>
<span id="cb3-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">4</span>))</span>
<span id="cb3-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># First dataset</span></span>
<span id="cb3-7"><a href="" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">141</span>)</span>
<span id="cb3-8"><a href="" aria-hidden="true" tabindex="-1"></a>sns.regplot(x<span class="op">=</span><span class="st">'x'</span>, y<span class="op">=</span><span class="st">'y'</span>, data<span class="op">=</span>anscombe.loc[anscombe[<span class="st">'dataset'</span>] <span class="op">==</span> <span class="st">'I'</span>], color<span class="op">=</span><span class="st">'#447099'</span>, ci<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb3-9"><a href="" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Набір даних I'</span>)</span>
<span id="cb3-10"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Second dataset</span></span>
<span id="cb3-12"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">142</span>)</span>
<span id="cb3-14"><a href="" aria-hidden="true" tabindex="-1"></a>sns.regplot(x<span class="op">=</span><span class="st">'x'</span>, y<span class="op">=</span><span class="st">'y'</span>, data<span class="op">=</span>anscombe.loc[anscombe[<span class="st">'dataset'</span>] <span class="op">==</span> <span class="st">'II'</span>], color<span class="op">=</span><span class="st">'#C10000'</span>, ci<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb3-15"><a href="" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Набір даних II'</span>)</span>
<span id="cb3-16"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Third dataset</span></span>
<span id="cb3-18"><a href="" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">143</span>)</span>
<span id="cb3-19"><a href="" aria-hidden="true" tabindex="-1"></a>sns.regplot(x<span class="op">=</span><span class="st">'x'</span>, y<span class="op">=</span><span class="st">'y'</span>, data<span class="op">=</span>anscombe.loc[anscombe[<span class="st">'dataset'</span>] <span class="op">==</span> <span class="st">'III'</span>], color<span class="op">=</span><span class="st">'#00891A'</span>, ci<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb3-20"><a href="" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Набір даних III'</span>)</span>
<span id="cb3-21"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Fourth dataset</span></span>
<span id="cb3-23"><a href="" aria-hidden="true" tabindex="-1"></a>plt.subplot(<span class="dv">144</span>)</span>
<span id="cb3-24"><a href="" aria-hidden="true" tabindex="-1"></a>sns.regplot(x<span class="op">=</span><span class="st">'x'</span>, y<span class="op">=</span><span class="st">'y'</span>, data<span class="op">=</span>anscombe.loc[anscombe[<span class="st">'dataset'</span>] <span class="op">==</span> <span class="st">'IV'</span>], color<span class="op">=</span><span class="st">'#f45100'</span>, ci<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb3-25"><a href="" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Набір даних IV'</span>)</span>
<span id="cb3-26"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-27"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb3-28"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src=".00_files/figure-revealjs/anscombe-output-1.svg" id="anscombe" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="datasaurus-dozen" class="slide level2 smaller">
<h2>Datasaurus Dozen</h2>
<p>Ще один класичний приклад - <span class="hi">Datasaurus Dozen</span>.</p>
<p>У всіх даних однаковий коефіцієнт кореляції Пірсона, хоча їхній характер очевидно різний.</p>

<img data-src=".00_files/figure-revealjs/datasaurus-output-1.svg" id="datasaurus" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="кореляція-в-python" class="slide level2 tiny">
<h2>Кореляція в Python</h2>
<div id="tbl-vgsales" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="" aria-hidden="true" tabindex="-1"></a>vgsales <span class="op">=</span> pd.read_csv(<span class="st">"https://raw.githubusercontent.com/Aranaur/aranaur.rbind.io/main/datasets/video_games_sales/vgsales.csv"</span>)</span>
<span id="cb4-2"><a href="" aria-hidden="true" tabindex="-1"></a>vgsales.head()</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Rank</th>
<th data-quarto-table-cell-role="th">Name</th>
<th data-quarto-table-cell-role="th">Platform</th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Genre</th>
<th data-quarto-table-cell-role="th">Publisher</th>
<th data-quarto-table-cell-role="th">NA_Sales</th>
<th data-quarto-table-cell-role="th">EU_Sales</th>
<th data-quarto-table-cell-role="th">JP_Sales</th>
<th data-quarto-table-cell-role="th">Other_Sales</th>
<th data-quarto-table-cell-role="th">Global_Sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>Wii Sports</td>
<td>Wii</td>
<td>2006.0</td>
<td>Sports</td>
<td>Nintendo</td>
<td>41.49</td>
<td>29.02</td>
<td>3.77</td>
<td>8.46</td>
<td>82.74</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>Super Mario Bros.</td>
<td>NES</td>
<td>1985.0</td>
<td>Platform</td>
<td>Nintendo</td>
<td>29.08</td>
<td>3.58</td>
<td>6.81</td>
<td>0.77</td>
<td>40.24</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>Mario Kart Wii</td>
<td>Wii</td>
<td>2008.0</td>
<td>Racing</td>
<td>Nintendo</td>
<td>15.85</td>
<td>12.88</td>
<td>3.79</td>
<td>3.31</td>
<td>35.82</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>Wii Sports Resort</td>
<td>Wii</td>
<td>2009.0</td>
<td>Sports</td>
<td>Nintendo</td>
<td>15.75</td>
<td>11.01</td>
<td>3.28</td>
<td>2.96</td>
<td>33.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5</td>
<td>Pokemon Red/Pokemon Blue</td>
<td>GB</td>
<td>1996.0</td>
<td>Role-Playing</td>
<td>Nintendo</td>
<td>11.27</td>
<td>8.89</td>
<td>10.22</td>
<td>1.00</td>
<td>31.37</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">NumPy</a></li><li><a href="#tabset-1-2">SciPy</a></li><li><a href="#tabset-1-3">Pandas</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<div id="corr-np" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb5-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="" aria-hidden="true" tabindex="-1"></a>np_corr_p <span class="op">=</span> np.corrcoef(vgsales[<span class="st">'NA_Sales'</span>], vgsales[<span class="st">'Global_Sales'</span>])[<span class="dv">0</span>, <span class="dv">1</span>]</span>
<span id="cb5-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Коефіцієнт кореляції: </span><span class="sc">{</span>np_corr_p<span class="sc">:.3f}</span><span class="ss">'</span>)</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Коефіцієнт кореляції: 0.941</code></pre>
</div>
</div>
</div>
<div id="tabset-1-2">
<div id="corr-scipy" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> st</span>
<span id="cb7-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="" aria-hidden="true" tabindex="-1"></a>st_corr_p <span class="op">=</span> st.pearsonr(vgsales[<span class="st">'NA_Sales'</span>], vgsales[<span class="st">'Global_Sales'</span>])</span>
<span id="cb7-4"><a href="" aria-hidden="true" tabindex="-1"></a>st_corr_s <span class="op">=</span> st.spearmanr(vgsales[<span class="st">'NA_Sales'</span>], vgsales[<span class="st">'Global_Sales'</span>])</span>
<span id="cb7-5"><a href="" aria-hidden="true" tabindex="-1"></a>st_corr_k <span class="op">=</span> st.kendalltau(vgsales[<span class="st">'NA_Sales'</span>], vgsales[<span class="st">'Global_Sales'</span>])</span>
<span id="cb7-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Коефіцієнт кореляції Пірсона: </span><span class="sc">{</span>st_corr_p[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss"> (p-value: </span><span class="sc">{</span>st_corr_p[<span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb7-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Коефіцієнт кореляції Спірмена: </span><span class="sc">{</span>st_corr_s[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss"> (p-value: </span><span class="sc">{</span>st_corr_s[<span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb7-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Коефіцієнт кореляції Кендалла: </span><span class="sc">{</span>st_corr_k[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss"> (p-value: </span><span class="sc">{</span>st_corr_k[<span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">)'</span>)</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Коефіцієнт кореляції Пірсона: 0.941 (p-value: 0.000)
Коефіцієнт кореляції Спірмена: 0.796 (p-value: 0.000)
Коефіцієнт кореляції Кендалла: 0.676 (p-value: 0.000)</code></pre>
</div>
</div>
</div>
<div id="tabset-1-3">
<div id="corr-pandas" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb9-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="" aria-hidden="true" tabindex="-1"></a>pd_corr_p <span class="op">=</span> vgsales[[<span class="st">'NA_Sales'</span>, <span class="st">'Global_Sales'</span>]].corr(method<span class="op">=</span><span class="st">'pearson'</span>).iloc[<span class="dv">0</span>, <span class="dv">1</span>]</span>
<span id="cb9-4"><a href="" aria-hidden="true" tabindex="-1"></a>pd_corr_s <span class="op">=</span> vgsales[[<span class="st">'NA_Sales'</span>, <span class="st">'Global_Sales'</span>]].corr(method<span class="op">=</span><span class="st">'spearman'</span>).iloc[<span class="dv">0</span>, <span class="dv">1</span>]</span>
<span id="cb9-5"><a href="" aria-hidden="true" tabindex="-1"></a>pd_corr_k <span class="op">=</span> vgsales[[<span class="st">'NA_Sales'</span>, <span class="st">'Global_Sales'</span>]].corr(method<span class="op">=</span><span class="st">'kendall'</span>).iloc[<span class="dv">0</span>, <span class="dv">1</span>]</span>
<span id="cb9-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Коефіцієнт кореляції Пірсона: </span><span class="sc">{</span>pd_corr_p<span class="sc">:.3f}</span><span class="ss">'</span>)</span>
<span id="cb9-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Коефіцієнт кореляції Спірмена: </span><span class="sc">{</span>pd_corr_s<span class="sc">:.3f}</span><span class="ss">'</span>)</span>
<span id="cb9-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Коефіцієнт кореляції Кендалла: </span><span class="sc">{</span>pd_corr_k<span class="sc">:.3f}</span><span class="ss">'</span>)</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Коефіцієнт кореляції Пірсона: 0.941
Коефіцієнт кореляції Спірмена: 0.796
Коефіцієнт кореляції Кендалла: 0.676</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="maximal-information-based-nonparametric-exploration" class="slide level2 tiny">
<h2>Maximal Information-based Nonparametric Exploration</h2>
<p><span class="hi">MINE</span> — це алгоритм, який використовується для виявлення нелінійних залежностей між змінними.</p>

<img data-src="img/mic.jpg" class="quarto-figure quarto-figure-center r-stretch"><div class="footer">
<p>🔗<a href="https://minepy.readthedocs.io/en/latest/">minepy - Maximal Information-based Nonparametric Exploration</a></p>
</div>
</section>
<section id="хибні-кореляції" class="slide level2">
<h2>Хибні кореляції</h2>
<p><a href="https://www.tylervigen.com/spurious-correlations">Spurious Correlations</a></p>

<img data-src="img/spurious.png" class="quarto-figure quarto-figure-center r-stretch"></section></section>
<section>
<section id="генеральна-сукупність-та-вибірка-у-задачі-регресії" class="title-slide slide level1 center" data-background-color="#eef3f8">
<h1>Генеральна сукупність та вибірка у задачі регресії</h1>

</section>
<section id="генеральна-сукупність-і-вибірка" class="slide level2 smaller">
<h2>Генеральна сукупність і вибірка</h2>
<p><span class="hi">Генеральна сукупність</span> - це сукупність всіх об’єктів, які ми вивчаємо.</p>
<p><span class="purple">Вибірка</span> - це підмножина генеральної сукупності, яка використовується для отримання інформації про генеральну сукупність.</p>
<p>Ми запишемо <span class="hi">просту</span> модель генеральної сукупності</p>
<p><span class="math display">\[ y_i = \beta_0 + \beta_1 x_i + u_i \]</span></p>
<p>де <span class="math inline">\(y_i\)</span> - залежна змінна;<br> <span class="math inline">\(x_i\)</span> - незалежна змінна;<br> <span class="math inline">\(\beta_0, \beta_1\)</span> — параметри моделі;<br> <span class="math inline">\(u_i\)</span> — випадкові збурення.</p>
<p>Тоді наша <span class="purple">модель регресії</span> на основі вибірки:</p>
<p><span class="math display">\[
y_i = \hat{\beta}_0 + \hat{\beta}_1 x_i + e_i
\]</span></p>
<p>де <span class="math inline">\(e_i\)</span> — залишки моделі.</p>
</section>
<section id="генеральна-сукупність-і-вибірка-1" class="slide level2 smaller">
<h2>Генеральна сукупність і вибірка</h2>
<p>Розрахункова регресійна модель дає <span class="purple">оцінки</span> для кожного спостереження:</p>
<p><span class="math display">\[ \hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1 x_i \]</span></p>
<p>де <span class="math inline">\(\hat{y}_i\)</span> — прогнозоване значення залежної змінної.</p>
<p>що дає нам <em>найкращу</em> лінію в нашому наборі даних.</p>
</section>
<section id="генеральна-сукупність-і-вибірка-2" class="slide level2 tiny">
<h2>Генеральна сукупність і вибірка</h2>
<p><strong>Питання:</strong> Чому ми співставляємо <em>генеральну сукупність і вибірку</em>?</p>
<div class="fragment">
<div class="columns">
<div class="column">
<div id="cell-pop1" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src=".00_files/figure-revealjs/pop1-output-1.svg" id="pop1"></p>
</figure>
</div>
</div>
</div>
<p><strong>Генеральна сукупність</strong></p>
</div><div class="column">
<div id="cell-scatter1" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src=".00_files/figure-revealjs/scatter1-output-1.svg" id="scatter1" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
</div>
<p><strong>Зв’язок у генеральній сукупності</strong></p>
<div id="cell-formula1" class="cell" data-execution_count="13">
<div id="formula1" class="cell-output cell-output-display cell-output-markdown" data-execution_count="13">
<p><span class="math display">\[ y_i = 0.05 + 0.72 x_i + u_i \]</span> <span class="math display">\[ y_i = \beta_0 + \beta_1 x_i + u_i \]</span></p>
</div>
</div>
</div></div>
</div>
</section>
<section id="генеральна-сукупність-і-вибірка-3" class="slide level2 tiny">
<h2>Генеральна сукупність і вибірка</h2>
<p><strong>Питання:</strong> Чому ми співставляємо <em>генеральну сукупність і вибірку</em>?</p>
<div class="columns">
<div class="column">
<div id="cell-sample1" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src=".00_files/figure-revealjs/sample1-output-1.svg" id="sample1"></p>
</figure>
</div>
</div>
</div>
<p><strong>Генеральна сукупність</strong></p>
</div><div class="column">
<div id="cell-sample1-scatter" class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src=".00_files/figure-revealjs/sample1-scatter-output-1.svg" id="sample1-scatter"></p>
</figure>
</div>
</div>
</div>
<p><strong>Зв’язок у генеральній сукупності</strong></p>
<div id="cell-formula2" class="cell" data-execution_count="16">
<div id="formula2" class="cell-output cell-output-display cell-output-markdown" data-execution_count="16">
<p><span class="math display">\[ y_i = 0.05 + 0.72 x_i + u_i \]</span></p>
</div>
</div>
<p><strong>Зв’язок у вибірці</strong></p>
<div id="cell-formula3" class="cell" data-execution_count="17">
<div id="formula3" class="cell-output cell-output-display cell-output-markdown" data-execution_count="17">
<p><span class="math display">\[ \hat{y_i} = 0.18 + 0.73 x_i \]</span></p>
</div>
</div>
</div></div>
</section>
<section id="генеральна-сукупність-і-вибірка-4" class="slide level2 tiny">
<h2>Генеральна сукупність і вибірка</h2>
<p><strong>Питання:</strong> Чому ми співставляємо <em>генеральну сукупність і вибірку</em>?</p>
<div class="columns">
<div class="column">
<div id="cell-sample2" class="cell" data-execution_count="18">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src=".00_files/figure-revealjs/sample2-output-1.svg" id="sample2"></p>
</figure>
</div>
</div>
</div>
<p><strong>Генеральна сукупність</strong></p>
</div><div class="column">
<div id="cell-sample2-scatter" class="cell" data-execution_count="19">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src=".00_files/figure-revealjs/sample2-scatter-output-1.svg" id="sample2-scatter"></p>
</figure>
</div>
</div>
</div>
<p><strong>Зв’язок у генеральній сукупності</strong></p>
<div id="cell-formula4" class="cell" data-execution_count="20">
<div id="formula4" class="cell-output cell-output-display cell-output-markdown" data-execution_count="20">
<p><span class="math display">\[ y_i = 0.05 + 0.72 x_i + u_i \]</span></p>
</div>
</div>
<p><strong>Зв’язок у вибірці</strong></p>
<div id="cell-formula5" class="cell" data-execution_count="21">
<div id="formula5" class="cell-output cell-output-display cell-output-markdown" data-execution_count="21">
<p><span class="math display">\[ \hat{y_i} = 0.05 + 0.76 x_i \]</span></p>
</div>
</div>
</div></div>
</section>
<section id="генеральна-сукупність-і-вибірка-5" class="slide level2 tiny">
<h2>Генеральна сукупність і вибірка</h2>
<p><strong>Питання:</strong> Чому ми співставляємо <em>генеральну сукупність і вибірку</em>?</p>
<div class="columns">
<div class="column">
<div id="cell-sample3" class="cell" data-execution_count="22">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src=".00_files/figure-revealjs/sample3-output-1.svg" id="sample3"></p>
</figure>
</div>
</div>
</div>
<p><strong>Генеральна сукупність</strong></p>
</div><div class="column">
<div id="cell-sample3-scatter" class="cell" data-execution_count="23">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src=".00_files/figure-revealjs/sample3-scatter-output-1.svg" id="sample3-scatter"></p>
</figure>
</div>
</div>
</div>
<p><strong>Зв’язок у генеральній сукупності</strong></p>
<div id="cell-formula6" class="cell" data-execution_count="24">
<div id="formula6" class="cell-output cell-output-display cell-output-markdown" data-execution_count="24">
<p><span class="math display">\[ y_i = 0.05 + 0.72 x_i + u_i \]</span></p>
</div>
</div>
<p><strong>Зв’язок у вибірці</strong></p>
<div id="cell-formula7" class="cell" data-execution_count="25">
<div id="formula7" class="cell-output cell-output-display cell-output-markdown" data-execution_count="25">
<p><span class="math display">\[ \hat{y_i} = 0.0 + 0.78 x_i \]</span></p>
</div>
</div>
</div></div>
</section>
<section class="slide level2">

<p><br><br><br> Давайте повторимо це <strong>10 000 разів</strong> (Монте-Карло).</p>
<div id="gen-dataset-2" class="cell" data-execution_count="26">
<details class="code-fold">
<summary>Генерація датасету</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">12468</span>)</span>
<span id="cb11-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit_linear_regression(size):</span>
<span id="cb11-4"><a href="" aria-hidden="true" tabindex="-1"></a>    sampled_data <span class="op">=</span> pop_df.sample(n<span class="op">=</span>size)</span>
<span id="cb11-5"><a href="" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> sm.OLS(sampled_data[<span class="st">'y'</span>], sm.add_constant(sampled_data[<span class="st">'x'</span>])).fit()</span>
<span id="cb11-6"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model.params</span>
<span id="cb11-7"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="" aria-hidden="true" tabindex="-1"></a>sim_results <span class="op">=</span> [fit_linear_regression(size<span class="op">=</span>n_s) <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">int</span>(<span class="fl">1e4</span>))]</span>
<span id="cb11-9"><a href="" aria-hidden="true" tabindex="-1"></a>sim_df <span class="op">=</span> pd.concat([pd.DataFrame(result) <span class="cf">for</span> result <span class="kw">in</span> sim_results], ignore_index<span class="op">=</span><span class="va">True</span>, axis<span class="op">=</span><span class="dv">1</span>).T</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="генеральна-сукупність-і-вибірка-6" class="slide level2">
<h2>Генеральна сукупність і вибірка</h2>
<div id="cell-gen-dataset-2-plot" class="cell" data-fig-dpi="300" data-execution_count="27">
<details class="code-fold">
<summary>Код</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">4</span>))</span>
<span id="cb12-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> intercept, slope <span class="kw">in</span> <span class="bu">zip</span>(sim_df[<span class="st">'const'</span>], sim_df[<span class="st">'x'</span>]):</span>
<span id="cb12-4"><a href="" aria-hidden="true" tabindex="-1"></a>    plt.axline((<span class="dv">0</span>, intercept), slope<span class="op">=</span>slope, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="fl">0.1</span>, alpha<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb12-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="" aria-hidden="true" tabindex="-1"></a>plt.scatter(pop_df[<span class="st">'x'</span>], pop_df[<span class="st">'y'</span>], color<span class="op">=</span><span class="st">'darkslategray'</span>, s<span class="op">=</span><span class="dv">60</span>)</span>
<span id="cb12-7"><a href="" aria-hidden="true" tabindex="-1"></a>plt.axline((<span class="dv">0</span>, lm0.params[<span class="dv">0</span>]), slope<span class="op">=</span>lm0.params[<span class="dv">1</span>], color<span class="op">=</span>red_pink, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb12-8"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tick_params(axis<span class="op">=</span><span class="st">'both'</span>, labelsize<span class="op">=</span><span class="dv">0</span>, length <span class="op">=</span> <span class="dv">0</span>)</span>
<span id="cb12-9"><a href="" aria-hidden="true" tabindex="-1"></a>plt.box(<span class="va">False</span>)</span>
<span id="cb12-10"><a href="" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">None</span>)</span>
<span id="cb12-11"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src=".00_files/figure-revealjs/gen-dataset-2-plot-output-1.svg" id="gen-dataset-2-plot" class="r-stretch"></section>
<section id="генеральна-сукупність-і-вибірка-7" class="slide level2 smaller">
<h2>Генеральна сукупність і вибірка</h2>
<p><strong>Питання:</strong> Чому ми співставляємо <em>генеральну сукупність і вибірку</em>?</p>
<div class="columns">
<div class="column">
<div id="cell-gen-dataset-2-plot-2" class="cell" data-fig-dpi="300" data-execution_count="28">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src=".00_files/figure-revealjs/gen-dataset-2-plot-2-output-1.svg" id="gen-dataset-2-plot-2"></p>
</figure>
</div>
</div>
</div>
</div><div class="column">
<ul>
<li><p>У <strong>середньому</strong> наші лінії регресії дуже добре відповідають лінії генеральної сукупності</p></li>
<li><p>Однак <strong>окремі лінії</strong> (зразки) можуть промахнутися.</p></li>
<li><p>Відмінності між окремими вибірками та генеральною сукупністю призводять до <strong>невизначеності</strong>.</p></li>
</ul>
</div></div>
</section>
<section id="генеральна-сукупність-і-вибірка-8" class="slide level2 smaller">
<h2>Генеральна сукупність і вибірка</h2>
<p><strong>Питання:</strong> Чому ми співставляємо <em>генеральну сукупність і вибірку</em>?</p>
<p><strong>Відповідь:</strong> Невизначеність має значення.</p>
<ul>
<li><span class="math inline">\(\hat{\beta}\)</span> сама по собі є випадковою змінною, яка залежить від випадкової вибірки.</li>
<li>Коли ми беремо зразок і запускаємо регресію, ми не знаємо, чи це «хороший» зразок (<span class="math inline">\(\hat{\beta}\)</span> близький до <span class="math inline">\(\beta\)</span>) чи «поганий зразок» (наш зразок сильно відрізняється від генеральної сукупності).</li>
</ul>
</section></section>
<section>
<section id="оцінювання-параметрів-регресії" class="title-slide slide level1 center" data-background-color="#eef3f8">
<h1>Оцінювання параметрів регресії</h1>

</section>
<section id="оцінювання-параметрів-регресії-1" class="slide level2 smaller">
<h2>Оцінювання параметрів регресії</h2>
<p>Ми можемо оцінити лінію регресії в Python:</p>
<p><code>lm = sm.OLS(y, sm.add_constant(x)).fit()</code></p>
<p>Але звідки такі оцінки?</p>
<p>Кілька слайдів назад:</p>
<blockquote>
<p><span class="math display">\[ \hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1 x_i \]</span> що дає нам <em>найкращий</em> рядок через наш набір даних.</p>
</blockquote>
<p>Але що ми маємо на увазі під «найкращою лінією»?</p>
</section>
<section id="бути-найкращим" class="slide level2 smaller">
<h2>Бути «найкращим»</h2>
<p><strong>Питання:</strong> Що ми маємо на увазі під <em>найкращою лінією</em>?</p>
<p><strong>Відповіді:</strong></p>
<ul>
<li>Загалом, <em>найкраща лінія</em> означає лінію, яка мінімізує суму квадратичних помилок (ESS):</li>
</ul>
<p><span class="math display">\[ \text{ESS} = \sum_{i = 1}^{n} e_i^2\quad \]</span></p>
<p>де <span class="math inline">\(\quad e_i = y_i - \hat{y}_i\)</span></p>
<ul>
<li>Звичайний метод <strong>найменших квадратів</strong> (<strong>OLS</strong>) мінімізує суму квадратів помилок.</li>
<li>На основі низки (здебільшого прийнятних) припущень, OLS
<ul>
<li>Є незміщенним</li>
<li>Це <em>найкращий</em> (мінімальна дисперсія) лінійний незміщений оцінювач</li>
</ul></li>
</ul>
</section>
<section id="мнк" class="slide level2 smaller">
<h2>МНК</h2>
<p>Давайте розглянемо набір даних, який ми згенерували раніше.</p>

<img data-src=".00_files/figure-revealjs/ols-plot-1-output-1.svg" id="ols-plot-1" class="r-stretch"></section>
<section id="мнк-1" class="slide level2 smaller">
<h2>МНК</h2>
<p>Для будь-якої лінії <span class="math inline">\(\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x\)</span></p>

<img data-src=".00_files/figure-revealjs/ols-plot-2-output-1.svg" id="ols-plot-2" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="мнк-2" class="slide level2 smaller">
<h2>МНК</h2>
<p>Для будь-якої лінії <span class="math inline">\(\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x\)</span> ми можемо обчислити помилки: <span class="math inline">\(e_i = y_i - \hat{y}_i\)</span></p>

<img data-src=".00_files/figure-revealjs/ols-plot-3-output-1.svg" id="ols-plot-3" class="r-stretch"></section>
<section id="мнк-3" class="slide level2 smaller">
<h2>МНК</h2>
<p>Для будь-якої лінії <span class="math inline">\(\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x\)</span> ми можемо обчислити помилки: <span class="math inline">\(e_i = y_i - \hat{y}_i\)</span></p>

<img data-src=".00_files/figure-revealjs/ols-plot-4-output-1.svg" id="ols-plot-4" class="r-stretch"></section>
<section id="мнк-4" class="slide level2 smaller">
<h2>МНК</h2>
<p>Для будь-якої лінії <span class="math inline">\(\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x\)</span> ми можемо обчислити помилки: <span class="math inline">\(e_i = y_i - \hat{y}_i\)</span></p>

<img data-src=".00_files/figure-revealjs/ols-plot-5-output-1.svg" id="ols-plot-5" class="r-stretch"></section>
<section id="мнк-5" class="slide level2 smaller">
<h2>МНК</h2>
<p>ESS зводить помилки в квадрат <span class="math inline">\(\sum e_i^2\)</span>: більші помилки отримують більші штрафи.</p>

<img data-src=".00_files/figure-revealjs/ols-plot-6-output-1.svg" id="ols-plot-6" class="r-stretch"></section>
<section id="мнк-6" class="slide level2 smaller">
<h2>МНК</h2>
<p>Оцінка МНК — це комбінація <span class="math inline">\(\hat{\beta}_0\)</span> і <span class="math inline">\(\hat{\beta}_1\)</span>, які мінімізують ESS.</p>

<img data-src=".00_files/figure-revealjs/ols-plot-7-output-1.svg" id="ols-plot-7" class="r-stretch"></section>
<section id="мнк-7" class="slide level2 smaller">
<h2>МНК</h2>
<p>У простій лінійній регресії оцінювач МНК виходить із вибору <span class="math inline">\(\hat{\beta}_0\)</span> і <span class="math inline">\(\hat{\beta}_1\)</span>, які мінімізують суму квадратів помилок (ESS), <em>тобто</em>,</p>
<p><span class="math display">\[ \min_{\hat{\beta}_0,\, \hat{\beta}_1} \text{ESS} \]</span></p>
<div class="fragment">
<p>але ми вже знаємо <span class="math inline">\(\text{ESS} = \sum_i e_i^2\)</span>. Тепер скористайтеся визначеннями <span class="math inline">\(e_i\)</span> і <span class="math inline">\(\hat{y}\)</span>.</p>
<p><span class="math display">\[
\begin{aligned}
   e_i^2 &amp;= \left( y_i - \hat{y}_i \right)^2 = \left( y_i - \hat{\beta}_0 - \hat{\beta}_1 x_i \right)^2 \\
   &amp;= y_i^2 - 2 y_i \hat{\beta}_0 - 2 y_i \hat{\beta}_1 x_i + \hat{\beta}_0^2 + 2 \hat{\beta}_0 \hat{\beta }_1 x_i + \hat{\beta}_1^2 x_i^2
\end{aligned}
\]</span></p>
</div>
</section>
<section id="мнк-8" class="slide level2 smaller">
<h2>МНК</h2>
<p>Ми наближаємось. Нам потрібно <strong>мінімізувати ESS</strong>. Ми показали, як ESS пов’язано з нашою вибіркою (наші дані: <span class="math inline">\(x\)</span> і <span class="math inline">\(y\)</span>) і нашими оцінками (<em>тобто</em>, <span class="math inline">\(\hat{\beta}_0\)</span> і <span class="math inline">\(\hat{\beta}_1\)</span>).</p>
<p><span class="math display">\[ \text{ESS} = \sum_i e_i^2 = \sum_i \left( y_i^2 - 2 y_i \hat{\beta}_0 - 2 y_i \hat{\beta}_1 x_i + \hat{\beta} _0^2 + 2 \hat{\beta}_0 \hat{\beta}_1 x_i + \hat{\beta}_1^2 x_i^2 \right) \]</span></p>
<p>Для умов мінімізації тепер беремо перші похідні ESS відносно <span class="math inline">\(\hat{\beta}_0\)</span> і <span class="math inline">\(\hat{\beta}_1\)</span>.</p>
<p><span class="math display">\[
\begin{aligned}
   \dfrac{\partial \text{ESS}}{\partial \hat{\beta}_0} &amp;= \sum_i \left( 2 \hat{\beta}_0 + 2 \hat{\beta}_1 x_i - 2 y_i \right) = 2n \hat{\beta}_0 + 2 \hat{\beta}_1 \sum_i x_i - 2 \sum_i y_i \\
   &amp;= 2n \hat{\beta}_0 + 2n \hat{\beta}_1 \overline{x} - 2n \overline{y}
\end{aligned}
\]</span></p>
<p>де <span class="math inline">\(\overline{x} = \frac{\sum x_i}{n}\)</span> і <span class="math inline">\(\overline{y} = \frac{\sum y_i}{n}\)</span> є вибірковими середніми <span class="math inline">\(x\)</span> і <span class="math inline">\(y\)</span> ( розмір <span class="math inline">\(n\)</span>).</p>
</section>
<section id="мнк-9" class="slide level2 smaller">
<h2>МНК</h2>
<p>Прирівнюємо похідну до нуля:</p>
<p><span class="math display">\[ \dfrac{\partial \text{ESS}}{\partial \hat{\beta}_0} = 2n \hat{\beta}_0 + 2n \hat{\beta}_1 \overline{x} - 2n \overline{y} = 0 \]</span></p>
<p>що означає</p>
<div class="recap">
<p><span class="math display">\[ \hat{\beta}_0 = \overline{y} - \hat{\beta}_1 \overline{x} \]</span></p>
</div>
<p>Тепер про <span class="math inline">\(\hat{\beta}_1\)</span>…</p>
</section>
<section id="мнк-10" class="slide level2 smaller">
<h2>МНК</h2>
<p>Візьміть похідну ESS відносно <span class="math inline">\(\hat{\beta}_1\)</span></p>
<p><span class="math display">\[
\begin{aligned}
   \dfrac{\partial \text{ESS}}{\partial \hat{\beta}_1} &amp;= \sum_i \left( 2 \hat{\beta}_0 x_i + 2 \hat{\beta}_1 x_i^2 - 2 y_i x_i \right) = 2 \hat{\beta}_0 \sum_i x_i + 2 \hat{\beta}_1 \sum_i x_i^2 - 2 \sum_i y_i x_i \\
   &amp;= 2n \hat{\beta}_0 \overline{x} + 2 \hat{\beta}_1 \sum_i x_i^2 - 2 \sum_i y_i x_i
\end{aligned}
\]</span></p>
<p>встановити його рівним нулю</p>
<p><span class="math display">\[ \dfrac{\partial \text{ESS}}{\partial \hat{\beta}_1} = 2n \hat{\beta}_0 \overline{x} + 2 \hat{\beta}_1 \sum_i x_i ^2 - 2 \sum_i y_i x_i = 0 \]</span></p>
<p>замінюємо <span class="math inline">\(\hat{\beta}_0\)</span>, <em>тобто</em>, <span class="math inline">\(\hat{\beta}_0 = \overline{y} - \hat{\beta}_1 \overline{x}\)</span> . Таким чином,</p>
<p><span class="math display">\[
  2n \left(\overline{y} - \hat{\beta}_1 \overline{x}\right) \overline{x} + 2 \hat{\beta}_1 \sum_i x_i^2 - 2 \sum_i y_i x_i = 0
\]</span></p>
</section>
<section id="мнк-11" class="slide level2 smaller">
<h2>МНК</h2>
<p>Продовжуючи з останнього слайда</p>
<p><span class="math display">\[ 2n \left(\overline{y} - \hat{\beta}_1 \overline{x}\right) \overline{x} + 2 \hat{\beta}_1 \sum_i x_i^2 - 2 \sum_i y_i x_i = 0 \]</span></p>
<p>розкриваємо дужки</p>
<p><span class="math display">\[ 2n \overline{y}\,\overline{x} - 2n \hat{\beta}_1 \overline{x}^2 + 2 \hat{\beta}_1 \sum_i x_i^2 - 2 \sum_i y_i x_i = 0 \]</span></p>
<p><span class="math display">\[ \implies 2 \hat{\beta}_1 \left( \sum_i x_i^2 - n \overline{x}^2 \right) = 2 \sum_i y_i x_i - 2n \overline{y}\,\overline{ x} \]</span></p>
<div class="recap">
<p><span class="math display">\[ \implies \hat{\beta}_1 = \dfrac{\sum_i y_i x_i - 2n \overline{y}\,\overline{x}}{\sum_i x_i^2 - n \overline{x}^2} = \dfrac{\sum_i (x_i - \overline{x})(y_i - \overline{y})}{\sum_i (x_i - \overline{x})^2} \]</span></p>
</div>
</section>
<section id="мнк-12" class="slide level2 smaller">
<h2>МНК</h2>
<p>Готово!</p>
<p>Тепер у нас є оцінювачі МНК для нахилу</p>
<p><span class="math display">\[ \hat{\beta}_1 = \dfrac{\sum_i (x_i - \overline{x})(y_i - \overline{y})}{\sum_i (x_i - \overline{x})^2}\]</span></p>
<p>і перетину</p>
<p><span class="math display">\[ \hat{\beta}_0 = \overline{y} - \hat{\beta}_1 \overline{x} \]</span></p>
<p>Тепер ми повернемося до припущень і властивостей МНК.</p>
</section></section>
<section>
<section id="мнк-властивості-та-припущення" class="title-slide slide level1 center" data-background-color="#eef3f8">
<h1>МНК: властивості та припущення</h1>

</section>
<section id="властивості" class="slide level2">
<h2>Властивості</h2>
<p>Уявіть, що ми намагаємося оцінити невідомий параметр <span class="math inline">\(\beta\)</span>, і нам відомі розподіли трьох конкуруючих оцінювачів.</p>
<p>Який би ми обрали?</p>

<img data-src=".00_files/figure-revealjs/three-estimators-output-1.svg" id="three-estimators" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="властивості-1" class="slide level2">
<h2>Властивості</h2>
<p><strong>Питання:</strong> Які властивості можуть бути важливі для оцінювача?</p>
<div class="fragment">
<p><strong>Відповідь перша: зміщення (Bias)</strong></p>
<p>Чи в середньому (після <em>багатьох</em> вибірок) оцінювач наближається до правильного значення?</p>
<p><strong>Більш формально:</strong> Чи дорівнює середнє значення розподілу оцінювача параметру, який він оцінює?</p>
<p><span class="math display">\[ \mathop{\text{Bias}}_\beta \left( \hat{\beta} \right) = \mathop{\boldsymbol{E}}\left[ \hat{\beta} \right] - \beta \]</span></p>
</div>
</section>
<section id="властивості-2" class="slide level2">
<h2>Властивості</h2>
<p><strong>Відповідь перша: зміщення (Bias)</strong></p>
<div class="columns">
<div class="column">
<p><strong>Незміщенна оцінка:</strong> <span class="math inline">\(\mathop{\boldsymbol{E}}\left[ \hat{\beta} \right] = \beta\)</span></p>
<div id="cell-unbiased-pdf" class="cell" data-execution_count="37">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src=".00_files/figure-revealjs/unbiased-pdf-output-1.svg" id="unbiased-pdf"></p>
</figure>
</div>
</div>
</div>
</div><div class="column">
<p><strong>Зміщенна оцінка:</strong> <span class="math inline">\(\mathop{\boldsymbol{E}}\left[ \hat{\beta} \right] \neq \beta\)</span></p>
<div id="cell-biased-pdf" class="cell" data-execution_count="38">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src=".00_files/figure-revealjs/biased-pdf-output-1.svg" id="biased-pdf"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="властивості-3" class="slide level2">
<h2>Властивості</h2>
<p><strong>Відповідь друга: дисперсія (Variance).</strong></p>
<div class="fragment">
<p>Важливі не лише центральні тенденції конкуруючих розподілів.</p>
<p>Ми також дбаємо про <strong>дисперсію</strong> оцінювача.</p>
<p><span class="math display">\[ \mathop{\text{Var}} \left( \hat{\beta} \right) = \mathop{\boldsymbol{E}}\left[ \left( \hat{\beta} - \mathop{\boldsymbol{E}}\left[ \hat{\beta} \right] \right)^2 \right] \]</span></p>
<p>Менші оцінки дисперсії означають, що ми отримуємо оцінки ближче до середнього в кожній вибірці.</p>
</div>
</section>
<section id="властивості-4" class="slide level2">
<h2>Властивості</h2>
<p><strong>Відповідь друга: дисперсія (Variance).</strong></p>

<img data-src=".00_files/figure-revealjs/variance-pdf-output-1.svg" id="variance-pdf" class="r-stretch"></section>
<section id="властивості-5" class="slide level2">
<h2>Властивості</h2>
<p><strong>Відповідь перша: зміщення</strong></p>
<p><strong>Відповідь друга: дисперсія</strong></p>
<p><strong>Тонкощі:</strong> Компроміс зміщення-дисперсії (<em>bias-variance tradeoff</em>).</p>
<p>Чи готові ми прийняти зміщення, щоб зменшити дисперсію?</p>
<p>В статистиці ми зазвичай дотримуємося незміщених оцінок. Але інші дисципліни (особливо у сфері ML) більше думають про цей компроміс.</p>
</section>
<section id="the-bias-variance-tradeoff." class="slide level2">
<h2>The bias-variance tradeoff.</h2>

<img data-src=".00_files/figure-revealjs/variance-bias-output-1.svg" id="variance-bias" class="r-stretch"></section>
<section id="властивості-6" class="slide level2">
<h2>Властивості</h2>
<p>Як ви вже могли здогадатися,</p>
<ul>
<li>МНК є <strong>незміщеною оцінкою</strong>.</li>
<li>МНК має <strong>мінімальне відхилення</strong> серед усіх незміщених лінійних оцінювачів.</li>
</ul>
</section>
<section id="властивості-7" class="slide level2">
<h2>Властивості</h2>
<p>Але… ці (дуже гарні) властивості залежать від ряду припущень:</p>
<ol type="1">
<li><p>Зв’язок генеральної сукупності є лінійним.</p></li>
<li><p>Наша змінна <span class="math inline">\(X\)</span> є <strong>екзогенною</strong>, <em>тобто</em>, <span class="math inline">\(\mathop{\boldsymbol{E}}\left[ u \mid X \right] = 0\)</span>.</p></li>
<li><p>Змінна <span class="math inline">\(X\)</span> має варіацію. І якщо існує кілька пояснювальних змінних, вони не є абсолютно колінеарними.</p></li>
<li><p>Збурення генеральної сукупності <span class="math inline">\(u_i\)</span> незалежно та однаково розподілені за нормальним законом розподілу із середнім в нулі <span class="math inline">\(\left( \mathop{\boldsymbol{E}}\left[ u \right] = 0 \right)\)</span> та дисперсією <span class="math inline">\(\sigma^2\)</span> (<em>тобто</em>, <span class="math inline">\(\mathop{\boldsymbol{E}}\left[ u^2 \right] = \sigma^2\)</span>).</p></li>
</ol>
<div class="footer">
<p>🔗<a href="https://gallery.shinyapps.io/slr_diag/">Diagnostics for simple linear regression</a></p>
</div>
</section>
<section id="припущення" class="slide level2">
<h2>Припущення</h2>
<p>Різні припущення гарантують різні властивості:</p>
<ul>
<li><p>Припущення (1), (2) і (3) роблять OLS незміщеним.</p></li>
<li><p>Припущення (4) дає нам незміщену оцінку для дисперсії наших оцінок МНК.</p></li>
</ul>
</section>
<section id="умовне-сподівання" class="slide level2 smaller">
<h2>Умовне сподівання</h2>
<p>Для багатьох випадків, нашим найважливішим припущенням є <strong>екзогенність</strong>, <em>тобто</em>, <span class="math display">\[
\begin{align}
   \mathop{E}\left[ u \mid X \right] = 0
\end{align}
\]</span> але що це насправді означає?</p>
<div class="fragment">
<p>Один із способів подумати про це визначення:</p>
<blockquote>
<p>Для <em>будь-якого</em> значення <span class="math inline">\(X\)</span> середнє значення залишків має дорівнювати нулю.</p>
</blockquote>
<ul>
<li><p><em>Наприклад</em>, <span class="math inline">\(\mathop{E}\left[ u \mid X=1 \right]=0\)</span> <em>і</em> <span class="math inline">\(\mathop{E}\left[ u \mid X=100 \right]= 0\)</span></p></li>
<li><p><em>Наприклад</em>, <span class="math inline">\(\mathop{E}\left[ u \mid X_2=\text{Жінка} \right]=0\)</span> <em>і</em> <span class="math inline">\(\mathop{E}\left[ u \mid X_2=\text{Чоловік} \right]=0\)</span></p></li>
</ul>
</div>
</section>
<section class="slide level2">

<p>Графічно…</p>
</section>
<section class="slide level2">

<p>Дійсна екзогенність, <em>тобто</em>, <span class="math inline">\(\mathop{E}\left[ u \mid X \right] = 0\)</span></p>

<img data-src=".00_files/figure-revealjs/ex-good-exog-output-1.svg" id="ex-good-exog" class="r-stretch"></section>
<section class="slide level2">

<p>Недійсна екзогенність, <em>i.e.</em>, <span class="math inline">\(\mathop{E}\left[ u \mid X \right] \neq 0\)</span></p>

<img data-src=".00_files/figure-revealjs/ex-bad-exog-output-1.svg" id="ex-bad-exog" class="r-stretch"></section></section>
<section>
<section id="невизначеність-та-помилки" class="title-slide slide level1 center" data-background-color="#eef3f8">
<h1>Невизначеність та помилки</h1>

</section>
<section id="щось-ще" class="slide level2">
<h2>Щось ще?</h2>
<p>До цього моменту ми знаємо, що МНК має деякі хороші властивості, і ми знаємо, як оцінити перетин і коефіцієнт нахилу за допомогою МНК.</p>
<p>Наш поточний робочий процес:</p>
<ul>
<li>Отримати дані (точки зі значеннями <span class="math inline">\(x\)</span> і <span class="math inline">\(y\)</span>)</li>
<li>Побудувати модель <span class="math inline">\(y\)</span> на <span class="math inline">\(x\)</span></li>
<li>Побудуйте лінію МНК (<em>тобто</em>, <span class="math inline">\(\hat{y} = \hat{\beta}_0 + \hat{\beta}_1\)</span>)</li>
<li>Готово?</li>
</ul>
<p>Але чого ми <strong>навчимося</strong> з цієї вправи?</p>
</section>
<section id="щось-ще-так" class="slide level2">
<h2>Щось ще? Так!</h2>
<p>Але чого ми <strong>навчимося</strong> з цієї вправи?</p>
<ul>
<li>Наскільки ми повинні бути впевнені в точності наших оцінок?</li>
<li>Наскільки добре наша модель пояснює зміну <span class="math inline">\(y\)</span>?</li>
</ul>
<p>Ми повинні вміти справлятися з невизначеністю.</p>
</section>
<section id="вчимося-на-помилках" class="slide level2">
<h2>Вчимося на помилках</h2>
<p>Як показало наше попереднє моделювання, наша проблема з <strong>невизначеністю</strong> полягає в тому, що ми не знаємо, чи наша вибіркова оцінка <em>близька</em> чи <em>далека</em> від невідомого параметра генеральної сукупності.</p>
<p>Проте ще не все втрачено. Ми можемо використовувати помилки <span class="math inline">\(\left(e_i = y_i - \hat{y}_i\right)\)</span>, щоб зрозуміти, наскільки добре наша модель пояснює варіацію <span class="math inline">\(y\)</span>.</p>
<p>Коли здається, що наша модель виконує «гарну» роботу, ми можемо з більшою впевненістю використовувати її, щоб дізнатися про зв’язок між <span class="math inline">\(y\)</span> і <span class="math inline">\(x\)</span>.</p>
<p>Тепер нам просто потрібно формалізувати вищезазначене.</p>
</section>
<section id="вчимося-на-помилках-1" class="slide level2">
<h2>Вчимося на помилках</h2>
<p>Спочатку ми оцінимо дисперсію <span class="math inline">\(u_i\)</span> (нагадаємо: <span class="math inline">\(\mathop{\text{Var}} \left( u_i \right) = \sigma^2\)</span>), використовуючи наші квадрати помилок, <em>тобто</em>,</p>
<p><span class="math display">\[ s^2 = \dfrac{\sum_i e_i^2}{n - k} \]</span></p>
<p>де <span class="math inline">\(k\)</span> дає кількість параметрів моделі, яку ми оцінюємо (<em>наприклад</em>, <span class="math inline">\(\beta_0\)</span> і <span class="math inline">\(\beta_1\)</span> дадуть <span class="math inline">\(k=2\)</span>).</p>
<p><span class="math inline">\(s^2\)</span> є незміщеною оцінкою <span class="math inline">\(\sigma^2\)</span>.</p>
</section>
<section id="вчимося-на-помилках-2" class="slide level2">
<h2>Вчимося на помилках</h2>
<p>Дисперсія <span class="math inline">\(\hat{\beta}_1\)</span> (для простої лінійної регресії) дорівнює</p>
<p><span class="math display">\[ \mathop{\text{Var}} \left( \hat{\beta}_1 \right) = \dfrac{s^2}{\sum_i \left( x_i - \overline{x} \right)^2 } \]</span></p>
<p>який показує, що дисперсія нашого оцінювача нахилу</p>
<ol type="1">
<li><p>збільшується, оскільки наші збурення стають шумнішими</p></li>
<li><p>зменшується зі збільшенням дисперсії <span class="math inline">\(x\)</span></p></li>
</ol>
</section>
<section id="вчимося-на-помилках-3" class="slide level2">
<h2>Вчимося на помилках</h2>
<p><em>Найчастіше:</em> <strong>стандартна помилка</strong> <span class="math inline">\(\hat{\beta}_1\)</span></p>
<p><span class="math display">\[ \mathop{\hat{\text{SE}}} \left( \hat{\beta}_1 \right) = \sqrt{\dfrac{s^2}{\sum_i \left( x_i - \overline{ x} \right)^2}} \]</span></p>
<p><em>Нагадуємо:</em> Стандартна помилка оцінювача — це стандартне відхилення розподілу оцінювача.</p>
</section>
<section id="мнк-в-python" class="slide level2 smaller">
<h2>МНК в Python</h2>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">Statsmodels v1</a></li><li><a href="#tabset-2-2">Statsmodels v2</a></li><li><a href="#tabset-2-3">SciPy</a></li><li><a href="#tabset-2-4">Sklearn</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<div id="lm-statsmodels-2" class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb13-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> smf.ols(<span class="st">'Global_Sales ~ NA_Sales'</span>, vgsales).fit()</span>
<span id="cb13-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(results.summary())</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:           Global_Sales   R-squared:                       0.886
Model:                            OLS   Adj. R-squared:                  0.886
Method:                 Least Squares   F-statistic:                 1.284e+05
Date:                Mon, 28 Apr 2025   Prob (F-statistic):               0.00
Time:                        14:39:16   Log-Likelihood:                -12888.
No. Observations:               16598   AIC:                         2.578e+04
Df Residuals:                   16596   BIC:                         2.580e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0632      0.004     14.725      0.000       0.055       0.072
NA_Sales       1.7918      0.005    358.380      0.000       1.782       1.802
==============================================================================
Omnibus:                    10021.157   Durbin-Watson:                   1.926
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         39268559.707
Skew:                           1.178   Prob(JB):                         0.00
Kurtosis:                     241.275   Cond. No.                         1.43
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</div>
<div id="tabset-2-2">
<div id="lm-statsmodels-1" class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb15-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(vgsales.NA_Sales)</span>
<span id="cb15-4"><a href="" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> sm.OLS(vgsales.Global_Sales, X)</span>
<span id="cb15-5"><a href="" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> model.fit()</span>
<span id="cb15-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(result.summary())</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:           Global_Sales   R-squared:                       0.886
Model:                            OLS   Adj. R-squared:                  0.886
Method:                 Least Squares   F-statistic:                 1.284e+05
Date:                Mon, 28 Apr 2025   Prob (F-statistic):               0.00
Time:                        14:39:16   Log-Likelihood:                -12888.
No. Observations:               16598   AIC:                         2.578e+04
Df Residuals:                   16596   BIC:                         2.580e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0632      0.004     14.725      0.000       0.055       0.072
NA_Sales       1.7918      0.005    358.380      0.000       1.782       1.802
==============================================================================
Omnibus:                    10021.157   Durbin-Watson:                   1.926
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         39268559.707
Skew:                           1.178   Prob(JB):                         0.00
Kurtosis:                     241.275   Cond. No.                         1.43
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</div>
<div id="tabset-2-3">
<p><span class="red">Тільки парна регресія</span></p>
<div id="cell-lm-scipy" class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb17-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="" aria-hidden="true" tabindex="-1"></a>stats.linregress(x<span class="op">=</span>vgsales.NA_Sales, y<span class="op">=</span>vgsales.Global_Sales)</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="lm-scipy" class="cell-output cell-output-display" data-execution_count="45">
<pre><code>LinregressResult(slope=1.7918272775678399, intercept=0.0632023352818627, rvalue=0.9410473571255512, pvalue=0.0, stderr=0.004999800281795847, intercept_stderr=0.004292205029993517)</code></pre>
</div>
</div>
</div>
<div id="tabset-2-4">
<div id="lm-sklearn" class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb19-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> vgsales[[<span class="st">'NA_Sales'</span>]]</span>
<span id="cb19-4"><a href="" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> vgsales[<span class="st">'Global_Sales'</span>]</span>
<span id="cb19-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression()</span>
<span id="cb19-7"><a href="" aria-hidden="true" tabindex="-1"></a>model.fit(X, y)</span>
<span id="cb19-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.intercept_, model.coef_, model.score(X, y))</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.06320233528185787 [1.79182728] 0.8855701283529853</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="вчимося-на-помилках-4" class="slide level2">
<h2>Вчимося на помилках</h2>
<p>Ми використовуємо стандартну помилку <span class="math inline">\(\hat{SE_{\hat{\beta}_1}}\)</span> разом із самим <span class="math inline">\(\hat{\beta}_1\)</span>, щоб дізнатися про параметр <span class="math inline">\(\beta_1\)</span>.</p>
<p>Після отримання розподілу <span class="math inline">\(\hat{\beta}_1\)</span>, у нас є два (пов’язаних) варіанти формального статистичного висновку щодо нашого невідомого параметра <span class="math inline">\(\beta_1\)</span>:</p>
<ul>
<li><p><strong>Довірчі інтервали:</strong> Використовуйте оцінку та її стандартну помилку, щоб створити інтервал, який при повторенні зазвичай міститиме справжній параметр.</p></li>
<li><p><strong>Перевірка гіпотези:</strong> Визначте, чи є статистично значущі докази відхилення гіпотетичного значення або діапазону значень.</p></li>
</ul>
</section></section>
<section>
<section id="довірчі-інтервали" class="title-slide slide level1 center" data-background-color="#eef3f8">
<h1>Довірчі інтервали</h1>

</section>
<section id="довірчі-інтервали-1" class="slide level2">
<h2>Довірчі інтервали</h2>
<p>Будуємо довірчі інтервали рівня <span class="math inline">\((1-\alpha)\)</span> для <span class="math inline">\(\beta_1\)</span> <span class="math display">\[ \hat{\beta_1}\ \pm t_{\alpha/2,\text{df}} \, \mathop{\hat{\text{SE}}} \left( \hat{\beta_1} \right) \]</span></p>
<p><span class="math inline">\(t_{\alpha/2,\text{df}}\)</span> позначає <span class="math inline">\(\alpha/2\)</span> квантиль <span class="math inline">\(t\)</span> розподілу з <span class="math inline">\(n-k\)</span> ступенями свободи.</p>
</section>
<section id="довірчі-інтервали-2" class="slide level2 smaller">
<h2>Довірчі інтервали</h2>
<p>Будуємо довірчі інтервали рівня <span class="math inline">\((1-\alpha)\)</span> для <span class="math inline">\(\beta_1\)</span> <span class="math display">\[ \hat{\beta_1}\ \pm t_{\alpha/2,\text{df}} \, \mathop{\hat{\text{SE}}} \left( \hat{\beta_1} \right) \]</span></p>
<p>Наприклад, 100 спостережень, два коефіцієнти (<em>тобто</em>, <span class="math inline">\(\hat{\beta}_0\)</span> і <span class="math inline">\(\hat{\beta}_1 \implies k = 2\)</span>), і <span class="math inline">\(\alpha = 0,05\)</span> ( для 95% довірчого інтервалу) дає нам <span class="math inline">\(t_{0,025,\,98} = -1.98\)</span></p>

<img data-src=".00_files/figure-revealjs/t-dist-output-1.svg" id="t-dist" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="довірчі-інтервали-3" class="slide level2 smaller">
<h2>Довірчі інтервали</h2>
<p>Будуємо довірчі інтервали рівня <span class="math inline">\((1-\alpha)\)</span> для <span class="math inline">\(\beta_1\)</span></p>
<div class="columns">
<div class="column" style="width:70%;">
<div id="ci-py-output" class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> smf.ols(<span class="st">'y ~ x'</span>, pop_df).fit()</span>
<span id="cb21-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(results.summary())</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.544
Model:                            OLS   Adj. R-squared:                  0.539
Method:                 Least Squares   F-statistic:                     116.9
Date:                Mon, 28 Apr 2025   Prob (F-statistic):           2.12e-18
Time:                        14:39:16   Log-Likelihood:                -87.291
No. Observations:                 100   AIC:                             178.6
Df Residuals:                      98   BIC:                             183.8
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0490      0.059      0.833      0.407      -0.068       0.166
x              0.7216      0.067     10.811      0.000       0.589       0.854
==============================================================================
Omnibus:                        0.377   Durbin-Watson:                   1.976
Prob(Omnibus):                  0.828   Jarque-Bera (JB):                0.538
Skew:                           0.006   Prob(JB):                        0.764
Kurtosis:                       2.641   Cond. No.                         1.18
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</div><div class="column" style="width:30%;">
<p><span class="math display">\[ \hat{\beta_1}\ \pm t_{\alpha/2,\text{df}} \, \mathop{\hat{\text{SE}}} \left( \hat{\beta_1} \right) \]</span></p>
<p>Отже, наш 95% довірчий інтервал становить <span class="math inline">\(0.7216 \pm 1.98 \times 0.067 = \left[ 0.589,\, 0.854 \right]\)</span></p>
</div></div>
</section>
<section id="довірчі-інтервали-4" class="slide level2">
<h2>Довірчі інтервали</h2>
<p>Отже, ми маємо довірчий інтервал для <span class="math inline">\(\beta_1\)</span>, <em>тобто</em>, <span class="math inline">\(\left[ 0.589,\, 0.854 \right]\)</span>.</p>
<p>Що це означає?</p>
<div class="fragment">
<p><strong>Неофіційно:</strong> Довірчий інтервал дає нам область (інтервал), в якій ми можемо певною мірою довіряти щодо вмісту параметра.</p>
</div>
<div class="fragment">
<p><strong>Більш формально:</strong> Якщо неодноразово робити вибірку з нашої сукупності та будувати довірчі інтервали для кожної з цих вибірок, <span class="math inline">\((1-\alpha)\)</span> відсотків наших інтервалів (<em>наприклад</em>, 95%) міститиме параметр генеральної сукупності <em>десь в інтервалі</em>.</p>
</div>
<div class="fragment">
<p>Тепер повернемося до нашої симуляції…</p>
</div>
</section>
<section id="довірчі-інтервали-5" class="slide level2">
<h2>Довірчі інтервали</h2>
<p>Ми відібрали 10 000 вибірок (кожна розміром <span class="math inline">\(n = 30\)</span>) із нашої сукупності та оцінили нашу регресійну модель для кожної з цих симуляцій:</p>
<span class="math display">\[ y_i = \hat{\beta}_0 + \hat{\beta}_1 x_i + e_i \]</span>
<center>
(повторюється 10 000 разів)
</center>
<p>Тепер давайте оцінимо 95% довірчі інтервали для кожного з цих інтервалів…</p>
</section>
<section id="довірчі-інтервали-6" class="slide level2">
<h2>Довірчі інтервали</h2>
<p><strong>З нашого попереднього моделювання:</strong> 97.5% 95% довірчих інтервалів містять справжнє значення параметра <span class="math inline">\(\beta_1\)</span>.</p>

<img data-src="img/simulation-ci-1.png" class="quarto-figure quarto-figure-center r-stretch"></section></section>
<section>
<section id="тестування-гіпотез" class="title-slide slide level1 center" data-background-color="#eef3f8">
<h1>Тестування гіпотез</h1>

</section>
<section id="тестування-гіпотез-1" class="slide level2 smaller">
<h2>Тестування гіпотез</h2>
<p>У багатьох дослідженнях ми хочемо знати більше, ніж точкову оцінку або діапазон значень. Ми хочемо знати, що наші статистичні дані говорять про існуючі теорії.</p>
<p>Ми хочемо перевірити гіпотези, висунуті чиновниками, політиками, економістами, науковцями, друзями, дивними сусідами тощо.</p>
<p><strong>Приклади</strong></p>
<ul>
<li><p>Збільшення присутності поліції <strong>зменшує злочинність</strong>?</p></li>
<li><p>Будівництво гігантської стіни <strong>зменшує злочинність</strong>?</p></li>
<li><p>Розпуск уряду <strong>згубно впливає на економіку</strong>?</p></li>
<li><p>Чи легальний канабіс <strong>зменшує водіння в нетверезому стані</strong> або <strong>зменшує вживання опіоїдів</strong>?</p></li>
<li><p>Чи стандарти якості повітря <strong>покращують здоров’я</strong> та/або <strong>зменшують кількість робочіх місць</strong>?</p></li>
</ul>
</section>
<section id="тестування-гіпотез-2" class="slide level2 smaller">
<h2>Тестування гіпотез</h2>
<p>Перевірка гіпотез спирається на дуже схожі результати та інтуїцію.</p>
<p>Хоча невизначеність, звичайно, існує, ми все ще можемо побудувати <em>надійні</em> статистичні тести (відкидаючи або не відхиляючи висунуту гіпотезу).</p>
<div class="fragment">
<p><strong>МНК <em>t</em> тест</strong>: Наша (нульова) гіпотеза стверджує, що <span class="math inline">\(\beta_1\)</span> дорівнює значенню <span class="math inline">\(c\)</span>, <em>тобто</em>, <span class="math inline">\(H_o:\: \beta_1 = c\)</span></p>
<p>З властивостей МНК ми можемо показати, що тестова статистика</p>
<p><span class="math display">\[ t_\text{stat} = \dfrac{\hat{\beta}_1 - c}{\mathop{\hat{\text{SE}}} \left( \hat{\beta}_1 \right)} \]</span></p>
<p>слідує розподілу <span class="math inline">\(t\)</span> з <span class="math inline">\(n-k\)</span> ступенями свободи.</p>
</div>
</section>
<section id="тестування-гіпотез-3" class="slide level2 smaller">
<h2>Тестування гіпотез</h2>
<p>Для <strong>двостороннього</strong> тесту рівня <span class="math inline">\(\alpha\)</span> ми відхиляємо нульову гіпотезу (і завершуємо альтернативну гіпотезу), коли</p>
<p><span class="math display">\[ \left|t_\text{stat}\right| &gt; \left|t_{1-\alpha/2,\,df}\right| \]</span></p>
<p>це означає, що наша <strong>тестова статистика є більш екстремальною, ніж критичне значення</strong>.</p>
<p>Крім того, ми можемо обчислити <strong>p-значення</strong>, яке супроводжує нашу тестову статистику, що фактично дає нам імовірність побачити нашу тестову статистику <em>або більш екстремальну тестову статистику</em>, якщо нульова гіпотеза вірна.</p>
<p>Дуже малі p-значення (зазвичай &lt; 0,05) означають, що ми навряд чи побачимо наші результати, якби нульова гіпотеза дійсно була вірною — ми схильні відхиляти нуьлову гіпотезу для p-значень нижче 0,05.</p>
</section>
<section id="тестування-гіпотез-4" class="slide level2 smaller">
<h2>Тестування гіпотез</h2>
<div class="columns">
<div class="column" style="width:70%;">
<div id="hypothesis-test" class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb23-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> smf.ols(<span class="st">'y ~ x'</span>, pop_df).fit()</span>
<span id="cb23-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(results.summary())</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.544
Model:                            OLS   Adj. R-squared:                  0.539
Method:                 Least Squares   F-statistic:                     116.9
Date:                Mon, 28 Apr 2025   Prob (F-statistic):           2.12e-18
Time:                        14:39:16   Log-Likelihood:                -87.291
No. Observations:                 100   AIC:                             178.6
Df Residuals:                      98   BIC:                             183.8
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.0490      0.059      0.833      0.407      -0.068       0.166
x              0.7216      0.067     10.811      0.000       0.589       0.854
==============================================================================
Omnibus:                        0.377   Durbin-Watson:                   1.976
Prob(Omnibus):                  0.828   Jarque-Bera (JB):                0.538
Skew:                           0.006   Prob(JB):                        0.764
Kurtosis:                       2.641   Cond. No.                         1.18
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
</div><div class="column" style="width:30%;">
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1 = 0\)</span> <em>vs.</em> <span class="math inline">\(H_a\)</span>: <span class="math inline">\(\beta_1 \neq 0\)</span></p>
<p><span class="math inline">\(t_\text{stat} = 10.811\)</span> та <span class="math inline">\(t_\text{0.975, 98} = -1.98\)</span></p>
<p><em>p</em>-значення <span class="math inline">\(&lt; 0,05\)</span></p>
<p><strong>Тому ми відкидаємо <span class="math inline">\(H_0\)</span>!</strong></p>
</div></div>
</section>
<section id="тестування-гіпотез-5" class="slide level2">
<h2>Тестування гіпотез</h2>
<p>Повертаємося до нашої симуляції! Давайте подивимося, що насправді робить наша <span class="math inline">\(t\)</span> статистика.</p>
<p>У цій ситуації ми фактично можемо знати (і забезпечити) нульову гіпотезу, оскільки ми згенерували дані.</p>
<p>Для кожного з 10 000 зразків ми обчислимо статистику <span class="math inline">\(t\)</span>, а потім побачимо, скільки статистичних даних <span class="math inline">\(t\)</span> перевищує наше критичне значення (-1.98, як вище).</p>
<p>Відповідь має бути приблизно 5 відсотків — наш рівень <span class="math inline">\(\alpha\)</span>.</p>
</section>
<section id="тестування-гіпотез-6" class="slide level2">
<h2>Тестування гіпотез</h2>
<p>У нашому моделюванні 2.1% нашої статистики <span class="math inline">\(t\)</span> відхиляє нульову гіпотезу.</p>
<p>Розподіл нашої статистики <span class="math inline">\(t\)</span> (заштрихування областей відхилення).</p>

<img data-src="img/simulation-t-plot-1.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section class="slide level2">

<p>Відповідно, 2.1% наших значень <span class="math inline">\(p\)</span> відхиляє нульову гіпотезу.</p>
<p>Розподіл наших значень <span class="math inline">\(p\)</span> (заштрихування значень <span class="math inline">\(p\)</span> нижче 0,05).</p>

<img data-src="img/simulation-p-plot-1.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="f-тест" class="slide level2">
<h2>F-тест</h2>
<p>Іноді можна зустріти <span class="math inline">\(F\)</span>-тести.</p>
<p>Ми використовуємо <span class="math inline">\(F\)</span>-тести для перевірки гіпотез, які включають кілька випадків <br> (<em>наприклад</em>, <span class="math inline">\(\beta_1 = \beta_2\)</span> або <span class="math inline">\(\beta_3 + \beta_4 = 1\)</span>),</p>
<p>а не одна проста гіпотеза <br>(<em>наприклад</em>, <span class="math inline">\(\beta_1 = 0\)</span>, для якого ми просто використаємо тест <span class="math inline">\(t\)</span>).</p>
</section>
<section id="f-тест-1" class="slide level2">
<h2>F-тест</h2>
<p><strong>Приклад</strong></p>
<p>Економісти люблять казати: «Гроші взаємозамінні».</p>
<p>Уявіть собі, що ми можемо захотіти перевірити, чи дійсно гроші, отримані як дохід, мають такий же вплив на споживання, як гроші, отримані від податкових знижок.</p>
<p><span class="math display">\[ \text{Споживання}_i = \beta_0 + \beta_1 \text{Дохід}_{i} + \beta_2 \text{Знижка}_i + u_i \]</span></p>
</section>
<section id="f-тест-2" class="slide level2">
<h2>F-тест</h2>
<p><strong>Приклад, продовження</strong></p>
<p>Ми можемо записати нашу нульову гіпотезу як</p>
<p><span class="math display">\[ H_o:\: \beta_1 = \beta_2 \iff H_o :\: \beta_1 - \beta_2 = 0 \]</span></p>
<p>Накладення цієї нульової гіпотези дає нам <strong>обмежену модель</strong></p>
<p><span class="math display">\[ \text{Споживання}_i = \beta_0 + \beta_1 \text{Дохід}_{i} + \beta_1 \text{Знижка}_i + u_i \]</span> <span class="math display">\[ \text{Споживання}_i = \beta_0 + \beta_1 \left( \text{Дохід}_{i} + \text{Знижка}_i \right) + u_i \]</span></p>
</section>
<section id="f-тест-3" class="slide level2">
<h2>F-тест</h2>
<p><strong>Приклад, продовження</strong></p>
<p>Щоб перевірити нульову гіпотезу <span class="math inline">\(H_o :\: \beta_1 = \beta_2\)</span> проти <span class="math inline">\(H_a :\: \beta_1 \neq \beta_2\)</span>, <br>ми використовуємо статистику <span class="math inline">\(F\)</span> <span class="math display">\[
\begin{align}
   F_{q,\,n-k-1} = \dfrac{\left(\text{ESS}_r - \text{ESS}_u\right)/q}{\text{ESS}_u/(n-k-1)}
\end{align}
\]</span> який (як випливає з назви) відповідає розподілу <span class="math inline">\(F\)</span> із ступенями свободи в чисельнику <span class="math inline">\(q\)</span> і ступенями свободи в знаменнику <span class="math inline">\(n-k-1\)</span>.</p>
<p>Тут <span class="math inline">\(q\)</span> — це кількість обмежень, які ми накладаємо через <span class="math inline">\(H_o\)</span>.</p>
</section>
<section id="f-тест-4" class="slide level2 smaller">
<h2>F-тест</h2>
<p><strong>Приклад, продовження</strong></p>
<p><span class="math inline">\(\text{ESS}_r\)</span> – це сума квадратів помилок (ESS) з нашої <strong>обмеженої моделі</strong> <span class="math display">\[ \text{Споживання}_i = \beta_0 + \beta_1 \left( \text{Дохід}_{i} + \text{Знижка}_i \right) + u_i \]</span></p>
<p>а <span class="math inline">\(\text{ESS}_u\)</span> – це сума квадратів помилок (ESS) з нашої <strong>необмеженої моделі</strong> <span class="math display">\[ \text{Споживання}_i = \beta_0 + \beta_1 \text{Дохід}_{i} + \beta_2 \text{Знижка}_i + u_i \]</span></p>
<div class="fragment">
<p>Тест <span class="math inline">\(F\)</span> порівнює ефективність необмеженої моделі з ефективність обмеженої моделі, використовуючи їхні <span class="math inline">\(\text{ESS}\)</span>.</p>
</div>
<div class="fragment">
<p><span class="math display">\[
\begin{align}
   F_\text{stat} = \dfrac{\left(\text{ESS}_r - \text{ESS}_u\right)/q}{\text{ESS}_u/(n-k-1)} \sim F_{ q,\,n-k-1}
\end{align}
\]</span></p>
</div>
</section></section>
<section>
<section id="оцінювання-моделі" class="title-slide slide level1 center" data-background-color="#eef3f8">
<h1>Оцінювання моделі</h1>

</section>
<section id="оцінювання-моделі-1" class="slide level2">
<h2>Оцінювання моделі</h2>
<p>Показники <em>хорошої відповідності</em> (анг. <em>goodness of fit</em>) намагаються проаналізувати, наскільки добре наша модель описує (<em>відповідає</em>) даним.</p>
<p><strong>Популярний показник:</strong> <span class="math inline">\(R^2\)</span> [R-квадрат] (<em>він же</em> коефіцієнт детермінації)</p>
<p><span class="math display">\[ R^2 = \dfrac{\sum_i (\hat{y}_i - \overline{y})^2}{\sum_i \left( y_i - \overline{y} \right)^2} = 1 - \dfrac{\sum_i \left( y_i - \hat{y}_i \right)^2}{\sum_i \left( y_i - \overline{y} \right)^2} \]</span></p>
<p>Зверніть увагу на нашого старого друга ESS: <span class="math inline">\(\sum_i \left( y_i - \hat{y}_i \right)^2 = \sum_i e_i^2\)</span>.</p>
<div class="fragment">
<p><span class="math inline">\(R^2\)</span> буквально вказує нам частку дисперсії в <span class="math inline">\(y\)</span>, яку враховує наша модель. Таким чином <span class="math inline">\(0 \leq R^2 \leq 1\)</span>.</p>
</div>
</section>
<section id="r2" class="slide level2 smaller">
<h2><span class="math inline">\(R^2\)</span></h2>
<p><strong>Проблема:</strong> коли ми додаємо змінні до нашої моделі, <span class="math inline">\(R^2\)</span> <em>постійно</em> збільшується.</p>
<div class="fragment">
<p>Щоб побачити цю проблему, ми можемо змоделювати набір даних із 10 000 спостережень за <span class="math inline">\(y\)</span> і 1000 випадкових змінних <span class="math inline">\(x_k\)</span>. <strong>Немає зв’язку між <span class="math inline">\(y\)</span> і <span class="math inline">\(x_k\)</span>!</strong></p>
<p>Псевдокод симуляції:</p>
</div>
<div class="fragment">
<ul>
<li>Згенеруйте 10 000 спостережень <span class="math inline">\(y\)</span></li>
<li>Згенеруйте 10 000 спостережень за змінними від <span class="math inline">\(x_1\)</span> до <span class="math inline">\(x_{1000}\)</span></li>
<li>Регресія:
<ul>
<li>LM<sub>1</sub>: регресія <span class="math inline">\(y\)</span> на <span class="math inline">\(x_1\)</span>; запис R<sup>2</sup></li>
<li>LM<sub>2</sub>: регресія <span class="math inline">\(y\)</span> на <span class="math inline">\(x_1\)</span> і <span class="math inline">\(x_2\)</span>; запис R<sup>2</sup></li>
<li>LM<sub>1000</sub>: регресія <span class="math inline">\(y\)</span> на <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span> і <span class="math inline">\(x_3\)</span>; запис R<sup>2</sup></li>
<li>…</li>
<li>LM<sub>1000</sub>: регресія <span class="math inline">\(y\)</span> на <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, …, <span class="math inline">\(x_{1000}\)</span>; запис R<sup>2</sup></li>
</ul></li>
</ul>
</div>
</section>
<section id="r2-1" class="slide level2 smaller">
<h2><span class="math inline">\(R^2\)</span></h2>
<p><strong>Проблема:</strong> коли ми додаємо змінні до нашої моделі, <span class="math inline">\(R^2\)</span> <em>постійно</em> збільшується.</p>
<p><code>Python</code> код для симуляції:</p>
<div id="r2-sim" class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb25-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb25-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb25-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> joblib <span class="im">import</span> Parallel, delayed</span>
<span id="cb25-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">1234</span>)</span>
<span id="cb25-7"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">10000</span></span>
<span id="cb25-9"><a href="" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb25-10"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> np.random.normal(size<span class="op">=</span>n)</span>
<span id="cb25-12"><a href="" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.random.normal(size<span class="op">=</span>(n, k))</span>
<span id="cb25-13"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> calculate_r2(i):</span>
<span id="cb25-15"><a href="" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> LinearRegression()</span>
<span id="cb25-16"><a href="" aria-hidden="true" tabindex="-1"></a>    model.fit(x[:, :i<span class="op">+</span><span class="dv">2</span>], y)</span>
<span id="cb25-17"><a href="" aria-hidden="true" tabindex="-1"></a>    r2 <span class="op">=</span> model.score(x[:, :i<span class="op">+</span><span class="dv">2</span>], y)</span>
<span id="cb25-18"><a href="" aria-hidden="true" tabindex="-1"></a>    adj_r2 <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> (<span class="dv">1</span> <span class="op">-</span> r2) <span class="op">*</span> (<span class="bu">len</span>(y) <span class="op">-</span> <span class="dv">1</span>) <span class="op">/</span> (<span class="bu">len</span>(y) <span class="op">-</span> (i<span class="op">+</span><span class="dv">2</span>))</span>
<span id="cb25-19"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.DataFrame({<span class="st">'k'</span>: [i<span class="op">+</span><span class="dv">2</span>], <span class="st">'r2'</span>: [r2], <span class="st">'r2_adj'</span>: [adj_r2]})</span>
<span id="cb25-20"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-21"><a href="" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> Parallel(n_jobs<span class="op">=-</span><span class="dv">1</span>)(delayed(calculate_r2)(i) <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(k))</span>
<span id="cb25-22"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-23"><a href="" aria-hidden="true" tabindex="-1"></a>r_df <span class="op">=</span> pd.concat(result, ignore_index<span class="op">=</span><span class="va">True</span>)</span></code><button title="Скопіювати текст" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="r2-2" class="slide level2 smaller">
<h2><span class="math inline">\(R^2\)</span></h2>
<p><strong>Проблема:</strong> коли ми додаємо змінні до нашої моделі, <span class="math inline">\(R^2\)</span> <em>постійно</em> збільшується.</p>

<img data-src=".00_files/figure-revealjs/r2-plot-output-1.svg" id="r2-plot" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="r_adj2" class="slide level2 smaller">
<h2><span class="math inline">\(R_{adj}^2\)</span></h2>
<p>Що робити? <strong>Рішення перше:</strong> <span class="pink">Скоригований</span> <span class="math inline">\(\color{#e64173}{R^2}\)</span></p>

<img data-src=".00_files/figure-revealjs/r2-adj-plot-output-1.svg" id="r2-adj-plot" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="r_adj2-1" class="slide level2 smaller">
<h2><span class="math inline">\(R_{adj}^2\)</span></h2>
<p><strong>Проблема:</strong> коли ми додаємо змінні до нашої моделі, <span class="math inline">\(R^2\)</span> <em>постійно</em> збільшується.</p>
<p><strong>Рішення перше:</strong> Штрафувати за кількість змінних, <em>наприклад</em>, скорегований <span class="math inline">\(R^2\)</span>:</p>
<p><span class="math display">\[ \overline{R}^2 = 1 - \dfrac{\sum_i \left( y_i - \hat{y}_i \right)^2/(n-k-1)}{\sum_i \left( y_i - \overline{y} \right)^2/(n-1)} \]</span></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Примітка</strong></p>
</div>
<div class="callout-content">
<p>Скоригований <span class="math inline">\(R^2\)</span> не обов’язково повинен бути від 0 до 1.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="інтерпретація-коефіцієнтів" class="title-slide slide level1 center" data-background-color="#eef3f8">
<h1>Інтерпретація коефіцієнтів</h1>

</section>
<section id="неперервні-змінні" class="slide level2 smaller">
<h2>Неперервні змінні</h2>
<p>Розглянемо взаємозв’язок</p>
<p><span class="math display">\[ \text{Pay}_i = \beta_0 + \beta_1 \, \text{School}_i + u_i \]</span></p>
<p>де</p>
<ul>
<li><span class="math inline">\(\text{Pay}_i\)</span> — це неперервна змінна, яка вимірює оплату праці</li>
<li><span class="math inline">\(\text{School}_i\)</span> — це неперервна змінна, яка вимірює роки навчання</li>
</ul>
<div class="fragment">
<p><strong>Інтерпретація</strong></p>
<ul>
<li><span class="math inline">\(\beta_0\)</span>: <span class="math inline">\(y\)</span>-intercept, <em>тобто</em>, <span class="math inline">\(\text{Pay}\)</span>, коли <span class="math inline">\(\text{School} = 0\)</span></li>
<li><span class="math inline">\(\beta_1\)</span>: очікувана зміна <span class="math inline">\(\text{Pay}\)</span> при збільшенні на одну одиницю <span class="math inline">\(\text{School}\)</span></li>
</ul>
</div>
</section>
<section id="неперервні-змінні-1" class="slide level2">
<h2>Неперервні змінні</h2>
<p>Альтернативний підхід</p>
<p>Розгляньте модель</p>
<p><span class="math display">\[ y = \beta_0 + \beta_1 \, x + u \]</span></p>
<p>Похідна:</p>
<p><span class="math display">\[ \dfrac{dy}{dx} = \beta_1 \]</span></p>
</section>
<section id="категоріальні-змінні" class="slide level2 smaller">
<h2>Категоріальні змінні</h2>
<p><span class="math display">\[ \text{Pay}_i = \beta_0 + \beta_1 \, \text{Female}_i + u_i \]</span></p>
<p>де</p>
<ul>
<li><span class="math inline">\(\text{Pay}_i\)</span> — це неперервна змінна, яка вимірює оплату праці</li>
<li><span class="math inline">\(\text{Female}_i\)</span> - двійкова/індикаторна змінна, яка приймає <span class="math inline">\(1\)</span>, коли <span class="math inline">\(i\)</span> є жіночою</li>
</ul>
<div class="fragment">
<p><strong>Інтерпретація</strong></p>
<ul>
<li><span class="math inline">\(\beta_0\)</span>: очікувана <span class="math inline">\(\text{Pay}\)</span> для чоловіків (<em>тобто</em>, коли <span class="math inline">\(\text{Female} = 0\)</span>)</li>
<li><span class="math inline">\(\beta_1\)</span>: очікувана різниця в <span class="math inline">\(\text{Pay}\)</span> між жінками та чоловіками</li>
<li><span class="math inline">\(\beta_0 + \beta_1\)</span>: очікувана <span class="math inline">\(\text{Pay}\)</span> для жінок</li>
</ul>
</div>
</section>
<section id="категоріальні-змінні-1" class="slide level2">
<h2>Категоріальні змінні</h2>
<p><span class="math inline">\(y_i = \beta_0 + \beta_1 x_i + u_i\)</span> для двійкової змінної <span class="math inline">\(x_i = \{\color{#314f4f}{0}, \, \color{#e64173}{1}\}\)</span></p>

<img data-src=".00_files/figure-revealjs/cat-plot-1-output-1.svg" id="cat-plot-1" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="категоріальні-змінні-2" class="slide level2">
<h2>Категоріальні змінні</h2>
<p><span class="math inline">\(y_i = \beta_0 + \beta_1 x_i + u_i\)</span> для двійкової змінної <span class="math inline">\(x_i = \{\color{#314f4f}{0}, \, \color{#e64173}{1}\}\)</span></p>

<img data-src=".00_files/figure-revealjs/cat-plot-2-output-1.svg" id="cat-plot-2" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="взаємодії" class="slide level2">
<h2>Взаємодії</h2>
<p>Взаємодії дозволяють змінювати вплив однієї змінної залежно від рівня іншої змінної.</p>
<p><strong>Приклади</strong></p>
<ol type="1">
<li><p>Чи змінюється вплив навчання на оплату за статтю?</p></li>
<li><p>Чи змінюється вплив статі на оплату залежно від раси?</p></li>
<li><p>Чи змінюється вплив навчання на оплату праці залежно від досвіду?</p></li>
</ol>
</section>
<section id="взаємодії-1" class="slide level2">
<h2>Взаємодії</h2>
<p>Раніше ми розглядали модель, яка дозволяла жінкам і чоловікам мати різну заробітну плату, але модель припускала, що вплив навчання на оплату праці буде однаковим для всіх:</p>
<p><span class="math display">\[ \text{Pay}_i = \beta_0 + \beta_1 \, \text{School}_i + \beta_2 \, \text{Female}_i + u_i \]</span></p>
<p>але ми також можемо припустити, щоб вплив освіти відрізнявся залежно від статі:</p>
<p><span class="math display">\[ \text{Pay}_i = \beta_0 + \beta_1 \, \text{School}_i + \beta_2 \, \text{Female}_i + \beta_3 \, \text{School}_i\times\text{Female}_i + u_i \]</span></p>
</section>
<section id="взаємодії-2" class="slide level2 smaller">
<h2>Взаємодії</h2>
<p>Модель, коли навчання в школі має однаковий ефект для всіх (<strong><font color="#e64173">F</font></strong> і <strong><font color="#314f4f">M</font></strong>):</p>

<img data-src=".00_files/figure-revealjs/int-plot-1-output-1.svg" id="int-plot-1" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="взаємодії-3" class="slide level2 smaller">
<h2>Взаємодії</h2>
<p>Модель, у якій вплив шкільного навчання може відрізнятися залежно від статі (<strong><font color="#e64173">F</font></strong> і <strong><font color="#314f4f">M</font></strong>):</p>

<img data-src=".00_files/figure-revealjs/int-plot-2-output-1.svg" id="int-plot-2" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="взаємодії-4" class="slide level2 smaller">
<h2>Взаємодії</h2>
<p>Інтерпретація коефіцієнтів може бути дещо складною у зв’язку з взаємодіями, але головне — уважно пропрацювати математику.</p>
<p><span class="math display">\[ \text{Pay}_i = \beta_0 + \beta_1 \, \text{School}_i + \beta_2 \, \text{Female}_i + \beta_3 \, \text{School}_i\times\text{Female}_i + u_i \]</span></p>
<p>Очікувана віддача від додаткового року навчання для жінок:</p>
<p><span class="math display">\[
\begin{aligned}
\mathop{\boldsymbol{E}}\left[ \text{Pay}_i | \text{Female} \land \text{School} = \ell + 1 \right] -
    \mathop{\boldsymbol{E}}\left[ \text{Pay}_i | \text{Female} \land \text{School} = \ell \right] &amp;= \\
\mathop{\boldsymbol{E}}\left[ \beta_0 + \beta_1 (\ell+1) + \beta_2 + \beta_3 (\ell + 1) + u_i \right] -
    \mathop{\boldsymbol{E}}\left[ \beta_0 + \beta_1 \ell + \beta_2 + \beta_3 \ell + u_i  \right] &amp;= \\
\beta_1 + \beta_3
\end{aligned}
\]</span></p>
<div class="fragment">
<p>Подібним чином <span class="math inline">\(\beta_1\)</span> дає очікувану віддачу від додаткового року навчання для чоловіків. Таким чином, <span class="math inline">\(\beta_3\)</span> дає <strong>різницю у віддачі від навчання</strong> для жінок і чоловіків.</p>
</div>
</section>
<section id="лог-лінійна-специфікація" class="slide level2 smaller">
<h2>Лог-лінійна специфікація</h2>
<p>В економіці ви часто побачите змінену залежну змінну (логарифмічну) з лінійними (не логарифмічну) пояснювальними змінними, <em>наприклад</em>,</p>
<p><span class="math display">\[ \log(\text{Pay}_i) = \beta_0 + \beta_1 \, \text{School}_i + u_i \]</span></p>
<p>Ця специфікація змінює нашу інтерпретацію коефіцієнтів нахилу.</p>
<p><strong>Інтерпретація</strong></p>
<ul>
<li><p>Збільшення нашої пояснювальної змінної на одну одиницю збільшує залежну змінну приблизно на <span class="math inline">\(\beta_1\times 100\)</span> відсотків.</p></li>
<li><p><em>Приклад:</em> Додатковий рік навчання збільшує платню приблизно на 3 відсотки (для <span class="math inline">\(\beta_1 = 0,03\)</span>).</p></li>
</ul>
</section>
<section id="лог-лінійна-специфікація-1" class="slide level2 smaller">
<h2>Лог-лінійна специфікація</h2>
<p><strong>Виведення</strong></p>
<p>Розглянемо лог-лінійну модель</p>
<p><span class="math display">\[ \log(y) = \beta_0 + \beta_1 \, x + u \]</span></p>
<p>і диференціал</p>
<p><span class="math display">\[ \dfrac{dy}{y} = \beta_1 dx \]</span></p>
<p>Таким чином, незначна зміна в <span class="math inline">\(x\)</span> (<em>тобто</em>, <span class="math inline">\(dx\)</span>) призводить до <span class="math inline">\(\beta_1 dx\)</span> <strong>відсоткової зміни</strong> в <span class="math inline">\(y\)</span>.</p>
</section>
<section id="лог-лінійна-специфікація-2" class="slide level2 smaller">
<h2>Лог-лінійна специфікація</h2>
<p>Оскільки логарифмічно-лінійна специфікація має іншу інтерпретацію, вам потрібно переконатися, що вона відповідає вашому процесу/моделі генерування даних.</p>
<p><span class="math inline">\(x\)</span> змінює <span class="math inline">\(y\)</span> у абсолютних значенняї (<em>наприклад</em>, збільшення на 3 одиниці) або у відсотках (<em>наприклад</em>, збільшення на 10 відсотків)?</p>
<div class="fragment">
<p><em>Тобто</em>, ви повинні бути впевнені, що експоненціальний зв’язок має сенс:</p>
<p><span class="math display">\[ \log(y_i) = \beta_0 + \beta_1 \, x_i + u_i \iff y_i = e^{\beta_0 + \beta_1 x_i + u_i} \]</span></p>
</div>
</section>
<section id="лог-лінійна-специфікація-3" class="slide level2">
<h2>Лог-лінійна специфікація</h2>

<img data-src=".00_files/figure-revealjs/log-liner-plot-output-1.svg" id="log-liner-plot" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="лог-логарифмічна-специфікація" class="slide level2">
<h2>Лог-логарифмічна специфікація</h2>
<p>Так само економетристи часто використовують логарифмічні моделі, в яких залежна змінна логарифмується <em>і</em> принаймні одна пояснювальна змінна логарифмується</p>
<p><span class="math display">\[ \log(\text{Pay}_i) = \beta_0 + \beta_1 \, \log(\text{School}_i) + u_i \]</span></p>
<p><strong>Інтерпретація:</strong></p>
<ul>
<li>Збільшення <span class="math inline">\(x\)</span> на один відсоток призведе до зміни <span class="math inline">\(y\)</span> на <span class="math inline">\(\beta_1\)</span> відсотків.</li>
<li>Часто трактується як еластичність.</li>
</ul>
</section>
<section id="лог-логарифмічна-специфікація-1" class="slide level2 smaller">
<h2>Лог-логарифмічна специфікація</h2>
<p><strong>Виведення</strong></p>
<p>Розглянемо модель log-log</p>
<p><span class="math display">\[ \log(y) = \beta_0 + \beta_1 \, \log(x) + u \]</span></p>
<p>і диференціал</p>
<p><span class="math display">\[ \dfrac{dy}{y} = \beta_1 \dfrac{dx}{x} \]</span></p>
<p>який говорить, що при збільшенні <span class="math inline">\(x\)</span> на один відсоток ми побачимо збільшення <span class="math inline">\(y\)</span> на <span class="math inline">\(\beta_1\)</span> відсоток. Як еластичність:</p>
<p><span class="math display">\[ \dfrac{dy}{dx} \dfrac{x}{y} = \beta_1 \]</span></p>
</section>
<section id="лог-лінійна-специфікація-з-бінарною-змінною" class="slide level2 smaller">
<h2>Лог-лінійна специфікація з бінарною змінною</h2>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Примітка</strong></p>
</div>
<div class="callout-content">
<p>Якщо у вас є логарифмічно-лінійна модель із двійковою змінною індикатора, інтерпретація коефіцієнта для цієї змінної змінюється.</p>
</div>
</div>
</div>
<p>Розглянемо</p>
<p><span class="math display">\[ \log(y_i) = \beta_0 + \beta_1 x_1 + u_i \]</span></p>
<p>для двійкової змінної <span class="math inline">\(x_1\)</span>.</p>
<p>Тепер інтерпретація <span class="math inline">\(\beta_1\)</span></p>
<ul>
<li>Коли <span class="math inline">\(x_1\)</span> змінюється з 0 на 1, <span class="math inline">\(y\)</span> зміниться на <span class="math inline">\(100 \times \left( e^{\beta_1} -1 \right)\)</span> відсотків.</li>
<li>Коли <span class="math inline">\(x_1\)</span> змінюється з 1 на 0, <span class="math inline">\(y\)</span> зміниться на <span class="math inline">\(100 \times \left( e^{-\beta_1} -1 \right)\)</span> відсотків.</li>
</ul>
</section>
<section id="лог-логарифмічна-специфікація-2" class="slide level2">
<h2>Лог-логарифмічна специфікація</h2>

<img data-src=".00_files/figure-revealjs/log-log-plot-output-1.svg" id="log-log-plot" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="контрольні-питання" class="slide level2 tiny scrollable">
<h2>Контрольні питання</h2>
<p><strong>Загальні Концепції та Кореляція</strong></p>
<ol type="1">
<li>Що таке коефіцієнт кореляції у статистичному сенсі? Які значення він може приймати?</li>
<li>Поясніть різницю між коваріацією та кореляцією. Чому кореляція часто є більш зручною мірою?</li>
<li>Наведіть формулу для коефіцієнта кореляції Пірсона.</li>
<li>Як перевіряється гіпотеза про те, що коефіцієнт кореляції дорівнює нулю (<span class="math inline">\(H_0: r = 0\)</span>)? Яка статистика критерію використовується?</li>
<li>Які основні умови (припущення) для коректного застосування t-критерію Стьюдента при перевірці гіпотези про кореляцію?</li>
<li>Що ілюструють приклади “Квартет Енскомба” та “Datasaurus Dozen” стосовно кореляційного та регресійного аналізу?</li>
<li>Що таке “хибна кореляція” (spurious correlation)? Наведіть приклад або поясніть суть явища.</li>
</ol>
<p><strong>Генеральна Сукупність, Вибірка та Основи Регресії</strong></p>
<ol start="8" type="1">
<li>Поясніть різницю між моделлю регресії для генеральної сукупності та моделлю регресії на основі вибірки. Які позначення використовуються для параметрів та залишків у кожному випадку?</li>
<li>Чому важливо розрізняти генеральну сукупність та вибірку при побудові регресійних моделей? Що ілюструє симуляція Монте-Карло на слайдах?</li>
<li>Що таке <span class="math inline">\(\hat{y}_i\)</span> у контексті регресійної моделі?</li>
</ol>
<p><strong>Оцінювання Параметрів Регресії (МНК)</strong></p>
<ol start="11" type="1">
<li>Що означає абревіатура МНК (OLS)? Який основний принцип цього методу?</li>
<li>Яку величину мінімізує метод найменших квадратів (МНК) для знаходження “найкращої” лінії регресії? Напишіть формулу.</li>
<li>Наведіть формули для оцінок МНК <span class="math inline">\(\hat{\beta}_0\)</span> та <span class="math inline">\(\hat{\beta}_1\)</span> у простій лінійній регресії.</li>
<li>Які основні властивості оцінок, отриманих методом МНК (з точки зору зміщення та дисперсії)? Що таке BLUE?</li>
</ol>
<p><strong>Припущення МНК та Невизначеність</strong></p>
<ol start="15" type="1">
<li>Перелічіть ключові припущення методу МНК.</li>
<li>Поясніть припущення екзогенності (<span class="math inline">\(\mathop{E}\left[ u \mid X \right] = 0\)</span>). Чому воно є важливим?</li>
<li>Як оцінюється дисперсія випадкових збурень (<span class="math inline">\(\sigma^2\)</span>) на основі вибіркових даних?</li>
<li>Що таке стандартна помилка оцінки коефіцієнта регресії (<span class="math inline">\(\mathop{\hat{\text{SE}}} \left( \hat{\beta}_1 \right)\)</span>)? Що вона показує?</li>
<li>Від чого залежить дисперсія (а отже, і стандартна помилка) оцінки коефіцієнта нахилу <span class="math inline">\(\hat{\beta}_1\)</span>?</li>
</ol>
<p><strong>Довірчі Інтервали та Перевірка Гіпотез</strong></p>
<ol start="20" type="1">
<li>Як будується довірчий інтервал для коефіцієнта регресії <span class="math inline">\(\beta_1\)</span>?</li>
<li>Як інтерпретується 95% довірчий інтервал для коефіцієнта <span class="math inline">\(\beta_1\)</span>?</li>
<li>Як формулюється типова нульова гіпотеза (<span class="math inline">\(H_0\)</span>) при перевірці значущості коефіцієнта регресії <span class="math inline">\(\beta_1\)</span>? Яка альтернативна гіпотеза (<span class="math inline">\(H_a\)</span>)?</li>
<li>Як розраховується t-статистика для перевірки гіпотези <span class="math inline">\(H_0: \beta_1 = c\)</span>?</li>
<li>Як приймається рішення про відхилення нульової гіпотези на основі t-статистики або p-значення?</li>
<li>У яких випадках використовується F-тест у регресійному аналізі? Чим він відрізняється від t-тесту?</li>
</ol>
<p><strong>Оцінювання Якості Моделі та Інтерпретація Коефіцієнтів</strong></p>
<ol start="26" type="1">
<li>Що таке коефіцієнт детермінації (<span class="math inline">\(R^2\)</span>)? Що він показує?</li>
<li>Яка основна проблема використання <span class="math inline">\(R^2\)</span> при порівнянні моделей з різною кількістю незалежних змінних?</li>
<li>Як скоригований <span class="math inline">\(R^2\)</span> (<span class="math inline">\(\overline{R}^2\)</span>) вирішує проблему звичайного <span class="math inline">\(R^2\)</span>?</li>
<li>Як інтерпретується коефіцієнт <span class="math inline">\(\beta_1\)</span> у моделі <span class="math inline">\(y = \beta_0 + \beta_1 x + u\)</span>, якщо <span class="math inline">\(x\)</span> та <span class="math inline">\(y\)</span> - неперервні змінні?</li>
<li>Як змінюється інтерпретація <span class="math inline">\(\beta_1\)</span> у множинній регресії <span class="math inline">\(y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + u\)</span>?</li>
<li>Як інтерпретуються коефіцієнти <span class="math inline">\(\beta_0\)</span> та <span class="math inline">\(\beta_1\)</span> у моделі <span class="math inline">\(y = \beta_0 + \beta_1 D + u\)</span>, де <span class="math inline">\(D\)</span> - фіктивна (бінарна 0/1) змінна?</li>
<li>Що дозволяє моделювати включення взаємодії між змінними (наприклад, <span class="math inline">\(x_1 \times x_2\)</span>)? Як інтерпретувати коефіцієнти в моделі з взаємодією?</li>
<li>Як інтерпретується коефіцієнт <span class="math inline">\(\beta_1\)</span> у лог-лінійній моделі <span class="math inline">\(\log(y) = \beta_0 + \beta_1 x + u\)</span>?</li>
<li>Як інтерпретується коефіцієнт <span class="math inline">\(\beta_1\)</span> у лог-логарифмічній моделі <span class="math inline">\(\log(y) = \beta_0 + \beta_1 \log(x) + u\)</span>?</li>
<li>Як інтерпретується коефіцієнт <span class="math inline">\(\beta_1\)</span> для бінарної змінної <span class="math inline">\(x_1\)</span> у лог-лінійній моделі <span class="math inline">\(\log(y) = \beta_0 + \beta_1 x_1 + u\)</span>?</li>
</ol>
</section>
<section id="додаткові-матеріали" class="slide level2 scrollable">
<h2>Додаткові матеріали</h2>
<ul>
<li><a href="https://github.com/Aranaur/aranaur.rbind.io/blob/main/lectures/asa/slides/2024/.00.qmd">Github: код лекції</a></li>
<li><a href="https://openintro.shinyapps.io/correlation_game/">Correlation game</a></li>
<li><a href="https://markeltsefon.medium.com/building-connections-for-a-b-testing-and-linear-regression-51130c492c52">Building connections for A/B testing and linear regression</a></li>
<li><a href="https://engineering.atspotify.com/2023/09/how-to-accurately-test-significance-with-difference-in-difference-models/">Spotify: How to Accurately Test Significance with Difference in Difference Models</a></li>
</ul>
</section></section>
<section id="дякую-за-увагу" class="title-slide slide level1 unnumbered unlisted center" data-background-color="#eef3f8">
<h1>Дякую за увагу!</h1>
<p><br> <br></p>
<p><iconify-icon inline="" icon="ic:baseline-telegram"></iconify-icon> <a href="https://t.me/araprof"><span class="citation" data-cites="araprof">@araprof</span></a></p>
<p><iconify-icon inline="" icon="mdi:youtube"></iconify-icon> <a href="https://www.youtube.com/@datamirosh"><span class="citation" data-cites="datamirosh">@datamirosh</span></a></p>
<p><iconify-icon inline="" icon="ion:home"></iconify-icon> <a href="https://aranaur.rbind.io">aranaur.rbind.io</a></p>
<p><iconify-icon inline="" icon="mdi:github"></iconify-icon> <a href="https://github.com/Aranaur">aranaur</a></p>
<p><iconify-icon inline="" icon="mdi:envelope"></iconify-icon> <a href="mailto:ihor.miroshnychenko@knu.ua" class="email">ihor.miroshnychenko@knu.ua</a></p>
<p><iconify-icon inline="" icon="mdi:linkedin"></iconify-icon> <a href="https://www.linkedin.com/in/ihormiroshnychenko/">ihormiroshnychenko</a></p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="fit.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://aranaur.rbind.io/lectures/asa/">🔗Прикладний статистичний аналіз</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src=".00_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src=".00_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src=".00_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src=".00_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src=".00_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src=".00_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src=".00_files/libs/revealjs/plugin/verticator/verticator.js"></script>
  <script src=".00_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src=".00_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src=".00_files/libs/revealjs/plugin/search/search.js"></script>
  <script src=".00_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src=".00_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'verticator': {"themetag":"h1","color":"","inversecolor":"","skipuncounted":false,"clickable":true,"position":"auto","offset":"3vmin","autogenerate":true,"tooltip":false,"scale":1},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'h.v',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'default',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: true,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: true,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1350,

        height: 759.375,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, Verticator, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Скопійовано!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Скопійовано!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>