---
title: "Модульний контроль"
subtitle: "Прикладний статистичний аналіз"
author: "Ігор Мірошниченко"
institute: КНУ імені Тараса Шевченка, ФІТ
from: markdown+emoji
language: _language-ua.yml
footer: <a href="https://aranaur.rbind.io/lectures/asa/">🔗Прикладний статистичний аналіз</a>
format:
  html:
    toc: true
preload-iframes: true
jupyter: python3
execute: 
  echo: true
  warning: false
editor_options: 
  chunk_output_type: console

revealjs-plugins:
  - verticator
---

```{python}
#| label: setup
#| include: false

# Import libraries
from scipy.stats import (
    norm, binom, expon, t, chi2, pareto, ttest_ind, sem, beta, laplace
)
from statsmodels.stats.proportion import proportion_confint
import numpy as numpy
from seaborn import distplot
from matplotlib import pyplot
import seaborn

from IPython.display import Markdown
from tabulate import tabulate

# Define colors
red_pink   = "#e64173"
turquoise  = "#20B2AA"
orange     = "#FFA500"
red        = "#fb6107"
blue       = "#181485"
navy       = "#150E37FF"
green      = "#8bb174"
yellow     = "#D8BD44"
purple     = "#6A5ACD"
slate      = "#314f4f"
```

# Пакети

В цьому модулі ми будемо використовувати наступні пакети:

```{python}
#| label: packages

from collections import namedtuple
from scipy.stats import binom
import math
import numpy as np
```

[Восьминіг Пауль](https://uk.wikipedia.org/wiki/Восьминіг_Пауль) 13 разів намагався вгадати переможця футбольного матчу.

11 разів він угадав правильно, 2 рази --- помилився. Ми хочемо перевірити гіпотезу:

 - $H_0$: восьминіг вгадує переможця матчу з ймовірністю 0.5
 - $H_1$: восьминіг вибирає переможця матчу з ймовірністю $\neq$ 0.5

Вам потрібно розробити статистичний критерій для перевірки цієї гіпотези, а також порахувати $p$-значення.

- $H_0: p = 0.5$
- $H_1: p \neq 0.5$  
- $S(X) = \sum\limits_{i=1}^n X_i \sim Binom(n, 0.5)$ за правильності гіпотези $H_0$  
- Критерій: $\bigl\{ S(X) \gt u_{1-\frac{\alpha}{2}} \bigr\} \cup \bigl\{ S(X) \lt u_{\frac{\alpha}{2}} \bigr\}$,
    + де $u_{\beta}$ - критичне значення, що дорівнює $\beta$-квантилю $Binom(n, 0.5)$,  
- $p$-значення = $2 \cdot \text{min}\bigl[P\bigl( S(X) \geqslant S_0 \, | \, H_0\bigr), \, P\bigl( S(X) \leqslant S_0 \, | \, H_0\bigr) \bigr]$, 
    + де $S_0$ - значення статистики від заданої вибірки

## Завдання 1

Реалізуйте критерій `check_paul_criterion(n, k, alpha)`, де:

- `n` &mdash; кількість матчів;
- `k` &mdash; кількість вірних передбачень від восьминога;
- `alpha` &mdash; рівень значущості критерію.

Функція має повернути `PaulCheckResults` з полями:

- `is_rejected`: відкинулася чи ні гіпотеза $H_0$ на рівні значущості $\alpha$
- `pvalue`: $p$-значення


```{python}
#| label: task_1
#| eval: false

PaulCheckResults = namedtuple('PaulCheckResults', ['is_rejected', 'pvalue'])

def check_paul_criterion(n: int, k: int, alpha: float = 0.05):
    """
    Ваш опиc тут
    ⋅˚₊‧ ଳ ‧₊˚ ⋅
    """

    # Ваш код тут
    # 𓇼 ⋆｡˚ 𓆝⋆｡˚ 𓇼

    return PaulCheckResults(is_rejected, pvalue)
```

## Завдання 2

1. Які висновки можна зробити з отриманого результату?
2. Визначіть критичну область критерію для заданого `n`.

## Завдання 3

1. Побудуйте довірчий інтервал для ймовірності вгадування восьминога.
2. Як можна інтерпретувати цей інтервал?