---
title: "Лабораторна робота №1"
subtitle: "Вступ у Data Science"
---

# Частина 1: Основи мови програмування R

## Завдання 1: Вектори

Ви торгуєте двома видами криптовалют: Біткоїн (BTC) та Ефіріум (ETH).
За тиждень торгів ви отримали наступні результати:

Для BTC:

    - Понеділок заробили 140$
    - Вівторок втратили 50$
    - Середа заробили 20$
    - Четвер втратили 120$
    - П'ятниця заробили 240$

Для ETH:

    - Понеділок втратили 24$
    - Вівторок втратили 50$
    - Середа заробили 100$
    - Четвер втратили 350$
    - П'ятниця заробили 10$

Ви вирішили проаналізувати результати тижня за допомогою R.

1. Створіть вектор `btc` з результатами торгів Біткоїном.
2. Створіть вектор `eth` з результатами торгів Ефіріумом.
3. Створіть вектор `profit` з результатами торгів за весь тиждень.
4. Порівняйте результати торгів Біткоїном та Ефіріумом за допомогою оператора `>`.

## Завдання 2: Data Frame

Ви вирішили проаналізувати результати торгів за допомогою Data Frame. Для цього ви створили два вектори: `day` та `profit`. Вектор `day` містить назви днів тижня, а вектор `profit` - результати торгів за весь тиждень.

1. Створіть Data Frame `trades` з векторів `day` та `profit`.
2. Виведіть перші 6 рядків Data Frame `trades`.
3. Виведіть останні 6 рядків Data Frame `trades`.
4. Перегляньте структуру Data Frame `trades`.

# Частина 2: Tidyverse

## Завдання 1: Завантаження та перегляд даних

1. Завантажте власний набір даних.
2. Проведіть обробку даних: перевірте тип даних, видаліть зайві стовпці, перейменуйте стовпці, тощо.
3. Згрупуйте дані за допомогою функції `group_by()` та розрахуйте основні статистичні показники для кожної групи.
