---
title: "A/B-тестування"
subtitle: "Прикладний статистичний аналіз"
author: "Ігор Мірошниченко"
institute: КНУ імені Тараса Шевченка | ФІТ
# date: today
# date-format: iso
from: markdown+emoji
title-slide-attributes:
  data-background-iframe: .03_files/libs/colored-particles/index.html
#   data-background-color: "#eef3f8"
language: _language-ua.yml
footer: 🔗 <a href="https://aranaur.rbind.io/lectures/asa/">Матеріали курсу</a>
format: 
  revealjs:
    transition: fade
    chalkboard: true
    logo: img/fit.png
    code-line-numbers: false
    slide-number: c/t
    mouse-wheel: true
    width: 1350  
    height: 759.375
    highlight-style: github
    pdf-separate-fragments: true
    # fig-height: 7.5
    # fig-width: 15
    fig-align: center
    fig-format: svg
    theme: [default, custom.scss]
jupyter: python3
execute: 
  warning: false
  echo: true
  # cache: true

---

```{python}
#| label: setup
#| include: false

# Import libraries
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm, uniform

from IPython.display import Markdown
from tabulate import tabulate

# Set seaborn default style
sns.set_style('whitegrid')
sns.set_palette('colorblind')

# Define colors
red_pink   = "#e64173"
turquoise  = "#20B2AA"
orange     = "#FFA500"
red        = "#fb6107"
blue       = "#181485"
navy       = "#150E37FF"
green      = "#8bb174"
yellow     = "#D8BD44"
# grey_light = "grey70"
# grey_mid   = "grey50"
# grey_dark  = "grey20"
purple     = "#6A5ACD"
slate      = "#314f4f"
```

# Дизайн A/B експерименту {background-color="#eef3f8"}

## Навіщо це потрібно

- Розробка будь-якого продукту - процес постійних поліпшень
- Очікуване поліпшення не завжди насправді покращує продукт - новий функціонал може бути нікому не потрібен
або реалізація псує всю витівку
- Кожна ідея потребує перевірки - інакше наш продукт піде не в той бік

## Навіщо це потрібно

- Перевіряти ідеї (гіпотези) можна по-різному:
  + Обговорити з колегами
  + Опитати користувачів
  + Поспілкуватися детально з групою користувачів
  + ...
- У деяких випадках запитати або поговорити
недостатньо

## Навіщо це потрібно

Не все можна спитати:

- Про новий алгоритм ранжування фотографій у соціальній мережі
- Чи не зламалося щось під час переїзду інфраструктури на нові технології
- Про інший алгоритм ціноутворення
- Про нові інструкції служби підтримки

## A/B тестування

- A/B тестування - це експеримент, який дозволяє перевірити, як працює новий функціонал
- Для цього випадково обирається частина користувачів, які отримують новий функціонал
- Інша частина користувачів отримує старий функціонал
- Потім порівнюється, як користувачі взаємодіють з новим і старим функціоналом за допомогою певних метрик
- Очікуємо, що групи користувачів будуть вести себе однаково, якщо новий функціонал не впливає на їх поведінку
- Спостереження (користувачі) незалежні одне від одного

## A/B тестування

- Не дивлячись на те, що користувачі обираються з однієї генеральної сукупності - метрики будуть відрізнятися
- Статистичні критерії дозволяють перевірити, чи є різниця між групами статистично значущою

## Основні складові A/B тестування

- **Гіпотеза** - що саме ми перевіряємо
- **Метрики** - які метрики ми використовуємо для оцінки експерименту
- **Розмір вибірки** - скільки користувачів ми вибираємо для експерименту
- **Розподіл користувачів** - як ми розподіляємо користувачів на групи
- **Збір метрик** - тривалість експерименту

## Гіпотеза

- Гіпотеза - це твердження, яке ми перевіряємо за допомогою експерименту
- Гіпотеза може бути як позитивною, так і негативною
- Позитивна гіпотеза - це твердження, що новий функціонал покращує якусь метрику
- Негативна гіпотеза - це твердження, що новий функціонал не покращує якусь метрику

## Метрики

- Метрики - це числові характеристики, які ми використовуємо для оцінки експерименту
- Ми заздалегідь повинні знати, що будемо вимірювати
- Зазвичай у продукту є декілька метрик, які використовуються для оцінки ефективності:
  + Основні метрики - середній чек, конверсія, дохід
  + Допоміжні метрики (проксі-метрики) - додавання товару у кошик, конверсія етапів воронки, оцінки користувачів
- Метрики повинні бути достатньо чутливими до змін, які ми хочемо виміряти
- Існують метрики, на котрі ми безпосередньо впливаємо своїми діями

Наприклад, якщо ми покращуємо алгоритм пошуку, то ми можемо виміряти, як змінилася конверсія пошуку

## Допоміжні метрики

В ідеалі, ми б вимірювали основні метрики (дохід компанії), але це не завжди можливо:

- Багато метрик не чутливі до малих змін в продукті (наприклад, середній чек)
- Чутливі проксі-метрики дозволяють оцінити якість зміни в продукті

## Приклад: сервіс таксі

- Ми - сервіс таксі
- Оновили дизайн карт для вибору точки призначення
- Основні метрики:
  + дохід на одного користувача
  + конверсія з відкриття додатку до замовлення
  + кількість подорожей на одного користувача у тиждень
- Допоміжні метрики:
  + конверсії по етапам воронки
  + час, який користувач проводить у додатку
- Кількість натискань для вибору точки, час на вибір точки - метрики, на котрі ми впливаємо в першу чергу

## Приклад: додаток для ведення заміток

- Оновили інтерфейс форматування тексту
- Основні метрики:
  + дохід на користувача
  + кількість заміток на користувача в тиждень
  + повернення користувача на наступний день
- Допоміжні метрики:
  + час на створення замітки
  + кількість використання заміток на день
- Кількість заміток з форматування в день, частка використаного функціоналу для форматування - метрики, на котрі ми впливаємо в першу чергу

## Пріоритетність метрик

- Коли метрик багато, слід визначити, які метрики важливіші
- Основні метрики можна поділити на [грошові]{.hi} та [продуктові]{.purple}
- У кожного продукту можуть бути свої головні метрики:
  + На стадії активного росту - це зазвичай продуктові метрики
  + На стадії зрілості - це зазвичай грошові метрики
  + Коли з одним користувачем все гаразд, акцент може перейти на іншу метрику

## Помилки при прийнятті рішень

- Ми використовуємо статистичні критерії для перевірки гіпотези
- Можемо зіткнутися з двома помилками:
  + **Хибнопозитивні** (англ. *false positive*) - коли ми відкидаємо нульову гіпотезу, хоча вона насправді є правильною
  + **Хибнонегативні** (англ. *false negative**) - коли ми приймаємо нульову гіпотезу, хоча вона насправді є неправильною

## Хибнопозитивна помилка

- Порівняли дві групи
- Помилково вважаємо, що між групами є різниця

Така помилка фіксується за допомогою вибору рівня значущості $\alpha$ і коректного використання системи тестування

## Хибнонегативна помилка

- Порівняли дві групи
- Помилково вважаємо, що між групами немає різниці

Визначається потужністю критеріїв та кількістю спостережень

## Розбиття користувачів на групи

- Основна мета --- створити контрольну і тестову вибірку так, щоб вони були максимально схожі
- Досягається за рахунок випадкового розподілу користувачів на групи
- Розбиття повинно бути відтворюваним
- Зазвичай реалізується через використання [хеш-функції]{.hi} від ідентифікатора користувача з певною [сіллю]{.purple}

## Хеш-функція та сіль

- Хеш-функція - це функція, яка перетворює будь-який об'єкт на випадковий набір байтів
- Хеш-функція має властивість, що при однакових вхідних даних вона завжди повертає один і той же результат
- Сіль - це додатковий параметр, який додається до вхідних даних
- Сіль дозволяє змінити результат хеш-функції, якщо вхідні дані не змінилися

## Приклад {.smaller}

Згенеруємо тестові дані для розбиття на групи:

```{python}
#| label: data-gen

import pandas as pd
import numpy as np

np.random.seed(1234)

user_id = np.random.choice(range(1000), size=1000, replace=False)

df = pd.DataFrame({'user_id': user_id})
df
```

## Приклад {.smaller}

Використаємо md5-хеш-функцію для розбиття на групи:

```{python}
#| label: hash

import hashlib

# Тестові дані
salt = 'test'
user = 'id_999'

# Об'єднуємо дані
value_str = user + salt

# Перетворюємо в байти
value_num = int(hashlib.md5(value_str.encode('utf-8')).hexdigest(), 16)

# Розбиваємо на групи за допомогою остачі від ділення
value_num % 100
```

## Приклад {.smaller}

Застосуємо до всіх користувачів:

```{python}
#| label: hash-apply

# Створюємо функцію для розбиття на групи
def hash_group(user_id, salt, n_groups):
    value_str = str(user_id) + str(salt)
    value_num = int(hashlib.md5(value_str.encode()).hexdigest(), 16)
    return value_num % n_groups

salt = 'test_1'
n_groups = 2

# Застосовуємо функцію до всіх користувачів
df['group'] = df['user_id'].apply(hash_group, args=(salt, n_groups))

# Перевіряємо розподіл користувачів
df['group'].value_counts()
```

## Приклад

Розбиття на групи можна перевіряти за кількістю користувачів у групах. І якщо це не так, слід розбиратися, чому так сталося.

Можливо ми використовуємо хеш-функцію, котра розбиває користувачів на групи нерівномірно.

## Розмір вибірки

Розмір вибірки - це кількість користувачів, які беруть участь у експерименті

Дані мають бути репрезентативними для генеральної сукупності:

- без свят
- тижневі цикли
- випадкова вибірка користувачів

Кількість даних залежить від очікуваного ефекту та критеріїв, які ми використовуємо для перевірки гіпотези

## Оцінювання ефекту

- Після збору даних ми отримуємо дві незалежні вибірки
- Зазвичай, використовуємо статистичний критерій для перевірки рівності середніх
- Якщо ми відкидаємо нульову гіпотезу, то ми приймаємо альтернативну гіпотезу
- Рівень значущості $\alpha$ фіксуємо заздалегідь

## Етапи A/B тестування

1. Вибір метрик
2. Вибір розмірів груп і тривалість експерименту
3. Запуск експерименту і збір метрик
4. Оцінювання результату

# A/A-експерименти і валідація метрик {background-color="#eef3f8"}

---



---


# Дякую за увагу! {background-color="#eef3f8"}

<br>
<br>

{{< iconify ic baseline-telegram >}} [@araprof](https://t.me/araprof)

{{< iconify mdi youtube >}} [@datamirosh](https://www.youtube.com/@datamirosh)

{{< iconify ion home >}} [aranaur.rbind.io](https://aranaur.rbind.io)

{{< iconify mdi github >}} [aranaur](https://github.com/Aranaur)

{{< iconify mdi envelope >}} <ihor.miroshnychenko@knu.ua>

{{< iconify mdi linkedin >}} [ihormiroshnychenko](https://www.linkedin.com/in/ihormiroshnychenko/)
