---
title: "Основи 🔥PyTorch"
subtitle: "Технології комп'ютерного зору"
author: "Ігор Мірошниченко"
institute: КНУ імені Тараса Шевченка
format:
  html: 
    highlight-style: github
    theme: [default, custom.scss]
    lang: ua
execute: 
  echo: true
  warning: false
editor_options: 
  chunk_output_type: console
---

```{python}
#| include: false
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
```

1. Читання документації

Важливою частиною глибокого навчання (і навчання програмуванню в цілому) є ознайомлення з документацією певного фреймворку, який ви використовуєте. Тому я рекомендую витратити 10 хвилин на прочитання наступного матеріалу (не біда, якщо ви поки що не все зрозумієте, адже головне не повне розуміння, а усвідомлення):

  - Документація про [`torch.Tensor`](https://docs.pytorch.org/docs/stable/tensors.html#torch-tensor).
  - Документація про [`torch.cuda`](https://docs.pytorch.org/docs/main/notes/cuda.html#cuda-semantics).

2. Створіть випадковий тензор з формою `(7, 7)`.
3. Виконайте множення матриць на тензор з 2 з іншим випадковим тензором з формою `(1, 7)`.
4. Встановіть випадкове початкове значення на `0` і повторіть кроки 2 і 3.

::: {.callout-tip collapse="true"}
## Очікуваний результат

```{python}
#| echo: false

torch.manual_seed(0)
a = torch.rand((7, 7))
b = torch.rand((1, 7)).T
c = torch.matmul(a, b)
print(c, c.shape)
```
:::

5. Говорячи про випадкові генератори, ми бачили, як встановити його за допомогою `torch.manual_seed()`, але чи існує еквівалент для GPU[^gpu]?
    + Якщо є, встановіть початкове значення GPU на `1234`.

[^gpu]: Підказка: для цього вам потрібно буде заглянути в документацію до `torch.cuda`

6. Створіть два випадкові тензори форми `(2, 3)` і надішліть їх обидва на GPU (для цього вам знадобиться доступ до GPU). При створенні тензорів встановіть `torch.manual_seed(1234)`.

::: {.callout-tip collapse="true"}
## Очікуваний результат

```{python}
#| echo: false

torch.manual_seed(1234)
a = torch.rand((2, 3)).cuda()
b = torch.rand((2, 3)).cuda()
print(f'Using device: {a.device}')
print(a, a.shape)
print(b, b.shape)
```
:::


7. Виконайте множення матриць на тензори, які ви створили в пункті 6 (знову ж таки, можливо, доведеться скоригувати форми одного з тензорів).

::: {.callout-tip collapse="true"}
## Очікуваний результат

```{python}
#| echo: false

c = torch.matmul(a, b.T)
print(c, c.shape)
```
:::

8. Знайдіть максимальне та мінімальне значення виходу 7.
9. Знайдіть максимальне та мінімальне значення індексу результату 7.
10. Створіть випадковий тензор з формою `(1, 1, 1, 10)`, а потім створіть новий тензор, з якого видалені всі розміри `1`, щоб залишився тензор з формою `(10)`. При створенні встановіть початкове значення `7` й виведіть на екран перший тензор і його форму, а також другий тензор і його форму.

::: {.callout-tip collapse="true"}
## Очікуваний результат

```{python}
#| echo: false

torch.manual_seed(7)
a = torch.rand((1, 1, 1, 10))
b = a.squeeze()
print(a, a.shape)
print(b, b.shape)
```
:::
