---
title: "Робочий процес 🔥PyTorch"
subtitle: "Технології комп'ютерного зору"
author: "Ігор Мірошниченко"
institute: КНУ імені Тараса Шевченка
format:
  html: 
    highlight-style: github
    theme: [default, custom.scss]
    lang: ua
execute: 
  echo: true
  warning: false
editor_options: 
  chunk_output_type: console
---

```{python}
#| include: false
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

red_pink   = "#e64173"
turquoise  = "#20B2AA"
orange     = "#FFA500"
red        = "#fb6107"
blue       = "#181485"
navy       = "#150E37FF"
green      = "#8bb174"
yellow     = "#D8BD44"
purple     = "#6A5ACD"
slate      = "#314f4f"
```

1. Створіть набір даних прямої лінії, використовуючи формулу лінійної регресії (`bias + weight * X`), а також додайте трохи випадкового шуму (наприклад, `torch.randn()`). При цьому самостійно оберіть початкове значення генератора випадкових чисел.
    * Випадково оберіть `bias` і `weight`. Точок має бути 100+. 
    * Розділіть дані на 80% для навчальної та 20% для тестової вибірки.
    * Побудуйте графік даних.

::: {.callout-tip collapse="true"}
## Очікуваний результат

```{python}
#| echo: false

import matplotlib.pyplot as plt
torch.manual_seed(42)
X = torch.arange(0, 1, 0.01).unsqueeze(1)
bias = torch.rand(1)
weight = torch.rand(1)
y = bias + weight * X + 0.02 * torch.randn(X.shape)
plt.scatter(X, y, color=turquoise, s=10)
plt.xlabel("X")
plt.ylabel("y")
plt.title("Generated linear data with noise")
plt.show()
```
:::

2. Створіть модель PyTorch, створивши підклас `nn.Module`.
    * Всередині повинен бути випадково ініціалізований `nn.Parameter()` з `requires_grad=True`, один для `weights` і один для `bias`. 
    * Реалізуйте метод `forward()` для обчислення функції лінійної регресії, яку ви використовували для створення набору даних в 1. 
    * Після побудови моделі створіть її екземпляр і перевірте його `state_dict()`.
  
::: {.callout-note}
Якщо ви хочете використовувати `nn.Linear()` замість `nn.Parameter()`, ви можете це зробити.
:::

3. Створіть функцію втрат та оптимізатор, використовуючи відповідно `nn.L1Loss()` та `torch.optim.SGD(params, lr)`. 
    * Встановіть швидкість навчання оптимізатора на `0.01`, а параметрами для оптимізації мають бути параметри моделі, яку ви створили в пункті 2.
    * Напишіть цикл навчання, щоб виконати відповідні кроки навчання протягом 300 епох.
    * Цикл навчання повинен тестувати модель на тестовому наборі даних кожні 20 епох.

4. Зробіть прогнози за допомогою навченої моделі на тестових даних.
    * Візуалізуйте ці прогнози на тлі оригінальних навчальних і тестових даних.
    
::: {.callout-note}
Якщо ви хочете використовувати бібліотеки, що не підтримують CUDA, такі як `matplotlib`, для побудови графіків, вам може знадобитися переконатися, що прогнози *не* виконуються на GPU.
:::

5. Збережіть `state_dict()` вашої навченої моделі у файлі.
    * Створіть новий екземпляр класу моделі, який ви створили в пункті 2, і завантажте в нього щойно збережений `state_dict()`.
    * Виконайте прогнозування на ваших тестових даних за допомогою завантаженої моделі та переконайтеся, що вони відповідають прогнозам оригінальної моделі з пункту 4.