---
title: "Власні набори даних 🔥PyTorch"
subtitle: "Технології комп'ютерного зору"
author: "Ігор Мірошниченко"
institute: КНУ імені Тараса Шевченка
format:
  html: 
    highlight-style: github
    theme: [default, custom.scss]
    lang: ua
execute: 
  echo: true
  warning: false
editor_options: 
  chunk_output_type: console
---

1. Відтворіть функції завантаження даних, які ми створили на лекції. Ви повинні мати готові до використання `DataLoader` для навчання та тестування.
2. У наших папках є кілька зображень. Тепер нам потрібно зробити їх сумісними з PyTorch, виконавши такі дії:
    a. Перетворити дані в тензори.
    b. Перетворити дані тензора в `torch.utils.data.Dataset`, а потім в `torch.utils.data.DataLoader`.
3. Завантажити дані зображення за допомогою `ImageFolder`
4. Відтворіть `model_0`, яку ми побудували.
5. Створити функції навчання та тестування для `model_0`.
6. Спробуйте навчити модель протягом 5, 20 і 50 епох. Що відбудеться з результатами?
    + Використовуйте `torch.optim.Adam()` з кроком навчання 0,001.
7. Подвійте кількість прихованих одиниць у вашій моделі та навчіть її протягом 20 епох. Що станеться з результатами?
8. Подвійте обсяг даних, які ви використовуєте у своїй моделі, і навчіть її протягом 20 епох. Що станеться з результатами?
9. Зробіть прогноз на основі власного зображення. Чи правильно працює модель, яку ви навчили? Якщо ні, що, на вашу думку, можна зробити, щоб її вдосконалити?
