---
title: Лабораторна робота №1
subtitle: Візуалізація часових рядів
---

::: {.callout-note}
Це орієнтовний план лабораторної роботи. Ви можете модифікувати завдання відповідно до ваших потреб та бажань.
:::

# Завдання

1. **Збір та підготовка даних:**
    - Оберіть часовий ряд для аналізу (можна використовувати власний набір даних або скористатися публічно доступними наборами).
    - Зчитайте дані та перевірте їхню коректність.
    - Здійсніть очистку та підготовку даних для подальшої обробки.
2. **Візуалізація основних характеристик:**
    - Побудуйте графік часового ряду.
    - Вивчіть базові характеристики часового ряду: тренд, сезонність, аномалії.
    - Використайте графіки розсіювання для вивчення взаємозв'язків між обраними змінними.
3. **Кореляційний аналіз:**
    - Визначте кореляції між різними часовими періодами у вашому ряді.
    - Визначте кореляції між різними часовими періодами з іншими змінними.

::: {.callout-important}
Звіт з лабораторної роботи необхідно оформити за допомогою Quarto.
:::