---
title: Лабораторна робота №2
subtitle: Декомпозиція часових рядів
---

::: {.callout-note}
Це орієнтовний план лабораторної роботи. Ви можете модифікувати завдання відповідно до ваших потреб та бажань.
:::

# Завдання

1. **Практична частина:**
    - Завантажте набір часових рядів для подальшого аналізу. Рекомендується використовувати реальні дані, наприклад, з публічних джерел або спеціалізованих платформ для навчання.
    - Застосуйте методи перетворення часових рядів до вибраного набору даних.
    - Використовуйте різні підходи до декомпозиції: з перетворенням, без перетворення, тощо.
2. **Аналітична частина:**
    - Порівняйте отримані результати після застосування різних методів перетворення та декомпозиції.
    - Визначте, які методи та підходи найкраще підходять для конкретного типу часового ряду.
    - Сформулюйте висновки щодо ефективності різних методів перетворення та підходів до декомпозиції часових рядів.
    - Запропонуйте можливі застосування отриманих знань у практичних задачах прогнозування часових рядів.

::: {.callout-important}
Звіт з лабораторної роботи необхідно оформити за допомогою Quarto.
:::