---
title: "Assignment 03: Reproducible publishing with Quarto"
subtitle: "STAT 150: R for Data Science"
author: "Ihor Miroshnychenko"
institute: Kyiv School of Economics
format:
  html: 
    highlight-style: github
    theme: [default, custom.scss]
execute: 
  echo: true
  warning: false
editor_options: 
  chunk_output_type: console
---

## 🎯 Learning Objectives

After completing this assignment, you should be able to:

- Create reproducible documents using Quarto.
- Integrate R code and narrative text seamlessly.
- Render documents to various formats (HTML, PDF, Word).
- Use Quarto extensions to enhance document functionality and appearance.

## 📝 Tasks: your CV

In this assignment, you will create a simple CV using Quarto. The CV should include the following sections[^sections]:

[^sections]: It's only a suggestion. You can modify the sections as per your preference.

- Personal Information (name, contact details, LinkedIn/GitHub links)
- Education (degrees, institutions, graduation dates)
- Work Experience (job titles, companies, dates, responsibilities)
- Skills (programming languages, tools, technologies)
- Projects (brief descriptions and links to GitHub repositories or live demos). If you do not have any projects yet, you can indicate which courses you have completed and what skills you have acquired.

::: {.callout-note}
**Try to think ahead:** as you gain new skills and experience, you must update your resume. It is a good idea to keep all your achievements in a separate file and refer to it to update/add to your achievements. Use code chunks for this.
:::

### Instructions

1. Create a new Quarto document (`.qmd` file).
2. Create a CV using Quarto.
3. Add a YAML header at the top of the document with appropriate metadata (title, author, date, output format).
4. Render the Quarto document to PDF format.

::: {.callout-tip}
Next tips can help you to make your CV more attractive and informative:

- You can use the [Quarto CV template](https://github.com/schochastics/quarto-cv) as a starting point.
- [Iconify](https://github.com/mcanouil/quarto-iconify), [Font Awesome](https://github.com/quarto-ext/fontawesome) and [Academicons](https://github.com/schochastics/academicons/tree/main) extensions for Quarto provide a wide range of icons that you can use to enhance the visual appeal of your CV.
- You can use [`gt`](https://gt.rstudio.com/) package and/or [`kableExtra`](https://haozhu233.github.io/kableExtra/) package to create beautiful tables in your CV.
- [Quarto Publishing](https://quarto.org/docs/publishing/) provides detailed instructions on how to publish your Quarto documents to various platforms.
:::

## 📤 Submission

Submit the `.qmd` file, and rendered document (PDF) to the assignment submission portal.

