---
title: "Прикладний статистичний аналіз"
author: "Посилання до варіантів"
lang: ua
date: 2024-06-14
date-format: iso
format: html
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(gt)
```

```{r echo=FALSE}
set.seed(20240614)
tibble(
  `ПІБ` = c(
    "Абрамов Кірілл Вікторович",
    "Білуха Назар Романович",
    "Гамзін Нікіта Сергійович",
    "Ільчук Олександр Михайлович",
    "Книш Сніжана Михайлівна",
    "Лаврій Руслан Романович",
    "Лаврій Софія Петрівна",
    "Майданик Андрій Олександрович",
    "Марчук Дмитро Андрійович",
    "Мінін Ігор Борисович",
    "Немченко Катерина Юріївна",
    "Нечипорук Вікторія Олександрівна",
    "Орищак Богдан Ігорович",
    "Пелішенко Владислав Святославович",
    "Подольський Нікіта Володимирович",
    "Прохорчук Дмитро Сергійович",
    "Рудківський Євгеній Віталійович",
    "Українець Андрій Олександрович",
    "Харламов Юрій Сергійович",
    "Шпирук Євгенія Сергіївна"
    ),
  `Варіант` = c(sample(1:3, 20, replace = TRUE)
                )
  ) %>% 
  mutate(url = case_when(`Варіант` == 1 ~ "https://forms.gle/hN9u9NfHhoJsBSe5A",
                         `Варіант` == 2 ~ "https://forms.gle/bpHmPAF6PG3r2D7B7",
                         `Варіант` == 3 ~ "https://forms.gle/GCTppZCWDXDkL6W3A"),
         `Варіант` = NULL) %>%
  arrange(`ПІБ`) %>% 
  mutate(url = map(url, ~ htmltools::a(href = .x, "посилання")),
        url = map(url, ~ gt::html(as.character(.x)))) %>%
  gt()
```

