---
title: Завдання №1
subtitle: "Прикладна аналітика"
format:
    html: default
---

Дослідимо набір [даних про відеоігри](https://aranaur.rbind.io/datasets/video_games_sales/), обсяг продажів яких склав понад 100 000 копій.

## Завдання

1. Перший крок --- завантажити дані та переконатися, що все рахувалося правильно: подивитися на стовпці, розмір, наявність пропущених значень (якщо є --- видалити). Також вивчіть типи змінних.
2. Побудуйте графік розподілу кількості випущених ігор за роками та виведіть описові характеристики змінної `Year`.
3. На яких платформах відбулося найбільше релізів?
4. Ігри яких видавців (`Publisher`) зустрічаються в датасеті найчастіше?
5. У якому регіоні медіанне значення обсягу продажів ігор `Nintendo` є найбільшим? (Регіони: `NA`, `EU`, `JP`, `Other`)
6. Вивчіть обсяги продажів ігор `Nintendo` в Японії з розбивкою за жанрами. Подивіться на медіану, середнє, міжквартильний розмах.
7. Візуалізуйте динаміку зміни обсягу світових продажів (`Global_Sales`) за роками для ігор `Nintendo` таких жанрів: `Fighting`, `Simulation`, `Platform`, `Racing`, `Sports`. У які моменти часу було продано найбільше ігор жанру `Sports`?

### Опис даних

Є такі поля:

* `Rank` --- місце за обсягом продажів
* `Name` --- назва гри
* `Platform` --- платформа, на якій випущено гру
* `Year` --- рік релізу
* `Genre` --- жанр
* `Publisher` --- видавець
* `NA_Sales` --- продажі в Північній Америці, у млн.
* `EU_Sales` --- продажі в Європі, у млн.
* `JP_Sales` --- продажі в Японії, у млн.
* `Other_Sales` --- продажі в решті світу, у млн.
* `Global_Sales` --- продажі по всьому світу, у млн.