---
title: Лабораторна робота №1
subtitle: Прикладний статистичний аналіз
subject: Регресійний аналіз
lang: ua
---

::: {.callout-note}
Це орієнтовний план роботи. Ви можете аргументовано відхилитись від нього.
:::

# Завдання

1. Завантажте дані, перевірте правильність, наявність пропущених значень, типи даних.
2. За необхідності, створіть нові змінні.
3. Проведіть кореляційний аналіз. Визначте залежну та незалежні змінні. Побудуйте візуалізації.
4. Перевірте виконання припущень регресійного аналізу.
5. Побудуйте модель з одним предиктором. Оцініть ефективність моделі.
6. Проведіть аналіз залишків.
7. Проведіть інтерпретацію параметрів моделі. Побудуйте довірчі інтервали для параметрів моделі. Перевірте гіпотези про значущість параметрів.
8. Зробіть висновки.

::: {.callout-important}
- **Захист** робіт **обов'язковий**.
- **Дедлайн** здачі робіт: **06.02.2024**
:::

::: {.callout-tip}
- Звіт бажано оформити з використанням [Quarto](https://quarto.org/). Підтримує R, Python. Можна використовувати Jupyter Notebook. Мої відео-інструкції:
    + на прикладі VS Code: [https://www.youtube.com/watch?v=pe4At0eaC4Q](https://www.youtube.com/watch?v=pe4At0eaC4Q)
    + на прикладі RStudio: [https://www.youtube.com/watch?v=Vdw3WQ4iE0o](https://www.youtube.com/watch?v=Vdw3WQ4iE0o)
- Дані обираєте самостійно. Бажано взяти актуальні і під Ваш курсовий проєкт. Деякі датасети можна знайти в мене: [aranaur.rbind.io](https://aranaur.rbind.io/datasets)
:::
