---
title: Лабораторна робота №3
subtitle: Прикладний статистичний аналіз
subject: Бутстрап
lang: ua
---

# Опис експерименту
Перед вами таблиця, з результатами експерименту. Ви проводили тестування нового дизайну сайту. Вам потрібно оцінити, чи є статистично значимі відмінності між контрольною та тестовою групами.

```{python}
#| label: bootstrap-data
#| echo: false

import pandas as pd

pd.read_csv('data/bootstrap.csv', sep=';', index_col=0)
```

**Опис змінних:**

- `value` - значення метрики
- `experimentVariant` - Варіант тесту (`Control` - контроль, `Treatment` - тест)

## Завдання

1. Порівняйте результат між тестом і контролем за двома кейсами:
    + Застосуйте *бутстрап (за середнім)* і *U-критерій Манна-Уітні* , а потім порівняйте *p-value*
    + Застосуйте *бутстрап (за медіаною)* і *U-критерій Манна-Уітні*, а потім порівняйте *p-value*.
  
2. Створіть відповідні візуалізації, напишіть висновки, які можна зробити на основі аналізу застосованих критеріїв

::: {.callout-important}
- **Дедлайн** здачі роботи: **13.02.2024**
:::

::: {.callout-tip}
- Звіт бажано оформити з використанням [Quarto](https://quarto.org/). Підтримує R, Python. Можна використовувати Jupyter Notebook. Мої відео-інструкції:
    + на прикладі VS Code: [https://www.youtube.com/watch?v=pe4At0eaC4Q](https://www.youtube.com/watch?v=pe4At0eaC4Q)
    + на прикладі RStudio: [https://www.youtube.com/watch?v=Vdw3WQ4iE0o](https://www.youtube.com/watch?v=Vdw3WQ4iE0o)
:::
