---
title: Лабораторна робота №4
subtitle: Прикладний статистичний аналіз
subject: A/A тестування
lang: ua
---

## Опис завдання
[А/А-тестування мобільного застосунку](data/aa.csv). 

Необхідно порахувати результати A/A-тесту, перевіряючи метрику якості FPR (будемо перевіряти на конверсії в покупку). Відомо, що спліт-система зламана. 

Потрібно перевірити твердження про поломку і знайти її причини, якщо спліт-система дійсно зламана.

```{python}
#| label: data
#| echo: false

import pandas as pd

pd.read_csv('data/aa.csv', sep=';', index_col=0)
```

## Опис колонок
* `uid` - ідентифікатор користувача
* `experimentVariant` - варіант експерименту
* `version` - версія додатка
* `purchase` - факт покупки

## Завдання

1. Запустіть A/A-тест.
2. Порахуйте FPR на рівні $\alpha$ = 0.05 (ставте підвибірки без повернення обсягом 1000). Ви побачите, що $FPR > \alpha$! Нам потрібно навпаки - щоб було менше.
3. Знайдіть причини поломки спліт-системи, орієнтуючись на результати експерименту (підказка: знайдіть аномалію у версії додатка).
4. Напишіть висновки, які можна зробити на основі аналізу результатів A/A-тесту.

::: {.callout-note collapse="true"}
## Підказка: як знайти причини поломки?

Вам доступна версія мобільного застосунку (МЗ) кожного користувача. Цю корисну інформацію можна використати для дослідження проблеми:

* Порахуйте конверсію (коефіцієнт покупок), групуючи за варіантом і версією МЗ. Можливо вже стане зрозуміло де саме причини поломки
* Порахуйте `pvalue` для кожної версії МЗ
* Знайдіть версії, де `pvalue` < 0.05
* Виключіть версію з `pvalue` < 0.05 з основного датафрейма
* Повторно запустіть розрахунок FPR через A/A. Тепер $FPR < \alpha$
* Ви знайшли поломку
:::

::: {.callout-important}
- **Дедлайн** здачі роботи: **15.02.2024**
:::

::: {.callout-tip}
- Звіт бажано оформити з використанням [Quarto](https://quarto.org/). Підтримує R, Python. Можна використовувати Jupyter Notebook. Мої відео-інструкції:
    + на прикладі VS Code: [https://www.youtube.com/watch?v=pe4At0eaC4Q](https://www.youtube.com/watch?v=pe4At0eaC4Q)
    + на прикладі RStudio: [https://www.youtube.com/watch?v=Vdw3WQ4iE0o](https://www.youtube.com/watch?v=Vdw3WQ4iE0o)
:::
