---
title: "GCP: Python та BigQuery"
subtitle: "Хмарні технології обробки даних"
author: "Ігор Мірошниченко"
institute: КНУ імені Тараса Шевченка | ФІТ
# date: today
# date-format: iso
from: markdown+emoji
title-slide-attributes:
  data-background-iframe: .01_files/libs/colored-particles/index.html
#   data-background-color: "#eef3f8"
lang: ua
footer: 🔗 <a href="https://aranaur.rbind.io/lectures/cloud_data_processing/">Матеріали курсу</a>
format: 
  html:
    toc: true
    code-line-numbers: false
    highlight-style: github
    pdf-separate-fragments: true
    # fig-height: 7.5
    fig-width: 15
    fig-align: center
    fig-format: svg
    theme: [default, custom.scss]
jupyter: python3
execute: 
  warning: false
  echo: true
---

```{python}
#| label: setup
#| include: false
#| eval: false

# Import libraries
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm, uniform, t

from IPython.display import Markdown
from tabulate import tabulate

# Set seaborn default style
sns.set_style('whitegrid')
sns.set_palette('colorblind')

# Define colors
red_pink   = "#e64173"
turquoise  = "#20B2AA"
orange     = "#FFA500"
red        = "#fb6107"
blue       = "#181485"
navy       = "#150E37FF"
green      = "#8bb174"
yellow     = "#D8BD44"
# grey_light = "grey70"
# grey_mid   = "grey50"
# grey_dark  = "grey20"
purple     = "#6A5ACD"
slate      = "#314f4f"
```

## Вимоги

1. Активувати BigQuery API в консолі GCP
2. Встановити бібліотеку `google-cloud-bigquery`:

```bash
pip install --upgrade google-cloud-bigquery
pip install google-cloud-bigquery-datatransfer
pip install db-dtypes
```

3. Створити сервісний ключ для доступу до BigQuery API (Role: Basic, Roles: Owner) та завантажити його на локальний комп'ютер.

## Початок роботи з API

```{python}
#| label: bigquery-setup

import os
from google.cloud import bigquery, bigquery_datatransfer
import google.auth
import time
import pandas as pd
import datetime
import json

# Завантаження сервісного ключа
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "./data/fit-cloud-course-key.json"
```

### Створення клієнта

```{python}
#| label: client

client = bigquery.Client('fit-cloud-course')
```

### Запити до BigQuery

```{python}
#| label: query

sql_query = """
SELECT station_id, name, dockcount
FROM `bigquery-public-data.san_francisco.bikeshare_stations`
LIMIT 5
"""
```

### Виконання запиту

```{python}
#| label: execute

query_job = client.query(sql_query)

print(query_job)
```

### Результати запиту

```{python}
#| label: results-1

for row in query_job:
    print(row)
```

```{python}
#| label: results-2

for row in query_job:
    print(row[0], row[1], row[2], sep=" | ")
```

```{python}
#| label: results-3

for row in query_job:
    print(row.station_id, row.name, row.dockcount, sep=" | ")
```

## Завантаження даних в BigQuery

### JSON

За необхідності, переведемо дані у плоский формат:

```{python}
#| label: flatten
#| eval: false

json_data = json.load(open('./data/orders.json'))
data_file_path = './data/orders_upload.json'

with open(data_file_path, 'w') as f:
    f.write('\n'.join(json.dumps(record) for record in json_data))
```

```{python}
#| label: upload-setup

dataset_id = 'dsongcp'
table_id = 'orders'
data_file_path = './data/orders.json'
```

```{python}
#| label: upload-config

job_config = bigquery.LoadJobConfig(
    schema=[
        bigquery.SchemaField("order_id", "INT64"),
        bigquery.SchemaField("creation_time", "DATETIME"),
        bigquery.SchemaField("product_ids", "INT64", mode="REPEATED"),
        ],
    source_format=bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
    autodetect=False,    
    write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE
)
```

```{python}
#| label: upload-execute

table_ref = client.dataset(dataset_id).table(table_id)
with open(data_file_path, "rb") as source_file:
    job = client.load_table_from_file(source_file, table_ref, job_config=job_config)

while job.running():
    print('Завантаження даних...')
    time.sleep(3)
print(job.result())
```

### GC Storage

```{python}
#| label: storage-upload

bucket_name = 'fit-cloud-course-dsongcp'
source_uri = f"gs://{bucket_name}/flights/raw/*.csv"
table_id = 'flights_py'
```

```{python}
#| label: storage-config-2

job_config = bigquery.LoadJobConfig(
    autodetect=True,
    source_format=bigquery.SourceFormat.CSV,
    skip_leading_rows=1,
    write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE
)
```

```{python}
#| label: storage-execute-2

table_ref = client.dataset(dataset_id).table(table_id)
job = client.load_table_from_uri(
    source_uri,
    table_ref,
    job_config=job_config
)

while job.running():
    print('Завантаження даних...')
    time.sleep(3)
print(job.result())
```

### CSV

```{python}
#| label: csv-upload

dataset_id = 'dsongcp'
table_id = 'users'
data_file_path = './data/users.csv'

job_config = bigquery.LoadJobConfig(
    source_format=bigquery.SourceFormat.CSV,
    skip_leading_rows=1,
    autodetect=True,
    write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE
)

table_ref = client.dataset(dataset_id).table(table_id)
with open(data_file_path, "rb") as source_file:
    job = client.load_table_from_file(source_file, table_ref, job_config=job_config)

while job.running():
    print('Завантаження даних...')
    time.sleep(3)
print(job.result())
```

```{python}
#| label: csv-rows-cols

table = client.get_table(table_ref)
print(f"Таблиця: {table}\nСпостережень: {table.num_rows}\nЗмінних: {len(table.schema)}")
```

### Google Sheets

Підключаємо Google Drive API.
Копіюємо email-адресу сервісного акаунта.

```{python}
#| label: sheets-setup

credentials, project = google.auth.default(
    scopes=[
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/bigquery"
    ]
)
```

```{python}
#| label: sheets-config

client = bigquery.Client(credentials=credentials, project=project)

dataset_id = 'dsongcp'
table_id = 'air_traffic'
table_ref = client.dataset(dataset_id).table(table_id)
```

```{python}
#| label: sheets-execute

table = bigquery.Table(table_ref, schema = [
    bigquery.SchemaField("Activity_Period", "INT64"),
    bigquery.SchemaField("Activity_Period_Start_Date", "DATE"),
    bigquery.SchemaField("Operating_Airline", "STRING"),
    bigquery.SchemaField("Operating_Airline_IATA_Code", "STRING"),
    bigquery.SchemaField("Published_Airline", "STRING"),
    bigquery.SchemaField("Published_Airline_IATA_Code", "STRING"),
    bigquery.SchemaField("GEO_Summary", "STRING"),
    bigquery.SchemaField("GEO_Region", "STRING"),
    bigquery.SchemaField("Activity_Type_Code", "STRING"),
    bigquery.SchemaField("Price_Category_Code", "STRING"),
    bigquery.SchemaField("Terminal", "STRING"),
    bigquery.SchemaField("Boarding_Area", "STRING"),
    bigquery.SchemaField("Passenger_Count", "INT64"),
    bigquery.SchemaField("data_as_of", "STRING"),
    bigquery.SchemaField("data_loaded_at", "STRING")
])

external_config = bigquery.ExternalConfig("GOOGLE_SHEETS")
sheet_url = "https://docs.google.com/spreadsheets/d/1vp7bCvxd3R2zciqxc8A4Qoq5DAvqhzfXJnljmG5OOw0/edit?usp=sharing"
external_config.source_uris = [sheet_url]

options = external_config.google_sheets_options
options.skip_leading_rows = 1
options.range = "air_traffic!A:O"

table.external_data_configuration = external_config
client.create_table(table)
```

## Мітки даних у BigQuery

Мітка – це пара ключ-значення, яку можна призначити ресурсам Google Cloud BigQuery. Ви можете прикріпити мітку до кожного ресурсу, а потім відфільтрувати ресурси на основі їхніх міток.

Ось кілька типових випадків використання міток:

- **Мітки команди:** `team:research` або `team:analytics`.
- **Мітки компонентів:** наприклад, `component:redis`, `component:frontend`, `component:ingestта`, `component:dashboard` тощо.
- **Мітки середовища:** `environment:production` і `environment:test`.
- **Мітки стану:** `state:active`, `state:readytodelete` і `state:archive`.
- **Мітки власності:** використовуються для ідентифікації команд, які відповідають за операції, наприклад `team:shopping-cart`.

### Створення таблиці

```{python}
#| label: create-table-1

# Створення посилання на таблицю
dataset_ref = bigquery.DatasetReference(client.project, 'dsongcp')

# Створення таблиці
table_ref = bigquery.TableReference(dataset_ref, 'flights_auto')
```

### Створення міток

```{python}
#| label: labels

# Створення міток
labels = {
    'type': 'auto',
    'category': 'transport'
}

# Створення таблиці з мітками
flights_auto_table = client.get_table(table_ref)
# Додавання міток
flights_auto_table.labels = labels
# Оновлення таблиці
client.update_table(flights_auto_table, ['labels'])
```

### Оновлення міток

```{python}
#| label: update-labels

# Оновлення міток
new_labels = {
    'type': 'auto',
    'category': 'transport',
    'year': '2015'
}

flights_auto_table = client.get_table(table_ref)
flights_auto_table.labels = new_labels
client.update_table(flights_auto_table, ['labels'])
```

### Видалення міток

```{python}
#| label: delete-labels

table = client.get_table(table_ref)
labels = table.labels
labels = {k: None for k, v in labels.items()}
table.labels = labels
client.update_table(table, ['labels'])
```

## Додавання/видалення змінних

```{python}
#| label: columns

# Створення таблиці
dataset_ref = bigquery.DatasetReference(client.project, 'dsongcp')
table_ref = bigquery.TableReference(dataset_ref, 'flights_auto')
bigquery_table = client.get_table(table_ref)
```

Отримання схеми таблиці:

```{python}
#| label: schema

schema = bigquery_table.schema
schema[:5]
```

Створимо копію схеми:

```{python}
#| label: copy-schema

new_schema = schema.copy()
```

Додамо нову змінну у схему:

```{python}
#| label: add-column

new_schema.append(bigquery.SchemaField('Distance_km', 'FLOAT64', mode='NULLABLE'))
# Передамо оновлену схему таблиці bigquery_table
bigquery_table.schema = new_schema
```

::: callout-note
Типи даних в BigQuery: <https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types>.
:::

Тепер зробимо запит на оновлення таблиці:

```{python}
#| label: update-schema

client.update_table(bigquery_table, ['schema'])
```

Переглянемо оновлену схему:

```{python}
#| label: updated-schema

bigquery_table = client.get_table(table_ref)
schema = bigquery_table.schema
schema[-5:]
```

Видалення змінної з схеми:

```{python}
#| label: delete-column

query_job = client.query("""
    ALTER TABLE dsongcp.flights_auto
    DROP COLUMN IF EXISTS Distance_km;
""")
```

Іноді запит може займати деякий час на виконання. Щоб перевірити статус запиту, використовуйте метод `query_job.state`:

```{python}
#| label: query-status

while query_job.state != 'DONE': 
    print('Запит виконується...')
    time.sleep(3)
    query_job.reload()
print(query_job.result())
```

## Збереження результатів запиту в таблицю

Напишемо запит, який вибере середню затримку вильоту та прибуття для кожного аеропорту відправлення:

```{python}
#| label: base-query

sql_query = """
SELECT
  ORIGIN,
  AVG(DepDelay) AS dep_delay,
  AVG(ArrDelay) AS arr_delay,
  COUNT(ArrDelay) AS num_flights
FROM
  `dsongcp.flights_auto`
GROUP BY
  ORIGIN
ORDER BY num_flights DESC
LIMIT 10
"""
```

Створимо окремий датасет, куди ми збережемо результати запиту:

```{python}
#| label: create-dataset

dataset_id = client.project + '.dsongcp_results'
dataset = bigquery.Dataset(dataset_id)
dataset.location = "US"
dataset = client.create_dataset(dataset, exists_ok=True)
print(f"Створено датасет {client.project}.{dataset.dataset_id}")
```

Визначимо таблицю, в яку ми збережемо результати запиту:

```{python}
#| label: table-info

project_id = client.project
dataset_id = 'dsongcp_results'
table_id = 'flights_delay'
```

Використаємо метод `from_string()` для створення посилання на таблицю:

```{python}
#| label: create-table-2

table_ref = bigquery.TableReference.from_string(f"{project_id}.{dataset_id}.{table_id}")
table_ref
```

Виконаємо запит та збережемо результати в таблицю:

```{python}
#| label: save-results

job_config = bigquery.QueryJobConfig(destination=table_ref, write_disposition="WRITE_TRUNCATE")
query_job = client.query(sql_query, job_config=job_config)
while query_job.state != 'DONE': 
    print('Запит виконується...')
    time.sleep(3)
    query_job.reload()
print(query_job.result())
```

::: callout-note
Більше про `QueryJobConfig` за посиланням <https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.job.QueryJobConfig>
:::

## Запит у DataFrame

Для зручності роботи з даними можна використовувати бібліотеку `pandas`. Для цього використаємо метод `to_dataframe()`:

```{python}
#| label: to-dataframe

query_job = client.query(sql_query)
df = query_job.to_dataframe()
df
```

## Параметризовані запити

Параметризовані запити дозволяють використовувати змінні в запитах. Це дозволяє виконувати один і той же запит з різними значеннями змінних.

Для цього використовується символ `@` перед змінною в запиті. Визначимо параметр `month` та виконаємо запит:

```{python}
#| label: query-params

query_params = [
    bigquery.ScalarQueryParameter("month", "INT64", 1)
]
```

```{python}
#| label: param-query

sql_query = """
SELECT
  ORIGIN,
  AVG(DepDelay) AS dep_delay,
  AVG(ArrDelay) AS arr_delay,
  COUNT(ArrDelay) AS num_flights
FROM
  `dsongcp.flights_auto`
WHERE
  Month = @month
GROUP BY
  ORIGIN
ORDER BY num_flights DESC
LIMIT 10
"""
```

```{python}
#| label: execute-params

job_config = bigquery.QueryJobConfig(query_parameters=query_params)
query_job = client.query(sql_query, job_config=job_config)
df = query_job.to_dataframe()
df
```

У випадку коли потрібно використати зріз по даті:

```{python}
#| label: date-params

query_params = [
    bigquery.ScalarQueryParameter("start_date", "DATE", datetime.date(2015, 1, 1)),
    bigquery.ScalarQueryParameter("end_date", "DATE", datetime.date(2015, 1, 7))
]
```

Тоді запит буде виглядати наступним чином:

```{python}
#| label: date-query

sql_query = """
SELECT
  ORIGIN,
  AVG(DepDelay) AS dep_delay,
  AVG(ArrDelay) AS arr_delay,
  COUNT(ArrDelay) AS num_flights
FROM
  `dsongcp.flights_auto`
WHERE
  FlightDate BETWEEN @start_date AND @end_date
GROUP BY
  ORIGIN
ORDER BY num_flights DESC
LIMIT 10
"""
```

```{python}
#| label: execute-date

job_config = bigquery.QueryJobConfig(query_parameters=query_params)
query_job = client.query(sql_query, job_config=job_config)
df = query_job.to_dataframe()
df
```

І третій варіант - позиційні параметри:

```{python}
#| label: positional-params

query_params = [
    bigquery.ScalarQueryParameter(None, "FLOAT64", 0),
    bigquery.ScalarQueryParameter(None, "FLOAT64", 0)

]
```

```{python}
#| label: positional-query

sql_query = """
SELECT
  ORIGIN,
  AVG(DepDelay) AS dep_delay,
  AVG(ArrDelay) AS arr_delay,
  COUNT(ArrDelay) AS num_flights
FROM
  `dsongcp.flights_auto`
WHERE
  DepDelay < ? AND ArrDelay < ?
GROUP BY
  ORIGIN
ORDER BY num_flights DESC
LIMIT 10
"""
```

```{python}
#| label: execute-positional

job_config = bigquery.QueryJobConfig(query_parameters=query_params)
query_job = client.query(sql_query, job_config=job_config)
df = query_job.to_dataframe()
df
```

Ще один варіант - використанням масивів:

```{python}
#| label: array-params

query_params = [
    bigquery.ArrayQueryParameter("ORIGIN", "STRING", ["PHX", "ATL", "LAS"]),
    bigquery.ScalarQueryParameter("DepDelay", "FLOAT64", 10),
]
```

```{python}
#| label: array-query

sql_query = """
SELECT
  ORIGIN,
  AVG(DepDelay) AS dep_delay,
  AVG(ArrDelay) AS arr_delay,
  COUNT(ArrDelay) AS num_flights
FROM
  `dsongcp.flights_auto`
WHERE
  ORIGIN IN UNNEST(@ORIGIN)
  AND DepDelay > @DepDelay
GROUP BY
  ORIGIN
ORDER BY num_flights DESC
"""
```

```{python}
#| label: execute-array

job_config = bigquery.QueryJobConfig(query_parameters=query_params)
query_job = client.query(sql_query, job_config=job_config)
df = query_job.to_dataframe()
df
```

## Таблиця BG -> GC Storage

```{python}
#| label: storage-setup

client = bigquery.Client('fit-cloud-course')
dataset_id = 'dsongcp'
bucket_name = 'fit-cloud-course-dsongcp'
```

```{python}
#| label: storage-results

table_ref = bigquery.TableReference.from_string(f"{client.project}.{dataset_id}.flights_auto")
```

```{python}
#| label: storage-config

job_config = bigquery.job.ExtractJobConfig()
# job_config.destination_format = bigquery.DestinationFormat.CSV
job_config.destination_format = bigquery.DestinationFormat.NEWLINE_DELIMITED_JSON
```

```{python}
#| label: storage-execute

destination_uri = f"gs://{bucket_name}/results/flights_delay.json"

extract_job = client.extract_table(
    table_ref,
    destination_uri,
    job_config=job_config,
    location="US"
)
extract_job.result()
```

## Робота з датасетами

Підключіть **BigQuery Data Transfer API**.

Створимо клас `DatasetManager` для роботи з датасетами:

```{python}
#| label: dataset-manager

class DatasetManager:
    def __init__(self, client):
        self.client = client

    def delete_dataset(self, dataset_id):
        self.client.delete_dataset(dataset_id, not_found_ok=True, delete_contents=True)

    def create_dataset(self, dataset_id, location='US'):
        dataset = bigquery.Dataset(dataset_id)
        dataset.location = location
        dataset_ = self.client.create_dataset(dataset, timeout=30)
        print(f"Датасет {self.client.project}.{dataset.dataset_id} створено")
        return dataset_

    def list_dataset(self):
        datasets = self.client.list_datasets()
        return [dataset.dataset_id for dataset in datasets]

    def copy_dataset(self, source_project_id, source_dataset_id, destination_project_id, destination_dataset_id, display_name):
        """
        Посилання:
        https://cloud.google.com/bigquery-transfer/docs/reference/datatransfer/rest/v1/projects.transferConfigs

        Надати доступ до IAM:
        https://cloud.google.com/bigquery/docs/enable-transfer-service#grant_bigqueryadmin_access

        Зауважте:
        - це також призведе до переміщення таблиць.
        - підключіть BigQuery Data Transfer API.
        """
        transfer_client = bigquery_datatransfer.DataTransferServiceClient()
        transfer_config = bigquery_datatransfer.TransferConfig(
            destination_dataset_id=destination_dataset_id,
            display_name=display_name,
            data_source_id="cross_region_copy", # 
            params={
                "source_project_id": source_project_id,
                "source_dataset_id": source_dataset_id,
            },
        )
        transfer_config = transfer_client.create_transfer_config(
            parent=transfer_client.common_project_path(destination_project_id),
            transfer_config=transfer_config,
        )
        print(f"Створено конфігурацію передачі: {transfer_config.name}")
```

Ініціалізуємо клієнт та клас:

```{python}
#| label: dataset-init

client = bigquery.Client('fit-cloud-course')
dataset_manager = DatasetManager(client)
```

Виведемо список датасетів:

```{python}
#| label: list-datasets

dataset_manager.list_dataset()
```

Створимо новий датасет:

```{python}
#| label: create-dataset-2

dataset_name = f'{client.project}.ny_taxi_trips'
dataset = dataset_manager.create_dataset(dataset_name)
```

Скопіюємо датасет:

```{python}
#| label: copy-dataset

source_project_id = 'bigquery-public-data'
source_dataset_id = 'new_york_taxi_trips'
destination_project_id = client.project
destination_dataset_id = 'ny_taxi_trips'
display_name = 'NY Taxi Trips'

dataset_manager.copy_dataset(source_project_id, source_dataset_id, destination_project_id, destination_dataset_id, display_name)
```

Видалимо датасет:

```{python}
#| label: delete-dataset

dataset_manager.delete_dataset(dataset_name)
```
