---
title: "Вступ до PySpark"
subtitle: "Моделі та методи обробки великих даних"
author: "Ігор Мірошниченко"
institute: КНУ імені Тараса Шевченка, ФІТ
from: markdown+emoji
title-slide-attributes:
    data-background-iframe: .01_files/libs/colored-particles/index.html
language: _language-ua.yml
footer: <a href="https://aranaur.rbind.io/lectures/mm_big_data/">🔗Моделі та методи обробки великих даних</a>
format:
  revealjs: 
    code-line-numbers: false
    # center: true
    navigation-mode: vertical
    transition: fade
    background-transition: fade
    # controls-layout: bottom-right
    chalkboard: true
    logo: fit.png
    slide-number: true
    toc: true
    toc-depth: 1
    mouse-wheel: true
    width: 1350  
    height: 759.375
    highlight-style: github
    # fig-width: 9
    # fig-height: 5
    fig-format: svg
    theme: [default, custom.scss]
    mermaid:
      theme: forest
  # gfm:
  #   mermaid-format: png
preload-iframes: true
jupyter: python3
execute: 
  echo: true
  warning: false
editor_options: 
  chunk_output_type: console

revealjs-plugins:
  - verticator
---

```{python}
#| label: setup
#| include: false

# Import libraries
from scipy.stats import (
    binom
)
import numpy as numpy
from seaborn import distplot
from matplotlib import pyplot
import seaborn
import random

import sys

# Import libraries
# import numpy as numpy
import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns

from IPython.display import Markdown
from tabulate import tabulate

# Define colors
red_pink   = "#e64173"
turquoise  = "#20B2AA"
orange     = "#FFA500"
red        = "#fb6107"
blue       = "#181485"
navy       = "#150E37FF"
green      = "#8bb174"
yellow     = "#D8BD44"
purple     = "#6A5ACD"
slate      = "#314f4f"
```

# Apache Spark та PySpark

##  Що таке PySpark?

- Apache Spark --- це розподілена обчислювальна система з відкритим вихідним кодом, призначена для швидкої обробки великих обсягів даних. 

- PySpark --- це інтерфейс Python для Apache Spark. Він ефективно обробляє великі набори даних за допомогою паралельних обчислень у робочих процесах Python, ідеально підходить для пакетної обробки, потокового передавання в реальному часі, машинного навчання, аналізу даних та SQL-запитів. 

- PySpark підтримує такі галузі, як фінанси, охорона здоров'я та електронна комерція, завдяки швидкості та масштабованості.

## Коли використовувати PySpark? {.smaller}

- Аналітика великих даних
- Розподілена обробка даних
- Потокові дані в реальному часі
- Машинне навчання на великих масивах даних
- ETL та ELT конвеєри
- Робота з різноманітними джерелами даних:
    1. CSV
    2. JSON
    3. Parquet
    4. ...

## Кластер Spark

Кластер Spark --- це група комп'ютерів (вузлів, nodes), які спільно обробляють великі набори даних за допомогою Apache Spark, з головним вузлом (master node), який координує роботу декількох робочих вузлів (worker nodes).

Головний вузол: Керує кластером, координує завдання, та планує завдання

Робочі вузли: виконують задачі, відповідають за обробку даних, зберігають дані

## SparkSession

SparkSession --- це точка входу в PySpark, що дозволяє взаємодіяти з основними можливостями Apache Spark. Він дозволяє нам виконувати запити, обробляти дані та керувати ресурсами в кластері Spark.

```{python}
#| label: spark-session

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("MySparkApp") \
    .getOrCreate()
```

- `.builder` --- створює новий об'єкт SparkSession
- `.appName("MySparkApp")` --- задає ім'я програми
- `.getOrCreate()` --- отримує існуючий SparkSession або створює новий, якщо його ще немає

## PySpark DataFrames

- DataFrames: Табличний формат (рядки/стовпці)
- Підтримує SQL-подібні операції
- Можна порівняти з Pandas Dataframe або SQL TABLE
- Структуровані дані

## PySpark DataFrames {.tiny}

```{python}
#| label: spark-dataframe

salaries = spark.read.csv("data/salaries.csv", header=True, inferSchema=True)

Markdown(tabulate(
  salaries.limit(5).collect(),
  headers=salaries.columns,
))
```

- `json()`
- `parquet()`
- `orc()`
- `jdbc()`

## Схема DataFrame

```{python}
#| label: spark-dataframe-schema

salaries.printSchema()
```

## Базові операції з DataFrame {.smaller}

```{python}
#| label: spark-dataframe-operations

row_count = salaries.count()
print(f"Кількість рядків: {row_count}")
```

```{python}
#| label: spark-dataframe-agg

Markdown(tabulate(
  salaries.groupBy("experience_level").agg({"salary_in_usd": "avg"}).collect(),
  headers=["Рівень досвіду", "Середня зарплата"],
))
```

- `sum`
- `min`
- `max`

## Ключові функції

- `select()`: вибір стовпців
- `filter()` або `where()`: фільтрація рядків
- `groupBy()`: групування даних
- `agg()`: агрегація даних
- `sort()` або `orderBy()`: сортування даних
- `limit()`: обмеження кількості рядків

## Приклад: Фільтрація та агрегація {.smaller}

```{python}
#| label: spark-dataframe-filter-agg

# arrange

Markdown(tabulate(
  salaries.filter(salaries["experience_level"] == "SE").groupBy("job_title") \
        .agg({"salary_in_usd": "avg"}) \
        .orderBy("avg(salary_in_usd)", ascending=False).limit(5) \
        .collect(),
  headers=["Посада", "Середня зарплата"],
))
```

## Виведення схеми та ручне визначення схеми

- `inferSchema`: автоматичне визначення схеми
- `schema`: ручне визначення схеми
- `printSchema()`: виведення схеми DataFrame

## Типи даних

- `StringType`: рядок
- `IntegerType`: ціле число
- `FloatType`: число з плаваючою комою
- `LongType`: довге ціле число
- `ArrayType`: масив

## Синтаксис типів даних

```{python}
#| label: spark-dataframe-types
#| eval: false

from pyspark.sql.types import (StructType, # <1>
                              StructField, IntegerType, # <1>
                              StringType, ArrayType)  # <1>

schema = StructType([ # <2>
  StructField("id", IntegerType(), True), # <2>
  StructField("name", StringType(), True), # <2>
  StructField("scores", ArrayType(IntegerType()), True) # <2>
]) # <2>

df = spark.createDataFrame(data, schema=schema) # <3>
```
1. Імпорт типів даних
2. Визначення схеми: `StructType` та `StructField` для опису структури даних
3. Створення DataFrame з даними та схемою

# Маніпуляція даними

## Пропущені значення

- `dropna()` або `na.drop()`: видалення рядків з пропущеними значеннями
- `fillna()` або `na.fill()`: заповнення пропущених значень

```{python}
#| label: spark-dataframe-missing
#| eval: false

df_cleaned = df.dropna() # <1>

df_cleaned = df.where(col("column_name").isNotNull()) # <2>

df_filled = df.na.fill({"column_name": "default_value"}) # <3>
df_filled = df.fillna(0) # <4>
```
1. Видалення рядків з пропущеними значеннями
2. Фільтрація рядків з ненульовими значеннями
3. Заповнення пропущених значень за допомогою словника
4. Заповнення пропущених значень за допомогою значення

## Стовпці

- `withColumn()`: додавання або зміна стовпця
- `withColumnRenamed()`: перейменування стовпця
- `drop()`: видалення стовпця
- `select()`: вибір стовпців
- `distinct()`: видалення дублікатів

```{python}
#| label: spark-dataframe-columns
#| eval: false

df = df.withColumn("new_column", col("existing_column") * 2)
df = df.withColumnRenamed("old_name", "new_name")
df = df.drop("column_name")
df = df.select("column1", "column2")
```

## Рядки

- `filter()`: фільтрація рядків
- `groupBy()`: групування рядків

```{python}
#| label: spark-dataframe-rows
#| eval: false

filtered_df = df.filter(df["column_name"] > 10)
grouped_df = df.groupBy("column_name").avg("other_column")
```

## Просунуті функції

- `join()`
- `union()`
- `intersect()`
- `except()`
- `sample()`
- `distinct()`

## Join

Типи об'єднань: `inner`, `cross`, `outer`, `full`, `fullouter`, `full_outer`, `left`, `leftouter`, `left_outer`, `right`, `rightouter`, `right_outer`, `semi`, `leftsemi`, `left_semi`, `anti`, `leftanti` та `left_anti`.

```{python}
#| label: spark-dataframe-join
#| eval: false

df_joined = df1.join(df2, on="key", how="inner")
df_joined = df1.join(df2, on=["key1", "key2"], how="inner")

df_joined = df1.join(df2, df1.key == df2.key, "inner")
```

## Union

Об'єднує рядки з двох фреймів даних з однаковою схемою

```{python}
#| label: spark-dataframe-union
#| eval: false

df_union = df1.union(df2)
```

## Arrays та Maps

- `array()`: створення масиву
- `map()`: створення словника

```{python}
#| label: spark-dataframe-arrays
#| eval: false

from pyspark.sql.functions import array, struct, lit

df = df.withColumn("scores", array(lit(85), lit(90), lit(78)))
```

```{python}
#| label: spark-dataframe-maps
#| eval: false

from pyspark.sql.types import StructField, StructType, StringType, MapType

schema = StructType([
    StructField("id", IntegerType(), True),
    StructField("name", StringType(), True),
    StructField("scores", MapType(StringType(), IntegerType()), True)
])
```

## Робота зі Structs

- Structs: Створення вкладених структур у рядках

```{python}
#| label: spark-dataframe-structs
#| eval: false

df = df.withColumn("address", struct(col("city"), col("state")))
```

# Власні функції

## UDF (User Defined Functions)

- UDF --- це функції, які ви визначаєте самостійно для виконання специфічних обчислень на даних у DataFrame.

Переваги UDF:

- Повторне використання та повторення спільних завдань
- Реєструються безпосередньо у Spark і можуть бути доступними для спільного використання
- PySpark DataFrames (для менших наборів даних)
- Pandas UDF (для більших наборів даних)

## UDF

Всі PySpark UDF мають бути зареєстровані за допомогою функції `udf()`.

```{python}
#| label: spark-dataframe-udf
#| eval: false

def to_uppercase(s): # <1>
    return s.upper() if s else None # <1>

to_uppercase_udf = udf(to_uppercase, StringType()) # <2>

df = df.withColumn("upper_name", to_uppercase_udf(df["name"])) # <2>
```

::: {.callout-note appearance="simple"}
UDF дозволяють застосовувати кастомну логіку Python до фреймів даних PySpark
:::

## pandas UDF

- Усуває "важкі" перетворення коду та даних
- Не потребує реєстрації в SparkSession
- Використовує можливості Pandas на дуже великих наборах даних

```{python}
#| label: spark-dataframe-pandas-udf
#| eval: false

from pyspark.sql.functions import pandas_udf

@pandas_udf("float")
def fahrenheit_to_celsius_pandas(temp_f):
  return (temp_f - 32) * 5.0/9.0
```

## PySpark UDFs vs. Pandas UDFs

::: {.columns}
::: {.column}
**PySpark UDF**

- Найкраще підходить для відносно невеликих наборів даних
- Просте обчислення
- Паралельні обчислення на рівні стовпців
- Потребує реєстрації в SparkSession
:::
::: {.column}
**Pandas UDF**

- Відносно великі набори даних
- Складні обчислення, такі як машинне навчання
- Паралельні обчислення на рівні рядків
- Не потребує реєстрації в SparkSession
:::
:::

# RDD (Resilient Distributed Dataset)

## PySpark паралелізація

- Автоматичне розпаралелювання даних і обчислень на декількох вузлах кластера
- Розподілена обробка великих наборів даних на декількох вузлах
- Робочі вузли обробляють дані паралельно, об'єднуючись в кінці виконання завдання
- Масштабована швидша обробка (гігабайти або навіть терабайти)

## RDD (Resilient Distributed Dataset)

RDD (стійкі розподілені набори даних) --- це основна структура даних у Spark, що представляє собою розподілений набір даних, який може бути оброблений паралельно на декількох вузлах кластера.

- Розподілена колекція даних по всьому кластеру з автоматичним відновленням після збоїв вузлів
- Добре підходить для великих обсягів даних
- Незмінні і можуть бути перетворені за допомогою таких операцій, як `map()` або `filter()`, з діями на кшталт `collect()` або `parallel()` для отримання результатів і створення RDD

## Створення RDD

```{python}
#| label: spark-rdd

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("RDDExample").getOrCreate()

census_df = spark.read.csv("data/salaries.csv", header=True, inferSchema=True)
census_rdd = census_df.rdd # <1>
data_collected = census_rdd.collect() # <2>

data_collected[:3]
```
1. Отримання RDD з DataFrame
2. Виклик `collect()` для отримання всіх елементів RDD

## Показати RDD

```{python}
#| label: spark-rdd-show

for row in data_collected[:3]:
    print(row)
```

## RDD vs DataFrame {.smaller}

::: {.columns}
::: {.column}
**DataFrames**

- Вищій рівень: оптимізовано для зручності використання
- SQL-подібні операції: Працюйте з SQL-подібними запитами та виконувати складні операції
з меншою кількістю коду
- Інформація про схему: Містить стовпці та типи, як у SQL-таблиці
:::
::: {.column}
**RDDs**

- Низькорівневий: більш гнучкий, але вимагає більше рядків коду для складних операцій
- Безпека типів: Зберігають типи даних, але не мають переваг оптимізації DataFrames
- Немає схеми: Складніше працювати зі структурованими даними, такими як SQL або реляційні дані
- Масштабування
- Дуже багатослівний у порівнянні з DataFrames і погано підходить для аналітики
:::
:::

## Деякі функції та методи RDD

- `map()`: застосування функції до кожного елемента RDD
- `collect()`: отримання всіх елементів RDD

# Spark SQL

## Загальне

- Модуль в Apache Spark для обробки структурованих даних
- Дозволяє запускати SQL-запити паралельно із завданнями обробки даних
- Безшовне поєднання Python та SQL в одному додатку
- DataFrame Interfacing: Забезпечує програмний доступ до структурованих даних

## TempViews

- `createOrReplaceTempView()`: створення або заміна тимчасової таблиці

```{python}
#| label: spark-sql-table

spark = SparkSession.builder.appName("Spark SQL Example").getOrCreate()

data = [("Alice", "HR", 30), ("Bob", "IT", 40), ("Cathy", "HR", 28)]
columns = ["Name", "Department", "Age"]
df = spark.createDataFrame(data, schema=columns)

df.createOrReplaceTempView("people")

result = spark.sql("SELECT Name, Age FROM people WHERE Age > 30")
result.show()
```

## TempViews {.smaller}

- TempViews захищають основні дані під час виконання аналітики
- Завантаження з CSV використовує вже відомі нам методи

```{python}
#| label: spark-sql-table-csv

df = spark.read.csv("data/salaries.csv", header=True, inferSchema=True)
df.createOrReplaceTempView("salaries")

spark.sql("SELECT experience_level, salary_in_usd FROM salaries").show(5)
```

## SQL та DataFrame

```{python}
#| label: spark-sql-query

query_result = spark.sql("SELECT * FROM salaries WHERE job_title = 'Data Analyst'")

high_earners = query_result.withColumn("Bonus", query_result["salary_in_usd"] * 1.1) \
                            .filter(query_result["salary_in_usd"] > 100000) \
                            .select("experience_level", "job_title", "salary_in_usd", "Bonus")

high_earners.show(5)
```

## Агрегації PySpark

```{python}
#| label: spark-sql-agg

spark.sql("""
SELECT experience_level, AVG(salary_in_usd) AS avg_salary
FROM salaries
GROUP BY experience_level
ORDER BY avg_salary DESC
""").show()
```

## Комбінування SQL та DataFrame

```{python}
#| label: spark-sql-combine

filtered_df = df.filter(df["experience_level"] == "SE") # <1>

filtered_df.createOrReplaceTempView("filtered_salaries") # <2>

spark.sql("""
  SELECT job_title, AVG(salary_in_usd) AS avg_salary
  FROM filtered_salaries
  GROUP BY job_title
  HAVING avg_salary > 300000
  ORDER BY avg_salary DESC
""").show(5)
```
1. Фільтрація даних у DataFrame
2. Створення тимчасової таблиці з відфільтрованими даними

## Робота з типами даних в агрегаціях

- `cast()`: перетворення типу даних

```{python}
#| label: spark-sql-agg-types

data = [("IT", "3000"), ("IT", "4000"), ("Finance", "3500")]
columns = ["Department", "Salary"]
df = spark.createDataFrame(data, schema=columns)

df = df.withColumn("Salary", df["Salary"].cast("int"))
# Perform aggregation
df.groupBy("Department").sum("Salary").show()
```

## RDD для агрегацій

```{python}
#| label: spark-rdd-agg

rdd = df.rdd.map(lambda row: (row["Department"], row["Salary"])) # <1>

rdd_aggregated = rdd.reduceByKey(lambda x, y: x + y) # <2>

print(rdd_aggregated.collect())
```
1. Отримання RDD з DataFrame
2. Виконання агрегації за допомогою `reduceByKey()` --- групує дані за ключами та обчислює суму

## Кращі практики

- **Фільтруйте завчасно**: зменшуйте розмір даних перед виконанням агрегації
- **Працюйте з типами даних**: переконайтеся, що дані чисті та правильно введені
- **Уникайте** операцій, які використовують **весь набір даних**: мінімізуйте такі операції, як `groupBy()`
- **Виберіть правильний інтерфейс**: надавайте перевагу DataFrame для більшості завдань через їх оптимізацію
- **Відстежуйте продуктивність**: використовуйте `explain()` для перевірки плану виконання та оптимізації

## Масштабування

- PyІpark ефективно працює з гігабайтами і терабайтами даних
- Використання PySpark --- це швидкість та ефективна обробка даних
- Розуміння виконання PySpark забезпечує ще більшу ефективність
- Використовуйте `broadcast()` для управління всім кластером: 
  - `broadcast()` --- для розподілу даних на всі вузли
  - `join()` --- для об'єднання даних з різних джерел

```{python}
#| label: spark-sql-broadcast
#| eval: false

joinded_df = df1.join(broadcast(small_df2), on="key", how="inner")
```

## План виконання

- `explain()`: виведення плану виконання запиту

```{python}
#| label: spark-sql-agg-explain

df.groupBy("Department").agg({"Salary": "avg"}).explain()
```

::: footer
[explain](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.explain.html)
:::

## Кешування та зберігання {.tiny}

- `cache()`: кешування DataFrame у пам'яті
- `persist()`: зберігання DataFrame на диску або в пам'яті

```{python}
#| label: spark-sql-cache

df = spark.read.csv("data/salaries.csv", header=True, inferSchema=True)

df.cache() # <1>

df.filter(df["experience_level"] == "SE").select("job_title", "salary_in_usd").show(5) # <2>
df.groupBy("job_title").agg({"salary_in_usd": "avg"}).select("job_title", "avg(salary_in_usd)").show(5) # <3>
```

## Кешування та зберігання {.tiny}

- `MEMORY_ONLY`: кешування в пам'яті
- `MEMORY_AND_DISK`: кешування в пам'яті та на диску
- `DISK_ONLY`: кешування на диску
- ...

```{python}
#| label: spark-sql-persist

from pyspark import StorageLevel # <1>

df.persist(StorageLevel.MEMORY_ONLY) # <2>

result = df.groupBy("job_title").agg({"salary_in_usd": "avg"}) # <3>
result.show(5)

df.unpersist() # <4>
```
1. Імпорт `StorageLevel` для управління кешуванням
2. Зберігання DataFrame в пам'яті та на диску
3. Виконання запиту
4. Вивільнення кешу

::: footer
[StorageLevel](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.StorageLevel.html)
:::

## Оптимізація

- Чим більше даних використовується, тим повільніша робота: віддавайте перевагу таким інструментам, як
`map()` над `groupby()`.
- Broadcast Joins: Broadcast використовує всі обчислення, навіть на невеликих наборах даних
- Уникайте повторюваних дій: Повторювані дії над одними і тими ж даними забирають час та обчислення,
без жодної користі

# Дякую за увагу! {.unnumbered .unlisted background-iframe=".01_files/libs/colored-particles/index.html"}

<br> <br>

{{< iconify solar book-bold >}} [Матеріали курсу](https://aranaur.rbind.io/lectures/mm_big_data/)

{{< iconify mdi envelope >}} ihor.miroshnychenko\@knu.ua

{{< iconify ic baseline-telegram >}} [Data Mirosh](https://t.me/araprof)

{{< iconify mdi linkedin >}} [\@ihormiroshnychenko](https://www.linkedin.com/in/ihormiroshnychenko/)

{{< iconify mdi github >}} [\@aranaur](https://github.com/Aranaur)

{{< iconify ion home >}} [aranaur.rbind.io](https://aranaur.rbind.io)
