---
title: Лабораторна робота №3
subtitle: Хмарні технології обробки даних
subject: Python BigQuery API
lang: ua
---

::: {.callout-important}
- **Дедлайн** здачі роботи: **02.04.2024**
:::

## Мета

Ознайомити студентів з основами роботи з Google BigQuery за допомогою Python-клієнта та виконанням базових операцій над даними.

## Завдання

### Встановлення засобів

- Встановіть необхідні **пакети** для роботи з Google BigQuery у Python.
- Отримайте доступ до Google BigQuery та отримайте **ключ аутентифікації JSON**.

### Підготовка даних

- Створіть **новий проект** у Google Cloud Console.
- Створіть **новий набір даних** у Google BigQuery.
- **Завантажте набір даних** (наприклад, CSV) у створений набір даних.

### Підключення до Google BigQuery за допомогою Python

- Використовуючи отриманий ключ аутентифікації JSON, **підключіться** до Google BigQuery за допомогою Python-клієнта.

### Виконання запитів

- **Напишіть запит** за допомогою SQL для отримання певних даних з вашого набору даних.
- **Виконайте цей запит** за допомогою Python-клієнта та виведіть результати.

### Аналіз даних

- Виконайте певні операції **аналізу даних** за допомогою Python (наприклад, підрахунок кількості рядків, середні значення, групування тощо).
- **Відобразіть** отримані результати аналізу даних у вигляді графіків або діаграм.