---
title: Лабораторна робота №5
subtitle: Хмарні технології обробки даних
subject: Vertex AI та Kuberflow
lang: ua
---

::: {.callout-important}
- **Дедлайн** здачі роботи: **09.04.2024**
:::

## Мета

Автоматизація процесу навчання моделі за допомогою Kuberflow.

## Завдання

### 1. Налаштування середовища розробки:

- Налаштуйте середовище розробки для використання Vertex AI.

### 2. Побудова моделей з використанням Kuberflow:

- Ініціалізуйте конвеєр для навчання моделі з використанням Kuberflow.
- Скомпілюйте ініціалізований конвеєр.
- Створіть Vertex AI Pipeline Job.
- Перевірте роботу конвеєра.

### 3. Оцінка якості та отримання прогнозних значень:

- Оцініть якість моделі за допомогою метрик якості.
- Порівняйте якість моделі з попередніми результатами.
- Отримайте прогнозні значення для тестового набору даних.
- Збережіть прогнозні значення у файл.
- Завантажте файл з прогнозними значеннями у хмарне сховище.
- Перевірте збережені прогнозні значення.

### 5. Звіт та висновки:

- Підготуйте звіт, що включає в себе опис процесу роботи, отримані результати, аналіз та висновки.

