---
title: Екзамен
subtitle: Хмарні технології обробки даних
lang: ua
---

::: {.callout-caution collapse="true"}
## Розподіл по варіантах

```{python}
#| label: options
#| echo: true
#| code-fold: true

import pandas as pd
import random

random.seed(23042025)

# Список студентів
students = [
    'Абрамов Кірілл Вікторович',
    'Білуха Назар Романович',
    'Гамзін Нікіта Сергійович',
    'Ільчук Олександр Михайлович',
    'Книш Сніжана Михайлівна',
    'Ковальчук Данило',
    'Лаврій Руслан Романович',
    'Лаврій Софія Петрівна',
    'Майданик Андрій Олександрович',
    'Марчук Дмитро Андрійович',
    'Мінін Ігор Борисович',
    'Немченко Катерина Юріївна',
    'Нечипорук Вікторія Олександрівна',
    'Орищак Богдан Ігорович',
    'Пелішенко Владислав Святославович',
    'Подольський Нікіта Володимирович',
    'Прохорчук Дмитро Сергійович',
    'Рудківський Євгеній Віталійович',
    'Українець Андрій Олександрович',
    'Шпирук Євгенія Сергіївна'
]

# Список варіантів роботи
lab_work = [f'Варіант {i}' for i in range(1, 5)]

# Випадковий розподіл варіантів роботи між студентами
random.shuffle(students)  # перемішуємо студентів
assignments = [(student, lab_work[i % len(lab_work)]) for i, student in enumerate(students)]

# Створення датафрейму з результатами
df = pd.DataFrame(assignments, columns=['Студент', 'Варіант'])

df.sort_values(by='Студент').style.hide(axis="index")
```
:::

::: {.callout-important}
<center>**ВСІ РОБОТИ ЗАВАНТАЖУЄТЕ ОКРЕМОЮ ПАПКОЮ У ХМАРУ, КУДИ ЗАВАНТАЖУВАЛИ ЛАБОРАТОРНІ РОБОТИ!**</center>
:::

## Попередні вимоги

- Для **виконання 1 та 2 завдань** необхідно завантажити дані з [лабораторної роботи №1](https://aranaur.quarto.pub/01-lab-cloud-24/) у BigQuery.
- Для **виконання 3 завдання** необхідно буде завантажити наступні [файли](https://github.com/Aranaur/ML23/tree/main/exam/data)


:::::: {.panel-tabset}

### Варіант 1

::: {.callout-note collapse="true"}
#### Завдання 1: BigQuery {#sec-1-1}

Розглянемо метрику **CAC (Customer Acquisition Cost)**, яка відображає **витрати на залучення одного покупця**.

Уявімо ситуацію: до нас звернулися маркетологи з проханням порівняти дві рекламні кампанії.

У рекламній **кампанії №1** про наш додаток розповів відомий блогер на Youtube-каналі про кулінарії. На цю інтеграцію сумарно витратили **250 000 грошових одиниць**. Внаслідок цієї кампанії **1 вересня** у додатку зареєструвалася **171 особа**.

У рамках рекламної кампанії №2 користувачам показували таргетовану рекламу у соціальних мережах. На це теж сумарно витратили **250 000 грошових одиниць**, і в результаті **1 вересня** у нас з'явилося **236 нових користувачів**.

Як нам оцінити, який із каналів залучення спрацював краще? На перший погляд, друга кампанія показала себе краще, оскільки нам удалося залучити більше людей за ті самі гроші. Але не поспішатимемо з висновками — давайте спочатку проведемо докладніший аналіз і розрахуємо **CAC** для двох рекламних кампаній.

На основі таблиці `user_actions` розрахуйте метрику **CAC** для двох рекламних кампаній.

Список id користувачів, що прийшли після **рекламної кампанії №1**:

```{markdown}
8631, 8632, 8638, 8643, 8657, 8673, 8706, 8707, 8715, 8723, 8732, 8739, 8741, 
8750, 8751, 8752, 8770, 8774, 8788, 8791, 8804, 8810, 8815, 8828, 8830, 8845, 
8853, 8859, 8867, 8869, 8876, 8879, 8883, 8896, 8909, 8911, 8933, 8940, 8972, 
8976, 8988, 8990, 9002, 9004, 9009, 9019, 9020, 9035, 9036, 9061, 9069, 9071, 
9075, 9081, 9085, 9089, 9108, 9113, 9144, 9145, 9146, 9162, 9165, 9167, 9175, 
9180, 9182, 9197, 9198, 9210, 9223, 9251, 9257, 9278, 9287, 9291, 9313, 9317, 
9321, 9334, 9351, 9391, 9398, 9414, 9420, 9422, 9431, 9450, 9451, 9454, 9472, 
9476, 9478, 9491, 9494, 9505, 9512, 9518, 9524, 9526, 9528, 9531, 9535, 9550, 
9559, 9561, 9562, 9599, 9603, 9605, 9611, 9612, 9615, 9625, 9633, 9652, 9654, 
9655, 9660, 9662, 9667, 9677, 9679, 9689, 9695, 9720, 9726, 9739, 9740, 9762, 
9778, 9786, 9794, 9804, 9810, 9813, 9818, 9828, 9831, 9836, 9838, 9845, 9871, 
9887, 9891, 9896, 9897, 9916, 9945, 9960, 9963, 9965, 9968, 9971, 9993, 9998, 
9999, 10001, 10013, 10016, 10023, 10030, 10051, 10057, 10064, 10082, 10103, 
10105, 10122, 10134, 10135
```

Список id користувачів, що прийшли після **рекламної кампанії №2**:

```{markdown}
8629, 8630, 8644, 8646, 8650, 8655, 8659, 8660, 8663, 8665, 8670, 8675, 8680, 8681, 
8682, 8683, 8694, 8697, 8700, 8704, 8712, 8713, 8719, 8729, 8733, 8742, 8748, 8754, 
8771, 8794, 8795, 8798, 8803, 8805, 8806, 8812, 8814, 8825, 8827, 8838, 8849, 8851, 
8854, 8855, 8870, 8878, 8882, 8886, 8890, 8893, 8900, 8902, 8913, 8916, 8923, 8929, 
8935, 8942, 8943, 8949, 8953, 8955, 8966, 8968, 8971, 8973, 8980, 8995, 8999, 9000, 
9007, 9013, 9041, 9042, 9047, 9064, 9068, 9077, 9082, 9083, 9095, 9103, 9109, 9117, 
9123, 9127, 9131, 9137, 9140, 9149, 9161, 9179, 9181, 9183, 9185, 9190, 9196, 9203, 
9207, 9226, 9227, 9229, 9230, 9231, 9250, 9255, 9259, 9267, 9273, 9281, 9282, 9289, 
9292, 9303, 9310, 9312, 9315, 9327, 9333, 9335, 9337, 9343, 9356, 9368, 9370, 9383, 
9392, 9404, 9410, 9421, 9428, 9432, 9437, 9468, 9479, 9483, 9485, 9492, 9495, 9497, 
9498, 9500, 9510, 9527, 9529, 9530, 9538, 9539, 9545, 9557, 9558, 9560, 9564, 9567, 
9570, 9591, 9596, 9598, 9616, 9631, 9634, 9635, 9636, 9658, 9666, 9672, 9684, 9692, 
9700, 9704, 9706, 9711, 9719, 9727, 9735, 9741, 9744, 9749, 9752, 9753, 9755, 9757, 
9764, 9783, 9784, 9788, 9790, 9808, 9820, 9839, 9841, 9843, 9853, 9855, 9859, 9863, 
9877, 9879, 9880, 9882, 9883, 9885, 9901, 9904, 9908, 9910, 9912, 9920, 9929, 9930, 
9935, 9939, 9958, 9959, 9961, 9983, 10027, 10033, 10038, 10045, 10047, 10048, 10058, 
10059, 10067, 10069, 10073, 10075, 10078, 10079, 10081, 10092, 10106, 10110, 10113, 10131
```

Назвіть колонку з найменуваннями кампаній `ads_campaign`, а колонку зі значенням метрики — `cac`.

Назви кампаній виведіть у такому вигляді:

- `Company 1`
- `Company 2`

Отримані значення метрики округліть *до двох знаків після коми*.

Результат має бути *відсортований за зменшенням* значення метрики.

Поля у фінальній таблиці: `ads_campaign`, `cac`

:::

---

::: {.callout-note collapse="true"}
#### Завдання 2: Looker Studio {#sec-1-2}

До отриманих результатів з попереднього завдання побудуйте візуалізацію за допомогою **Looker Studio**.

Надайте доступ до візуалізації.
:::

---

::: {.callout-note collapse="true"}
#### Завдання 3: BigQuery ML {#sec-1-3}

Завантажте [файли](https://github.com/Aranaur/ML23/tree/main/exam/data) у BigQuery. У вас має бути два файли:

- Навчальний набір даних (`train.csv`).
- Тестовий набір даних (`test.csv`).

Дані отримані від [Yelp](https://www.yelp.com/dataset).

**Ваша задача: Використовуйте дані ресторанів, щоб передбачити, чи матимуть вони рейтинг 4.5 зірки або вище.**

::: {.callout-note}
## Важливо

Ви повинні будете використовувати числову змінну `stars` (рейтинги ресторанів), щоб створити власну змінну результату, яка буде `Yes`, якщо рейтинг ресторану становить 4.5 зірки або вище, і `No`, якщо середня оцінка ресторану нижче 4.5.

*Підказка:* Можливо, ви захочете викинути `stars` (тобто не використовуйте її для прогнозування).

:::

##### Основні кроки

1. Завантажте дані (за потреби очистіть їх). Оберіть декілька змінних, які найкраще підходять для цієї задачі (мінімум 2).<br>
2. Виберіть методи для цієї задачі класифікації.

::: {.callout-tip}
## Примітка

Ви **не можете** вибрати звичайну МНК регресію або звичайну логістичну регресію.
:::

3. Обробіть дані. Цей крок включає нормалізацію, створення нових змінних/взаємодій тощо.
4. Налаштуйте гіперпараметри вашої моделі.
5. Оцініть `accuracy` вашої моделі на валідаційній вибірці.
6. Оцініть `precision` вашої моделі на валідаційній вибірці.
7. Навчіть свою найкращу модель на повному навчальному наборі даних. Прогнозуйте на тестовому наборі даних. Оцініть ефективність.
:::


### Варіант 2

::: {.callout-note collapse="true"}
#### Завдання 1: BigQuery {#sec-2-1}

Уявімо ситуацію: до нас звернулися маркетологи з проханням порівняти дві рекламні кампанії.

В межах **кампанії №1** про наш додаток розповів відомий блогер на Youtube-каналі про кулінарії. В межах рекламної **кампанії №2** користувачам показували таргетовану рекламу у соціальних мережах.

Список id користувачів, що прийшли після **рекламної кампанії №1**:

```{markdown}
8631, 8632, 8638, 8643, 8657, 8673, 8706, 8707, 8715, 8723, 8732, 8739, 8741, 
8750, 8751, 8752, 8770, 8774, 8788, 8791, 8804, 8810, 8815, 8828, 8830, 8845, 
8853, 8859, 8867, 8869, 8876, 8879, 8883, 8896, 8909, 8911, 8933, 8940, 8972, 
8976, 8988, 8990, 9002, 9004, 9009, 9019, 9020, 9035, 9036, 9061, 9069, 9071, 
9075, 9081, 9085, 9089, 9108, 9113, 9144, 9145, 9146, 9162, 9165, 9167, 9175, 
9180, 9182, 9197, 9198, 9210, 9223, 9251, 9257, 9278, 9287, 9291, 9313, 9317, 
9321, 9334, 9351, 9391, 9398, 9414, 9420, 9422, 9431, 9450, 9451, 9454, 9472, 
9476, 9478, 9491, 9494, 9505, 9512, 9518, 9524, 9526, 9528, 9531, 9535, 9550, 
9559, 9561, 9562, 9599, 9603, 9605, 9611, 9612, 9615, 9625, 9633, 9652, 9654, 
9655, 9660, 9662, 9667, 9677, 9679, 9689, 9695, 9720, 9726, 9739, 9740, 9762, 
9778, 9786, 9794, 9804, 9810, 9813, 9818, 9828, 9831, 9836, 9838, 9845, 9871, 
9887, 9891, 9896, 9897, 9916, 9945, 9960, 9963, 9965, 9968, 9971, 9993, 9998, 
9999, 10001, 10013, 10016, 10023, 10030, 10051, 10057, 10064, 10082, 10103, 
10105, 10122, 10134, 10135
```

Список id користувачів, що прийшли після **рекламної кампанії №2**:

```{markdown}
8629, 8630, 8644, 8646, 8650, 8655, 8659, 8660, 8663, 8665, 8670, 8675, 8680, 8681, 
8682, 8683, 8694, 8697, 8700, 8704, 8712, 8713, 8719, 8729, 8733, 8742, 8748, 8754, 
8771, 8794, 8795, 8798, 8803, 8805, 8806, 8812, 8814, 8825, 8827, 8838, 8849, 8851, 
8854, 8855, 8870, 8878, 8882, 8886, 8890, 8893, 8900, 8902, 8913, 8916, 8923, 8929, 
8935, 8942, 8943, 8949, 8953, 8955, 8966, 8968, 8971, 8973, 8980, 8995, 8999, 9000, 
9007, 9013, 9041, 9042, 9047, 9064, 9068, 9077, 9082, 9083, 9095, 9103, 9109, 9117, 
9123, 9127, 9131, 9137, 9140, 9149, 9161, 9179, 9181, 9183, 9185, 9190, 9196, 9203, 
9207, 9226, 9227, 9229, 9230, 9231, 9250, 9255, 9259, 9267, 9273, 9281, 9282, 9289, 
9292, 9303, 9310, 9312, 9315, 9327, 9333, 9335, 9337, 9343, 9356, 9368, 9370, 9383, 
9392, 9404, 9410, 9421, 9428, 9432, 9437, 9468, 9479, 9483, 9485, 9492, 9495, 9497, 
9498, 9500, 9510, 9527, 9529, 9530, 9538, 9539, 9545, 9557, 9558, 9560, 9564, 9567, 
9570, 9591, 9596, 9598, 9616, 9631, 9634, 9635, 9636, 9658, 9666, 9672, 9684, 9692, 
9700, 9704, 9706, 9711, 9719, 9727, 9735, 9741, 9744, 9749, 9752, 9753, 9755, 9757, 
9764, 9783, 9784, 9788, 9790, 9808, 9820, 9839, 9841, 9843, 9853, 9855, 9859, 9863, 
9877, 9879, 9880, 9882, 9883, 9885, 9901, 9904, 9908, 9910, 9912, 9920, 9929, 9930, 
9935, 9939, 9958, 9959, 9961, 9983, 10027, 10033, 10038, 10045, 10047, 10048, 10058, 
10059, 10067, 10069, 10073, 10075, 10078, 10079, 10081, 10092, 10106, 10110, 10113, 10131
```

Retention rate – коефіцієнт утримання клієнтів. Він показує частку користувачів, які повернулися до програми через N днів, тижнів або місяців після свого першого входу — метрику можна розраховувати за будь-якими цікавими періодами.

Для кожної рекламної кампанії порахуйте **Retention 1-го та 7-го дня** у залучених користувачів.

У результаті включіть чотири колонки: колонку з найменуваннями кампаній, дату першої взаємодії з додатком, кількість днів, що минули з дати першої взаємодії (порядковий номер), і саме значення Retention.

Колонки зі значеннями назвіть відповідно `ads_campaign`, `start_date`, `day_number`, `retention`.

Назви кампаній виведіть у такому вигляді:

- `Company 1`
- `Company 2`

Метрику необхідно виразити у вигляді частки, округливши отримані значення **до двох знаків після коми**.

Результат має бути відсортований спочатку за найменуванням кампанії (за зростанням), потім за зростанням порядкового номера дня.

У результат мають потрапити наступні дні: **нульовий, перший та сьомий**.

Поля в фінальній таблиці: `ads_campaign`, `start_date`, `day_number`, `retention`
:::

---

::: {.callout-note collapse="true"}
#### Завдання 2: Looker Studio {#sec-2-2}

До отриманих результатів з попереднього завдання побудуйте візуалізацію за допомогою **Looker Studio**.

Надайте доступ до візуалізації.
:::

---

::: {.callout-note collapse="true"}
#### Завдання 3: BigQuery ML {#sec-2-3}

Завантажте [файли](https://github.com/Aranaur/ML23/tree/main/exam/data) у BigQuery. У вас має бути два файли:

- Навчальний набір даних (`train.csv`).
- Тестовий набір даних (`test.csv`).

Дані отримані від [Yelp](https://www.yelp.com/dataset).

**Ваша задача: Використовуйте дані ресторанів, щоб передбачити, чи матимуть вони рейтинг 4.5 зірки або вище.**

::: {.callout-note}
## Важливо

Ви повинні будете використовувати числову змінну `stars` (рейтинги ресторанів), щоб створити власну змінну результату, яка буде `Yes`, якщо рейтинг ресторану становить 4.5 зірки або вище, і `No`, якщо середня оцінка ресторану нижче 4.5.

*Підказка:* Можливо, ви захочете викинути `stars` (тобто не використовуйте її для прогнозування).

:::

##### Основні кроки

1. Завантажте дані (за потреби очистіть їх). Оберіть декілька змінних, які найкраще підходять для цієї задачі (мінімум 2).<br>
2. Виберіть методи для цієї задачі класифікації.

::: {.callout-tip}
## Примітка

Ви **не можете** вибрати звичайну МНК регресію або звичайну логістичну регресію.
:::

3. Обробіть дані. Цей крок включає нормалізацію, створення нових змінних/взаємодій тощо.
4. Налаштуйте гіперпараметри вашої моделі.
5. Оцініть `accuracy` вашої моделі на валідаційній вибірці.
6. Оцініть `precision` вашої моделі на валідаційній вибірці.
7. Навчіть свою найкращу модель на повному навчальному наборі даних. Прогнозуйте на тестовому наборі даних. Оцініть ефективність.
:::

### Варіант 3

::: {.callout-note collapse="true"}
#### Завдання 1: BigQuery {#sec-3-1}

Уявімо ситуацію: до нас звернулися маркетологи з проханням порівняти дві рекламні кампанії.

В межах **кампанії №1** про наш додаток розповів відомий блогер на Youtube-каналі про кулінарії. В межах рекламної **кампанії №2** користувачам показували таргетовану рекламу у соціальних мережах.

Список id користувачів, що прийшли після **рекламної кампанії №1**:

```{markdown}
8631, 8632, 8638, 8643, 8657, 8673, 8706, 8707, 8715, 8723, 8732, 8739, 8741, 
8750, 8751, 8752, 8770, 8774, 8788, 8791, 8804, 8810, 8815, 8828, 8830, 8845, 
8853, 8859, 8867, 8869, 8876, 8879, 8883, 8896, 8909, 8911, 8933, 8940, 8972, 
8976, 8988, 8990, 9002, 9004, 9009, 9019, 9020, 9035, 9036, 9061, 9069, 9071, 
9075, 9081, 9085, 9089, 9108, 9113, 9144, 9145, 9146, 9162, 9165, 9167, 9175, 
9180, 9182, 9197, 9198, 9210, 9223, 9251, 9257, 9278, 9287, 9291, 9313, 9317, 
9321, 9334, 9351, 9391, 9398, 9414, 9420, 9422, 9431, 9450, 9451, 9454, 9472, 
9476, 9478, 9491, 9494, 9505, 9512, 9518, 9524, 9526, 9528, 9531, 9535, 9550, 
9559, 9561, 9562, 9599, 9603, 9605, 9611, 9612, 9615, 9625, 9633, 9652, 9654, 
9655, 9660, 9662, 9667, 9677, 9679, 9689, 9695, 9720, 9726, 9739, 9740, 9762, 
9778, 9786, 9794, 9804, 9810, 9813, 9818, 9828, 9831, 9836, 9838, 9845, 9871, 
9887, 9891, 9896, 9897, 9916, 9945, 9960, 9963, 9965, 9968, 9971, 9993, 9998, 
9999, 10001, 10013, 10016, 10023, 10030, 10051, 10057, 10064, 10082, 10103, 
10105, 10122, 10134, 10135
```

Список id користувачів, що прийшли після **рекламної кампанії №2**:

```{markdown}
8629, 8630, 8644, 8646, 8650, 8655, 8659, 8660, 8663, 8665, 8670, 8675, 8680, 8681, 
8682, 8683, 8694, 8697, 8700, 8704, 8712, 8713, 8719, 8729, 8733, 8742, 8748, 8754, 
8771, 8794, 8795, 8798, 8803, 8805, 8806, 8812, 8814, 8825, 8827, 8838, 8849, 8851, 
8854, 8855, 8870, 8878, 8882, 8886, 8890, 8893, 8900, 8902, 8913, 8916, 8923, 8929, 
8935, 8942, 8943, 8949, 8953, 8955, 8966, 8968, 8971, 8973, 8980, 8995, 8999, 9000, 
9007, 9013, 9041, 9042, 9047, 9064, 9068, 9077, 9082, 9083, 9095, 9103, 9109, 9117, 
9123, 9127, 9131, 9137, 9140, 9149, 9161, 9179, 9181, 9183, 9185, 9190, 9196, 9203, 
9207, 9226, 9227, 9229, 9230, 9231, 9250, 9255, 9259, 9267, 9273, 9281, 9282, 9289, 
9292, 9303, 9310, 9312, 9315, 9327, 9333, 9335, 9337, 9343, 9356, 9368, 9370, 9383, 
9392, 9404, 9410, 9421, 9428, 9432, 9437, 9468, 9479, 9483, 9485, 9492, 9495, 9497, 
9498, 9500, 9510, 9527, 9529, 9530, 9538, 9539, 9545, 9557, 9558, 9560, 9564, 9567, 
9570, 9591, 9596, 9598, 9616, 9631, 9634, 9635, 9636, 9658, 9666, 9672, 9684, 9692, 
9700, 9704, 9706, 9711, 9719, 9727, 9735, 9741, 9744, 9749, 9752, 9753, 9755, 9757, 
9764, 9783, 9784, 9788, 9790, 9808, 9820, 9839, 9841, 9843, 9853, 9855, 9859, 9863, 
9877, 9879, 9880, 9882, 9883, 9885, 9901, 9904, 9908, 9910, 9912, 9920, 9929, 9930, 
9935, 9939, 9958, 9959, 9961, 9983, 10027, 10033, 10038, 10045, 10047, 10048, 10058, 
10059, 10067, 10069, 10073, 10075, 10078, 10079, 10081, 10092, 10106, 10110, 10113, 10131
```

Для кожної рекламної кампанії порахуйте середню вартість замовлення залучених користувачів за перший тиждень використання програми **з 1 по 7 вересня 2022 року**.

Назвіть колонку з найменуваннями кампаній `ads_campaign`, а колонку зі значенням метрики — `avg_check`.

Назви кампаній виведіть у такому вигляді:

- Company 1
- Company 2

Отримані значення метрики необхідно округліть **до двох знаків після коми**.

Результат має бути відсортований **за зменшенням значення метрики**.

Поля у фінальній таблиці: `ads_campaign`, `avg_check`
:::

---

::: {.callout-note collapse="true"}
#### Завдання 2: Looker Studio {#sec-3-2}

До отриманих результатів з попереднього завдання побудуйте візуалізацію за допомогою **Looker Studio**.

Надайте доступ до візуалізації.
:::

---

::: {.callout-note collapse="true"}
#### Завдання 3: BigQuery ML {#sec-3-3}

Завантажте [файли](https://github.com/Aranaur/ML23/tree/main/exam/data) у BigQuery. У вас має бути два файли:

- Навчальний набір даних (`train.csv`).
- Тестовий набір даних (`test.csv`).

Дані отримані від [Yelp](https://www.yelp.com/dataset).

**Ваша задача: Використовуйте дані ресторанів, щоб передбачити, чи матимуть вони рейтинг 4.5 зірки або вище.**

::: {.callout-note}
## Важливо

Ви повинні будете використовувати числову змінну `stars` (рейтинги ресторанів), щоб створити власну змінну результату, яка буде `Yes`, якщо рейтинг ресторану становить 4.5 зірки або вище, і `No`, якщо середня оцінка ресторану нижче 4.5.

*Підказка:* Можливо, ви захочете викинути `stars` (тобто не використовуйте її для прогнозування).

:::

##### Основні кроки

1. Завантажте дані (за потреби очистіть їх). Оберіть декілька змінних, які найкраще підходять для цієї задачі (мінімум 2).<br>
2. Виберіть методи для цієї задачі класифікації.

::: {.callout-tip}
## Примітка

Ви **не можете** вибрати звичайну МНК регресію або звичайну логістичну регресію.
:::

3. Обробіть дані. Цей крок включає нормалізацію, створення нових змінних/взаємодій тощо.
4. Налаштуйте гіперпараметри вашої моделі.
5. Оцініть `accuracy` вашої моделі на валідаційній вибірці.
6. Оцініть `precision` вашої моделі на валідаційній вибірці.
7. Навчіть свою найкращу модель на повному навчальному наборі даних. Прогнозуйте на тестовому наборі даних. Оцініть ефективність.
:::

### Варіант 4

::: {.callout-note collapse="true"}
#### Завдання 1: BigQuery {#sec-4-1}

Уявімо ситуацію: до нас звернулися маркетологи з проханням порівняти дві рекламні кампанії.

В межах **кампанії №1** про наш додаток розповів відомий блогер на Youtube-каналі про кулінарії. В межах рекламної **кампанії №2** користувачам показували таргетовану рекламу у соціальних мережах.

Список id користувачів, що прийшли після **рекламної кампанії №1**:

```{markdown}
8631, 8632, 8638, 8643, 8657, 8673, 8706, 8707, 8715, 8723, 8732, 8739, 8741, 
8750, 8751, 8752, 8770, 8774, 8788, 8791, 8804, 8810, 8815, 8828, 8830, 8845, 
8853, 8859, 8867, 8869, 8876, 8879, 8883, 8896, 8909, 8911, 8933, 8940, 8972, 
8976, 8988, 8990, 9002, 9004, 9009, 9019, 9020, 9035, 9036, 9061, 9069, 9071, 
9075, 9081, 9085, 9089, 9108, 9113, 9144, 9145, 9146, 9162, 9165, 9167, 9175, 
9180, 9182, 9197, 9198, 9210, 9223, 9251, 9257, 9278, 9287, 9291, 9313, 9317, 
9321, 9334, 9351, 9391, 9398, 9414, 9420, 9422, 9431, 9450, 9451, 9454, 9472, 
9476, 9478, 9491, 9494, 9505, 9512, 9518, 9524, 9526, 9528, 9531, 9535, 9550, 
9559, 9561, 9562, 9599, 9603, 9605, 9611, 9612, 9615, 9625, 9633, 9652, 9654, 
9655, 9660, 9662, 9667, 9677, 9679, 9689, 9695, 9720, 9726, 9739, 9740, 9762, 
9778, 9786, 9794, 9804, 9810, 9813, 9818, 9828, 9831, 9836, 9838, 9845, 9871, 
9887, 9891, 9896, 9897, 9916, 9945, 9960, 9963, 9965, 9968, 9971, 9993, 9998, 
9999, 10001, 10013, 10016, 10023, 10030, 10051, 10057, 10064, 10082, 10103, 
10105, 10122, 10134, 10135
```

Список id користувачів, що прийшли після **рекламної кампанії №2**:

```{markdown}
8629, 8630, 8644, 8646, 8650, 8655, 8659, 8660, 8663, 8665, 8670, 8675, 8680, 8681, 
8682, 8683, 8694, 8697, 8700, 8704, 8712, 8713, 8719, 8729, 8733, 8742, 8748, 8754, 
8771, 8794, 8795, 8798, 8803, 8805, 8806, 8812, 8814, 8825, 8827, 8838, 8849, 8851, 
8854, 8855, 8870, 8878, 8882, 8886, 8890, 8893, 8900, 8902, 8913, 8916, 8923, 8929, 
8935, 8942, 8943, 8949, 8953, 8955, 8966, 8968, 8971, 8973, 8980, 8995, 8999, 9000, 
9007, 9013, 9041, 9042, 9047, 9064, 9068, 9077, 9082, 9083, 9095, 9103, 9109, 9117, 
9123, 9127, 9131, 9137, 9140, 9149, 9161, 9179, 9181, 9183, 9185, 9190, 9196, 9203, 
9207, 9226, 9227, 9229, 9230, 9231, 9250, 9255, 9259, 9267, 9273, 9281, 9282, 9289, 
9292, 9303, 9310, 9312, 9315, 9327, 9333, 9335, 9337, 9343, 9356, 9368, 9370, 9383, 
9392, 9404, 9410, 9421, 9428, 9432, 9437, 9468, 9479, 9483, 9485, 9492, 9495, 9497, 
9498, 9500, 9510, 9527, 9529, 9530, 9538, 9539, 9545, 9557, 9558, 9560, 9564, 9567, 
9570, 9591, 9596, 9598, 9616, 9631, 9634, 9635, 9636, 9658, 9666, 9672, 9684, 9692, 
9700, 9704, 9706, 9711, 9719, 9727, 9735, 9741, 9744, 9749, 9752, 9753, 9755, 9757, 
9764, 9783, 9784, 9788, 9790, 9808, 9820, 9839, 9841, 9843, 9853, 9855, 9859, 9863, 
9877, 9879, 9880, 9882, 9883, 9885, 9901, 9904, 9908, 9910, 9912, 9920, 9929, 9930, 
9935, 9939, 9958, 9959, 9961, 9983, 10027, 10033, 10038, 10045, 10047, 10048, 10058, 
10059, 10067, 10069, 10073, 10075, 10078, 10079, 10081, 10092, 10106, 10110, 10113, 10131
```

Оцінимо показник, який відображає рентабельність інвестицій і показує, наскільки вигідним є той чи інший проект чи продукт. Ця метрика називається **ROI (Return on Investment)**, у маркетингу її часто застосовують для підрахунку окупності рекламних кампаній.

Наведемо приклад. Допустимо, ми вклали в рекламу **100 грошових одиниць** і в результаті продали товарів на **220 грошових одиниць**. Тоді **ROI** буде розрахований так:

$$ ROI = \frac{220 - 100}{100} \times 100\% = 120\% $$

Таким чином, на кожну вкладену одиницю грошей у рекламу ми отримали 1.2 грошових одиниць прибутку.

Порівняємо дві рекламні кампанії за значеннями метрики **ROI** і зробимо висновок про те, який з рекламних каналів більшою мірою окупає витрати на залучення нових користувачів.

Розрахуйте **ROI** для кожного рекламного каналу.

Назвіть колонку з найменуваннями кампаній `ads_campaign`, а колонку зі значенням метрики — `roi`.

Назви кампаній виведіть у такому вигляді:

- `Company 1`
- `Company 2`

Отримані значення метрики необхідно виразити **у відсотках** та округлити **до двох знаків після коми**.

Результат має бути відсортований **за зменшенням** значення метрики.

Поля у фінальній таблиці: `ads_campaign`, `roi`
:::

---

::: {.callout-note collapse="true"}
#### Завдання 2: Looker Studio {#sec-4-2}

До отриманих результатів з попереднього завдання побудуйте візуалізацію за допомогою **Looker Studio**.

Надайте доступ до візуалізації.
:::

---

::: {.callout-note collapse="true"}
#### Завдання 3: BigQuery ML {#sec-4-3}

Завантажте [файли](https://github.com/Aranaur/ML23/tree/main/exam/data) у BigQuery. У вас має бути два файли:

- Навчальний набір даних (`train.csv`).
- Тестовий набір даних (`test.csv`).

Дані отримані від [Yelp](https://www.yelp.com/dataset).

**Ваша задача: Використовуйте дані ресторанів, щоб передбачити, чи матимуть вони рейтинг 4.5 зірки або вище.**

::: {.callout-note}
## Важливо

Ви повинні будете використовувати числову змінну `stars` (рейтинги ресторанів), щоб створити власну змінну результату, яка буде `Yes`, якщо рейтинг ресторану становить 4.5 зірки або вище, і `No`, якщо середня оцінка ресторану нижче 4.5.

*Підказка:* Можливо, ви захочете викинути `stars` (тобто не використовуйте її для прогнозування).

:::

##### Основні кроки

1. Завантажте дані (за потреби очистіть їх). Оберіть декілька змінних, які найкраще підходять для цієї задачі (мінімум 2).<br>
2. Виберіть методи для цієї задачі класифікації.

::: {.callout-tip}
## Примітка

Ви **не можете** вибрати звичайну МНК регресію або звичайну логістичну регресію.
:::

3. Обробіть дані. Цей крок включає нормалізацію, створення нових змінних/взаємодій тощо.
4. Налаштуйте гіперпараметри вашої моделі.
5. Оцініть `accuracy` вашої моделі на валідаційній вибірці.
6. Оцініть `precision` вашої моделі на валідаційній вибірці.
7. Навчіть свою найкращу модель на повному навчальному наборі даних. Прогнозуйте на тестовому наборі даних. Оцініть ефективність.
:::
:::


