---
title: Завдання №1
subtitle: "Прикладна аналітика"
format:
    html: default
    pdf:
        include-in-header: preamble.tex
---

# Задачі на базові типи даних

1. Напишіть програму, яка вітає користувача, виводячи слово `Hello`, введене ім'я та розділові знаки за зразком (див. приклад вхідних і вихідних даних). Програма має зчитувати в строкову змінну значення і писати відповідне привітання. Зверніть увагу, що після коми має обов'язково стояти пробіл, а перед знаком оклику пробілу немає. *Операцією конкатенації рядків (`+`) користуватися не можна*.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | Harry       | Hello, Harry! |
    | Ron         | Hello, Ron!   |
    | Hermione    | Hello, Hermione! |

    : **Приклад** {.striped .hover}

2. Напишіть програму, яка за заданим числом `N` від 1 до 9 виводить на екран `N` пінгвінів. Зображення одного пінгвіна має розмір 5×9 символів, між двома сусідніми пінгвінами також є порожній (із пропусків) стовпець. Дозволяється вивести порожній стовпець після останнього пінгвіна. Для спрощення малювання скопіюйте пінгвіна з прикладу в середовище розробки. **Приклад:**

    **Вхідні дані**: `N` = 3

```{.markdown}
   _~_       _~_       _~_    
  (o o)     (o o)     (o o)   
 /  V  \   /  V  \   /  V  \  
/(  _  )\ /(  _  )\ /(  _  )\ 
  ^^ ^^     ^^ ^^     ^^ ^^   
```

`N` = 1

```{.markdown}
   _~_   
  (o o)   
 /  V  \   
/(  _  )\
  ^^ ^^  
```



3. `N` школярів **ділять** `K` яблук порівну, залишок, що не ділиться, залишається в кошику. Скільки яблук дістанеться кожному школяреві?

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 3, 14       | 4            |

    : **Приклад** {.striped .hover}

4. `N` школярів **поділили** `K` яблук порівну, залишок, що не ділиться, залишився в кошику. Скільки яблук залишилося в кошику?

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 3, 14       | 2            |

    : **Приклад** {.striped .hover}

5. Вводиться ціле невід'ємне число `N` (`N` ≤ 100). Виведіть $2^{N}$.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 2           | 4            |

    : **Приклад** {.striped .hover}

6. Дано натуральне число. Виведіть його останню цифру.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 179         | 9            |

    : **Приклад** {.striped .hover}

7. Дано двозначне число. Знайдіть число десятків у ньому.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 42          | 4            |

    : **Приклад** {.striped .hover}

8. Дано натуральне число. Знайдіть число десятків у його десятковому записі (другу праворуч цифру).

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 173         | 7            |

    : **Приклад** {.striped .hover}

9. Дано тризначне число. Знайдіть суму його цифр.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 179         | 17           |

    : **Приклад** {.striped .hover}

10. Запишіть літеру `A` (латинську, заголовну) 100 разів поспіль. Напишіть програму, яка виводить цей рядок (тільки букви, без лапок).

11. Дано число `N`. Від початку доби минуло `N` хвилин. Визначте, скільки годин і хвилин показуватиме електронний годинник у цей момент. Програма має вивести два числа: кількість годин (від 0 до 23) і кількість хвилин (від 0 до 59). Врахуйте, що число `N` може бути більшим, ніж кількість хвилин у добі.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 150         | 2 30         |

    : **Приклад** {.striped .hover}

12. Програма отримує на вхід три числа: `A`, `B`, `N` - цілі, невід'ємні. Пиріжок у їдальні коштує `A` гривень і `B` копійок. Визначте, скільки гривень і копійок потрібно заплатити за `N` пиріжків.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 10, 15, 2   | 20 30        |
    | 2, 50, 4    | 10 0         |

    : **Приклад** {.striped .hover}

13. Напишіть програму, яка зчитує ціле число і виводить текст, аналогічний наведеному в прикладі (важливо точно дотримуватися виведення програми: зверніть увагу на пробіли і на крапки). Не можна користуватися конкатенацією рядків, використовуйте `print()` з кількома параметрами.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 179         | The next number for the number 179 is 180. The previous number for the number 179 is 178. |
    | 0           | The next number for the number 0 is 1. The previous number for the number 0 is -1.       |

    : **Приклад** {.striped .hover}

14. Вводиться число `0` або `1`, необхідно вивести `1` або `0` відповідно.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 0           | 1            |
    | 1           | 0            |

    : **Приклад** {.striped .hover}

15. Дано ціле число `N`. Виведіть наступне за ним парне число.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 7           | 8            |
    | 8           | 10           |

    : **Приклад** {.striped .hover}

16. Задане число `N` записали 10 разів поспіль і потім піднесли до квадрата. Що вийшло?

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 0           | 0            |
    | 1           | 1234567900987654321            |
    | 2           | 4938271603950617284            |
    | 7           | 60493827148395061729           |

    : **Приклад** {.striped .hover}

17. Довжина кільцевої дороги Кропивницького - `47` кілометрів. Велосипедист стартує з нульового кілометра і їде зі швидкістю `v` кілометрів на годину. На якій позначці він зупиниться через `t` годин? Якщо `v > 0`, то велосипедист рухається в позитивному напрямку, якщо ж значення `v < 0`, то в негативному.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 10, 3       | 30           |
    | 10, 4       | 40           |
    | -10, 2      | 27           |

    : **Приклад** {.striped .hover}

18. Електронний годинник показує час у форматі `h:mm:ss`, тобто спочатку записується кількість годин (число від 0 до 23), потім обов'язково двозначна кількість хвилин, потім обов'язково двозначна кількість секунд. Кількість хвилин і секунд за потреби доповнюються до двозначного числа нулями.

    Від початку доби минуло `N` секунд. Виведіть, що покаже годинник.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 3602        | 1:00:02      |
    | 129700      | 12:01:40     |

    : **Приклад** {.striped .hover}

19. Дано два моменти часу в межах однієї й тієї самої доби. Для кожного моменту вказано годину, хвилину і секунду.
Відомо, що другий момент часу настав не раніше першого.

    Визначте скільки секунд минуло між двома моментами часу.

    Програма на вхід отримує шість цілих чисел через переведення рядка. Перші три цілих числа відповідають годинам, хвилинам і секундам першого моменту, наступні три числа відповідають другому моменту.

    Години задаються числом від 0 до 23 включно. Хвилини і секунди - від 0 до 59.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 1, 1, 1, 2, 2, 2 | 3661    |

    : **Приклад** {.striped .hover}

20. За день машина проїжджає `N` кілометрів. Скільки днів потрібно, щоб проїхати маршрут завдовжки `M` кілометрів?

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 700, 750    | 2            |
    | 700, 2100   | 3            |
    | 100, 100    | 1            |

    : **Приклад** {.striped .hover}

21. Равлик повзе по вертикальній жердині заввишки `H` метрів, піднімаючись за день на `A` метрів, а за ніч спускаючись на `B` метрів.

    На який день равлик доповзе до вершини жердини? Гарантується, що `A > B`, `A < H`.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 10, 3, 2    | 8            |

    : **Приклад** {.striped .hover}

22. Напишіть програму для пошуку довжини гіпотенузи. Створіть змінні `a` та `b`, в яких будуть записані довжини катетів прямокутного трикутника. Після чого розрахуйте `c` і збережіть у ній довжину гіпотенузи цього трикутника.

::: {.callout-tip collapse="true"}
## Підказка

Для розрахунку довжини гіпотенузи використовуйте [теорему Піфагора](https://uk.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BE%D1%80%D0%B5%D0%BC%D0%B0_%D0%9F%D1%96%D1%84%D0%B0%D0%B3%D0%BE%D1%80%D0%B0).
:::

23. Задані дійсні числа `a`, `b` та `с` – сторони трикутника. Обчисліть периметр та площу трикутника. Результат збережіть у змінні `perimeter` та `area` відповідно.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 3, 4, 5     | perimeter = 12, area = 6        |

    : **Приклад** {.striped .hover}

::: {.callout-tip collapse="true"}
## Підказка

Периметр – це сума довжин усіх сторін. Площу трикутника по трьох сторонах можна обчислити за допомогою [формули Герона](https://ru.wikipedia.org/wiki/%D0%A4%D0%BE%D1%80%D0%BC%D1%83%D0%BB%D0%B0_%D0%93%D0%B5%D1%80%D0%BE%D0%BD%D0%B0). Квадратний корінь - це зведення у ступінь 0.5.

А ви знали, що Формула Герона міститься в «Метриці» Герона Олександрійського (I століття н. е.) і названа на його честь (хоча вона була відома ще Архімеду). Герон цікавився трикутниками з цілими сторонами, площі яких теж є цілими, такі трикутники звуться героновими, найпростішим героновим трикутником є єгипетський трикутник.
:::

24. У змінній `x` збережено ціле позитивне число. Обчисліть `x + x0x0x`. Результат збережіть змінну `result`.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 1           | 10102        |
    | 2           | 20204      |
    | 3           | 30306      |

    : **Приклад** {.striped .hover}

25. Збережіть у змінний `square` рядок, який виводить на екран **прямокутник 4 х 4**, сформований із зірочок, розділених пробілом.

```
print(square)

* * * *
* * * *
* * * *
* * * *
```

26. У змінну `a` збережено деяке речення, у якому можуть бути додані зайві пробіли. Напишіть програму, яка прибиратиме з `a` зайві пропуски і зберігатиме результат у змінну `result`. 
Усі слова мають бути розділені одним пропуском, а на початку та наприкінці речення пропусків бути не повинно.

**Приклад:**

```{.python}
a = "Я вивчаю нову мову програмування.   "
result = "Я вивчаю нову мову програмування."
```

27. Напишіть програму, ґрунтуючись на введенні та виведенні в прикладах. Введенням буде рядок `a`. Результат збережіть у `result`.

```{.python}
a = "div*2"
result = "<div></div><div></div>"

a = "p*1" 
result = "<p></p>"

a = "li*3"
result = "<li></li><li></li><li></li>"
```

28. Напишіть програму, яка прийматиме рядок зі слів і повертатиме рядок, у якому ці слова будуть відсортовані в [лексикографічному порядку](https://uk.wikipedia.org/wiki/%D0%9B%D0%B5%D0%BA%D1%81%D0%B8%D0%BA%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D1%96%D1%87%D0%BD%D0%B8%D0%B9_%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA). Початковий рядок міститься у змінній `x`, результат збережіть у `result`. 

**Приклад:**

```{{python}}
x = 'Світ надзвичайно широкий має укладисті далі'
result = 'Світ далі має надзвичайно широкий укладисті'
```

29. Напишіть програму, яка прийматиме номер кредитної картки `card` і повертатиме номер картки, у якому буде видно тільки останні 4 цифри. Інші цифри мають замінюватися зірочками. Результат збережіть у `result`.

**Приклад:**

```{.python}
card = '5468350018455833'
result = '************5833'
```
