---
title: Завдання №2
subtitle: "Прикладна аналітика"
format:
    html: default
    pdf:
        include-in-header: preamble.tex
---

# Задачі на цикли, списки, умовні оператори

1. Напишіть програму, яка приймає два цілих числа `A` і `B` і виводить найбільше значення з них. Числа - цілі від 1 до 1000.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 1, 2        | 2            |

    : **Приклад** {.striped .hover}

2. Напишіть програму, яка приймає два цілих числа `A` і `B`. Програма повинна вивести `"1"`, якщо перше число більше другого, `"2"`, якщо друге більше за перше або `"0"`, якщо вони рівні.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 1, 2        | 2            |

    : **Приклад** {.striped .hover}

3. Дано три цілих числа. Знайдіть найбільше з них (програма повинна вивести рівно одне ціле число).

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 1, 2, 3     | 3            |

    : **Приклад** {.striped .hover}

4. Програма приймає число - рік. Потрібно визначити, чи є рік високосним. Якщо рік є високосним, то виведіть `YES`, інакше виведіть `NO`. Нагадаємо, що відповідно до григоріанського календаря, рік є високосним,
якщо його номер кратний 4, але не кратний 100, або ж якщо він кратний 400.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 4           |  YES         |

    : **Приклад** {.striped .hover}

5. Шаховий король ходить по горизонталі, вертикалі та діагоналі, але тільки на 1 клітинку. Дано дві різні клітинки шахової дошки, визначте, чи може король потрапити з першої клітинки на другу одним ходом.

    Пояснення: програма отримує на вхід чотири числа від 1 до 8 кожне, що задають номер стовпчика і номер рядка спочатку для першої клітинки, потім для другої клітинки. Програма повинна вивести `YES`, якщо з першої клітинки ходом короля можна потрапити в другу або `NO` в іншому випадку.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 4, 4, 5, 5  | YES          |

    : **Приклад** {.striped .hover}

6. Вкажіть усі порівняння, внаслідок яких ми отримаємо `True`.

- `'ІВАН' < 'іван'`
- `'Python' < 'R'`
- `'big number' != 'bug number'`
- `'ЯЯЯ' == 'Я Я'`
- `'гірка' >= 'зірка'`

7. У змінній `m` зберігається ціле позитивне число – тривалість сну в хвилинах. Якщо тривалість сну становитиме **від 7 до 9 години включно**, то в змінну `optimal_sleep_duration` збережіть значення `True`. В протилежному випадку - `False`.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 410         |  False       |
    | 500         |  True        |

    : **Приклад** {.striped .hover}

8. У змінній `x` зберігається ціле число. Перевірте, чи це число **ділиться без залишку** на `3` і на `7`. Результат збережіть в змінну `result`. Змінна результат повинен мати **логічний тип даних**.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 7           |  False       |
    | 21          |  True        |

    : **Приклад** {.striped .hover}

9. У змінних `str_1` і `str_2` збережено два рядки. Якщо рядки містять однакові літери, вам потрібно зберегти у змінну `is_the_same_letters` значення `True`, якщо літери в рядках відрізняються - збережіть у змінну значення `False`.

Ми не враховуємо порядок букв, їхню кількість і регістр.

::: {.callout-tip collapse="true"}
## Підказка

Подивіться інформацію про [множини](https://www.w3schools.com/python/python_sets.asp) (`set`) в Python.
:::

| Вхідні дані | Вихідні дані |
|-------------|--------------|
| 'AaB', 'Ab' |  True        |
| 'Aa', 'AaB' |  False       |

: **Приклад** {.striped .hover}

10. Дано два рядки `str_1` і `str_2`. Збережіть у `result` `True`, якщо `str_1` є **анаграмою** `str_2`, і `False` в іншому випадку. Регістр літер (велика чи маленька буква) не повинен впливати на роботу програми. Тобто 'Літо' і ‘Тіло’ - це валідна анаграма.

    *Анаграма* - це слово або фраза, утворена шляхом перестановки літер іншого слова або фрази, зазвичай з використанням усіх вихідних літер рівно один раз.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | "Літо", "Тіло" |  True     |
    | "Провал", "Привіт" |  False       |

    : **Приклад** {.striped .hover}

11. У змінних `a` та `b` задано значення довжини та ширини прямокутника відповідно. Перевірте, чи є цей прямокутник квадратом.

    Збережіть у змінну `result` значення `True`, якщо це квадрат, інакше `False`.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 121, 100    |  False       |
    | 10, 10      |  True       |

    : **Приклад** {.striped .hover}

12. У змінних `a` і `b` задано два числа. Квадрат якого числа більший? Збережіть це число в `result`.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 1, 2        |  2           |
    | 2, -3       |  -3          |

    : **Приклад** {.striped .hover}

13. Катя і Діма вирішили купити квартиру в Києві. Сімейний бюджет обмежений, тому їм підходять такі варіанти:

    1. Вартість не більше 1.5 млн, площа не менше 50 квадратних метрів, віддаленість від метро не більше 25 хвилин пішки.
    2. Вартість не більше 1.3 млн, площа не менше 35 квадратних метрів, віддаленість від метро не більше 5 хвилин пішки.

    Напишіть програму, яка отримує на вхід вартість квартири p, площу s і віддаленість від метро d, і зберігає у змінну result повідомлення про те, підходить квартира чи ні у форматі `True` або `False`.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 1295000, 32, 13 |  False        |
    | 1498000, 51.9, 23 |  True       |

14. Катя завершила навчання на курсі Machine Learning і набрала `K` балів за розв'язання задач. Щоб отримати сертифікат про проходження курсу, необхідно набрати щонайменше `M` балів. Якщо Катя набрала від `L` балів, то отримає сертифікат з відзнакою. 

    Напишіть програму, яка збереже у змінну `result` інформацію про результати проходження курсу в такому форматі:

    - `"Недостатньо балів"`, якщо Каті не вистачило балів для отримання сертифіката,
    - `"Сертифікат видано"`, якщо Катя набрала кількість балів, необхідну для отримання сертифіката,
    - `"Видано сертифікат з відзнакою"`, якщо Катя набрала `≥ L` балів.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 121, 100, 150 |  "Сертифікат видано"  |
    | 148, 110, 145 |  "Видано сертифікат з відзнакою" |

15. Компанія вирішила виплатити співробітникам премію в розмірі:

    - 2 оклади, якщо його стаж роботи ≥ 2 роки
    - 5 окладів, якщо стаж роботи ≥ 5 років
    - 10 окладів, якщо стаж роботи ≥ 15 років

    У змінній `x` - зарплата співробітника, у змінній `y` - стаж. Обчисліть розмір премії, результат збережіть у змінну `result`. 

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 150000, 3   |  300000      |
    | 100000, 1   |  0           |
    | 200000, 16  |  2000000     |

16. Дано словник `dict_age`, у якому зберігається інформація про вік трьох братів у форматі:

    - ключ - це ім'я
    - значення - це вік, число цілих років.

    Якщо вік у братів різний і виходить однозначно визначити середнього брата, збережіть ім'я середнього брата у змінну `result`.

    Якщо хоча б у двох братів вік однаковий, то збережіть у змінну `result` порожній рядок.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | {'Марк': 5, 'Авель': 5, 'Карп': 9} |  "" |
    | {'Антон': 5, 'Денис': 14, 'Борис': 9}|  "Борис" |

17. Напишіть програму, яка прийматиме довжини сторін трикутника `a`, `b` і `c`, визначатиме, чи є він прямокутним, і зберігатиме результат перевірки в `result` у форматі `True` або `False`. 

    - Прямокутний трикутник - це трикутник, у якому один кут прямий (тобто 90 градусів).
    - Найдовша сторона (гіпотенуза) не обов'язково буде останнім аргументом.
    - Усі аргументи будуть цілими числами.

    | Вхідні дані | Вихідні дані |
    |-------------|--------------|
    | 70, 130, 110     |  False        |
    | 3, 5, 4     |  True        |


18. Напишіть програму, яка буде вираховувати або довжину кола, або периметр квадрата, виходячи з переданих аргументів.

    На вхід подаються буква у змінній `f` і число у змінній `v`.

    Буква визначатиме геометричну фігуру:

    `'S'` - квадрат
    `'С'` - коло

    Якщо буквою задано квадрат, то другий аргумент, число `v`, вважається довжиною сторони квадрата. В іншому випадку число вважається радіусом кола.

    Результат збережіть у `result`

    Число `pi` візьміть рівним `3.14`.
