---
title: "Project 2"
subtitle: "Probability and Statistics"
author: "Ihor Miroshnychenko"
institute: Kyiv School of Economics
format:
  html: 
    highlight-style: github
    theme: [default, custom.scss]
    toc: true
    toc-depth: 2
execute: 
  echo: true
  warning: false
editor_options: 
  chunk_output_type: console
---

::: {.callout-important}
The project is a joint with the course "Descriptive Statistics and Data Visualization".
:::

# Description

**TL;DR**: Ask a question you’re curious about and answer it with a dataset of your choice. This is your project in a nutshell.

**May be too long, but please do read**

The final project for this class will consist of analysis on a dataset of your own choosing. The dataset may already exist, or you may collect your own data using a survey or by conducting an experiment. You can choose the data based on your teams’ interests or based on work in other courses or research projects. The goal of this project is for you to demonstrate proficiency in the techniques we have covered in this class (and beyond, if you like) and apply them to a novel dataset in a meaningful way.

The goal is not to do an exhaustive data analysis i.e., do not calculate every statistic and procedure you have learned for every variable, but rather let me know that you are proficient at asking meaningful questions and answering them with results of data analysis, that you are proficient in using R, and that you are proficient at interpreting and presenting the results. Focus on methods that help you begin to answer your research questions. You do not have to apply every statistical procedure we learned. Also, critique your own methods and provide suggestions for improving your analysis. Issues pertaining to the reliability and validity of your data, and appropriateness of the statistical analysis should be discussed here.

The project is very open ended. You should:

- ask a question that you are curious about
- perform statistical inference and/or fit a model or descriptive or predictive purposes

There is no limit on what tools or packages you may use. You do not need to visualize all of the data at once. A single high-quality visualization will receive a much higher grade than a large number of poor-quality visualizations. Also pay attention to your presentation. Neatness, coherency, and clarity will count.

# Proposal conversation

There are two main purposes of the project proposal conversation:

- To help you think about the project thoroughly before you go too far down a path and form an analysis plan that is feasible and that will allow you to be successful for this project.
- To ensure all members of the team are on the same page about the status of the project and the remaining work to be done and how it will be distributed among yourselves.

To prepare for this conversation: identify a data set and a research question for the final project. This can be one of the datasets you used in your first project, but if you find it difficult to ask him statistical questions, it is better to think about an alternative.

# Criteria for datasets

The data sets should meet the following criteria:

- At least 100 observations
- At least 5 columns
- At least 4 of the columns must be useful and unique explanatory variables.
  + Identifier variables such as “name”, “social security number”, etc. are not useful explanatory variables.
  + If you have multiple columns with the same information (e.g. “state abbreviation” and “state name”), then they are not unique explanatory variables.
- You may not use data that has previously been used in any course materials, or any derivation of data that has been used in course materials.

::: callout-tip
Please ask me if you’re unsure whether your data set meets the criteria.
:::

If you set your hearts on a dataset that has fewer observations or variables than what’s suggested here, that might still be ok; use these numbers as guidance for a successful proposal, not as minimum requirements.

## Components

You should include, at a minimum, the following sections in your report.

### Introduction

The introduction provides motivation and context for your research.

To begin, introduce the data set in a few short sentences. Next, create a code book (aka a “data dictionary”) of the variables in the data set. Although a code book is provided above, you should include one in your report as well so that your report is self-contained. Specifically, only include in your report a code book of the variables that you use.

Complete the introduction by providing a concise, clear statement of your research question and hypotheses. Be sure to motivate why the research question is interesting/useful.

Example research question and hypotheses (if we were predicting penguin weights instead of baby weights):

> Can we predict body mass with bill depth? We hypothesize that penguins with deeper bills will also have more mass.

### Methodology

Here you should introduce any statistical methods you use and describe why you choose the methods you do to answer your question. You might also include any preliminary summary statistics or figures you use to explore the data.

### Results 

Place figure(s) here to illustrate the main results from your analysis. 1 beautiful figure is worth more than several poorly formatted figures. You must have at least 1 figure.

Provide only the main results from your analysis. The goal is not to do an exhaustive data analysis (calculate every possible statistic and create every possible model for all variables). Rather, you should demonstrate that you are proficient at asking meaningful questions and answering them using data, that you are skilled in writing about and interpreting results, and that you can accomplish these tasks using R. More is not better.

### Discussion 

This section is a conclusion and discussion. You should:

- Summarize your main finding in a sentence or two.
- Discuss your finding and why it is useful (put in the context of your motivation from the introduction).
- Critique your own analyses and include a brief paragraph on what you would do differently if you were able to start the project over.

### Appendix 

List a brief (1 or 2 sentence) summary of the relative contributions of each team member, e.g., “Aang built the models, Katara implemented them in R, and Sokka wrote the introduction and discussion.”

::: callout-important
All team members should be comfortable describing all aspects of the project and understanding all code.
:::

### Formatting 

Your project should be professionally formatted. For example, this means labeling graphs and figures, turning off code chunks, using proper citations and cross-references, and following typical style guidelines.

## Submission

Every team member must submit the same report into Moodle.

# Presentation 

Your presentation must be no longer than 10 minutes. Final presentations will be held at the last week of the course. You will present your project to the class and answer questions from your peers and the instructors.

## Slides

For your presentation, you must create presentation slides that summarize and showcase your project. Introduce your research question and data set, showcase visualizations, and provide some conclusions. These slides should serve as a brief visual accompaniment to your write-up and will be graded for content and quality.

Here is a suggested outline as you think through the slides; you do not have to use this exact format for the slide deck.

- Title Slide
- Slide 1: Introduce the topic and motivation
- Slide 2: Introduce the data
- Slide 3 - 4: Highlights from exploratory data analysis
- Slide 4 - 5: Highlights from inference and/or modeling
- Slide 6: Conclusions + critique/shortcomings

We recommend choosing an option that’s easy to collaborate with, e.g., Google Slides.

# Grading

1. **Preparation**: Accuracy in data preparation and preprocessing for analysis, considering the specifics of the data set.
2. **Visualization of Results**: Quality of visualizations, readability of graphs, and correctness in representing the data.
3. **Interpretation of Results**: Correct interpretation of the results, including the ability to explain the data set and the results obtained.
4. **Report Quality**: Clarity and structure of the report, well-formulated conclusions, references to sources, and adherence to ethical guidelines.
5. **Team Participation**: Active participation in the project, including the ability to explain the data set and the results obtained.

**Total points:** 25

