---
title: "Exercises 1 solutions"
subtitle: "Probability and Statistics"
affiliation: "Kyiv School of Economics"
format: 
  docx: default
toc: true
number-sections: false
echo: false
---

# Single mean

1.  **Статистика проти параметрів: одне середнє значення.** Кожен з наступних сценаріїв був створений для оцінки середнього значення.
    Для кожного з них визначте словами: статистику та параметр.

    a.  Вибірку з 25 мешканців Нью-Йорка запитали, скільки вони сплять за ніч.

    b.  Дослідники з двох різних університетів Каліфорнії зібрали інформацію про зріст студентів старших курсів.

3.  **Дослідники, які вивчають антропометрію, зібрали дані про розміри тіла, а також вік, вагу, зріст і стать 507 фізично активних дорослих людей.
    Зведені статистичні дані щодо розподілу зросту (виміряного в сантиметрах, см), а також гістограма наведені нижче.

        a.  Якими є точкові оцінки середнього та медіанного зросту активних дорослих?

    b.  Які точкові оцінки для стандартного відхилення та IQR зросту дорослого дорослого населення?

    c.  Чи вважається людина зі зростом 1 м 80 см (180 см) незвично високою?
        І чи вважається людина зі зростом 1 м 55 см (155 см) незвично низькою?
        Поясніть свої міркування.

    d.  Дослідники взяли ще одну випадкову вибірку фізично активних дорослих.
        Чи можна очікувати, що середнє значення і стандартне відхилення цієї нової вибірки будуть такими ж, як наведені вище?
        Поясніть свої міркування.

    e.  Отримані вибіркові середні є точковими оцінками для середнього зросту всіх активних осіб, якщо вибірка осіб еквівалентна простій випадковій вибірці.
        Яку міру ми використовуємо для кількісної оцінки мінливості такої оцінки?
        Обчисліть цю величину, використовуючи дані вихідної вибірки за умови, що ці дані є простою випадковою вибіркою.

5.  **Зріст дорослих порівняно з вихованцями дитячих садків.** Зріст 507 фізично активних дорослих у середньому становить 171 см, а стандартне відхилення - 9,4 см.

    a.  Як ви гадаєте, чи буде стандартне відхилення зросту кількох сотень вихованців дитячих садків вищим або нижчим за 9,4 см?
        Поясніть свої міркування.

    b.  Припустимо, що взято багато вибірок розміром 100 дорослих і, окремо, багато вибірок розміром 100 вихованців дитячих садків.
        Для кожної з багатьох вибірок обчислюється середній зріст.
        Який набір вибіркових середніх матиме більшу стандартну похибку середнього: середні вибірки дорослих чи середні вибірки дітей дошкільного віку?

7.  **Визначте критичне значення $t$.
    Випадкова вибірка відібрана з приблизно нормальної генеральної сукупності з невідомим стандартним відхиленням.
    Знайдіть ступені свободи та критичне $t$-значення (t$^\star$) для заданого обсягу вибірки та довірчої ймовірності.

    a.  $n = 6$, CL = 90%.

    b.  $n = 21$, CL = 98%
    
    c.  $n = 29$, CL = 95%

    d.  $n = 12$, CL = 99%.

9.  **Знайти p-значення, I.** Випадкова вибірка відібрана з приблизно нормальної генеральної сукупності з невідомим середнім квадратичним відхиленням.
    Знайдіть p-значення для заданого обсягу вибірки та статистики тестування.
    Також визначте, чи буде відхилена нульова гіпотеза при $\alpha = 0,05$.

    :::: {layout=«[-0.05, 0.425, 0.425]»}
    :::{#ab}
    a.  $n = 11$, $T = 1.91$

    b.  $n = 17$, $T = -3.45$
    :::
    :::{#cd}
    c.  $n = 7$, $T = 0.83$

    d.  $n = 28$, $T = 2.13$
    :::
    ::::

17. **Звички сну нью-йоркців.** Нью-Йорк відомий як «місто, яке ніколи не спить».
    У випадковій вибірці з 25 нью-йоркців запитали, скільки вони сплять за ніч.
    Статистичні зведення цих даних наведені нижче.
    Бальна оцінка свідчить про те, що нью-йоркці сплять в середньому менше 8 годин на добу.
    Оцініть твердження, що Нью-Йорк - місто, яке ніколи не спить, маючи на увазі, що, незважаючи на це твердження, реальна середня кількість годин, яку сплять жителі Нью-Йорка, може бути меншою за 8 годин або більшою за 8 годин.

    a.  Запишіть гіпотези символами та словами.

    b.  Перевірте умови, а потім обчисліть тестову статистику, $T$, і пов'язані з нею ступені свободи.

    c.  Знайдіть та інтерпретуйте p-значення в цьому контексті.
        Може бути корисним намалювати малюнок.

    d.  Який висновок випливає з перевірки гіпотези?

    e.  Якби ви побудували 90% довірчий інтервал, який відповідав би цій перевірці гіпотези, чи очікували б ви, що 8 годин потраплять в цей інтервал?

19. **$t^\star$ для правильного довірчого інтервалу.** Як ви бачили, хвости $t-$-розподілу довші за стандартний нормальний, що призводить до того, що $t^{\star}_{df}$ буде більшим за $z^{\star}$ для будь-якого заданого довірчого інтервалу.
    При знаходженні ДІ для генеральної сукупності пояснити, як помилкове використання $z^{\star}$ (замість правильного $t^{*}_{df}$) вплине на довірчий рівень.

21. **Георгіана стверджує, що у невеликому місті, яке славиться своєю музичною школою, середньостатистична дитина бере уроки гри на фортепіано менше 5 років.
    У нас є випадкова вибірка з 20 дітей з міста, середній стаж занять на фортепіано становить 4,6 років, а стандартне відхилення - 2,2 роки.

    a.  Оцініть правильність твердження Георгіани (або те, що протилежне може бути правдою) за допомогою перевірки гіпотез.

    b.  Побудуйте 95% довірчий інтервал для кількості років, протягом яких учні в цьому місті беруть уроки гри на фортепіано, та інтерпретуйте його в контексті даних.

    c.  Чи узгоджуються ваші результати перевірки гіпотези та довірчий інтервал?
        Поясніть свої міркування.

# Two independent means


1.  **Пекар-експериментатор, який працює над вдосконаленням рецепту рогаликів, експериментує з активними сухими (AD) та швидкорозчинними (I) дріжджами.
    Він випікає дюжину рогаликів з кожним типом дріжджів і оцінює кожен рогалик за шкалою від 1 до 10 за тим, наскільки добре він піднімається.
    Вони висувають наступний набір гіпотез для оцінки того, чи є різниця в середньому підйомі рогаликів, випечених на активних сухих і швидкорозчинних дріжджах.
    Що не так з наведеними гіпотезами?

    $$H_0: \bar{x}_{AD} \leq \bar{x}_{I} \quad \quad H_A: \bar{x}_{AD} > \bar{x}_{I}$$

3.  **Діаманти, тест на рандомізацію.** Ціни на діаманти зростають зі збільшенням ваги в каратах, але це зростання не є плавним.
    Наприклад, різницю між розміром діаманта вагою 0,99 карата і 1 карат неможливо помітити неозброєним оком, але ціна діаманта вагою 1 карат, як правило, набагато вища, ніж ціна діаманта вагою 0,99 карата.
    У нас є дві випадкові вибірки діамантів: 23 діаманти вагою 0,99 карата і 23 діаманти вагою 1 карат. 
    Для того, щоб мати можливість порівнювати еквівалентні одиниці, ми спочатку ділимо ціну кожного діаманта на 100-кратну його вагу в каратах.
    Тобто, для діаманта вагою 0,99 карата ми ділимо ціну на 99, а для діаманта вагою 1 карат - на 100.
    Потім ми рандомізуємо вагу в каратах до значень ціни, щоб змоделювати нульовий розподіл різниці в середніх цінах на діаманти вагою 0,99 карата і 1 карат.
    Нульовий розподіл (з 1 000 рандомізованих відмінностей) показаний нижче і відображає розподіл відмінностей у вибіркових середніх (ціни за карат), якби дійсно не було відмінностей у сукупності, з якої походять ці діаманти.

    Використовуючи рандомізований розподіл, проведіть перевірку гіпотези, щоб оцінити, чи є різниця між цінами за карат діамантів вагою 0,99 карата і 1 карат.
    Переконайтеся, що ви чітко сформулювали свої гіпотези та інтерпретували результати в контексті даних.

7.  **Втрата ваги.** Ви читаєте статтю, в якій дослідники створили 95% довірчий інтервал для різниці в середній втраті ваги для двох дієт.
    Вони на 95% впевнені, що справжня різниця в середній втраті ваги за 6 місяців для двох дієт знаходиться десь між (1 фунт, 25 фунтів).
    Автори стверджують, що «таким чином, дієта А ($\bar{x}_A$ = 20 фунтів середньої втрати) призводить до набагато більшої середньої втрати ваги в порівнянні з дієтою Б ($\bar{x}_B$ = 7 фунтів середньої втрати)». Прокоментуйте твердження авторів.

9.  **Діаманти, математичний тест.** У нас є дані про дві випадкові вибірки діамантів: одна з діамантами вагою 0,99 карата, інша з діамантами вагою 1 карат.
    У кожній вибірці по 23 діаманти.
    Нижче наведено вибіркові статистичні дані про ціну за карат діамантів у кожній вибірці.
    Проведіть перевірку гіпотези за допомогою математичної моделі, щоб оцінити, чи існує різниця між цінами за карат діамантів вагою 0,99 карата і 1 карат. Обов'язково чітко сформулюйте свої гіпотези, перевірте відповідні умови та інтерпретуйте свої результати в контексті отриманих даних.

11. **Діаманти, математичний інтервал.** Ми маємо дані про дві випадкові вибірки діамантів: одна з них містить діаманти вагою 0,99 карата, а інша - 1 карат.
    У кожній вибірці по 23 діаманти.
    Нижче наведено вибіркову статистику ціни за карат діамантів у кожній вибірці.
    Припускаючи, що умови для проведення висновку за допомогою математичної моделі виконуються, побудуйте 95% довірчий інтервал для істинної генеральної різниці в цінах за карат діамантів вагою 0,99 карата і 1 карат.

13. **Різниця середніх значень.** Ми зібрали дві випадкові вибірки з двох різних популяцій
    У кожній частині нижче ми розглянемо вибіркові середні $\bar{x}_1$ та $\bar{x}_2$, які ми можемо спостерігати за цими двома вибірками.

    a.  Чому дорівнює середнє арифметичне та середньоквадратичне відхилення $\bar{x}_1$?

    b.  Чому дорівнює асоційоване середнє та стандартне відхилення $\bar{x}_2$?

    c.  Обчисліть та інтерпретуйте середнє та стандартне відхилення, пов'язані з різницею вибіркових середніх для двох груп $\bar{x}_2 - \bar{x}_1$.

    d.  Як пов'язані між собою стандартні відхилення з частин (a), (b) і (c)?

15. **Курячий раціон: боби проти льону.** Курівництво - це багатомільярдна індустрія, і будь-які методи, що збільшують швидкість росту молодих курчат, можуть зменшити витрати споживачів, одночасно збільшуючи прибутки компанії, можливо, на мільйони доларів.
    Було проведено експеримент для вимірювання та порівняння ефективності різних кормових добавок на швидкість росту курчат.
    Щойно вилуплені курчата були випадковим чином розподілені на шість груп, і кожній групі давали різні кормові добавки.
    У цій вправі ми розглядаємо курчат, яких годували кінськими бобами та лляним насінням.
    Нижче наведено деякі зведені статистичні дані з цього набору даних, а також секторні діаграми, що показують розподіл ваги за типом корму.

    a.  Опишіть розподіл ваги курей, яким згодовували кінські боби та лляне насіння.

    b.  Чи дають ці дані переконливі докази того, що середня вага курчат, яких годували льоном і кінськими бобами, відрізняється?
        Використовуйте 5% рівень розрізнення.

    c.  Якого типу помилки ми могли припуститися?
        Поясніть.

    d.  Чи змінився б ваш висновок, якби ми використали $\alpha = 0.01$?

17. **Куряча дієта: казеїн проти сої.** Казеїн є поширеною добавкою для збільшення ваги для людей.
    Чи має він вплив на курей?
    Був проведений експеримент для вимірювання та порівняння ефективності різних кормових добавок на швидкість росту курчат.
    Щойно вилуплені курчата були випадковим чином розподілені на шість груп, і кожній групі давали різні кормові добавки.
    У цій вправі ми розглядаємо курчат, яких годували казеїном і соєю.
    Припустимо, що умови для проведення висновку з використанням математичних моделей виконані, і, використовуючи наведені нижче дані, перевірте гіпотезу про те, що середня вага курчат, яких годували казеїном, відрізняється від середньої ваги курчат, яких годували соєвими бобами.
    Якщо перевірка гіпотези дасть статистично достовірний результат, обговоріть, чи можна пояснити більшу середню вагу курей раціоном з казеїном.

19. **Група дослідників, які цікавляться можливими ефектами відволікаючих стимулів під час прийому їжі, такими як збільшення або зменшення кількості споживаної їжі, спостерігала за споживанням їжі групою з 44 пацієнтів, яких було рандомізовано на дві рівні групи.
    Основна група обідала під час гри в пасьянс, а контрольна група обідала без будь-яких додаткових відволікаючих чинників.
    Пацієнти основної групи з'їли 52,1 грама печива зі стандартним відхиленням 45,1 грама, а пацієнти контрольної групи - 27,1 грама печива зі стандартним відхиленням 26,4 грама.
    Чи є ці дані переконливим доказом того, що середній рівень споживання їжі (виміряний у кількості з'їденого печива) відрізняється у пацієнтів основної групи порівняно з контрольною групою?
    Припустимо, що умови для проведення висновку з використанням математичних моделей виконані.

