<!DOCTYPE html>
<html lang="uk"><head>
<script src=".midterm-mock-slides_files/libs/clipboard/clipboard.min.js"></script>
<script src=".midterm-mock-slides_files/libs/quarto-html/tabby.min.js"></script>
<script src=".midterm-mock-slides_files/libs/quarto-html/popper.min.js"></script>
<script src=".midterm-mock-slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href=".midterm-mock-slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href=".midterm-mock-slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href=".midterm-mock-slides_files/libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Ihor Miroshnychenko">
  <meta name="dcterms.date" content="2026-05-29">
  <title>Mock Midterm — розбір</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href=".midterm-mock-slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href=".midterm-mock-slides_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href=".midterm-mock-slides_files/libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link href=".midterm-mock-slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href=".midterm-mock-slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href=".midterm-mock-slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href=".midterm-mock-slides_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href=".midterm-mock-slides_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href=".midterm-mock-slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Mock Midterm — розбір</h1>
  <p class="subtitle">STAT250: Теорія ймовірностей та статистика</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Ihor Miroshnychenko 
</div>
        <p class="quarto-title-affiliation">
            Kyiv School of Economics
          </p>
    </div>
</div>

  <p class="date">2026-05-29</p>
</section><section id="TOC">
<nav role="doc-toc"> 
<h2 id="toc-title">Table of contents</h2>
<ul>
<li><a href="#/як-побудовано-розбір" id="/toc-як-побудовано-розбір">Як побудовано розбір</a></li>
<li><a href="#/section-a.-multiple-choice" id="/toc-section-a.-multiple-choice">Section A. Multiple Choice</a></li>
<li><a href="#/section-b.-true-false" id="/toc-section-b.-true-false">Section B. True / False</a></li>
<li><a href="#/section-c.-validity-check" id="/toc-section-c.-validity-check">Section C. Validity Check</a></li>
<li><a href="#/section-d.-r-output-interpretation" id="/toc-section-d.-r-output-interpretation">Section D. R Output Interpretation</a></li>
<li><a href="#/problem-1-spam-filter" id="/toc-problem-1-spam-filter">Problem 1 — Spam Filter</a></li>
<li><a href="#/problem-2-dogecat" id="/toc-problem-2-dogecat">Problem 2 — DOGECAT</a></li>
<li><a href="#/problem-3-sleepy-barista" id="/toc-problem-3-sleepy-barista">Problem 3 — Sleepy Barista</a></li>
<li><a href="#/problem-4-normal-streams" id="/toc-problem-4-normal-streams">Problem 4 — Normal: Streams</a></li>
<li><a href="#/problem-5-exponential-delivery" id="/toc-problem-5-exponential-delivery">Problem 5 — Exponential: Delivery</a></li>
<li><a href="#/problem-6-markov-inequality" id="/toc-problem-6-markov-inequality">Problem 6 — Markov Inequality</a></li>
<li><a href="#/problem-7-clt-sleep-hours" id="/toc-problem-7-clt-sleep-hours">Problem 7 — CLT: Sleep Hours</a></li>
<li><a href="#/problem-8-joint-xy-study-vs-game" id="/toc-problem-8-joint-xy-study-vs-game">Problem 8 — Joint XY: Study vs Game</a></li>
<li><a href="#/problem-9-sample-covariance-correlation" id="/toc-problem-9-sample-covariance-correlation">Problem 9 — Sample Covariance &amp; Correlation</a></li>
<li><a href="#/problem-10-casino-coin-flips" id="/toc-problem-10-casino-coin-flips">Problem 10 — Casino Coin Flips</a></li>
<li><a href="#/підсумок" id="/toc-підсумок">Підсумок</a></li>
</ul>
</nav>
</section>
<section id="як-побудовано-розбір" class="title-slide slide level1 unnumbered center">
<h1>Як побудовано розбір</h1>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Структура слайдів</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><strong>🧩 Завдання</strong> — формулювання, як у білеті.</li>
<li><strong>✅ Розв’язання</strong> — крок за кроком: логіка та обчислення.</li>
<li><strong>📊 R / tidyverse</strong> — перевірка чи візуалізація там, де додає інтуїцію.</li>
</ol>
</div>
</div>
</div>
<ul>
<li><strong>Частина I (40 б.):</strong> A — MCQ (10), B — True/False (8), C — Validity (6+2 бонус), D — R-output (16).</li>
<li><strong>Частина II (60 б.):</strong> 10 прикладних задач × 6 балів.</li>
</ul>
</section>

<section>
<section id="section-a.-multiple-choice" class="title-slide slide level1 center">
<h1>Section A. Multiple Choice</h1>

</section>
<section id="a1-характеризація-pmf" class="slide level2">
<h2>🧩 A1 — характеризація PMF</h2>
<blockquote>
<p>Яка з відповідей правильно характеризує <strong>функцію ймовірностей</strong> (PMF)?</p>
<p><strong>(A)</strong> <span class="math inline">\(\int_{-\infty}^{\infty} p(x)\,dx = 1\)</span> і <span class="math inline">\(p(x) \ge 0\)</span>.</p>
<p><strong>(B)</strong> <span class="math inline">\(p(x) \ge 0\)</span> для всіх <span class="math inline">\(x\)</span> і <span class="math inline">\(\sum_{\text{all } x} p(x) = 1\)</span>.</p>
<p><strong>(C)</strong> <span class="math inline">\(p(x)\)</span> — неперервна функція <span class="math inline">\(x\)</span>.</p>
<p><strong>(D)</strong> <span class="math inline">\(p(x)\)</span> може перевищувати 1 для окремих <span class="math inline">\(x\)</span>.</p>
</blockquote>
</section>
<section id="a1-розвязання" class="slide level2">
<h2>✅ A1 — розв’язання</h2>
<p>PMF описує <strong>дискретну</strong> величину: умови нормування та невід’ємності формулюються через <strong>суму</strong>.</p>
<ul>
<li><ol type="A">
<li>— формула PDF (інтеграл).</li>
</ol></li>
<li><ol start="3" type="A">
<li>— PMF взагалі визначена лише на зліченній множині точок.</li>
</ol></li>
<li><ol start="4" type="A">
<li>— для PMF <span class="math inline">\(p(x) = P(X = x) \le 1\)</span> завжди.</li>
</ol></li>
</ul>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Відповідь: (B).</strong></p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Ключове протиставлення PMF vs PDF: сума проти інтеграла. Підкреслити: «ймовірність у точці» має сенс лише для дискретних. Типова помилка — обрати (A) через звичку до інтегралів.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a2-operatornamevar2x-5" class="slide level2">
<h2>🧩 A2 — <span class="math inline">\(\operatorname{Var}(2X + 5)\)</span></h2>
<blockquote>
<p><span class="math inline">\(E[X] = 3, \operatorname{Var}(X) = 4\)</span>. Знайти <span class="math inline">\(\operatorname{Var}(2X + 5)\)</span>.</p>
<p><strong>(A)</strong> 8 &nbsp;&nbsp; <strong>(B)</strong> 13 &nbsp;&nbsp; <strong>(C)</strong> 16 &nbsp;&nbsp; <strong>(D)</strong> 21</p>
</blockquote>
</section>
<section id="a2-розвязання" class="slide level2">
<h2>✅ A2 — розв’язання</h2>
<p>Властивість дисперсії: <span class="math inline">\(\operatorname{Var}(aX + b) = a^2 \operatorname{Var}(X)\)</span>.</p>
<p><span class="math display">\[
\operatorname{Var}(2X + 5) = 2^2 \cdot 4 = 16.
\]</span></p>
<p>Зсув <span class="math inline">\(+5\)</span> <strong>не впливає</strong> на розкид; масштаб <span class="math inline">\(\times 2\)</span> збільшує дисперсію у <strong>4 рази</strong>.</p>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Відповідь: (C) 16.</strong></p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Дві типові помилки: (1) помножити дисперсію на 2, забувши квадрат; (2) додати щось через +5. Нагадати інтуїцію: константа зсуває весь розподіл, не міняючи форму. Можна намалювати на дошці.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a3-стандартний-нормальний-яке-твердження-хибне" class="slide level2">
<h2>🧩 A3 — стандартний нормальний: яке твердження ХИБНЕ?</h2>
<blockquote>
<p><span class="math inline">\(Z \sim \mathcal{N}(0, 1)\)</span>. Яке з тверджень <strong>FALSE</strong>?</p>
<p><strong>(A)</strong> <span class="math inline">\(P(Z &gt; 0) = 0.5\)</span> &nbsp;&nbsp; <strong>(B)</strong> <span class="math inline">\(P(Z = 0) = 0.5\)</span></p>
<p><strong>(C)</strong> <span class="math inline">\(E[Z] = 0, \operatorname{Var}(Z) = 1\)</span> &nbsp;&nbsp; <strong>(D)</strong> Розподіл симетричний навколо 0</p>
</blockquote>
</section>
<section id="a3-розвязання" class="slide level2">
<h2>✅ A3 — розв’язання</h2>
<p>Для <strong>неперервної</strong> випадкової величини <span class="math inline">\(P(Z = c) = 0\)</span> для будь-якого фіксованого <span class="math inline">\(c\)</span>.</p>
<p>Отже <span class="math inline">\(P(Z = 0) = 0\)</span>, а не <span class="math inline">\(0.5\)</span>.</p>
<ul>
<li><ol type="A">
<li>✓ за симетрією.</li>
</ol></li>
<li><ol start="3" type="A">
<li>✓ — означення <span class="math inline">\(\mathcal{N}(0, 1)\)</span>.</li>
</ol></li>
<li><ol start="4" type="A">
<li>✓ — щільність <span class="math inline">\(\varphi(z) = \varphi(-z)\)</span>.</li>
</ol></li>
</ul>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Відповідь: (B).</strong></p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Принциповий момент: для <strong>неперервної</strong> величини маса однієї точки = 0. Часто плутають із дискретним випадком, де <span class="math inline">\(P(X = c)\)</span> — повноцінна ймовірність. Зв’язати з B3 — однакова ідея.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a4-нерівність-маркова" class="slide level2">
<h2>🧩 A4 — нерівність Маркова</h2>
<blockquote>
<p>Для <strong>невід’ємної</strong> <span class="math inline">\(X\)</span> з <span class="math inline">\(E[X] = \mu\)</span> і <span class="math inline">\(a &gt; 0\)</span>:</p>
<p><strong>(A)</strong> <span class="math inline">\(P(X \ge a) \le \dfrac{\mu}{a}\)</span> &nbsp;&nbsp; <strong>(B)</strong> <span class="math inline">\(P(X \le a) \le \dfrac{\mu}{a}\)</span></p>
<p><strong>(C)</strong> <span class="math inline">\(P(|X - \mu| \ge a) \le \dfrac{\operatorname{Var}(X)}{a^2}\)</span> &nbsp;&nbsp; <strong>(D)</strong> <span class="math inline">\(P(X \ge a) = e^{-a/\mu}\)</span></p>
</blockquote>
</section>
<section id="a4-розвязання" class="slide level2">
<h2>✅ A4 — розв’язання</h2>
<p>Класичне формулювання Маркова: для <span class="math inline">\(X \ge 0\)</span> та <span class="math inline">\(a &gt; 0\)</span></p>
<p><span class="math display">\[
P(X \ge a) \le \frac{E[X]}{a} = \frac{\mu}{a}.
\]</span></p>
<ul>
<li><ol start="3" type="A">
<li>— це нерівність <strong>Чебишева</strong> (центрований варіант).</li>
</ol></li>
<li><ol start="4" type="A">
<li>— формула для <strong>виживання</strong> Exp-розподілу, а не загальна нерівність.</li>
</ol></li>
</ul>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Відповідь: (A).</strong></p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Виділити дві умови Маркова: <span class="math inline">\(X \ge 0\)</span> та <span class="math inline">\(E[X] &lt; \infty\)</span>. Без невід’ємності нерівність не діє. Чебишева (C) — корисно згадати як «наступний рівень»: дає кращу межу, але потребує дисперсії. Зв’язок із P6.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a5-operatornamevar-для-binomial" class="slide level2">
<h2>🧩 A5 — <span class="math inline">\(\operatorname{Var}\)</span> для Binomial</h2>
<blockquote>
<p><span class="math inline">\(X \sim \mathrm{Binomial}(n = 20, p = 0.30)\)</span>. Знайти <span class="math inline">\(\operatorname{Var}(X)\)</span>.</p>
<p><strong>(A)</strong> 0.21 &nbsp;&nbsp; <strong>(B)</strong> 0.30 &nbsp;&nbsp; <strong>(C)</strong> 4.2 &nbsp;&nbsp; <strong>(D)</strong> 6</p>
</blockquote>
</section>
<section id="a5-розвязання" class="slide level2">
<h2>✅ A5 — розв’язання</h2>
<p>З довідника: <span class="math inline">\(\operatorname{Var}(X) = n p (1 - p)\)</span>.</p>
<p><span class="math display">\[
\operatorname{Var}(X) = 20 \cdot 0.30 \cdot 0.70 = 4.2.
\]</span></p>
<p>Зауваження: <span class="math inline">\(np = 6\)</span> — це <strong>середнє</strong>, <span class="math inline">\(p(1 - p) = 0.21\)</span> — дисперсія <strong>одного</strong> Бернуллі.</p>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Відповідь: (C) 4.2.</strong></p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Студенти часто плутають <span class="math inline">\(np\)</span> (середнє) із дисперсією. Підказка: «середнє росте з <span class="math inline">\(n\)</span>, дисперсія — теж, але через множник <span class="math inline">\(p(1-p)\)</span>». На дошці розкласти <span class="math inline">\(X = \sum X_i\)</span> де <span class="math inline">\(X_i\)</span> — Бернуллі, і скористатись адитивністю дисперсії.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a5-binom20-0.3-у-r" class="slide level2">
<h2>📊 A5 — Binom(20, 0.3) у R</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">20</span>; p <span class="ot">&lt;-</span> <span class="fl">0.30</span></span>
<span id="cb1-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">k =</span> <span class="dv">0</span><span class="sc">:</span>n, <span class="at">pmf =</span> <span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span>n, n, p)) <span class="sc">|&gt;</span></span>
<span id="cb1-3"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(k, pmf)) <span class="sc">+</span></span>
<span id="cb1-4"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> blue, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb1-5"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> n <span class="sc">*</span> p, <span class="at">color =</span> red, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb1-6"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> n<span class="sc">*</span>p <span class="sc">+</span> <span class="fl">0.4</span>, <span class="at">y =</span> <span class="fu">max</span>(<span class="fu">dbinom</span>(<span class="dv">0</span><span class="sc">:</span>n, n, p)) <span class="sc">*</span> <span class="fl">0.9</span>,</span>
<span id="cb1-7"><a href="" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"E[X] = 6"</span>, <span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">color =</span> red) <span class="sc">+</span></span>
<span id="cb1-8"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, n, <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb1-9"><a href="" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Binom(20, 0.3): Var = 4.2,  SD ≈ 2.05"</span>,</span>
<span id="cb1-10"><a href="" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"k"</span>, <span class="at">y =</span> <span class="st">"P(X = k)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src=".midterm-mock-slides_files/figure-revealjs/unnamed-chunk-1-1.svg" class="r-stretch"></section>
<section id="a6-memoryless-property" class="slide level2">
<h2>🧩 A6 — memoryless property</h2>
<blockquote>
<p>Для <span class="math inline">\(X \sim \mathrm{Exp}(\lambda)\)</span> і будь-яких <span class="math inline">\(s, t &gt; 0\)</span>:</p>
<p><strong>(A)</strong> <span class="math inline">\(P(X &gt; s + t \mid X &gt; s) = P(X &gt; t)\)</span></p>
<p><strong>(B)</strong> <span class="math inline">\(E[X^2] = (E[X])^2\)</span></p>
<p><strong>(C)</strong> <span class="math inline">\(\operatorname{Var}(X) = E[X]\)</span></p>
<p><strong>(D)</strong> <span class="math inline">\(P(X &gt; s + t) = P(X &gt; s) + P(X &gt; t)\)</span></p>
</blockquote>
</section>
<section id="a6-розвязання" class="slide level2">
<h2>✅ A6 — розв’язання</h2>
<p>Memoryless: знання, що чекали <span class="math inline">\(s\)</span> часу, <strong>не змінює</strong> розподілу подальшого очікування.</p>
<p><span class="math display">\[
P(X &gt; s + t \mid X &gt; s)
= \frac{e^{-\lambda(s+t)}}{e^{-\lambda s}}
= e^{-\lambda t} = P(X &gt; t).
\]</span></p>
<ul>
<li><ol start="2" type="A">
<li>хибно — це твердження дало б <span class="math inline">\(\operatorname{Var}(X) = 0\)</span>.</li>
</ol></li>
<li><ol start="3" type="A">
<li>випадково вірне для <span class="math inline">\(\mathrm{Exp}(1)\)</span>, але не загалом.</li>
</ol></li>
<li><ol start="4" type="A">
<li>хибно — ймовірності не додаються таким чином.</li>
</ol></li>
</ul>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Відповідь: (A).</strong></p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Memoryless — унікальна риса Exp (і дискретного geometric). Інтуїція: «час очікування автобуса не знає, скільки ви вже чекали». Підготувати до P5(d), де ця ж властивість зустрінеться у задачі про доставку.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a7-clt" class="slide level2">
<h2>🧩 A7 — CLT</h2>
<blockquote>
<p>CLT: величина <span class="math inline">\(\dfrac{\bar X_n - \mu}{\sigma/\sqrt{n}}\)</span> збігається за розподілом до:</p>
<p><strong>(A)</strong> <span class="math inline">\(\mathcal{N}(\mu, \sigma^2)\)</span> &nbsp;&nbsp; <strong>(B)</strong> <span class="math inline">\(\mathcal{N}(0, 1)\)</span> &nbsp;&nbsp; <strong>(C)</strong> <span class="math inline">\(\mathrm{Unif}(0, 1)\)</span> &nbsp;&nbsp; <strong>(D)</strong> <span class="math inline">\(\mathrm{Exp}(1)\)</span></p>
</blockquote>
</section>
<section id="a7-розвязання" class="slide level2">
<h2>✅ A7 — розв’язання</h2>
<p>CLT стандартизує середнє: ділення на <span class="math inline">\(\sigma/\sqrt{n}\)</span> та віднімання <span class="math inline">\(\mu\)</span> дає <strong>стандартний</strong> нормальний.</p>
<p><span class="math display">\[
\frac{\bar X_n - \mu}{\sigma/\sqrt{n}} \xrightarrow{d} \mathcal{N}(0, 1).
\]</span></p>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Відповідь: (B).</strong></p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Ключова деталь: вже <strong>стандартизована</strong> величина — тому збігається саме до <span class="math inline">\(\mathcal{N}(0, 1)\)</span>, а не до <span class="math inline">\(\mathcal{N}(\mu, \sigma^2)\)</span>. Відповідь (A) — типова пастка для тих, хто запам’ятав «CLT → нормальний», але не дивиться на знаменник.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a8-найсильніший-лінійний-звязок" class="slide level2">
<h2>🧩 A8 — найсильніший лінійний зв’язок</h2>
<blockquote>
<p>Який <span class="math inline">\(\rho\)</span> вказує на <strong>найсильніший</strong> лінійний зв’язок?</p>
<p><strong>(A)</strong> <span class="math inline">\(0.72\)</span> &nbsp;&nbsp; <strong>(B)</strong> <span class="math inline">\(-0.91\)</span> &nbsp;&nbsp; <strong>(C)</strong> <span class="math inline">\(0.50\)</span> &nbsp;&nbsp; <strong>(D)</strong> <span class="math inline">\(0.01\)</span></p>
</blockquote>
</section>
<section id="a8-розвязання" class="slide level2">
<h2>✅ A8 — розв’язання</h2>
<p>Сила лінійного зв’язку = <span class="math inline">\(|\rho|\)</span>, <strong>знак</strong> — лише напрям.</p>
<p><span class="math display">\[
|{-0.91}| = 0.91 &gt; 0.72 &gt; 0.50 &gt; 0.01.
\]</span></p>
<p>Від’ємний знак означає, що зі зростанням <span class="math inline">\(X\)</span> величина <span class="math inline">\(Y\)</span> <strong>спадає</strong> — і це найсильніший зв’язок із наведених.</p>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Відповідь: (B) <span class="math inline">\(\rho = -0.91\)</span>.</strong></p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Знак vs сила — стандартна плутанина. Підкреслити: <span class="math inline">\(\rho = -0.91\)</span> описує точки, що майже лежать на прямій з негативним нахилом. Зробити аналогію зі склянкою, яку перекидаєш: жорсткий механічний зв’язок є, просто оберненого знаку.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a9-баєс-high-risk-applicant" class="slide level2">
<h2>🧩 A9 — Баєс: high-risk applicant</h2>
<blockquote>
<p>5% високого ризику; модель ловить 90% true high-risk і <strong>хибно</strong> прапорить 10% low-risk. Дано «+»: <span class="math inline">\(P(\text{high} \mid +) \approx ?\)</span></p>
<p><strong>(A)</strong> 0.05 &nbsp;&nbsp; <strong>(B)</strong> 0.32 &nbsp;&nbsp; <strong>(C)</strong> 0.50 &nbsp;&nbsp; <strong>(D)</strong> 0.90</p>
</blockquote>
</section>
<section id="a9-баєс" class="slide level2">
<h2>✅ A9 — Баєс</h2>
<p><span class="math display">\[
P(+) = 0.05 \cdot 0.90 + 0.95 \cdot 0.10 = 0.045 + 0.095 = 0.140.
\]</span></p>
<p><span class="math display">\[
P(\text{high} \mid +) = \frac{0.05 \cdot 0.90}{0.140} = \frac{0.045}{0.140} \approx 0.321.
\]</span></p>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Відповідь: (B) ≈ 0.32.</strong></p>
<p>⚠️ Класична <strong>base-rate fallacy</strong>: «90% чутливість» <span class="math inline">\(\neq\)</span> «90% впевненості після +».</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Найважливіший слайд секції. Пояснити числами: 95% «low-risk» × 10% FP = 9.5 false positives на 100 заявок, а true positives — лише 4.5. Тому posterior значно менше за чутливість. Підготувати до P1 (та сама ідея на спам-фільтрі).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="a9-у-r" class="slide level2">
<h2>📊 A9 — у R</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="" aria-hidden="true" tabindex="-1"></a>prior_h <span class="ot">&lt;-</span> <span class="fl">0.05</span>; prior_l <span class="ot">&lt;-</span> <span class="fl">0.95</span></span>
<span id="cb2-2"><a href="" aria-hidden="true" tabindex="-1"></a>sens <span class="ot">&lt;-</span> <span class="fl">0.90</span>;    fpr  <span class="ot">&lt;-</span> <span class="fl">0.10</span></span>
<span id="cb2-3"><a href="" aria-hidden="true" tabindex="-1"></a>p_pos <span class="ot">&lt;-</span> sens <span class="sc">*</span> prior_h <span class="sc">+</span> fpr <span class="sc">*</span> prior_l</span>
<span id="cb2-4"><a href="" aria-hidden="true" tabindex="-1"></a>sens <span class="sc">*</span> prior_h <span class="sc">/</span> p_pos</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3214286</code></pre>
</div>
</div>
</section>
<section id="a10-закон-великих-чисел" class="slide level2">
<h2>🧩 A10 — Закон великих чисел</h2>
<blockquote>
<p>LLN гарантує, що при <span class="math inline">\(n \to \infty\)</span>:</p>
<p><strong>(A)</strong> <span class="math inline">\(\bar X_n \xrightarrow{p} \mu\)</span></p>
<p><strong>(B)</strong> <span class="math inline">\(\bar X_n \xrightarrow{d} \mathcal{N}(0, 1)\)</span></p>
<p><strong>(C)</strong> Окремі <span class="math inline">\(X_i\)</span> наближаються до <span class="math inline">\(\mu\)</span></p>
<p><strong>(D)</strong> <span class="math inline">\(S_n^2 \to 0\)</span></p>
</blockquote>
</section>
<section id="a10-розвязання" class="slide level2">
<h2>✅ A10 — розв’язання</h2>
<p>LLN: <strong>середнє за вибіркою</strong> збігається за ймовірністю до <strong>істинного середнього</strong>.</p>
<ul>
<li><ol start="2" type="A">
<li>— це CLT (про <strong>стандартизоване</strong> середнє).</li>
</ol></li>
<li><ol start="3" type="A">
<li>— кожне окреме <span class="math inline">\(X_i\)</span> залишається випадковим, <strong>не</strong> «прилипає» до <span class="math inline">\(\mu\)</span>.</li>
</ol></li>
<li><ol start="4" type="A">
<li>— навпаки, <span class="math inline">\(S_n^2 \to \sigma^2\)</span>.</li>
</ol></li>
</ul>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Відповідь: (A).</strong></p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>LLN — про <strong>середнє вибірки</strong>, не про окремі спостереження. Уточнити різницю: CLT каже <strong>як швидко</strong> і <strong>в якій формі</strong> <span class="math inline">\(\bar X_n\)</span> наближається до <span class="math inline">\(\mu\)</span>; LLN — лише факт збіжності. Зв’язати з P10(d).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="section-b.-true-false" class="title-slide slide level1 center">
<h1>Section B. True / False</h1>

</section>
<section id="b1-формула-включень-виключень" class="slide level2">
<h2>🧩 B1 — формула включень-виключень</h2>
<blockquote>
<p>Для будь-яких подій <span class="math inline">\(A, B\)</span>: <span class="math inline">\(P(A \cup B) = P(A) + P(B) - P(A \cap B)\)</span>.</p>
</blockquote>
</section>
<section id="b1-true" class="slide level2">
<h2>✅ B1 — <strong>TRUE</strong></h2>
<p>Класична формула включень-виключень для <strong>довільних</strong> подій (без вимоги несумісності).</p>
<p>Якби події були <strong>несумісні</strong>, <span class="math inline">\(P(A \cap B) = 0\)</span> і формула спрощується до адитивності.</p>
<aside class="notes">
<p>Найшвидший слайд секції — формула знайома. Підкреслити: «мінус <span class="math inline">\(P(A \cap B)\)</span>» з’являється, бо інакше перетин рахується двічі. Намалювати кола Венна, якщо є дошка.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="b2-cov-0-незалежність" class="slide level2">
<h2>🧩 B2 — Cov = 0 ⇒ незалежність?</h2>
<blockquote>
<p>Якщо <span class="math inline">\(\operatorname{Cov}(X, Y) = 0\)</span>, то <span class="math inline">\(X\)</span> і <span class="math inline">\(Y\)</span> незалежні.</p>
</blockquote>
</section>
<section id="b2-false" class="slide level2">
<h2>✅ B2 — <strong>FALSE</strong></h2>
<p>Незалежність <span class="math inline">\(\Rightarrow\)</span> <span class="math inline">\(\operatorname{Cov} = 0\)</span>, але <strong>не навпаки</strong>.</p>
<p><strong>Контрприклад:</strong> <span class="math inline">\(X \sim \mathcal{N}(0, 1)\)</span>, <span class="math inline">\(Y = X^2\)</span>. Тоді <span class="math inline">\(\operatorname{Cov}(X, Y) = E[X^3] - E[X]E[X^2] = 0\)</span>, але <span class="math inline">\(Y\)</span> детерміновано залежить від <span class="math inline">\(X\)</span>.</p>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>Виправлення:</strong> «Якщо <span class="math inline">\(X, Y\)</span> <strong>незалежні</strong>, то <span class="math inline">\(\operatorname{Cov}(X, Y) = 0\)</span>.»</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Одна з улюблених пасток підручників. Cov ловить лише <strong>лінійний</strong> зв’язок — а <span class="math inline">\(Y = X^2\)</span> це чиста нелінійність. На графіку парабола: видно структуру, але «середній нахил» = 0. Підкреслити: незалежність — сильніша умова.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="b2-covx-x²-0-але-залежні" class="slide level2">
<h2>📊 B2 — Cov(X, X²) = 0, але залежні</h2>

<img data-src=".midterm-mock-slides_files/figure-revealjs/unnamed-chunk-3-1.svg" class="r-stretch"></section>
<section id="b3-px-c-0" class="slide level2">
<h2>🧩 B3 — <span class="math inline">\(P(X = c) = 0\)</span>?</h2>
<blockquote>
<p>Для будь-якої <strong>неперервної</strong> <span class="math inline">\(X\)</span> і константи <span class="math inline">\(c\)</span>: <span class="math inline">\(P(X = c) = 0\)</span>.</p>
</blockquote>
</section>
<section id="b3-true" class="slide level2">
<h2>✅ B3 — <strong>TRUE</strong></h2>
<p>Маса однієї точки для неперервного розподілу дорівнює нулю — це наслідок інтегрального означення:</p>
<p><span class="math display">\[
P(X = c) = \int_c^c f(x)\,dx = 0.
\]</span></p>
<p>Саме тому в неперервних розподілах байдуже, <span class="math inline">\(\le\)</span> чи <span class="math inline">\(&lt;\)</span>.</p>
<aside class="notes">
<p>Зв’язок із A3. Обов’язково зазначити практичний наслідок: при розрахунках типу <span class="math inline">\(P(a &lt; X &lt; b)\)</span> можна не перейматись межами. У дискретному ж випадку <span class="math inline">\(P(X \le 2)\)</span> і <span class="math inline">\(P(X &lt; 2)\)</span> — різні величини.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="b4-дисперсія-може-бути-відємною" class="slide level2">
<h2>🧩 B4 — дисперсія може бути від’ємною?</h2>
<blockquote>
<p>Дисперсія може бути від’ємною, якщо розподіл лівоскошений.</p>
</blockquote>
</section>
<section id="b4-false" class="slide level2">
<h2>✅ B4 — <strong>FALSE</strong></h2>
<p><span class="math display">\[
\operatorname{Var}(X) = E[(X - \mu)^2] \ge 0.
\]</span></p>
<p>Це сподівання <strong>квадрата</strong> — не може бути від’ємним. Скошеність впливає лише на третій момент.</p>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>Виправлення:</strong> «Дисперсія завжди невід’ємна; <span class="math inline">\(\operatorname{Var}(X) = 0\)</span> ⇔ <span class="math inline">\(X\)</span> — стала майже напевне.»</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Скошеність впливає на <strong>третій</strong> момент (асиметрію), а не на дисперсію. Швидке мнемонічне правило: «дисперсія — це квадрат». Можна попросити аудиторію назвати, який момент відповідає за «довжину хвоста» — це підготує до D4.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="b5-lln" class="slide level2">
<h2>🧩 B5 — LLN</h2>
<blockquote>
<p>LLN гарантує <span class="math inline">\(\bar X_n \xrightarrow{p} \mu\)</span> при <span class="math inline">\(n \to \infty\)</span>.</p>
</blockquote>
</section>
<section id="b5-true" class="slide level2">
<h2>✅ B5 — <strong>TRUE</strong></h2>
<p>Слабкий закон великих чисел (за умови <span class="math inline">\(E|X| &lt; \infty\)</span>):</p>
<p><span class="math display">\[
\forall \varepsilon &gt; 0: \quad P(|\bar X_n - \mu| &gt; \varepsilon) \to 0.
\]</span></p>
<p>Сильний закон дає навіть <strong>майже напевну</strong> збіжність.</p>
<aside class="notes">
<p>Не плутати з CLT. Пояснити «за ймовірністю» простими словами: для будь-якої заданої ε ймовірність «промахнутися» більше ε прямує до 0. Зв’язок із A10 і P10(d).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="b6-стандартизація-нормального" class="slide level2">
<h2>🧩 B6 — стандартизація нормального</h2>
<blockquote>
<p>Якщо <span class="math inline">\(X \sim \mathcal{N}(\mu, \sigma^2)\)</span>, то <span class="math inline">\(\dfrac{X - \mu}{\sigma} \sim \mathcal{N}(1, 1)\)</span>.</p>
</blockquote>
</section>
<section id="b6-false" class="slide level2">
<h2>✅ B6 — <strong>FALSE</strong></h2>
<p>Стандартизація дає <strong>стандартний</strong> нормальний, а не зсунутий:</p>
<p><span class="math display">\[
\frac{X - \mu}{\sigma} \sim \mathcal{N}(0, 1).
\]</span></p>
<p>Швидка перевірка: <span class="math inline">\(E\!\left[\frac{X-\mu}{\sigma}\right] = 0\)</span>, <span class="math inline">\(\operatorname{Var}\!\left[\frac{X-\mu}{\sigma}\right] = 1\)</span>.</p>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>Виправлення:</strong> «<span class="math inline">\(\dfrac{X - \mu}{\sigma} \sim \mathcal{N}(0, 1)\)</span>.»</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Тут діє лінійна властивість моментів: віднімання <span class="math inline">\(\mu\)</span> зсуває середнє до 0, ділення на <span class="math inline">\(\sigma\)</span> робить дисперсію 1. Корисно показати кроки на дошці — це фундамент для всіх <span class="math inline">\(z\)</span>-перетворень у Section D.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="b7-нерівність-маркова" class="slide level2">
<h2>🧩 B7 — нерівність Маркова</h2>
<blockquote>
<p>Для <span class="math inline">\(X \ge 0\)</span> і <span class="math inline">\(a &gt; 0\)</span>: <span class="math inline">\(P(X \ge a) \le \dfrac{E[X]}{a}\)</span>.</p>
</blockquote>
</section>
<section id="b7-true" class="slide level2">
<h2>✅ B7 — <strong>TRUE</strong></h2>
<p>Це класична нерівність Маркова. Умова <strong>невід’ємності</strong> <span class="math inline">\(X\)</span> є критичною: для довільних <span class="math inline">\(X\)</span> нерівність не виконується.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Швидка перевірка для Exp(1/20): E[T] = 20, P(T &gt; 100) &lt;= 20/100 = 0.2</span></span>
<span id="cb4-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pexp</span>(<span class="dv">100</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>)    <span class="co"># 0.0067 — реальне</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.006737947</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="dv">20</span> <span class="sc">/</span> <span class="dv">100</span>                      <span class="co"># 0.2 — межа Маркова (груба, але вірна)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2</code></pre>
</div>
</div>
<aside class="notes">
<p>Показати на цифрах, наскільки межа груба: 0.0067 vs 0.2 — у 30 разів. Маркова рідко близька до істини, але вона єдина, що працює, коли знаємо лише <span class="math inline">\(E[X]\)</span>. Підготувати до P6.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="b8-кореляція" class="slide level2">
<h2>🧩 B8 — кореляція</h2>
<blockquote>
<p><span class="math inline">\(-1 \le \rho \le 1\)</span>, і <span class="math inline">\(\rho = \pm 1\)</span> ⇔ існує <strong>ідеальний лінійний</strong> зв’язок.</p>
</blockquote>
</section>
<section id="b8-true" class="slide level2">
<h2>✅ B8 — <strong>TRUE</strong></h2>
<p>Це наслідок нерівності Коші–Шварца:</p>
<p><span class="math display">\[
|\operatorname{Cov}(X, Y)| \le \sqrt{\operatorname{Var}(X)\operatorname{Var}(Y)}.
\]</span></p>
<p>Рівність ⇔ <span class="math inline">\(Y = aX + b\)</span> для деяких <span class="math inline">\(a \ne 0, b\)</span>. Знак <span class="math inline">\(\rho\)</span> збігається зі знаком <span class="math inline">\(a\)</span>.</p>
<aside class="notes">
<p>Підкреслити: «ідеальна» означає <strong>строго лінійна</strong>, а не «детерміністична». <span class="math inline">\(Y = X^2\)</span> — детермінований зв’язок, але <span class="math inline">\(\rho \ne \pm 1\)</span>. Зв’язок із B2 і A8. Якщо є час — нагадати, що <span class="math inline">\(\rho\)</span> безрозмірне.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="section-c.-validity-check" class="title-slide slide level1 center">
<h1>Section C. Validity Check</h1>

</section>
<section id="c1-pmf-fx-tfracx110-x-in-0123" class="slide level2">
<h2>🧩 C1 — PMF: <span class="math inline">\(f(x) = \tfrac{x+1}{10}\)</span>, <span class="math inline">\(x \in \{0,1,2,3\}\)</span></h2>
<blockquote>
<p>Чи валідна PMF?</p>
</blockquote>
<p>Треба перевірити: (i) <span class="math inline">\(f(x) \ge 0\)</span>, (ii) <span class="math inline">\(\sum f(x) = 1\)</span>.</p>
</section>
<section id="c1-розвязання" class="slide level2">
<h2>✅ C1 — розв’язання</h2>
<p><strong>Невід’ємність:</strong> <span class="math inline">\(f(0)=0.1,\ f(1)=0.2,\ f(2)=0.3,\ f(3)=0.4 \ge 0\)</span> ✓</p>
<p><strong>Сума:</strong></p>
<p><span class="math display">\[
\sum_{x=0}^{3} \frac{x+1}{10}
= \frac{1 + 2 + 3 + 4}{10}
= \frac{10}{10} = 1 \;\checkmark
\]</span></p>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Висновок:</strong> Валідна PMF.</p>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">3</span>; pmf <span class="ot">&lt;-</span> (x <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">10</span></span>
<span id="cb8-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">all</span>(pmf <span class="sc">&gt;=</span> <span class="dv">0</span>); <span class="fu">sum</span>(pmf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<aside class="notes">
<p>Шаблон перевірки PMF: невід’ємність + нормування. Завжди дві умови. На R перевіряємо <code>all(pmf &gt;= 0)</code> і <code>sum(pmf)</code>. Цей слайд — мінімальний робочий приклад: добре спрацьовує як референс.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="c2-pmf-fx-tfracx18-x-in-123" class="slide level2">
<h2>🧩 C2 — PMF: <span class="math inline">\(f(x) = \tfrac{x+1}{8}\)</span>, <span class="math inline">\(x \in \{1,2,3\}\)</span></h2>
<blockquote>
<p>Чи валідна PMF?</p>
</blockquote>
</section>
<section id="c2-розвязання" class="slide level2">
<h2>✅ C2 — розв’язання</h2>
<p><strong>Невід’ємність:</strong> <span class="math inline">\(f(1)=0.25,\ f(2)=0.375,\ f(3)=0.5 \ge 0\)</span> ✓</p>
<p><strong>Сума:</strong></p>
<p><span class="math display">\[
\sum_{x=1}^{3} \frac{x+1}{8}
= \frac{2 + 3 + 4}{8}
= \frac{9}{8} \neq 1 \;\text{✗}
\]</span></p>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>Висновок:</strong> НЕ валідна PMF — нормування порушено.</p>
<p>Щоб виправити: замінити знаменник на <span class="math inline">\(9\)</span>.</p>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>; <span class="fu">sum</span>((x <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">8</span>)        <span class="co"># 1.125</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.125</code></pre>
</div>
</div>
<aside class="notes">
<p>Спосіб виправити — підказати студентам шукати правильний нормувальний коефіцієнт. У завданні C-бонус ця ж техніка: знайти <span class="math inline">\(k\)</span>, щоб сума = 1. Підготовка до C-бонусу.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="c3-pdf-fx-3x2-0-le-x-le-1" class="slide level2">
<h2>🧩 C3 — PDF: <span class="math inline">\(f(x) = 3x^2\)</span>, <span class="math inline">\(0 \le x \le 1\)</span></h2>
<blockquote>
<p>Чи валідна PDF?</p>
</blockquote>
</section>
<section id="c3-розвязання" class="slide level2">
<h2>✅ C3 — розв’язання</h2>
<p><strong>Невід’ємність:</strong> <span class="math inline">\(3x^2 \ge 0\)</span> для всіх <span class="math inline">\(x\)</span> ✓</p>
<p><strong>Інтеграл:</strong></p>
<p><span class="math display">\[
\int_0^1 3x^2\,dx = \left[x^3\right]_0^1 = 1 \;\checkmark
\]</span></p>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p><strong>Висновок:</strong> Валідна PDF (це окремий випадок <span class="math inline">\(\mathrm{Beta}(3, 1)\)</span>).</p>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">integrate</span>(<span class="cf">function</span>(x) <span class="dv">3</span> <span class="sc">*</span> x<span class="sc">^</span><span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1 with absolute error &lt; 1.1e-14</code></pre>
</div>
</div>
<aside class="notes">
<p>Для PDF — інтеграл замість суми. Підкреслити паралель: PMF/<span class="math inline">\(\sum\)</span> ↔︎ PDF/<span class="math inline">\(\int\)</span>. <span class="math inline">\(\mathrm{Beta}(3, 1)\)</span> — приклад «зростаючої щільності»: маса концентрується ближче до 1. Можна показати на графіку.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="c4-pdf-fx-2x-0-le-x-le-2" class="slide level2">
<h2>🧩 C4 — PDF: <span class="math inline">\(f(x) = 2x\)</span>, <span class="math inline">\(0 \le x \le 2\)</span></h2>
<blockquote>
<p>Чи валідна PDF?</p>
</blockquote>
</section>
<section id="c4-розвязання" class="slide level2">
<h2>✅ C4 — розв’язання</h2>
<p><strong>Невід’ємність:</strong> <span class="math inline">\(2x \ge 0\)</span> на <span class="math inline">\([0, 2]\)</span> ✓</p>
<p><strong>Інтеграл:</strong></p>
<p><span class="math display">\[
\int_0^2 2x\,dx = \left[x^2\right]_0^2 = 4 \neq 1 \;\text{✗}
\]</span></p>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>Висновок:</strong> НЕ валідна PDF.</p>
<p>Щоб виправити: замінити коефіцієнт <span class="math inline">\(2\)</span> на <span class="math inline">\(1/2\)</span> (тоді <span class="math inline">\(\int_0^2 \tfrac{x}{2}\,dx = 1\)</span>).</p>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">integrate</span>(<span class="cf">function</span>(x) <span class="dv">2</span> <span class="sc">*</span> x, <span class="dv">0</span>, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>4 with absolute error &lt; 4.4e-14</code></pre>
</div>
</div>
<aside class="notes">
<p>Звернути увагу: <span class="math inline">\(f(x) = 2x\)</span> на <span class="math inline">\([0, 1]\)</span> була б валідною (інтеграл = 1), але розширення меж до 2 ламає нормування. Це гарна нагода обговорити: PDF — це <strong>функція + носій</strong>, неможна змінювати одне без іншого.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="c3-бонус-знайти-k" class="slide level2">
<h2>🧩 C3 (бонус) — знайти <span class="math inline">\(k\)</span></h2>
<blockquote>
<p><span class="math inline">\(f(x) = k\,x(4 - x), \quad x \in \{1, 2, 3\}\)</span>. Знайти <span class="math inline">\(k &gt; 0\)</span>, щоб PMF була валідною.</p>
</blockquote>
</section>
<section id="c3-бонус-розвязання" class="slide level2">
<h2>✅ C3 (бонус) — розв’язання</h2>
<p>Обчислимо суму без <span class="math inline">\(k\)</span>:</p>
<p><span class="math display">\[
\sum_{x=1}^{3} x(4 - x) = 1\cdot 3 + 2\cdot 2 + 3\cdot 1 = 3 + 4 + 3 = 10.
\]</span></p>
<p>Умова <span class="math inline">\(k \cdot 10 = 1\)</span>:</p>
<p><span class="math display">\[
\boxed{k = \frac{1}{10} = 0.1}.
\]</span></p>
<p><strong>Перевірка невід’ємності:</strong> <span class="math inline">\(0.1 \cdot \{3, 4, 3\} = \{0.3, 0.4, 0.3\} \ge 0\)</span> ✓ і сума <span class="math inline">\(= 1\)</span> ✓.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>; k <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> <span class="fu">sum</span>(x <span class="sc">*</span> (<span class="dv">4</span> <span class="sc">-</span> x))</span>
<span id="cb17-2"><a href="" aria-hidden="true" tabindex="-1"></a>k; <span class="fu">sum</span>(k <span class="sc">*</span> x <span class="sc">*</span> (<span class="dv">4</span> <span class="sc">-</span> x))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<aside class="notes">
<p>Алгоритм пошуку нормувальної константи: (1) обчислити суму без <span class="math inline">\(k\)</span>, (2) узяти <span class="math inline">\(k = 1/\text{сума}\)</span>, (3) перевірити невід’ємність. Та сама техніка для PDF, але з інтегралом. Корисний навик для всього курсу.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="section-d.-r-output-interpretation" class="title-slide slide level1 center">
<h1>Section D. R Output Interpretation</h1>

</section>
<section id="block-d1-normal-пісенні-стріми" class="slide level2">
<h2>Block D1 — Normal: пісенні стріми</h2>
<p>Контекст: <span class="math inline">\(X \sim \mathcal{N}(\mu = 12, \sigma = 3.2)\)</span> — щоденні стріми (тис.) укр. поп-пісень.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">12</span>; sigma <span class="ot">&lt;-</span> <span class="fl">3.2</span></span>
<span id="cb20-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">15.2</span>, mu, sigma)                          <span class="co"># 0.8413</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8413447</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">8.8</span>,  mu, sigma)                          <span class="co"># 0.1587</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1586553</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">5.6</span>,  mu, sigma, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)      <span class="co"># 0.9772</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9772499</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.90</span>, mu, sigma)                          <span class="co"># 16.10</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.10097</code></pre>
</div>
</div>
</section>
<section id="d1a-pnorm15.2-0.8413" class="slide level2">
<h2>✅ D1(a) — <code>pnorm(15.2) = 0.8413</code></h2>
<p><span class="math display">\[
P(X &lt; 15.2) = 0.8413 = 84.13\%.
\]</span></p>
<p>Близько <strong>84%</strong> пісень отримують менше 15 200 стрімів на день. Поріг <span class="math inline">\(15.2 = \mu + \sigma\)</span> — рівно <span class="math inline">\(z = 1\)</span>.</p>
<p><strong>Для продюсера:</strong> 15 200 — це <strong>верхня межа звичайного діапазону</strong>, не «хіт». Хіт мав би бути значно вищим (див. (d)).</p>
<aside class="notes">
<p><code>pnorm</code> — це CDF, тобто <span class="math inline">\(P(X &lt; x)\)</span> (для неперервної однаково <span class="math inline">\(\le\)</span>). Прив’язати до правила 68–95: <span class="math inline">\(\mu + \sigma\)</span> → 84% маси ліворуч. Корисно записати чисельники в стилі <span class="math inline">\(0.5 + 0.34 = 0.84\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d1b-правило-689599.7" class="slide level2">
<h2>✅ D1(b) — правило 68–95–99.7</h2>
<p><span class="math display">\[
P(8.8 &lt; X &lt; 15.2) = 0.8413 - 0.1587 = 0.6826.
\]</span></p>
<p>Інтервал <span class="math inline">\([8.8;\,15.2] = [\mu - \sigma;\ \mu + \sigma]\)</span> — це <strong>класичне правило <span class="math inline">\(\mu \pm 1\sigma\)</span></strong> з емпіричного правила: 68.27% маси.</p>
<aside class="notes">
<p>Емпіричне правило 68–95–99.7 — обов’язково запам’ятати на іспит. Підказати: <span class="math inline">\(\mu \pm 1\sigma \approx 68\%\)</span>, <span class="math inline">\(\mu \pm 2\sigma \approx 95\%\)</span>, <span class="math inline">\(\mu \pm 3\sigma \approx 99.7\%\)</span>. Часто екзаменаційні задачі побудовані саме на цих числах.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d1c-pnorm5.6-lower.tail-false-0.9772" class="slide level2">
<h2>✅ D1(c) — <code>pnorm(5.6, lower.tail = FALSE) = 0.9772</code></h2>
<p><span class="math display">\[
P(X &gt; 5.6) = 0.9772 \quad \Leftrightarrow \quad P(X &lt; 5.6) = 0.0228.
\]</span></p>
<p><span class="math inline">\(5.6 = \mu - 2\sigma\)</span> — це <span class="math inline">\(z = -2\)</span>.</p>
<p><strong>Для аналітика:</strong> лише ≈ <strong>2.3%</strong> пісень отримують <strong>менше 5 600 стрімів</strong> — це сильний сигнал, що пісня <strong>серйозно недопрацьовує</strong> (нижні 2.5%).</p>
<aside class="notes">
<p><code>lower.tail = FALSE</code> — це <span class="math inline">\(P(X &gt; x)\)</span>, верхній хвіст. Тут <span class="math inline">\(5.6 = \mu - 2\sigma\)</span> — це нижні 2.5%, тому правий хвіст 97.5%. Підкреслити: <span class="math inline">\(z = -2\)</span> → дві сторони хвостів дають <span class="math inline">\(5\%\)</span> (правило 95%).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d1d-qnorm0.90-16.10" class="slide level2">
<h2>✅ D1(d) — <code>qnorm(0.90) = 16.10</code></h2>
<p>Поріг «хіта» — <strong>16 100 стрімів</strong> (90-й перцентиль).</p>
<p><strong>Геометрично:</strong> 16.10 — це точка на осі <span class="math inline">\(x\)</span>, <strong>лівіше</strong> від якої лежить <strong>90%</strong> площі під кривою; справа залишається <strong>10%</strong> (топ-10% — наші «хіти»).</p>
<p>Зауваження: <span class="math inline">\(16.10 &gt; \mu + \sigma = 15.2\)</span>, бо <span class="math inline">\(z_{0.9} = 1.282 &gt; 1\)</span>.</p>
<aside class="notes">
<p><code>qnorm</code> — обернена до <code>pnorm</code> (квантиль). Підкреслити пару <code>p…</code> ↔︎ <code>q…</code> — це шаблон для всіх розподілів R (<code>pbinom</code>/<code>qbinom</code>, <code>pexp</code>/<code>qexp</code>). Студенти часто плутають аргументи.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d1-візуалізація" class="slide level2">
<h2>📊 D1 — візуалізація</h2>

<img data-src=".midterm-mock-slides_files/figure-revealjs/unnamed-chunk-11-1.svg" class="r-stretch"></section>
<section id="block-d2-binomial-бариста" class="slide level2">
<h2>Block D2 — Binomial: бариста</h2>
<p><span class="math inline">\(X \sim \mathrm{Binomial}(10, 0.12)\)</span> — к-сть неправильних замовлень з 10.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="fl">0.12</span>)                  <span class="co"># 0.2785</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.278501</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">1</span>, <span class="dv">10</span>, <span class="fl">0.12</span>)                  <span class="co"># 0.6583</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.658275</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pbinom</span>(<span class="dv">2</span>, <span class="dv">10</span>, <span class="fl">0.12</span>)              <span class="co"># 0.1087</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1086818</code></pre>
</div>
</div>
</section>
<section id="d2a-dbinom0-0.2785" class="slide level2">
<h2>✅ D2(a) — <code>dbinom(0) = 0.2785</code></h2>
<p><span class="math display">\[
P(X = 0) = 0.2785 \approx 27.85\%.
\]</span></p>
<p>Ймовірність того, що з 10 замовлень <strong>жодне</strong> не зіпсоване — це і є «ідеальна зміна».</p>
<p><strong>Так</strong>, це і є ймовірність «доброї зміни» (нуль помилок). Лише ≈ <strong>3 з 10</strong> змін будуть бездоганними.</p>
<aside class="notes">
<p><code>dbinom(k, n, p)</code> — це <strong>density</strong>, тобто <span class="math inline">\(P(X = k)\)</span> для дискретного. Не плутати з <code>pbinom</code>. Формула <span class="math inline">\(0.88^{10}\)</span> також обчислюється напряму — корисно показати без R, аби студенти могли порахувати на іспиті.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d2b-pbinom1-0.6583" class="slide level2">
<h2>✅ D2(b) — <code>pbinom(1) = 0.6583</code></h2>
<p><code>pbinom(q, ...)</code> повертає <span class="math inline">\(P(X \le q)\)</span>:</p>
<p><span class="math display">\[
P(X \le 1) = P(X = 0) + P(X = 1) = 0.6583.
\]</span></p>
<p>Подія: <strong>«не більше 1 помилки за 10 замовлень»</strong>. <strong>Включено обидва</strong> значення <span class="math inline">\(X = 0\)</span> і <span class="math inline">\(X = 1\)</span>.</p>
<aside class="notes">
<p>Дуже частий ляп: студент пише <span class="math inline">\(P(X \le 1)\)</span>, але в голові уявляє <span class="math inline">\(P(X &lt; 1)\)</span>. Для дискретних розподілів <span class="math inline">\(\le\)</span> і <span class="math inline">\(&lt;\)</span> — РІЗНІ. Запам’ятати: <code>pbinom(q)</code> = <span class="math inline">\(P(X \le q)\)</span>, з включенням точки.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d2c-1---pbinom2-0.1087" class="slide level2">
<h2>✅ D2(c) — <code>1 - pbinom(2) = 0.1087</code></h2>
<p><span class="math display">\[
1 - P(X \le 2) = P(X &gt; 2) = P(X \ge 3) = 0.1087.
\]</span></p>
<p><strong>Для менеджера:</strong> приблизно <strong>10.9%</strong> змін матимуть <strong>3 або більше</strong> неправильних замовлень — саме тоді він втручається. Тобто близько <strong>1 з 9</strong> змін потребує втручання.</p>
<aside class="notes">
<p>Класична техніка для правого хвоста: <span class="math inline">\(1 - P(X \le k)\)</span>. Підкреслити, що <code>pbinom(2)</code> включає 2, тому <span class="math inline">\(1 - P(X \le 2) = P(X \ge 3)\)</span>, а не <span class="math inline">\(P(X &gt; 2)\)</span> — хоч для цілих це одне і те саме. Уважно з межами.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d2d-різниця-між-двома" class="slide level2">
<h2>✅ D2(d) — різниця між двома</h2>
<p><code>pbinom(1, ...)</code> <span class="math inline">\(= P(X \le 1)\)</span> — <strong>акумулює</strong> малі значення (низку успіхів).</p>
<p><code>1 - pbinom(2, ...)</code> <span class="math inline">\(= P(X \ge 3)\)</span> — <strong>доповнення</strong> від нижньої частини, дає <strong>верхній хвіст</strong>.</p>
<p>Чому величини різні (0.66 vs 0.11)? Бо при <span class="math inline">\(p = 0.12\)</span> розподіл сильно скошений до <strong>малих</strong> значень: <span class="math inline">\(E[X] = np = 1.2\)</span>. Маса сконцентрована в <span class="math inline">\(\{0, 1, 2\}\)</span>, у хвості <span class="math inline">\(\ge 3\)</span> маси мало.</p>
<aside class="notes">
<p>Підсумкова інтуїція секції: при малому <span class="math inline">\(p\)</span> Binomial скошений вправо (хоч і дискретний). Корисно зробити ескіз PMF на дошці. На P3 ці ж три обчислення повторюються — тут добра підготовка.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d2-pmf-binom10-0.12" class="slide level2">
<h2>📊 D2 — PMF Binom(10, 0.12)</h2>

<img data-src=".midterm-mock-slides_files/figure-revealjs/unnamed-chunk-13-1.svg" class="r-stretch"></section>
<section id="block-d3-exponential-доставка-bolt" class="slide level2">
<h2>Block D3 — Exponential: доставка Bolt</h2>
<p><span class="math inline">\(T \sim \mathrm{Exp}(\lambda = 1/20)\)</span>, <span class="math inline">\(E[T] = 20\)</span> хв.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">pexp</span>(<span class="dv">30</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)      <span class="co"># 0.2231</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2231302</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">pexp</span>(<span class="dv">40</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>) <span class="sc">-</span> <span class="fu">pexp</span>(<span class="dv">10</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>)  <span class="co"># 0.4712</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4711954</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">qexp</span>(<span class="fl">0.50</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>)                        <span class="co"># 13.86</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.86294</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">qexp</span>(<span class="fl">0.95</span>, <span class="at">rate =</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>)                        <span class="co"># 59.91</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 59.91465</code></pre>
</div>
</div>
</section>
<section id="d3a-pexp30-lowerf-0.2231" class="slide level2">
<h2>✅ D3(a) — <code>pexp(30, lower=F) = 0.2231</code></h2>
<p><span class="math display">\[
P(T &gt; 30) = e^{-30/20} = e^{-1.5} \approx 0.2231.
\]</span></p>
<p><strong>Для голодного студента:</strong> близько <strong>22.3%</strong> доставок займають <strong>довше 30 хвилин</strong>. Тобто кожна <strong>п’ята</strong> доставка — «довга».</p>
<aside class="notes">
<p>Survival function для Exp: <span class="math inline">\(P(T &gt; t) = e^{-\lambda t}\)</span>. Це одна з небагатьох формул, яку студент може порахувати без R на іспиті, якщо пам’ятає <span class="math inline">\(e^{-1} \approx 0.37, e^{-1.5} \approx 0.22, e^{-2} \approx 0.14\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d3b-pexp40---pexp10-0.4712" class="slide level2">
<h2>✅ D3(b) — <code>pexp(40) - pexp(10) = 0.4712</code></h2>
<p><span class="math display">\[
P(10 &lt; T &lt; 40) = P(T &lt; 40) - P(T &lt; 10).
\]</span></p>
<p>Подія: <strong>доставка прийшла в «прийнятному вікні» від 10 до 40 хвилин</strong>. ≈ 47% усіх доставок.</p>
<aside class="notes">
<p>Стандартна техніка інтервалу: <span class="math inline">\(P(a &lt; T &lt; b) = F(b) - F(a)\)</span>. Для неперервного байдуже, <span class="math inline">\(&lt;\)</span> чи <span class="math inline">\(\le\)</span> (B3). Можна обчислити через survivor: <span class="math inline">\(e^{-0.5} - e^{-2}\)</span> — наочніше.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d3c-медіана-середнього" class="slide level2">
<h2>✅ D3(c) — медіана &lt; середнього</h2>
<p>Медіана = 13.86 хв, середнє = 20 хв. Для Exp:</p>
<p><span class="math display">\[
\mathrm{Median} = \frac{\ln 2}{\lambda} \approx 0.693 / \lambda, \quad E[T] = 1/\lambda.
\]</span></p>
<p>Тобто завжди <span class="math inline">\(\mathrm{Median} = 0.693 \cdot E[T] &lt; E[T]\)</span>.</p>
<p><strong>Що це означає про форму:</strong> розподіл <strong>скошений вправо</strong> (right-skewed). Кілька дуже довгих доставок «тягнуть» середнє вгору, а медіана залишається ближче до типового досвіду.</p>
<aside class="notes">
<p>Загальне правило для скошених розподілів: mean &gt; median (правоскошений), mean &lt; median (лівоскошений). Це пряма зв’язка з D4 (зарплати). Підказати: коли «викид тягне в один бік», саме середнє рухається першим.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d3d-qexp0.95-59.91" class="slide level2">
<h2>✅ D3(d) — <code>qexp(0.95) = 59.91</code></h2>
<p><span class="math inline">\(X \approx 60\)</span> хвилин — <strong>«95% доставок прибувають за 60 хв»</strong>.</p>
<p><strong>Для клієнта о 2 ночі:</strong> з 5% ймовірністю чекати доведеться <strong>довше години</strong>. Якщо ви дуже голодні — є помітний ризик. Якщо ні — на 95% впораєтесь до 1 год.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Перевіримо: median, mean, 95%</span></span>
<span id="cb42-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">qexp</span>(<span class="fl">0.5</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>); <span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>); <span class="fu">qexp</span>(<span class="fl">0.95</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13.86294</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 59.91465</code></pre>
</div>
</div>
<aside class="notes">
<p>Підкреслити різницю між медіаною (≈14 хв), середнім (20 хв) і 95%-перцентилем (≈60 хв) — це 3× середнього. Класична скошеність Exp. У реальному житті це SLA: «95% доставок до 60 хв».</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="block-d4-salary-stats-normal" class="slide level2">
<h2>Block D4 — Salary stats + Normal</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(salary)</span>
<span id="cb46-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co">#  Min. 1st Qu. Median Mean 3rd Qu.  Max.</span></span>
<span id="cb46-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co">#  2100   3800   4900 5600    6200 42000</span></span>
<span id="cb46-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(salary)  <span class="co"># [1] 3200</span></span>
<span id="cb46-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">3800</span>, <span class="dv">5600</span>, <span class="dv">3200</span>)                  <span class="co"># 0.2869</span></span>
<span id="cb46-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">9000</span>, <span class="dv">5600</span>, <span class="dv">3200</span>, <span class="at">lower.tail =</span> F)  <span class="co"># 0.1440</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="d4a-форма-розподілу" class="slide level2">
<h2>✅ D4(a) — форма розподілу</h2>
<p><strong>Mean (5600) &gt; Median (4900)</strong> і <strong>Max (42 000)</strong> сильно віддалений від <span class="math inline">\(Q_3 = 6200\)</span>.</p>
<p>Класичні ознаки <strong>сильної правої скошеності</strong> (right-skewed): кілька високооплачуваних топ-менеджерів «тягнуть» середнє вгору.</p>
<p><strong>Нормальний розподіл — поганий фіт:</strong> він симетричний, тонкохвостий і не моделює викиди. Для зарплат краще log-normal або gamma.</p>
<aside class="notes">
<p>Це найважливіший слайд D4 — діагностика розподілу за summary. Три індикатори правої скошеності: mean &gt; median, <span class="math inline">\(Q_3 - Q_2\)</span> &gt; <span class="math inline">\(Q_2 - Q_1\)</span> (тут не дано, але типово), max далеко від <span class="math inline">\(Q_3\)</span>. Зв’язок із D3(c) — Exp як приклад skewed-right.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d4b-pnorm3800-0.2869" class="slide level2">
<h2>✅ D4(b) — <code>pnorm(3800) = 0.2869</code></h2>
<p><span class="math display">\[
P(X &lt; 3800) \approx 28.7\%.
\]</span></p>
<p>За нормальною апроксимацією ≈ <strong>29% співробітників</strong> заробляють <strong>менше 3 800 $/міс</strong>.</p>
<p>⚠️ Реальна частка може відрізнятися — нормальна модель не враховує скошеність.</p>
<aside class="notes">
<p>Реальна частка нижче 3800 = 25% (бо <span class="math inline">\(Q_1 = 3800\)</span>). Нормальна модель дає 28.7% — близько, але неточно. Підкреслити: модель — це <strong>інструмент</strong>, її можна (і треба) критикувати.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d4c-pnorm9000-lowerf-0.1440" class="slide level2">
<h2>✅ D4(c) — <code>pnorm(9000, lower=F) = 0.1440</code></h2>
<p><span class="math display">\[
P(X &gt; 9000) \approx 14.4\%.
\]</span></p>
<p><strong>Для HR-аналітика:</strong> під нормальним наближенням ≈ <strong>14.4%</strong> — топ-заробляючі (понад $9 000).</p>
<p>Через скошеність реальний відсоток може бути <strong>меншим</strong> (у важкому хвості мало людей, але вони далеко відриваються).</p>
<aside class="notes">
<p>Парадокс: нормальна модель <strong>переоцінює</strong> кількість «топ» у тілі, але <strong>недооцінює</strong> екстремальні викиди (max = 42 000 — це <span class="math inline">\(&gt; 11\sigma\)</span>, що для нормальної фактично неможливо). Хороша тема для розмови про важкі хвости.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d4d-більшість-заробляє-вище-середнього" class="slide level2">
<h2>✅ D4(d) — «більшість заробляє вище середнього»</h2>
<p><strong>Релевантна статистика — медіана</strong>, не середнє.</p>
<ul>
<li>Mean = 5600: половина людей заробляє менше, половина більше.</li>
<li>Median = 4900: рівно половина людей заробляє <strong>менше 4900</strong>, тобто <strong>більше половини заробляє МЕНШЕ середнього</strong> (5600), а не більше.</li>
</ul>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>Менеджер помиляється:</strong> при правій скошеності типова людина заробляє <strong>менше</strong> середнього. Це фундаментальна риса несиметричних розподілів зарплат.</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Класична риторична пастка («більшість заробляє вище середнього»). Завжди питай: про що йдеться — про <strong>mean</strong> чи <strong>median</strong>? Підкреслити політичний/економічний контекст: репортажі часто маніпулюють «середньою зарплатою».</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="d4-інтуїція-скошеності" class="slide level2">
<h2>📊 D4 — інтуїція скошеності</h2>

<img data-src=".midterm-mock-slides_files/figure-revealjs/unnamed-chunk-16-1.svg" class="r-stretch"></section></section>
<section>
<section id="problem-1-spam-filter" class="title-slide slide level1 center">
<h1>Problem 1 — Spam Filter</h1>

</section>
<section id="сюжет" class="slide level2">
<h2>🧩 Сюжет</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Подія</th>
<th style="text-align: center;">Позначення</th>
<th style="text-align: right;">Значення</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Частка спаму</td>
<td style="text-align: center;"><span class="math inline">\(P(S)\)</span></td>
<td style="text-align: right;">0.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">Чутливість (true positive)</td>
<td style="text-align: center;"><span class="math inline">\(P(+\mid S)\)</span></td>
<td style="text-align: right;">0.95</td>
</tr>
<tr class="odd">
<td style="text-align: left;">False positive</td>
<td style="text-align: center;"><span class="math inline">\(P(+\mid \bar{S})\)</span></td>
<td style="text-align: right;">0.08</td>
</tr>
</tbody>
</table>
<p>Запитання:</p>
<ol type="a">
<li><span class="math inline">\(P(+)\)</span> через закон повної ймовірності; (b) <span class="math inline">\(P(S \mid +)\)</span> за Баєсом; (c) перевірити твердження сусіда; (d) очікувані числа з 50 листів.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="" aria-hidden="true" tabindex="-1"></a>prior_s <span class="ot">&lt;-</span> <span class="fl">0.20</span>; prior_ns <span class="ot">&lt;-</span> <span class="fl">0.80</span></span>
<span id="cb47-2"><a href="" aria-hidden="true" tabindex="-1"></a>sens <span class="ot">&lt;-</span> <span class="fl">0.95</span>;    fpr  <span class="ot">&lt;-</span> <span class="fl">0.08</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="p1a-p-закон-повної-ймовірності" class="slide level2">
<h2>✅ P1(a) — <span class="math inline">\(P(+)\)</span> (закон повної ймовірності)</h2>
<p><span class="math display">\[
P(+) = P(+\mid S)P(S) + P(+\mid \bar{S})P(\bar{S})
\]</span></p>
<p><span class="math display">\[
= 0.95 \cdot 0.20 + 0.08 \cdot 0.80
= 0.19 + 0.064 = \boxed{0.254}.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="" aria-hidden="true" tabindex="-1"></a>p_pos <span class="ot">&lt;-</span> sens <span class="sc">*</span> prior_s <span class="sc">+</span> fpr <span class="sc">*</span> prior_ns; p_pos</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.254</code></pre>
</div>
</div>
<aside class="notes">
<p>Закон повної ймовірності — крок 1 для Bayes. Завжди розбиваємо <span class="math inline">\(P(+)\)</span> на дві гілки: «спам + флаг» і «не спам + флаг». Структура: пріор × правдоподібність, додати по всіх класах. Майже та сама схема, що в A9.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p1b-ps-mid-баєс" class="slide level2">
<h2>✅ P1(b) — <span class="math inline">\(P(S \mid +)\)</span> (Баєс)</h2>
<p><span class="math display">\[
P(S \mid +) = \frac{P(+\mid S)\,P(S)}{P(+)}
= \frac{0.95 \cdot 0.20}{0.254}
= \frac{0.19}{0.254}
\]</span></p>
<p><span class="math display">\[
\approx \boxed{0.748}.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="" aria-hidden="true" tabindex="-1"></a>sens <span class="sc">*</span> prior_s <span class="sc">/</span> p_pos</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7480315</code></pre>
</div>
</div>
<p>Тобто ≈ <strong>75%</strong> позначених листів дійсно спам.</p>
<aside class="notes">
<p>Baes у мнемонічній формі: <span class="math inline">\(\text{posterior} = \frac{\text{likelihood} \times \text{prior}}{\text{normalizer}}\)</span>. Тут base rate спаму 20%, але після спостереження «+» вона зросла до 75%. Підкреслити: гарна модель <strong>оновлює</strong> наше переконання.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p1c-оцінка-твердження-сусіда" class="slide level2">
<h2>✅ P1(c) — оцінка твердження сусіда</h2>
<p>Сусід: «Якщо фільтр зловив — точно спам».</p>
<p>Це <strong>хибно</strong>: <span class="math inline">\(P(S \mid +) = 0.748\)</span>, не 1. Один з кожних <strong>4 позначених</strong> листів — насправді <strong>легітимний</strong> (false positive).</p>
<p><strong>Чому:</strong> легітимних листів 4× більше (80% vs 20%), тож навіть 8% помилкових прапорів дають значний абсолютний внесок: 0.064 проти 0.19.</p>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Завжди перевіряйте папку «Спам» — там близько 25% <strong>не</strong> спаму!</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p><span class="math inline">\(P(+ | S) = 0.95\)</span> — це <strong>чутливість</strong> (sensitivity, recall); <span class="math inline">\(P(S | +) = 0.748\)</span> — це <strong>precision</strong>. У ML це різні метрики. Поплутати їх — класична помилка. Якщо клас рідкісний, навіть «гарна» модель дає багато false positives.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p1d-очікувані-числа-з-50-листів" class="slide level2">
<h2>✅ P1(d) — очікувані числа з 50 листів</h2>
<p>Очікувано спаму:</p>
<p><span class="math display">\[
E[\#\text{spam}] = 50 \cdot 0.20 = 10.
\]</span></p>
<p>З них фільтр <strong>правильно</strong> позначає:</p>
<p><span class="math display">\[
E[\#\text{true positive}] = 10 \cdot 0.95 = 9.5 \approx 9{-}10.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="dv">50</span> <span class="sc">*</span> prior_s; <span class="dv">50</span> <span class="sc">*</span> prior_s <span class="sc">*</span> sens</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.5</code></pre>
</div>
</div>
<aside class="notes">
<p>Лінійність сподівання: <span class="math inline">\(E[\text{спам у 50}] = 50 \cdot P(S)\)</span>. Працює навіть якщо листи залежні. Це підготовка до Bin(50, 0.2) у наступних задачах. Підкреслити, що очікуване число — це <strong>середнє</strong> по багатьох днях, не гарантія на конкретний день.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p1-1000-листів" class="slide level2">
<h2>📊 P1 — 1000 листів</h2>

<img data-src=".midterm-mock-slides_files/figure-revealjs/unnamed-chunk-21-1.svg" class="r-stretch"></section></section>
<section>
<section id="problem-2-dogecat" class="title-slide slide level1 center">
<h1>Problem 2 — DOGECAT</h1>

</section>
<section id="сюжет-1" class="slide level2">
<h2>🧩 Сюжет</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Сценарій</th>
<th style="text-align: center;">Rug pull</th>
<th style="text-align: center;">Crabbing</th>
<th style="text-align: center;">To the moon</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Дохідність <span class="math inline">\(r\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-40\%\)</span></td>
<td style="text-align: center;"><span class="math inline">\(+5\%\)</span></td>
<td style="text-align: center;"><span class="math inline">\(+60\%\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(P(R = r)\)</span></td>
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">0.30</td>
<td style="text-align: center;">0.20</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>валідність розподілу; (b) <span class="math inline">\(E[R]\)</span>; (c) <span class="math inline">\(\operatorname{Var}(R), \operatorname{SD}(R)\)</span>; (d) портфель $500.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.40</span>, <span class="fl">0.05</span>, <span class="fl">0.60</span>)</span>
<span id="cb55-2"><a href="" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.50</span>, <span class="fl">0.30</span>, <span class="fl">0.20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="p2a-валідність" class="slide level2">
<h2>✅ P2(a) — валідність</h2>
<p><strong>Невід’ємність:</strong> <span class="math inline">\(0.50, 0.30, 0.20 \ge 0\)</span> ✓</p>
<p><strong>Сума:</strong> <span class="math inline">\(0.50 + 0.30 + 0.20 = 1.00\)</span> ✓</p>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Валідний розподіл.</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Дві умови — як у Section C, але тут дискретний фінансовий сценарій. Корисний момент: усі три ймовірності цілком ненульові, тому всі сценарії «живі». Підготовка до обчислення моментів.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p2b-er" class="slide level2">
<h2>✅ P2(b) — <span class="math inline">\(E[R]\)</span></h2>
<p><span class="math display">\[
E[R] = -0.40 \cdot 0.50 + 0.05 \cdot 0.30 + 0.60 \cdot 0.20
\]</span></p>
<p><span class="math display">\[
= -0.20 + 0.015 + 0.12 = \boxed{-0.065 = -6.5\%}.
\]</span></p>
<p><strong>Висновок:</strong> очікувана дохідність <strong>від’ємна</strong> → це <strong>погана</strong> «інвестиція», в середньому втрачаємо 6.5% капіталу на місяць.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="" aria-hidden="true" tabindex="-1"></a>ER <span class="ot">&lt;-</span> <span class="fu">sum</span>(r <span class="sc">*</span> p); ER</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.065</code></pre>
</div>
</div>
<aside class="notes">
<p>Базова формула: <span class="math inline">\(E[R] = \sum r_i p_i\)</span>. Підкреслити: «найімовірніший» сценарій (rug pull, 50%) ще не визначає <span class="math inline">\(E[R]\)</span> повністю — треба зважити всі. Корисно нагадати про <strong>expected utility</strong> як критерій рішень.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p2c-operatornamevarr-operatornamesdr" class="slide level2">
<h2>✅ P2(c) — <span class="math inline">\(\operatorname{Var}(R), \operatorname{SD}(R)\)</span></h2>
<p><span class="math display">\[
E[R^2] = (-0.40)^2 \cdot 0.50 + (0.05)^2 \cdot 0.30 + (0.60)^2 \cdot 0.20
\]</span></p>
<p><span class="math display">\[
= 0.080 + 0.00075 + 0.072 = 0.15275.
\]</span></p>
<p><span class="math display">\[
\operatorname{Var}(R) = E[R^2] - (E[R])^2 = 0.15275 - 0.004225 = 0.148525.
\]</span></p>
<p><span class="math display">\[
\operatorname{SD}(R) = \sqrt{0.148525} \approx 0.3854 = 38.5\%.
\]</span></p>
<p><strong>SD <span class="math inline">\(\approx 39\%\)</span></strong> — гігантська волатильність порівняно з середнім <span class="math inline">\(-6.5\%\)</span>. Сценарій більше «казино», ніж інвестиція.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="" aria-hidden="true" tabindex="-1"></a>VarR <span class="ot">&lt;-</span> <span class="fu">sum</span>(r<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> p) <span class="sc">-</span> ER<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb58-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">Var =</span> VarR, <span class="at">SD =</span> <span class="fu">sqrt</span>(VarR))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Var        SD 
0.1485250 0.3853894 </code></pre>
</div>
</div>
<aside class="notes">
<p>Формула <span class="math inline">\(\operatorname{Var}(R) = E[R^2] - (E[R])^2\)</span> — основна. Підкреслити, що <span class="math inline">\(E[R^2] \ne (E[R])^2\)</span>, інакше дисперсія = 0. Зв’язок із Sharpe ratio: <span class="math inline">\(E[R] / \operatorname{SD}(R)\)</span> тут від’ємне — інвестори втікають.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p2d-портфель-500" class="slide level2">
<h2>✅ P2(d) — портфель $500</h2>
<p>Портфель <span class="math inline">\(V = 500 \cdot (1 + R)\)</span>, тобто <span class="math inline">\(V = 500 + 500 R\)</span>.</p>
<p><span class="math display">\[
E[V] = 500 + 500 \cdot E[R] = 500 + 500 \cdot (-0.065) = 500 - 32.50 = \boxed{\$467.50}.
\]</span></p>
<p><span class="math display">\[
\operatorname{SD}(V) = 500 \cdot \operatorname{SD}(R) \approx 500 \cdot 0.3854 \approx \boxed{\$192.7}.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="" aria-hidden="true" tabindex="-1"></a>EV <span class="ot">&lt;-</span> <span class="dv">500</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">+</span> ER); SDV <span class="ot">&lt;-</span> <span class="dv">500</span> <span class="sc">*</span> <span class="fu">sqrt</span>(VarR)</span>
<span id="cb60-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">E_V =</span> EV, <span class="at">SD_V =</span> SDV)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     E_V     SD_V 
467.5000 192.6947 </code></pre>
</div>
</div>
<aside class="notes">
<p>Лінійні перетворення моментів: <span class="math inline">\(E[aR + b] = aE[R] + b\)</span>, <span class="math inline">\(\operatorname{Var}(aR + b) = a^2 \operatorname{Var}(R)\)</span>, <span class="math inline">\(\operatorname{SD}(aR + b) = |a| \operatorname{SD}(R)\)</span>. Аналог A2, тільки на практиці. Корисно зробити паралель.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p2-розподіл-портфеля" class="slide level2">
<h2>📊 P2 — розподіл портфеля</h2>

<img data-src=".midterm-mock-slides_files/figure-revealjs/unnamed-chunk-26-1.svg" class="r-stretch"></section></section>
<section>
<section id="problem-3-sleepy-barista" class="title-slide slide level1 center">
<h1>Problem 3 — Sleepy Barista</h1>

</section>
<section id="сюжет-2" class="slide level2">
<h2>🧩 Сюжет</h2>
<p><span class="math inline">\(X \sim \mathrm{Binomial}(n = 10, p = 0.12)\)</span> — к-сть неправильних замовлень.</p>
<ol type="a">
<li><span class="math inline">\(P(X = 0)\)</span>; (b) <span class="math inline">\(P(X \ge 2)\)</span>; (c) <span class="math inline">\(E[X], \operatorname{Var}(X)\)</span>; (d) <span class="math inline">\(P(X &gt; 2)\)</span>.</li>
</ol>
</section>
<section id="p3a-px-0" class="slide level2">
<h2>✅ P3(a) — <span class="math inline">\(P(X = 0)\)</span></h2>
<p><span class="math display">\[
P(X = 0) = \binom{10}{0}(0.12)^0(0.88)^{10} = 0.88^{10}.
\]</span></p>
<p><span class="math display">\[
0.88^{10} \approx \boxed{0.2785}.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="fl">0.12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.278501</code></pre>
</div>
</div>
<aside class="notes">
<p>Найпростіший випадок Binomial: всі провали. <span class="math inline">\(P(X = 0) = (1-p)^n\)</span>. Студенти часто пишуть <span class="math inline">\(\binom{n}{0} \cdot p^0\)</span>, що = 1, забуваючи <span class="math inline">\(0! = 1\)</span>. Швидше — одразу <span class="math inline">\((1-p)^n\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p3b-px-ge-2-через-доповнення" class="slide level2">
<h2>✅ P3(b) — <span class="math inline">\(P(X \ge 2)\)</span> через доповнення</h2>
<p><span class="math display">\[
P(X \ge 2) = 1 - P(X = 0) - P(X = 1).
\]</span></p>
<p><span class="math display">\[
P(X = 1) = \binom{10}{1}(0.12)(0.88)^9 = 10 \cdot 0.12 \cdot 0.88^9
\approx 0.3798.
\]</span></p>
<p><span class="math display">\[
P(X \ge 2) = 1 - 0.2785 - 0.3798 \approx \boxed{0.3417}.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pbinom</span>(<span class="dv">1</span>, <span class="dv">10</span>, <span class="fl">0.12</span>)        <span class="co"># 0.3417</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.341725</code></pre>
</div>
</div>
<aside class="notes">
<p>Стратегія «доповнення»: коли треба <span class="math inline">\(P(X \ge k)\)</span> і <span class="math inline">\(k\)</span> мале — рахуй <span class="math inline">\(1 - P(X \le k-1)\)</span>. У R: <code>1 - pbinom(k-1, n, p)</code> або <code>pbinom(k-1, n, p, lower.tail = FALSE)</code>. Запам’ятати: <code>pbinom</code> приймає <strong>верхню межу</strong> <span class="math inline">\(\le\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p3c-ex-operatornamevarx" class="slide level2">
<h2>✅ P3(c) — <span class="math inline">\(E[X], \operatorname{Var}(X)\)</span></h2>
<p><span class="math display">\[
E[X] = np = 10 \cdot 0.12 = 1.2.
\]</span></p>
<p><span class="math display">\[
\operatorname{Var}(X) = np(1 - p) = 10 \cdot 0.12 \cdot 0.88 = 1.056.
\]</span></p>
<p><strong>Інтерпретація</strong> <span class="math inline">\(E[X]\)</span>: у <strong>середньому</strong> за зміну з 10 замовлень буде <strong>1.2 неправильних</strong> — приблизно одне.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">E_X =</span> <span class="dv">10</span> <span class="sc">*</span> <span class="fl">0.12</span>, <span class="at">Var_X =</span> <span class="dv">10</span> <span class="sc">*</span> <span class="fl">0.12</span> <span class="sc">*</span> <span class="fl">0.88</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  E_X Var_X 
1.200 1.056 </code></pre>
</div>
</div>
<aside class="notes">
<p>Формули <span class="math inline">\(np\)</span> і <span class="math inline">\(np(1-p)\)</span> — святе для Binomial. Підкреслити: <span class="math inline">\(E[X]\)</span> може бути нецілим (1.2), хоч <span class="math inline">\(X\)</span> завжди ціле. Це особливість сподівання — воно «середнє по всіх можливих світах».</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p3d-px-2-втручання" class="slide level2">
<h2>✅ P3(d) — <span class="math inline">\(P(X &gt; 2)\)</span> (втручання)</h2>
<p><span class="math display">\[
P(X &gt; 2) = P(X \ge 3) = 1 - P(X \le 2).
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pbinom</span>(<span class="dv">2</span>, <span class="dv">10</span>, <span class="fl">0.12</span>)        <span class="co"># 0.1087</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1086818</code></pre>
</div>
</div>
<p><span class="math display">\[
\approx \boxed{0.1087 = 10.87\%}.
\]</span></p>
<p>Менеджер втручатиметься приблизно у <strong>1 з 9</strong> змін.</p>
<aside class="notes">
<p>Уважно: <span class="math inline">\(P(X &gt; 2) = P(X \ge 3)\)</span> бо <span class="math inline">\(X\)</span> ціле. Тому <code>1 - pbinom(2, ...)</code>, а НЕ <code>1 - pbinom(3, ...)</code>. Це найчастіша помилка у задачах із Binomial: плутанина <span class="math inline">\(&gt;\)</span> vs <span class="math inline">\(\ge\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="problem-4-normal-streams" class="title-slide slide level1 center">
<h1>Problem 4 — Normal: Streams</h1>

</section>
<section id="сюжет-3" class="slide level2">
<h2>🧩 Сюжет</h2>
<p><span class="math inline">\(X \sim \mathcal{N}(\mu = 12\,000, \sigma = 3\,200)\)</span>.</p>
<ol type="a">
<li><span class="math inline">\(P(X &gt; 17\,000)\)</span>; (b) 90-й перцентиль (<span class="math inline">\(z_{0.9} \approx 1.28\)</span>); (c) <span class="math inline">\(P(8\,000 &lt; X &lt; 15\,200)\)</span>.</li>
</ol>
</section>
<section id="p4a-px-17000" class="slide level2">
<h2>✅ P4(a) — <span class="math inline">\(P(X &gt; 17\,000)\)</span></h2>
<p><span class="math display">\[
z = \frac{17\,000 - 12\,000}{3\,200} = \frac{5\,000}{3\,200} = 1.5625.
\]</span></p>
<p><span class="math display">\[
P(X &gt; 17\,000) = 1 - \Phi(1.5625) \approx 1 - 0.9410 = \boxed{0.0590}.
\]</span></p>
<p>≈ <strong>5.9%</strong> пісень отримують понад 17 тис. стрімів.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">17000</span>, <span class="dv">12000</span>, <span class="dv">3200</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05908512</code></pre>
</div>
</div>
<aside class="notes">
<p>Шаблон <span class="math inline">\(z\)</span>-перетворення: <span class="math inline">\(z = (x - \mu) / \sigma\)</span>. Потім дивимось у таблицю <span class="math inline">\(\Phi(z)\)</span> або використовуємо R. Корисно нагадати: <span class="math inline">\(\Phi(1.56) \approx 0.94\)</span> — типове значення з таблиці.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p4b-90-й-перцентиль" class="slide level2">
<h2>✅ P4(b) — 90-й перцентиль</h2>
<p><span class="math display">\[
x_{0.9} = \mu + z_{0.9} \cdot \sigma = 12\,000 + 1.28 \cdot 3\,200
\]</span></p>
<p><span class="math display">\[
= 12\,000 + 4\,096 = \boxed{16\,096}.
\]</span></p>
<p>10% найкращих пісень отримують <strong>щонайменше 16 100 стрімів</strong> на день.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.90</span>, <span class="dv">12000</span>, <span class="dv">3200</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16100.97</code></pre>
</div>
</div>
<aside class="notes">
<p>Обернений шлях: <span class="math inline">\(x = \mu + z \cdot \sigma\)</span>. Ключові квантилі для запам’ятовування: <span class="math inline">\(z_{0.90} \approx 1.28\)</span>, <span class="math inline">\(z_{0.95} \approx 1.645\)</span>, <span class="math inline">\(z_{0.975} \approx 1.96\)</span>. Це фундамент довірчих інтервалів у Stat-2.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p4c-p8000-x-15200" class="slide level2">
<h2>✅ P4(c) — <span class="math inline">\(P(8\,000 &lt; X &lt; 15\,200)\)</span></h2>
<p><span class="math display">\[
z_1 = \frac{8\,000 - 12\,000}{3\,200} = -1.25, \quad z_2 = \frac{15\,200 - 12\,000}{3\,200} = 1.
\]</span></p>
<p><span class="math display">\[
P = \Phi(1) - \Phi(-1.25) = 0.8413 - 0.1056 = \boxed{0.7357}.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">15200</span>, <span class="dv">12000</span>, <span class="dv">3200</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">8000</span>, <span class="dv">12000</span>, <span class="dv">3200</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.735695</code></pre>
</div>
</div>
<aside class="notes">
<p>Двосторонній інтервал: <span class="math inline">\(\Phi(z_2) - \Phi(z_1)\)</span>. Корисна перевірка: тут <span class="math inline">\(z_1 = -1.25, z_2 = +1\)</span> — асиметричні, тому це <strong>не</strong> правило <span class="math inline">\(\mu \pm \sigma\)</span> і не <span class="math inline">\(\mu \pm 2\sigma\)</span>. Студенти часто намагаються відразу застосувати готове правило.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p4-візуалізація" class="slide level2">
<h2>📊 P4 — візуалізація</h2>

<img data-src=".midterm-mock-slides_files/figure-revealjs/unnamed-chunk-34-1.svg" class="r-stretch"></section></section>
<section>
<section id="problem-5-exponential-delivery" class="title-slide slide level1 center">
<h1>Problem 5 — Exponential: Delivery</h1>

</section>
<section id="сюжет-4" class="slide level2">
<h2>🧩 Сюжет</h2>
<p><span class="math inline">\(T \sim \mathrm{Exp}(\lambda)\)</span>, <span class="math inline">\(E[T] = 1/\lambda = 20\)</span> хв, тобто <span class="math inline">\(\lambda = 0.05\)</span>.</p>
<ol type="a">
<li><span class="math inline">\(E[T], \operatorname{Var}(T)\)</span>; (b) <span class="math inline">\(P(T &gt; 30)\)</span>; (c) <span class="math inline">\(P(10 &lt; T &lt; 40)\)</span>; (d) memoryless.</li>
</ol>
</section>
<section id="p5a-et-operatornamevart" class="slide level2">
<h2>✅ P5(a) — <span class="math inline">\(E[T], \operatorname{Var}(T)\)</span></h2>
<p><span class="math display">\[
E[T] = \frac{1}{\lambda} = 20 \text{ хв}.
\]</span></p>
<p><span class="math display">\[
\operatorname{Var}(T) = \frac{1}{\lambda^2} = 400 \text{ хв}^2, \quad \operatorname{SD}(T) = 20 \text{ хв}.
\]</span></p>
<p>Цікаво: для Exp <strong><span class="math inline">\(\operatorname{SD} = E[T]\)</span></strong> — це характерна риса розподілу.</p>
<aside class="notes">
<p>Запам’ятати: для Exp параметр <span class="math inline">\(\lambda\)</span> — це <strong>інтенсивність</strong> (events per unit time), а <span class="math inline">\(1/\lambda\)</span> — <strong>середній час між подіями</strong>. Часто плутають: задано «20 хв» → <span class="math inline">\(\lambda = 1/20\)</span>, а не <span class="math inline">\(\lambda = 20\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p5b-pt-30" class="slide level2">
<h2>✅ P5(b) — <span class="math inline">\(P(T &gt; 30)\)</span></h2>
<p><span class="math display">\[
P(T &gt; 30) = e^{-\lambda \cdot 30} = e^{-30/20} = e^{-1.5}
\]</span></p>
<p><span class="math display">\[
\approx \boxed{0.2231}.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pexp</span>(<span class="dv">30</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>)        <span class="co"># 0.2231</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2231302</code></pre>
</div>
</div>
<aside class="notes">
<p>Survivor function <span class="math inline">\(e^{-\lambda t}\)</span> дає миттєву відповідь без R: <span class="math inline">\(e^{-1.5} \approx 0.22\)</span>. Корисний трюк для іспиту, коли калькулятор не дозволено. Зв’язок із D3(a) — те саме обчислення.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p5c-p10-t-40" class="slide level2">
<h2>✅ P5(c) — <span class="math inline">\(P(10 &lt; T &lt; 40)\)</span></h2>
<p><span class="math display">\[
P(10 &lt; T &lt; 40) = e^{-10/20} - e^{-40/20} = e^{-0.5} - e^{-2}
\]</span></p>
<p><span class="math display">\[
\approx 0.6065 - 0.1353 = \boxed{0.4712}.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">pexp</span>(<span class="dv">40</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>) <span class="sc">-</span> <span class="fu">pexp</span>(<span class="dv">10</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4711954</code></pre>
</div>
</div>
<aside class="notes">
<p>Через survivors: <span class="math inline">\(S(10) - S(40) = e^{-0.5} - e^{-2}\)</span>. Підкреслити: однаково, чи писати через <code>pexp</code> (CDF), чи через <span class="math inline">\(1 - F\)</span>. Це додає впевненості при перевірці.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p5d-memoryless-property" class="slide level2">
<h2>✅ P5(d) — memoryless property</h2>
<p><span class="math display">\[
P(T &gt; 30 \mid T &gt; 20) = P(T &gt; 10) = e^{-10/20} = e^{-0.5} \approx 0.6065.
\]</span></p>
<p><strong>Інтерпретація:</strong> факт того, що студент уже прочекав 20 хв, <strong>не дає жодної інформації</strong> про те, скільки ще доведеться чекати. Розподіл «забуває» минуле.</p>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Чекання попередніх 20 хв <strong>не наближає</strong> доставку — інтуїція «зараз має приїхати» хибна для Exp.</p>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Перевірка: ці дві мають бути рівні</span></span>
<span id="cb80-2"><a href="" aria-hidden="true" tabindex="-1"></a>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pexp</span>(<span class="dv">30</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>)) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pexp</span>(<span class="dv">20</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>))   <span class="co"># P(T&gt;30 | T&gt;20)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6065307</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pexp</span>(<span class="dv">10</span>, <span class="dv">1</span><span class="sc">/</span><span class="dv">20</span>)                            <span class="co"># P(T&gt;10)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6065307</code></pre>
</div>
</div>
<aside class="notes">
<p>Ключовий слайд про Exp. Підкреслити: memoryless — це <strong>функціональне рівняння</strong>, тільки Exp (серед неперервних) йому задовольняє. Аналог у дискретному світі — geometric. Розгорнути на дошці: <span class="math inline">\(P(T &gt; s+t)/P(T&gt;s) = P(T&gt;t)\)</span> через експоненту.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="problem-6-markov-inequality" class="title-slide slide level1 center">
<h1>Problem 6 — Markov Inequality</h1>

</section>
<section id="сюжет-5" class="slide level2">
<h2>🧩 Сюжет</h2>
<p><span class="math inline">\(T \ge 0\)</span> — чайові кур’єра (UAH). Відомо лише <span class="math inline">\(E[T] = 180\)</span>.</p>
<ol type="a">
<li>сформулювати Маркова; знайти верхню межу для <span class="math inline">\(P(T \ge 900)\)</span>;</li>
<li>перевірити «не більше 15% шансу заробити &gt; 1200»;</li>
<li>описати розподіл, на якому межа Маркова <strong>точна</strong>.</li>
</ol>
</section>
<section id="p6a-маркова" class="slide level2">
<h2>✅ P6(a) — Маркова</h2>
<p><strong>Умови:</strong> <span class="math inline">\(X \ge 0\)</span>, <span class="math inline">\(E[X] &lt; \infty\)</span>, <span class="math inline">\(a &gt; 0\)</span>.</p>
<p><strong>Формула:</strong></p>
<p><span class="math display">\[
P(X \ge a) \le \frac{E[X]}{a}.
\]</span></p>
<p>Застосування при <span class="math inline">\(a = 900\)</span>:</p>
<p><span class="math display">\[
P(T \ge 900) \le \frac{180}{900} = 0.20 = \boxed{20\%}.
\]</span></p>
<aside class="notes">
<p>Завжди починати з умов: <span class="math inline">\(X \ge 0\)</span>, <span class="math inline">\(E[X] &lt; \infty\)</span>. Маркова — це <strong>верхня межа</strong>, не точне значення. Підкреслити: знак <span class="math inline">\(\le\)</span>, не <span class="math inline">\(=\)</span>. Це часта помилка — писати «дорівнює 20%».</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p6b-твердження-друга" class="slide level2">
<h2>✅ P6(b) — твердження друга</h2>
<p>Друг каже: «не більше 15% шансу <span class="math inline">\(T &gt; 1200\)</span>».</p>
<p>Маркова дає:</p>
<p><span class="math display">\[
P(T \ge 1200) \le \frac{180}{1200} = 0.15 = 15\%.
\]</span></p>
<p>Маркова не доводить, що ймовірність <strong>дорівнює</strong> 15% — це лише <strong>верхня межа</strong>. Тобто 15% — це <strong>найгірший випадок</strong>. Твердження друга — <strong>правильне за змістом</strong> (як верхня оцінка), і <strong>збігається</strong> з границею Маркова, тож «not too strong» — він використав саме Markov bound.</p>
<div class="fragment">
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Реальна ймовірність може бути значно меншою (наприклад, 5% або навіть 0%), але <strong>точно не вище 15%</strong>.</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Тонкий момент: твердження «не більше 15%» — це САМЕ те, що каже Маркова. Тобто друг не помилився, але й нічого нового не сказав. На іспиті розмежувати «істина» vs «строге твердження».</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p6c-коли-маркова-точна" class="slide level2">
<h2>✅ P6(c) — коли Маркова точна</h2>
<p>Межа досягається, коли вся маса зосереджена в <strong>двох точках</strong>: 0 та <span class="math inline">\(a\)</span>.</p>
<p><strong>Конкретно:</strong></p>
<p><span class="math display">\[
P(T = 900) = \frac{180}{900} = 0.20, \quad P(T = 0) = 0.80.
\]</span></p>
<p>Перевірка: <span class="math inline">\(E[T] = 0 \cdot 0.8 + 900 \cdot 0.2 = 180\)</span> ✓, <span class="math inline">\(P(T \ge 900) = 0.20\)</span> — точно межа.</p>
<p><strong>Урок:</strong> Маркова <strong>груба</strong> для розподілів із багатою структурою, але <strong>точна</strong> для двозначкових розподілів. Тому її майже завжди можна суттєво поліпшити, якщо знати <span class="math inline">\(\operatorname{Var}\)</span> (нерівність Чебишева).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Простий приклад: Bernoulli-подібна T з масами в 0 і 900</span></span>
<span id="cb84-2"><a href="" aria-hidden="true" tabindex="-1"></a>T_vals <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">900</span>); T_p <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.8</span>, <span class="fl">0.2</span>)</span>
<span id="cb84-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(T_vals <span class="sc">*</span> T_p)       <span class="co"># E[T] = 180</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 180</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(T_p[T_vals <span class="sc">&gt;=</span> <span class="dv">900</span>]) <span class="co"># P(T &gt;= 900) = 0.20 — точно як Markov</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2</code></pre>
</div>
</div>
<aside class="notes">
<p>Цей слайд про <strong>тіснотну</strong> межі. Маркова досягається лише на «екстремальному» розподілі — двозначковому. Усі реалістичні розподіли роблять межу набагато гіршою. Зв’язок із B7 і A4.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="problem-7-clt-sleep-hours" class="title-slide slide level1 center">
<h1>Problem 7 — CLT: Sleep Hours</h1>

</section>
<section id="сюжет-6" class="slide level2">
<h2>🧩 Сюжет</h2>
<p><span class="math inline">\(\mu = 5.8\)</span> год, <span class="math inline">\(\sigma = 1.2\)</span> год, <span class="math inline">\(n = 36\)</span>, розподіл невідомий.</p>
<ol type="a">
<li>розподіл <span class="math inline">\(\bar X\)</span>, теорема, <span class="math inline">\(E[\bar X], \operatorname{Var}(\bar X)\)</span>;</li>
<li><span class="math inline">\(P(\bar X &lt; 5.5)\)</span>;</li>
<li><span class="math inline">\(c\)</span>: <span class="math inline">\(P(\bar X &gt; c) = 0.05\)</span> (<span class="math inline">\(z_{0.95} \approx 1.645\)</span>).</li>
</ol>
</section>
<section id="p7a-розподіл-bar-x-clt" class="slide level2">
<h2>✅ P7(a) — розподіл <span class="math inline">\(\bar X\)</span> (CLT)</h2>
<p>За <strong>Центральною граничною теоремою</strong> (бо <span class="math inline">\(n = 36 \ge 30\)</span>):</p>
<p><span class="math display">\[
\bar X \overset{\text{прибл.}}{\sim} \mathcal{N}\!\left(\mu,\ \frac{\sigma^2}{n}\right).
\]</span></p>
<p><span class="math display">\[
E[\bar X] = \mu = 5.8,
\]</span></p>
<p><span class="math display">\[
\operatorname{Var}(\bar X) = \frac{\sigma^2}{n} = \frac{1.44}{36} = 0.04, \quad \operatorname{SE}(\bar X) = 0.2.
\]</span></p>
<p><span class="math display">\[
\boxed{\bar X \overset{\text{прибл.}}{\sim} \mathcal{N}(5.8,\ 0.2^2)}.
\]</span></p>
<aside class="notes">
<p>Дуже важливий слайд. Дві ключові ідеї: (1) <strong>розподіл невідомий</strong>, але завдяки CLT нам байдуже; (2) <strong>дисперсія середнього у <span class="math inline">\(n\)</span> разів МЕНША</strong> за дисперсію окремого спостереження. Зв’язок із A7, B5.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p7b-pbar-x-5.5" class="slide level2">
<h2>✅ P7(b) — <span class="math inline">\(P(\bar X &lt; 5.5)\)</span></h2>
<p><span class="math display">\[
z = \frac{5.5 - 5.8}{0.2} = -1.5.
\]</span></p>
<p><span class="math display">\[
P(\bar X &lt; 5.5) = \Phi(-1.5) = 1 - 0.9332 = \boxed{0.0668}.
\]</span></p>
<p>≈ <strong>6.7%</strong> ймовірність того, що середній сон у виборі з 36 студентів <strong>нижче 5.5 год</strong>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">5.5</span>, <span class="at">mean =</span> <span class="fl">5.8</span>, <span class="at">sd =</span> <span class="fl">0.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0668072</code></pre>
</div>
</div>
<aside class="notes">
<p>Використовуємо SE = 0.2, не <span class="math inline">\(\sigma\)</span> = 1.2. Це найчастіша помилка в CLT-задачах: підставити <span class="math inline">\(\sigma\)</span> замість <span class="math inline">\(\sigma/\sqrt{n}\)</span>. Підкреслити: для <span class="math inline">\(\bar X\)</span> масштаб менший — тому навіть «помірне» відхилення <span class="math inline">\(-0.3\)</span> дає <span class="math inline">\(z = -1.5\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p7c-поріг-c-для-верхніх-5" class="slide level2">
<h2>✅ P7(c) — поріг <span class="math inline">\(c\)</span> для верхніх 5%</h2>
<p><span class="math display">\[
c = \mu + z_{0.95} \cdot \operatorname{SE} = 5.8 + 1.645 \cdot 0.2
\]</span></p>
<p><span class="math display">\[
= 5.8 + 0.329 = \boxed{6.129}.
\]</span></p>
<p>Інтерпретація: лише в 5% вибірок із 36 студентів середній сон перевищить <strong>6.13 год</strong>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.95</span>, <span class="at">mean =</span> <span class="fl">5.8</span>, <span class="at">sd =</span> <span class="fl">0.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.128971</code></pre>
</div>
</div>
<aside class="notes">
<p>Шаблон: <span class="math inline">\(c = \mu + z_{1-\alpha} \cdot \text{SE}\)</span>. Це підготовка до довірчих інтервалів: <span class="math inline">\(\bar x \pm z_{1-\alpha/2} \cdot \text{SE}\)</span>. Запам’ятати <span class="math inline">\(z_{0.95} = 1.645\)</span> і <span class="math inline">\(z_{0.975} = 1.96\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="problem-8-joint-xy-study-vs-game" class="title-slide slide level1 center">
<h1>Problem 8 — Joint XY: Study vs Game</h1>

</section>
<section id="сюжет-7" class="slide level2">
<h2>🧩 Сюжет</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(X \backslash Y\)</span></th>
<th style="text-align: center;"><span class="math inline">\(Y=0\)</span></th>
<th style="text-align: center;"><span class="math inline">\(Y=2\)</span></th>
<th style="text-align: center;"><span class="math inline">\(Y=4\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(X = 1\)</span></td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.15</td>
<td style="text-align: center;">0.10</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(X = 3\)</span></td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.15</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(X = 6\)</span></td>
<td style="text-align: center;">0.15</td>
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0.00</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="" aria-hidden="true" tabindex="-1"></a>joint <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.15</span>, <span class="fl">0.10</span>,</span>
<span id="cb92-2"><a href="" aria-hidden="true" tabindex="-1"></a>                  <span class="fl">0.10</span>, <span class="fl">0.25</span>, <span class="fl">0.15</span>,</span>
<span id="cb92-3"><a href="" aria-hidden="true" tabindex="-1"></a>                  <span class="fl">0.15</span>, <span class="fl">0.05</span>, <span class="fl">0.00</span>),</span>
<span id="cb92-4"><a href="" aria-hidden="true" tabindex="-1"></a>                <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>,</span>
<span id="cb92-5"><a href="" aria-hidden="true" tabindex="-1"></a>                <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="at">X =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">6</span>), <span class="at">Y =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">4</span>)))</span>
<span id="cb92-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(joint)        <span class="co"># перевірка нормування</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
</section>
<section id="p8a-маргінали" class="slide level2">
<h2>✅ P8(a) — маргінали</h2>
<p><strong>За рядками (<span class="math inline">\(X\)</span>):</strong></p>
<p><span class="math display">\[
P(X=1) = 0.30, \quad P(X=3) = 0.50, \quad P(X=6) = 0.20.
\]</span></p>
<p><strong>За стовпцями (<span class="math inline">\(Y\)</span>):</strong></p>
<p><span class="math display">\[
P(Y=0) = 0.30, \quad P(Y=2) = 0.45, \quad P(Y=4) = 0.25.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="" aria-hidden="true" tabindex="-1"></a>px <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(joint); py <span class="ot">&lt;-</span> <span class="fu">colSums</span>(joint)</span>
<span id="cb94-2"><a href="" aria-hidden="true" tabindex="-1"></a>px; py</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  1   3   6 
0.3 0.5 0.2 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   0    2    4 
0.30 0.45 0.25 </code></pre>
</div>
</div>
<aside class="notes">
<p>Маргінали = суми рядків/стовпців. Завжди першим ділом — отримати <span class="math inline">\(p_X, p_Y\)</span> зі спільної. Перевірка: суми обох мають = 1. У R: <code>rowSums</code> для <span class="math inline">\(p_X\)</span>, <code>colSums</code> для <span class="math inline">\(p_Y\)</span>.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p8b-ex-ey" class="slide level2">
<h2>✅ P8(b) — <span class="math inline">\(E[X], E[Y]\)</span></h2>
<p><span class="math display">\[
E[X] = 1 \cdot 0.30 + 3 \cdot 0.50 + 6 \cdot 0.20 = 0.3 + 1.5 + 1.2 = 3.0.
\]</span></p>
<p><span class="math display">\[
E[Y] = 0 \cdot 0.30 + 2 \cdot 0.45 + 4 \cdot 0.25 = 0 + 0.90 + 1.00 = 1.9.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="" aria-hidden="true" tabindex="-1"></a>EX <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">as.numeric</span>(<span class="fu">names</span>(px)) <span class="sc">*</span> px)</span>
<span id="cb97-2"><a href="" aria-hidden="true" tabindex="-1"></a>EY <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">as.numeric</span>(<span class="fu">names</span>(py)) <span class="sc">*</span> py)</span>
<span id="cb97-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">EX =</span> EX, <span class="at">EY =</span> EY)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> EX  EY 
3.0 1.9 </code></pre>
</div>
</div>
<aside class="notes">
<p><span class="math inline">\(E[X]\)</span> обчислюється з <strong>маргіналу</strong> <span class="math inline">\(p_X\)</span> — не з усієї матриці. Тобто значення <span class="math inline">\(Y\)</span> не впливає на <span class="math inline">\(E[X]\)</span> (і навпаки). Це базовий тест: чи студент розуміє, що сподівання — характеристика однієї змінної.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p8c-незалежність" class="slide level2">
<h2>✅ P8(c) — незалежність?</h2>
<p>Перевіримо в одній клітинці: чи <span class="math inline">\(P(X=1, Y=0) = P(X=1) P(Y=0)\)</span>?</p>
<p><span class="math display">\[
P(X=1)P(Y=0) = 0.30 \cdot 0.30 = 0.09.
\]</span></p>
<p><span class="math display">\[
P(X=1, Y=0) = 0.05 \neq 0.09.
\]</span></p>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>Не незалежні.</strong> Інтуїтивно: хто вчиться більше, той менше грає — клітинка (<span class="math inline">\(X=6, Y=4\)</span>) має ймовірність <strong>0</strong>.</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Тест на незалежність: <span class="math inline">\(P(X, Y) = P(X) \cdot P(Y)\)</span> <strong>для кожної</strong> клітинки. Достатньо знайти <strong>одну</strong> клітинку, де це порушено — і вже не незалежні. Контрприклад зазвичай у нулях, як тут.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p8d-operatornamecovx-y" class="slide level2">
<h2>✅ P8(d) — <span class="math inline">\(\operatorname{Cov}(X, Y)\)</span></h2>
<p><span class="math display">\[
E[XY] = \sum_{x, y} xy \cdot P(x, y).
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="" aria-hidden="true" tabindex="-1"></a>xs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">6</span>); ys <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">4</span>)</span>
<span id="cb99-2"><a href="" aria-hidden="true" tabindex="-1"></a>EXY <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">outer</span>(xs, ys) <span class="sc">*</span> joint)</span>
<span id="cb99-3"><a href="" aria-hidden="true" tabindex="-1"></a>EXY                                 <span class="co"># 4.9</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.6</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="" aria-hidden="true" tabindex="-1"></a>Cov <span class="ot">&lt;-</span> EXY <span class="sc">-</span> EX <span class="sc">*</span> EY</span>
<span id="cb101-2"><a href="" aria-hidden="true" tabindex="-1"></a>Cov                                 <span class="co"># -0.80</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.1</code></pre>
</div>
</div>
<p><span class="math display">\[
E[XY] = 4.9, \quad \operatorname{Cov}(X, Y) = 4.9 - 3.0 \cdot 1.9 = 4.9 - 5.7 = \boxed{-0.80}.
\]</span></p>
<p><strong>Знак:</strong> від’ємний → ті, хто більше вчаться, грають <strong>менше</strong> (та навпаки). Має економічний сенс: час обмежений.</p>
<aside class="notes">
<p>Формула <span class="math inline">\(\operatorname{Cov} = E[XY] - E[X]E[Y]\)</span> — стандартна. <span class="math inline">\(E[XY]\)</span> = сума <span class="math inline">\(x_i y_j p_{ij}\)</span> по всіх клітинках. Це <strong>подвійна</strong> сума, на відміну від маргінальних. Зв’язок із B2: <span class="math inline">\(\operatorname{Cov} \ne 0\)</span> → залежні (а назад — ні).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p8-теплова-мапа" class="slide level2">
<h2>📊 P8 — теплова мапа</h2>

<img data-src=".midterm-mock-slides_files/figure-revealjs/unnamed-chunk-45-1.svg" class="r-stretch"></section></section>
<section>
<section id="problem-9-sample-covariance-correlation" class="title-slide slide level1 center">
<h1>Problem 9 — Sample Covariance &amp; Correlation</h1>

</section>
<section id="сюжет-8" class="slide level2">
<h2>🧩 Сюжет</h2>
<p><span class="math inline">\(n = 25\)</span>, <span class="math inline">\(\bar X = 2.8\)</span> кав/день, <span class="math inline">\(\bar Y = 64.0\)</span> балів, <span class="math inline">\(S_X = 1.1\)</span>, <span class="math inline">\(S_Y = 12.5\)</span>, <span class="math inline">\(\sum_{i=1}^{25} (X_i - \bar X)(Y_i - \bar Y) = 154.0\)</span>.</p>
<ol type="a">
<li><span class="math inline">\(S_{XY}\)</span>; (b) <span class="math inline">\(r_{XY}\)</span>; (c) інтерпретація; (d) каузальність.</li>
</ol>
</section>
<section id="p9a-sample-covariance" class="slide level2">
<h2>✅ P9(a) — sample covariance</h2>
<p><span class="math display">\[
S_{XY} = \frac{1}{n - 1}\sum_{i=1}^n (X_i - \bar X)(Y_i - \bar Y)
= \frac{154.0}{24}
\]</span></p>
<p><span class="math display">\[
\approx \boxed{6.4167}.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="" aria-hidden="true" tabindex="-1"></a>S_XY <span class="ot">&lt;-</span> <span class="dv">154</span> <span class="sc">/</span> (<span class="dv">25</span> <span class="sc">-</span> <span class="dv">1</span>); S_XY</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.416667</code></pre>
</div>
</div>
<aside class="notes">
<p>Важливо: ділимо на <span class="math inline">\(n - 1\)</span>, не <span class="math inline">\(n\)</span> (Bessel’s correction). Це робить оцінку <strong>незміщеною</strong>. У R: <code>cov()</code> за замовчуванням використовує <span class="math inline">\(n - 1\)</span>. Студенти часто плутають із дисперсією популяції.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p9b-sample-correlation" class="slide level2">
<h2>✅ P9(b) — sample correlation</h2>
<p><span class="math display">\[
r_{XY} = \frac{S_{XY}}{S_X \cdot S_Y} = \frac{6.4167}{1.1 \cdot 12.5} = \frac{6.4167}{13.75}
\]</span></p>
<p><span class="math display">\[
\approx \boxed{0.467}.
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="" aria-hidden="true" tabindex="-1"></a>r_XY <span class="ot">&lt;-</span> S_XY <span class="sc">/</span> (<span class="fl">1.1</span> <span class="sc">*</span> <span class="fl">12.5</span>); r_XY</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4666667</code></pre>
</div>
</div>
<aside class="notes">
<p><span class="math inline">\(r\)</span> — це нормалізована коваріація. Знаменник <span class="math inline">\(S_X \cdot S_Y\)</span> робить її <strong>безрозмірною</strong> і обмеженою в <span class="math inline">\([-1, 1]\)</span>. На відміну від <span class="math inline">\(S_{XY}\)</span> (6.4 у дивних одиницях), <span class="math inline">\(r\)</span> можна порівнювати між різними дослідженнями.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p9c-інтерпретація" class="slide level2">
<h2>✅ P9(c) — інтерпретація</h2>
<p><strong>Знак:</strong> додатній — більше кави корелює з вищою само-оцінкою продуктивності.</p>
<p><strong>Величина:</strong> <span class="math inline">\(|r| \approx 0.47\)</span> — <strong>помірний</strong> лінійний зв’язок (не слабкий, не сильний).</p>
<p>Категоризація (умовна):</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(|r|\)</span></th>
<th style="text-align: left;">Сила</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.0–0.2</td>
<td style="text-align: left;">дуже слабкий</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.2–0.4</td>
<td style="text-align: left;">слабкий</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>0.4–0.6</strong></td>
<td style="text-align: left;"><strong>помірний</strong> ← наш випадок</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.6–0.8</td>
<td style="text-align: left;">сильний</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.8–1.0</td>
<td style="text-align: left;">дуже сильний</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Шкала умовна — у різних науках різні стандарти. У психології 0.3 вже вважається сильним, у фізиці 0.95 — слабкий. Підкреслити: завжди питай контекст. Зв’язок із A8 (порівняння <span class="math inline">\(|\rho|\)</span>).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p9d-кореляція-причинність" class="slide level2">
<h2>✅ P9(d) — кореляція ≠ причинність</h2>
<p>Студент: «Більше кави <strong>спричиняє</strong> вищу продуктивність».</p>
<p><strong>Хиба:</strong> <span class="math inline">\(r = 0.47\)</span> показує лише <strong>лінійну асоціацію</strong>, не <strong>каузальність</strong>.</p>
<p>Можливі альтернативні пояснення:</p>
<ol type="1">
<li><strong>Зворотна каузальність:</strong> більш мотивовані/продуктивні люди п’ють більше кави.</li>
<li><strong>Сторонній фактор (confounder):</strong> обидві змінні залежать від, скажімо, <strong>тиску дедлайнів</strong> — більше дедлайнів → більше кави і більше зусиль.</li>
<li><strong>Самооцінка ≠ продуктивність:</strong> <span class="math inline">\(Y\)</span> — суб’єктивна оцінка, корелює радше з настроєм/ентузіазмом.</li>
</ol>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Для каузальних висновків потрібен <strong>експеримент</strong> (RCT) або принаймні квазі-експериментальний дизайн.</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Найважливіший слайд P9. Класична мантра: <strong>correlation does not imply causation</strong>. Назвати конкретні confounders — це показує, що студент розуміє, чому простий <span class="math inline">\(r\)</span> не доводить причинності. Класичні приклади: морозиво vs утоплення (обоє від спеки).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="problem-10-casino-coin-flips" class="title-slide slide level1 center">
<h1>Problem 10 — Casino Coin Flips</h1>

</section>
<section id="сюжет-9" class="slide level2">
<h2>🧩 Сюжет</h2>
<p><span class="math inline">\(X_i = +100\)</span> з <span class="math inline">\(p = 0.45\)</span>, <span class="math inline">\(-100\)</span> з <span class="math inline">\(p = 0.55\)</span>.</p>
<ol type="a">
<li><span class="math inline">\(E[X_i], \operatorname{Var}(X_i)\)</span>;</li>
<li><span class="math inline">\(S_{100}\)</span>, теорема, нормальна апроксимація;</li>
<li><span class="math inline">\(P(S_{100} &gt; 0)\)</span> (hint: <span class="math inline">\(\sqrt{990\,000} \approx 995\)</span>);</li>
<li>LLN і чому «грати до перемоги» приречено.</li>
</ol>
</section>
<section id="p10a-ex_i-operatornamevarx_i" class="slide level2">
<h2>✅ P10(a) — <span class="math inline">\(E[X_i], \operatorname{Var}(X_i)\)</span></h2>
<p><span class="math display">\[
E[X_i] = 100 \cdot 0.45 + (-100) \cdot 0.55 = 45 - 55 = -10.
\]</span></p>
<p><span class="math display">\[
E[X_i^2] = 100^2 \cdot 0.45 + (-100)^2 \cdot 0.55 = 10\,000.
\]</span></p>
<p><span class="math display">\[
\operatorname{Var}(X_i) = 10\,000 - (-10)^2 = 10\,000 - 100 = 9\,900.
\]</span></p>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(E[X_i] = -\$10\)</span> — <strong>математика на боці казино</strong> (експлуатує перевагу 0.55 vs 0.45).</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Підкреслити: <span class="math inline">\(E[X_i^2] = 10\,000\)</span> незалежно від <span class="math inline">\(p\)</span> — це бо обидва результати рівні за модулем. Дисперсія майже = <span class="math inline">\(E[X_i^2]\)</span>, бо середнє маленьке. Це гарний приклад, де середнє «мізерне» порівняно з SD.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p10b-s_100-і-clt" class="slide level2">
<h2>✅ P10(b) — <span class="math inline">\(S_{100}\)</span> і CLT</h2>
<p>За незалежністю флипів:</p>
<p><span class="math display">\[
E[S_{100}] = 100 \cdot (-10) = -1\,000.
\]</span></p>
<p><span class="math display">\[
\operatorname{Var}(S_{100}) = 100 \cdot 9\,900 = 990\,000.
\]</span></p>
<p><span class="math display">\[
\operatorname{SD}(S_{100}) = \sqrt{990\,000} \approx 995.
\]</span></p>
<p><strong>Теорема:</strong> Центральна гранична (CLT) → для <span class="math inline">\(n = 100\)</span> можна апроксимувати:</p>
<p><span class="math display">\[
\boxed{S_{100} \overset{\text{прибл.}}{\sim} \mathcal{N}(-1\,000,\ 995^2)}.
\]</span></p>
<aside class="notes">
<p>Адитивність: <span class="math inline">\(E[S_n] = n E[X]\)</span>, <span class="math inline">\(\operatorname{Var}(S_n) = n \operatorname{Var}(X)\)</span> — для незалежних. Але SD росте як <span class="math inline">\(\sqrt{n}\)</span>, не <span class="math inline">\(n\)</span>! Це ключ до P10(d). Підкреслити: середнє «вирівнюється», сума — ні.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p10c-ps_100-0" class="slide level2">
<h2>✅ P10(c) — <span class="math inline">\(P(S_{100} &gt; 0)\)</span></h2>
<p><span class="math display">\[
z = \frac{0 - (-1\,000)}{995} = \frac{1\,000}{995} \approx 1.005.
\]</span></p>
<p><span class="math display">\[
P(S_{100} &gt; 0) = 1 - \Phi(1.005) \approx 1 - 0.8425 = \boxed{0.1575}.
\]</span></p>
<p>≈ <strong>15.7%</strong> шанс закінчити «у плюсі» після 100 флипів.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">0</span>, <span class="at">mean =</span> <span class="sc">-</span><span class="dv">1000</span>, <span class="at">sd =</span> <span class="fu">sqrt</span>(<span class="dv">990000</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1574393</code></pre>
</div>
</div>
<aside class="notes">
<p>15.7% — несподівано великий шанс! Через велику <span class="math inline">\(\sigma\)</span> хвіст «розхлюпується» далеко. Це ілюструє, чому казино <strong>рекламують</strong> виграші: на коротких сесіях люди справді бувають у плюсі.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p10d-lln-і-безнадійна-стратегія" class="slide level2">
<h2>✅ P10(d) — LLN і безнадійна стратегія</h2>
<p><strong>Закон великих чисел:</strong></p>
<p><span class="math display">\[
\bar X_n = \frac{S_n}{n} \xrightarrow{p} E[X_i] = -\$10.
\]</span></p>
<p>Тобто <strong>середній виграш на флип</strong> збігається до <strong>−10 $</strong>.</p>
<p><strong>Чому «грати до перемоги» приречено:</strong></p>
<ul>
<li><span class="math inline">\(E[S_n] = -10n\)</span> → лінійно <strong>зростає вниз</strong> із <span class="math inline">\(n\)</span>.</li>
<li><span class="math inline">\(\operatorname{SD}(S_n) = 99.5 \sqrt{n}\)</span> → росте, але <strong>повільніше</strong> (<span class="math inline">\(\sqrt{n}\)</span> vs <span class="math inline">\(n\)</span>).</li>
<li>Відношення сигнал/шум <span class="math inline">\(|E[S_n]| / \operatorname{SD}(S_n) = 10\sqrt{n}/99.5 \to \infty\)</span>.</li>
</ul>
<p>Тож <span class="math inline">\(P(S_n &gt; 0) \to 0\)</span> — чим довше граєш, тим меншою стає ймовірність вирівнятися.</p>
<div class="fragment">
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>LLN не дає «реваншу» — він <strong>гарантує</strong> збитки на дистанції. Це і є <strong>edge of the house</strong>.</p>
</div>
</div>
</div>
</div>
<aside class="notes">
<p>Фінал курсу: розгорнутий приклад, де LLN + CLT діють разом. Підкреслити: «gambler’s fallacy» — переконання, що після серії програшів має наступити виграш. Насправді кожен флип незалежний, а очікування — мінус. Корисно зробити паузу для рефлексії.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="p10-clt-vs-симуляція" class="slide level2">
<h2>📊 P10 — CLT vs симуляція</h2>

<img data-src=".midterm-mock-slides_files/figure-revealjs/unnamed-chunk-49-1.svg" class="r-stretch"></section>
<section id="p10-lln-збіжність" class="slide level2">
<h2>📊 P10 — LLN збіжність</h2>

<img data-src=".midterm-mock-slides_files/figure-revealjs/unnamed-chunk-50-1.svg" class="r-stretch"></section></section>
<section id="підсумок" class="title-slide slide level1 unnumbered center">
<h1>Підсумок</h1>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Ключові ідеї mock midterm</strong></p>
</div>
<div class="callout-content">
<ul>
<li><strong>PMF vs PDF:</strong> сума проти інтегралу; PDF може бути &gt; 1, PMF — ні.</li>
<li><strong>Cov = 0 ≠ незалежність</strong> (B2): контрприклад <span class="math inline">\(Y = X^2\)</span>.</li>
<li><strong>Базова частота:</strong> <span class="math inline">\(P(+\mid \text{spam}) \neq P(\text{spam}\mid +)\)</span> — Bayes (A9, P1).</li>
<li><strong>Memoryless</strong> — унікальна риса Exp (A6, P5).</li>
<li><strong>Markov vs Chebyshev:</strong> Markov груба, але <strong>точна</strong> на двозначкових (P6).</li>
<li><strong>CLT + LLN:</strong> <span class="math inline">\(\bar X \to \mu\)</span>, <span class="math inline">\(S_n\)</span> розкид росте як <span class="math inline">\(\sqrt{n}\)</span> — обидва на користь казино (P10).</li>
<li><strong>Кореляція ≠ причинність</strong> (P9): завжди питай про confounder.</li>
<li><strong>Skewed-right</strong> розподіли: mean &gt; median, нормальний — поганий фіт (D4).</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<p><strong>Удачі на справжньому мідтермі!</strong> 📚🎯</p>
</div>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src=".midterm-mock-slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src=".midterm-mock-slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src=".midterm-mock-slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src=".midterm-mock-slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src=".midterm-mock-slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src=".midterm-mock-slides_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src=".midterm-mock-slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src=".midterm-mock-slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src=".midterm-mock-slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src=".midterm-mock-slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src=".midterm-mock-slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'h.v',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'default',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: true,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1350,

        height: 759,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>