<!DOCTYPE html>
<html lang="en"><head>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src=".03-t-test_files/libs/clipboard/clipboard.min.js"></script>
<script src=".03-t-test_files/libs/quarto-html/tabby.min.js"></script>
<script src=".03-t-test_files/libs/quarto-html/popper.min.js"></script>
<script src=".03-t-test_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href=".03-t-test_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href=".03-t-test_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href=".03-t-test_files/libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src=".03-t-test_files/libs/quarto-contrib/iconify-1.0.7/iconify-icon.min.js"></script><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Ihor Miroshnychenko">
  <title>t-test</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href=".03-t-test_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href=".03-t-test_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href=".03-t-test_files/libs/revealjs/dist/theme/quarto-8a52321a21477e1bb40c2cb18c896737.css">
  <link href=".03-t-test_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href=".03-t-test_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href=".03-t-test_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href=".03-t-test_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href=".03-t-test_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href=".03-t-test_files/libs/revealjs/plugin/verticator/verticator.css" rel="stylesheet">
  <link href=".03-t-test_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>
  
  <script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-iframe=".03-t-test_files/libs/colored-particles/index.html" class="quarto-title-block center">
  <h1 class="title"><span class="math inline">\(t\)</span>-test</h1>
  <p class="subtitle">Applied Statistics</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Ihor Miroshnychenko 
</div>
        <p class="quarto-title-affiliation">
            Kyiv School of Economics
          </p>
    </div>
</div>

</section><section id="TOC">
<nav role="doc-toc"> 
<h2 id="toc-title">Table of contents</h2>
<ul>
<li><a href="#/t-test" id="/toc-t-test"><span class="math inline">\(t\)</span>-test</a></li>
<li><a href="#/confidence-intervals" id="/toc-confidence-intervals">Confidence intervals</a></li>
<li><a href="#/t-test-and-unknown-distribution" id="/toc-t-test-and-unknown-distribution"><span class="math inline">\(t\)</span>-test and unknown distribution</a></li>
<li><a href="#/two-sample-t-test.-the-task-of-ab-testing" id="/toc-two-sample-t-test.-the-task-of-ab-testing">Two-sample <span class="math inline">\(t\)</span>-test. The task of AB testing</a></li>
<li><a href="#/mde-for-the-t-test." id="/toc-mde-for-the-t-test.">MDE for the <span class="math inline">\(t\)</span>-test.</a></li>
</ul>
</nav>
</section>
<section>
<section id="t-test" class="title-slide slide level1 center" data-background-iframe=".03-t-test_files/libs/colored-particles/index.html">
<h1><span class="math inline">\(t\)</span>-test</h1>

</section>
<section id="task" class="slide level2 smaller">
<h2>📈 Task</h2>
<blockquote>
<p>Our company wants to switch from one DBMS to another. The main criterion for the transition is “the time spent per day loading new data.” If previously it took an average of 10 hours to update the database on a daily basis, we want to find a new DBMS that will do it faster than 7 hours.</p>
<p>To do this, we decided to transfer all the data to the new database under test. During one week, we will calculate the data loading time every day, and if the average time for updating is less than 7 hours, then we will completely switch to the new DBMS. Your task is to come up with a way to test the hypothesis that the new DBMS is better than the old one.</p>
</blockquote>
<p>The sample is:</p>
<ul>
<li><code>[6.9, 6.45, 6.32, 6.88, 6.09, 7.13, 6.76]</code> — the time to load into the new database by day in hours.</li>
</ul>
<aside class="notes">
<p>Перша задача лекції — навмисно «незручна»: вибірка всього 7 днів (один тиждень експерименту), бізнес хоче порівняти середній час завантаження з порогом 7 годин. Підкреслити малий розмір вибірки — саме він зламає Z-тест далі. Одностороння гіпотеза: новий СУБД кращий = час <em>менший</em> за 7.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="hypothesis" class="slide level2">
<h2>📊 Hypothesis</h2>
<ul>
<li><span class="math inline">\(X_1, X_2, ..., X_7\)</span> — the time of loading new data into the DBMS in hours for each day of the experiment</li>
<li><span class="math inline">\(X\)</span> from the normal distribution.</li>
</ul>
<div id="data-gen" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.array([<span class="fl">6.9</span>, <span class="fl">6.45</span>, <span class="fl">6.32</span>, <span class="fl">6.88</span>, <span class="fl">6.09</span>, <span class="fl">7.13</span>, <span class="fl">6.76</span>])</span>
<span id="cb1-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Average time of loading into the DBMS: </span><span class="sc">{</span>X<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss"> hours"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Average time of loading into the DBMS: 6.65 hours</code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(H_0: \bar{X} \geq 7\)</span> vs.&nbsp;<span class="math inline">\(H_1: \bar{X} &lt; 7\)</span></li>
</ul>
<aside class="notes">
<p>Формалізуємо: припускаємо нормальність вихідних даних (поки що — далі побачимо, коли без неї можна обійтися). Вибіркове середнє ≈ 6.65 &lt; 7, але цього мало — треба перевірити, чи різниця статистично значуща, а не випадкова на 7 спостереженнях. Записуємо H₀ (не гірше за 7) проти H₁ (швидше за 7).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="z-test" class="slide level2">
<h2>📐 <span class="math inline">\(Z\)</span>-test</h2>
<ul>
<li>The statistic <span class="math inline">\(Z(X) = \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{\sigma^2}}\)</span></li>
</ul>
<div class="fragment">
<p>Then you just need to calculate the following statistics: <span class="math display">\[\sqrt{n}\dfrac{\overline X - 7}{\sqrt{\sigma^2}} \overset{H_0}{\sim} \mathcal{N}(0, 1)\]</span></p>
</div>
<div class="fragment">
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>But there’s one problem: <span class="hi">we don’t know <span class="math inline">\(\sigma^2\)</span>!</span></p>
</div>
</div>
</div>
<aside class="notes">
<p>Прямий місток з минулої лекції: ми вже вміємо рахувати Z-статистику для середнього. Але у Z-тесті σ² мусить бути <em>відомою</em>. Для пропорцій вона була «самоописова» через p(1−p), а тут — час у годинах, неперервна метрика, і σ² нізвідки взяти. Це і є та сама проблема невідомої дисперсії, якою закінчилась лекція про Z-тест.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="t-test-1" class="slide level2 smaller">
<h2>📐 <span class="math inline">\(t'\)</span>-test</h2>
<p><span class="math inline">\(\widehat{\sigma^2} =S^2 = \dfrac{1}{n - 1}\underset{i=1}{\overset{n}{\sum}}(X_i - \overline X)^2\)</span></p>
<div class="fragment">
<div id="sigma-hat" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample variance: </span><span class="sc">{</span>X<span class="sc">.</span>var(ddof<span class="op">=</span><span class="dv">1</span>)<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample variance: 0.1367</code></pre>
</div>
</div>
</div>
<div class="fragment">
<p>Let’s introduce a new criterion, the <span class="math inline">\(t\)</span>-test, in which we substitute:</p>
<ul>
<li><span class="math inline">\(T(X) := \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{S^2}}\)</span></li>
<li><span class="math inline">\(T(X) \overset{H_0}{\sim} \mathcal{N}(0, 1)\)</span> 🤨</li>
</ul>
</div>
<div class="fragment">
<blockquote>
<p>It remains to be seen: Is it true that at <span class="math inline">\(H_0\)</span> the distribution of the statistic T is standard normal?</p>
</blockquote>
<aside class="notes">
<p>Наївна ідея: якщо σ² невідома — підставимо її оцінку S² (вибіркова дисперсія, ddof=1, тобто ділимо на n−1). Отримуємо нову статистику T(X). Емодзі 🤨 свідомий: ми <em>припускаємо</em>, що T теж ~N(0,1), але це гіпотеза, яку треба перевірити. S² — сама випадкова величина, і ця випадковість може зіпсувати розподіл. Далі перевіримо симуляцією.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="distribution-of-statistics" class="slide level2">
<h2>📊 Distribution of statistics</h2>
<ul>
<li>We will generate a sample <span class="math inline">\(X\)</span> <span class="math inline">\(M\)</span> times and calculate the statistic <span class="math inline">\(T(X)\)</span> each time.</li>
<li>As a result, we will get a sample of size <span class="math inline">\(M\)</span> for <span class="math inline">\(T(X)\)</span> and can draw a histogram of the distribution.</li>
<li>We will also plot the distribution <span class="math inline">\(\mathcal{N}(0, 1)\)</span> separately.</li>
<li>If the empirical distribution visually coincides with the theoretical normal distribution, then everything is fine. If not, then we cannot simply replace <span class="math inline">\(\sigma^2\)</span> with <span class="math inline">\(S^2\)</span>.
<ul>
<li>Additionally, let’s see what happens if we replace <span class="math inline">\(T(X)\)</span> with <span class="math inline">\(Z(X)\)</span>.</li>
</ul></li>
</ul>
<aside class="notes">
<p>План перевірки (той самий прийом, що й для візуалізації ЦГТ у минулій лекції): M разів генеруємо вибірку з відомого нормального розподілу, щоразу рахуємо T(X) і Z(X). Отримуємо емпіричний розподіл кожної статистики й накладаємо на теоретичний N(0,1). Z(X) тут — «чесний» контроль: для нього σ відома, тож він <em>має</em> лягти на N(0,1).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="python-and-statistics-distribution" class="slide level2 smaller">
<h2>Python and 📊 statistics distribution</h2>
<div id="cell-t-test-sim-def" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb5-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="" aria-hidden="true" tabindex="-1"></a>M <span class="op">=</span> <span class="dv">100_000</span></span>
<span id="cb5-4"><a href="" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="dv">7</span></span>
<span id="cb5-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># T(X): variance estimated from the sample (S^2)</span></span>
<span id="cb5-7"><a href="" aria-hidden="true" tabindex="-1"></a>samples_T <span class="op">=</span> stats.norm.rvs(loc<span class="op">=</span><span class="dv">5</span>, scale<span class="op">=</span><span class="dv">3</span>, size<span class="op">=</span>(M, sample_size))</span>
<span id="cb5-8"><a href="" aria-hidden="true" tabindex="-1"></a>T_X <span class="op">=</span> np.sqrt(sample_size) <span class="op">*</span> (samples_T.mean(axis<span class="op">=</span><span class="dv">1</span>) <span class="op">-</span> <span class="dv">5</span>) <span class="op">/</span> samples_T.std(axis<span class="op">=</span><span class="dv">1</span>, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb5-9"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Z(X): true variance (sigma = 3) is known</span></span>
<span id="cb5-11"><a href="" aria-hidden="true" tabindex="-1"></a>samples_Z <span class="op">=</span> stats.norm.rvs(loc<span class="op">=</span><span class="dv">5</span>, scale<span class="op">=</span><span class="dv">3</span>, size<span class="op">=</span>(M, sample_size))</span>
<span id="cb5-12"><a href="" aria-hidden="true" tabindex="-1"></a>Z_X <span class="op">=</span> np.sqrt(sample_size) <span class="op">*</span> (samples_Z.mean(axis<span class="op">=</span><span class="dv">1</span>) <span class="op">-</span> <span class="dv">5</span>) <span class="op">/</span> <span class="dv">3</span></span>
<span id="cb5-13"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="" aria-hidden="true" tabindex="-1"></a>plot_data <span class="op">=</span> pd.DataFrame({</span>
<span id="cb5-15"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Statistic"</span>: np.repeat([<span class="st">"T_X"</span>, <span class="st">"Z_X"</span>], M),</span>
<span id="cb5-16"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Value"</span>:     np.concatenate([T_X, Z_X]),</span>
<span id="cb5-17"><a href="" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb5-18"><a href="" aria-hidden="true" tabindex="-1"></a>plot_data</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="t-test-sim-def" class="cell-output cell-output-display" data-execution_count="29">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Statistic</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>T_X</td>
<td>1.748327</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>T_X</td>
<td>-0.742777</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>T_X</td>
<td>-1.318122</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>T_X</td>
<td>-1.559567</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>T_X</td>
<td>0.041304</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">...</th>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">199995</th>
<td>Z_X</td>
<td>0.155388</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">199996</th>
<td>Z_X</td>
<td>0.853186</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">199997</th>
<td>Z_X</td>
<td>-1.659037</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">199998</th>
<td>Z_X</td>
<td>0.085819</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">199999</th>
<td>Z_X</td>
<td>0.990811</td>
</tr>
</tbody>
</table>

<p>200000 rows × 2 columns</p>
</div>
</div>
</div>
<aside class="notes">
<p>Реалізація векторизована: замість циклу на 100 000 ітерацій генеруємо матрицю (M × 7) і рахуємо середнє/дисперсію по рядках — це швидко. Ключова відмінність двох статистик у знаменнику: T(X) ділить на <code>std(..., ddof=1)</code> (оцінка S), Z(X) — на справжню σ=3. Дані складаємо в довгий DataFrame для зручного фасетингу.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="python-and-statistics-distribution-1" class="slide level2 smaller">
<h2>Python and 📊 statistics distribution</h2>
<div id="cell-t-test-sim-run" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">1000</span>)</span>
<span id="cb6-2"><a href="" aria-hidden="true" tabindex="-1"></a>normal_pdf <span class="op">=</span> stats.norm.pdf(x, loc<span class="op">=</span><span class="dv">0</span>, scale<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb6-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">13</span>, <span class="fl">4.5</span>))</span>
<span id="cb6-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, name <span class="kw">in</span> <span class="bu">zip</span>(axes, [<span class="st">"T_X"</span>, <span class="st">"Z_X"</span>]):</span>
<span id="cb6-7"><a href="" aria-hidden="true" tabindex="-1"></a>    values <span class="op">=</span> plot_data.loc[plot_data[<span class="st">"Statistic"</span>] <span class="op">==</span> name, <span class="st">"Value"</span>].to_numpy()</span>
<span id="cb6-8"><a href="" aria-hidden="true" tabindex="-1"></a>    lo, hi <span class="op">=</span> np.quantile(values, [<span class="fl">0.001</span>, <span class="fl">0.999</span>])</span>
<span id="cb6-9"><a href="" aria-hidden="true" tabindex="-1"></a>    clipped <span class="op">=</span> values[(values <span class="op">&gt;=</span> lo) <span class="op">&amp;</span> (values <span class="op">&lt;=</span> hi)]</span>
<span id="cb6-10"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="" aria-hidden="true" tabindex="-1"></a>    kde <span class="op">=</span> stats.gaussian_kde(clipped)</span>
<span id="cb6-12"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.hist(clipped, bins<span class="op">=</span><span class="dv">30</span>, density<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">"skyblue"</span>, alpha<span class="op">=</span><span class="fl">0.6</span>,</span>
<span id="cb6-13"><a href="" aria-hidden="true" tabindex="-1"></a>            edgecolor<span class="op">=</span><span class="st">"white"</span>)</span>
<span id="cb6-14"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.plot(x, normal_pdf, color<span class="op">=</span>red,  lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"Theoretical"</span>)</span>
<span id="cb6-15"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.plot(x, kde(x),     color<span class="op">=</span>blue, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"Empirical"</span>)</span>
<span id="cb6-16"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.set_title(name)</span>
<span id="cb6-17"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"Value"</span>)</span>
<span id="cb6-18"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb6-19"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(lo, hi)</span>
<span id="cb6-20"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.legend()</span>
<span id="cb6-21"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">"Distribution of statistics T(X) and Z(X)"</span>)</span>
<span id="cb6-23"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb6-24"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".03-t-test_files/figure-revealjs/t-test-sim-run-output-1.svg" id="t-test-sim-run" class="quarto-figure quarto-figure-center r-stretch"><div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<ul>
<li>The <span class="math inline">\(Z\)</span>-test works here: <span class="math inline">\(\sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{\sigma^2}} \sim \mathcal{N}(0, 1)\)</span>.</li>
<li>But this is not the case for <span class="math inline">\(T(X)\)</span>! <span class="hi">They are different! So the <span class="math inline">\(t'\)</span>-test is not suitable for the original problem!</span></li>
</ul>
</div>
</div>
</div>
<aside class="notes">
<p>Головний висновок слайда: праворуч Z(X) ідеально лягає на N(0,1) (червона = синя), а ліворуч T(X) має <em>важчі хвости</em> — емпірична крива виходить за теоретичну. Тобто наївна підстановка S² замість σ² на малій вибірці (n=7) ламає розподіл. Саме хвости визначають критичні значення → t’-тест на малих вибірках дає неправильний p-value.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-did-it-happen" class="slide level2 smaller">
<h2>📝 Why did it happen?</h2>
<p><span class="math inline">\(S^2\)</span> is a random variable!</p>
<p>Let’s look at the distribution of <span class="math inline">\(\sqrt{S^2}\)</span> on the same normal distribution.</p>
<div id="cell-sigma-hat-sim" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb7-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="" aria-hidden="true" tabindex="-1"></a>samples <span class="op">=</span> stats.norm.rvs(loc<span class="op">=</span><span class="dv">5</span>, scale<span class="op">=</span><span class="dv">3</span>, size<span class="op">=</span>(M, sample_size))</span>
<span id="cb7-4"><a href="" aria-hidden="true" tabindex="-1"></a>sigma_hat <span class="op">=</span> samples.std(axis<span class="op">=</span><span class="dv">1</span>, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="" aria-hidden="true" tabindex="-1"></a>lo, hi <span class="op">=</span> np.quantile(sigma_hat, [<span class="fl">0.001</span>, <span class="fl">0.999</span>])</span>
<span id="cb7-7"><a href="" aria-hidden="true" tabindex="-1"></a>clipped <span class="op">=</span> sigma_hat[(sigma_hat <span class="op">&gt;=</span> lo) <span class="op">&amp;</span> (sigma_hat <span class="op">&lt;=</span> hi)]</span>
<span id="cb7-8"><a href="" aria-hidden="true" tabindex="-1"></a>kde <span class="op">=</span> stats.gaussian_kde(clipped)</span>
<span id="cb7-9"><a href="" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> np.linspace(lo, hi, <span class="dv">1000</span>)</span>
<span id="cb7-10"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.5</span>))</span>
<span id="cb7-12"><a href="" aria-hidden="true" tabindex="-1"></a>ax.hist(clipped, bins<span class="op">=</span><span class="dv">30</span>, density<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">"skyblue"</span>, alpha<span class="op">=</span><span class="fl">0.6</span>,</span>
<span id="cb7-13"><a href="" aria-hidden="true" tabindex="-1"></a>        edgecolor<span class="op">=</span><span class="st">"white"</span>)</span>
<span id="cb7-14"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(grid, kde(grid), color<span class="op">=</span>blue, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"Empirical density"</span>)</span>
<span id="cb7-15"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axvline(<span class="dv">3</span>, color<span class="op">=</span>red, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"True sigma = 3"</span>)</span>
<span id="cb7-16"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Distribution of the sample standard deviation"</span>)</span>
<span id="cb7-17"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Value"</span>)</span>
<span id="cb7-18"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb7-19"><a href="" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb7-20"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb7-21"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".03-t-test_files/figure-revealjs/sigma-hat-sim-output-1.svg" id="sigma-hat-sim" class="quarto-figure quarto-figure-center r-stretch"><div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Conclusion.</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(T(X) \overset{H_0}{\nsim} \mathcal{N}(0, 1)\)</span> 😭</p>
</div>
</div>
</div>
<aside class="notes">
<p>Пояснення «чому»: √S² сама гуляє навколо справжньої σ=3 (червона лінія) і на n=7 розкид великий — оцінка часто помітно менша або більша за 3. Коли ми ділимо на випадковий, інколи малий, знаменник — статистика «вистрілює» у хвости. Звідси важчі хвости T(X). Висновок: T(X) під H₀ НЕ є N(0,1). Треба знайти його справжній розподіл.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-is-the-distribution-of-tx" class="slide level2 tiny40">
<h2>What is the distribution of <span class="math inline">\(T(X)\)</span>?</h2>
<ol type="1">
<li><p>Let <span class="math inline">\(X_1 \ldots X_n \sim \mathcal{N}(\mu, \sigma^2)\)</span></p></li>
<li><p>Let <span class="math inline">\(\xi_1 \ldots \xi_n \sim \mathcal{N}(0, 1)\)</span>. Then <span class="math inline">\(\eta=\xi_1^2 +\ ... +\xi_n^2 \sim \chi^2_n\)</span>, — <a href="https://en.wikipedia.org/wiki/Chi-squared_distribution"><strong><span class="math inline">\(\chi^2\)</span> distribution with <span class="math inline">\(n\)</span> degrees of freedom</strong></a>.</p>
<ul>
<li><p>Then <span class="math inline">\(\underset{i=1}{\overset{n}{\sum}}\left(\xi_i - \overline \xi \right)^2 \sim \chi^2_{n-1}\)</span>. <a href="https://en.wikipedia.org/wiki/Cochran%27s_theorem">Proof</a> 🫠</p></li>
<li><p><span class="math inline">\(S^2_X = \dfrac{1}{n - 1}\underset{i=1}{\overset{n}{\sum}}(X_i - \overline X)^2\)</span></p></li>
<li><p><span class="math inline">\(\xi_i := \dfrac{X_i - \mu}{\sigma} \sim \mathcal{N}(0, 1)\)</span>. Then <span class="math inline">\(S^2_{\xi} = \dfrac{1}{\sigma^2}S^2_X\)</span>.</p></li>
<li><p>So <span class="math inline">\(\dfrac{(n - 1)\cdot S^2_X}{\sigma^2} = \underset{i=1}{\overset{n}{\sum}}\left(\xi_i - \overline \xi \right)^2 \sim \chi^2_{n-1}\)</span>.</p></li>
</ul></li>
<li><p>Let <span class="math inline">\(\xi \sim \mathcal{N}(0, 1), \eta \sim \chi^2_k\)</span> and <span class="math inline">\(\xi\)</span> with <span class="math inline">\(\eta\)</span> be independent. Then the statistic <span class="math inline">\(\zeta = \dfrac{\xi}{\sqrt{\eta/k}} \sim t_{k}\)</span> — from the <a href="https://en.wikipedia.org/wiki/Student%27s_t-distribution">Student’s distribution</a> with <span class="math inline">\(k\)</span> degrees of freedom.</p>
<ul>
<li><span class="math inline">\(\xi := \sqrt{n}\dfrac{\overline X - \mu_0}{\sigma} \sim \mathcal{N}(0, 1)\)</span></li>
<li><span class="math inline">\(\eta := \dfrac{(n - 1)\cdot S^2_X}{\sigma^2} \sim \chi^2_{n-1}\)</span></li>
<li><span class="math inline">\(\xi\)</span> and <span class="math inline">\(\eta\)</span> are <a href="https://math.stackexchange.com/questions/4165803/overlinex-and-s2-are-independent">independent</a></li>
<li>Then</li>
</ul></li>
</ol>
<p><span class="math display">\[
\begin{align}
T = \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{S^2}} = \frac{\sqrt{n}\dfrac{\overline X - \mu_0}{\sigma}}{\sqrt{\dfrac{(n - 1)\cdot S^2_X}{(n - 1)\sigma^2}}} = \dfrac{\xi}{\sqrt{\dfrac{\eta}{n-1}}} \sim t_{n - 1}
\end{align}
\]</span></p>
<aside class="notes">
<p>Теоретичний кістяк (можна пройти швидко, акцент на результаті). Три цеглинки: (1) сума квадратів стандартних нормальних — це χ², (2) (n−1)S²/σ² ~ χ²ₙ₋₁, (3) означення розподілу Стьюдента — відношення N(0,1) до кореня з χ²/df. Підставляємо й бачимо: T(X) ~ t з n−1 ступенями свободи. Саме «−1» (бо оцінили середнє) пояснює важчі хвости на малих n.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="problem-and-t-test" class="slide level2 smaller">
<h2>📈 Problem and 📐 <span class="math inline">\(t\)</span>-test</h2>
<p><span class="math inline">\(T = \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{S^2}} \sim t_{n - 1}\)</span> — taken from a Student’s distribution with <span class="math inline">\(n - 1\)</span> degrees of freedom.</p>
<p><br></p>
<div id="t-test-data" class="cell columns column-output-location" data-execution_count="7">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.array([<span class="fl">6.9</span>, <span class="fl">6.45</span>, <span class="fl">6.32</span>, <span class="fl">6.88</span>, <span class="fl">6.09</span>, <span class="fl">7.13</span>, <span class="fl">6.76</span>])</span>
<span id="cb8-2"><a href="" aria-hidden="true" tabindex="-1"></a>t_stat <span class="op">=</span> np.sqrt(<span class="bu">len</span>(X)) <span class="op">*</span> (X.mean() <span class="op">-</span> <span class="dv">7</span>) <span class="op">/</span> X.std(ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb8-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"t-statistic: </span><span class="sc">{</span>t_stat<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>t-statistic: -2.52</code></pre>
</div>
</div></div>
<p><br></p>
<div id="t-test-p-value" class="cell columns column-output-location" data-execution_count="8">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> stats.t.cdf(t_stat, df<span class="op">=</span><span class="bu">len</span>(X) <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb10-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-value: </span><span class="sc">{</span>p_value<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>p-value: 0.0225</code></pre>
</div>
</div></div>
<p><br></p>
<div id="t-test-scipy" class="cell columns column-output-location" data-execution_count="9">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> stats.ttest_1samp(X, popmean<span class="op">=</span><span class="dv">7</span>, alternative<span class="op">=</span><span class="st">"less"</span>)</span>
<span id="cb12-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"t-statistic: </span><span class="sc">{</span>result<span class="sc">.</span>statistic<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb12-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-value:     </span><span class="sc">{</span>result<span class="sc">.</span>pvalue<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>t-statistic: -2.5248
p-value:     0.0225</code></pre>
</div>
</div></div>
<aside class="notes">
<p>Тепер рахуємо «вручну» і через бібліотеку. Вручну: та сама статистика, але p-value беремо з <code>t.cdf</code> (df = n−1 = 6), а не з <code>norm.cdf</code> — це і є різниця між t- і t’-тестом. <code>stats.ttest_1samp</code> з <code>alternative="less"</code> робить це автоматично і дає ті самі числа. p-value &lt; 0.05 → відхиляємо H₀ → новий СУБД справді швидший за 7 годин. Завжди корисно звірити ручний розрахунок з бібліотекою.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="confidence-intervals" class="title-slide slide level1 center" data-background-iframe=".03-t-test_files/libs/colored-particles/index.html">
<h1>Confidence intervals</h1>

</section>
<section id="confidence-interval-for-the-mean-option-1" class="slide level2 tiny">
<h2>📊 Confidence interval for the mean: option 1</h2>
<p><span class="hi">Confidence interval</span> — set <span class="math inline">\(m\)</span>: the test does not reject <span class="math inline">\(H_0: \mu = m\)</span> at the significance level <span class="math inline">\(\alpha\)</span>.</p>
<ul>
<li><p>Let <span class="math inline">\(\mu\)</span> be the true mean of the sample. We also know that for <span class="math inline">\(H_0: \sqrt{n}\dfrac{\overline X - m}{\sqrt{S^2}} \sim t_{n - 1}\)</span>.</p></li>
<li><p>We are interested in <span class="math inline">\(m\)</span> such that: <span class="math inline">\(\left\{-t_{n-1, 1 - \frac{\alpha}{2}} &lt; \sqrt{n}\dfrac{\overline X - m}{\sqrt{S^2}} &lt; t_{n-1, 1 - \frac{\alpha}{2}} \right\}\)</span>, in which case the criterion will not be rejected.</p></li>
<li><p>Let’s write it so that only <span class="math inline">\(m\)</span> remains in the center:</p></li>
</ul>
<p><span class="math display">\[\left\{\overline X - \dfrac{t_{n - 1, 1 - \alpha/2} \sqrt{S^2}}{\sqrt{n}} &lt; m &lt; \overline X + \dfrac{t_{n - 1, 1 - \alpha/2} \sqrt{S^2}}{\sqrt{n}}\right\}\]</span></p>
<ul>
<li>Then the confidence interval:</li>
</ul>
<p><span class="math display">\[CI_{\mu} = \left(\overline X \pm \dfrac{t_{n - 1, 1 - \alpha/2} \sqrt{S^2}}{\sqrt{n}} \right),\]</span></p>
<p>where <span class="math inline">\(S^2 = \dfrac{1}{n - 1}\underset{i=1}{\overset{n}{\sum}}(X_i - \overline X)^2\)</span></p>
<aside class="notes">
<p>Перший погляд на довірчий інтервал — через «інверсію тесту»: CI це множина значень m, які тест НЕ відхиляє. Виводимо, розкриваючи нерівність відносно m: середнє ± критичне t × стандартна похибка. Важливо: тут квантиль t (не z), бо σ невідома й n мале.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="confidence-interval-for-the-mean-option-2" class="slide level2 tiny">
<h2>📊 Confidence interval for the mean: option 2</h2>
<p><a href="https://en.wikipedia.org/wiki/Confidence_interval#Definition">Classical definition</a> of a confidence interval:</p>
<blockquote>
<p>A confidence interval for a parameter <span class="math inline">\(\theta\)</span> of confidence level <span class="math inline">\(1 - \alpha\)</span> is a pair of statistics <span class="math inline">\(L(X), R(X)\)</span> such that <span class="math inline">\(P(L(X) &lt; \theta &lt; R(X)) = 1 - \alpha\)</span>.</p>
</blockquote>
<p><span class="math display">\[
\begin{align}
&amp;T(X) = \sqrt{n}\dfrac{\overline X - \mu}{\sqrt{S^2}} \sim t_{n - 1} \Rightarrow \\
&amp;P\left(-t_{n - 1, 1-\alpha/2} &lt; \sqrt{n}\dfrac{\overline X - \mu}{\sqrt{S^2}} &lt; t_{n - 1, 1-\alpha/2} \right) = 1 - \alpha \Leftrightarrow \\
&amp;P\left(\overline X - \dfrac{t_{n - 1, 1 - \alpha/2} \sqrt{S^2}}{\sqrt{n}}  &lt; \mu &lt; \overline X + \dfrac{t_{n - 1, 1 - \alpha/2} \sqrt{S^2}}{\sqrt{n}} \right) = 1 - \alpha
\end{align}
\]</span></p>
<ul>
<li>Then the confidence interval:</li>
</ul>
<p><span class="math display">\[CI_{\mu} = \left(\overline X \pm \dfrac{t_{n - 1, 1 - \alpha/2} \sqrt{S^2}}{\sqrt{n}} \right)\]</span></p>
<aside class="notes">
<p>Другий, «класичний» шлях до того самого CI — прямо з означення: пара статистик, що накриває μ з імовірністю 1−α. Відштовхуємось від того, що T(X) ~ tₙ₋₁, і переписуємо ймовірність. Результат ідентичний варіанту 1 — два різні обґрунтування, одна формула. Корисно показати студентам, що інтуїція «інверсії тесту» і строге означення узгоджені.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="python-and-confidence-interval" class="slide level2 smaller">
<h2>Python and 📊 confidence interval</h2>
<div id="ci" class="cell columns column-output-location" data-execution_count="10">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb14-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="" aria-hidden="true" tabindex="-1"></a>sample <span class="op">=</span> stats.norm.rvs(loc<span class="op">=</span><span class="dv">10</span>, scale<span class="op">=</span><span class="dv">2</span>, size<span class="op">=</span><span class="dv">100</span>)</span>
<span id="cb14-4"><a href="" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb14-5"><a href="" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(sample)</span>
<span id="cb14-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="" aria-hidden="true" tabindex="-1"></a>t_crit <span class="op">=</span> stats.t.ppf(<span class="dv">1</span> <span class="op">-</span> alpha <span class="op">/</span> <span class="dv">2</span>, df<span class="op">=</span>n <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb14-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"t critical value: </span><span class="sc">{</span>t_crit<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb14-9"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="" aria-hidden="true" tabindex="-1"></a>manual_ci <span class="op">=</span> sample.mean() <span class="op">+</span> np.array([<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>]) <span class="op">*</span> t_crit <span class="op">*</span> sample.std(ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np.sqrt(n)</span>
<span id="cb14-11"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Manual CI: </span><span class="sc">{</span>manual_ci<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb14-12"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="" aria-hidden="true" tabindex="-1"></a>ci <span class="op">=</span> stats.ttest_1samp(sample, popmean<span class="op">=</span><span class="dv">0</span>).confidence_interval(confidence_level<span class="op">=</span><span class="dv">1</span> <span class="op">-</span> alpha)</span>
<span id="cb14-14"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"scipy CI:  [</span><span class="sc">{</span>ci<span class="sc">.</span>low<span class="sc">:.4f}</span><span class="ss">, </span><span class="sc">{</span>ci<span class="sc">.</span>high<span class="sc">:.4f}</span><span class="ss">]"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>t critical value: 1.9842
Manual CI: [ 9.43190633 10.1527076 ]
scipy CI:  [9.4319, 10.1527]</code></pre>
</div>
</div></div>
<aside class="notes">
<p>Перевірка на синтетичній вибірці з N(10, 2²), n=100. Рахуємо CI двома способами: вручну за формулою (квантиль через <code>t.ppf</code>) і через <code>ttest_1samp(...).confidence_interval</code>. Числа збігаються. <code>popmean</code> у виклику не впливає на CI — він потрібен лише для статистики тесту. Очікувано інтервал накриває справжнє μ=10.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="task-ci-for-the-dbms" class="slide level2 smaller">
<h2>📈 Task: CI for the DBMS</h2>
<div id="ci-data" class="cell columns column-output-location" data-execution_count="11">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.array([<span class="fl">6.9</span>, <span class="fl">6.45</span>, <span class="fl">6.32</span>, <span class="fl">6.88</span>, <span class="fl">6.09</span>, <span class="fl">7.13</span>, <span class="fl">6.76</span>])</span>
<span id="cb16-2"><a href="" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb16-3"><a href="" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(X)</span>
<span id="cb16-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="" aria-hidden="true" tabindex="-1"></a>t_crit <span class="op">=</span> stats.t.ppf(<span class="dv">1</span> <span class="op">-</span> alpha <span class="op">/</span> <span class="dv">2</span>, df<span class="op">=</span>n <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb16-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"t critical value: </span><span class="sc">{</span>t_crit<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb16-7"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="" aria-hidden="true" tabindex="-1"></a>manual_ci <span class="op">=</span> X.mean() <span class="op">+</span> np.array([<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>]) <span class="op">*</span> t_crit <span class="op">*</span> X.std(ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np.sqrt(n)</span>
<span id="cb16-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Manual CI: </span><span class="sc">{</span>manual_ci<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-10"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="" aria-hidden="true" tabindex="-1"></a>ci <span class="op">=</span> stats.ttest_1samp(X, popmean<span class="op">=</span><span class="dv">0</span>).confidence_interval(confidence_level<span class="op">=</span><span class="dv">1</span> <span class="op">-</span> alpha)</span>
<span id="cb16-12"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"scipy CI:  [</span><span class="sc">{</span>ci<span class="sc">.</span>low<span class="sc">:.4f}</span><span class="ss">, </span><span class="sc">{</span>ci<span class="sc">.</span>high<span class="sc">:.4f}</span><span class="ss">]"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>t critical value: 2.4469
Manual CI: [6.3051702  6.98911551]
scipy CI:  [6.3052, 6.9891]</code></pre>
</div>
</div></div>
<aside class="notes">
<p>Повертаємось до СУБД: будуємо 95% CI для середнього часу завантаження. На n=7 критичне t помітно більше за 1.96 (≈2.45) — інтервал ширший, ніж дав би Z. Звертаємо увагу: верхня межа інтервалу нижча за 7 → це узгоджується з висновком тесту, що час значуще менший за 7 годин.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="t-test-and-unknown-distribution" class="title-slide slide level1 center" data-background-iframe=".03-t-test_files/libs/colored-particles/index.html">
<h1><span class="math inline">\(t\)</span>-test and unknown distribution</h1>

</section>
<section id="task-1" class="slide level2 tiny">
<h2>📊 Task</h2>
<blockquote>
<p>You have come up with an idea for a startup where couriers collect orders for customers and deliver them to their homes. The margin on an order in your startup is X ₴, and the cost of a courier’s work is 1k ₴. The specifics of your startup are such that there is a high risk of return without payment. Given the costs, investors are willing to sponsor your infrastructure and customer acquisition if you show that you will make a profit.</p>
<p>From the data, you have the money brought in from each user. Sometimes a positive value, sometimes negative.</p>
</blockquote>
<ul>
<li><span class="math inline">\(X_1, X_2, \dots X_N\)</span> — a sample of the user’s profit.</li>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(E \overline{X} \leq 0\)</span> vs.&nbsp;<span class="math inline">\(H_1: E \overline{X} &gt; 0\)</span></li>
</ul>
<p>Data:</p>
<div id="cell-profit-data" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="" aria-hidden="true" tabindex="-1"></a>profits <span class="op">=</span> pd.read_csv(<span class="st">"data/profit_from_user.out"</span>, sep<span class="op">=</span><span class="vs">r"</span><span class="dv">\s</span><span class="op">+</span><span class="vs">"</span>,</span>
<span id="cb18-2"><a href="" aria-hidden="true" tabindex="-1"></a>                      header<span class="op">=</span><span class="va">None</span>, names<span class="op">=</span>[<span class="st">"profit"</span>])</span>
<span id="cb18-3"><a href="" aria-hidden="true" tabindex="-1"></a>profits.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="profit-data" class="cell-output cell-output-display" data-execution_count="37">
<div>
<style scoped="">
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>

<table class="dataframe caption-top" data-border="1">
<thead>
<tr class="header" style="text-align: right;">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">profit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>-718.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>657.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>693.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>391.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>-644.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<aside class="notes">
<p>Друга задача — той самий кур’єрський стартап, що й у лекції 1, але тепер метрика неперервна: прибуток з користувача (буває від’ємний — повернення без оплати). Інвестори дають гроші, якщо середній прибуток &gt; 0. H₀: середнє ≤ 0. Тут σ² теж невідома, але — і це ключове — розподіл явно НЕ нормальний. Чи можна все одно застосувати t-тест?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="task-2" class="slide level2 tiny">
<h2>📊 Task</h2>
<div id="profit-avg" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Average profit: </span><span class="sc">{</span>profits[<span class="st">'profit'</span>]<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss"> ₴"</span>)</span>
<span id="cb19-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample size: </span><span class="sc">{</span><span class="bu">len</span>(profits)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Average profit: 58.49 ₴
Sample size: 5000</code></pre>
</div>
</div>
<div id="cell-profit-distplot" class="cell columns column-output-location" data-fig-height="7" data-execution_count="14">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="" aria-hidden="true" tabindex="-1"></a>values <span class="op">=</span> profits[<span class="st">"profit"</span>].to_numpy()</span>
<span id="cb21-2"><a href="" aria-hidden="true" tabindex="-1"></a>kde <span class="op">=</span> stats.gaussian_kde(values)</span>
<span id="cb21-3"><a href="" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> np.linspace(values.<span class="bu">min</span>(), values.<span class="bu">max</span>(), <span class="dv">500</span>)</span>
<span id="cb21-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb21-6"><a href="" aria-hidden="true" tabindex="-1"></a>ax.hist(values, bins<span class="op">=</span><span class="dv">40</span>, density<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">"skyblue"</span>, alpha<span class="op">=</span><span class="fl">0.6</span>,</span>
<span id="cb21-7"><a href="" aria-hidden="true" tabindex="-1"></a>        edgecolor<span class="op">=</span><span class="st">"white"</span>)</span>
<span id="cb21-8"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(grid, kde(grid), color<span class="op">=</span>blue, lw<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb21-9"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Distribution of profits"</span>)</span>
<span id="cb21-10"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Profit, ₴"</span>)</span>
<span id="cb21-11"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb21-12"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb21-13"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src=".03-t-test_files/figure-revealjs/profit-distplot-output-1.svg" id="profit-distplot"></p>
</figure>
</div>
</div>
</div></div>
<ul>
<li>The initial sample is not from a normal distribution</li>
<li>The sample is quite large: not 7 items, but 5000.</li>
</ul>
<p><span class="hi">Can we use the normal distribution as an approximation?</span></p>
<aside class="notes">
<p>Дивимось на дані: середнє додатне, але вибірка велика (5000) і розподіл явно не нормальний (бімодальний/скошений — суміш «оплатив» і «повернув»). Контраст із першою задачею: там n=7 і нормальність, тут n=5000 і ненормальність. Питання на слайді — гачок: чи рятує великий обсяг вибірки? Відповідь дасть ЦГТ + теорема Слуцького на наступному слайді.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="t-test-and-approximation" class="slide level2 tiny40">
<h2><span class="math inline">\(t\)</span>-test and approximation</h2>
<ol type="1">
<li>We will consider the same statistic <span class="math inline">\(T = \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{S^2}}\)</span>.</li>
<li><span class="math inline">\(\xi := \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{\sigma^2}} \stackrel{d}{\rightarrow} \mathcal{N}(0, 1)\)</span>. Under the CLT, the convergence is only under the <a href="https://en.wikipedia.org/wiki/Convergence_in_distribution">distribution</a>.</li>
<li>Then <span class="math inline">\(T = \sqrt{n}\dfrac{\overline X - \mu_0}{\sqrt{S^2}} = \xi \cdot \sqrt{\dfrac{\sigma^2}{S^2}}\)</span>. Let’s denote <span class="math inline">\(\phi := \sqrt{\dfrac{\sigma^2}{S^2}}\)</span>
<ul>
<li>Do you remember at the beginning of the lecture that <span class="math inline">\(S^2\)</span> is the best estimate for the variance? Another way to write this is: <span class="math inline">\(S^2\)</span> <a href="https://en.wikipedia.org/wiki/Convergence_of_random_variables#Convergence_in_probability">converges in probability</a> to <span class="math inline">\(\sigma^2\)</span>. That is, <span class="math inline">\(S^2 \stackrel{p}{\rightarrow} \sigma^2\)</span></li>
<li>And in this case, there is a <a href="https://en.wikipedia.org/wiki/Continuous_mapping_theorem">theorem</a> that states that <span class="math inline">\(\phi = \dfrac{\sigma^2}{S^2} \stackrel{p}{\rightarrow} 1\)</span>.</li>
</ul></li>
<li><span class="math inline">\(T = \xi \cdot \phi\)</span>.
<ul>
<li><span class="math inline">\(\xi \stackrel{d}{\rightarrow} \mathcal{N}(0, 1)\)</span></li>
<li><span class="math inline">\(\phi \stackrel{p}{\rightarrow} 1\)</span></li>
<li>And here another <a href="https://en.wikipedia.org/wiki/Slutsky%27s_theorem">theorem</a> comes into play: <span class="math inline">\(T = \xi \cdot \phi \stackrel{d}{\rightarrow} 1\cdot \mathcal{N}(0, 1)\)</span>. This is the same convergence as in the CLT!</li>
<li>That is, the statistic <span class="math inline">\(T\)</span> is also normally distributed!</li>
</ul></li>
</ol>
<p><span class="hi">So, if the sample is large, we can assume that <span class="math inline">\(T(X) \overset{H_0}{\sim} \mathcal{N}(0, 1)\)</span>.</span></p>
<aside class="notes">
<p>Аргумент у три кроки. (1) За ЦГТ чисельник ξ → N(0,1) навіть для ненормальних даних. (2) S² → σ² за ймовірністю (закон великих чисел), тож множник φ=√(σ²/S²) → 1. (3) Теорема Слуцького: добуток «збіжного до N(0,1)» на «збіжне до 1» → N(0,1). Підсумок: на великій вибірці T(X) ~ N(0,1) незалежно від вихідного розподілу. Ось чому на 5000 спостережень нормальність даних уже не потрібна.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="python-and-checking" class="slide level2 tiny40">
<h2>Python and checking</h2>
<p>Let’s test our criterion on large samples:</p>
<div id="cell-sim-t-test" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb22-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="dv">2000</span></span>
<span id="cb22-4"><a href="" aria-hidden="true" tabindex="-1"></a>M <span class="op">=</span> <span class="dv">10_000</span></span>
<span id="cb22-5"><a href="" aria-hidden="true" tabindex="-1"></a>sample_distr <span class="op">=</span> <span class="dv">5</span> <span class="op">+</span> stats.expon.rvs(scale<span class="op">=</span><span class="dv">300</span>, size<span class="op">=</span><span class="dv">2000</span>)</span>
<span id="cb22-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="" aria-hidden="true" tabindex="-1"></a>idx <span class="op">=</span> np.random.randint(<span class="dv">0</span>, <span class="bu">len</span>(sample_distr), size<span class="op">=</span>(M, sample_size))</span>
<span id="cb22-8"><a href="" aria-hidden="true" tabindex="-1"></a>resamples <span class="op">=</span> sample_distr[idx]</span>
<span id="cb22-9"><a href="" aria-hidden="true" tabindex="-1"></a>T_X <span class="op">=</span> np.sqrt(sample_size) <span class="op">*</span> (resamples.mean(axis<span class="op">=</span><span class="dv">1</span>) <span class="op">-</span> sample_distr.mean()) <span class="op">/</span> resamples.std(axis<span class="op">=</span><span class="dv">1</span>, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb22-10"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">1000</span>)</span>
<span id="cb22-12"><a href="" aria-hidden="true" tabindex="-1"></a>kde <span class="op">=</span> stats.gaussian_kde(T_X)</span>
<span id="cb22-13"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-14"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.5</span>))</span>
<span id="cb22-15"><a href="" aria-hidden="true" tabindex="-1"></a>ax.hist(T_X, bins<span class="op">=</span><span class="dv">30</span>, density<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">"skyblue"</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, edgecolor<span class="op">=</span><span class="st">"white"</span>)</span>
<span id="cb22-16"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(x, kde(x),                       color<span class="op">=</span>blue, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"Empirical"</span>)</span>
<span id="cb22-17"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(x, stats.norm.pdf(x), color<span class="op">=</span>red,  lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"Theoretical"</span>)</span>
<span id="cb22-18"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Distribution of the statistic T(X)"</span>)</span>
<span id="cb22-19"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Value"</span>)</span>
<span id="cb22-20"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb22-21"><a href="" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb22-22"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb22-23"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".03-t-test_files/figure-revealjs/sim-t-test-output-1.svg" id="sim-t-test" class="quarto-figure quarto-figure-center r-stretch"><p>We can see that the distributions are the same!</p>
<aside class="notes">
<p>Емпірична перевірка теорії: беремо скошений експоненційний розподіл (типова продуктова метрика), n=2000, M=10000 ресемплів. Рахуємо T(X) щоразу. Гістограма лягає точно на N(0,1) — теорема Слуцького працює. На великій вибірці t-статистика нормальна навіть для дуже несиметричних даних.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="python-and-checking-1" class="slide level2 tiny40">
<h2>Python and checking</h2>
<p>And on the normal distribution, where were the first differences on a small sample?</p>
<div id="cell-sim-t-test-norm" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb23-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="dv">2000</span></span>
<span id="cb23-4"><a href="" aria-hidden="true" tabindex="-1"></a>M <span class="op">=</span> <span class="dv">10_000</span></span>
<span id="cb23-5"><a href="" aria-hidden="true" tabindex="-1"></a>sample_distr <span class="op">=</span> stats.norm.rvs(loc<span class="op">=</span><span class="dv">5</span>, scale<span class="op">=</span><span class="dv">3</span>, size<span class="op">=</span><span class="dv">300</span>)</span>
<span id="cb23-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="" aria-hidden="true" tabindex="-1"></a>idx <span class="op">=</span> np.random.randint(<span class="dv">0</span>, <span class="bu">len</span>(sample_distr), size<span class="op">=</span>(M, sample_size))</span>
<span id="cb23-8"><a href="" aria-hidden="true" tabindex="-1"></a>resamples <span class="op">=</span> sample_distr[idx]</span>
<span id="cb23-9"><a href="" aria-hidden="true" tabindex="-1"></a>T_X <span class="op">=</span> np.sqrt(sample_size) <span class="op">*</span> (resamples.mean(axis<span class="op">=</span><span class="dv">1</span>) <span class="op">-</span> sample_distr.mean()) <span class="op">/</span> resamples.std(axis<span class="op">=</span><span class="dv">1</span>, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb23-10"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">1000</span>)</span>
<span id="cb23-12"><a href="" aria-hidden="true" tabindex="-1"></a>kde <span class="op">=</span> stats.gaussian_kde(T_X)</span>
<span id="cb23-13"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.5</span>))</span>
<span id="cb23-15"><a href="" aria-hidden="true" tabindex="-1"></a>ax.hist(T_X, bins<span class="op">=</span><span class="dv">30</span>, density<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span><span class="st">"skyblue"</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, edgecolor<span class="op">=</span><span class="st">"white"</span>)</span>
<span id="cb23-16"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(x, kde(x),                       color<span class="op">=</span>blue, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"Empirical"</span>)</span>
<span id="cb23-17"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(x, stats.norm.pdf(x), color<span class="op">=</span>red,  lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"Theoretical"</span>)</span>
<span id="cb23-18"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Distribution of the statistic T(X)"</span>)</span>
<span id="cb23-19"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Value"</span>)</span>
<span id="cb23-20"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb23-21"><a href="" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb23-22"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb23-23"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".03-t-test_files/figure-revealjs/sim-t-test-norm-output-1.svg" id="sim-t-test-norm" class="quarto-figure quarto-figure-center r-stretch"><p>That is, the first time we were unlucky because the sample size was small</p>
<aside class="notes">
<p>Контрольний експеримент: той самий нормальний розподіл, що ламав T(X) на n=7, але тепер вибірка велика. Тепер усе лягає на N(0,1). Висновок-рамка для всієї лекції: проблема була НЕ в нормальності, а в <em>малому n</em>. На малій вибірці рятує точний t-розподіл; на великій — і нормальне наближення, і t дають те саме.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="confidence-interval-large-sample" class="slide level2 smaller">
<h2>Confidence interval (large sample)</h2>
<p><span class="math display">\[CI_{\mu} = \left(\overline X \pm \dfrac{z_{1 - \alpha/2} \sqrt{S^2}}{\sqrt{n}} \right)\]</span></p>
<div id="ci-expon" class="cell columns column-output-location" data-execution_count="17">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb24-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="" aria-hidden="true" tabindex="-1"></a>sample <span class="op">=</span> stats.expon.rvs(scale<span class="op">=</span><span class="dv">300</span>, size<span class="op">=</span><span class="dv">2000</span>)</span>
<span id="cb24-4"><a href="" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb24-5"><a href="" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(sample)</span>
<span id="cb24-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="" aria-hidden="true" tabindex="-1"></a>z_crit <span class="op">=</span> stats.norm.ppf(<span class="dv">1</span> <span class="op">-</span> alpha <span class="op">/</span> <span class="dv">2</span>)</span>
<span id="cb24-8"><a href="" aria-hidden="true" tabindex="-1"></a>manual_ci <span class="op">=</span> sample.mean() <span class="op">+</span> np.array([<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>]) <span class="op">*</span> z_crit <span class="op">*</span> sample.std(ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np.sqrt(n)</span>
<span id="cb24-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Manual CI: </span><span class="sc">{</span>manual_ci<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb24-10"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="" aria-hidden="true" tabindex="-1"></a>ci <span class="op">=</span> stats.ttest_1samp(sample, popmean<span class="op">=</span><span class="dv">0</span>).confidence_interval(confidence_level<span class="op">=</span><span class="dv">1</span> <span class="op">-</span> alpha)</span>
<span id="cb24-12"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"scipy CI:  [</span><span class="sc">{</span>ci<span class="sc">.</span>low<span class="sc">:.2f}</span><span class="ss">, </span><span class="sc">{</span>ci<span class="sc">.</span>high<span class="sc">:.2f}</span><span class="ss">]"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>Manual CI: [287.85114264 314.43475287]
scipy CI:  [287.84, 314.44]</code></pre>
</div>
</div></div>
<aside class="notes">
<p>На великій вибірці CI можна будувати через z-квантиль (нормальне наближення). Порівнюємо з <code>ttest_1samp</code> (який використовує t) — на n=2000 t≈z, тож інтервали практично збігаються. Це ілюструє: для великих n вибір між t і z не має практичного значення.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="task-ci-for-startup-profit" class="slide level2 smaller">
<h2>📈 Task: CI for startup profit</h2>
<div id="ci-profit" class="cell columns column-output-location" data-execution_count="18">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb26-2"><a href="" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">len</span>(profits)</span>
<span id="cb26-3"><a href="" aria-hidden="true" tabindex="-1"></a>z_crit <span class="op">=</span> stats.norm.ppf(<span class="dv">1</span> <span class="op">-</span> alpha <span class="op">/</span> <span class="dv">2</span>)</span>
<span id="cb26-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="" aria-hidden="true" tabindex="-1"></a>values <span class="op">=</span> profits[<span class="st">"profit"</span>].to_numpy()</span>
<span id="cb26-6"><a href="" aria-hidden="true" tabindex="-1"></a>manual_ci <span class="op">=</span> values.mean() <span class="op">+</span> np.array([<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>]) <span class="op">*</span> z_crit <span class="op">*</span> values.std(ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np.sqrt(n)</span>
<span id="cb26-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Manual CI: </span><span class="sc">{</span>manual_ci<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb26-8"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="" aria-hidden="true" tabindex="-1"></a>ci <span class="op">=</span> stats.ttest_1samp(values, popmean<span class="op">=</span><span class="dv">0</span>).confidence_interval(confidence_level<span class="op">=</span><span class="dv">1</span> <span class="op">-</span> alpha)</span>
<span id="cb26-10"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"scipy CI:  [</span><span class="sc">{</span>ci<span class="sc">.</span>low<span class="sc">:.2f}</span><span class="ss">, </span><span class="sc">{</span>ci<span class="sc">.</span>high<span class="sc">:.2f}</span><span class="ss">]"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>Manual CI: [ 14.03617262 102.93742738]
scipy CI:  [14.03, 102.95]</code></pre>
</div>
</div></div>
<p>Yes, the revenue is positive! So we found investors for our startup 🫡.</p>
<aside class="notes">
<p>Фінал кур’єрської задачі: 95% CI для середнього прибутку. Інтервал повністю додатний — нуль у нього не входить → відхиляємо H₀, середній прибуток значуще &gt; 0. Бізнес-висновок: стартап прибутковий, інвестори дають гроші. Звертаємо увагу — той самий висновок можна було б отримати й через p-value тесту; CI додає оцінку <em>величини</em> ефекту.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="t-test-vs.-t-test" class="slide level2 tiny">
<h2><span class="math inline">\(t'\)</span>-test vs.&nbsp;<span class="math inline">\(t\)</span>-test</h2>
<p>To begin with, let’s define when it is better to use which criterion?</p>
<ol type="1">
<li>If the sample size is 60, then <span class="math inline">\(t_{59} \approx \mathcal{N}(0, 1)\)</span>.
<ul>
<li>Let’s look at the Student’s and normal distributions:</li>
</ul></li>
</ol>
<div id="cell-t-vs-z" class="cell columns column-output-location" data-fig-height="7" data-execution_count="19">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> <span class="dv">60</span> <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb28-2"><a href="" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">100</span>)</span>
<span id="cb28-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb28-5"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(x, stats.t.pdf(x, df),  color<span class="op">=</span>red,  lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"Student's"</span>)</span>
<span id="cb28-6"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(x, stats.norm.pdf(x),   color<span class="op">=</span>blue, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"Normal"</span>)</span>
<span id="cb28-7"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Student's and normal distributions"</span>)</span>
<span id="cb28-8"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Value"</span>)</span>
<span id="cb28-9"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb28-10"><a href="" aria-hidden="true" tabindex="-1"></a>ax.legend(title<span class="op">=</span><span class="st">"Distribution"</span>)</span>
<span id="cb28-11"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb28-12"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src=".03-t-test_files/figure-revealjs/t-vs-z-output-1.svg" id="t-vs-z"></p>
</figure>
</div>
</div>
</div></div>
<ul>
<li>We can see that these 2 distributions are visually identical, so it doesn’t matter whether you calculate the statistic <span class="math inline">\(T\sim \mathcal{N}(0, 1)\)</span> or <span class="math inline">\(T\sim t_n\)</span>.</li>
<li>But this does not mean that with <span class="math inline">\(N=60\)</span> <span class="math inline">\(T\)</span>-test/<span class="math inline">\(T'\)</span>-test work correctly! If the sample is not from a normal distribution, they can both still be wrong.</li>
</ul>
<aside class="notes">
<p>Практичне правило: вже з df≈59 криві t і N(0,1) візуально невідрізнні. Тобто на n≥60 не важливо, який квантиль брати. Застереження (важливе!): збіг t і z НЕ гарантує коректності тесту — якщо дані ненормальні й вибірка мала, обидва варіанти помиляться. Великий n рятує через ЦГТ, а не через вибір розподілу.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="t-test-vs.-t-test-1" class="slide level2 tiny40">
<h2><span class="math inline">\(t'\)</span>-test vs.&nbsp;<span class="math inline">\(t\)</span>-test</h2>
<ol start="2" type="1">
<li>If the sample is less than 60, it is safer to use the <span class="math inline">\(t\)</span>-test than the <span class="math inline">\(t'\)</span>-test.
<ul>
<li><strong>The FPR of the <span class="math inline">\(t\)</span>-test will always be smaller than that of the <span class="math inline">\(t'\)</span>-test</strong>.
<ul>
<li>FPR is affected by the percentage of cases <span class="math inline">\(p\)</span>-value &lt; <span class="math inline">\(\alpha\)</span>. In <span class="math inline">\(t\)</span>-test <span class="math inline">\(p\)</span>-value <span class="math inline">\(\geq\)</span> <span class="math inline">\(t'\)</span>-test <span class="math inline">\(p\)</span>-value.</li>
<li><code>pvalue = stats.t.cdf(x, df)</code> or <code>pvalue = stats.norm.cdf(x)</code>. So the heavier the tail of the distribution, the larger the <span class="math inline">\(p\)</span>-value. Now let’s look at an example:</li>
</ul></li>
</ul></li>
</ol>
<div id="cell-t-test-vs-tprime" class="cell" data-fig-height="11" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameters</span></span>
<span id="cb29-2"><a href="" aria-hidden="true" tabindex="-1"></a>df_array <span class="op">=</span> [<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>]</span>
<span id="cb29-3"><a href="" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">100</span>)</span>
<span id="cb29-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="dv">6</span>))</span>
<span id="cb29-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># CDF for the t-distribution at several degrees of freedom</span></span>
<span id="cb29-8"><a href="" aria-hidden="true" tabindex="-1"></a>palette <span class="op">=</span> [red, blue, green, purple]</span>
<span id="cb29-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> d, color <span class="kw">in</span> <span class="bu">zip</span>(df_array, palette):</span>
<span id="cb29-10"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.plot(x, stats.t.cdf(x, df<span class="op">=</span>d), color<span class="op">=</span>color, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="ss">f"t(df=</span><span class="sc">{</span>d<span class="sc">}</span><span class="ss">)"</span>)</span>
<span id="cb29-11"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># CDF for the normal distribution</span></span>
<span id="cb29-13"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(x, stats.norm.cdf(x), color<span class="op">=</span><span class="st">"black"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"N(0, 1)"</span>)</span>
<span id="cb29-14"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-15"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"CDF distribution for t and normal distributions"</span>)</span>
<span id="cb29-16"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"X"</span>)</span>
<span id="cb29-17"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"CDF"</span>)</span>
<span id="cb29-18"><a href="" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb29-19"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb29-20"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

<p>The Student’s distribution with infinity degrees of freedom is a normal distribution: <span class="math inline">\(t_{\infty} = \mathcal{N}(0, 1)\)</span>.</p>
<aside class="notes">
<p>Чому t «безпечніший» на малих n: у нього важчі хвости → p-value більший → рідше хибно відхиляємо H₀ (менший FPR). На графіку видно: що менше df, то нижче CDF у лівому хвості (наприклад t(df=2) найдалі від чорної N(0,1)); зі зростанням df крива t наближається до нормальної. У границі t∞ = N(0,1). Тобто t-тест ніколи не «оптимістичніший» за t’-тест.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="t-test-vs.-t-test-1-output" class="slide level2 tiny40 output-location-slide"><h2><span class="math inline">\(t'\)</span>-test vs.&nbsp;<span class="math inline">\(t\)</span>-test</h2><div class="cell output-location-slide" data-fig-height="11" data-execution_count="20">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src=".03-t-test_files/figure-revealjs/t-test-vs-tprime-output-1.svg" id="t-test-vs-tprime"></p>
</figure>
</div>
</div>
</div></section><section id="conclusions" class="slide level2">
<h2>Conclusions</h2>
<p>We can see that we can use <span class="math inline">\(t\)</span>-test everywhere (and <span class="math inline">\(t'\)</span>-test not always), and it is safer for small samples. <strong>That is why <span class="math inline">\(t\)</span>-test has become much more popular than <span class="math inline">\(t'\)</span>-test</strong>. But <span class="math inline">\(t'\)</span>-test can also be useful in practice:</p>
<ul>
<li>You don’t have to think about degrees of freedom during implementation.</li>
<li>It will be much easier to write such a criterion in SQL: you can use table values in the code to understand whether the criterion is rejected.</li>
<li>It’s easier to do various theoretical calculations.</li>
<li>It’s harder to make a mistake during implementation.</li>
</ul>
<aside class="notes">
<p>Підсумок порівняння: t-тест універсальніший і безпечніший на малих вибірках — тому він де-факто стандарт. Але t’-тест (нормальне наближення) теж має місце: не треба думати про ступені свободи, легше зашити в SQL (фіксоване критичне значення 1.96), простіше для теоретичних викладок і важче помилитись в імплементації. На великих n вони еквівалентні — обирай за зручністю.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="two-sample-t-test.-the-task-of-ab-testing" class="title-slide slide level1 center" data-background-iframe=".03-t-test_files/libs/colored-particles/index.html">
<h1>Two-sample <span class="math inline">\(t\)</span>-test. The task of AB testing</h1>

</section>
<section id="task-3" class="slide level2">
<h2>📊 Task</h2>
<blockquote>
<p>We have promotion services on our website. We want to start giving discounts on them to attract more people and start earning more money. To do this, we decided to conduct an AB test: We did not give discounts to one half of the users, and in the other half, we gave discounts to all new users. We need to understand whether we started to earn more money.</p>
</blockquote>
<p>This time we have 2 samples: <span class="math inline">\(A\)</span> - control, and <span class="math inline">\(B\)</span> - test.</p>
<aside class="notes">
<p>Перехід до двовибіркового t-тесту — пряма аналогія з двовибірковим Z-тестом для пропорцій з минулої лекції, але тепер метрика неперервна (виторг). A/B-тест зі знижками: контроль (без знижки) проти тесту (зі знижкою). Замість порівняння з фіксованим μ₀ порівнюємо два «живих» середніх, обидва з шумом.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="task-4" class="slide level2 tiny40">
<h2>📊 Task</h2>
<p><span class="math display">\[H_0: \mathbb{E} A = \mathbb{E} B \; \text{vs.} \; H_1: \mathbb{E}A &lt; \mathbb{E} B\]</span></p>
<div class="columns">
<div class="column" style="width:50%;">
<ol type="1">
<li><strong>Both samples are normal</strong>.</li>
</ol>
<p>Then there are 2 criteria depending on our knowledge of variance:</p>
<ul>
<li><p><span class="math inline">\(\sigma^2_A = \sigma^2_B\)</span>.</p>
<p>Then:</p>
<ul>
<li><span class="math inline">\(S^2_{full} = \dfrac{(N - 1)S^2_A + (M - 1)S^2_B}{N + M - 2}\)</span>, where N, M are the size of the control and test, respectively. And the criterion is as follows:</li>
<li><span class="math inline">\(T(A, B) = \dfrac{\overline A - \overline B}{S_{full}\sqrt{1/N + 1/M}} \overset{H_0}{\sim} T_{n + m - 2}\)</span></li>
</ul></li>
<li><p><span class="math inline">\(\sigma^2_A \neq \sigma^2_B\)</span>.</p>
<p>Then:</p>
<ul>
<li><span class="math inline">\(T(A, B) = \dfrac{\overline A - \overline B}{\sqrt{S^2_{A}/N + S^2_{B}/M}} \overset{H_0}{\sim} T_{v}\)</span></li>
<li>where <span class="math inline">\(v = \dfrac{\left(\dfrac{S^2_{A}}{N} + \dfrac{S^2_{B}}{M} \right)^2}{\left(\dfrac{(S^2_{A})^2}{N^2(N - 1)} + \dfrac{(S^2_{B})^2}{M^2(M-1)} \right)}\)</span></li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<ol start="2" type="1">
<li><strong>At least 1 sample is abnormal</strong>.</li>
</ol>
<p>Then the normal approximation with a large sample size, the <span class="math inline">\(t'\)</span>-test criterion, comes into play:</p>
<ul>
<li><span class="math inline">\(T(A, B) = \dfrac{\overline A - \overline B}{\sqrt{S^2_{A}/N + S^2_{B}/M}} \overset{H_0}{\sim} \mathcal{N}(0, 1)\)</span></li>
</ul>
</div></div>
<aside class="notes">
<p>Карта випадків. Якщо обидві вибірки нормальні: при рівних дисперсіях — pooled-варіант з S²_full і df=N+M−2; при різних — Welch з апроксимацією Саттертвейта для ступенів свободи v (страшна формула, але її рахує бібліотека). Якщо хоч одна ненормальна — рятує великий n і нормальне наближення (той самий аргумент Слуцького). На практиці майже завжди беруть Welch (<code>equal_var=False</code>) — він безпечніший.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="python-and-the-two-sample-t-test" class="slide level2 tiny">
<h2>Python and the two-sample <span class="math inline">\(t\)</span>-test</h2>
<div id="ttest_ind-sim" class="cell columns column-output-location" data-execution_count="21">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb30-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Data generation</span></span>
<span id="cb30-4"><a href="" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> stats.expon.rvs(scale<span class="op">=</span><span class="dv">1100</span>, size<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb30-5"><a href="" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> stats.norm.rvs(loc<span class="op">=</span><span class="dv">980</span>, scale<span class="op">=</span><span class="dv">30</span>, size<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb30-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># Welch's t-test (variances not assumed equal)</span></span>
<span id="cb30-8"><a href="" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> stats.ttest_ind(X, Y, alternative<span class="op">=</span><span class="st">"greater"</span>, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb30-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"t-statistic: </span><span class="sc">{</span>result<span class="sc">.</span>statistic<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb30-10"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-value:     </span><span class="sc">{</span>result<span class="sc">.</span>pvalue<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>t-statistic: 2.5646
p-value:     0.0052</code></pre>
</div>
</div></div>
<p><br></p>
<div id="ttest_ind-sim-ci" class="cell" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="" aria-hidden="true" tabindex="-1"></a>ci <span class="op">=</span> result.confidence_interval(confidence_level<span class="op">=</span><span class="fl">0.95</span>)</span>
<span id="cb32-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"95% CI for the difference: [</span><span class="sc">{</span>ci<span class="sc">.</span>low<span class="sc">:.2f}</span><span class="ss">, </span><span class="sc">{</span>ci<span class="sc">.</span>high<span class="sc">:.2f}</span><span class="ss">]"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>95% CI for the difference: [31.07, inf]</code></pre>
</div>
</div>
<aside class="notes">
<p>Реалізація через <code>stats.ttest_ind</code> з <code>equal_var=False</code> (Welch) — це двовибірковий аналог <code>ttest_1samp</code>. Дані навмисно різні за формою: X експоненційний (важкий хвіст), Y нормальний — але n=1000 в кожній групі, тож наближення працює. <code>alternative="greater"</code> перевіряє H₁: середнє A &gt; B. Бібліотека сама рахує і статистику, і df Велча, і CI для різниці середніх.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="mde-for-the-t-test." class="title-slide slide level1 center" data-background-iframe=".03-t-test_files/libs/colored-particles/index.html">
<h1>MDE for the <span class="math inline">\(t\)</span>-test.</h1>

</section>
<section id="recalling-mde" class="slide level2 tiny">
<h2>Recalling MDE</h2>
<p>The <strong>MDE</strong> is the true value of the effect such that our chance of detecting it is equal to <span class="math inline">\(1-\beta\)</span> when using our criterion.</p>
<p>What does MDE depend on?</p>
<ul>
<li>Error of the 1st kind, or <span class="math inline">\(\alpha\)</span>.
<ul>
<li>For example, if <span class="math inline">\(\alpha = 1\)</span>, we will find an effect even with a sample size of 1 (we will just always reject the 0 hypothesis). And if <span class="math inline">\(\alpha = 0\)</span>, we will never detect an effect.</li>
</ul></li>
<li>Power, or <span class="math inline">\(1 - \beta\)</span>.
<ul>
<li>It follows from the definition itself</li>
</ul></li>
<li>From noise in the data, or from variance.
<ul>
<li>The noisier the data, as we know, the wider the confidence interval. This means that it is more difficult to accurately predict the true effect, so the MDE will be larger.</li>
</ul></li>
<li>Sample size.
<ul>
<li>We are interested not just in the variance in the data, but in the variance of the mean: by the same token, it should be as small as possible. And what is the variance of the mean? It is <span class="math inline">\(\dfrac{\sigma^2}{N}\)</span>, so MDE also depends on the sample size.</li>
</ul></li>
</ul>
<aside class="notes">
<p>MDE (minimum detectable effect) — найменший ефект, який ми зможемо зловити з потужністю 1−β. Чотири залежності: ↑α → легше «знайти» ефект (але більше хибних), ↑потужність → треба більший MDE або n, ↑шум (σ²) → ширший CI → більший MDE, ↑n → менша дисперсія середнього σ²/N → менший MDE. Це фундамент планування A/B-тесту: рахуємо потрібний n ДО експерименту.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="task-5" class="slide level2 tiny">
<h2>📊 Task</h2>
<p>First, let’s define the hypothesis to be tested:</p>
<ul>
<li><span class="math inline">\(H_0: \mu_0 = 0\ vs. \ H_1: \mu_0 &gt; 0\)</span></li>
</ul>
<p>We define.</p>
<ul>
<li><span class="math inline">\(S^2_{\mu} := \dfrac{S^2}{N}\)</span> — estimate of the variance of the mean.</li>
<li><span class="math inline">\(S_{\mu} = \sqrt{\dfrac{S^2}{N}}\)</span> — the estimate of the standard deviation of the mean, or SEM.</li>
</ul>
<p>Now we know that</p>
<ul>
<li><span class="math inline">\(\overline X \sim \mathcal{N}(\mu, S^2_{\mu})\)</span></li>
</ul>
<p>We need to find <span class="math inline">\(MDE=m\)</span>, such that:</p>
<ul>
<li>if <span class="math inline">\(\overline X \sim \mathcal{N}(m, S^2_{\mu})\)</span>, then in <span class="math inline">\(1-\beta\)</span> percent of cases the criterion will be rejected. Check the power.</li>
<li>If <span class="math inline">\(\overline X \sim \mathcal{N}(0, S^2_{\mu})\)</span>, then the criterion will be rejected for it in <span class="math inline">\(\alpha\)</span> percent of cases. Let’s check the FPR.</li>
</ul>
<aside class="notes">
<p>Постановка для виведення MDE. Вводимо SEM = √(S²/N) — стандартну похибку середнього. Середнє розподілене нормально навколо істинного μ з дисперсією S²/N. Шукаємо такий зсув m, щоб дві умови виконувались одночасно: під H₁ (середнє=m) тест відхиляє в 1−β випадків, під H₀ (середнє=0) — лише в α. Два розподіли середніх, що «розповзаються» на відстань MDE.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="python-mde" class="slide level2">
<h2>Python &amp; MDE</h2>
<p><span class="math display">\[\text{MDE} = (z_{1 - \alpha} + z_{1 - \beta}) \cdot \sqrt{\dfrac{S^2}{N}}\]</span></p>
<p>where <span class="math inline">\(z_{1 - \alpha}\)</span> and <span class="math inline">\(z_{1 - \beta}\)</span> are quantiles of the distribution <span class="math inline">\(\mathcal{N}(0, 1)\)</span>.</p>
<div id="mde" class="cell" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="" aria-hidden="true" tabindex="-1"></a>profits <span class="op">=</span> pd.read_csv(<span class="st">"data/profit_from_user.out"</span>, sep<span class="op">=</span><span class="vs">r"</span><span class="dv">\s</span><span class="op">+</span><span class="vs">"</span>,</span>
<span id="cb34-2"><a href="" aria-hidden="true" tabindex="-1"></a>                      header<span class="op">=</span><span class="va">None</span>, names<span class="op">=</span>[<span class="st">"profit"</span>])</span>
<span id="cb34-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb34-5"><a href="" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb34-6"><a href="" aria-hidden="true" tabindex="-1"></a>beta <span class="op">=</span> <span class="fl">0.2</span></span>
<span id="cb34-7"><a href="" aria-hidden="true" tabindex="-1"></a>S2 <span class="op">=</span> profits[<span class="st">"profit"</span>].var(ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb34-8"><a href="" aria-hidden="true" tabindex="-1"></a>A_mean <span class="op">=</span> profits[<span class="st">"profit"</span>].mean()</span>
<span id="cb34-9"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="" aria-hidden="true" tabindex="-1"></a>mde <span class="op">=</span> (stats.norm.ppf(<span class="dv">1</span> <span class="op">-</span> alpha) <span class="op">+</span> stats.norm.ppf(<span class="dv">1</span> <span class="op">-</span> beta)) <span class="op">*</span> np.sqrt(S2 <span class="op">/</span> N)</span>
<span id="cb34-11"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MDE: </span><span class="sc">{</span>mde<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>MDE: 126.0953</code></pre>
</div>
</div>
<aside class="notes">
<p>Формула MDE = (z₁₋α + z₁₋β)·SEM. Беремо z-квантилі (велика вибірка → нормальне наближення). Для α=5%, потужності 80% сума квантилів ≈ 1.645+0.842 ≈ 2.49. Множимо на SEM = √(S²/N). Рахуємо на даних кур’єрського стартапу: який мінімальний ефект ми зловимо на N=1000.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section class="slide level2">

<div id="cell-mde-plot" class="cell" data-fig-height="12" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb36-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="" aria-hidden="true" tabindex="-1"></a>sem <span class="op">=</span> np.sqrt(S2 <span class="op">/</span> N)</span>
<span id="cb36-4"><a href="" aria-hidden="true" tabindex="-1"></a>A_means <span class="op">=</span> stats.norm.rvs(loc<span class="op">=</span>A_mean,       scale<span class="op">=</span>sem, size<span class="op">=</span><span class="dv">10_000</span>)</span>
<span id="cb36-5"><a href="" aria-hidden="true" tabindex="-1"></a>B_means <span class="op">=</span> stats.norm.rvs(loc<span class="op">=</span>A_mean <span class="op">+</span> mde, scale<span class="op">=</span>sem, size<span class="op">=</span><span class="dv">10_000</span>)</span>
<span id="cb36-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> np.linspace(<span class="bu">min</span>(A_means.<span class="bu">min</span>(), B_means.<span class="bu">min</span>()),</span>
<span id="cb36-8"><a href="" aria-hidden="true" tabindex="-1"></a>                   <span class="bu">max</span>(A_means.<span class="bu">max</span>(), B_means.<span class="bu">max</span>()), <span class="dv">500</span>)</span>
<span id="cb36-9"><a href="" aria-hidden="true" tabindex="-1"></a>kde_a <span class="op">=</span> stats.gaussian_kde(A_means)</span>
<span id="cb36-10"><a href="" aria-hidden="true" tabindex="-1"></a>kde_b <span class="op">=</span> stats.gaussian_kde(B_means)</span>
<span id="cb36-11"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-12"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="dv">6</span>))</span>
<span id="cb36-13"><a href="" aria-hidden="true" tabindex="-1"></a>ax.fill_between(grid, kde_a(grid), color<span class="op">=</span>red,   alpha<span class="op">=</span><span class="fl">0.6</span>, label<span class="op">=</span><span class="st">"Control"</span>)</span>
<span id="cb36-14"><a href="" aria-hidden="true" tabindex="-1"></a>ax.fill_between(grid, kde_b(grid), color<span class="op">=</span>green, alpha<span class="op">=</span><span class="fl">0.6</span>, label<span class="op">=</span><span class="st">"Test"</span>)</span>
<span id="cb36-15"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axvline(A_mean,       color<span class="op">=</span><span class="st">"black"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb36-16"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axvline(A_mean <span class="op">+</span> mde, color<span class="op">=</span><span class="st">"black"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb36-17"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axvline(A_mean <span class="op">+</span> stats.norm.ppf(<span class="dv">1</span> <span class="op">-</span> alpha) <span class="op">*</span> sem,</span>
<span id="cb36-18"><a href="" aria-hidden="true" tabindex="-1"></a>           color<span class="op">=</span>red_pink, linestyle<span class="op">=</span><span class="st">":"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"Critical value"</span>)</span>
<span id="cb36-19"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"MDE for the t-test"</span>)</span>
<span id="cb36-20"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Value"</span>)</span>
<span id="cb36-21"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Density"</span>)</span>
<span id="cb36-22"><a href="" aria-hidden="true" tabindex="-1"></a>ax.legend(title<span class="op">=</span><span class="st">"Group"</span>)</span>
<span id="cb36-23"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb36-24"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

<aside class="notes">
<p>Візуалізація MDE: червоний розподіл — середнє контролю навколо A_mean, зелений — тесту, зсунутий рівно на MDE. Пунктирні лінії — центри обох. Рожева пунктирна — критичне значення тесту (поріг відхилення під α). Площа зеленого праворуч від рожевої лінії = потужність (1−β=80%); площа червоного праворуч від неї = α=5%. Якщо справжній ефект = MDE, ми ловимо його у 80% випадків.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="" class="slide level2 output-location-slide"><div class="cell output-location-slide" data-fig-height="12" data-execution_count="24">
<div class="cell-output cell-output-display">
<div>
<figure>
<p><img data-src=".03-t-test_files/figure-revealjs/mde-plot-output-1.svg" id="mde-plot"></p>
</figure>
</div>
</div>
</div></section><section id="python-mde-1" class="slide level2 smaller">
<h2>Python &amp; MDE</h2>
<p><span class="math inline">\(N = 1000\)</span>, <span class="math inline">\(\alpha=5\)</span>%, <span class="math inline">\(1-\beta=80\)</span>%, how do you find <span class="math inline">\(S^2\)</span>?</p>
<p>In practice, there are 3 ways:</p>
<ul>
<li>Estimate on historical data. In this case, it is not suitable because there was no startup before.</li>
<li>Estimate using similar data.</li>
<li>Estimate it theoretically. The worst way that works if the first 2 don’t work.</li>
</ul>
<aside class="notes">
<p>Практичне питання: звідки взяти S² ДО експерименту, якщо даних ще нема? Три шляхи за спаданням якості: (1) історичні дані свого продукту — тут не підходить, стартапу ще не було; (2) схожі дані (конкуренти, аналогічні метрики); (3) теоретична оцінка — найгірший варіант, лише коли перші два недоступні. Це реальний біль продуктових аналітиків при плануванні тестів.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="mde-and-sample-size" class="slide level2 smaller">
<h2>MDE and sample size</h2>
<p>For us, this is too large an MDE: we want it to be <span class="math inline">\(\leq\)</span> 100, and we assume that this is the most likely true effect based on experience.</p>
<p>Now let’s solve the opposite problem: We know MDE = 100, <span class="math inline">\(\alpha=5\)</span>%, <span class="math inline">\(1-\beta=80\)</span>%, <span class="math inline">\(S^2\)</span>, what is <span class="math inline">\(N\)</span>? Let’s derive it from the MDE formula:</p>
<p><span class="math display">\[N = \left(\dfrac{z_{1 - \alpha} + z_{1 - \beta}}{\text{MDE}}\right)^2 S^2\]</span></p>
<div id="mde-n" class="cell" data-execution_count="25">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="" aria-hidden="true" tabindex="-1"></a>mde <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb37-2"><a href="" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> (stats.norm.ppf(<span class="dv">1</span> <span class="op">-</span> alpha) <span class="op">+</span> stats.norm.ppf(<span class="dv">1</span> <span class="op">-</span> beta))<span class="op">**</span><span class="dv">2</span> <span class="op">*</span> S2 <span class="op">/</span> mde<span class="op">**</span><span class="dv">2</span></span>
<span id="cb37-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample size: </span><span class="sc">{</span>N<span class="sc">:.0f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample size: 1590</code></pre>
</div>
</div>
<aside class="notes">
<p>Обернена задача — найчастіша на практиці: фіксуємо потрібний MDE (100 ₴, з досвіду — реалістичний ефект), α, потужність, і рахуємо потрібний N. Виводимо N з формули MDE (підносимо до квадрата). Це і є відповідь на питання «скільки користувачів набрати в A/B-тест». Якщо отримане N завелике для бізнесу — доведеться або підвищити MDE, або знизити потужність.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section id="questions" class="title-slide slide level1 unnumbered unlisted center" data-background-iframe=".03-t-test_files/libs/colored-particles/index.html">
<h1>Questions?</h1>
<p><iconify-icon inline="" icon="solar:book-bold"></iconify-icon> <a href="https://teaching.kse.org.ua/course/view.php?id=4049">Course materials</a></p>
<p><iconify-icon inline="" icon="mdi:envelope"></iconify-icon> imiroshnychenko@kse.org.ua</p>
<p><iconify-icon inline="" icon="ic:baseline-telegram"></iconify-icon> <a href="https://t.me/araprof"><span class="citation" data-cites="araprof">@araprof</span></a></p>
<p><iconify-icon inline="" icon="mdi:youtube"></iconify-icon> <a href="https://www.youtube.com/@datamirosh"><span class="citation" data-cites="datamirosh">@datamirosh</span></a></p>
<p><iconify-icon inline="" icon="mdi:linkedin"></iconify-icon> <a href="https://www.linkedin.com/in/ihormiroshnychenko/">@ihormiroshnychenko</a></p>
<p><iconify-icon inline="" icon="mdi:github"></iconify-icon> <a href="https://github.com/Aranaur">@aranaur</a></p>
<p><iconify-icon inline="" icon="ion:home"></iconify-icon> <a href="https://aranaur.rbind.io">aranaur.rbind.io</a></p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="img/kse.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://teaching.kse.org.ua/course/view.php?id=4049">🔗Applied Statistics</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src=".03-t-test_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src=".03-t-test_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src=".03-t-test_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src=".03-t-test_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src=".03-t-test_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src=".03-t-test_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src=".03-t-test_files/libs/revealjs/plugin/verticator/verticator.js"></script>
  <script src=".03-t-test_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src=".03-t-test_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src=".03-t-test_files/libs/revealjs/plugin/search/search.js"></script>
  <script src=".03-t-test_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src=".03-t-test_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'verticator': {"themetag":"h1","color":"","inversecolor":"","skipuncounted":false,"clickable":true,"position":"auto","offset":"3vmin","autogenerate":true,"tooltip":false,"scale":1},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'h.v',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'default',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: true,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: true,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1350,

        height: 759.375,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, Verticator, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>