<!DOCTYPE html>
<html lang="en"><head>
<script src=".06-chi_files/libs/clipboard/clipboard.min.js"></script>
<script src=".06-chi_files/libs/quarto-html/tabby.min.js"></script>
<script src=".06-chi_files/libs/quarto-html/popper.min.js"></script>
<script src=".06-chi_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href=".06-chi_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href=".06-chi_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href=".06-chi_files/libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src=".06-chi_files/libs/quarto-contrib/iconify-1.0.7/iconify-icon.min.js"></script><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Ihor Miroshnychenko">
  <title>\chi^2 tests for categorical data</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href=".06-chi_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href=".06-chi_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href=".06-chi_files/libs/revealjs/dist/theme/quarto-8a52321a21477e1bb40c2cb18c896737.css">
  <link href=".06-chi_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href=".06-chi_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href=".06-chi_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href=".06-chi_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href=".06-chi_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href=".06-chi_files/libs/revealjs/plugin/verticator/verticator.css" rel="stylesheet">
  <link href=".06-chi_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-iframe=".06-chi_files/libs/colored-particles/index.html" class="quarto-title-block center">
  <h1 class="title"><span class="math inline">\(\chi^2\)</span> tests for categorical data</h1>
  <p class="subtitle">Applied Statistics</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Ihor Miroshnychenko 
</div>
        <p class="quarto-title-affiliation">
            Kyiv School of Economics
          </p>
    </div>
</div>

</section><section id="TOC">
<nav role="doc-toc"> 
<h2 id="toc-title">Table of contents</h2>
<ul>
<li><a href="#/why-count-categories" id="/toc-why-count-categories">Why count categories?</a></li>
<li><a href="#/goodness-of-fit-test" id="/toc-goodness-of-fit-test">Goodness-of-fit test</a></li>
<li><a href="#/test-of-independence" id="/toc-test-of-independence">Test of independence</a></li>
<li><a href="#/test-of-homogeneity" id="/toc-test-of-homogeneity">Test of homogeneity</a></li>
<li><a href="#/yates-correction" id="/toc-yates-correction">Yates’ correction</a></li>
<li><a href="#/summary" id="/toc-summary">Summary</a></li>
</ul>
</nav>
</section>
<section>
<section id="why-count-categories" class="title-slide slide level1 center" data-background-iframe=".06-chi_files/libs/colored-particles/index.html">
<h1>Why count categories?</h1>

</section>
<section id="the-questions-we-keep-asking" class="slide level2 smaller">
<h2>🎯 The questions we keep asking</h2>
<p>The <span class="math inline">\(z\)</span>-, <span class="math inline">\(t\)</span>- and Kolmogorov tests all needed a <strong>numeric</strong> measurement. But a huge share of product data is just <strong>counts in categories</strong>:</p>
<ul>
<li>which weekday a user signed up on,</li>
<li>which subscription plan they chose,</li>
<li>how many sessions they had this week (0, 1, 2, 3+).</li>
</ul>
<div class="fragment">
<p>Three flavours of the <strong>same</strong> question — <em>do the observed counts match what we expected?</em></p>
<ul>
<li><strong>Goodness-of-fit:</strong> does one categorical variable follow a <em>known</em> distribution?</li>
<li><strong>Independence:</strong> are <em>two</em> categorical variables related?</li>
<li><strong>Homogeneity:</strong> do <em>several groups</em> share the same category distribution?</li>
</ul>
<aside class="notes">
<p>Усі попередні критерії (z, t, Колмогоров) вимагали ЧИСЛОВОГО виміру. Але величезна частка продуктових даних — це просто підрахунки за категоріями: день тижня реєстрації, обраний тариф, кількість сесій. Сьогодні — інструмент саме для такого. Три різновиди одного питання: чи спостережувані частоти збігаються з очікуваними. Goodness-of-fit — одна змінна проти відомого розподілу; незалежність — дві змінні пов’язані?; однорідність — кілька груп мають однаковий розподіл за категоріями. Усе зведеться до однієї статистики.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="our-running-case-a-streaming-app-growth-team" class="slide level2 smaller">
<h2>🎧 Our running case: a streaming-app growth team</h2>
<p>A music-streaming startup. The growth team brings three categorical questions:</p>
<ol type="1">
<li>New signups arrive every day — <strong>are they spread evenly across weekdays</strong>, or is some day special? → <em>goodness-of-fit</em>.</li>
<li>Is a user’s <strong>engagement level</strong> (visits per month) <strong>independent</strong> of how long they’ve been registered? → <em>independence</em>.</li>
<li>A new onboarding flow is A/B-tested — does it <strong>change the mix</strong> of plans users pick? → <em>homogeneity</em>.</li>
</ol>
<div class="fragment">
<p>One idea behind all three: <span class="hi">compare observed counts <span class="math inline">\(O\)</span> with expected counts <span class="math inline">\(E\)</span></span>.</p>
<p><span class="math display">\[
\tau = \sum_{\text{cells}} \frac{(O - E)^2}{E}.
\]</span></p>
<aside class="notes">
<p>Наскрізний кейс на всю лекцію — growth-команда стримінгового застосунку, три категоріальні питання: (1) чи рівномірно реєстрації за днями тижня — узгодженість; (2) чи незалежний рівень активності від давності реєстрації — незалежність; (3) чи змінює новий онбординг розподіл обраних тарифів — однорідність. Під капотом усе зведеться до однієї статистики: сума по клітинках (O−E)²/E, де O — спостережені частоти, E — очікувані за гіпотезою. Велика сума → дані далеко від гіпотези.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="goodness-of-fit-test" class="title-slide slide level1 center" data-background-iframe=".06-chi_files/libs/colored-particles/index.html">
<h1>Goodness-of-fit test</h1>

</section>
<section id="intuition-is-the-die-fair" class="slide level2 smaller">
<h2>🎲 Intuition: is the die fair?</h2>
<p>Before signups, the textbook intuition — a die rolled <span class="math inline">\(n = 60\)</span> times.</p>
<p><span class="math display">\[
H_0: p_1 = p_2 = \dots = p_6 = \tfrac{1}{6}
\qquad\text{vs.}\qquad
H_1: H_0 \text{ is false}.
\]</span></p>
<div id="cell-die-observed-expected" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="" aria-hidden="true" tabindex="-1"></a>faces    <span class="op">=</span> np.arange(<span class="dv">1</span>, <span class="dv">7</span>)</span>
<span id="cb1-2"><a href="" aria-hidden="true" tabindex="-1"></a>observed <span class="op">=</span> np.array([<span class="dv">5</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">20</span>])</span>
<span id="cb1-3"><a href="" aria-hidden="true" tabindex="-1"></a>n        <span class="op">=</span> observed.<span class="bu">sum</span>()</span>
<span id="cb1-4"><a href="" aria-hidden="true" tabindex="-1"></a>expected <span class="op">=</span> np.full(<span class="dv">6</span>, n <span class="op">/</span> <span class="dv">6</span>)            <span class="co"># 10 per face under H0</span></span>
<span id="cb1-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">4.2</span>))</span>
<span id="cb1-7"><a href="" aria-hidden="true" tabindex="-1"></a>ax.bar(faces <span class="op">-</span> <span class="fl">0.18</span>, observed, width<span class="op">=</span><span class="fl">0.36</span>, color<span class="op">=</span>red_pink, label<span class="op">=</span><span class="st">"observed $O$"</span>)</span>
<span id="cb1-8"><a href="" aria-hidden="true" tabindex="-1"></a>ax.bar(faces <span class="op">+</span> <span class="fl">0.18</span>, expected, width<span class="op">=</span><span class="fl">0.36</span>, color<span class="op">=</span>slate,   label<span class="op">=</span><span class="st">"expected $E$"</span>)</span>
<span id="cb1-9"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"A die rolled 60 times"</span>)<span class="op">;</span> ax.set_xlabel(<span class="st">"face"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"count"</span>)</span>
<span id="cb1-10"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(faces)<span class="op">;</span> ax.legend()</span>
<span id="cb1-11"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb1-12"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".06-chi_files/figure-revealjs/die-observed-expected-output-1.svg" id="die-observed-expected" class="quarto-figure quarto-figure-center r-stretch"><p>Face <strong>6</strong> shows up far more often than <span class="math inline">\(H_0\)</span> predicts. Is that surprising, or just luck?</p>
<aside class="notes">
<p>Класична інтуїція перед бізнес-кейсом — кубик, кинутий 60 разів. H0: усі грані рівноймовірні (по 1/6), тобто очікувано по 10 на грань. На графіку: рожеві стовпчики — спостережено, сірі — очікувано. Грань «6» випала 20 разів замість ~10. Питання критерію: це здивування чи звичайна випадковість? Щоб відповісти, потрібна одна міра відхилення спостереженого від очікуваного.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-chi2-statistic" class="slide level2 smaller">
<h2>📊 The <span class="math inline">\(\chi^2\)</span> statistic</h2>
<p>We have <strong>empirical frequencies</strong> <span class="math inline">\(n_i\)</span> and <strong>theoretical probabilities</strong> <span class="math inline">\(p_i\)</span>. Measure the total mismatch:</p>
<p><span class="math display">\[
\tau = n\sum_{i=1}^{k}\frac{\left(\frac{n_i}{n}-p_i\right)^2}{p_i}
     = \sum_{i=1}^{k}\frac{(O_i - E_i)^2}{E_i},
\qquad E_i = n\,p_i.
\]</span></p>
<div class="fragment">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Each term is a <strong>squared, standardized</strong> gap between observed and expected. Dividing by <span class="math inline">\(E_i\)</span> puts rare and common categories on the same scale — a gap of 5 means more for an expected count of 10 than for 1000.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Будуємо міру: для кожної категорії беремо (спостережено − очікувано)², ділимо на очікувано і сумуємо. Ділення на E_i — ключове: воно стандартизує, ставить рідкісні й часті категорії на одну шкалу (розрив 5 при очікуваних 10 важить більше, ніж при 1000). Дві еквівалентні форми: через частки n_i/n і ймовірності p_i, або коротко Σ(O−E)²/E. Далі — який розподіл має ця статистика при H0.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="where-does-chi2-come-from" class="slide level2 tiny">
<h2>🧮 Where does <span class="math inline">\(\chi^2\)</span> come from?</h2>
<div class="columns">
<div class="column" style="width:48%;">
<p>Take the simplest case — two outcomes, <span class="math inline">\(p_1 = p\)</span>, <span class="math inline">\(p_2 = 1-p\)</span>:</p>
<p><span class="math display">\[\tau = \frac{(n_1 - np)^2}{p(1-p)\,n} \stackrel{[1]}{\sim} \frac{(\text{Binom}(n,p)-np)^2}{p(1-p)\,n}\]</span></p>
<p><span class="math display">\[\stackrel{[2]}{\sim} \frac{\left(\mathcal{N}(np,\,np(1-p)) - np\right)^2}{p(1-p)\,n} \stackrel{[3]}{=} \mathcal{N}(0,1)^2\]</span></p>
</div><div class="column" style="width:52%;">
<ol type="1">
<li>The only random quantity is <span class="math inline">\(n_1\)</span>; under <span class="math inline">\(H_0\)</span> it is <span class="math inline">\(\text{Binom}(n,p)\)</span>.</li>
<li><strong>CLT:</strong> for large <span class="math inline">\(n\)</span>, <span class="math inline">\(\text{Binom}(n,p) \approx \mathcal{N}\!\big(np,\,np(1-p)\big)\)</span>.</li>
<li>Standardising gives <span class="math inline">\(\mathcal{N}(0,1)\)</span>, and the square of a standard normal is a <span class="math inline">\(\chi^2\)</span> with <strong>one</strong> degree of freedom.</li>
</ol>
<p><span class="math display">\[\tau \sim \chi^2_1 \;\Longrightarrow\; \tau = \sum_{i=1}^{k}\frac{(O_i-E_i)^2}{E_i} \sim \chi^2_{k-1}.\]</span></p>
</div></div>
<p><a href="https://arxiv.org/pdf/1808.09171.pdf">Full proof</a> · <span class="math inline">\(k\)</span> categories → <span class="math inline">\(k-1\)</span> degrees of freedom (the counts must sum to <span class="math inline">\(n\)</span>).</p>
<aside class="notes">
<p>Звідки χ²? Розглядаємо найпростіший випадок — дві категорії. Алгебра зводить статистику до (n₁−np)²/(p(1−p)n). Далі три кроки: [1] єдина випадкова величина n₁ при H0 біноміальна; [2] ЦГТ — біном ≈ нормальний; [3] стандартизуємо й отримуємо квадрат стандартного нормального, тобто χ² з одним ступенем свободи. Для k категорій узагальнюється до χ² з k−1 ступенями: один ступінь «з’їдає» умова, що частоти сумуються в n.&nbsp;Деталі — за посиланням; студентам важлива логіка, не повне доведення.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-chi2-distribution" class="slide level2 smaller">
<h2>📈 The <span class="math inline">\(\chi^2\)</span> distribution</h2>
<div id="cell-chi2-distribution" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="fl">0.001</span>, <span class="dv">15</span>, <span class="dv">1000</span>)</span>
<span id="cb2-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.6</span>))</span>
<span id="cb2-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> df, c <span class="kw">in</span> [(<span class="dv">1</span>, red_pink), (<span class="dv">2</span>, blue), (<span class="dv">3</span>, slate), (<span class="dv">5</span>, green), (<span class="dv">10</span>, orange)]:</span>
<span id="cb2-5"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.plot(x, chi2.pdf(x, df<span class="op">=</span>df), color<span class="op">=</span>c, lw<span class="op">=</span><span class="fl">2.2</span>, label<span class="op">=</span><span class="ss">f"df = </span><span class="sc">{</span>df<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-6"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="fl">0.5</span>)</span>
<span id="cb2-7"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="vs">r"</span><span class="dv">$</span><span class="er">\</span><span class="vs">chi</span><span class="dv">^</span><span class="vs">2</span><span class="dv">$</span><span class="vs"> probability density"</span>)<span class="op">;</span> ax.set_xlabel(<span class="st">"x"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"density"</span>)</span>
<span id="cb2-8"><a href="" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb2-9"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb2-10"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".06-chi_files/figure-revealjs/chi2-distribution-output-1.svg" id="chi2-distribution" class="quarto-figure quarto-figure-center r-stretch"><p>Right-skewed, lives on <span class="math inline">\([0, \infty)\)</span>, and <strong>shifts right</strong> as the degrees of freedom grow.</p>
<aside class="notes">
<p>Сімейство χ² для різних ступенів свободи. Ключові риси: визначений лише на невід’ємних значеннях (статистика — сума квадратів), скошений вправо, із ростом df зсувається праворуч і стає більш симетричним (наближається до нормального). Саме за цим розподілом рахуємо p-value: чим більша статистика, тим далі у правому хвості, тим менший p.&nbsp;Потрібен правильний df — для goodness-of-fit це k−1.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="algorithm" class="slide level2 smaller">
<h2>🧭 Algorithm</h2>
<ol type="1">
<li>Fix a significance level <span class="math inline">\(\alpha\)</span>.</li>
<li>Fix the discrete distribution <span class="math inline">\(\mathcal{P}\)</span> you want to test the sample against.</li>
<li>Record the sample of <span class="math inline">\(k\)</span> outcomes in a <strong>frequency table</strong>.</li>
<li>If any <strong>expected</strong> cell count is <span class="math inline">\(&lt; 5\)</span> (or <span class="math inline">\(&lt; 10\)</span> for a <span class="math inline">\(2\times1\)</span> table), <strong>merge</strong> categories until the rule holds.</li>
<li>Compute <span class="math inline">\(\tau = \sum_{i=1}^k \dfrac{(O_i - E_i)^2}{E_i}\)</span>.</li>
<li>The <span class="math inline">\(p\)</span>-value is <span class="math inline">\(P(X \geq \tau)\)</span> with <span class="math inline">\(X \sim \chi^2_{k-1}\)</span>.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(p\text{-value} \leq \alpha\)</span>.</li>
</ol>
<aside class="notes">
<p>Покроковий рецепт goodness-of-fit. Зверніть особливу увагу на крок 4 — правило очікуваних частот ≥5: χ² спирається на нормальне наближення (ЦГТ), яке ламається на малих очікуваних частотах. Якщо клітинка занадто рідкісна — об’єднуємо категорії. Решта механічна: рахуємо статистику, беремо праву хвостову ймовірність χ² з k−1 ступенями, порівнюємо з α. df тут саме k−1, а не k.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="back-to-the-die" class="slide level2 smaller">
<h2>🎲 Back to the die</h2>
<div id="die-chisquare" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># chisquare() compares observed counts to a uniform expectation by default</span></span>
<span id="cb3-2"><a href="" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> chisquare(observed)</span>
<span id="cb3-3"><a href="" aria-hidden="true" tabindex="-1"></a>k   <span class="op">=</span> <span class="bu">len</span>(observed)</span>
<span id="cb3-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"chi2      = </span><span class="sc">{</span>res<span class="sc">.</span>statistic<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb3-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"df        = </span><span class="sc">{</span>k <span class="op">-</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb3-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-value   = </span><span class="sc">{</span>res<span class="sc">.</span>pvalue<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb3-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"reject H0"</span> <span class="cf">if</span> res.pvalue <span class="op">&lt;</span> <span class="fl">0.05</span></span>
<span id="cb3-9"><a href="" aria-hidden="true" tabindex="-1"></a>      <span class="cf">else</span> <span class="st">"keep H0"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>chi2      = 13.40
df        = 5
p-value   = 0.0199
reject H0</code></pre>
</div>
</div>
<div class="fragment">
<p><span class="math inline">\(\chi^2 = 13.4\)</span> on <span class="math inline">\(5\)</span> df gives <span class="math inline">\(p\text{-value} = P(X \geq 13.4) =\)</span> 0.0199. At <span class="math inline">\(\alpha = 5\%\)</span> we <strong>reject</strong> fairness — face 6 was too much.</p>
<aside class="notes">
<p>Застосовуємо до кубика. scipy.stats.chisquare за замовчуванням порівнює спостережені частоти з рівномірним розподілом — рівно наш H0. Отримуємо χ²≈13.4, df=5, p≈0.02 &lt; 0.05 → відхиляємо гіпотезу про чесність кубика. Тобто грань «6» справді випадала надто часто, це не випадковість. Підкреслити: один рядок коду, але за ним уся побудована теорія.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="apply-signups-by-weekday" class="slide level2 smaller">
<h2>🎧 Apply: signups by weekday</h2>
<p>Are 700 new signups spread evenly across the week, or do weekends spike?</p>
<div id="signups-gof" class="cell columns column-output-location" data-execution_count="5">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="" aria-hidden="true" tabindex="-1"></a>days    <span class="op">=</span> [<span class="st">"Mon"</span>, <span class="st">"Tue"</span>, <span class="st">"Wed"</span>, <span class="st">"Thu"</span>, <span class="st">"Fri"</span>, <span class="st">"Sat"</span>, <span class="st">"Sun"</span>]</span>
<span id="cb5-2"><a href="" aria-hidden="true" tabindex="-1"></a>signups <span class="op">=</span> np.array([<span class="dv">92</span>, <span class="dv">88</span>, <span class="dv">95</span>, <span class="dv">90</span>, <span class="dv">110</span>, <span class="dv">130</span>, <span class="dv">95</span>])</span>
<span id="cb5-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> chisquare(signups)        <span class="co"># H0: uniform over 7 days</span></span>
<span id="cb5-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"n         = </span><span class="sc">{</span>signups<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"chi2      = </span><span class="sc">{</span>res<span class="sc">.</span>statistic<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb5-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"df        = </span><span class="sc">{</span><span class="bu">len</span>(days) <span class="op">-</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-value   = </span><span class="sc">{</span>res<span class="sc">.</span>pvalue<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>n         = 700
chi2      = 13.58
df        = 6
p-value   = 0.0347</code></pre>
</div>
</div></div>
<div id="cell-signups-plot" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.6</span>, <span class="fl">3.0</span>))</span>
<span id="cb7-2"><a href="" aria-hidden="true" tabindex="-1"></a>ax.bar(days, signups, color<span class="op">=</span>turquoise, label<span class="op">=</span><span class="st">"observed"</span>)</span>
<span id="cb7-3"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axhline(signups.mean(), color<span class="op">=</span>red_pink, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"expected (uniform)"</span>)</span>
<span id="cb7-4"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"signups"</span>)<span class="op">;</span> ax.legend(fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb7-5"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb7-6"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".06-chi_files/figure-revealjs/signups-plot-output-1.svg" id="signups-plot" class="quarto-figure quarto-figure-center r-stretch"><p>The weekend bump pushes <span class="math inline">\(p\)</span> below <span class="math inline">\(5\%\)</span> → signups are <strong>not</strong> uniform. Schedule campaigns accordingly.</p>
<aside class="notes">
<p>Перший бізнес-вихід: 700 реєстрацій за тиждень. H0 — рівномірно по 7 днях (по 100). chisquare ловить сплеск у п’ятницю–суботу, p&lt;0.05 → відхиляємо рівномірність. Практичний висновок для growth-команди: трафік не рівномірний, кампанії й бюджет варто планувати під вихідні. Той самий критерій, що й для кубика, лише замість граней — дні тижня. Це і є сила узагальнення.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-expected-count-rule" class="slide level2 smaller">
<h2>⚠️ The expected-count rule</h2>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The <span class="math inline">\(\chi^2\)</span> approximation relies on the CLT, which <strong>breaks for rare categories</strong>. Rule of thumb: every <strong>expected</strong> count should be <span class="math inline">\(\geq 5\)</span>.</p>
</div>
</div>
</div>
<p>If, say, “Sun” had an expected count of 2, you would <strong>merge</strong> it with a neighbour, or switch to an <strong>exact</strong> test (<code>scipy.stats.fisher_exact</code> for <span class="math inline">\(2\times2\)</span>, or a Monte-Carlo <span class="math inline">\(p\)</span>-value).</p>
<div class="fragment">
<p>Note the rule is about <strong>expected</strong> counts <span class="math inline">\(E_i\)</span>, not the observed ones — a category can be empty in the sample yet still have a large <span class="math inline">\(E_i\)</span>.</p>
<aside class="notes">
<p>Найчастіша помилка студентів — правило стосується ОЧІКУВАНИХ частот, а не спостережених. χ² — асимптотичний критерій (через ЦГТ), і на рідкісних категоріях наближення χ² погане, p-value перекошений. Тому: усі E_i ≥ 5; якщо ні — об’єднуємо категорії або беремо точний критерій (Фішера для 2×2, або Монте-Карло p-value). Спостережена клітинка може бути нульовою — це нормально, поки очікувана достатньо велика.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="does-the-test-hold-its-promises" class="slide level2 smaller">
<h2>🧪 Does the test hold its promises?</h2>
<p>Same Monte-Carlo habit as for the <span class="math inline">\(t\)</span>- and KS-tests: simulate, count rejections, add a Wilson CI.</p>
<div id="gof-mc-fn" class="cell columns column-output-location" data-execution_count="7">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gof_rejection_rate(p_true, p_null, n, n_exps<span class="op">=</span><span class="dv">2000</span>,</span>
<span id="cb8-2"><a href="" aria-hidden="true" tabindex="-1"></a>                       alpha<span class="op">=</span><span class="fl">0.05</span>, seed<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb8-3"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Goodness-of-fit chi-square via Monte Carlo.</span></span>
<span id="cb8-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co">    p_true == p_null -&gt; H0 true  -&gt; the rate is the FPR.</span></span>
<span id="cb8-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co">    p_true != p_null -&gt; H1 true  -&gt; the rate is the power.</span></span>
<span id="cb8-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb8-8"><a href="" aria-hidden="true" tabindex="-1"></a>    rng, rej <span class="op">=</span> np.random.default_rng(seed), <span class="dv">0</span></span>
<span id="cb8-9"><a href="" aria-hidden="true" tabindex="-1"></a>    p_null <span class="op">=</span> np.asarray(p_null)</span>
<span id="cb8-10"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_exps):</span>
<span id="cb8-11"><a href="" aria-hidden="true" tabindex="-1"></a>        counts <span class="op">=</span> rng.multinomial(n, p_true)</span>
<span id="cb8-12"><a href="" aria-hidden="true" tabindex="-1"></a>        rej <span class="op">+=</span> chisquare(counts, f_exp<span class="op">=</span>n <span class="op">*</span> p_null).pvalue <span class="op">&lt;=</span> alpha</span>
<span id="cb8-13"><a href="" aria-hidden="true" tabindex="-1"></a>    ci <span class="op">=</span> proportion_confint(rej, n_exps, alpha<span class="op">=</span><span class="fl">0.05</span>, method<span class="op">=</span><span class="st">"wilson"</span>)</span>
<span id="cb8-14"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> rej <span class="op">/</span> n_exps, ci</span>
<span id="cb8-15"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="" aria-hidden="true" tabindex="-1"></a>uniform <span class="op">=</span> np.full(<span class="dv">6</span>, <span class="dv">1</span> <span class="op">/</span> <span class="dv">6</span>)</span>
<span id="cb8-17"><a href="" aria-hidden="true" tabindex="-1"></a>fpr, ci <span class="op">=</span> gof_rejection_rate(uniform, uniform, n<span class="op">=</span><span class="dv">60</span>)</span>
<span id="cb8-18"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"FPR (fair die, n=60): </span><span class="sc">{</span>fpr<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb8-19"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"95% CI: (</span><span class="sc">{</span>ci[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>ci[<span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>FPR (fair die, n=60): 0.045
95% CI: (0.037, 0.056)</code></pre>
</div>
</div></div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>At <span class="math inline">\(n=60\)</span> the FPR already sits on <span class="math inline">\(\alpha\)</span> — the <span class="math inline">\(\chi^2\)</span> approximation is well calibrated even on a small sample, as long as expected counts <span class="math inline">\(\geq 5\)</span> (here <span class="math inline">\(10\)</span>).</p>
</div>
</div>
</div>
<aside class="notes">
<p>Перевикористовуємо звичку валідувати критерій Монте-Карло — як для t- і KS-тестів. Функція gof_rejection_rate: тисячі разів генерує частоти з мультиноміального розподілу, проганяє chisquare і рахує частку відхилень + інтервал Уілсона. Однакові ймовірності p_true=p_null → H0 вірна → міряємо FPR. На чесному кубику при n=60 FPR уже лягає на 5% — χ²-наближення добре каліброване навіть на малій вибірці, поки очікувані частоти ≥5 (тут по 10). Тобто правило ≥5 — це саме та межа, за якою критерій тримає обіцянку.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="power-catching-a-loaded-die" class="slide level2 smaller">
<h2>🧪 Power: catching a loaded die</h2>
<p>A subtly loaded die — face 6 has probability <span class="math inline">\(0.20\)</span> instead of <span class="math inline">\(\tfrac{1}{6}\)</span>. How large a sample do we need to notice?</p>
<div id="cell-gof-power" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="" aria-hidden="true" tabindex="-1"></a>loaded <span class="op">=</span> np.array([<span class="fl">0.12</span>, <span class="fl">0.17</span>, <span class="fl">0.17</span>, <span class="fl">0.17</span>, <span class="fl">0.17</span>, <span class="fl">0.20</span>])   <span class="co"># sums to 1</span></span>
<span id="cb10-2"><a href="" aria-hidden="true" tabindex="-1"></a>sizes  <span class="op">=</span> np.array([<span class="dv">30</span>, <span class="dv">60</span>, <span class="dv">120</span>, <span class="dv">240</span>, <span class="dv">480</span>, <span class="dv">960</span>])</span>
<span id="cb10-3"><a href="" aria-hidden="true" tabindex="-1"></a>tpr, lo, hi <span class="op">=</span> [], [], []</span>
<span id="cb10-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> nn <span class="kw">in</span> sizes:</span>
<span id="cb10-5"><a href="" aria-hidden="true" tabindex="-1"></a>    r, (l, h) <span class="op">=</span> gof_rejection_rate(loaded, uniform, n<span class="op">=</span><span class="bu">int</span>(nn))</span>
<span id="cb10-6"><a href="" aria-hidden="true" tabindex="-1"></a>    tpr.append(r)<span class="op">;</span> lo.append(l)<span class="op">;</span> hi.append(h)</span>
<span id="cb10-7"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.4</span>))</span>
<span id="cb10-9"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(sizes, tpr, color<span class="op">=</span>red_pink, lw<span class="op">=</span><span class="fl">2.5</span>, marker<span class="op">=</span><span class="st">"o"</span>, label<span class="op">=</span><span class="st">"power (TPR)"</span>)</span>
<span id="cb10-10"><a href="" aria-hidden="true" tabindex="-1"></a>ax.fill_between(sizes, lo, hi, color<span class="op">=</span>turquoise, alpha<span class="op">=</span><span class="fl">0.3</span>, label<span class="op">=</span><span class="st">"95% CI"</span>)</span>
<span id="cb10-11"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="fl">0.8</span>, color<span class="op">=</span>slate, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"80</span><span class="sc">% g</span><span class="st">old standard"</span>)</span>
<span id="cb10-12"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb10-13"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"number of rolls n"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"power"</span>)</span>
<span id="cb10-14"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Power of the goodness-of-fit test vs sample size"</span>)<span class="op">;</span> ax.legend()</span>
<span id="cb10-15"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb10-16"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".06-chi_files/figure-revealjs/gof-power-output-1.svg" id="gof-power" class="quarto-figure quarto-figure-center r-stretch"><p>A small distortion needs a <strong>large</strong> sample to be caught reliably — the same power–sample-size trade-off as every other test.</p>
<aside class="notes">
<p>Тепер кубик трохи підроблений: грань «6» має ймовірність 0.20 замість 1/6, решта злегка занижені. Потужність росте з кількістю кидків і лише на кількох сотнях перетинає золотий стандарт 80%. Мораль та сама, що в усіх критеріях: маленьке відхилення вимагає ВЕЛИКОЇ вибірки, щоб його надійно зловити. Це місток до планування розміру вибірки — знаючи очікуваний ефект, підбираємо n під потрібну потужність.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="test-of-independence" class="title-slide slide level1 center" data-background-iframe=".06-chi_files/libs/colored-particles/index.html">
<h1>Test of independence</h1>

</section>
<section id="the-task" class="slide level2 smaller">
<h2>🔗 The task</h2>
<blockquote>
<p>The growth team wants to understand the <strong>user profile</strong> better.</p>
</blockquote>
<blockquote>
<p>We study <strong>engagement</strong> — how many times a month a user visits — against <strong>how long</strong> they have been registered.</p>
</blockquote>
<blockquote>
<p>Question: is an <span class="hi">active user’s visit frequency</span> <strong>independent</strong> of <span class="hi-slate">how long they have been registered</span>?</p>
</blockquote>
<div class="fragment">
<p>Two categorical variables on the <strong>same</strong> users → a <strong>contingency table</strong>.</p>
<aside class="notes">
<p>Друге питання кейсу: вивчаємо профіль користувача — зв’язок між активністю (скільки відвідувань на місяць) і давністю реєстрації. Питання незалежності: чи частота візитів активного користувача не залежить від того, скільки він уже зареєстрований? Це ДВІ категоріальні змінні, виміряні на ТИХ САМИХ користувачах — тому дані лягають у таблицю спряженості (contingency table), а не в один частотний ряд.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-contingency-table" class="slide level2 smaller">
<h2>📋 The contingency table</h2>
<p><span class="math inline">\(\eta\)</span> = visits per month; <span class="math inline">\(\psi\)</span> = registration tenure. We count users in each combination.</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>visits \ tenure</th>
<th><span class="math inline">\(&lt;1\)</span>y</th>
<th><span class="math inline">\(1\text{–}2\)</span>y</th>
<th><span class="math inline">\(2\text{–}3\)</span>y</th>
<th><span class="math inline">\(3\text{–}4\)</span>y</th>
<th><span class="math inline">\(4\text{–}5\)</span>y</th>
<th><span class="math inline">\(5\text{+}\)</span>y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\leq 9\)</span></td>
<td>932299</td>
<td>680684</td>
<td>794884</td>
<td>585978</td>
<td>470660</td>
<td>397554</td>
</tr>
<tr class="even">
<td><span class="math inline">\(10\text{–}19\)</span></td>
<td>490658</td>
<td>519094</td>
<td>648085</td>
<td>416680</td>
<td>347016</td>
<td>315555</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(20\text{–}29\)</span></td>
<td>223166</td>
<td>347325</td>
<td>306182</td>
<td>219092</td>
<td>254512</td>
<td>237701</td>
</tr>
<tr class="even">
<td><span class="math inline">\(30\text{+}\)</span></td>
<td>204310</td>
<td>426824</td>
<td>277656</td>
<td>127961</td>
<td>237965</td>
<td>220446</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
H_0: P\big(\text{cell }(i,j)\big) = q_i\, p_j \quad\text{for all } i, j
\qquad\text{(visits } \perp \text{ tenure).}
\]</span></p>
<aside class="notes">
<p>Таблиця спряженості: рядки — рівень активності (≤9, 10–19, 20–29, 30+ візитів), стовпці — давність реєстрації (від &lt;1 до 5+ років), у клітинках — кількість користувачів. H0 незалежності каже: ймовірність потрапити в клітинку (i,j) дорівнює добутку маргінальних ймовірностей q_i·p_j — тобто рядок і стовпець не «знають» один про одного. Якщо так, очікувані частоти легко порахувати з маргінальних сум.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="expected-counts-under-independence" class="slide level2 smaller">
<h2>🧩 Expected counts under independence</h2>
<p>If the variables are independent, the expected probability of a cell is the <strong>product of marginals</strong>:</p>
<p><span class="math display">\[
\hat{p}_j = \frac{\text{column }j\text{ total}}{n}, \qquad
\hat{q}_i = \frac{\text{row }i\text{ total}}{n}, \qquad
E_{ij} = n\,\hat{q}_i\,\hat{p}_j = \frac{(\text{row}_i)(\text{col}_j)}{n}.
\]</span></p>
<div class="fragment">
<p>Estimating <span class="math inline">\(m\)</span> row + <span class="math inline">\(k\)</span> column probabilities (each set sums to 1) costs degrees of freedom:</p>
<p><span class="math display">\[
\text{df} = mk - (m-1) - (k-1) - 1 = (m-1)(k-1).
\]</span></p>
<aside class="notes">
<p>Як знайти очікувані частоти, не знаючи q_i і p_j? Оцінюємо їх з маргінальних сум: частка стовпця і частка рядка. Тоді E_ij = (сума рядка × сума стовпця)/n — знайома формула. За ступені свободи: маємо mk клітинок, але оцінили (m−1) незалежних рядкових і (k−1) стовпцевих ймовірностей плюс загальне обмеження — лишається (m−1)(k−1). Для таблиці 4×6 це 15 ступенів свободи. Це df, з яким беремо χ² хвіст.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="algorithm-1" class="slide level2 smaller">
<h2>🧭 Algorithm</h2>
<ol type="1">
<li>Fix a significance level <span class="math inline">\(\alpha\)</span>.</li>
<li>Record the two variables in an <span class="math inline">\(m \times k\)</span> contingency table.</li>
<li>If any <strong>expected</strong> cell count is <span class="math inline">\(&lt; 5\)</span> (or <span class="math inline">\(&lt; 10\)</span> for a <span class="math inline">\(2\times2\)</span> table), merge categories.</li>
<li>Compute <span class="math display">\[
\tau = \sum_{i,j}\frac{(O_{ij} - E_{ij})^2}{E_{ij}}, \qquad E_{ij}=\frac{(\text{row}_i)(\text{col}_j)}{n}.
\]</span></li>
<li>The <span class="math inline">\(p\)</span>-value is <span class="math inline">\(P(X \geq \tau)\)</span> with <span class="math inline">\(X \sim \chi^2_{(m-1)(k-1)}\)</span>.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(p\text{-value} \leq \alpha\)</span>.</li>
</ol>
<aside class="notes">
<p>Алгоритм майже той самий, що й для узгодженості — змінюється лише спосіб рахувати очікувані частоти (з маргіналів) і ступені свободи ((m−1)(k−1) замість k−1). Те саме правило ≥5 на очікувані клітинки. Та сама статистика Σ(O−E)²/E і та сама права хвостова ймовірність χ². Тобто незалежність — це goodness-of-fit, де «відома» гіпотеза будується з самих даних через незалежність.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="run-the-test" class="slide level2 tiny">
<h2>🎧 Run the test</h2>
<div id="independence-test" class="cell columns column-output-location" data-execution_count="9">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="" aria-hidden="true" tabindex="-1"></a>table <span class="op">=</span> np.array([</span>
<span id="cb11-2"><a href="" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">932299</span>, <span class="dv">680684</span>, <span class="dv">794884</span>, <span class="dv">585978</span>, <span class="dv">470660</span>, <span class="dv">397554</span>],</span>
<span id="cb11-3"><a href="" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">490658</span>, <span class="dv">519094</span>, <span class="dv">648085</span>, <span class="dv">416680</span>, <span class="dv">347016</span>, <span class="dv">315555</span>],</span>
<span id="cb11-4"><a href="" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">223166</span>, <span class="dv">347325</span>, <span class="dv">306182</span>, <span class="dv">219092</span>, <span class="dv">254512</span>, <span class="dv">237701</span>],</span>
<span id="cb11-5"><a href="" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">204310</span>, <span class="dv">426824</span>, <span class="dv">277656</span>, <span class="dv">127961</span>, <span class="dv">237965</span>, <span class="dv">220446</span>],</span>
<span id="cb11-6"><a href="" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb11-7"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="" aria-hidden="true" tabindex="-1"></a>chi2_stat, p, dof, expected <span class="op">=</span> chi2_contingency(table)</span>
<span id="cb11-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"chi2    = </span><span class="sc">{</span>chi2_stat<span class="sc">:,.0f}</span><span class="ss">"</span>)</span>
<span id="cb11-10"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"df      = </span><span class="sc">{</span>dof<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-11"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-value = </span><span class="sc">{</span>p<span class="sc">:.3g}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>chi2    = 270,783
df      = 15
p-value = 0</code></pre>
</div>
</div></div>
<div class="fragment">
<div id="cell-residuals" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="" aria-hidden="true" tabindex="-1"></a>resid <span class="op">=</span> (table <span class="op">-</span> expected) <span class="op">/</span> np.sqrt(expected)   <span class="co"># standardized residuals</span></span>
<span id="cb13-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.6</span>, <span class="fl">3.2</span>))</span>
<span id="cb13-4"><a href="" aria-hidden="true" tabindex="-1"></a>im <span class="op">=</span> ax.imshow(resid, cmap<span class="op">=</span><span class="st">"RdBu_r"</span>, vmin<span class="op">=-</span><span class="dv">40</span>, vmax<span class="op">=</span><span class="dv">40</span>, aspect<span class="op">=</span><span class="st">"auto"</span>)</span>
<span id="cb13-5"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(<span class="bu">range</span>(<span class="dv">6</span>))<span class="op">;</span> ax.set_xticklabels([<span class="st">"&lt;1"</span>, <span class="st">"1-2"</span>, <span class="st">"2-3"</span>, <span class="st">"3-4"</span>, <span class="st">"4-5"</span>, <span class="st">"5+"</span>])</span>
<span id="cb13-6"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_yticks(<span class="bu">range</span>(<span class="dv">4</span>))<span class="op">;</span> ax.set_yticklabels([<span class="st">"&lt;=9"</span>, <span class="st">"10-19"</span>, <span class="st">"20-29"</span>, <span class="st">"30+"</span>])</span>
<span id="cb13-7"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"tenure (years)"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"visits"</span>)</span>
<span id="cb13-8"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Standardized residuals  (O - E)/$</span><span class="ch">\\</span><span class="st">sqrt</span><span class="sc">{E}</span><span class="st">$"</span>)</span>
<span id="cb13-9"><a href="" aria-hidden="true" tabindex="-1"></a>fig.colorbar(im, ax<span class="op">=</span>ax, shrink<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb13-10"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb13-11"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src=".06-chi_files/figure-revealjs/residuals-output-1.svg" id="residuals" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
</div>
<p><span class="math inline">\(H_0\)</span> is rejected at <span class="math inline">\(5\%\)</span>: visit frequency is <strong>not</strong> independent of tenure. The residual map shows <strong>where</strong> — newer users skew low-visit, veterans skew high.</p>
<aside class="notes">
<p>chi2_contingency повертає статистику, p-value, df і матрицю очікуваних частот одним рядком. p мізерний → відхиляємо незалежність: активність ПОВ’ЯЗАНА з давністю реєстрації. Але χ² каже лише «так/ні». Карта стандартизованих залишків (O−E)/√E показує ДЕ саме зв’язок: червоне — більше за очікуване, синє — менше. Видно патерн: нові користувачі тяжіють до низької активності, «ветерани» — до високої. Це той самий хід, що з QQ-plot у минулій лекції: не лише «чи відрізняється», а «як саме».</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="significant-strong-cramérs-v" class="slide level2 smaller">
<h2>📏 Significant ≠ strong: Cramér’s V</h2>
<p>This table holds almost <strong>10 million</strong> users. With <span class="math inline">\(n\)</span> that large, <span class="math inline">\(p \approx 0\)</span> for <em>any</em> departure — significance is <strong>guaranteed</strong>, not informative.</p>
<p>Measure the <strong>strength</strong> of association with <strong>Cramér’s V</strong>:</p>
<p><span class="math display">\[
V = \sqrt{\frac{\chi^2}{n\,(\min(m,k)-1)}} \in [0, 1].
\]</span></p>
<div id="cramers-v" class="cell columns column-output-location" data-execution_count="11">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="" aria-hidden="true" tabindex="-1"></a>chi2_stat, p, dof, _ <span class="op">=</span> chi2_contingency(table)</span>
<span id="cb14-2"><a href="" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> table.<span class="bu">sum</span>()</span>
<span id="cb14-3"><a href="" aria-hidden="true" tabindex="-1"></a>V <span class="op">=</span> np.sqrt(chi2_stat <span class="op">/</span> (n <span class="op">*</span> (<span class="bu">min</span>(table.shape) <span class="op">-</span> <span class="dv">1</span>)))</span>
<span id="cb14-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"chi2     = </span><span class="sc">{</span>chi2_stat<span class="sc">:,.0f}</span><span class="ss">"</span>)</span>
<span id="cb14-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-value  = </span><span class="sc">{</span>p<span class="sc">:.1g}</span><span class="ss">"</span>)</span>
<span id="cb14-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"n        = </span><span class="sc">{</span>n<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb14-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Cramer V = </span><span class="sc">{</span>V<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>chi2     = 270,783
p-value  = 0
n        = 9,682,287
Cramer V = 0.097</code></pre>
</div>
</div></div>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>The <span class="math inline">\(p\)</span>-value screams “reject”, yet <span class="math inline">\(V \approx 0.10\)</span> says the association is <strong>weak</strong>. Rules of thumb: <span class="math inline">\(V \approx 0.1\)</span> small, <span class="math inline">\(0.3\)</span> medium, <span class="math inline">\(0.5\)</span> large. On big data, <strong>always</strong> pair a <span class="math inline">\(\chi^2\)</span> <span class="math inline">\(p\)</span>-value with an effect size.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Найважливіше застереження секції — прямий аналог «large-sample caveat» з минулої лекції (Шапіро відхиляє все на великих n). Тут таблиця містить майже 10 млн користувачів, тож p≈0 при БУДЬ-ЯКОМУ відхиленні — значущість гарантована й нічого не каже про силу зв’язку. Cramér’s V нормує χ² на n і розмір таблиці, даючи число в [0,1]. Тут V≈0.10 — зв’язок СЛАБКИЙ, хоча p=0. Орієнтири: 0.1 слабкий, 0.3 середній, 0.5 сильний. Урок: на великих даних p-value майже завжди «значущий», тож завжди супроводжуйте його розміром ефекту, інакше зробите висновок про «сильний зв’язок» там, де його практично немає.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="test-of-homogeneity" class="title-slide slide level1 center" data-background-iframe=".06-chi_files/libs/colored-particles/index.html">
<h1>Test of homogeneity</h1>

</section>
<section id="the-task-1" class="slide level2 smaller">
<h2>🧪 The task</h2>
<blockquote>
<p>The growth team A/B-tests a new <strong>onboarding flow</strong>.</p>
</blockquote>
<blockquote>
<p><strong>Control</strong> users see the old flow; <strong>test</strong> users see the new one.</p>
</blockquote>
<blockquote>
<p>For each user we record how many <strong>playlists</strong> they create in week 1: <span class="math inline">\(0\)</span>, <span class="math inline">\(1\)</span>, <span class="math inline">\(2\)</span>, <span class="math inline">\(3{+}\)</span>.</p>
</blockquote>
<blockquote>
<p>Does the new onboarding <strong>change the distribution</strong> of playlists created?</p>
</blockquote>
<aside class="notes">
<p>Третє питання кейсу — однорідність. A/B-тест нового онбордингу: контроль бачить старий потік, тест — новий. Для кожного користувача рахуємо, скільки плейлистів він створив за перший тиждень (0,1,2,3+). Питання: чи змінює новий онбординг РОЗПОДІЛ цієї категоріальної величини між групами? Це вже не одна змінна (узгодженість) і не дві змінні на одних людях (незалежність), а порівняння розподілу однієї величини у ДВОХ групах.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="homogeneity-independence" class="slide level2 smaller">
<h2>🔁 Homogeneity ≡ independence</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>group \ playlists</th>
<th><span class="math inline">\(0\)</span></th>
<th><span class="math inline">\(1\)</span></th>
<th><span class="math inline">\(2\)</span></th>
<th><span class="math inline">\(3{+}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Test</strong> (new flow)</td>
<td>3243</td>
<td>432</td>
<td>108</td>
<td>66</td>
</tr>
<tr class="even">
<td><strong>Control</strong> (old)</td>
<td>3045</td>
<td>421</td>
<td>128</td>
<td>83</td>
</tr>
</tbody>
</table>
<p>Read the table differently: treat the <strong>group</strong> itself as a second categorical variable.</p>
<ul>
<li><span class="math inline">\(\psi\)</span> = playlists created (<span class="math inline">\(0, 1, 2, 3{+}\)</span>),</li>
<li><span class="math inline">\(\eta\)</span> = which group the user is in (test / control).</li>
</ul>
<div class="fragment">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The table is <strong>identical</strong> to a contingency table → testing homogeneity is <em>mechanically</em> the same as testing independence. Same statistic, same <span class="math inline">\(\chi^2_{(m-1)(k-1)}\)</span>, same <code>chi2_contingency</code>.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Ключовий інсайт лекції: однорідність і незалежність — це механічно ОДНЕ І ТЕ САМЕ. Якщо подивитися на таблицю по-іншому — вважати саму групу (тест/контроль) другою категоріальною змінною — отримаємо звичайну таблицю спряженості. Тому формула, статистика, ступені свободи та функція ідентичні. Філософська різниця лише в дизайні: при однорідності маргінали груп фіксовані наперед (ми самі набрали тест і контроль), при незалежності — випадкові. На обчислення це не впливає.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="run-the-test-1" class="slide level2 smaller">
<h2>🎧 Run the test</h2>
<div id="homogeneity-test" class="cell columns column-output-location" data-execution_count="12">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="" aria-hidden="true" tabindex="-1"></a>ab <span class="op">=</span> np.array([</span>
<span id="cb16-2"><a href="" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">3243</span>, <span class="dv">432</span>, <span class="dv">108</span>, <span class="dv">66</span>],   <span class="co"># test  (new flow)</span></span>
<span id="cb16-3"><a href="" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">3045</span>, <span class="dv">421</span>, <span class="dv">128</span>, <span class="dv">83</span>],   <span class="co"># control (old flow)</span></span>
<span id="cb16-4"><a href="" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb16-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="" aria-hidden="true" tabindex="-1"></a>chi2_stat, p, dof, _ <span class="op">=</span> chi2_contingency(ab)</span>
<span id="cb16-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"chi2    = </span><span class="sc">{</span>chi2_stat<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb16-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"df      = </span><span class="sc">{</span>dof<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-value = </span><span class="sc">{</span>p<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb16-10"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"reject H0"</span> <span class="cf">if</span> p <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">"keep H0"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>chi2    = 6.083
df      = 3
p-value = 0.1076
keep H0</code></pre>
</div>
</div></div>
<div class="fragment">
<p><span class="math inline">\(p\text{-value} &gt; 5\%\)</span> → we <strong>cannot</strong> claim the new onboarding changed the playlist distribution. The redesign is <em>not</em> moving this metric — ship it only if it helps something else.</p>
<aside class="notes">
<p>Запускаємо той самий chi2_contingency на таблиці 2×4. p&gt;0.05 → НЕ відхиляємо однорідність: немає підстав стверджувати, що новий онбординг змінив розподіл створених плейлистів. Важливий урок про нульовий результат: це не «доказ, що ефекту немає», а «ми не виявили ефекту». Практичний висновок для команди — за цією метрикою редизайн нейтральний; викочувати варто лише якщо він покращує щось інше. Не відхилена H0 ≠ підтверджена H0.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="yates-correction" class="title-slide slide level1 center" data-background-iframe=".06-chi_files/libs/colored-particles/index.html">
<h1>Yates’ correction</h1>

</section>
<section id="when-the-table-is-small" class="slide level2 smaller">
<h2>✂️ When the table is small</h2>
<p>For a <span class="math inline">\(2\times2\)</span> table with <strong>small</strong> counts, the continuous <span class="math inline">\(\chi^2\)</span> over-rejects (inflated Type I error). <strong>Yates’ continuity correction</strong> shrinks each gap by <span class="math inline">\(0.5\)</span>:</p>
<p><span class="math display">\[
\tau_{\text{Yates}} = \sum_{i,j}\frac{\big(|O_{ij} - E_{ij}| - 0.5\big)^2}{E_{ij}}.
\]</span></p>
<div class="fragment">
<p>Use it when expected counts are modest. Rules of thumb for <strong>not</strong> needing it:</p>
<ul>
<li>every cell expected count <span class="math inline">\(&gt; 5\)</span> (general table);</li>
<li><span class="math inline">\(&gt; 10\)</span> per cell for a <span class="math inline">\(2\times1\)</span> frequency table or a <span class="math inline">\(2\times2\)</span> contingency table.</li>
</ul>
<aside class="notes">
<p>Поправка Йейтса — для малих таблиць 2×2. Проблема: χ² неперервний, а частоти дискретні; на малих вибірках це робить критерій надто «нетерплячим» — він відхиляє H0 частіше за номінальні 5% (роздута помилка I роду). Поправка Йейтса віднімає 0.5 від кожного |O−E| перед піднесенням у квадрат, роблячи критерій консервативнішим. Коли НЕ потрібна: очікувані частоти &gt;5 (загалом) або &gt;10 для 2×2. У scipy chi2_contingency застосовує її за замовчуванням для 2×2.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="with-and-without-the-correction" class="slide level2 smaller">
<h2>🔬 With and without the correction</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>A</th>
<th>B</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1</strong></td>
<td>15</td>
<td>18</td>
<td>33</td>
</tr>
<tr class="even">
<td><strong>2</strong></td>
<td>15</td>
<td>13</td>
<td>28</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>30</td>
<td>31</td>
<td>61</td>
</tr>
</tbody>
</table>
<div id="yates-example" class="cell columns column-output-location" data-execution_count="13">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="" aria-hidden="true" tabindex="-1"></a>table <span class="op">=</span> np.array([[<span class="dv">15</span>, <span class="dv">18</span>], [<span class="dv">15</span>, <span class="dv">13</span>]])</span>
<span id="cb18-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="" aria-hidden="true" tabindex="-1"></a>raw  <span class="op">=</span> chi2_contingency(table, correction<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb18-4"><a href="" aria-hidden="true" tabindex="-1"></a>yate <span class="op">=</span> chi2_contingency(table, correction<span class="op">=</span><span class="va">True</span>)   <span class="co"># scipy default for 2x2</span></span>
<span id="cb18-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"no correction:"</span>)</span>
<span id="cb18-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  chi2 = </span><span class="sc">{</span>raw[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">   p = </span><span class="sc">{</span>raw[<span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb18-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Yates' correction:"</span>)</span>
<span id="cb18-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  chi2 = </span><span class="sc">{</span>yate[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">   p = </span><span class="sc">{</span>yate[<span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>no correction:
  chi2 = 0.399   p = 0.527
Yates' correction:
  chi2 = 0.141   p = 0.708</code></pre>
</div>
</div></div>
<div class="fragment">
<p>The correction <strong>lowers</strong> <span class="math inline">\(\chi^2\)</span> and <strong>raises</strong> the <span class="math inline">\(p\)</span>-value — more conservative, as intended.</p>
<aside class="notes">
<p>Той самий 2×2 з обома підходами. correction=False — «сирий» χ²; correction=True — з поправкою Йейтса (це дефолт scipy для 2×2). Поправка зменшує статистику і збільшує p-value — критерій стає обережнішим. На цьому прикладі різниця помітна. Але чи справді поправка тримає 5%? Це твердження не варто брати на віру — перевіримо його Монте-Карло, як ми робили з усіма критеріями.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="a-reusable-monte-carlo-checker" class="slide level2 smaller">
<h2>🧪 A reusable Monte-Carlo checker</h2>
<p>Same engine as for the <span class="math inline">\(t\)</span>- and KS-tests: simulate, count rejections, add a Wilson CI.</p>
<div id="chi2-mc-fn" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> chi2_rejection_rate(n, p1, p2, correction, alpha<span class="op">=</span><span class="fl">0.05</span>,</span>
<span id="cb20-2"><a href="" aria-hidden="true" tabindex="-1"></a>                        n_exps<span class="op">=</span><span class="dv">3000</span>, seed<span class="op">=</span><span class="dv">42</span>):</span>
<span id="cb20-3"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""2x2 chi-square homogeneity test via Monte Carlo.</span></span>
<span id="cb20-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co">    p1 == p2  -&gt; H0 true  -&gt; the rate is the FPR.</span></span>
<span id="cb20-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co">    p1 != p2  -&gt; H1 true  -&gt; the rate is the power (TPR).</span></span>
<span id="cb20-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb20-8"><a href="" aria-hidden="true" tabindex="-1"></a>    rng, rej <span class="op">=</span> np.random.default_rng(seed), <span class="dv">0</span></span>
<span id="cb20-9"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_exps):</span>
<span id="cb20-10"><a href="" aria-hidden="true" tabindex="-1"></a>        a <span class="op">=</span> binom.rvs(n, p1, random_state<span class="op">=</span>rng)<span class="op">;</span> b <span class="op">=</span> n <span class="op">-</span> a   <span class="co"># group 1</span></span>
<span id="cb20-11"><a href="" aria-hidden="true" tabindex="-1"></a>        c <span class="op">=</span> binom.rvs(n, p2, random_state<span class="op">=</span>rng)<span class="op">;</span> d <span class="op">=</span> n <span class="op">-</span> c   <span class="co"># group 2</span></span>
<span id="cb20-12"><a href="" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> (a <span class="op">+</span> c) <span class="kw">and</span> (b <span class="op">+</span> d):                             <span class="co"># avoid empty column</span></span>
<span id="cb20-13"><a href="" aria-hidden="true" tabindex="-1"></a>            p <span class="op">=</span> chi2_contingency([[a, b], [c, d]],</span>
<span id="cb20-14"><a href="" aria-hidden="true" tabindex="-1"></a>                                 correction<span class="op">=</span>correction)[<span class="dv">1</span>]</span>
<span id="cb20-15"><a href="" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb20-16"><a href="" aria-hidden="true" tabindex="-1"></a>            p <span class="op">=</span> <span class="fl">1.0</span></span>
<span id="cb20-17"><a href="" aria-hidden="true" tabindex="-1"></a>        rej <span class="op">+=</span> p <span class="op">&lt;=</span> alpha</span>
<span id="cb20-18"><a href="" aria-hidden="true" tabindex="-1"></a>    ci <span class="op">=</span> proportion_confint(rej, n_exps, alpha<span class="op">=</span><span class="fl">0.05</span>, method<span class="op">=</span><span class="st">"wilson"</span>)</span>
<span id="cb20-19"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> rej <span class="op">/</span> n_exps, ci</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Pass <strong>equal</strong> probabilities (<span class="math inline">\(p_1 = p_2\)</span>) to measure the FPR, <strong>different</strong> ones to measure power.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Перевикористовуємо ту саму ідею валідації, що для t- і KS-критеріїв. Функція chi2_rejection_rate: тисячі разів генерує дві біноміальні вибірки розміру n, складає таблицю 2×2, рахує частку відхилень + довірчий інтервал Уілсона. Однакові ймовірності p1=p2 → H0 вірна → міряємо FPR (хибнопозитивні). Різні → потужність. Прапорець correction перемикає поправку Йейтса. Той самий двигун, лише всередині chi2_contingency.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="yates-correction-controls-the-fpr" class="slide level2 smaller">
<h2>📉 Yates’ correction controls the FPR</h2>
<div id="cell-yates-fpr" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="" aria-hidden="true" tabindex="-1"></a>sizes <span class="op">=</span> np.arange(<span class="dv">4</span>, <span class="dv">40</span>, <span class="dv">3</span>)</span>
<span id="cb21-2"><a href="" aria-hidden="true" tabindex="-1"></a>with_y  <span class="op">=</span> [chi2_rejection_rate(n, <span class="fl">0.3</span>, <span class="fl">0.3</span>, correction<span class="op">=</span><span class="va">True</span>)  <span class="cf">for</span> n <span class="kw">in</span> sizes]</span>
<span id="cb21-3"><a href="" aria-hidden="true" tabindex="-1"></a>no_y    <span class="op">=</span> [chi2_rejection_rate(n, <span class="fl">0.3</span>, <span class="fl">0.3</span>, correction<span class="op">=</span><span class="va">False</span>) <span class="cf">for</span> n <span class="kw">in</span> sizes]</span>
<span id="cb21-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.4</span>))</span>
<span id="cb21-6"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(sizes, [r <span class="cf">for</span> r, _ <span class="kw">in</span> with_y], color<span class="op">=</span>red_pink, lw<span class="op">=</span><span class="fl">2.5</span>, marker<span class="op">=</span><span class="st">"o"</span>,</span>
<span id="cb21-7"><a href="" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"with Yates"</span>)</span>
<span id="cb21-8"><a href="" aria-hidden="true" tabindex="-1"></a>ax.fill_between(sizes, [ci[<span class="dv">0</span>] <span class="cf">for</span> _, ci <span class="kw">in</span> with_y], [ci[<span class="dv">1</span>] <span class="cf">for</span> _, ci <span class="kw">in</span> with_y],</span>
<span id="cb21-9"><a href="" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span>red_pink, alpha<span class="op">=</span><span class="fl">0.15</span>)</span>
<span id="cb21-10"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(sizes, [r <span class="cf">for</span> r, _ <span class="kw">in</span> no_y], color<span class="op">=</span>blue, lw<span class="op">=</span><span class="fl">2.5</span>, ls<span class="op">=</span><span class="st">"--"</span>, marker<span class="op">=</span><span class="st">"s"</span>,</span>
<span id="cb21-11"><a href="" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"no correction"</span>)</span>
<span id="cb21-12"><a href="" aria-hidden="true" tabindex="-1"></a>ax.fill_between(sizes, [ci[<span class="dv">0</span>] <span class="cf">for</span> _, ci <span class="kw">in</span> no_y], [ci[<span class="dv">1</span>] <span class="cf">for</span> _, ci <span class="kw">in</span> no_y],</span>
<span id="cb21-13"><a href="" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span>blue, alpha<span class="op">=</span><span class="fl">0.12</span>)</span>
<span id="cb21-14"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="fl">0.05</span>, color<span class="op">=</span>orange, ls<span class="op">=</span><span class="st">":"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="vs">r"</span><span class="dv">$</span><span class="ch">\a</span><span class="vs">lpha = 0</span><span class="dv">.</span><span class="vs">05</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb21-15"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"group size n"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"FPR"</span>)</span>
<span id="cb21-16"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"FPR vs sample size (H0 true)"</span>)<span class="op">;</span> ax.legend()</span>
<span id="cb21-17"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb21-18"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".06-chi_files/figure-revealjs/yates-fpr-output-1.svg" id="yates-fpr" class="quarto-figure quarto-figure-center r-stretch"><p>Without correction the FPR sits <strong>above</strong> <span class="math inline">\(\alpha\)</span> on small samples; Yates pulls it back down (often below <span class="math inline">\(\alpha\)</span> — slightly conservative).</p>
<aside class="notes">
<p>A/A-експеримент: p1=p2=0.3, H0 вірна, тож будь-яке відхилення — хибне. Без поправки (синій пунктир) FPR на малих n помітно ВИЩИЙ за 5% — критерій бреше частіше, ніж обіцяв. З поправкою Йейтса (рожевий) FPR притиснутий до α, часто навіть нижче — критерій стає консервативним. Це підтверджує теорію емпірично: на малих 2×2 поправка потрібна, щоб тримати помилку I роду під контролем. Ось чому scipy вмикає її за замовчуванням.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-price-a-little-power" class="slide level2 smaller">
<h2>⚖️ The price: a little power</h2>
<p>Now the groups truly differ (<span class="math inline">\(p_1 = 0.30\)</span> vs <span class="math inline">\(p_2 = 0.35\)</span>). How often does each version detect it?</p>
<div id="cell-yates-power" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="" aria-hidden="true" tabindex="-1"></a>sizes <span class="op">=</span> np.arange(<span class="dv">50</span>, <span class="dv">2001</span>, <span class="dv">250</span>)</span>
<span id="cb22-2"><a href="" aria-hidden="true" tabindex="-1"></a>with_y <span class="op">=</span> [chi2_rejection_rate(n, <span class="fl">0.30</span>, <span class="fl">0.35</span>, correction<span class="op">=</span><span class="va">True</span>)  <span class="cf">for</span> n <span class="kw">in</span> sizes]</span>
<span id="cb22-3"><a href="" aria-hidden="true" tabindex="-1"></a>no_y   <span class="op">=</span> [chi2_rejection_rate(n, <span class="fl">0.30</span>, <span class="fl">0.35</span>, correction<span class="op">=</span><span class="va">False</span>) <span class="cf">for</span> n <span class="kw">in</span> sizes]</span>
<span id="cb22-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.4</span>))</span>
<span id="cb22-6"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(sizes, [r <span class="cf">for</span> r, _ <span class="kw">in</span> with_y], color<span class="op">=</span>purple, lw<span class="op">=</span><span class="fl">2.5</span>, marker<span class="op">=</span><span class="st">"o"</span>,</span>
<span id="cb22-7"><a href="" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"with Yates"</span>)</span>
<span id="cb22-8"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(sizes, [r <span class="cf">for</span> r, _ <span class="kw">in</span> no_y], color<span class="op">=</span>blue, lw<span class="op">=</span><span class="fl">2.5</span>, ls<span class="op">=</span><span class="st">"--"</span>, marker<span class="op">=</span><span class="st">"s"</span>,</span>
<span id="cb22-9"><a href="" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"no correction"</span>)</span>
<span id="cb22-10"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="fl">0.8</span>, color<span class="op">=</span>slate, ls<span class="op">=</span><span class="st">":"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"80</span><span class="sc">% g</span><span class="st">old standard"</span>)</span>
<span id="cb22-11"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb22-12"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"group size n"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"power (TPR)"</span>)</span>
<span id="cb22-13"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Power vs sample size (H1 true)"</span>)<span class="op">;</span> ax.legend()</span>
<span id="cb22-14"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb22-15"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".06-chi_files/figure-revealjs/yates-power-output-1.svg" id="yates-power" class="quarto-figure quarto-figure-center r-stretch"><div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Yates’ correction trades a sliver of <strong>power</strong> for an honest <strong>FPR</strong>. On large samples the two curves meet — the correction stops mattering once counts are big.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Тепер групи реально різні (0.30 vs 0.35). Потужність обох версій росте з n і перетинає золотий стандарт 80%. Версія з поправкою (фіолетова) трохи нижча — це плата: за чесний FPR ми віддаємо дрібку потужності. На великих вибірках криві сходяться — поправка перестає мати значення, бо χ² і так добре наближений. Мета-висновок: поправка Йейтса критична на малих 2×2 і практично нешкідлива на великих, тож дефолт scipy розумний.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="exact-alternative-fishers-exact-test" class="slide level2 smaller">
<h2>🎯 Exact alternative: Fisher’s exact test</h2>
<p>When counts are tiny, skip the approximation entirely. <strong>Fisher’s exact test</strong> computes the <span class="math inline">\(p\)</span>-value directly from the <strong>hypergeometric</strong> distribution — no <span class="math inline">\(\chi^2\)</span> limit, valid for <em>any</em> cell size.</p>
<div id="fisher" class="cell columns column-output-location" data-execution_count="17">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="" aria-hidden="true" tabindex="-1"></a>table_2x2 <span class="op">=</span> np.array([[<span class="dv">15</span>, <span class="dv">18</span>], [<span class="dv">15</span>, <span class="dv">13</span>]])</span>
<span id="cb23-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="" aria-hidden="true" tabindex="-1"></a>odds, p_fisher <span class="op">=</span> fisher_exact(table_2x2)</span>
<span id="cb23-4"><a href="" aria-hidden="true" tabindex="-1"></a>p_yates <span class="op">=</span> chi2_contingency(table_2x2)[<span class="dv">1</span>]</span>
<span id="cb23-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Fisher odds ratio = </span><span class="sc">{</span>odds<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb23-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Fisher p-value    = </span><span class="sc">{</span>p_fisher<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb23-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Yates  p-value    = </span><span class="sc">{</span>p_yates<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>Fisher odds ratio = 0.722
Fisher p-value    = 0.6111
Yates  p-value    = 0.7077</code></pre>
</div>
</div></div>
<div class="fragment">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Fisher is <strong>exact</strong> for any table; <span class="math inline">\(\chi^2\)</span>-with-Yates is its large-sample <em>approximation</em>. Here they agree (both <span class="math inline">\(\approx 0.6\)</span>–<span class="math inline">\(0.7\)</span> → no association). Use Fisher as the safe default for small <span class="math inline">\(2\times2\)</span> tables; <span class="math inline">\(\chi^2\)</span> scales better to large or bigger-than-<span class="math inline">\(2\times2\)</span> tables.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Альтернатива поправці Йейтса на малих таблицях — точний критерій Фішера. Він рахує p-value напряму з гіпергеометричного розподілу (перебирає всі таблиці з тими ж маргіналами), без жодного асимптотичного наближення — тому коректний за будь-яких частот. На нашому 2×2: Fisher p≈0.61, Yates p≈0.71 — обидва великі, зв’язку немає, висновки збігаються. Правило вибору: Фішер — безпечний дефолт для малих 2×2; χ² краще масштабується на великі таблиці й таблиці більші за 2×2 (Фішер там обчислювально дорогий). Тобто Йейтс — це швидке наближення до Фішера.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="summary" class="title-slide slide level1 center" data-background-iframe=".06-chi_files/libs/colored-particles/index.html">
<h1>Summary</h1>

</section>
<section id="the-one-idea" class="slide level2 smaller">
<h2>🧾 The one idea</h2>
<p>Everything today reduced to one statistic: <span class="hi">compare observed and expected counts</span>.</p>
<p><span class="math display">\[
\tau = \sum_{\text{cells}} \frac{(O - E)^2}{E} \sim \chi^2_{\text{df}}.
\]</span></p>
<ul>
<li><strong>Goodness-of-fit</strong> — one variable vs a known distribution; <span class="math inline">\(\text{df} = k-1\)</span>.</li>
<li><strong>Independence</strong> — two variables on the same units; <span class="math inline">\(E_{ij} = \tfrac{\text{row}\cdot\text{col}}{n}\)</span>, <span class="math inline">\(\text{df} = (m-1)(k-1)\)</span>.</li>
<li><strong>Homogeneity</strong> — same distribution across groups; <em>mechanically identical</em> to independence.</li>
<li><strong>Yates’ correction / Fisher</strong> — small <span class="math inline">\(2\times2\)</span> tables; trade power for an honest FPR, or go exact.</li>
<li><strong>Cramér’s V</strong> — on big <span class="math inline">\(n\)</span> everything is “significant”; report the <strong>effect size</strong> too.</li>
</ul>
<aside class="notes">
<p>Підсумок: уся лекція — одна статистика Σ(O−E)²/E, що при H0 розподілена за χ². Три задачі відрізняються лише тим, як рахувати E і df: узгодженість (одна змінна, df=k−1); незалежність (дві змінні, E з маргіналів, df=(m−1)(k−1)); однорідність (групи) — механічно те саме, що незалежність. На малих 2×2 — поправка Йейтса або точний Фішер. І ключове застереження для великих даних: p майже завжди значущий, тож завжди додавайте розмір ефекту (Cramér’s V). Усе зведено до підрахунку відхилень спостереженого від очікуваного.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="which-chi2-test-when" class="slide level2 smaller">
<h2>🧭 Which <span class="math inline">\(\chi^2\)</span> test, when?</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Question</th>
<th>Tool</th>
<th>df</th>
<th>Watch out for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One variable vs a <strong>known</strong> distribution?</td>
<td><code>chisquare</code></td>
<td><span class="math inline">\(k-1\)</span></td>
<td>distribution fixed up front</td>
</tr>
<tr class="even">
<td>Are <strong>two</strong> categorical variables related?</td>
<td><code>chi2_contingency</code></td>
<td><span class="math inline">\((m-1)(k-1)\)</span></td>
<td>expected count <span class="math inline">\(\geq 5\)</span></td>
</tr>
<tr class="odd">
<td>Do <strong>groups</strong> share a distribution?</td>
<td><code>chi2_contingency</code></td>
<td><span class="math inline">\((m-1)(k-1)\)</span></td>
<td>same math as independence</td>
</tr>
<tr class="even">
<td>Small <span class="math inline">\(2\times2\)</span> table?</td>
<td><code>chi2_contingency</code> (Yates on) / <code>fisher_exact</code></td>
<td><span class="math inline">\(1\)</span></td>
<td><span class="math inline">\(\chi^2\)</span> over-rejects</td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The meta-lesson still holds: when in doubt, <span class="hi">validate the criterion with Monte Carlo</span> on data that looks like yours.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Шпаргалка «який χ² коли»: відома гіпотеза про один ряд частот — chisquare, df=k−1; дві категоріальні змінні — chi2_contingency, df=(m−1)(k−1), стежте за очікуваними ≥5; групи — той самий chi2_contingency; малі 2×2 — поправка Йейтса або точний критерій Фішера, бо χ² переоцінює. І наскрізний мета-урок усього курсу: маєш сумнів щодо каліброваності критерію — переваліруй його Монте-Карло на даних, схожих на твої. Саме так ми перевірили й поправку Йейтса.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section id="questions" class="title-slide slide level1 unnumbered unlisted center" data-background-iframe=".06-chi_files/libs/colored-particles/index.html">
<h1>Questions?</h1>
<p><iconify-icon inline="" icon="solar:book-bold"></iconify-icon> <a href="https://teaching.kse.org.ua/course/view.php?id=4049">Course materials</a></p>
<p><iconify-icon inline="" icon="mdi:envelope"></iconify-icon> imiroshnychenko@kse.org.ua</p>
<p><iconify-icon inline="" icon="ic:baseline-telegram"></iconify-icon> <a href="https://t.me/araprof"><span class="citation" data-cites="araprof">@araprof</span></a></p>
<p><iconify-icon inline="" icon="mdi:youtube"></iconify-icon> <a href="https://www.youtube.com/@datamirosh"><span class="citation" data-cites="datamirosh">@datamirosh</span></a></p>
<p><iconify-icon inline="" icon="mdi:linkedin"></iconify-icon> <a href="https://www.linkedin.com/in/ihormiroshnychenko/">@ihormiroshnychenko</a></p>
<p><iconify-icon inline="" icon="mdi:github"></iconify-icon> <a href="https://github.com/Aranaur">@aranaur</a></p>
<p><iconify-icon inline="" icon="ion:home"></iconify-icon> <a href="https://aranaur.rbind.io">aranaur.rbind.io</a></p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="img/kse.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://teaching.kse.org.ua/course/view.php?id=4049">🔗Applied Statistics</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src=".06-chi_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src=".06-chi_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src=".06-chi_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src=".06-chi_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src=".06-chi_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src=".06-chi_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src=".06-chi_files/libs/revealjs/plugin/verticator/verticator.js"></script>
  <script src=".06-chi_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src=".06-chi_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src=".06-chi_files/libs/revealjs/plugin/search/search.js"></script>
  <script src=".06-chi_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src=".06-chi_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'verticator': {"themetag":"h1","color":"","inversecolor":"","skipuncounted":false,"clickable":true,"position":"auto","offset":"3vmin","autogenerate":true,"tooltip":false,"scale":1},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'h.v',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'default',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: true,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: true,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1350,

        height: 759.375,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, Verticator, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>