<!DOCTYPE html>
<html lang="en"><head>
<script src=".07-mu_files/libs/clipboard/clipboard.min.js"></script>
<script src=".07-mu_files/libs/quarto-html/tabby.min.js"></script>
<script src=".07-mu_files/libs/quarto-html/popper.min.js"></script>
<script src=".07-mu_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href=".07-mu_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href=".07-mu_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href=".07-mu_files/libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src=".07-mu_files/libs/quarto-contrib/iconify-1.0.7/iconify-icon.min.js"></script><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Ihor Miroshnychenko">
  <title>Nonparametric tests for A/B</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href=".07-mu_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href=".07-mu_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href=".07-mu_files/libs/revealjs/dist/theme/quarto-8a52321a21477e1bb40c2cb18c896737.css">
  <link href=".07-mu_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href=".07-mu_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href=".07-mu_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href=".07-mu_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href=".07-mu_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href=".07-mu_files/libs/revealjs/plugin/verticator/verticator.css" rel="stylesheet">
  <link href=".07-mu_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-iframe=".07-mu_files/libs/colored-particles/index.html" class="quarto-title-block center">
  <h1 class="title">Nonparametric tests for A/B</h1>
  <p class="subtitle">Applied Statistics</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Ihor Miroshnychenko 
</div>
        <p class="quarto-title-affiliation">
            Kyiv School of Economics
          </p>
    </div>
</div>

</section><section id="TOC">
<nav role="doc-toc"> 
<h2 id="toc-title">Table of contents</h2>
<ul>
<li><a href="#/why-nonparametric" id="/toc-why-nonparametric">Why nonparametric?</a></li>
<li><a href="#/the-sign-test" id="/toc-the-sign-test">The sign test</a></li>
<li><a href="#/wilcoxon-signed-rank" id="/toc-wilcoxon-signed-rank">Wilcoxon signed-rank</a></li>
<li><a href="#/mannwhitney-u-test" id="/toc-mannwhitney-u-test">Mann–Whitney U-test</a></li>
<li><a href="#/ranks-the-shortcut" id="/toc-ranks-the-shortcut">Ranks: the shortcut</a></li>
<li><a href="#/running-the-test" id="/toc-running-the-test">Running the test</a></li>
<li><a href="#/does-it-hold-its-promises" id="/toc-does-it-hold-its-promises">Does it hold its promises?</a></li>
<li><a href="#/effect-size-caveats" id="/toc-effect-size-caveats">Effect size &amp; caveats</a></li>
<li><a href="#/summary" id="/toc-summary">Summary</a></li>
</ul>
</nav>
</section>
<section>
<section id="why-nonparametric" class="title-slide slide level1 center" data-background-iframe=".07-mu_files/libs/colored-particles/index.html">
<h1>Why nonparametric?</h1>

</section>
<section id="the-plan-three-tests-simplest-first" class="slide level2 smaller">
<h2>🎧 The plan: three tests, simplest first</h2>
<p>The streaming-app growth team keeps shipping A/B experiments on <strong>daily listening minutes</strong> — a metric with a long right tail and the odd binge outlier. The <span class="math inline">\(t\)</span>-test leans on normality, so instead we build tests that read only the <strong>direction</strong> or the <strong>order</strong> of the data.</p>
<div class="fragment">
<p>We go from simplest to most general:</p>
<ol type="1">
<li><strong>Sign test</strong> — keep only the <em>direction</em> of each change (binomial).</li>
<li><strong>Wilcoxon signed-rank</strong> — rank the <em>sizes</em> of paired changes.</li>
<li><strong>Mann–Whitney U</strong> — compare <em>two independent groups</em> by ranks.</li>
</ol>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Engagement metrics (minutes, revenue, orders) are almost never normal: a long right tail of super-users, a floor at zero, and the odd outlier who streamed all night.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Повертаємось до наскрізного кейсу — growth-команда стримінгу A/B-тестує продуктові метрики (хвилини прослуховування на день) із довгим правим хвостом і поодинокими «binge»-викидами. t-тест спирається на нормальність, тож натомість будуємо критерії, що читають лише НАПРЯМОК або ПОРЯДОК даних. Ідемо від найпростішого до найзагальнішого: (1) знаковий критерій — лише напрямок кожної зміни (біном); (2) знаково-ранговий Вілкоксон — ранжуємо РОЗМІРИ парних змін; (3) Манн–Уітні — порівнюємо дві НЕЗАЛЕЖНІ групи за рангами. Спершу — чому середнє тут поганий орієнтир.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="why-the-t-test-gets-nervous" class="slide level2 smaller">
<h2>📉 Why the <span class="math inline">\(t\)</span>-test gets nervous</h2>
<div id="cell-skew-picture" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">3.8</span>))</span>
<span id="cb1-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].hist(control, bins<span class="op">=</span><span class="dv">18</span>, color<span class="op">=</span>turquoise, alpha<span class="op">=</span><span class="fl">0.9</span>)</span>
<span id="cb1-4"><a href="" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].axvline(np.mean(control),   color<span class="op">=</span>red_pink, lw<span class="op">=</span><span class="fl">2.5</span>, label<span class="op">=</span><span class="st">"mean"</span>)</span>
<span id="cb1-5"><a href="" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].axvline(np.median(control), color<span class="op">=</span>slate,  ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="fl">2.5</span>, label<span class="op">=</span><span class="st">"median"</span>)</span>
<span id="cb1-6"><a href="" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">"Daily listening minutes (control)"</span>)</span>
<span id="cb1-7"><a href="" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_xlabel(<span class="st">"minutes"</span>)<span class="op">;</span> ax[<span class="dv">0</span>].set_ylabel(<span class="st">"users"</span>)<span class="op">;</span> ax[<span class="dv">0</span>].legend(fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb1-8"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># one whale joins the sample -&gt; watch the mean move, the median barely flinch</span></span>
<span id="cb1-10"><a href="" aria-hidden="true" tabindex="-1"></a>spiked <span class="op">=</span> np.append(control, <span class="dv">600</span>)</span>
<span id="cb1-11"><a href="" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].axhline(np.mean(control),    color<span class="op">=</span>slate,    ls<span class="op">=</span><span class="st">":"</span>,  lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"mean, before"</span>)</span>
<span id="cb1-12"><a href="" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].axhline(np.mean(spiked),     color<span class="op">=</span>red_pink, lw<span class="op">=</span><span class="fl">2.5</span>,        label<span class="op">=</span><span class="st">"mean, after outlier"</span>)</span>
<span id="cb1-13"><a href="" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].axhline(np.median(spiked),   color<span class="op">=</span>blue,     ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="fl">2.5</span>, label<span class="op">=</span><span class="st">"median, after"</span>)</span>
<span id="cb1-14"><a href="" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">"One outlier drags the mean"</span>)<span class="op">;</span> ax[<span class="dv">1</span>].set_xlabel(<span class="st">""</span>)<span class="op">;</span> ax[<span class="dv">1</span>].set_ylabel(<span class="st">"minutes"</span>)</span>
<span id="cb1-15"><a href="" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_xticks([])<span class="op">;</span> ax[<span class="dv">1</span>].legend(fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb1-16"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb1-17"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".07-mu_files/figure-revealjs/skew-picture-output-1.svg" id="skew-picture" class="quarto-figure quarto-figure-center r-stretch"><p>The <span class="math inline">\(t\)</span>-test compares <strong>means</strong>, and the mean is hostage to the tail. The <strong>median</strong> — and order in general — barely moves. We want a test that listens to <strong>order</strong>, not magnitude.</p>
<aside class="notes">
<p>Лівий графік — реальна форма метрики: сильно скошена вправо, довгий хвіст. Правий — що робить ОДИН викид (користувач на 600 хв): середнє стрибає, медіана майже не ворушиться. t-тест порівнює саме середні, а середнє — заручник хвоста й викидів. На малих/скошених вибірках це й роздуває дисперсію, і робить нормальне наближення сумнівним. Звідси ідея: будувати критерій на ПОРЯДКУ (рангах), а не на величинах. Порядок стійкий до викидів і не вимагає нормальності.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-sign-test" class="title-slide slide level1 center" data-background-iframe=".07-mu_files/libs/colored-particles/index.html">
<h1>The sign test</h1>

</section>
<section id="when-the-ab-is-paired" class="slide level2 smaller">
<h2>🔁 When the A/B is paired</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p>The cleanest A/B splits users into <strong>two independent groups</strong>. But many experiments instead measure the <strong>same user twice</strong>:</p>
<ul>
<li><strong>crossover</strong> — each user gets the old recsys one week, the new one the next;</li>
<li><strong>before / after</strong> a rollout;</li>
<li><strong>matched pairs</strong>.</li>
</ul>
<p>Now the two columns are <strong>not independent</strong>, so an independent-samples test (<code>ttest_ind</code>, or the Mann–Whitney we build at the end) does <strong>not</strong> apply. Collapse each pair to its <strong>difference</strong> <span class="math inline">\(d_i = \text{new}_i - \text{old}_i\)</span> and test <em>that</em>.</p>
</div><div class="column" style="width:54%;">
<div id="23702e0e" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src=".07-mu_files/figure-revealjs/cell-4-output-1.svg" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
</div>
</div></div>
<p>A single sample also fits here: test one group’s median against a fixed <strong>target / KPI</strong>.</p>
<aside class="notes">
<p>Найчистіший A/B ділить користувачів на ДВІ НЕЗАЛЕЖНІ групи. Але часто експеримент натомість міряє того самого користувача двічі: крос-овер (тиждень стара система, тиждень нова), до/після розкочування, метчовані пари. Тоді два стовпці ВЖЕ не незалежні — тести для незалежних груп (ttest_ind чи Манн–Уітні, який будуємо в кінці) не підходять. Розв’язок: згорнути кожну пару в РІЗНИЦЮ d_i = new_i − old_i і тестувати вже її. На графіку кожна точка — один користувач, видимий двічі; вище діагоналі — покращився, нижче — впав. Сюди ж лягає й одновибірковий випадок: перевірити медіану однієї вибірки проти фіксованого цільового KPI. Далі — два критерії саме для цього: знаковий і знаково-ранговий Вілкоксона.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-sign-test-direction-only" class="slide level2 smaller">
<h2>✍️ The sign test: direction only</h2>
<p>The simplest idea: throw away the magnitude, keep only the <strong>sign</strong> of each difference. The count of “+” is then pure coin-flipping under <span class="math inline">\(H_0\)</span>:</p>
<p><span class="math display">\[
T = \#\{\,d_i &gt; 0\,\} \overset{H_0}{\sim} \text{Binom}\!\left(n, \tfrac12\right).
\]</span></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Paired</strong> <span class="math inline">\(H_0:\ P(\text{new} &gt; \text{old}) = \tfrac12\)</span> — the new recsys helps as often as it hurts (“no effect”).</p>
</div><div class="column" style="width:50%;">
<p><strong>One-sample</strong> <span class="math inline">\(H_0:\ \text{median} = m_0\)</span>, scoring <span class="math inline">\(d_i = x_i - m_0\)</span>.</p>
</div></div>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><strong>Zero distributional assumptions</strong> — just independence and a continuous-ish metric. The price: ignoring <em>how big</em> each change was, so it is the <strong>least powerful</strong> of the three. Run it with <code>scipy.stats.binomtest</code>.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Найпростіша ідея — викинути величину, лишити тільки ЗНАК кожної різниці. Кількість плюсів при H0 — це чисте підкидання монетки: T = #{d_i&gt;0} ~ Binom(n, 1/2). Парний варіант: H0 — P(new&gt;old)=1/2, тобто нова система допомагає так само часто, як і шкодить (ефекту немає). Одновибірковий: H0 — медіана = m0, рахуємо d_i = x_i − m0. Головна перевага — НУЛЬ припущень про розподіл (лише незалежність і неперервна метрика). Ціна — ігноруємо, наскільки великою була кожна зміна, тому це НАЙМЕНШ потужний із трьох критеріїв. У scipy — binomtest. Це місток від біноміального тесту (перша лекція) до парних дизайнів.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="sign-test-on-the-crossover-ab" class="slide level2 smaller">
<h2>🎧 Sign test on the crossover A/B</h2>
<div id="sign-test" class="cell columns column-output-location" data-execution_count="4">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="" aria-hidden="true" tabindex="-1"></a>k   <span class="op">=</span> <span class="bu">int</span>((d_u <span class="op">&gt;</span> <span class="dv">0</span>).<span class="bu">sum</span>())          <span class="co"># users who improved</span></span>
<span id="cb2-2"><a href="" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> binomtest(k, n_pair, <span class="fl">0.5</span>, alternative<span class="op">=</span><span class="st">"greater"</span>)</span>
<span id="cb2-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"improved   : </span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span>n_pair<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"sign-test p : </span><span class="sc">{</span>res<span class="sc">.</span>pvalue<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb2-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"reject H0"</span> <span class="cf">if</span> res.pvalue <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">"keep H0"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>improved   : 23/30
sign-test p : 0.0026
reject H0</code></pre>
</div>
</div></div>
<div id="cell-sign-test-plot" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="" aria-hidden="true" tabindex="-1"></a>xs   <span class="op">=</span> np.arange(<span class="dv">0</span>, n_pair <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb4-2"><a href="" aria-hidden="true" tabindex="-1"></a>crit <span class="op">=</span> binom.ppf(<span class="fl">0.95</span>, n_pair, <span class="fl">0.5</span>)          <span class="co"># one-sided cutoff</span></span>
<span id="cb4-3"><a href="" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> [red_pink <span class="cf">if</span> x <span class="op">&gt;=</span> crit <span class="cf">else</span> turquoise <span class="cf">for</span> x <span class="kw">in</span> xs]</span>
<span id="cb4-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.6</span>, <span class="fl">3.2</span>))</span>
<span id="cb4-6"><a href="" aria-hidden="true" tabindex="-1"></a>ax.bar(xs, binom.pmf(xs, n_pair, <span class="fl">0.5</span>), color<span class="op">=</span>cols)</span>
<span id="cb4-7"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axvline(k, color<span class="op">=</span>slate, lw<span class="op">=</span><span class="fl">2.5</span>, label<span class="op">=</span><span class="ss">f"observed = </span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb4-8"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"$H_0$: Binom(30, ½) — pink = rejection region"</span>)</span>
<span id="cb4-9"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"# improved users"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"prob"</span>)<span class="op">;</span> ax.legend(fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb4-10"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb4-11"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".07-mu_files/figure-revealjs/sign-test-plot-output-1.svg" id="sign-test-plot" class="quarto-figure quarto-figure-center r-stretch"><p><span class="math inline">\(23/30\)</span> users improved — well inside the right tail of the coin-flip null, so the new recsys <strong>helps more often than not</strong>.</p>
<aside class="notes">
<p>Застосовуємо до крос-овер A/B. Рахуємо, скільки користувачів покращилося: k = #{d&gt;0} = 23 з 30. binomtest(23, 30, 0.5, alternative=‘greater’) дає p≈0.003 — відхиляємо H0. Графік: нульовий розподіл — Binom(30, ½), рожевим позначено критичну область (права засічка на рівні 0.95). Спостережені 23 лежать глибоко в правому хвості, тож висновок: нова система допомагає частіше, ніж шкодить. Зверніть увагу — ми НЕ використали, наскільки саме зросли хвилини, лише напрямок зміни. Це й робить критерій таким невибагливим до припущень.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="one-sample-median-vs-a-target-kpi" class="slide level2 smaller">
<h2>🎯 One-sample: median vs a target KPI</h2>
<p>Same machinery, one sample against a fixed target. <em>Is the median session length on the <span class="math inline">\(30\)</span>-minute KPI?</em></p>
<div id="sign-onesample" class="cell columns column-output-location" data-execution_count="6">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="" aria-hidden="true" tabindex="-1"></a>above <span class="op">=</span> <span class="bu">int</span>((sess_min <span class="op">&gt;</span> target_min).<span class="bu">sum</span>())</span>
<span id="cb5-2"><a href="" aria-hidden="true" tabindex="-1"></a>res   <span class="op">=</span> binomtest(above, <span class="bu">len</span>(sess_min), <span class="fl">0.5</span>, alternative<span class="op">=</span><span class="st">"two-sided"</span>)</span>
<span id="cb5-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"above </span><span class="sc">{</span>target_min<span class="sc">}</span><span class="ss"> min : </span><span class="sc">{</span>above<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span><span class="bu">len</span>(sess_min)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"sample median  : </span><span class="sc">{</span>np<span class="sc">.</span>median(sess_min)<span class="sc">:.1f}</span><span class="ss"> min"</span>)</span>
<span id="cb5-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"sign-test p    : </span><span class="sc">{</span>res<span class="sc">.</span>pvalue<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb5-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"reject H0"</span> <span class="cf">if</span> res.pvalue <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">"keep H0"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>above 30 min : 19/40
sample median  : 29.1 min
sign-test p    : 0.8746
keep H0</code></pre>
</div>
</div></div>
<div class="fragment">
<p>The split is close to <span class="math inline">\(50/50\)</span> and <span class="math inline">\(p\)</span> is large → the median is <strong>statistically consistent with the <span class="math inline">\(30\)</span>-minute target</strong>. A “non-rejection” we are happy to report: we are hitting the KPI, not missing it.</p>
<aside class="notes">
<p>Та сама механіка, але одна вибірка проти фіксованого цільового KPI: чи медіана тривалості сесії дорівнює цільовим 30 хвилинам? Рахуємо, скільки спостережень вище за 30 (тут 19 із 40), і робимо двосторонній binomtest проти 0.5. Розбиття близьке до 50/50, p великий → медіана статистично узгоджена з 30-хвилинною ціллю. Це той рідкий випадок, коли «не відхилили H0» — приємний результат: ми тримаємо KPI, а не промахуємось. Нагадайте студентам: не відхилили ≠ довели рівність, але для моніторингу KPI це адекватний інструмент.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="wilcoxon-signed-rank" class="title-slide slide level1 center" data-background-iframe=".07-mu_files/libs/colored-particles/index.html">
<h1>Wilcoxon signed-rank</h1>

</section>
<section id="wilcoxon-signed-rank-keep-the-magnitude" class="slide level2 smaller">
<h2>🏅 Wilcoxon signed-rank: keep the magnitude</h2>
<div class="columns">
<div class="column" style="width:48%;">
<p>The sign test wastes <em>how big</em> each change was. Wilcoxon <strong>ranks the absolute differences</strong>, then re-attaches their signs:</p>
<p><span class="math display">\[
W = \sum_{i=1}^{n} \text{rank}\big(|d_i|\big)\cdot \text{sign}(d_i).
\]</span></p>
<p>A few large improvements now outweigh many tiny dips. Distribution is tabulated, <span class="math inline">\(\to\)</span> normal for large <span class="math inline">\(n\)</span>.</p>
</div><div class="column" style="width:52%;">
<div id="signed-rank" class="cell columns column-output-location" data-execution_count="7">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="" aria-hidden="true" tabindex="-1"></a>absrank <span class="op">=</span> rankdata(np.<span class="bu">abs</span>(d_u))</span>
<span id="cb7-2"><a href="" aria-hidden="true" tabindex="-1"></a>W <span class="op">=</span> np.<span class="bu">sum</span>(absrank <span class="op">*</span> np.sign(d_u))     <span class="co"># by hand</span></span>
<span id="cb7-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="" aria-hidden="true" tabindex="-1"></a>p_sr <span class="op">=</span> wilcoxon(new_u, old_u,</span>
<span id="cb7-5"><a href="" aria-hidden="true" tabindex="-1"></a>                alternative<span class="op">=</span><span class="st">"greater"</span>).pvalue</span>
<span id="cb7-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"signed-rank W = </span><span class="sc">{</span>W<span class="sc">:.0f}</span><span class="ss">"</span>)</span>
<span id="cb7-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"scipy p-value = </span><span class="sc">{</span>p_sr<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>signed-rank W = 317
scipy p-value = 0.0003</code></pre>
</div>
</div></div>
</div></div>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Extra assumption: the differences <span class="math inline">\(d_i\)</span> are <strong>symmetric</strong> about their center. Milder than full normality, but not free — check a histogram of <span class="math inline">\(d_i\)</span> first. (<code>scipy.stats.wilcoxon</code>.)</p>
</div>
</div>
</div>
<aside class="notes">
<p>Знаковий критерій марнує інформацію про РОЗМІР кожної зміни. Вілкоксон ранжує модулі різниць |d_i|, а потім повертає їм знаки: W = Σ rank(|d_i|)·sign(d_i). Тепер кілька великих покращень переважують багато дрібних просідань — критерій чутливіший, тобто потужніший за знаковий. Розподіл статистики табличний і прямує до нормального на великих n.&nbsp;У коді рахуємо W вручну через rankdata і звіряємо зі scipy.stats.wilcoxon — p≈0.0003. Важлива ДОДАТКОВА умова: різниці d_i мають бути СИМЕТРИЧНІ відносно свого центру. Це слабше за повну нормальність, але не безкоштовно — спершу гляньте на гістограму d_i. Якщо симетрії немає, повертайтесь до знакового критерію.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="same-crossover-three-tests" class="slide level2 smaller">
<h2>⚔️ Same crossover, three tests</h2>
<div id="three-paired-tests" class="cell columns column-output-location" data-execution_count="8">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> paired_pvals(new, old, n):</span>
<span id="cb9-2"><a href="" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> new <span class="op">-</span> old</span>
<span id="cb9-3"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {</span>
<span id="cb9-4"><a href="" aria-hidden="true" tabindex="-1"></a>        <span class="st">"sign"</span>:        binomtest(<span class="bu">int</span>((d <span class="op">&gt;</span> <span class="dv">0</span>).<span class="bu">sum</span>()), n, <span class="fl">0.5</span>,</span>
<span id="cb9-5"><a href="" aria-hidden="true" tabindex="-1"></a>                                 alternative<span class="op">=</span><span class="st">"greater"</span>).pvalue,</span>
<span id="cb9-6"><a href="" aria-hidden="true" tabindex="-1"></a>        <span class="st">"signed-rank"</span>: wilcoxon(new, old, alternative<span class="op">=</span><span class="st">"greater"</span>).pvalue,</span>
<span id="cb9-7"><a href="" aria-hidden="true" tabindex="-1"></a>        <span class="st">"paired t"</span>:    ttest_rel(new, old, alternative<span class="op">=</span><span class="st">"greater"</span>).pvalue,</span>
<span id="cb9-8"><a href="" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb9-9"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="" aria-hidden="true" tabindex="-1"></a>clean <span class="op">=</span> paired_pvals(new_u, old_u, n_pair)</span>
<span id="cb9-11"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># one binge-on-old user joins the experiment</span></span>
<span id="cb9-13"><a href="" aria-hidden="true" tabindex="-1"></a>new_o <span class="op">=</span> np.append(new_u, <span class="fl">60.0</span>)</span>
<span id="cb9-14"><a href="" aria-hidden="true" tabindex="-1"></a>old_o <span class="op">=</span> np.append(old_u, <span class="fl">500.0</span>)</span>
<span id="cb9-15"><a href="" aria-hidden="true" tabindex="-1"></a>out   <span class="op">=</span> paired_pvals(new_o, old_o, n_pair <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb9-16"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name <span class="kw">in</span> clean:</span>
<span id="cb9-18"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:12s}</span><span class="ss"> clean=</span><span class="sc">{</span>clean[name]<span class="sc">:.4f}</span><span class="ss">  +outlier=</span><span class="sc">{</span>out[name]<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>sign         clean=0.0026  +outlier=0.0053
signed-rank  clean=0.0003  +outlier=0.0021
paired t     clean=0.0006  +outlier=0.7244</code></pre>
</div>
</div></div>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>On clean data the <strong>signed-rank</strong> <span class="math inline">\(p\)</span> tracks the paired <span class="math inline">\(t\)</span>-test. Add one extreme user and the <span class="math inline">\(t\)</span>-test’s <span class="math inline">\(p\)</span> jumps to <span class="math inline">\(\approx 0.72\)</span> — its verdict flips — while the <strong>sign</strong> and <strong>signed-rank</strong> tests barely move. Magnitude buys power; ranks buy robustness.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Двобій трьох парних критеріїв на одних даних. На чистих даних signed-rank іде пліч-о-пліч із парним t-тестом (обидва p≈0.0003–0.0006), знаковий трохи слабший (≈0.003), але теж значущий. Потім додаємо одного користувача-«binge», який на старій системі наслухав 500 хв, а на новій лише 60 (величезна від’ємна різниця). p парного t-тесту підскакує до ≈0.72 — вердикт перевертається, бо різниця середніх стає заручником одного викиду. А знаковий і знаково-ранговий майже не ворухнулися (≈0.005 і ≈0.002). Мораль: величина дає потужність (signed-rank &gt; sign), а ранги/знаки дають робастність до викидів (обидва &gt; t). Це і є компроміс, який ми обираємо свідомо.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="how-much-does-magnitude-buy" class="slide level2 smaller">
<h2>🧪 How much does magnitude buy?</h2>
<p>Power on <strong>heavy-tailed</strong> per-user differences (Student-<span class="math inline">\(t\)</span>, <span class="math inline">\(df=2\)</span>) with a real shift — exactly where outliers live.</p>
<div id="cell-paired-power" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> paired_rejection_rate(shift, n, test, df<span class="op">=</span><span class="dv">2</span>, n_exps<span class="op">=</span><span class="dv">1500</span>, alpha<span class="op">=</span><span class="fl">0.05</span>, seed<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb11-2"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Differences ~ shift + Student-t(df).  shift=0 -&gt; FPR, else power."""</span></span>
<span id="cb11-3"><a href="" aria-hidden="true" tabindex="-1"></a>    rng, rej <span class="op">=</span> np.random.default_rng(seed), <span class="dv">0</span></span>
<span id="cb11-4"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_exps):</span>
<span id="cb11-5"><a href="" aria-hidden="true" tabindex="-1"></a>        d <span class="op">=</span> shift <span class="op">+</span> rng.standard_t(df, n)</span>
<span id="cb11-6"><a href="" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> test <span class="op">==</span> <span class="st">"sign"</span>:</span>
<span id="cb11-7"><a href="" aria-hidden="true" tabindex="-1"></a>            p <span class="op">=</span> binomtest(<span class="bu">int</span>((d <span class="op">&gt;</span> <span class="dv">0</span>).<span class="bu">sum</span>()), n, <span class="fl">0.5</span>).pvalue</span>
<span id="cb11-8"><a href="" aria-hidden="true" tabindex="-1"></a>        <span class="cf">elif</span> test <span class="op">==</span> <span class="st">"sr"</span>:</span>
<span id="cb11-9"><a href="" aria-hidden="true" tabindex="-1"></a>            p <span class="op">=</span> wilcoxon(d).pvalue</span>
<span id="cb11-10"><a href="" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb11-11"><a href="" aria-hidden="true" tabindex="-1"></a>            p <span class="op">=</span> ttest_1samp(d, <span class="dv">0</span>).pvalue</span>
<span id="cb11-12"><a href="" aria-hidden="true" tabindex="-1"></a>        rej <span class="op">+=</span> p <span class="op">&lt;=</span> alpha</span>
<span id="cb11-13"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> rej <span class="op">/</span> n_exps</span>
<span id="cb11-14"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="" aria-hidden="true" tabindex="-1"></a>sizes <span class="op">=</span> [<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">40</span>, <span class="dv">80</span>]</span>
<span id="cb11-16"><a href="" aria-hidden="true" tabindex="-1"></a>curves <span class="op">=</span> {t: [paired_rejection_rate(<span class="fl">0.7</span>, n, t) <span class="cf">for</span> n <span class="kw">in</span> sizes]</span>
<span id="cb11-17"><a href="" aria-hidden="true" tabindex="-1"></a>          <span class="cf">for</span> t <span class="kw">in</span> (<span class="st">"sr"</span>, <span class="st">"sign"</span>, <span class="st">"t"</span>)}</span>
<span id="cb11-18"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-19"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.2</span>))</span>
<span id="cb11-20"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(sizes, curves[<span class="st">"sr"</span>],   color<span class="op">=</span>red_pink, lw<span class="op">=</span><span class="fl">2.5</span>, marker<span class="op">=</span><span class="st">"o"</span>, label<span class="op">=</span><span class="st">"signed-rank"</span>)</span>
<span id="cb11-21"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(sizes, curves[<span class="st">"sign"</span>], color<span class="op">=</span>green,    lw<span class="op">=</span><span class="fl">2.5</span>, marker<span class="op">=</span><span class="st">"^"</span>, label<span class="op">=</span><span class="st">"sign"</span>)</span>
<span id="cb11-22"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(sizes, curves[<span class="st">"t"</span>],    color<span class="op">=</span>blue,     lw<span class="op">=</span><span class="fl">2.5</span>, marker<span class="op">=</span><span class="st">"s"</span>, ls<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="st">"paired t"</span>)</span>
<span id="cb11-23"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="fl">0.8</span>, color<span class="op">=</span>slate, ls<span class="op">=</span><span class="st">":"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"80</span><span class="sc">% g</span><span class="st">old standard"</span>)</span>
<span id="cb11-24"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb11-25"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"# users n"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"power (TPR)"</span>)</span>
<span id="cb11-26"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Heavy-tailed differences: ranks beat the paired t-test"</span>)<span class="op">;</span> ax.legend()</span>
<span id="cb11-27"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb11-28"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".07-mu_files/figure-revealjs/paired-power-output-1.svg" id="paired-power" class="quarto-figure quarto-figure-center r-stretch"><p>Signed-rank leads throughout, the sign test is close behind, and the paired <span class="math inline">\(t\)</span>-test <strong>trails badly</strong> — its variance is wrecked by the tails. With outlier-prone metrics, the nonparametric pair is both safer <em>and</em> stronger.</p>
<aside class="notes">
<p>Перевіряємо потужність на ВАЖКОХВОСТИХ різницях (розподіл Стьюдента з df=2) зі справжнім зсувом — саме там, де живуть викиди. Функція paired_rejection_rate генерує різниці shift + t(df) і проганяє обраний критерій; shift=0 дав би FPR, ненульовий — потужність. На графіку: знаково-ранговий лідирує на всіх n, знаковий трохи позаду, а парний t-тест ПЛЕНТАЄТЬСЯ — його дисперсію руйнують важкі хвости. Висновок для продуктових метрик із викидами: непараметрична пара (sign / signed-rank) одночасно й безпечніша (тримає FPR без нормальності), і потужніша за t. Це дзеркальний аргумент до того, що ми побачимо для незалежних вибірок із Манном–Уітні.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="mannwhitney-u-test" class="title-slide slide level1 center" data-background-iframe=".07-mu_files/libs/colored-particles/index.html">
<h1>Mann–Whitney U-test</h1>

</section>
<section id="two-independent-groups-again" class="slide level2 smaller">
<h2>🎯 Two independent groups again</h2>
<div class="columns">
<div class="column" style="width:42%;">
<p>Now the classic A/B — <strong>independent</strong> control and test groups, no pairing. We drop the assumption of a specific shape; the homogeneity null compares the <strong>whole distributions</strong>:</p>
<p><span class="math display">\[
H_0: F = G \qquad\text{vs.}\qquad H_1: F \neq G,
\]</span></p>
<p>where <span class="math inline">\(F\)</span>, <span class="math inline">\(G\)</span> are the distribution functions of the two groups.</p>
<p>The most useful alternative is a <span class="hi">location shift</span>: the test group is <em>stochastically larger</em>.</p>
</div><div class="column" style="width:58%;">
<div id="a02a1fe5" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src=".07-mu_files/figure-revealjs/cell-11-output-1.svg" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
</div>
</div></div>
<p>Previously we relied on the <strong>values</strong> of the sample items; this time we look not at the values themselves but at their <span class="hi-slate">order</span> relative to each other.</p>
<aside class="notes">
<p>Тепер класичний A/B — дві НЕЗАЛЕЖНІ групи (контроль і тест), без пар. Відмовляємось від припущення про конкретну форму розподілу. Нульова гіпотеза однорідності порівнює РОЗПОДІЛИ цілком: H0: F=G проти H1: F≠G. Найкорисніша альтернатива — зсув положення (location shift): тестова група «стохастично більша», тобто типово видає більші значення. Графік показує саме цей сценарій: та сама форма, зсунута праворуч. Ключова зміна мислення проти z/t/КС: дивимось не на самі значення, а на їхній взаємний ПОРЯДОК. Це і є фундамент непараметричних рангових критеріїв.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="idea-count-the-pairs" class="slide level2 smaller">
<h2>🔢 Idea: count the pairs</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Take every control user and every test user and ask: <em>did the test user listen longer?</em> <strong>Count the winning pairs.</strong></p>
<p><span class="math display">\[
U = \sum_{i=1}^{N}\sum_{j=1}^{M} I\big[A_i &lt; B_j\big],
\]</span></p>
<p>where <span class="math inline">\(A_1,\dots,A_N\)</span> is the control sample, <span class="math inline">\(B_1,\dots,B_M\)</span> is the test sample, and <span class="math inline">\(I[\cdot]\)</span> is <span class="math inline">\(1\)</span> when the condition holds, else <span class="math inline">\(0\)</span>.</p>
</div><div class="column" style="width:45%;">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>If the groups are alike, the test user wins about <strong>half</strong> the time: <span class="math display">\[
\mathbb{E}_{H_0}\,U = \frac{NM}{2}.
\]</span> Far more (or far fewer) winning pairs <span class="math inline">\(\Rightarrow\)</span> one group is shifted.</p>
</div>
</div>
</div>
</div></div>
<div id="u-observed" class="cell columns column-output-location" data-execution_count="11">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="" aria-hidden="true" tabindex="-1"></a>N, M <span class="op">=</span> <span class="bu">len</span>(control), <span class="bu">len</span>(test)</span>
<span id="cb12-2"><a href="" aria-hidden="true" tabindex="-1"></a>U_obs <span class="op">=</span> calculate_U(control, test)   <span class="co"># pairs with control &lt; test</span></span>
<span id="cb12-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"N x M       = </span><span class="sc">{</span>N <span class="op">*</span> M<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb12-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"E[U] under H0 = </span><span class="sc">{</span>N <span class="op">*</span> M <span class="op">/</span> <span class="dv">2</span><span class="sc">:.0f}</span><span class="ss">"</span>)</span>
<span id="cb12-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"observed U    = </span><span class="sc">{</span>U_obs<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>N x M       = 6400
E[U] under H0 = 3200
observed U    = 4137</code></pre>
</div>
</div></div>
<p><code>U</code> <span class="math inline">\(=\)</span> 4137 against an expected 3200. Is that gap big or just noise?</p>
<aside class="notes">
<p>Винаходимо критерій з нуля. Беремо КОЖНУ пару (контрольний користувач, тестовий) і питаємо: чи тестовий слухав довше? Рахуємо «виграшні» пари: U = Σ_i Σ_j I[A_i&lt;B_j]. Якщо групи однакові, тестовий виграє приблизно половину пар, тож E[U]=NM/2. Сильне відхилення вгору чи вниз — ознака зсуву. На наших даних U помітно більший за NM/2 — нова система ніби піднімає прослуховування. Але «помітно» поки на око: треба знати розподіл U при H0, щоб сказати, велике це відхилення чи звичайний шум.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-does-u-look-like-under-h_0" class="slide level2 smaller">
<h2>📊 What does <span class="math inline">\(U\)</span> look like under <span class="math inline">\(H_0\)</span>?</h2>
<p>Simulate the null — both groups drawn from the <strong>same</strong> control distribution — and watch where <span class="math inline">\(U\)</span> lands.</p>
<div id="cell-U-null-dist" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="" aria-hidden="true" tabindex="-1"></a>null_dist <span class="op">=</span> lognorm(s<span class="op">=</span><span class="fl">0.6</span>, scale<span class="op">=</span>np.exp(<span class="fl">3.4</span>))   <span class="co"># the control law</span></span>
<span id="cb14-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="" aria-hidden="true" tabindex="-1"></a>stats <span class="op">=</span> np.array([</span>
<span id="cb14-4"><a href="" aria-hidden="true" tabindex="-1"></a>    calculate_U(null_dist.rvs(N, random_state<span class="op">=</span>rng),</span>
<span id="cb14-5"><a href="" aria-hidden="true" tabindex="-1"></a>                null_dist.rvs(M, random_state<span class="op">=</span>rng))</span>
<span id="cb14-6"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">2000</span>)</span>
<span id="cb14-7"><a href="" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb14-8"><a href="" aria-hidden="true" tabindex="-1"></a>lo, hi <span class="op">=</span> np.quantile(stats, [<span class="fl">0.025</span>, <span class="fl">0.975</span>])</span>
<span id="cb14-9"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.2</span>))</span>
<span id="cb14-11"><a href="" aria-hidden="true" tabindex="-1"></a>ax.hist(stats, bins<span class="op">=</span><span class="st">"auto"</span>, color<span class="op">=</span>turquoise, alpha<span class="op">=</span><span class="fl">0.9</span>, label<span class="op">=</span><span class="st">"$U$ under $H_0$"</span>)</span>
<span id="cb14-12"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axvline(N <span class="op">*</span> M <span class="op">/</span> <span class="dv">2</span>, color<span class="op">=</span>slate,   lw<span class="op">=</span><span class="fl">2.5</span>, label<span class="op">=</span><span class="vs">r"</span><span class="dv">$\m</span><span class="vs">athbb{E}_{H_0}U</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb14-13"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axvline(U_obs,     color<span class="op">=</span>red_pink, lw<span class="op">=</span><span class="dv">3</span>,   label<span class="op">=</span><span class="ss">f"observed U = </span><span class="sc">{</span>U_obs<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb14-14"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axvspan(lo, hi, color<span class="op">=</span>yellow, alpha<span class="op">=</span><span class="fl">0.15</span>, label<span class="op">=</span><span class="st">"95</span><span class="sc">% c</span><span class="st">entral band"</span>)</span>
<span id="cb14-15"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Null distribution of U vs the observed value"</span>)</span>
<span id="cb14-16"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"U"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"count"</span>)<span class="op">;</span> ax.legend(fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb14-17"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb14-18"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".07-mu_files/figure-revealjs/u-null-dist-output-1.svg" id="u-null-dist" class="quarto-figure quarto-figure-center r-stretch"><p>95% central band: 2635–3781. The observed <span class="math inline">\(U\)</span> sits <strong>outside</strong> it <span class="math inline">\(\Rightarrow\)</span> we reject <span class="math inline">\(H_0\)</span> — but this band was tailor-made for this case. We need a <em>general</em> yardstick.</p>
<aside class="notes">
<p>Будуємо нульовий розподіл емпірично: 2000 разів генеруємо ОБИДВІ групи з однакового (контрольного) розподілу й щоразу рахуємо U. Гістограма центрована на NM/2, як і обіцяла теорія. Жовта смуга — центральні 95%. Спостережене U лежить ПОЗА нею — отже, відхиляємо H0. Це той самий хід, що з Монте-Карло раніше. Проблема: ця смуга підігнана під конкретний цей кейс і розмір вибірки. Потрібен універсальний орієнтир — теоретичний розподіл U, щоб не симулювати щоразу.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="normal-approximation" class="slide level2 smaller">
<h2>🔔 Normal approximation</h2>
<div class="columns">
<div class="column" style="width:42%;">
<p><span class="math inline">\(U\)</span> is a sum of many indicators, so the <strong>CLT</strong> kicks in. Under <span class="math inline">\(H_0\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
U &amp;\overset{H_0}{\longrightarrow} \mathcal{N}\big(\mathbb{E}U,\ \mathbb{D}U\big),\\[4pt]
\mathbb{E}U &amp;= \frac{NM}{2},\\[4pt]
\mathbb{D}U &amp;= \frac{NM\,(N + M + 1)}{12}.
\end{aligned}
\]</span></p>
<p>Standardise and read a <span class="math inline">\(p\)</span>-value off <span class="math inline">\(\mathcal{N}(0,1)\)</span> — no simulation needed.</p>
</div><div class="column" style="width:58%;">
<div id="cell-U-normal" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="" aria-hidden="true" tabindex="-1"></a>EU <span class="op">=</span> N <span class="op">*</span> M <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb15-2"><a href="" aria-hidden="true" tabindex="-1"></a>DU <span class="op">=</span> N <span class="op">*</span> M <span class="op">*</span> (N <span class="op">+</span> M <span class="op">+</span> <span class="dv">1</span>) <span class="op">/</span> <span class="dv">12</span></span>
<span id="cb15-3"><a href="" aria-hidden="true" tabindex="-1"></a>approx <span class="op">=</span> norm(loc<span class="op">=</span>EU, scale<span class="op">=</span>np.sqrt(DU))</span>
<span id="cb15-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="" aria-hidden="true" tabindex="-1"></a>xs <span class="op">=</span> np.linspace(stats.<span class="bu">min</span>(), stats.<span class="bu">max</span>(), <span class="dv">400</span>)</span>
<span id="cb15-6"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">4.4</span>))</span>
<span id="cb15-7"><a href="" aria-hidden="true" tabindex="-1"></a>ax.hist(stats, bins<span class="op">=</span><span class="st">"auto"</span>, density<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span>turquoise, alpha<span class="op">=</span><span class="fl">0.8</span>,</span>
<span id="cb15-8"><a href="" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"simulated $U$"</span>)</span>
<span id="cb15-9"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(xs, approx.pdf(xs), color<span class="op">=</span>blue, lw<span class="op">=</span><span class="fl">2.8</span>, label<span class="op">=</span><span class="st">"normal approx."</span>)</span>
<span id="cb15-10"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axvline(EU, color<span class="op">=</span>slate, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="vs">r"</span><span class="dv">$\m</span><span class="vs">athbb{E}_{H_0}U</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb15-11"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Theory matches the simulation"</span>)</span>
<span id="cb15-12"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"U"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"density"</span>)<span class="op">;</span> ax.legend(fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb15-13"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb15-14"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src=".07-mu_files/figure-revealjs/u-normal-output-1.svg" id="u-normal" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
</div>
</div></div>
<p>The bell fits. But computing <span class="math inline">\(U\)</span> by the double loop is <span class="math inline">\(O(NM)\)</span> — slow on millions of users. There is a shortcut.</p>
<aside class="notes">
<p>U — сума багатьох індикаторів, тож за ЦГТ при H0 вона прямує до нормального з матсподіванням NM/2 і дисперсією NM(N+M+1)/12. Це дає аналітичний орієнтир: стандартизуємо U і читаємо p-value з N(0,1), без жодних симуляцій. Графік: теоретична крива чудово лягає на симульовану гістограму. Єдина вада — рахувати U подвійним циклом це O(NM), на мільйонах користувачів задорого. Далі покажемо трюк через ранги, що зводить обчислення до сортування.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="ranks-the-shortcut" class="title-slide slide level1 center" data-background-iframe=".07-mu_files/libs/colored-particles/index.html">
<h1>Ranks: the shortcut</h1>

</section>
<section id="pool-everyone-and-number-them" class="slide level2 smaller">
<h2>🏁 Pool everyone and number them</h2>
<div class="columns">
<div class="column" style="width:42%;">
<p>Throw both samples into one line, sort ascending, and hand out positions — <strong>ranks</strong>.</p>
<p><span class="math inline">\(A = \color{#20B2AA}{[1, 5, 8, 20]}\)</span></p>
<p><span class="math inline">\(B = \color{#e64173}{[2, 3, 6]}\)</span></p>
<p><span class="math inline">\(A \cup B = [\color{#20B2AA}1, \color{#e64173}2, \color{#e64173}3, \color{#20B2AA}5, \color{#e64173}6, \color{#20B2AA}8, \color{#20B2AA}{20}]\)</span></p>
<p>Ranks of <span class="math inline">\(B\)</span>: <span class="math inline">\(2, 3, 5\)</span>.</p>
</div><div class="column" style="width:58%;">
<div id="7536cb2e" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src=".07-mu_files/figure-revealjs/cell-15-output-1.svg" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
</div>
</div></div>
<p><br></p>
<p>Let <span class="math inline">\(R_j\)</span> be the rank of <span class="math inline">\(B_j\)</span> in the pooled list and <span class="math inline">\(V = R_1 + \dots + R_M\)</span>. The more one group is shifted, the larger (or smaller) its rank sum. The link to our pair count:</p>
<p><span class="math display">\[
U = V - \frac{M(M + 1)}{2}.
\]</span></p>
<aside class="notes">
<p>Прискорення: замість перебору пар об’єднуємо обидві вибірки, сортуємо за зростанням і присвоюємо позиції — ранги. На прикладі ранги групи B: 2, 3, 5. Сума рангів V = R_1+…+R_M. Інтуїція: що сильніше група зсунута вгору, то більша її сума рангів (і навпаки). Магічний місток до підрахунку пар: U = V − M(M+1)/2. Тобто замість O(NM) перебору достатньо відсортувати (O((N+M)log(N+M))) і скласти ранги. Це та сама статистика, лише пораховано розумно.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ties-share-the-rank" class="slide level2 smaller">
<h2>🤝 Ties: share the rank</h2>
<p>When several users have <strong>equal</strong> values (very common with rounded minutes), they would compete for the same positions. The fix: give every tied value the <strong>average</strong> of the positions it spans.</p>
<div id="ties" class="cell columns column-output-location" data-execution_count="15">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="" aria-hidden="true" tabindex="-1"></a>vals <span class="op">=</span> np.array([<span class="dv">10</span>, <span class="dv">12</span>, <span class="dv">12</span>, <span class="dv">12</span>, <span class="dv">15</span>])</span>
<span id="cb16-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"values:"</span>, vals)</span>
<span id="cb16-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"ranks :"</span>, rankdata(vals))   <span class="co"># 1, 3, 3, 3, 5</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>values: [10 12 12 12 15]
ranks : [1. 3. 3. 3. 5.]</code></pre>
</div>
</div></div>
<div class="fragment">
<p>This also patches our pair count: a tie is <strong>half</strong> a win, so the general statistic is <span class="math display">\[
U = \sum_{i}^{N}\sum_{j}^{M}\Big(I[A_i &lt; B_j] + \tfrac12\,I[A_i = B_j]\Big),
\]</span> which is <em>exactly</em> what the average-rank formula <span class="math inline">\(V - \tfrac{M(M+1)}{2}\)</span> computes.</p>
<p>Ties also <strong>shrink</strong> the variance <span class="math inline">\(\mathbb{D}U\)</span>; <code>scipy</code> applies the correction automatically. <code>rankdata</code> already does the averaging for us.</p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Heavy ties (many identical values) make the normal approximation rougher — <code>scipy</code> then prefers an exact/corrected <span class="math inline">\(p\)</span>-value. We rarely compute ranks by hand.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Зв’язки (ties) — коли кілька спостережень мають однакове значення (а з округленими хвилинами це постійно). Якби давали їм різні позиції, результат залежав би від випадкового порядку. Розв’язок: усім однаковим значенням — СЕРЕДНІЙ ранг позицій, які вони займають (тут три 12-ки отримують ранг 3). Це заодно лагодить і наш підрахунок пар: зв’язок — це «пів-перемоги», тож загальна статистика U = ΣΣ(I[A&lt;B] + ½·I[A=B]), і це РІВНО те, що дає формула середніх рангів V−M(M+1)/2. Зв’язки ще й зменшують дисперсію U, тому в нормальне наближення вводять поправку на зв’язки — scipy робить це сам. rankdata теж усереднює автоматично. За сильних зв’язків наближення грубіше, і scipy перемикається на точний/скоригований p-value. Руками ранги майже ніколи не рахуємо.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="running-the-test" class="title-slide slide level1 center" data-background-iframe=".07-mu_files/libs/colored-particles/index.html">
<h1>Running the test</h1>

</section>
<section id="algorithm" class="slide level2 smaller">
<h2>🧭 Algorithm</h2>
<p>Testing <span class="math inline">\(H_0: F = G\)</span> vs <span class="math inline">\(H_1: F \neq G\)</span>:</p>
<ol type="1">
<li>Fix a significance level <span class="math inline">\(\alpha\)</span>.</li>
<li><strong>Pool</strong> both samples and assign ranks <span class="math inline">\(1, \dots, N+M\)</span> (average ranks for ties).</li>
<li>Sum the ranks of group <span class="math inline">\(B\)</span>: <span class="math inline">\(V = R_1 + \dots + R_M\)</span>, then <span class="math inline">\(U = V - \dfrac{M(M+1)}{2}\)</span>.</li>
<li>Under <span class="math inline">\(H_0\)</span> use <span class="math inline">\(\mathbb{E}U = \dfrac{NM}{2}\)</span>, <span class="math inline">\(\mathbb{D}U = \dfrac{NM(N+M+1)}{12}\)</span> and <span class="math display">\[
Z = \frac{U - \mathbb{E}U}{\sqrt{\mathbb{D}U}} \overset{H_0}{\longrightarrow} \mathcal{N}(0, 1).
\]</span></li>
<li>Read the <span class="math inline">\(p\)</span>-value from <span class="math inline">\(\mathcal{N}(0,1)\)</span> (or use the <strong>exact</strong> distribution for small samples).</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(p\text{-value} \leq \alpha\)</span>.</li>
</ol>
<p><br></p>
<center>
<strong>It does not depend on the magnitude of the values — only their order.</strong>
</center>
<aside class="notes">
<p>Покроковий рецепт. Перевіряємо H0: F=G. (1) Фіксуємо α. (2) Об’єднуємо вибірки і присвоюємо ранги, для зв’язків — середні. (3) Сумуємо ранги групи B → V, далі U=V−M(M+1)/2. (4) При H0 беремо E[U] і D[U], стандартизуємо в Z. (5) p-value з N(0,1), а на малих вибірках — з точного розподілу U. (6) Порівнюємо з α. Головна теза слайда: критерій залежить лише від ПОРЯДКУ значень, а не від їхньої величини — тому стійкий до викидів і не вимагає нормальності. Це його суперсила.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-the-test-assumes" class="slide level2 smaller">
<h2>📋 What the test assumes</h2>
<p>Distribution-free is <em>not</em> assumption-free. Mann–Whitney still needs:</p>
<ol type="1">
<li><strong>Independence</strong> — observations independent <em>within</em> each group and <em>between</em> the two groups. No pairing, no repeated measures on the same user.</li>
<li><strong>At least an ordinal scale</strong> — values must be rankable (minutes, ratings, ranks). Nominal categories don’t qualify.</li>
<li><strong>Same shape</strong>, for the <em>median/shift</em> reading — if <span class="math inline">\(F\)</span> and <span class="math inline">\(G\)</span> differ only by a <strong>location shift</strong>, the test is a clean test of the median difference. Differ in <strong>spread or shape</strong> and it still validly detects whether one group is <em>stochastically larger</em>, just not “the medians differ”.</li>
</ol>
<div class="fragment">
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Samples <strong>paired</strong> (same user before/after, matched pairs)? Independence breaks → that’s exactly the <strong>sign</strong> and <strong>Wilcoxon signed-rank</strong> tests we built first, run on the within-pair differences.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Distribution-free ≠ assumption-free. Три припущення критерію Манна–Уітні. (1) Незалежність — спостереження незалежні і всередині кожної групи, і між групами; жодних пар чи повторних вимірів на тому самому користувачі. (2) Щонайменше порядкова шкала — значення мають бути ранжовними (хвилини, оцінки, ранги), номінальні категорії не годяться. (3) Однакова форма — САМЕ для трактування як тесту медіан/зсуву: якщо F і G різняться лише положенням, це чистий тест різниці медіан; якщо ж формою чи розкидом — критерій усе одно коректно виявляє «чи одна група стохастично більша», але вже не «медіани різні». І ключове: якщо вибірки ПАРНІ (той самий користувач до/після, метчовані пари), незалежність ламається — тоді беремо парний критерій (знаковий або signed-rank Вілкоксона) на різницях усередині пар, саме ті, що ми розглянули на початку лекції.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="mannwhitneyu-in-one-line" class="slide level2 smaller">
<h2>🐍 <code>mannwhitneyu</code> in one line</h2>
<div id="scipy-mw" class="cell columns column-output-location" data-execution_count="16">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> mannwhitneyu(control, test, alternative<span class="op">=</span><span class="st">"two-sided"</span>)</span>
<span id="cb18-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"U (control) = </span><span class="sc">{</span>res<span class="sc">.</span>statistic<span class="sc">:.0f}</span><span class="ss">"</span>)</span>
<span id="cb18-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-value     = </span><span class="sc">{</span>res<span class="sc">.</span>pvalue<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb18-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"reject H0"</span> <span class="cf">if</span> res.pvalue <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> <span class="st">"keep H0"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>U (control) = 2263
p-value     = 0.0014
reject H0</code></pre>
</div>
</div></div>
<div class="fragment">
<p><code>scipy</code> reports <span class="math inline">\(U\)</span> for the <strong>first</strong> argument; the two are complementary, <span class="math inline">\(U_A + U_B = NM\)</span>, so <code>mannwhitneyu(test, control).statistic</code> equals our pair count 4137.</p>
<ul>
<li><code>alternative="greater"</code> / <code>"less"</code> give the <strong>one-sided</strong> tests (“did the new recsys <em>increase</em> listening?”).</li>
<li><code>method="auto"</code> picks the <strong>exact</strong> distribution for small <span class="math inline">\(n\)</span> and the <strong>normal</strong> approximation (with a tie correction) otherwise.</li>
<li><code>use_continuity=True</code> (default) shaves <span class="math inline">\(0.5\)</span> off the gap before standardising, so a hand-computed <span class="math inline">\(Z\)</span> won’t match scipy exactly on small samples.</li>
</ul>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Same test, second name: <strong>Wilcoxon rank-sum test</strong>. <code>scipy.stats.ranksums</code> runs it via the normal approximation (here <span class="math inline">\(p \approx 0.0014\)</span>, identical). Don’t confuse it with the <em>paired</em> <strong>Wilcoxon signed-rank</strong> test — that one is for dependent samples (covered earlier).</p>
</div>
</div>
</div>
<aside class="notes">
<p>Уся побудована теорія — один виклик mannwhitneyu. Повертає статистику U (для ПЕРШОГО аргументу) і p-value. Важлива деталь: scipy рахує U для першого аргументу, а він доповнює наш: U_A+U_B=NM, тож mannwhitneyu(test, control) дасть саме наш підрахунок пар. alternative=‘greater’/‘less’ — односторонні гіпотези (наприклад, «нова система ЗБІЛЬШИЛА прослуховування»). method=‘auto’ сам обирає точний розподіл на малих вибірках і нормальне наближення з поправкою на зв’язки на великих. use_continuity=True (дефолт) віднімає 0.5 перед стандартизацією, тож ручний Z не збіжиться зі scipy на малих вибірках — це нормально. Окремо наголосіть на двох назвах: критерій Манна–Уітні = критерій суми рангів Вілкоксона (scipy.stats.ranksums, через нормальне наближення), і його НЕ можна плутати з парним signed-rank Вілкоксона для залежних вибірок. Практично студенту достатньо знати, що передати й як прочитати p-value.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="same-data-two-tests" class="slide level2 smaller">
<h2>⚔️ Same data, two tests</h2>
<p>Run the parametric <span class="math inline">\(t\)</span>-test and the rank test on the <strong>identical</strong> listening data:</p>
<div id="t-vs-mw" class="cell columns column-output-location" data-execution_count="17">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="" aria-hidden="true" tabindex="-1"></a>p_t  <span class="op">=</span> ttest_ind(control, test).pvalue</span>
<span id="cb20-2"><a href="" aria-hidden="true" tabindex="-1"></a>p_mw <span class="op">=</span> mannwhitneyu(control, test, alternative<span class="op">=</span><span class="st">"two-sided"</span>).pvalue</span>
<span id="cb20-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Welch/t-test p-value      = </span><span class="sc">{</span>p_t<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb20-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Mann-Whitney p-value      = </span><span class="sc">{</span>p_mw<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb20-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co"># now drop in one all-night listener into control</span></span>
<span id="cb20-8"><a href="" aria-hidden="true" tabindex="-1"></a>control_out <span class="op">=</span> np.append(control, <span class="dv">1500</span>)</span>
<span id="cb20-9"><a href="" aria-hidden="true" tabindex="-1"></a>p_t2  <span class="op">=</span> ttest_ind(control_out, test).pvalue</span>
<span id="cb20-10"><a href="" aria-hidden="true" tabindex="-1"></a>p_mw2 <span class="op">=</span> mannwhitneyu(control_out, test).pvalue</span>
<span id="cb20-11"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">+1 outlier in control:"</span>)</span>
<span id="cb20-12"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  t-test p-value  = </span><span class="sc">{</span>p_t2<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb20-13"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Mann-Whitney p  = </span><span class="sc">{</span>p_mw2<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>Welch/t-test p-value      = 0.0008
Mann-Whitney p-value      = 0.0014

+1 outlier in control:
  t-test p-value  = 0.8658
  Mann-Whitney p  = 0.0024</code></pre>
</div>
</div></div>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>A single outlier inflates the control mean and <strong>rescues</strong> the <span class="math inline">\(t\)</span>-test’s null, flipping its verdict. The rank test barely notices — its decision rests on <strong>order</strong>, which one extreme value cannot bend.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Прямий двобій на ОДНИХ І ТИХ САМИХ даних. Спочатку обидва тести бачать ефект. Потім додаємо одного користувача-«сову» на 1500 хв у контроль: середнє контролю підскакує, різниця середніх тане — і t-тест втрачає значущість, перевертаючи висновок. Манн–Уітні майже не реагує: його рішення спирається на порядок, а один екстремум не зрушить ранги. Це наочна демонстрація робастності рангового критерію до викидів і скошеності. Мораль: на продуктових метриках з хвостами ранговий тест часто чесніший за t-тест.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="does-it-hold-its-promises" class="title-slide slide level1 center" data-background-iframe=".07-mu_files/libs/colored-particles/index.html">
<h1>Does it hold its promises?</h1>

</section>
<section id="a-reusable-monte-carlo-checker" class="slide level2 smaller">
<h2>🧪 A reusable Monte-Carlo checker</h2>
<p>Same habit as for the <span class="math inline">\(t\)</span>-, KS- and <span class="math inline">\(\chi^2\)</span>-tests: simulate, count rejections, add a Wilson CI.</p>
<div id="mw-mc-fn" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> rejection_rate(dist_a, dist_b, n, test<span class="op">=</span><span class="st">"mw"</span>, alpha<span class="op">=</span><span class="fl">0.05</span>,</span>
<span id="cb22-2"><a href="" aria-hidden="true" tabindex="-1"></a>                   n_exps<span class="op">=</span><span class="dv">1500</span>, seed<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb22-3"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Two-sample rejection rate via Monte Carlo.</span></span>
<span id="cb22-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co">    dist_a == dist_b -&gt; H0 true  -&gt; the rate is the FPR.</span></span>
<span id="cb22-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co">    dist_a != dist_b -&gt; H1 true  -&gt; the rate is the power (TPR).</span></span>
<span id="cb22-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co">    test = 'mw' (Mann-Whitney) or 't' (two-sample t-test).</span></span>
<span id="cb22-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb22-9"><a href="" aria-hidden="true" tabindex="-1"></a>    rng, rej <span class="op">=</span> np.random.default_rng(seed), <span class="dv">0</span></span>
<span id="cb22-10"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_exps):</span>
<span id="cb22-11"><a href="" aria-hidden="true" tabindex="-1"></a>        a <span class="op">=</span> dist_a.rvs(n, random_state<span class="op">=</span>rng)</span>
<span id="cb22-12"><a href="" aria-hidden="true" tabindex="-1"></a>        b <span class="op">=</span> dist_b.rvs(n, random_state<span class="op">=</span>rng)</span>
<span id="cb22-13"><a href="" aria-hidden="true" tabindex="-1"></a>        p <span class="op">=</span> (mannwhitneyu(a, b, alternative<span class="op">=</span><span class="st">"two-sided"</span>).pvalue</span>
<span id="cb22-14"><a href="" aria-hidden="true" tabindex="-1"></a>             <span class="cf">if</span> test <span class="op">==</span> <span class="st">"mw"</span> <span class="cf">else</span> ttest_ind(a, b).pvalue)</span>
<span id="cb22-15"><a href="" aria-hidden="true" tabindex="-1"></a>        rej <span class="op">+=</span> p <span class="op">&lt;=</span> alpha</span>
<span id="cb22-16"><a href="" aria-hidden="true" tabindex="-1"></a>    ci <span class="op">=</span> proportion_confint(rej, n_exps, alpha<span class="op">=</span><span class="fl">0.05</span>, method<span class="op">=</span><span class="st">"wilson"</span>)</span>
<span id="cb22-17"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> rej <span class="op">/</span> n_exps, ci</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Pass the <strong>same</strong> distribution twice to measure the FPR, <strong>different</strong> ones to measure power.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Перевикористовуємо звичку валідувати критерій Монте-Карло — як для t-, KS- і χ²-тестів. Функція rejection_rate: тисячі разів генерує дві вибірки, проганяє обраний тест (‘mw’ або ‘t’) і рахує частку відхилень + інтервал Уілсона. Однаковий розподіл двічі → H0 вірна → міряємо FPR (хибнопозитивні). Різні розподіли → потужність. Один двигун обслуговує і перевірку каліброваності, і порівняння потужності — далі застосуємо його до скошених і нормальних даних.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="fpr-calibrated-without-normality" class="slide level2 smaller">
<h2>✅ FPR: calibrated without normality</h2>
<p>Draw both groups from the <strong>same skewed</strong> law (lognormal) — any rejection is a false positive.</p>
<div id="cell-mw-fpr" class="cell" data-execution_count="19">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="" aria-hidden="true" tabindex="-1"></a>null <span class="op">=</span> lognorm(s<span class="op">=</span><span class="fl">0.6</span>, scale<span class="op">=</span>np.exp(<span class="fl">3.4</span>))</span>
<span id="cb23-2"><a href="" aria-hidden="true" tabindex="-1"></a>sizes <span class="op">=</span> [<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">40</span>, <span class="dv">80</span>, <span class="dv">160</span>]</span>
<span id="cb23-3"><a href="" aria-hidden="true" tabindex="-1"></a>mw <span class="op">=</span> [rejection_rate(null, null, n, test<span class="op">=</span><span class="st">"mw"</span>) <span class="cf">for</span> n <span class="kw">in</span> sizes]</span>
<span id="cb23-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.2</span>))</span>
<span id="cb23-6"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(sizes, [r <span class="cf">for</span> r, _ <span class="kw">in</span> mw], color<span class="op">=</span>red_pink, lw<span class="op">=</span><span class="fl">2.5</span>, marker<span class="op">=</span><span class="st">"o"</span>,</span>
<span id="cb23-7"><a href="" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"Mann–Whitney FPR"</span>)</span>
<span id="cb23-8"><a href="" aria-hidden="true" tabindex="-1"></a>ax.fill_between(sizes, [c[<span class="dv">0</span>] <span class="cf">for</span> _, c <span class="kw">in</span> mw], [c[<span class="dv">1</span>] <span class="cf">for</span> _, c <span class="kw">in</span> mw],</span>
<span id="cb23-9"><a href="" aria-hidden="true" tabindex="-1"></a>                color<span class="op">=</span>turquoise, alpha<span class="op">=</span><span class="fl">0.3</span>, label<span class="op">=</span><span class="st">"95% CI"</span>)</span>
<span id="cb23-10"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="fl">0.05</span>, color<span class="op">=</span>slate, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="vs">r"</span><span class="dv">$</span><span class="ch">\a</span><span class="vs">lpha = 0</span><span class="dv">.</span><span class="vs">05</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb23-11"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="fl">0.15</span>)</span>
<span id="cb23-12"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"group size n"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"FPR"</span>)</span>
<span id="cb23-13"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"False-positive rate on skewed null data"</span>)<span class="op">;</span> ax.legend()</span>
<span id="cb23-14"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb23-15"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".07-mu_files/figure-revealjs/mw-fpr-output-1.svg" id="mw-fpr" class="quarto-figure quarto-figure-center r-stretch"><p>The FPR sits on <span class="math inline">\(\alpha\)</span> at every sample size — the rank test is <strong>distribution-free</strong>: it never relied on normality to begin with.</p>
<aside class="notes">
<p>A/A-перевірка: обидві групи з ОДНОГО скошеного (логнормального) розподілу, тож будь-яке відхилення — хибне. Крива FPR Манна–Уітні лягає на 5% за всіх розмірів вибірки, інтервал Уілсона накриває α. Це й означає «distribution-free»: критерій не спирався на нормальність, тому скошеність його не псує. Контраст із t-тестом тут не драматичний за рівних вибірок, головна перевага рангового тесту проявиться в ПОТУЖНОСТІ на скошених даних — це наступні слайди. Висновок: Манн–Уітні чесно тримає обіцяний рівень помилки I роду на реальних продуктових даних.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="power-on-normal-data-the-cost-of-ranks" class="slide level2 smaller">
<h2>⚖️ Power on normal data: the cost of ranks</h2>
<p>When the data <strong>are</strong> normal, throwing away magnitudes for ranks costs a little power.</p>
<div id="cell-power-normal" class="cell" data-execution_count="20">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="" aria-hidden="true" tabindex="-1"></a>a_norm <span class="op">=</span> norm(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb24-2"><a href="" aria-hidden="true" tabindex="-1"></a>b_norm <span class="op">=</span> norm(<span class="fl">0.4</span>, <span class="dv">1</span>)        <span class="co"># a genuine shift</span></span>
<span id="cb24-3"><a href="" aria-hidden="true" tabindex="-1"></a>sizes  <span class="op">=</span> [<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">40</span>, <span class="dv">80</span>, <span class="dv">160</span>]</span>
<span id="cb24-4"><a href="" aria-hidden="true" tabindex="-1"></a>mw <span class="op">=</span> [rejection_rate(a_norm, b_norm, n, test<span class="op">=</span><span class="st">"mw"</span>) <span class="cf">for</span> n <span class="kw">in</span> sizes]</span>
<span id="cb24-5"><a href="" aria-hidden="true" tabindex="-1"></a>tt <span class="op">=</span> [rejection_rate(a_norm, b_norm, n, test<span class="op">=</span><span class="st">"t"</span>)  <span class="cf">for</span> n <span class="kw">in</span> sizes]</span>
<span id="cb24-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.2</span>))</span>
<span id="cb24-8"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(sizes, [r <span class="cf">for</span> r, _ <span class="kw">in</span> tt], color<span class="op">=</span>blue,    lw<span class="op">=</span><span class="fl">2.5</span>, marker<span class="op">=</span><span class="st">"s"</span>,</span>
<span id="cb24-9"><a href="" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"t-test"</span>)</span>
<span id="cb24-10"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(sizes, [r <span class="cf">for</span> r, _ <span class="kw">in</span> mw], color<span class="op">=</span>red_pink, lw<span class="op">=</span><span class="fl">2.5</span>, marker<span class="op">=</span><span class="st">"o"</span>,</span>
<span id="cb24-11"><a href="" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"Mann–Whitney"</span>)</span>
<span id="cb24-12"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="fl">0.8</span>, color<span class="op">=</span>slate, ls<span class="op">=</span><span class="st">":"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"80</span><span class="sc">% g</span><span class="st">old standard"</span>)</span>
<span id="cb24-13"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb24-14"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"group size n"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"power (TPR)"</span>)</span>
<span id="cb24-15"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Normal data: t-test slightly ahead"</span>)<span class="op">;</span> ax.legend()</span>
<span id="cb24-16"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb24-17"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".07-mu_files/figure-revealjs/power-normal-output-1.svg" id="power-normal" class="quarto-figure quarto-figure-center r-stretch"><p>The <span class="math inline">\(t\)</span>-test wins — but only by a hair (the asymptotic efficiency of Mann–Whitney under normality is <span class="math inline">\(\approx 95\%\)</span>). You give up almost nothing for the insurance.</p>
<aside class="notes">
<p>Чесна ціна рангів: коли дані СПРАВДІ нормальні, відмова від величин на користь рангів коштує трохи потужності. На графіку t-тест трохи вище за Манна–Уітні, обидва перетинають золоті 80% десь поряд. Але розрив крихітний — асимптотична ефективність Манна–Уітні за нормальності ≈95%, тобто втрачаємо близько 5%. Інакше кажучи, страховка від скошеності й викидів майже безкоштовна навіть у «найкращому для t-тесту» світі. Це знімає головний контраргумент проти непараметрики.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="power-on-skewed-data-ranks-win-big" class="slide level2 smaller">
<h2>🚀 Power on skewed data: ranks win big</h2>
<p>Now the realistic case — a <strong>multiplicative</strong> lift on a heavy right tail (the new recsys lifts everyone ~35%).</p>
<div id="cell-power-skewed" class="cell" data-execution_count="21">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="" aria-hidden="true" tabindex="-1"></a>a_sk <span class="op">=</span> lognorm(s<span class="op">=</span><span class="fl">0.9</span>, scale<span class="op">=</span>np.exp(<span class="fl">3.4</span>))</span>
<span id="cb25-2"><a href="" aria-hidden="true" tabindex="-1"></a>b_sk <span class="op">=</span> lognorm(s<span class="op">=</span><span class="fl">0.9</span>, scale<span class="op">=</span>np.exp(<span class="fl">3.4</span>) <span class="op">*</span> <span class="fl">1.35</span>)   <span class="co"># 35% lift, same shape</span></span>
<span id="cb25-3"><a href="" aria-hidden="true" tabindex="-1"></a>sizes <span class="op">=</span> [<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">40</span>, <span class="dv">80</span>, <span class="dv">160</span>]</span>
<span id="cb25-4"><a href="" aria-hidden="true" tabindex="-1"></a>mw <span class="op">=</span> [rejection_rate(a_sk, b_sk, n, test<span class="op">=</span><span class="st">"mw"</span>) <span class="cf">for</span> n <span class="kw">in</span> sizes]</span>
<span id="cb25-5"><a href="" aria-hidden="true" tabindex="-1"></a>tt <span class="op">=</span> [rejection_rate(a_sk, b_sk, n, test<span class="op">=</span><span class="st">"t"</span>)  <span class="cf">for</span> n <span class="kw">in</span> sizes]</span>
<span id="cb25-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.2</span>))</span>
<span id="cb25-8"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(sizes, [r <span class="cf">for</span> r, _ <span class="kw">in</span> mw], color<span class="op">=</span>red_pink, lw<span class="op">=</span><span class="fl">2.5</span>, marker<span class="op">=</span><span class="st">"o"</span>,</span>
<span id="cb25-9"><a href="" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"Mann–Whitney"</span>)</span>
<span id="cb25-10"><a href="" aria-hidden="true" tabindex="-1"></a>ax.plot(sizes, [r <span class="cf">for</span> r, _ <span class="kw">in</span> tt], color<span class="op">=</span>blue,    lw<span class="op">=</span><span class="fl">2.5</span>, marker<span class="op">=</span><span class="st">"s"</span>,</span>
<span id="cb25-11"><a href="" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"t-test"</span>)</span>
<span id="cb25-12"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="fl">0.8</span>, color<span class="op">=</span>slate, ls<span class="op">=</span><span class="st">":"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"80</span><span class="sc">% g</span><span class="st">old standard"</span>)</span>
<span id="cb25-13"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb25-14"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"group size n"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"power (TPR)"</span>)</span>
<span id="cb25-15"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Skewed data: Mann–Whitney detects the lift sooner"</span>)<span class="op">;</span> ax.legend()</span>
<span id="cb25-16"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb25-17"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".07-mu_files/figure-revealjs/power-skewed-output-1.svg" id="power-skewed" class="quarto-figure quarto-figure-center r-stretch"><div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>On heavy-tailed metrics the rank test reaches 80% power at a <strong>much smaller</strong> sample — the tail that bloats the <span class="math inline">\(t\)</span>-test’s variance simply doesn’t reach the ranks.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Реалістичний кейс: мультиплікативний приріст на важкому правому хвості — нова система піднімає прослуховування приблизно на 35% (та сама форма, більший масштаб). Тепер Манн–Уітні ВПЕВНЕНО випереджає t-тест: досягає 80% потужності на значно меншій вибірці. Причина — хвіст, що роздуває дисперсію t-тесту, просто не «дотягується» до рангів, бо ранг найбільшого значення завжди N+M незалежно від того, наскільки воно велике. Підсумок порівняння: на нормальних даних втрачаємо ~5% потужності, на скошених — виграємо багато. Для продуктових метрик вибір очевидний.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="effect-size-caveats" class="title-slide slide level1 center" data-background-iframe=".07-mu_files/libs/colored-particles/index.html">
<h1>Effect size &amp; caveats</h1>

</section>
<section id="significant-large" class="slide level2 smaller">
<h2>📐 Significant ≠ large</h2>
<p>A <span class="math inline">\(p\)</span>-value says <em>whether</em> the groups differ; it never says <em>by how much</em>. As with Cramér’s <span class="math inline">\(V\)</span> for <span class="math inline">\(\chi^2\)</span>, report an <strong>effect size</strong>.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Probability of superiority</strong> (common-language effect size): <span class="math display">\[
\hat{P}(A &lt; B) = \frac{U}{NM} \in [0, 1].
\]</span> “A random test user beats a random control user <span class="math inline">\(\hat P\)</span> of the time.” <span class="math inline">\(0.5\)</span> means no effect.</p>
</div><div class="column" style="width:50%;">
<p><strong>Rank-biserial correlation:</strong> <span class="math display">\[
r_{rb} = 2\,\hat{P}(A&lt;B) - 1 \in [-1, 1].
\]</span> <span class="math inline">\(0\)</span> = no effect, <span class="math inline">\(\pm 1\)</span> = complete separation.</p>
</div></div>
<div id="effect-size" class="cell columns column-output-location" data-execution_count="22">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="" aria-hidden="true" tabindex="-1"></a>U <span class="op">=</span> calculate_U(control, test)      <span class="co"># pairs control &lt; test</span></span>
<span id="cb26-2"><a href="" aria-hidden="true" tabindex="-1"></a>P_sup <span class="op">=</span> U <span class="op">/</span> (N <span class="op">*</span> M)</span>
<span id="cb26-3"><a href="" aria-hidden="true" tabindex="-1"></a>r_rb  <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> P_sup <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb26-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"P(control &lt; test) = </span><span class="sc">{</span>P_sup<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb26-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"rank-biserial r   = </span><span class="sc">{</span>r_rb<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>P(control &lt; test) = 0.646
rank-biserial r   = 0.293</code></pre>
</div>
</div></div>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>On millions of users <strong>any</strong> shift is “significant”. Always pair the <span class="math inline">\(p\)</span>-value with <span class="math inline">\(\hat P(A&lt;B)\)</span> to judge whether the lift is worth shipping.</p>
</div>
</div>
</div>
<aside class="notes">
<p>p-value каже ЧИ є різниця, але не НАСКІЛЬКИ вона велика — точно як з Cramér’s V для χ². Тому додаємо розмір ефекту. Перший і найзрозноміліший — ймовірність переваги P(A&lt;B)=U/NM: «випадковий тестовий користувач переграє випадкового контрольного у частці P випадків»; 0.5 — ефекту немає. Другий — рангово-бісеріальна кореляція r=2P−1 в діапазоні [−1,1]. На наших даних P помітно більше за 0.5. Ключове застереження (як і для χ² на великих n): на мільйонах користувачів значущим стає будь-який зсув, тож завжди супроводжуйте p-value розміром ефекту, щоб вирішити, чи варто викочувати зміну.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="hodgeslehmann-a-shift-with-a-ci" class="slide level2 smaller">
<h2>📏 Hodges–Lehmann: a shift <em>with</em> a CI</h2>
<p><span class="math inline">\(\hat P(A&lt;B)\)</span> gives the <em>size</em> of the effect but no interval. The <strong>Hodges–Lehmann</strong> estimator gives the shift <strong>in minutes</strong> — the median of all pairwise differences — plus a <strong>distribution-free</strong> confidence interval (the inversion of the U-test).</p>
<div id="hodges-lehmann" class="cell columns column-output-location" data-execution_count="23">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="" aria-hidden="true" tabindex="-1"></a>diffs <span class="op">=</span> np.subtract.outer(test, control).ravel()  <span class="co"># all B - A pairs</span></span>
<span id="cb28-2"><a href="" aria-hidden="true" tabindex="-1"></a>hl    <span class="op">=</span> np.median(diffs)                           <span class="co"># HL shift estimate</span></span>
<span id="cb28-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="" aria-hidden="true" tabindex="-1"></a>ds <span class="op">=</span> np.sort(diffs)</span>
<span id="cb28-5"><a href="" aria-hidden="true" tabindex="-1"></a>z  <span class="op">=</span> norm.ppf(<span class="dv">1</span> <span class="op">-</span> <span class="fl">0.05</span> <span class="op">/</span> <span class="dv">2</span>)</span>
<span id="cb28-6"><a href="" aria-hidden="true" tabindex="-1"></a>k  <span class="op">=</span> <span class="bu">int</span>(np.floor(N <span class="op">*</span> M <span class="op">/</span> <span class="dv">2</span> <span class="op">-</span> z <span class="op">*</span> np.sqrt(N <span class="op">*</span> M <span class="op">*</span> (N <span class="op">+</span> M <span class="op">+</span> <span class="dv">1</span>) <span class="op">/</span> <span class="dv">12</span>)))</span>
<span id="cb28-7"><a href="" aria-hidden="true" tabindex="-1"></a>ci_low, ci_high <span class="op">=</span> ds[k], ds[N <span class="op">*</span> M <span class="op">-</span> <span class="dv">1</span> <span class="op">-</span> k]</span>
<span id="cb28-8"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"HL shift   = </span><span class="sc">{</span>hl<span class="sc">:.1f}</span><span class="ss"> min"</span>)</span>
<span id="cb28-10"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"95% CI     = (</span><span class="sc">{</span>ci_low<span class="sc">:.1f}</span><span class="ss">, </span><span class="sc">{</span>ci_high<span class="sc">:.1f}</span><span class="ss">) min"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>HL shift   = 8.7 min
95% CI     = (3.3, 14.6) min</code></pre>
</div>
</div></div>
<div class="fragment">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The interval excludes <span class="math inline">\(0\)</span> — consistent with the rejected <span class="math inline">\(H_0\)</span> — and, unlike a mean difference, neither the estimate nor its CI is dragged around by the all-night outlier.</p>
</div>
</div>
</div>
<aside class="notes">
<p>P(A&lt;B) дає величину ефекту, але без інтервалу. Оцінювач Ходжеса–Лемана повертає зсув У ХВИЛИНАХ — це медіана ВСІХ попарних різниць (B−A) — плюс distribution-free довірчий інтервал, який є інверсією U-критерію (ті самі квантилі впорядкованих різниць, що відповідають критичному значенню рангової статистики). На наших даних зсув ≈8.7 хв, 95% ДІ ≈ (3.3, 14.6). Інтервал не накриває 0 — узгоджено з відхиленою H0. Головна перевага перед різницею середніх: ні точкова оцінка, ні її ДІ не «тягнуться» за викидом-«совою». Це природне доповнення до слайда про розмір ефекту: тепер маємо і величину, і невизначеність, і все це робастно.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="what-h_0-really-claims" class="slide level2 smaller">
<h2>⚠️ What <span class="math inline">\(H_0\)</span> really claims</h2>
<p>The strict null is <span class="math inline">\(F = G\)</span> — the <strong>whole</strong> distributions match, not just the medians.</p>
<ul>
<li>Under a pure <strong>location shift</strong> (same shape), Mann–Whitney <em>is</em> a clean test of medians/shift. This is the case to aim for.</li>
<li>If the groups differ in <strong>shape or spread</strong> (e.g.&nbsp;the new recsys helps casual users but bores super-fans), a “non-significant” result can still hide a real, <em>re-shaping</em> effect — and a significant one need not mean “B is larger”.</li>
</ul>
<div class="fragment">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Plot the two distributions before interpreting. Mann–Whitney answers “is one group stochastically larger?”, <strong>not</strong> “are the means equal?”.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Тонкість, яку студенти часто плутають: строга H0 — це F=G, тобто збіг РОЗПОДІЛІВ цілком, а не лише медіан. Якщо форма однакова й різниця тільки в положенні (location shift) — Манн–Уітні чисто тестує зсув/медіану, і саме до цього сценарію варто прагнути. Але якщо групи різняться ФОРМОЮ чи розкидом (нова система допомагає casual-користувачам, але набридає фанатам), то «незначущий» результат може ховати реальний перерозподіл, а значущий — не обов’язково означати «B більше». Порада: спершу намалюйте обидва розподіли. Манн–Уітні відповідає на «чи одна група стохастично більша?», а не «чи рівні середні?».</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="summary" class="title-slide slide level1 center" data-background-iframe=".07-mu_files/libs/colored-particles/index.html">
<h1>Summary</h1>

</section>
<section id="the-one-idea" class="slide level2 smaller">
<h2>🧾 The one idea</h2>
<p>Replace <strong>values</strong> with their <span class="hi">order</span>, and the test stops caring about shape or outliers.</p>
<p><span class="math display">\[
U = \sum_{i}^{N}\sum_{j}^{M} I[A_i &lt; B_j] = V - \frac{M(M+1)}{2},
\qquad
U \overset{H_0}{\longrightarrow} \mathcal{N}\!\left(\frac{NM}{2},\ \frac{NM(N+M+1)}{12}\right).
\]</span></p>
<ul>
<li><strong>Pool &amp; rank</strong> the two samples; the rank sum drives the statistic.</li>
<li><strong>Distribution-free</strong> — calibrated FPR with no normality assumption.</li>
<li><strong>Robust</strong> — one outlier cannot bend an order.</li>
<li><strong>Power</strong> — a touch below the <span class="math inline">\(t\)</span>-test on normal data, well above it on skewed/heavy-tailed data.</li>
<li><strong>Effect size</strong> — report <span class="math inline">\(\hat P(A&lt;B) = U/NM\)</span> alongside the <span class="math inline">\(p\)</span>-value, especially on big <span class="math inline">\(n\)</span>.</li>
</ul>
<div class="fragment">
<p>The same trick spans the whole family — keep only <span class="hi-slate">direction</span> (sign test) or <span class="hi">order</span> (rank tests):</p>
<ul>
<li><strong>Independent groups</strong> → <strong>Mann–Whitney</strong>.</li>
<li><strong>Paired / one-sample</strong> → <strong>sign</strong> (direction) or <strong>Wilcoxon signed-rank</strong> (magnitude).</li>
</ul>
<aside class="notes">
<p>Підсумок однією думкою: замініть значення їхнім ПОРЯДКОМ — і критерій перестає залежати від форми розподілу й викидів. Статистика U рахується або як кількість пар, або через суму рангів V, і при H0 прямує до нормального з відомими E і D. Чотири тези: pool &amp; rank — об’єднуємо й ранжуємо; distribution-free — калібрований FPR без нормальності; робастність — один викид не зрушить порядок; потужність — трохи нижча за t на нормальних даних, помітно вища на скошених. І завжди додавайте розмір ефекту P(A&lt;B)=U/NM поряд із p-value, особливо на великих вибірках. Той самий принцип охоплює всю родину критеріїв: лишаємо або НАПРЯМОК (знаковий критерій), або ПОРЯДОК (рангові). Незалежні групи — Манн–Уітні; парні чи одновибіркові — знаковий або знаково-ранговий Вілкоксон.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="which-test-when" class="slide level2 tiny">
<h2>🧭 Which test, when?</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Your situation</th>
<th>Reach for</th>
<th>Watch out for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Two <strong>independent</strong> groups, ~normal, no outliers</td>
<td>two-sample <strong><span class="math inline">\(t\)</span>-test</strong> (<code>ttest_ind</code>)</td>
<td>normality, equal-ish variance</td>
</tr>
<tr class="even">
<td>Two <strong>independent</strong> groups, skewed / outliers / ordinal</td>
<td><strong>Mann–Whitney</strong> (<code>mannwhitneyu</code>)</td>
<td>what <span class="math inline">\(H_0\)</span> means (<span class="math inline">\(F=G\)</span>); ties</td>
</tr>
<tr class="odd">
<td><strong>Paired</strong> / crossover, magnitude matters</td>
<td><strong>Wilcoxon signed-rank</strong> (<code>wilcoxon</code>)</td>
<td>differences symmetric</td>
</tr>
<tr class="even">
<td><strong>Paired</strong> / crossover, assumption-free</td>
<td><strong>sign test</strong> (<code>binomtest</code>)</td>
<td>least powerful (direction only)</td>
</tr>
<tr class="odd">
<td><strong>One sample</strong> vs a target median/KPI</td>
<td><strong>sign</strong> / <strong>signed-rank</strong></td>
<td>symmetry for signed-rank</td>
</tr>
<tr class="even">
<td>Need a magnitude, not just a verdict</td>
<td><strong>Hodges–Lehmann</strong> shift + CI, or <strong><span class="math inline">\(\hat P(A&lt;B)\)</span></strong></td>
<td>significant <span class="math inline">\(\neq\)</span> large on big <span class="math inline">\(n\)</span></td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The meta-lesson of the course still holds: when in doubt, <span class="hi">validate the test with Monte Carlo</span> on data that looks like yours.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Шпаргалка «який критерій коли», згрупована за ДИЗАЙНОМ. Дві НЕЗАЛЕЖНІ групи, приблизно нормальні без викидів — двовибірковий t-тест; скошені/важкохвості/порядкові — Манн–Уітні (H0 — це F=G цілком, стежте за зв’язками). ПАРНІ/крос-овер: якщо величина зміни важлива — знаково-ранговий Вілкоксон (різниці мають бути симетричні); якщо хочемо нуль припущень — знаковий критерій (найслабший, лише напрямок). ОДНА вибірка проти цільового KPI/медіани — знаковий або знаково-ранговий. Потрібен розмір, а не лише вердикт — Ходжес–Леман з ДІ або P(A&lt;B), бо на великих n значуще ≠ велике. І наскрізний мета-урок курсу: маєте сумнів щодо каліброваності — переваліруйте критерій Монте-Карло на даних, схожих на ваші.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section id="questions" class="title-slide slide level1 unnumbered unlisted center" data-background-iframe=".07-mu_files/libs/colored-particles/index.html">
<h1>Questions?</h1>
<p><iconify-icon inline="" icon="solar:book-bold"></iconify-icon> <a href="https://teaching.kse.org.ua/course/view.php?id=4049">Course materials</a></p>
<p><iconify-icon inline="" icon="mdi:envelope"></iconify-icon> imiroshnychenko@kse.org.ua</p>
<p><iconify-icon inline="" icon="ic:baseline-telegram"></iconify-icon> <a href="https://t.me/araprof"><span class="citation" data-cites="araprof">@araprof</span></a></p>
<p><iconify-icon inline="" icon="mdi:youtube"></iconify-icon> <a href="https://www.youtube.com/@datamirosh"><span class="citation" data-cites="datamirosh">@datamirosh</span></a></p>
<p><iconify-icon inline="" icon="mdi:linkedin"></iconify-icon> <a href="https://www.linkedin.com/in/ihormiroshnychenko/">@ihormiroshnychenko</a></p>
<p><iconify-icon inline="" icon="mdi:github"></iconify-icon> <a href="https://github.com/Aranaur">@aranaur</a></p>
<p><iconify-icon inline="" icon="ion:home"></iconify-icon> <a href="https://aranaur.rbind.io">aranaur.rbind.io</a></p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="img/kse.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://teaching.kse.org.ua/course/view.php?id=4049">🔗Applied Statistics</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src=".07-mu_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src=".07-mu_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src=".07-mu_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src=".07-mu_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src=".07-mu_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src=".07-mu_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src=".07-mu_files/libs/revealjs/plugin/verticator/verticator.js"></script>
  <script src=".07-mu_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src=".07-mu_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src=".07-mu_files/libs/revealjs/plugin/search/search.js"></script>
  <script src=".07-mu_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src=".07-mu_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'verticator': {"themetag":"h1","color":"","inversecolor":"","skipuncounted":false,"clickable":true,"position":"auto","offset":"3vmin","autogenerate":true,"tooltip":false,"scale":1},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'h.v',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'default',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: true,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: true,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1350,

        height: 759.375,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, Verticator, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>