<!DOCTYPE html>
<html lang="en"><head>
<script src=".09-var-reduce_files/libs/clipboard/clipboard.min.js"></script>
<script src=".09-var-reduce_files/libs/quarto-html/tabby.min.js"></script>
<script src=".09-var-reduce_files/libs/quarto-html/popper.min.js"></script>
<script src=".09-var-reduce_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href=".09-var-reduce_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href=".09-var-reduce_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href=".09-var-reduce_files/libs/quarto-html/quarto-syntax-highlighting-acf12a64177840b8d86f2d4f01b2e9fb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src=".09-var-reduce_files/libs/quarto-contrib/iconify-1.0.7/iconify-icon.min.js"></script><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Ihor Miroshnychenko">
  <title>Sharper experiments: variance reduction &amp; ratio metrics</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href=".09-var-reduce_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href=".09-var-reduce_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href=".09-var-reduce_files/libs/revealjs/dist/theme/quarto-8a52321a21477e1bb40c2cb18c896737.css">
  <link href=".09-var-reduce_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href=".09-var-reduce_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href=".09-var-reduce_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href=".09-var-reduce_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href=".09-var-reduce_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href=".09-var-reduce_files/libs/revealjs/plugin/verticator/verticator.css" rel="stylesheet">
  <link href=".09-var-reduce_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-iframe=".09-var-reduce_files/libs/colored-particles/index.html" class="quarto-title-block center">
  <h1 class="title">Sharper experiments: variance reduction &amp; ratio metrics</h1>
  <p class="subtitle">Applied Statistics</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Ihor Miroshnychenko 
</div>
        <p class="quarto-title-affiliation">
            Kyiv School of Economics
          </p>
    </div>
</div>

</section><section id="TOC">
<nav role="doc-toc"> 
<h2 id="toc-title">Table of contents</h2>
<ul>
<li><a href="#/the-last-wall" id="/toc-the-last-wall">The last wall</a></li>
<li><a href="#/stratification" id="/toc-stratification">Stratification</a></li>
<li><a href="#/cuped" id="/toc-cuped">CUPED</a></li>
<li><a href="#/ratio-metrics-the-unit-of-analysis-trap" id="/toc-ratio-metrics-the-unit-of-analysis-trap">Ratio metrics: the unit-of-analysis trap</a></li>
<li><a href="#/linearization" id="/toc-linearization">Linearization</a></li>
<li><a href="#/head-to-head-the-bench" id="/toc-head-to-head-the-bench">Head-to-head: the bench</a></li>
<li><a href="#/the-course-in-one-map" id="/toc-the-course-in-one-map">The course in one map</a></li>
</ul>
</nav>
</section>
<section>
<section id="the-last-wall" class="title-slide slide level1 center" data-background-iframe=".09-var-reduce_files/libs/colored-particles/index.html">
<h1>The last wall</h1>

</section>
<section id="the-task" class="slide level2 smaller">
<h2>🛒 The task</h2>
<blockquote>
<p>You are an analyst at an <strong>online grocery store</strong> with delivery. Marketing wants to raise the <strong>average revenue per user</strong> and proposes an <strong>email campaign</strong>: a personalised promo bundle for active customers. Before sending anything to everyone, the team runs an <strong>A/B test</strong> — and you own the design.</p>
</blockquote>
<div class="fragment">
<p>The design pipeline — the one this course has been building since lecture 1:</p>
<ol type="1">
<li><strong>Target metric</strong>: ARPU — average revenue per user over the experiment window.</li>
<li><strong>Hypotheses</strong>: <span class="math inline">\(H_0\!: \mu_T = \mu_C\)</span> vs <span class="math inline">\(H_1\!: \mu_T \neq \mu_C\)</span> (two-sided, as always).</li>
<li><strong>Minimum detectable effect</strong>: historical ARPU is <span class="math inline">\(\approx 250\)</span> UAH with <span class="math inline">\(\sigma \approx 80\)</span> UAH; the campaign pays for itself from <span class="math inline">\(\Delta = 10\)</span> UAH.</li>
<li><strong>Error budget</strong>: <span class="math inline">\(\alpha = 0.05\)</span>, power <span class="math inline">\(1-\beta = 0.8\)</span>.</li>
<li><strong>Sample size</strong> → <strong>assignment</strong> → <strong>experiment</strong> → <strong>t-test</strong>.</li>
</ol>
<aside class="notes">
<p>Фінальна лекція курсу. Наскрізний кейс: онлайн-магазин продуктів із доставкою. Маркетинг хоче підняти середню виручку на користувача (ARPU) і пропонує email-кампанію з персональним промо-набором. Перед повною розсилкою — A/B-тест, і ми відповідаємо за дизайн. Проговоріть пайплайн, який курс збирав від першої лекції: метрика ARPU, двостороння гіпотеза (наголосіть: саме двостороння — торік у матеріалах був різнобій між «більше» в тексті та ≠ у формулі, тут все консистентно), MDE = 10 грн (з юніт-економіки кампанії: дешевші ефекти не окупаються), α = 0.05, потужність 0.8, історичні σ ≈ 80 і середнє ≈ 250. Це «рутинна» частина — вона займе три слайди. А далі почнеться справжня тема лекції: що робити, коли цього пайплайна НЕ ВИСТАЧАЄ.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="sample-size" class="slide level2 smaller">
<h2>🧮 Sample size</h2>
<p>For a two-sample t-test with equal arms:</p>
<p><span class="math display">\[
n \;=\; \frac{\left(z_{1-\alpha/2} + z_{1-\beta}\right)^2 \cdot 2\sigma^2}{\Delta^2}
\qquad\text{per arm.}
\]</span></p>
<div id="design-params" class="cell columns column-output-location" data-execution_count="2">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="" aria-hidden="true" tabindex="-1"></a>alpha, beta   <span class="op">=</span> <span class="fl">0.05</span>, <span class="fl">0.20</span></span>
<span id="cb1-2"><a href="" aria-hidden="true" tabindex="-1"></a>mu, sigma     <span class="op">=</span> <span class="fl">250.0</span>, <span class="fl">80.0</span>     <span class="co"># historical ARPU</span></span>
<span id="cb1-3"><a href="" aria-hidden="true" tabindex="-1"></a>mde           <span class="op">=</span> <span class="fl">10.0</span>            <span class="co"># breakeven effect, UAH</span></span>
<span id="cb1-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="" aria-hidden="true" tabindex="-1"></a>z_a <span class="op">=</span> norm.ppf(<span class="dv">1</span> <span class="op">-</span> alpha<span class="op">/</span><span class="dv">2</span>)</span>
<span id="cb1-6"><a href="" aria-hidden="true" tabindex="-1"></a>z_b <span class="op">=</span> norm.ppf(<span class="dv">1</span> <span class="op">-</span> beta)</span>
<span id="cb1-7"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> n_per_arm(sd, delta):</span>
<span id="cb1-9"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">int</span>(np.ceil((z_a <span class="op">+</span> z_b)<span class="op">**</span><span class="dv">2</span> <span class="op">*</span> <span class="dv">2</span><span class="op">*</span>sd<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> delta<span class="op">**</span><span class="dv">2</span>))</span>
<span id="cb1-10"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> n_per_arm(sigma, mde)</span>
<span id="cb1-12"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"users per arm: </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>users per arm: 1005</code></pre>
</div>
</div></div>
<div class="fragment">
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(n \propto \sigma^2 / \Delta^2\)</span>. Remember this shape — the whole lecture lives inside it.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Формула розміру груп для двовибіркового t-тесту з рівними плечима — та сама, що в лекціях про t-тест. Підставляємо: σ = 80, Δ = 10, α = 0.05, β = 0.2 → 1005 користувачів на групу. Функцію n_per_arm ми ще використаємо не раз. Головне на слайді — НЕ число 1005, а форма залежності: n пропорційне σ²/Δ². Квадрати означають: щоб ловити вдвічі менший ефект, треба вчетверо більше людей; щоб компенсувати вдвічі більший шум — теж вчетверо. Уся лекція житиме всередині цієї формули: ми не можемо чіпати Δ (його диктує бізнес), тому будемо тиснути на σ.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="does-the-plan-keep-its-promises" class="slide level2 smaller">
<h2>🎰 Does the plan keep its promises?</h2>
<p>Habit from the Monte Carlo lecture: <strong>simulate the design before running it</strong>.</p>
<div id="mc-baseline" class="cell columns column-output-location" data-execution_count="3">
<div class="column">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> wilson(k, n_trials):</span>
<span id="cb3-2"><a href="" aria-hidden="true" tabindex="-1"></a>    lo, hi <span class="op">=</span> proportion_confint(k, n_trials, method<span class="op">=</span><span class="st">"wilson"</span>)</span>
<span id="cb3-3"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="ss">f"</span><span class="sc">{</span>k<span class="op">/</span>n_trials<span class="sc">:.3f}</span><span class="ss">  [</span><span class="sc">{</span>lo<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>hi<span class="sc">:.3f}</span><span class="ss">]"</span></span>
<span id="cb3-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">42</span>)</span>
<span id="cb3-6"><a href="" aria-hidden="true" tabindex="-1"></a>MC  <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb3-7"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="" aria-hidden="true" tabindex="-1"></a>ctrl_1 <span class="op">=</span> rng.normal(mu, sigma, (MC, n))</span>
<span id="cb3-9"><a href="" aria-hidden="true" tabindex="-1"></a>ctrl_2 <span class="op">=</span> rng.normal(mu, sigma, (MC, n))</span>
<span id="cb3-10"><a href="" aria-hidden="true" tabindex="-1"></a>test   <span class="op">=</span> rng.normal(mu <span class="op">+</span> mde, sigma, (MC, n))</span>
<span id="cb3-11"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="" aria-hidden="true" tabindex="-1"></a>p_aa <span class="op">=</span> ttest_ind(ctrl_1, ctrl_2, axis<span class="op">=</span><span class="dv">1</span>, equal_var<span class="op">=</span><span class="va">False</span>).pvalue</span>
<span id="cb3-13"><a href="" aria-hidden="true" tabindex="-1"></a>p_ab <span class="op">=</span> ttest_ind(ctrl_1, test,   axis<span class="op">=</span><span class="dv">1</span>, equal_var<span class="op">=</span><span class="va">False</span>).pvalue</span>
<span id="cb3-14"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"A/A FPR  :"</span>, wilson((p_aa <span class="op">&lt;</span> alpha).<span class="bu">sum</span>(), MC))</span>
<span id="cb3-16"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"A/B power:"</span>, wilson((p_ab <span class="op">&lt;</span> alpha).<span class="bu">sum</span>(), MC))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>A/A FPR  : 0.044  [0.033, 0.059]
A/B power: 0.798  [0.772, 0.822]</code></pre>
</div>
</div></div>
<div class="fragment">
<p>FPR sits on <span class="math inline">\(\alpha\)</span>, power sits on <span class="math inline">\(0.8\)</span> — the design is honest. <code>wilson()</code> will chaperone every simulated rate today, as usual.</p>
<aside class="notes">
<p>Звичка з лекції про Монте-Карло: перш ніж запускати експеримент — симулюємо його. Векторизовано: матриці MC×n, ttest_ind по axis=1, жодних циклів — 1000 симульованих експериментів за частки секунди. A/A-тест дає FPR ≈ 0.05, A/B з ефектом 10 грн — потужність ≈ 0.8. Дизайн чесний. І зверніть увагу на wilson(): частка відхилень сама є оцінкою з шумом, тому до кожного симульованого FPR і power ми, як завжди в цьому курсі, чіпляємо інтервал Уілсона. Ця функція супроводжуватиме нас усю лекцію. Поки що все йде за підручником — інтрига на наступному слайді.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-wall" class="slide level2 smaller">
<h2>🧱 The wall</h2>
<p>You bring the plan to the PM. The answer:</p>
<blockquote>
<p>“1005 users per arm is fine. But finance says the campaign is worth shipping even at <strong>+5 UAH</strong>. And we can’t hold the promo budget for longer — <strong>no extra users</strong>.”</p>
</blockquote>
<div id="wall-math" class="cell columns column-output-location" data-execution_count="4">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> delta <span class="kw">in</span> (<span class="dv">10</span>, <span class="dv">5</span>):</span>
<span id="cb5-2"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"MDE = </span><span class="sc">{</span>delta<span class="sc">:&gt;2}</span><span class="ss"> UAH -&gt; "</span></span>
<span id="cb5-3"><a href="" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>n_per_arm(sigma, delta)<span class="sc">}</span><span class="ss"> users per arm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>MDE = 10 UAH -&gt; 1005 users per arm
MDE =  5 UAH -&gt; 4019 users per arm</code></pre>
</div>
</div></div>
<div class="fragment">
<p>Halve the effect → <strong>quadruple</strong> the sample. That’s the wall: <span class="math inline">\(n \propto \sigma^2/\Delta^2\)</span>, and</p>
<ul>
<li><span class="math inline">\(\Delta\)</span> is set by <strong>economics</strong> — not yours to touch;</li>
<li><span class="math inline">\(n\)</span> is set by <strong>traffic and time</strong> — the PM just froze it;</li>
<li><span class="math inline">\(\sigma\)</span> … is set by <strong>how you analyse the data</strong>. <span class="hi">The only free lever.</span></li>
</ul>
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Today’s promise: keep the same users, the same weeks, the same honest <span class="math inline">\(\alpha\)</span> — and detect smaller effects, by making <span class="math inline">\(\sigma\)</span> <em>effectively</em> smaller. <strong>Variance reduction = power for free.</strong></p>
</div>
</div>
</div>
<aside class="notes">
<p>Стіна, з якої починається лекція. PM повертається: фінансисти кажуть, що кампанія окупна вже від +5 грн, а бюджету тримати промо довше немає — більше користувачів не буде. Рахуємо: для MDE = 5 треба ≈4020 на групу — вчетверо більше. Розкладаємо формулу на три важелі. Δ диктує економіка — ми його не обираємо. n диктують трафік і час — PM щойно їх заморозив. Лишається σ. І ось ключова думка лекції: σ у формулі — це НЕ «природна мінливість користувачів», це дисперсія ТІЄЇ ВЕЛИЧИНИ, ЯКУ МИ ЗАНОСИМО В ТЕСТ. Її можна зменшити, не чіпаючи ані даних, ані чесності критерію — просто розумніше аналізуючи. Це і є variance reduction: потужність задарма. План лекції — три способи: використати те, що ми ЗНАЄМО про користувачів (стратифікація), те, що вони РОБИЛИ раніше (CUPED), і правильно обрати САМУ метрику (ratio-метрики та лінеаризація). Наприкінці — очний турнір усіх методів і підсумкова карта курсу.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="roadmap" class="slide level2 smaller">
<h2>🗺️ Roadmap</h2>
<table class="caption-top">
<colgroup>
<col style="width: 11%">
<col style="width: 25%">
<col style="width: 29%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Lever</th>
<th>Method</th>
<th>Section</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>what we <strong>know</strong> about users</td>
<td>stratification</td>
<td>next</td>
</tr>
<tr class="even">
<td>2</td>
<td>what users <strong>did before</strong></td>
<td>CUPED</td>
<td>after that</td>
</tr>
<tr class="odd">
<td>3</td>
<td>what we <strong>measure</strong> at all</td>
<td>ratio metrics &amp; linearization</td>
<td>then</td>
</tr>
<tr class="even">
<td>4</td>
<td>all of it at once</td>
<td>head-to-head bench</td>
<td>—</td>
</tr>
<tr class="odd">
<td>5</td>
<td>the whole course</td>
<td>one map</td>
<td>finale</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Дорожня карта фінальної лекції. Три важелі зниження дисперсії: (1) стратифікація — використовуємо відому структуру аудиторії; (2) CUPED — використовуємо передекспериментальну історію; (3) ratio-метрики та лінеаризація — правильно обираємо одиницю аналізу й саму метрику (тут же чатується найпідступніша пастка лекції). Потім очний турнір методів на одному світі й фінальна карта всього курсу. Поїхали.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="stratification" class="title-slide slide level1 center" data-background-iframe=".09-var-reduce_files/libs/colored-particles/index.html">
<h1>Stratification</h1>

</section>
<section id="the-store-has-structure" class="slide level2 smaller">
<h2>🏷️ The store has structure</h2>
<p>The store runs a <strong>loyalty program</strong>. From historical data:</p>
<ul>
<li><strong>registered</strong> users: mean ARPU <span class="math inline">\(\approx 300\)</span> UAH, sd <span class="math inline">\(\approx 62\)</span>;</li>
<li><strong>unregistered</strong>: mean ARPU <span class="math inline">\(\approx 200\)</span> UAH, sd <span class="math inline">\(\approx 62\)</span>;</li>
<li>shares in the population: <span class="math inline">\(50\%/50\%\)</span>.</li>
</ul>
<div id="cell-strata-plot" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="" aria-hidden="true" tabindex="-1"></a>mu_u, mu_r, sd_w, w_r <span class="op">=</span> <span class="fl">200.0</span>, <span class="fl">300.0</span>, <span class="fl">62.0</span>, <span class="fl">0.5</span></span>
<span id="cb7-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.linspace(<span class="dv">0</span>, <span class="dv">500</span>, <span class="dv">500</span>)</span>
<span id="cb7-4"><a href="" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">12.5</span>, <span class="fl">3.8</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb7-5"><a href="" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(x, norm.pdf(x, mu_u, sd_w), color<span class="op">=</span>red_pink,  lw<span class="op">=</span><span class="fl">2.5</span>, label<span class="op">=</span><span class="st">"unregistered"</span>)</span>
<span id="cb7-6"><a href="" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(x, norm.pdf(x, mu_r, sd_w), color<span class="op">=</span>turquoise, lw<span class="op">=</span><span class="fl">2.5</span>, label<span class="op">=</span><span class="st">"registered"</span>)</span>
<span id="cb7-7"><a href="" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"What we know: two strata, sd = 62 each"</span>)</span>
<span id="cb7-8"><a href="" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend()</span>
<span id="cb7-9"><a href="" aria-hidden="true" tabindex="-1"></a>mix <span class="op">=</span> w_r<span class="op">*</span>norm.pdf(x, mu_r, sd_w) <span class="op">+</span> (<span class="dv">1</span><span class="op">-</span>w_r)<span class="op">*</span>norm.pdf(x, mu_u, sd_w)</span>
<span id="cb7-10"><a href="" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(x, mix, color<span class="op">=</span>blue, lw<span class="op">=</span><span class="fl">2.5</span>)</span>
<span id="cb7-11"><a href="" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"What the t-test sees: one blob, sd ≈ 80"</span>)</span>
<span id="cb7-12"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax <span class="kw">in</span> axes:</span>
<span id="cb7-13"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"ARPU, UAH"</span>)</span>
<span id="cb7-14"><a href="" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"density"</span>)</span>
<span id="cb7-15"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb7-16"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".09-var-reduce_files/figure-revealjs/strata-plot-output-1.svg" id="strata-plot" class="quarto-figure quarto-figure-center r-stretch"><p>The “<span class="math inline">\(\sigma \approx 80\)</span>” from our design is not one population — it is <strong>two well-separated groups glued together</strong>.</p>
<aside class="notes">
<p>Перший важіль — структура, яку ми і так знаємо. У магазину є програма лояльності: зареєстровані користувачі витрачають у середньому 300 грн, незареєстровані — 200, у кожної підгрупи власне sd = 62, частки 50/50. Лівий графік — те, що знаємо ми: дві добре розділені страти. Правий — те, що «бачить» звичайний t-тест: один розмазаний горб зі стандартним відхиленням близько 80. Ось звідки взялося σ = 80 у нашому дизайні: це не «природна мінливість покупця», це ДВІ групи, склеєні докупи. Реєстрація в лояльності — ковариата: вона корелює з метрикою і НЕ залежить від трітменту. Зараз ми цю інформацію перетворимо на потужність.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="variance-decomposition" class="slide level2 smaller">
<h2>🧩 Variance decomposition</h2>
<p>For a mixture of strata with weights <span class="math inline">\(w_s\)</span>, means <span class="math inline">\(\mu_s\)</span> and variances <span class="math inline">\(\sigma_s^2\)</span>:</p>
<p><span class="math display">\[
\underbrace{\operatorname{Var}(Y)}_{\text{what the t-test fights}}
= \underbrace{\textstyle\sum_s w_s \sigma_s^2}_{\text{within strata}}
\;+\; \underbrace{\textstyle\sum_s w_s (\mu_s - \bar\mu)^2}_{\text{between strata}}
\]</span></p>
<div id="variance-decomp" class="cell columns column-output-location" data-execution_count="6">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="" aria-hidden="true" tabindex="-1"></a>mu_bar      <span class="op">=</span> w_r<span class="op">*</span>mu_r <span class="op">+</span> (<span class="dv">1</span> <span class="op">-</span> w_r)<span class="op">*</span>mu_u</span>
<span id="cb8-2"><a href="" aria-hidden="true" tabindex="-1"></a>var_within  <span class="op">=</span> sd_w<span class="op">**</span><span class="dv">2</span></span>
<span id="cb8-3"><a href="" aria-hidden="true" tabindex="-1"></a>var_between <span class="op">=</span> w_r<span class="op">*</span>(mu_r <span class="op">-</span> mu_bar)<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> (<span class="dv">1</span> <span class="op">-</span> w_r)<span class="op">*</span>(mu_u <span class="op">-</span> mu_bar)<span class="op">**</span><span class="dv">2</span></span>
<span id="cb8-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"within  : </span><span class="sc">{</span>var_within<span class="sc">:7.0f}</span><span class="ss">  (sd </span><span class="sc">{</span>np<span class="sc">.</span>sqrt(var_within)<span class="sc">:.1f}</span><span class="ss">)"</span>)</span>
<span id="cb8-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"between : </span><span class="sc">{</span>var_between<span class="sc">:7.0f}</span><span class="ss">  (sd </span><span class="sc">{</span>np<span class="sc">.</span>sqrt(var_between)<span class="sc">:.1f}</span><span class="ss">)"</span>)</span>
<span id="cb8-7"><a href="" aria-hidden="true" tabindex="-1"></a>total <span class="op">=</span> var_within <span class="op">+</span> var_between</span>
<span id="cb8-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"total   : </span><span class="sc">{</span>total<span class="sc">:7.0f}</span><span class="ss">  (sd </span><span class="sc">{</span>np<span class="sc">.</span>sqrt(total)<span class="sc">:.1f}</span><span class="ss">)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>within  :    3844  (sd 62.0)
between :    2500  (sd 50.0)
total   :    6344  (sd 79.6)</code></pre>
</div>
</div></div>
<div class="fragment">
<p><strong>40% of the design variance</strong> (<span class="math inline">\(2500/6344\)</span>) is <em>between</em> strata — and that part is <strong>not noise</strong>: we know each user’s stratum before the experiment starts. Paying sample size for it is a waste.</p>
<aside class="notes">
<p>Ключова формула секції — розклад дисперсії суміші: повна дисперсія = дисперсія всередині страт + дисперсія між стратами. Числа: всередині 62² = 3844, між — 0.5·50² + 0.5·50² = 2500, разом 6344, тобто sd ≈ 79.6 ≈ наші 80. Сорок відсотків дисперсії, з якою бореться наш t-тест, — це різниця МІЖ стратами. І ця частина — не шум! Ми знаємо статус лояльності кожного користувача ЩЕ ДО експерименту. Платити за неї розміром вибірки — марнотратство. Стратифікація — це спосіб «відрізати» доданок between і лишити тесту тільки справжній шум within.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="where-the-extra-noise-bites" class="slide level2 smaller">
<h2>🎲 Where the extra noise bites</h2>
<p>Randomize <span class="math inline">\(1005\)</span> users into an arm → the <strong>share of registered users in the arm is itself random</strong>:</p>
<div id="mix-noise" class="cell columns column-output-location" data-execution_count="7">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">1</span>)</span>
<span id="cb10-2"><a href="" aria-hidden="true" tabindex="-1"></a>shares <span class="op">=</span> rng.binomial(n, <span class="fl">0.5</span>, <span class="dv">100_000</span>) <span class="op">/</span> n</span>
<span id="cb10-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="" aria-hidden="true" tabindex="-1"></a>sd_mix    <span class="op">=</span> shares.std() <span class="op">*</span> (mu_r <span class="op">-</span> mu_u)</span>
<span id="cb10-5"><a href="" aria-hidden="true" tabindex="-1"></a>sd_sample <span class="op">=</span> sd_w <span class="op">/</span> np.sqrt(n)</span>
<span id="cb10-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"sd of registered share : </span><span class="sc">{</span>shares<span class="sc">.</span>std()<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb10-8"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"arm-mean noise from mix: </span><span class="sc">{</span>sd_mix<span class="sc">:.2f}</span><span class="ss"> UAH"</span>)</span>
<span id="cb10-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"arm-mean noise within  : </span><span class="sc">{</span>sd_sample<span class="sc">:.2f}</span><span class="ss"> UAH"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>sd of registered share : 0.0158
arm-mean noise from mix: 1.58 UAH
arm-mean noise within  : 1.96 UAH</code></pre>
</div>
</div></div>
<div class="fragment">
<p>In an A/A test the arm means differ <strong>not only</strong> because users are random, but because one arm got a <em>slightly richer loyalty mix</em>. That mix-luck contributes almost as much noise as genuine sampling — and we can remove it <strong>exactly</strong>, because the mix is observable.</p>
<aside class="notes">
<p>Де саме ця «зайва» дисперсія кусає? При рандомізації 1005 людей у групу частка зареєстрованих У ГРУПІ — сама випадкова величина: біноміальний розкид ≈ 1.6 п.п. Кожен відсоток перекосу зсуває середнє групи на 1 грн (бо різниця страт — 100 грн). Разом: шум середнього групи від «пощастило з міксом» ≈ 1.6 грн, а класичний вибірковий шум усередині страт ≈ 2.0 грн. Тобто ледь не ПОЛОВИНА хиткості групового середнього в A/A — це просто лотерея складу групи. І цю лотерею можна прибрати точно, бо склад групи спостережуваний: ми знаємо, хто зареєстрований. Два способи: балансувати склад на етапі призначення (стратифікована рандомізація) або виправити зважуванням на етапі аналізу (пост-стратифікація). Математика оцінки одна й та сама — наступний слайд.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="stratified-mean-and-its-variance" class="slide level2 smaller">
<h2>⚖️ Stratified mean and its variance</h2>
<p>Estimate the arm mean as a <strong>weighted sum of stratum means</strong>, weights = <em>population</em> shares <span class="math inline">\(w_s\)</span>:</p>
<p><span class="math display">\[
\hat{Y}_{str} = \sum_{s} w_s \, \bar{Y}_s ,
\qquad
\operatorname{Var}\!\big(\hat{Y}_{str}\big) = \sum_{s} w_s^2 \, \frac{\sigma_s^2}{n_s}
\;\overset{n_s = w_s n}{=}\;
\frac{1}{n} \sum_{s} w_s \sigma_s^2 .
\]</span></p>
<p>Compare the two estimators of the same arm mean:</p>
<p><span class="math display">\[
\operatorname{Var}(\bar Y) \approx \frac{6344}{n}
\qquad\text{vs}\qquad
\operatorname{Var}(\hat Y_{str}) \approx \frac{3844}{n} .
\]</span></p>
<div class="fragment">
<p>The between-strata term is <strong>gone</strong>: the weights are fixed constants, so the loyalty-mix lottery no longer shakes the estimate. The t-statistic just swaps in the new mean and variance:</p>
<p><span class="math display">\[
t = \frac{\hat{Y}_{str,T} - \hat{Y}_{str,C}}{\sqrt{\widehat{\operatorname{Var}}(\hat Y_{str,T}) + \widehat{\operatorname{Var}}(\hat Y_{str,C})}}
\]</span></p>
<aside class="notes">
<p>Оцінювач: стратифіковане середнє — зважена сума середніх по стратах, ваги = частки страт у ПОПУЛЯЦІЇ (константи, не частки у вибірці!). Його дисперсія: Σ w² σ²/n_s; за пропорційної алокації n_s = w·n це (1/n)·Σ w σ² — тобто в чисельнику лишилась ЛИШЕ внутрішньостратова дисперсія 3844 замість повної 6344. Доданок between зник не магією: ваги — фіксовані числа, тому лотерея складу групи більше не хитає оцінку. Порівняйте з торішнім записом формули: там было Var_str = (1/N)Σw σ² без пояснення, звідки взялося, — тут ми чесно пройшли через Σ w² σ²/n_s. Стратифікований t-тест — та сама t-статистика, лише з новими середнім і дисперсією; ступені свободи беремо як n_T + n_C − 2, на таких розмірах це не принципово.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="strat_ttest" class="slide level2 smaller">
<h2>🐍 <code>strat_ttest</code></h2>
<div id="strat-fn" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> draw_arm_strat(size, rng, effect<span class="op">=</span><span class="fl">0.0</span>):</span>
<span id="cb12-2"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""One arm of the grocery experiment: loyalty stratum + ARPU."""</span></span>
<span id="cb12-3"><a href="" aria-hidden="true" tabindex="-1"></a>    reg <span class="op">=</span> rng.random(size) <span class="op">&lt;</span> w_r                     <span class="co"># True = registered</span></span>
<span id="cb12-4"><a href="" aria-hidden="true" tabindex="-1"></a>    y   <span class="op">=</span> np.where(reg, mu_r, mu_u) <span class="op">+</span> sd_w<span class="op">*</span>rng.standard_normal(size) <span class="op">+</span> effect</span>
<span id="cb12-5"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> reg, y</span>
<span id="cb12-6"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> strat_ttest(reg_c, y_c, reg_t, y_t, w<span class="op">=</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>)):</span>
<span id="cb12-8"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Two-sample t-test on stratified means; w = population shares."""</span></span>
<span id="cb12-9"><a href="" aria-hidden="true" tabindex="-1"></a>    m, v <span class="op">=</span> [], []</span>
<span id="cb12-10"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> reg, y <span class="kw">in</span> ((reg_c, y_c), (reg_t, y_t)):</span>
<span id="cb12-11"><a href="" aria-hidden="true" tabindex="-1"></a>        groups <span class="op">=</span> [y[<span class="op">~</span>reg], y[reg]]</span>
<span id="cb12-12"><a href="" aria-hidden="true" tabindex="-1"></a>        m.append(<span class="bu">sum</span>(wi <span class="op">*</span> g.mean() <span class="cf">for</span> wi, g <span class="kw">in</span> <span class="bu">zip</span>(w, groups)))</span>
<span id="cb12-13"><a href="" aria-hidden="true" tabindex="-1"></a>        v.append(<span class="bu">sum</span>(wi<span class="op">**</span><span class="dv">2</span> <span class="op">*</span> g.var(ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> g.size <span class="cf">for</span> wi, g <span class="kw">in</span> <span class="bu">zip</span>(w, groups)))</span>
<span id="cb12-14"><a href="" aria-hidden="true" tabindex="-1"></a>    t_stat <span class="op">=</span> (m[<span class="dv">1</span>] <span class="op">-</span> m[<span class="dv">0</span>]) <span class="op">/</span> np.sqrt(v[<span class="dv">0</span>] <span class="op">+</span> v[<span class="dv">1</span>])</span>
<span id="cb12-15"><a href="" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> y_c.size <span class="op">+</span> y_t.size <span class="op">-</span> <span class="dv">2</span></span>
<span id="cb12-16"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">2</span> <span class="op">*</span> stats.t.sf(<span class="bu">abs</span>(t_stat), df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Population shares <span class="math inline">\(w\)</span> come <strong>from outside the experiment</strong> (the user base), not from the arm itself.</p>
<aside class="notes">
<p>Реалізація — дюжина рядків. draw_arm_strat генерує одну групу нашого світу: статус лояльності Бернуллі(0.5) і ARPU з відповідної страти (+effect для тестової групи). strat_ttest рахує для кожної групи стратифіковане середнє й дисперсію за формулами з попереднього слайда і повертає двосторонній p-value. Тонкість, на яку варто вказати студентам: ваги w — це частки страт у ПОПУЛЯЦІЇ (їх знаємо з бази користувачів), а не в конкретній групі. Саме через це фіксування і зникає «лотерея складу». Перевіряємо чесність — наступний слайд, як завжди, Монте-Карло.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="monte-carlo-plain-vs-stratified" class="slide level2 smaller">
<h2>🔬 Monte Carlo: plain vs stratified</h2>
<div id="mc-strat" class="cell columns column-output-location" data-execution_count="9">
<div class="column">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">11</span>)</span>
<span id="cb13-2"><a href="" aria-hidden="true" tabindex="-1"></a>MC  <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb13-3"><a href="" aria-hidden="true" tabindex="-1"></a>cnt <span class="op">=</span> <span class="bu">dict</span>.fromkeys(</span>
<span id="cb13-4"><a href="" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"plain FPR"</span>, <span class="st">"plain power"</span>, <span class="st">"strat FPR"</span>, <span class="st">"strat power"</span>], <span class="dv">0</span>)</span>
<span id="cb13-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(MC):</span>
<span id="cb13-7"><a href="" aria-hidden="true" tabindex="-1"></a>    reg_a, y_a <span class="op">=</span> draw_arm_strat(n, rng)</span>
<span id="cb13-8"><a href="" aria-hidden="true" tabindex="-1"></a>    reg_b, y_b <span class="op">=</span> draw_arm_strat(n, rng)</span>
<span id="cb13-9"><a href="" aria-hidden="true" tabindex="-1"></a>    reg_t, y_t <span class="op">=</span> draw_arm_strat(n, rng, effect<span class="op">=</span>mde)</span>
<span id="cb13-10"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="" aria-hidden="true" tabindex="-1"></a>    cnt[<span class="st">"plain FPR"</span>]   <span class="op">+=</span> ttest_ind(y_a, y_b, equal_var<span class="op">=</span><span class="va">False</span>).pvalue <span class="op">&lt;</span> alpha</span>
<span id="cb13-12"><a href="" aria-hidden="true" tabindex="-1"></a>    cnt[<span class="st">"plain power"</span>] <span class="op">+=</span> ttest_ind(y_a, y_t, equal_var<span class="op">=</span><span class="va">False</span>).pvalue <span class="op">&lt;</span> alpha</span>
<span id="cb13-13"><a href="" aria-hidden="true" tabindex="-1"></a>    cnt[<span class="st">"strat FPR"</span>]   <span class="op">+=</span> strat_ttest(reg_a, y_a, reg_b, y_b) <span class="op">&lt;</span> alpha</span>
<span id="cb13-14"><a href="" aria-hidden="true" tabindex="-1"></a>    cnt[<span class="st">"strat power"</span>] <span class="op">+=</span> strat_ttest(reg_a, y_a, reg_t, y_t) <span class="op">&lt;</span> alpha</span>
<span id="cb13-15"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> cnt.items():</span>
<span id="cb13-17"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>k<span class="sc">:12s}</span><span class="ss">: </span><span class="sc">{</span>wilson(v, MC)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>plain FPR   : 0.050  [0.038, 0.065]
plain power : 0.814  [0.789, 0.837]
strat FPR   : 0.054  [0.042, 0.070]
strat power : 0.950  [0.935, 0.962]</code></pre>
</div>
</div></div>
<div class="fragment">
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Same users, same effect, same <span class="math inline">\(\alpha\)</span> — and power jumps from <span class="math inline">\(\approx 0.80\)</span> to <span class="math inline">\(\approx 0.95\)</span>. Effective sd dropped from <span class="math inline">\(79.6\)</span> to <span class="math inline">\(62\)</span>; the design that needed <span class="math inline">\(1005\)</span> users now needs 604.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Стенд: 1000 світів, у кожному — A/A і A/B для обох критеріїв на ТИХ САМИХ даних. Результат: FPR обох тестів на рівні α (інтервали Уілсона накривають 0.05) — обидва чесні. А потужність: звичайний t-тест ≈ 0.80 (як і проєктували), стратифікований ≈ 0.95. Ті самі користувачі, той самий ефект 10 грн, той самий рівень значущості — п’ятнадцять пунктів потужності задарма. Мовою розміру вибірки: ефективне sd впало з 79.6 до 62, і дизайн, якому було потрібно 1005 користувачів, тепер обходиться 604-ма. Це і є «потужність задарма» з обіцянки лекції — ми просто перестали платити за дисперсію, яку самі ж могли пояснити.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="post-stratification-fine-print" class="slide level2 smaller">
<h2>📎 Post-stratification &amp; fine print</h2>
<ul>
<li><strong>Didn’t control the assignment?</strong> Apply the <em>same</em> weighted estimator to a plain random split — <span class="hi">post-stratification</span>. Asymptotically it captures nearly the same gain.</li>
<li><strong>More strata</strong>: city × platform × loyalty… works the same way; each stratum needs a decent <span class="math inline">\(n_s\)</span> for <span class="math inline">\(\bar Y_s\)</span> and <span class="math inline">\(s_s^2\)</span> to be stable.</li>
<li><strong>The stratum must be pre-treatment</strong>: defined <em>before</em> the experiment and unaffected by it. Stratifying on something the treatment can move destroys the test.</li>
<li><strong>The gain is capped</strong> by how much of the variance is <em>between</em> strata — here <span class="math inline">\(40\%\)</span>; a useless covariate buys you nothing.</li>
</ul>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>A nuance we inherit honestly: the stratified test answers the question about the <strong>population-weighted</strong> mean. That is <em>exactly</em> the ARPU the business cares about — but it is a different estimand than “mean of whoever landed in my sample”.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Дрібний шрифт секції. (1) Якщо рандомізацію вже провели простим жеребом — не біда: той самий зважений оцінювач, застосований постфактум, називається пост-стратифікацією і асимптотично дає майже той самий виграш. (2) Страт може бути багато (місто × платформа × лояльність), аби в кожній лишалося достатньо спостережень для стабільних оцінок середнього й дисперсії. (3) Критично: страта має бути ПЕРЕДтрітментною характеристикою — визначеною до експерименту і незалежною від нього. Стратифікувати за тим, що трітмент може змінити, — зруйнувати тест. (4) Виграш обмежений часткою between-дисперсії: у нас 40%, а від марної коваріати виграшу нуль. І нюанс, який торік був сформульований як «ми отримали не зовсім той тест»: стратифікований критерій відповідає на питання про ПОПУЛЯЦІЙНО зважене середнє. Для бізнесу це якраз і є ARPU, тож для нас це фіча, а не баг, — але формально це інший естиманд, ніж «середнє тих, хто випадково потрапив у вибірку».</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="cuped" class="title-slide slide level1 center" data-background-iframe=".09-var-reduce_files/libs/colored-particles/index.html">
<h1>CUPED</h1>

</section>
<section id="week-5-who-won" class="slide level2 smaller">
<h2>👀 Week 5: who won?</h2>
<p>Stratification used a <strong>coarse</strong> label. But we have something far richer: every user’s <strong>own history</strong>. Ten users, revenue in the experiment week:</p>

<img data-src=".09-var-reduce_files/figure-revealjs/cuped-toy1-output-1.svg" id="cuped-toy1" class="quarto-figure quarto-figure-center r-stretch"><p>Between-user spread (<span class="math inline">\(100\)</span>–<span class="math inline">\(195\)</span> UAH) dwarfs any treatment effect. A t-test compares <em>these</em> clouds.</p>
<aside class="notes">
<p>Другий важіль. Стратифікація використовувала грубу мітку — зареєстрований чи ні. Але в нас є значно багатше знання: ВЛАСНА історія кожного користувача. Іграшковий приклад: десять користувачів, виручка за тиждень експерименту, групи A і B чергуються. Дивимось на хмару тижня 5: розкид між користувачами — від 100 до 195 грн, і на його тлі жоден ефект трітменту не видно. Звичайний t-тест порівнює саме ЦІ дві хмари — і тоне в міжкористувацькому розкиді. Питання до аудиторії: а що, як подивитись, скільки кожен витрачав РАНІШЕ?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="and-now-with-the-past" class="slide level2 smaller">
<h2>👀 …and now with the past</h2>

<img data-src=".09-var-reduce_files/figure-revealjs/cuped-toy2-output-1.svg" id="cuped-toy2" class="quarto-figure quarto-figure-center r-stretch"><p>Against each user’s own baseline the picture is unambiguous: <strong>every</strong> B-user gained, <strong>every</strong> A-user stayed flat. <span class="hi">Compare users to their own past — the noise between users cancels out.</span></p>
<aside class="notes">
<p>Ті самі дані, але тепер із тижнями 1–4. Кожна лінія — один користувач; видно, що витрати людини стабільні в часі, а на тижні 5 КОЖЕН користувач групи B підріс (+5, +2, +1, +2, +5), і КОЖЕН користувач A лишився на місці. Проти власного бейзлайна кожного користувача картина однозначна. Ідея CUPED саме така: відняти від метрики те, що передбачувано з минулого користувача, — і міжкористувацький розкид скоротиться, лишивши ефект видимим. Залишилось формалізувати «відняти минуле» так, щоб тест лишився незміщеним і мінімізував дисперсію.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="cuped-1" class="slide level2 smaller">
<h2>📐 CUPED</h2>
<p><strong>CUPED</strong> — <strong>C</strong>ontrolled-experiment <strong>U</strong>sing <strong>P</strong>re-<strong>E</strong>xperiment <strong>D</strong>ata. Adjust the metric <span class="math inline">\(Y\)</span> with a pre-experiment covariate <span class="math inline">\(X\)</span>:</p>
<p><span class="math display">\[
Y_{cuped} = Y - \theta X
\]</span></p>
<ul>
<li><span class="math inline">\(Y\)</span> — the target metric during the experiment (ARPU);</li>
<li><span class="math inline">\(X\)</span> — a covariate measured <strong>before</strong> the experiment (e.g.&nbsp;the same user’s ARPU over the previous 4 weeks);</li>
<li><span class="math inline">\(\theta\)</span> — a constant, <strong>the same for both arms</strong>, chosen to minimize variance.</li>
</ul>
<div class="fragment">
<p>Why is the comparison still fair? Randomization makes <span class="math inline">\(\mathbb{E}X_T = \mathbb{E}X_C\)</span>, and <span class="math inline">\(\theta\)</span> is shared, so</p>
<p><span class="math display">\[
\mathbb{E}\big[\bar Y_{cuped,T} - \bar Y_{cuped,C}\big]
= \mathbb{E}\big[\bar Y_T - \bar Y_C\big] - \theta\big(\mathbb{E}\bar X_T - \mathbb{E}\bar X_C\big)
= \mathbb{E}\big[\bar Y_T - \bar Y_C\big].
\]</span></p>
<p><span class="hi">The difference of means is untouched; only its noise shrinks.</span></p>
<aside class="notes">
<p>CUPED — Controlled-experiment Using Pre-Experiment Data (Microsoft, 2013). Конструкція: від метрики Y віднімаємо θ·X, де X — коваріата, виміряна ДО експерименту (наприклад, ARPU того ж користувача за попередні 4 тижні), а θ — константа, СПІЛЬНА для обох груп. Чому порівняння лишається чесним: завдяки рандомізації очікування X у тесті й контролі однакові, а θ однакова — тож у різниці середніх доданок з X скорочується В ОЧІКУВАННІ. Ми не зсуваємо оцінку ефекту — ми лише прибираємо з неї передбачувану частину шуму. (Примітка: часто пишуть Y − θ(X − X̄), щоб зберегти й масштаб метрики; на різницю груп це не впливає.) Лишилось обрати θ — наступний слайд.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-optimal-theta" class="slide level2 smaller">
<h2>🎚️ The optimal <span class="math inline">\(\theta\)</span></h2>
<p>Choose <span class="math inline">\(\theta\)</span> to minimize the variance:</p>
<p><span class="math display">\[
\operatorname{Var}(Y_{cuped}) = \operatorname{Var}(Y) - 2\theta \operatorname{Cov}(X, Y) + \theta^2 \operatorname{Var}(X)
\]</span></p>
<p>A parabola in <span class="math inline">\(\theta\)</span> — differentiate, set to zero:</p>
<p><span class="math display">\[
\frac{d}{d\theta}\operatorname{Var}(Y_{cuped}) = 2\theta \operatorname{Var}(X) - 2\operatorname{Cov}(X, Y) = 0
\quad\Rightarrow\quad
\boxed{\;\theta = \frac{\operatorname{Cov}(X, Y)}{\operatorname{Var}(X)}\;}
\]</span></p>
<p>Substitute back:</p>
<p><span class="math display">\[
\operatorname{Var}(Y_{cuped}) = \operatorname{Var}(Y)\,\big(1 - r^2\big),
\qquad r = \operatorname{corr}(X, Y).
\]</span></p>
<div class="fragment">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The entire method in one number: correlate at <span class="math inline">\(r = 0.7\)</span> → variance <span class="math inline">\(\times\,0.51\)</span> → <strong>half the sample size</strong> for the same power. And <span class="math inline">\(\theta = \operatorname{Cov}/\operatorname{Var}\)</span> is just the <strong>OLS slope</strong> of <span class="math inline">\(Y\)</span> on <span class="math inline">\(X\)</span> — CUPED is regression adjustment wearing a product-analytics badge.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Оптимальна θ. Дисперсія Y_cuped — парабола за θ: Var(Y) − 2θCov + θ²Var(X). Диференціюємо, прирівнюємо до нуля: θ* = Cov(X,Y)/Var(X). Підставляємо назад — і отримуємо головну формулу методу: Var(Y_cuped) = Var(Y)·(1 − r²), де r — кореляція коваріати з метрикою. Уся сила CUPED в одному числі: r = 0.7 → дисперсія множиться на 0.51 → удвічі менше користувачів за тієї ж потужності. І зверніть увагу: θ* = Cov/Var — це в точності НАХИЛ OLS-регресії Y на X. CUPED — це регресійне коригування, перевдягнене в термінологію продуктової аналітики; для статистика тут немає нової математики, є нова дисципліна застосування.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="what-makes-a-good-covariate" class="slide level2 smaller">
<h2>🧰 What makes a good covariate</h2>
<blockquote>
<p>Anything correlated with <span class="math inline">\(Y\)</span> that <strong>cannot be affected by the treatment</strong>.</p>
</blockquote>
<ol type="1">
<li><strong>The same metric, pre-experiment</strong> — the default and usually the best:
<ul>
<li>for ARPU → ARPU over the previous 4 weeks;</li>
<li>for retention → last month’s retention; for CTR → last week’s CTR.</li>
</ul></li>
<li><strong>Other pre-experiment behaviour</strong> — sessions, order frequency, average basket before the test.</li>
<li><strong>ML predictions</strong> of <span class="math inline">\(Y\)</span> built on pre-experiment features (a.k.a. CUPAC) — squeezes several covariates into one.</li>
<li><strong>Stable attributes</strong> — country, device, cohort.</li>
</ol>
<div class="fragment">
<p>Industry calibration:</p>
<ul>
<li><strong>Netflix</strong> (KDD 2016): streaming-hours metric, covariate = pre-experiment streaming hours → <strong>≈40%</strong> variance reduction.</li>
<li><strong>Microsoft</strong> (2022): CTR with a 2-week pre-period → gain equivalent to <strong>adding ~20% traffic</strong>.</li>
</ul>
<aside class="notes">
<p>Що брати за коваріату? Дефолт і зазвичай найкращий вибір — ТА САМА метрика за передекспериментальний період: для ARPU — ARPU за попередні 4 тижні, для ретеншена — ретеншен минулого місяця, для CTR — CTR минулого тижня. Працює й інша передекспериментальна поведінка (сесії, частота замовлень, середній кошик), ML-прогноз метрики за історичними фічами (це називають CUPAC — корисно, коли хочеться стиснути кілька коваріат в одну), стабільні атрибути типу країни чи девайса. Єдина тверда вимога — трітмент НЕ МОЖЕ впливати на коваріату; усе виміряне до старту експерименту автоматично безпечне. Індустріальні орієнтири: Netflix на KDD-2016 звітував ≈40% зниження дисперсії для годин стрімінгу з коваріатою «години стрімінгу до експерименту»; Microsoft у 2022 — виграш, еквівалентний +20% трафіку для CTR. Посилання — в матеріалах курсу.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="cuped_ttest" class="slide level2 smaller">
<h2>🐍 <code>cuped_ttest</code></h2>
<div id="cuped-fn" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="" aria-hidden="true" tabindex="-1"></a>r_xy <span class="op">=</span> <span class="fl">0.7</span>          <span class="co"># historical corr(pre-ARPU, ARPU) at our store</span></span>
<span id="cb15-2"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> draw_arm_cuped(size, rng, effect<span class="op">=</span><span class="fl">0.0</span>):</span>
<span id="cb15-4"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""One arm: pre-experiment ARPU x and experiment ARPU y, corr = r_xy."""</span></span>
<span id="cb15-5"><a href="" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> rng.normal(mu, sigma, size)</span>
<span id="cb15-6"><a href="" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> mu <span class="op">+</span> r_xy<span class="op">*</span>(x <span class="op">-</span> mu) <span class="op">+</span> sigma<span class="op">*</span>np.sqrt(<span class="dv">1</span> <span class="op">-</span> r_xy<span class="op">**</span><span class="dv">2</span>)<span class="op">*</span>rng.standard_normal(size) <span class="op">+</span> effect</span>
<span id="cb15-7"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> x, y</span>
<span id="cb15-8"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> calculate_theta(x, y):</span>
<span id="cb15-10"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.cov(x, y)[<span class="dv">0</span>, <span class="dv">1</span>] <span class="op">/</span> x.var(ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb15-11"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cuped_ttest(x_c, y_c, x_t, y_t):</span>
<span id="cb15-13"><a href="" aria-hidden="true" tabindex="-1"></a>    theta <span class="op">=</span> calculate_theta(np.concatenate([x_c, x_t]),</span>
<span id="cb15-14"><a href="" aria-hidden="true" tabindex="-1"></a>                            np.concatenate([y_c, y_t]))</span>
<span id="cb15-15"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ttest_ind(y_c <span class="op">-</span> theta<span class="op">*</span>x_c, y_t <span class="op">-</span> theta<span class="op">*</span>x_t, equal_var<span class="op">=</span><span class="va">False</span>).pvalue</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><span class="math inline">\(\theta\)</span> is estimated on <strong>both arms pooled</strong> — one shared constant, as the unbiasedness argument requires.</p>
<aside class="notes">
<p>Реалізація. draw_arm_cuped генерує пару (X, Y) з кореляцією 0.7 — «історичне» ARPU і ARPU під час експерименту. calculate_theta — формула Cov/Var. cuped_ttest: оцінюємо θ на ОБ’ЄДНАНИХ групах (одна спільна константа — саме цього вимагав аргумент незміщеності), віднімаємо θX у кожній групі і застосовуємо звичайний Welch-тест до скоригованих значень. Три функції, жодної нової статистики — вся новизна в передобробці метрики. Тепер традиційний ритуал: перевіряємо на симуляціях, що FPR не роздуто і скільки потужності це дає.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="monte-carlo-does-cuped-cheat" class="slide level2 smaller">
<h2>🔬 Monte Carlo: does CUPED cheat?</h2>
<div id="mc-cuped" class="cell columns column-output-location" data-execution_count="13">
<div class="column">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">5</span>)</span>
<span id="cb16-2"><a href="" aria-hidden="true" tabindex="-1"></a>MC  <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb16-3"><a href="" aria-hidden="true" tabindex="-1"></a>p_cuped_aa, p_cuped_ab, p_plain_ab <span class="op">=</span> (np.empty(MC) <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">3</span>))</span>
<span id="cb16-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(MC):</span>
<span id="cb16-6"><a href="" aria-hidden="true" tabindex="-1"></a>    x_a, y_a <span class="op">=</span> draw_arm_cuped(n, rng)</span>
<span id="cb16-7"><a href="" aria-hidden="true" tabindex="-1"></a>    x_b, y_b <span class="op">=</span> draw_arm_cuped(n, rng)</span>
<span id="cb16-8"><a href="" aria-hidden="true" tabindex="-1"></a>    x_t, y_t <span class="op">=</span> draw_arm_cuped(n, rng, effect<span class="op">=</span>mde)</span>
<span id="cb16-9"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="" aria-hidden="true" tabindex="-1"></a>    p_cuped_aa[i] <span class="op">=</span> cuped_ttest(x_a, y_a, x_b, y_b)</span>
<span id="cb16-11"><a href="" aria-hidden="true" tabindex="-1"></a>    p_cuped_ab[i] <span class="op">=</span> cuped_ttest(x_a, y_a, x_t, y_t)</span>
<span id="cb16-12"><a href="" aria-hidden="true" tabindex="-1"></a>    p_plain_ab[i] <span class="op">=</span> ttest_ind(y_a, y_t, equal_var<span class="op">=</span><span class="va">False</span>).pvalue</span>
<span id="cb16-13"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"CUPED A/A FPR :"</span>, wilson((p_cuped_aa <span class="op">&lt;</span> alpha).<span class="bu">sum</span>(), MC))</span>
<span id="cb16-15"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"CUPED A/B pow :"</span>, wilson((p_cuped_ab <span class="op">&lt;</span> alpha).<span class="bu">sum</span>(), MC))</span>
<span id="cb16-16"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"plain A/B pow :"</span>, wilson((p_plain_ab <span class="op">&lt;</span> alpha).<span class="bu">sum</span>(), MC))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>CUPED A/A FPR : 0.053  [0.041, 0.069]
CUPED A/B pow : 0.974  [0.962, 0.982]
plain A/B pow : 0.805  [0.779, 0.828]</code></pre>
</div>
</div></div>
<div id="cell-cuped-pplot" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="fl">12.5</span>, <span class="fl">3.2</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb18-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, p, ttl, color <span class="kw">in</span> <span class="bu">zip</span>(</span>
<span id="cb18-3"><a href="" aria-hidden="true" tabindex="-1"></a>        axes, (p_cuped_aa, p_cuped_ab, p_plain_ab),</span>
<span id="cb18-4"><a href="" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"CUPED A/A"</span>, <span class="st">"CUPED A/B"</span>, <span class="st">"plain t A/B"</span>),</span>
<span id="cb18-5"><a href="" aria-hidden="true" tabindex="-1"></a>        (red_pink, turquoise, orange)):</span>
<span id="cb18-6"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.hist(p, bins<span class="op">=</span><span class="dv">20</span>, <span class="bu">range</span><span class="op">=</span>(<span class="dv">0</span>, <span class="dv">1</span>), color<span class="op">=</span>color, alpha<span class="op">=</span><span class="fl">0.85</span>)</span>
<span id="cb18-7"><a href="" aria-hidden="true" tabindex="-1"></a>    ax.set_title(ttl)<span class="op">;</span> ax.set_xlabel(<span class="st">"p-value"</span>)</span>
<span id="cb18-8"><a href="" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"count"</span>)</span>
<span id="cb18-9"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb18-10"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".09-var-reduce_files/figure-revealjs/cuped-pplot-output-1.svg" id="cuped-pplot" class="quarto-figure quarto-figure-center r-stretch"><aside class="notes">
<p>Стенд: 1000 світів, n = 1005 на групу, r = 0.7, ефект 10 грн. Три розподіли p-value. CUPED A/A — рівномірний, FPR ≈ 0.05: метод не махлює, нулю він відхиляє рівно з обіцяною частотою. CUPED A/B — маса біля нуля, потужність ≈ 0.97. Звичайний t-тест на тих самих даних — ≈ 0.80. Сімнадцять пунктів потужності з тієї ж вибірки, і формула не збрехала: виміряний var ratio ≈ 0.51 = 1 − 0.7². Проти стратифікації (0.95) CUPED тут трохи сильніший — бо неперервна історія користувача несе більше інформації, ніж бінарна мітка лояльності. За хвилину ми побачимо, що ці двоє ще й конкурують за одну й ту саму інформацію.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="cuped-fine-print" class="slide level2 smaller">
<h2>⚠️ CUPED fine print</h2>
<ol type="1">
<li><strong>Correlation is the whole game.</strong> Gain <span class="math inline">\(= 1 - r^2\)</span>: at <span class="math inline">\(|r| = 0.3\)</span> you shave only <span class="math inline">\(9\%\)</span> of variance. Below that — not worth the pipeline complexity.</li>
<li><strong>The covariate must be treatment-free.</strong> Pre-experiment data is safe <em>by construction</em>. A covariate measured <strong>during</strong> the experiment (sessions, visits…) can absorb part of the effect — and silently bias the estimate.</li>
<li><strong>New users have no history.</strong> <span class="math inline">\(X\)</span> missing → CUPED degrades toward the plain test (Netflix: 5–15% reduction for new users vs 40% for existing). Practical fix: set <span class="math inline">\(X = \bar X\)</span> (or <span class="math inline">\(0\)</span> in the centred form) for them.</li>
<li><strong>It’s OLS.</strong> CUPED with pooled <span class="math inline">\(\theta\)</span> ≡ regression adjustment; more covariates → multiple regression / CUPAC.</li>
</ol>
<aside class="notes">
<p>Дрібний шрифт CUPED. (1) Виграш — це рівно 1 − r²: за |r| = 0.3 ви зрізаєте лише 9% дисперсії; нижче — ускладнення пайплайна того не варте. (2) Коваріата не сміє залежати від трітменту. Передекспериментальні дані безпечні ЗА ПОБУДОВОЮ. А от «кількість сесій під час експерименту» — вже ні: якщо трітмент збільшує і сесії, і виручку, віднімання θ·сесії з’їсть частину ефекту, і оцінка тихо зміститься. Це найпоширеніший спосіб зіпсувати CUPED на практиці. (3) У нових користувачів історії немає: для них X пропущений, і виграш деградує (у Netflix 5–15% проти 40% у старих). Практичний трюк — підставити їм середнє X̄ (у центрованій формі — нуль): вони просто не отримують коригування. (4) І ще раз: це OLS. Хочете кілька коваріат — множинна регресія або CUPAC. Уся «магія» — дисципліна вибору коваріати, не математика.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="ratio-metrics-the-unit-of-analysis-trap" class="title-slide slide level1 center" data-background-iframe=".09-var-reduce_files/libs/colored-particles/index.html">
<h1>Ratio metrics: the unit-of-analysis trap</h1>

</section>
<section id="a-new-request" class="slide level2 smaller">
<h2>🛍️ A new request</h2>
<p>The PM is back with a different metric:</p>
<blockquote>
<p>“The redesigned checkout should make people complete orders more often. Measure the <strong>session→order conversion</strong>: of all sessions, how many end with a purchase?”</p>
</blockquote>
<p>Four users of the pilot log:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">user</th>
<th style="text-align: center;">sessions</th>
<th style="text-align: center;">orders</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>total</strong></td>
<td style="text-align: center;"><strong>16</strong></td>
<td style="text-align: center;"><strong>10</strong></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\text{CR} = \frac{\text{orders}}{\text{sessions}} = \frac{10}{16} = 0.625
\]</span></p>
<p>One number, two levels: <strong>sessions</strong> live inside <strong>users</strong>. Which one is the <em>unit</em>?</p>
<aside class="notes">
<p>Третя секція — і найпідступніша пастка лекції. Новий запит PM: редизайн чекаута має підвищити конверсію сесії в замовлення. Метрика — session→order conversion: частка сесій, що закінчились покупкою. Мініатюрний приклад: чотири користувачі, 16 сесій, 10 замовлень, CR = 0.625. Але придивіться до таблиці: у цього числа ДВА рівні — сесії живуть УСЕРЕДИНІ користувачів. Рандомізуємо ми КОРИСТУВАЧІВ (не можна ж показувати одній людині різні чекаути в різних сесіях), а конверсія рахується ПО СЕСІЯХ. Питання, яка з двох сутностей — «одиниця», звучить занудно, але зараз ми побачимо, що неправильна відповідь коштує роздутого вп’ятеро-вдесятеро FPR.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-tempting-analysis" class="slide level2 smaller">
<h2>🍬 The tempting analysis</h2>
<p>Lecture-2 reflex: conversion = proportion → unroll every session into a <span class="math inline">\(0/1\)</span> outcome and compare two proportions.</p>
<p><span class="math display">\[
\underbrace{[1,1,1,1,0]}_{\text{user 1}},\;
\underbrace{[1,0,0,0]}_{\text{user 2}},\;
\underbrace{[0]}_{\text{user 3}},\;
\underbrace{[1,1,1,1,1,0]}_{\text{user 4}}
\;\;\longrightarrow\;\;
\text{one big } 0/1 \text{ sample, } n = 16
\]</span></p>
<div class="fragment">
<p>Feels legitimate: thousands of sessions, big <span class="math inline">\(n\)</span>, tiny standard errors…</p>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>But the t-test (and the z-test for proportions) assumes observations are <strong>i.i.d.</strong> Sessions of the <em>same</em> user are neither independent nor identically distributed: each user carries their own habit — and <em>their own</em> propensity to buy.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Спокусливий аналіз — рефлекс із другої лекції: конверсія це частка, частки порівнюємо z-тестом. Розгортаємо кожну сесію в нулик-одиничку, отримуємо «вибірку» з 16 (а в реальному тесті — з десятків тисяч) спостережень, стандартні похибки крихітні, все красиво. Пастка в базовому припущенні: t- і z-тести вимагають i.i.d. А сесії ОДНОГО користувача — не незалежні і не однаково розподілені: у кожної людини своя звичка й своя схильність купувати. Сесії користувача 1 «пам’ятають» одна одну через його особистість. Формально: дані кластеровані, а ми робимо вигляд, що кожна сесія — окрема людина. Наскільки це страшно? Спершу мисленнєвий експеримент, потім симуляція.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="two-stubborn-users" class="slide level2 smaller">
<h2>🙅 Two stubborn users</h2>
<p>A thought experiment:</p>
<ul>
<li>One user in <strong>test</strong>, one in <strong>control</strong>; each makes <span class="math inline">\(10\,000\)</span> sessions.</li>
<li>The test user <strong>always</strong> orders (conversion <span class="math inline">\(1\)</span>), the control user <strong>never</strong> does (conversion <span class="math inline">\(0\)</span>) — personalities, not treatment.</li>
</ul>
<div class="fragment">
<p>The pooled t-test sees two samples of <span class="math inline">\(10\,000\)</span> observations: all ones vs all zeros → <span class="math inline">\(p \approx 0\)</span>, “an overwhelming win”. Swap the users — an equally overwhelming <strong>loss</strong>.</p>
<div class="callout callout-note no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>The effective sample size here is <span class="math inline">\(n = 2\)</span>, not <span class="math inline">\(n = 20\,000\)</span>. Sessions multiply the <em>volume</em> of data, not the <em>evidence</em>. Randomization assigned <strong>users</strong> — the experiment cannot know more than the number of users it randomized.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Мисленнєвий експеримент, який варто запам’ятати назавжди. Один користувач у тесті, один у контролі, кожен зробив по 10 000 сесій. Тестовий завжди замовляє (це його характер, не заслуга чекаута), контрольний — ніколи. Пул-тест бачить 10 000 одиниць проти 10 000 нулів: p ≈ 0, «нищівна перемога тесту». Поміняйте користувачів місцями — «нищівна поразка». Насправді ефективний розмір вибірки тут — ДВА. Сесії множать обсяг даних, але не обсяг ДОКАЗІВ: рандомізація призначала користувачів, і більше інформації, ніж кількість користувачів, в експерименті немає. Правило, яке з цього випливає: одиниця аналізу має збігатися з одиницею рандомізації.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-trap-measured" class="slide level2 smaller">
<h2>🔬 The trap, measured</h2>
<p>A realistic grocery world: heavy-tailed activity, personal conversion propensities.</p>
<div id="mc-pooled" class="cell columns column-output-location" data-execution_count="15">
<div class="column">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> draw_group(n_users, rng, lift<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb19-2"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Sessions and orders per user over the experiment window."""</span></span>
<span id="cb19-3"><a href="" aria-hidden="true" tabindex="-1"></a>    lam      <span class="op">=</span> rng.gamma(<span class="fl">1.0</span>, <span class="fl">20.0</span>, n_users)     <span class="co"># user activity</span></span>
<span id="cb19-4"><a href="" aria-hidden="true" tabindex="-1"></a>    sessions <span class="op">=</span> rng.poisson(lam) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb19-5"><a href="" aria-hidden="true" tabindex="-1"></a>    p        <span class="op">=</span> np.minimum(rng.beta(<span class="fl">0.8</span>, <span class="fl">3.2</span>, n_users)<span class="op">*</span>lift, <span class="fl">1.0</span>)</span>
<span id="cb19-6"><a href="" aria-hidden="true" tabindex="-1"></a>    orders   <span class="op">=</span> rng.binomial(sessions, p)</span>
<span id="cb19-7"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> sessions, orders</span>
<span id="cb19-8"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> unroll(sessions, orders):</span>
<span id="cb19-10"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Per-session 0/1 outcomes (order doesn't matter for a t-test)."""</span></span>
<span id="cb19-11"><a href="" aria-hidden="true" tabindex="-1"></a>    total <span class="op">=</span> sessions.<span class="bu">sum</span>()</span>
<span id="cb19-12"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.concatenate([np.ones(orders.<span class="bu">sum</span>()),</span>
<span id="cb19-13"><a href="" aria-hidden="true" tabindex="-1"></a>                           np.zeros(total <span class="op">-</span> orders.<span class="bu">sum</span>())])</span>
<span id="cb19-14"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-15"><a href="" aria-hidden="true" tabindex="-1"></a>rng     <span class="op">=</span> np.random.default_rng(<span class="dv">7</span>)</span>
<span id="cb19-16"><a href="" aria-hidden="true" tabindex="-1"></a>MC, n_u <span class="op">=</span> <span class="dv">1000</span>, <span class="dv">2000</span></span>
<span id="cb19-17"><a href="" aria-hidden="true" tabindex="-1"></a>fpr_cnt <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb19-18"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(MC):</span>
<span id="cb19-19"><a href="" aria-hidden="true" tabindex="-1"></a>    o_c, m_c <span class="op">=</span> draw_group(n_u, rng)</span>
<span id="cb19-20"><a href="" aria-hidden="true" tabindex="-1"></a>    o_t, m_t <span class="op">=</span> draw_group(n_u, rng)</span>
<span id="cb19-21"><a href="" aria-hidden="true" tabindex="-1"></a>    pv <span class="op">=</span> ttest_ind(unroll(o_c, m_c), unroll(o_t, m_t),</span>
<span id="cb19-22"><a href="" aria-hidden="true" tabindex="-1"></a>                   equal_var<span class="op">=</span><span class="va">False</span>).pvalue</span>
<span id="cb19-23"><a href="" aria-hidden="true" tabindex="-1"></a>    fpr_cnt <span class="op">+=</span> pv <span class="op">&lt;</span> alpha</span>
<span id="cb19-24"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-25"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"pooled-session A/A FPR:"</span>,</span>
<span id="cb19-26"><a href="" aria-hidden="true" tabindex="-1"></a>      wilson(fpr_cnt, MC))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>pooled-session A/A FPR: 0.512  [0.481, 0.543]</code></pre>
</div>
</div></div>
<div class="fragment">
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>An <strong>A/A test</strong> — no effect anywhere — and the pooled-session t-test fires in <strong>half of all experiments</strong>. This is not a subtle bias; it is a machine for shipping placebo features.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Вимірюємо пастку. Реалістичний світ: активність користувача — важкохвоста (гамма-пуассон: хтось заходить раз, хтось — 60 разів за вікно), особиста схильність купувати — бета(0.8, 3.2), середня конверсія ≈ 20%. Дві групи по 2000 користувачів, ЖОДНОГО ефекту — чистий A/A. Розгортаємо сесії в нулі-одиниці, застосовуємо t-тест… і він відхиляє нуль у ≈51% експериментів замість 5%. Це не «легке заниження похибки» — це машина з ухвалення плацебо-фіч: кожен другий нейтральний реліз буде «статистично значущим». Зверніть увагу на unroll: для t-тесту порядок нулів та одиниць неважливий, тож достатньо M одиниць і O−M нулів. Причина катастрофи — та сама: справжня одиниця — користувач, а ми порахували стандартну похибку так, ніби кожна сесія незалежна.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-honest-target" class="slide level2 smaller">
<h2>🧭 The honest target</h2>
<p>State the hypothesis about the <strong>ratio metric</strong> of each arm:</p>
<p><span class="math display">\[
K = \frac{\sum_i M_i}{\sum_i O_i},
\qquad
H_0\!: K_T - K_C = 0 \;\;\text{vs}\;\; H_1\!: K_T - K_C \neq 0,
\]</span></p>
<p>where <span class="math inline">\(O_i\)</span>, <span class="math inline">\(M_i\)</span> are <strong>per-user</strong> sessions and orders — users stay whole.</p>
<div class="fragment">
<p>But <span class="math inline">\(K\)</span> is a <em>ratio of two random sums</em>: no textbook CI, <code>ttest_ind</code> does not apply…</p>
<p><br></p>
<center>
Sound familiar? <span class="hi"><strong>Bootstrap!</strong></span> — lecture 8’s promise: <em>one universal recipe for almost any statistic</em>.
</center>
<aside class="notes">
<p>Чесна постановка. Гіпотезу формулюємо про ratio-метрику групи: K = сума замовлень / сума сесій, де суми йдуть по КОРИСТУВАЧАХ групи — користувачі лишаються цілими, ніхто не розгортає їх у сесії. K — це session-weighted конверсія: сесія активного користувача важить стільки ж, скільки сесія рідкісного гостя; саме так метрику й бачить бізнес у дашборді. Але K — відношення двох випадкових сум: підручникової формули ДІ немає, ttest_ind не застосуєш. Знайомо звучить? Минула лекція давала обіцянку: бутстреп — один універсальний рецепт довірчого інтервалу майже для будь-якої статистики. Час стягнути дивіденди.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="bootstrap-the-users" class="slide level2 smaller">
<h2>♻️ Bootstrap the <em>users</em></h2>
<div id="ratio-boot-fn" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> ratio_bootstrap_ci(o_c, m_c, o_t, m_t, rng, B<span class="op">=</span><span class="dv">1000</span>, alpha<span class="op">=</span><span class="fl">0.05</span>):</span>
<span id="cb21-2"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Central bootstrap CI for K_t - K_c, resampling whole users."""</span></span>
<span id="cb21-3"><a href="" aria-hidden="true" tabindex="-1"></a>    k_hat <span class="op">=</span> m_t.<span class="bu">sum</span>()<span class="op">/</span>o_t.<span class="bu">sum</span>() <span class="op">-</span> m_c.<span class="bu">sum</span>()<span class="op">/</span>o_c.<span class="bu">sum</span>()</span>
<span id="cb21-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="" aria-hidden="true" tabindex="-1"></a>    ic <span class="op">=</span> rng.integers(<span class="dv">0</span>, o_c.size, (B, o_c.size))   <span class="co"># user indices!</span></span>
<span id="cb21-6"><a href="" aria-hidden="true" tabindex="-1"></a>    it <span class="op">=</span> rng.integers(<span class="dv">0</span>, o_t.size, (B, o_t.size))</span>
<span id="cb21-7"><a href="" aria-hidden="true" tabindex="-1"></a>    k_star <span class="op">=</span> (m_t[it].<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> o_t[it].<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb21-8"><a href="" aria-hidden="true" tabindex="-1"></a>              <span class="op">-</span> m_c[ic].<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> o_c[ic].<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb21-9"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="" aria-hidden="true" tabindex="-1"></a>    q_lo, q_hi <span class="op">=</span> np.quantile(k_star, [alpha<span class="op">/</span><span class="dv">2</span>, <span class="dv">1</span> <span class="op">-</span> alpha<span class="op">/</span><span class="dv">2</span>])</span>
<span id="cb21-11"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">2</span><span class="op">*</span>k_hat <span class="op">-</span> q_hi, <span class="dv">2</span><span class="op">*</span>k_hat <span class="op">-</span> q_lo</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-important no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Resample <strong>user indices</strong>, so each draw carries its <span class="math inline">\((O_i, M_i)\)</span> <strong>pair</strong>. Resampling orders and sessions <em>separately</em> would break the within-user link — the exact dependence the whole section is about.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Двовибірковий бутстреп із восьмої лекції, з одним вирішальним нюансом: ресемплимо ІНДЕКСИ КОРИСТУВАЧІВ, щоб кожне витягування тягло за собою ПАРУ (сесії, замовлення) цієї людини. Ресемплити замовлення і сесії окремими choice-ами — значить розірвати внутрішньокористувацький зв’язок, тобто саме ту залежність, довкола якої вся секція. Технічно: матриці індексів B×n, fancy indexing, суми по axis=1 — і B значень K* за один прохід; ДІ — центральний, як ми домовилися минулого разу. Одиниця ресемплінгу = одиниця рандомізації = користувач. Це правило працює і для будь-яких інших кластерованих даних: ресемплюємо кластери цілком.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="calibration-and-power" class="slide level2 smaller">
<h2>🔬 Calibration and power</h2>
<div id="mc-ratio" class="cell columns column-output-location" data-execution_count="17">
<div class="column">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">3</span>)</span>
<span id="cb22-2"><a href="" aria-hidden="true" tabindex="-1"></a>MC_b <span class="op">=</span> <span class="dv">500</span></span>
<span id="cb22-3"><a href="" aria-hidden="true" tabindex="-1"></a>fpr <span class="op">=</span> pwr_ratio <span class="op">=</span> pwr_user_t <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb22-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(MC_b):</span>
<span id="cb22-6"><a href="" aria-hidden="true" tabindex="-1"></a>    o_a, m_a <span class="op">=</span> draw_group(n_u, rng)</span>
<span id="cb22-7"><a href="" aria-hidden="true" tabindex="-1"></a>    o_b, m_b <span class="op">=</span> draw_group(n_u, rng)</span>
<span id="cb22-8"><a href="" aria-hidden="true" tabindex="-1"></a>    o_t, m_t <span class="op">=</span> draw_group(n_u, rng, lift<span class="op">=</span><span class="fl">1.10</span>)</span>
<span id="cb22-9"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="" aria-hidden="true" tabindex="-1"></a>    lo, hi <span class="op">=</span> ratio_bootstrap_ci(o_a, m_a, o_b, m_b, rng)</span>
<span id="cb22-11"><a href="" aria-hidden="true" tabindex="-1"></a>    fpr <span class="op">+=</span> (lo <span class="op">&gt;</span> <span class="dv">0</span>) <span class="op">|</span> (hi <span class="op">&lt;</span> <span class="dv">0</span>)</span>
<span id="cb22-12"><a href="" aria-hidden="true" tabindex="-1"></a>    lo, hi <span class="op">=</span> ratio_bootstrap_ci(o_a, m_a, o_t, m_t, rng)</span>
<span id="cb22-13"><a href="" aria-hidden="true" tabindex="-1"></a>    pwr_ratio <span class="op">+=</span> (lo <span class="op">&gt;</span> <span class="dv">0</span>) <span class="op">|</span> (hi <span class="op">&lt;</span> <span class="dv">0</span>)</span>
<span id="cb22-14"><a href="" aria-hidden="true" tabindex="-1"></a>    pwr_user_t <span class="op">+=</span> ttest_ind(m_a, m_t,</span>
<span id="cb22-15"><a href="" aria-hidden="true" tabindex="-1"></a>                            equal_var<span class="op">=</span><span class="va">False</span>).pvalue <span class="op">&lt;</span> alpha</span>
<span id="cb22-16"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-17"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"ratio bootstrap A/A FPR :"</span>, wilson(fpr, MC_b))</span>
<span id="cb22-18"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"ratio bootstrap power   :"</span>, wilson(pwr_ratio, MC_b))</span>
<span id="cb22-19"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"orders-per-user t power :"</span>, wilson(pwr_user_t, MC_b))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>ratio bootstrap A/A FPR : 0.050  [0.034, 0.073]
ratio bootstrap power   : 0.622  [0.579, 0.663]
orders-per-user t power : 0.422  [0.379, 0.466]</code></pre>
</div>
</div></div>
<div class="fragment">
<p>The user-level bootstrap is <strong>calibrated</strong> (FPR <span class="math inline">\(\approx \alpha\)</span>). And against the honest fallback — a t-test on <em>orders per user</em> — the ratio metric wins power: orders per user <span class="math inline">\(= O_i \cdot p_i\)</span> drags the noisy activity <span class="math inline">\(O_i\)</span> into the metric, while <span class="math inline">\(K\)</span> mostly cancels it.</p>
<aside class="notes">
<p>Перевіряємо обидві обіцянки. Калібрування: у A/A користувацький бутстреп спрацьовує хибно ≈5% — рівно за прейскурантом (порівняйте з 54% у пул-тесту!). Потужність: підіймаємо конверсію в тесті на 10% і порівнюємо з чесною альтернативою — t-тестом по «замовлень на користувача» (це валідний критерій: одиниця — користувач, i.i.d. дотримано; саме його торік називали бейзлайном). Ratio-метрика виграє: ≈0.62 проти ≈0.42. Причина: замовлення на користувача = O_i·p_i, тобто в метрику затягнуто гучний шум активності O_i (гамма з важким хвостом); а в K активність здебільшого скорочується — чисельник і знаменник ходять разом. Це знову зниження дисперсії, тільки досягнуте вибором МЕТРИКИ. Важливо: це різні гіпотези (session-weighted конверсія vs середні замовлення) — обирати треба ту, що відповідає бізнес-питанню, і тут питання PM саме про конверсію сесій.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="the-denominator-danger" class="slide level2 smaller">
<h2>🕳️ The denominator danger</h2>
<p>The ratio hides a second moving part: the treatment can move the <strong>denominator</strong> too.</p>
<blockquote>
<p>Checkout redesign → orders are easier → users come back for <em>extra quick sessions</em> → <span class="math inline">\(\sum O\)</span> grows → <span class="math inline">\(K\)</span> can <strong>fall</strong> while the business booms (or rise while it burns).</p>
</blockquote>
<div class="fragment">
<p>The working rule from practice:</p>
<ul>
<li>Sure the treatment <strong>can’t touch the denominator</strong>? → test the ratio metric alone.</li>
<li>Any chance it can? → <strong>test the denominator separately</strong> (a per-user t-test on <span class="math inline">\(O_i\)</span> — it’s i.i.d. by user), and read the ratio only alongside it.</li>
</ul>
<div class="callout callout-warning no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>A ratio metric is a <em>fraction of two experiments</em>. Report numerator, denominator and the ratio — never the ratio alone.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Остання міна секції — знаменник. Трітмент може рухати не лише чисельник: зручний чекаут → замовляти легше → користувачі повертаються за додатковими короткими сесіями → сума сесій росте → конверсія K може ВПАСТИ на тлі процвітаючого бізнесу. Або навпаки: фіча, що відлякує казуальних відвідувачів, зріже знаменник і «підніме конверсію» на пожежі. Робоче правило: якщо ви впевнені, що трітмент не чіпає знаменник, — тестуйте ratio-метрику саму; якщо є хоч шанс — окремо тестуйте знаменник (t-тест по сесіях на користувача — це i.i.d. по користувачах, звичайний критерій) і читайте ratio тільки поруч із ним. У звіті ratio-метрика ніколи не ходить сама: чисельник, знаменник, відношення — три числа, інакше рішення наосліп.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="linearization" class="title-slide slide level1 center" data-background-iframe=".09-var-reduce_files/libs/colored-particles/index.html">
<h1>Linearization</h1>

</section>
<section id="the-scaling-problem" class="slide level2 smaller">
<h2>🏗️ The scaling problem</h2>
<p>You join a company to build the <strong>A/B platform</strong>: hundreds of experiments, thousands of metrics, automatic reports every morning.</p>
<p>The bootstrap served us well, but at platform scale it hurts:</p>
<ul>
<li><span class="math inline">\(B = 10\,000\)</span> resamples <strong>per metric per experiment</strong>, daily;</li>
<li>memory: index matrices of size <span class="math inline">\(B \times n\)</span> for every ratio metric;</li>
<li>and the rest of the platform machinery — CUPED, stratification, sequential monitors — expects a <strong>per-user column</strong>, not a resampling loop.</li>
</ul>
<div class="fragment">
<p>Dream: transform <span class="math inline">\((O_i, M_i)\)</span> into a single per-user value <span class="math inline">\(Z_i\)</span> such that a plain <strong>t-test on <span class="math inline">\(Z\)</span></strong> answers the question about the ratio <span class="math inline">\(K\)</span>.</p>
<aside class="notes">
<p>Мотивація лінеаризації — інженерна. Уявіть, що ви будуєте корпоративну A/B-платформу: сотні експериментів, тисячі метрик, автоматичні ранкові звіти. Бутстреп чудовий, але на такому масштабі болить: десять тисяч ресемплів на кожну метрику кожного експерименту щодня, матриці індексів B×n у пам’яті, а головне — вся інша машинерія платформи (CUPED, стратифікація, секвенційні монітори) очікує на вхід КОЛОНКУ ЗНАЧЕНЬ по користувачах, а не цикл ресемплінгу. Мрія: перетворити пару (сесії, замовлення) кожного користувача на одне число Z_i так, щоб звичайний t-тест по Z відповідав на питання про ratio-метрику K. Ця мрія має назву — лінеаризація (дельта-метод), і коштує вона один рядок Тейлора.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="one-line-of-taylor" class="slide level2 tiny">
<h2>📐 One line of Taylor</h2>
<p>First-order Taylor expansion of <span class="math inline">\(f(x, y) = x/y\)</span> around <span class="math inline">\((x_0, y_0)\)</span>:</p>
<p><span class="math display">\[
\frac{x}{y} \;\approx\; \frac{x_0}{y_0} + \frac{1}{y_0}(x - x_0) - \frac{x_0}{y_0^2}(y - y_0)
\;=\; \frac{x_0}{y_0} + \frac{1}{y_0}\left(x - \frac{x_0}{y_0}\, y\right)
\]</span></p>
<p>Our statistic is exactly such a ratio — of two <strong>means</strong>: <span class="math inline">\(K = \dfrac{\sum M_i}{\sum O_i} = \dfrac{\overline{M}}{\overline{O}}\)</span>. Expand around <span class="math inline">\((\mathbb{E}M, \mathbb{E}O)\)</span> (LLN drives the means there):</p>
<p><span class="math display">\[
\frac{\overline M}{\overline O}
\;\approx\; \frac{\mathbb{E}M}{\mathbb{E}O} + \frac{1}{\mathbb{E}O}\left(\overline M - \frac{\mathbb{E}M}{\mathbb{E}O}\,\overline O\right)
\;=\; \frac{1}{n}\sum_{i=1}^{n} \underbrace{\left[\frac{\mathbb{E}M}{\mathbb{E}O} + \frac{1}{\mathbb{E}O}\left(M_i - \frac{\mathbb{E}M}{\mathbb{E}O}\, O_i\right)\right]}_{Z_i'}
\]</span></p>
<div class="fragment">
<p>The ratio of means became a <strong>mean of per-user values</strong> <span class="math inline">\(Z_i'\)</span> — i.i.d., because users are. Plug in the estimates (<span class="math inline">\(\mathbb{E}M \to \overline M\)</span>, <span class="math inline">\(\mathbb{E}O \to \overline O\)</span>, consistent by LLN):</p>
<p><span class="math display">\[
\boxed{\;Z_i = K + \frac{1}{\overline O}\big(M_i - K\, O_i\big), \qquad K = \overline M / \overline O\;}
\]</span></p>
<aside class="notes">
<p>Вся математика лінеаризації — один рядок Тейлора. Розкладаємо f(x,y) = x/y до перших похідних довкола точки (x₀, y₀) і згортаємо в компактну форму. Далі помічаємо: наша K — це відношення двох СЕРЕДНІХ (поділіть чисельник і знаменник на n). Розкладаємо довкола (EM, EO) — саме туди середні збігаються за ЗВЧ — і диво: відношення середніх перетворилося на СЕРЕДНЄ по-користувацьких значень Z’_i. А Z’_i — i.i.d., бо i.i.d. користувачі! Справжніх EM і EO ми не знаємо — підставляємо їхні консистентні оцінки, отримуємо робочу формулу Z_i = K + (M_i − K·O_i)/Ō. Інтуїція для студентів: Z_i вимірює, наскільки користувач i «перевиконує» групову конверсію K на своїх сесіях, у масштабі внеску в K. Хто конвертить вище середнього — Z вище K, хто нижче — нижче. При великих n усе це строго обґрунтовується дельта-методом.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="linearize-and-a-free-lunch-check" class="slide level2 smaller">
<h2>🐍 <code>linearize</code> — and a free lunch check</h2>
<div id="linearize-fn" class="cell columns column-output-location" data-execution_count="18">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> linearize(num, den):</span>
<span id="cb24-2"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Per-user linearized ratio metric."""</span></span>
<span id="cb24-3"><a href="" aria-hidden="true" tabindex="-1"></a>    k <span class="op">=</span> num.<span class="bu">sum</span>() <span class="op">/</span> den.<span class="bu">sum</span>()</span>
<span id="cb24-4"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> k <span class="op">+</span> (num <span class="op">-</span> k<span class="op">*</span>den) <span class="op">/</span> den.mean()</span>
<span id="cb24-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">2</span>)</span>
<span id="cb24-7"><a href="" aria-hidden="true" tabindex="-1"></a>o, m <span class="op">=</span> draw_group(<span class="dv">5000</span>, rng)</span>
<span id="cb24-8"><a href="" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> linearize(m, o)</span>
<span id="cb24-9"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"K        : </span><span class="sc">{</span>m<span class="sc">.</span><span class="bu">sum</span>()<span class="op">/</span>o<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.5f}</span><span class="ss">"</span>)</span>
<span id="cb24-11"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"mean(Z)  : </span><span class="sc">{</span>z<span class="sc">.</span>mean()<span class="sc">:.5f}</span><span class="ss">"</span>)</span>
<span id="cb24-12"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"sd(Z)    : </span><span class="sc">{</span>z<span class="sc">.</span>std()<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>K        : 0.20197
mean(Z)  : 0.20197
sd(Z)    : 0.2691</code></pre>
</div>
</div></div>
<div class="fragment">
<p><code>mean(Z)</code> reproduces <span class="math inline">\(K\)</span> <strong>exactly</strong> (not just asymptotically — check the algebra), so the t-test on <span class="math inline">\(Z\)</span> compares the right quantity. And <span class="math inline">\(Z\)</span> is an ordinary per-user column: feed it to <code>ttest_ind</code>, to <code>strat_ttest</code>, to <code>cuped_ttest</code>…</p>
<aside class="notes">
<p>Реалізація — три рядки. Приємний факт для перевірки: середнє Z відтворює K ТОЧНО, не лише асимптотично — підставте формулу й переконайтеся (сума M_i − K·O_i дорівнює нулю за означенням K). Тобто t-тест по Z порівнює саме ту величину, про яку питає PM. І головний бонус: Z — звичайна по-користувацька колонка. Її можна віддати ttest_ind, можна стратифікувати нашим strat_ttest, можна CUPED-ити нашим cuped_ttest із Z за минулий місяць як коваріатою. Лінеаризація вбудовує ratio-метрики в УСЮ машинерію лекції. Лишилось перевірити чесність і швидкість.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="linearization-vs-bootstrap" class="slide level2 smaller">
<h2>🔬 Linearization vs bootstrap</h2>
<div id="mc-lin" class="cell columns column-output-location" data-execution_count="19">
<div class="column">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">9</span>)</span>
<span id="cb26-2"><a href="" aria-hidden="true" tabindex="-1"></a>fpr_lin <span class="op">=</span> agree <span class="op">=</span> pwr_lin <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb26-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(MC_b):</span>
<span id="cb26-5"><a href="" aria-hidden="true" tabindex="-1"></a>    o_a, m_a <span class="op">=</span> draw_group(n_u, rng)</span>
<span id="cb26-6"><a href="" aria-hidden="true" tabindex="-1"></a>    o_b, m_b <span class="op">=</span> draw_group(n_u, rng)</span>
<span id="cb26-7"><a href="" aria-hidden="true" tabindex="-1"></a>    o_t, m_t <span class="op">=</span> draw_group(n_u, rng, lift<span class="op">=</span><span class="fl">1.10</span>)</span>
<span id="cb26-8"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="" aria-hidden="true" tabindex="-1"></a>    pv <span class="op">=</span> ttest_ind(linearize(m_a, o_a), linearize(m_b, o_b),</span>
<span id="cb26-10"><a href="" aria-hidden="true" tabindex="-1"></a>                   equal_var<span class="op">=</span><span class="va">False</span>).pvalue</span>
<span id="cb26-11"><a href="" aria-hidden="true" tabindex="-1"></a>    fpr_lin <span class="op">+=</span> pv <span class="op">&lt;</span> alpha</span>
<span id="cb26-12"><a href="" aria-hidden="true" tabindex="-1"></a>    lo, hi <span class="op">=</span> ratio_bootstrap_ci(o_a, m_a, o_b, m_b, rng)</span>
<span id="cb26-13"><a href="" aria-hidden="true" tabindex="-1"></a>    agree <span class="op">+=</span> (pv <span class="op">&lt;</span> alpha) <span class="op">==</span> ((lo <span class="op">&gt;</span> <span class="dv">0</span>) <span class="op">|</span> (hi <span class="op">&lt;</span> <span class="dv">0</span>))</span>
<span id="cb26-14"><a href="" aria-hidden="true" tabindex="-1"></a>    pwr_lin <span class="op">+=</span> ttest_ind(linearize(m_t, o_t), linearize(m_a, o_a),</span>
<span id="cb26-15"><a href="" aria-hidden="true" tabindex="-1"></a>                         equal_var<span class="op">=</span><span class="va">False</span>).pvalue <span class="op">&lt;</span> alpha</span>
<span id="cb26-16"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-17"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"linearized t A/A FPR:"</span>, wilson(fpr_lin, MC_b))</span>
<span id="cb26-18"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"agrees with bootstrap:"</span>, wilson(agree, MC_b))</span>
<span id="cb26-19"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"linearized t power  :"</span>, wilson(pwr_lin, MC_b))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>linearized t A/A FPR: 0.054  [0.037, 0.077]
agrees with bootstrap: 0.990  [0.977, 0.996]
linearized t power  : 0.612  [0.569, 0.654]</code></pre>
</div>
</div></div>
<div id="lin-timing" class="cell columns column-output-location" data-execution_count="20">
<div class="column">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">4</span>)</span>
<span id="cb28-2"><a href="" aria-hidden="true" tabindex="-1"></a>o_c, m_c <span class="op">=</span> draw_group(<span class="dv">10_000</span>, rng)</span>
<span id="cb28-3"><a href="" aria-hidden="true" tabindex="-1"></a>o_t, m_t <span class="op">=</span> draw_group(<span class="dv">10_000</span>, rng)</span>
<span id="cb28-4"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.time()</span>
<span id="cb28-6"><a href="" aria-hidden="true" tabindex="-1"></a>ratio_bootstrap_ci(o_c, m_c, o_t, m_t, rng, B<span class="op">=</span><span class="dv">10_000</span>)</span>
<span id="cb28-7"><a href="" aria-hidden="true" tabindex="-1"></a>t_boot <span class="op">=</span> time.time() <span class="op">-</span> t0</span>
<span id="cb28-8"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.time()</span>
<span id="cb28-10"><a href="" aria-hidden="true" tabindex="-1"></a>ttest_ind(linearize(m_c, o_c), linearize(m_t, o_t), equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb28-11"><a href="" aria-hidden="true" tabindex="-1"></a>t_lin <span class="op">=</span> time.time() <span class="op">-</span> t0</span>
<span id="cb28-12"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"bootstrap (B=10k) : </span><span class="sc">{</span>t_boot<span class="sc">:.3f}</span><span class="ss"> s"</span>)</span>
<span id="cb28-14"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"linearized t-test : </span><span class="sc">{</span>t_lin<span class="op">*</span><span class="dv">1000</span><span class="sc">:.2f}</span><span class="ss"> ms  "</span></span>
<span id="cb28-15"><a href="" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"(~</span><span class="sc">{</span>t_boot<span class="op">/</span>t_lin<span class="sc">:,.0f}</span><span class="ss">x faster)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>bootstrap (B=10k) : 1.320 s
linearized t-test : 0.85 ms  (~1,561x faster)</code></pre>
</div>
</div></div>
<aside class="notes">
<p>Очна ставка з бутстрепом на тому самому світі. FPR лінеаризованого t-тесту ≈ 0.05 — чесний. Рішення (відхилити/не відхилити) збігаються з бутстрепом майже завжди — на A/A ≈99–100% згоди: це два способи порахувати одне й те саме. Потужність — та сама, що в бутстрепа. А тепер ціна: на 10 000 користувачів бутстреп із B=10 000 — секунди, лінеаризація — мілісекунди, три-чотири порядки швидкості. Для платформи, що жене тисячі метрик щоночі, це різниця між «рахуємо годину» і «рахуємо секунду». Асимптотика проти обчислень: на малих вибірках (сотні користувачів) чесніший бутстреп, на платформних масштабах — лінеаризація без вагань.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="everything-composes" class="slide level2 tiny">
<h2>🔗 Everything composes</h2>
<p>The linearized <span class="math inline">\(Z_i\)</span> is a first-class per-user metric. The lecture’s toolbox stacks:</p>
<div class="cell" data-fig-width="9" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<svg width="864" height="480" viewbox="0.00 0.00 399.60 47.20" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none; display: block; margin: auto auto auto auto">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 43.2)">
<title>compose</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-43.2 395.6,-43.2 395.6,4 -4,4"></polygon>
<!-- raw -->
<g id="node1" class="node">
<title>raw</title>
<path fill="#f5f5f5" stroke="#314f4f" d="M62.74,-39.3C62.74,-39.3 11.75,-39.3 11.75,-39.3 5.75,-39.3 -0.25,-33.3 -0.25,-27.3 -0.25,-27.3 -0.25,-11.9 -0.25,-11.9 -0.25,-5.9 5.75,0.1 11.75,0.1 11.75,0.1 62.74,0.1 62.74,0.1 68.74,0.1 74.74,-5.9 74.74,-11.9 74.74,-11.9 74.74,-27.3 74.74,-27.3 74.74,-33.3 68.74,-39.3 62.74,-39.3"></path>
<text text-anchor="middle" x="37.25" y="-23.5" font-family="Arial" font-size="13.00">(Oᵢ, Mᵢ)</text>
<text text-anchor="middle" x="37.25" y="-7.9" font-family="Arial" font-size="13.00">per user</text>
</g>
<!-- lin -->
<g id="node2" class="node">
<title>lin</title>
<path fill="#f5f5f5" stroke="#314f4f" d="M163.12,-39.3C163.12,-39.3 122.29,-39.3 122.29,-39.3 116.29,-39.3 110.29,-33.3 110.29,-27.3 110.29,-27.3 110.29,-11.9 110.29,-11.9 110.29,-5.9 116.29,0.1 122.29,0.1 122.29,0.1 163.12,0.1 163.12,0.1 169.12,0.1 175.12,-5.9 175.12,-11.9 175.12,-11.9 175.12,-27.3 175.12,-27.3 175.12,-33.3 169.12,-39.3 163.12,-39.3"></path>
<text text-anchor="middle" x="142.7" y="-23.5" font-family="Arial" font-size="13.00">linearize</text>
<text text-anchor="middle" x="142.7" y="-7.9" font-family="Arial" font-size="13.00">→ Zᵢ</text>
</g>
<!-- raw&#45;&gt;lin -->
<g id="edge1" class="edge">
<title>raw-&gt;lin</title>
<path fill="none" stroke="black" d="M74.72,-19.6C82.99,-19.6 91.84,-19.6 100.29,-19.6"></path>
<polygon fill="black" stroke="black" points="100.36,-23.1 110.36,-19.6 100.36,-16.1 100.36,-23.1"></polygon>
</g>
<!-- cuped -->
<g id="node3" class="node">
<title>cuped</title>
<path fill="#f5f5f5" stroke="#314f4f" d="M278.26,-39.3C278.26,-39.3 223.12,-39.3 223.12,-39.3 217.12,-39.3 211.12,-33.3 211.12,-27.3 211.12,-27.3 211.12,-11.9 211.12,-11.9 211.12,-5.9 217.12,0.1 223.12,0.1 223.12,0.1 278.26,0.1 278.26,0.1 284.26,0.1 290.26,-5.9 290.26,-11.9 290.26,-11.9 290.26,-27.3 290.26,-27.3 290.26,-33.3 284.26,-39.3 278.26,-39.3"></path>
<text text-anchor="middle" x="250.69" y="-23.5" font-family="Arial" font-size="13.00">CUPED</text>
<text text-anchor="middle" x="250.69" y="-7.9" font-family="Arial" font-size="13.00">Zᵢ − θXᵢ</text>
</g>
<!-- lin&#45;&gt;cuped -->
<g id="edge2" class="edge">
<title>lin-&gt;cuped</title>
<path fill="none" stroke="black" d="M174.93,-19.6C183,-19.6 191.89,-19.6 200.64,-19.6"></path>
<polygon fill="black" stroke="black" points="200.79,-23.1 210.79,-19.6 200.79,-16.1 200.79,-23.1"></polygon>
</g>
<!-- strat -->
<g id="node4" class="node">
<title>strat</title>
<path fill="#f5f5f5" stroke="#314f4f" d="M379.67,-39.3C379.67,-39.3 338.41,-39.3 338.41,-39.3 332.41,-39.3 326.41,-33.3 326.41,-27.3 326.41,-27.3 326.41,-11.9 326.41,-11.9 326.41,-5.9 332.41,0.1 338.41,0.1 338.41,0.1 379.67,0.1 379.67,0.1 385.67,0.1 391.67,-5.9 391.67,-11.9 391.67,-11.9 391.67,-27.3 391.67,-27.3 391.67,-33.3 385.67,-39.3 379.67,-39.3"></path>
<text text-anchor="middle" x="359.04" y="-23.5" font-family="Arial" font-size="13.00">stratified</text>
<text text-anchor="middle" x="359.04" y="-7.9" font-family="Arial" font-size="13.00">t-test</text>
</g>
<!-- cuped&#45;&gt;strat -->
<g id="edge3" class="edge">
<title>cuped-&gt;strat</title>
<path fill="none" stroke="black" d="M290.38,-19.6C298.74,-19.6 307.62,-19.6 316.1,-19.6"></path>
<polygon fill="black" stroke="black" points="316.18,-23.1 326.18,-19.6 316.18,-16.1 316.18,-23.1"></polygon>
</g>
</g>
</svg>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li>ratio metric → <code>linearize</code> → per-user column;</li>
<li>pre-experiment <span class="math inline">\(Z\)</span> of the same user → <strong>CUPED</strong> covariate;</li>
<li>loyalty stratum → <strong>stratified</strong> weighting of the result.</li>
</ul>
<p>Each step removes its own share of variance; none of them touches the expected difference.</p>
<aside class="notes">
<p>Місток, що зшиває лекцію докупи. Лінеаризована Z — повноцінна по-користувацька метрика, тож конвеєр складається: ratio-метрика → linearize → колонка Z; Z того ж користувача за передекспериментальний період → коваріата для CUPED; статус лояльності → стратифіковане зважування результату. Кожен крок прибирає СВОЮ частку дисперсії: лінеаризація — шум знаменника, CUPED — міжкористувацьку сталу складову, стратифікація — міжстратову. І жоден не чіпає очікувану різницю груп. Саме так це і влаштовано у великих платформах (у Яндекса лінеаризація ratio-метрик + CUPED — стандартний конвеєр). Тепер — обіцяний турнір: скільки кожен метод дає на одному й тому самому світі.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="head-to-head-the-bench" class="title-slide slide level1 center" data-background-iframe=".09-var-reduce_files/libs/colored-particles/index.html">
<h1>Head-to-head: the bench</h1>

</section>
<section id="one-world-four-analyses" class="slide level2 smaller">
<h2>🏟️ One world, four analyses</h2>
<p>Back to the PM’s frozen budget: <span class="math inline">\(n = 1005\)</span> per arm, target effect <strong>5 UAH</strong> — the one our plain design cannot see. The world now contains <strong>both</strong> structures:</p>
<div id="bench-fn" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> draw_arm_full(size, rng, effect<span class="op">=</span><span class="fl">0.0</span>):</span>
<span id="cb30-2"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Loyalty stratum + pre-experiment ARPU (r = 0.7 within stratum)."""</span></span>
<span id="cb30-3"><a href="" aria-hidden="true" tabindex="-1"></a>    reg <span class="op">=</span> rng.random(size) <span class="op">&lt;</span> w_r</span>
<span id="cb30-4"><a href="" aria-hidden="true" tabindex="-1"></a>    mus <span class="op">=</span> np.where(reg, mu_r, mu_u)</span>
<span id="cb30-5"><a href="" aria-hidden="true" tabindex="-1"></a>    x   <span class="op">=</span> mus <span class="op">+</span> sd_w<span class="op">*</span>rng.standard_normal(size)</span>
<span id="cb30-6"><a href="" aria-hidden="true" tabindex="-1"></a>    y   <span class="op">=</span> (mus <span class="op">+</span> r_xy<span class="op">*</span>(x <span class="op">-</span> mus)</span>
<span id="cb30-7"><a href="" aria-hidden="true" tabindex="-1"></a>           <span class="op">+</span> sd_w<span class="op">*</span>np.sqrt(<span class="dv">1</span> <span class="op">-</span> r_xy<span class="op">**</span><span class="dv">2</span>)<span class="op">*</span>rng.standard_normal(size) <span class="op">+</span> effect)</span>
<span id="cb30-8"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> reg, x, y</span>
<span id="cb30-9"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> strat_cuped_ttest(reg_c, x_c, y_c, reg_t, x_t, y_t):</span>
<span id="cb30-11"><a href="" aria-hidden="true" tabindex="-1"></a>    theta <span class="op">=</span> calculate_theta(np.concatenate([x_c, x_t]),</span>
<span id="cb30-12"><a href="" aria-hidden="true" tabindex="-1"></a>                            np.concatenate([y_c, y_t]))</span>
<span id="cb30-13"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> strat_ttest(reg_c, y_c <span class="op">-</span> theta<span class="op">*</span>x_c, reg_t, y_t <span class="op">-</span> theta<span class="op">*</span>x_t)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Four analysts get the same CSV: <strong>plain t</strong> / <strong>stratified</strong> / <strong>CUPED</strong> / <strong>stratified + CUPED</strong>.</p>
<aside class="notes">
<p>Фінальний експеримент лекції. Повертаємось до замороженого бюджету PM: 1005 користувачів на групу і цільовий ефект 5 грн — той, якого наш базовий дизайн не бачить (потужність ~0.26). Світ тепер повний: у користувача є страта лояльності (200/300, sd 62 всередині) І передекспериментальне ARPU з кореляцією 0.7 всередині страти. Зверніть увагу: X корелює з Y двома шляхами — через особисту історію (0.7 всередині страти) і через саму страту (зареєстровані більші за обома координатами). Це реалістично — і зараз дасть повчальний ефект. Четверо аналітиків отримують один CSV: звичайний t-тест, стратифікація, CUPED, стратифікація+CUPED (θ на об’єднаних групах, потім стратифікований тест на резидуалах).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-tournament" class="slide level2 smaller">
<h2>🔬 The tournament</h2>
<div id="mc-bench" class="cell columns column-output-location" data-execution_count="22">
<div class="column">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">17</span>)</span>
<span id="cb31-2"><a href="" aria-hidden="true" tabindex="-1"></a>MC  <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb31-3"><a href="" aria-hidden="true" tabindex="-1"></a>mde_small <span class="op">=</span> <span class="fl">5.0</span></span>
<span id="cb31-4"><a href="" aria-hidden="true" tabindex="-1"></a>cnt <span class="op">=</span> <span class="bu">dict</span>.fromkeys([<span class="st">"plain"</span>, <span class="st">"stratified"</span>, <span class="st">"CUPED"</span>, <span class="st">"strat+CUPED"</span>], <span class="dv">0</span>)</span>
<span id="cb31-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(MC):</span>
<span id="cb31-7"><a href="" aria-hidden="true" tabindex="-1"></a>    rc, xc, yc <span class="op">=</span> draw_arm_full(n, rng)</span>
<span id="cb31-8"><a href="" aria-hidden="true" tabindex="-1"></a>    rt, xt, yt <span class="op">=</span> draw_arm_full(n, rng, effect<span class="op">=</span>mde_small)</span>
<span id="cb31-9"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-10"><a href="" aria-hidden="true" tabindex="-1"></a>    cnt[<span class="st">"plain"</span>]       <span class="op">+=</span> ttest_ind(yc, yt, equal_var<span class="op">=</span><span class="va">False</span>).pvalue <span class="op">&lt;</span> alpha</span>
<span id="cb31-11"><a href="" aria-hidden="true" tabindex="-1"></a>    cnt[<span class="st">"stratified"</span>]  <span class="op">+=</span> strat_ttest(rc, yc, rt, yt) <span class="op">&lt;</span> alpha</span>
<span id="cb31-12"><a href="" aria-hidden="true" tabindex="-1"></a>    cnt[<span class="st">"CUPED"</span>]       <span class="op">+=</span> cuped_ttest(xc, yc, xt, yt) <span class="op">&lt;</span> alpha</span>
<span id="cb31-13"><a href="" aria-hidden="true" tabindex="-1"></a>    cnt[<span class="st">"strat+CUPED"</span>] <span class="op">+=</span> strat_cuped_ttest(rc, xc, yc, rt, xt, yt) <span class="op">&lt;</span> alpha</span>
<span id="cb31-14"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-15"><a href="" aria-hidden="true" tabindex="-1"></a>power   <span class="op">=</span> {k: v<span class="op">/</span>MC <span class="cf">for</span> k, v <span class="kw">in</span> cnt.items()}</span>
<span id="cb31-16"><a href="" aria-hidden="true" tabindex="-1"></a>bands   <span class="op">=</span> {k: proportion_confint(v, MC, method<span class="op">=</span><span class="st">"wilson"</span>) <span class="cf">for</span> k, v <span class="kw">in</span> cnt.items()}</span>
<span id="cb31-17"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> cnt.items():</span>
<span id="cb31-18"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"power </span><span class="sc">{</span>k<span class="sc">:12s}</span><span class="ss">: </span><span class="sc">{</span>wilson(v, MC)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>power plain       : 0.255  [0.229, 0.283]
power stratified  : 0.408  [0.378, 0.439]
power CUPED       : 0.655  [0.625, 0.684]
power strat+CUPED : 0.678  [0.648, 0.706]</code></pre>
</div>
</div></div>
<div id="cell-bench-plot" class="cell" data-execution_count="23">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">3.9</span>))</span>
<span id="cb33-2"><a href="" aria-hidden="true" tabindex="-1"></a>names  <span class="op">=</span> <span class="bu">list</span>(power)</span>
<span id="cb33-3"><a href="" aria-hidden="true" tabindex="-1"></a>vals   <span class="op">=</span> [power[k] <span class="cf">for</span> k <span class="kw">in</span> names]</span>
<span id="cb33-4"><a href="" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [slate, turquoise, red_pink, green]</span>
<span id="cb33-5"><a href="" aria-hidden="true" tabindex="-1"></a>err <span class="op">=</span> np.array([[power[k] <span class="op">-</span> bands[k][<span class="dv">0</span>], bands[k][<span class="dv">1</span>] <span class="op">-</span> power[k]] <span class="cf">for</span> k <span class="kw">in</span> names]).T</span>
<span id="cb33-6"><a href="" aria-hidden="true" tabindex="-1"></a>ax.bar(names, vals, color<span class="op">=</span>colors, alpha<span class="op">=</span><span class="fl">0.9</span>)</span>
<span id="cb33-7"><a href="" aria-hidden="true" tabindex="-1"></a>ax.errorbar(names, vals, yerr<span class="op">=</span>err, fmt<span class="op">=</span><span class="st">"none"</span>, ecolor<span class="op">=</span>navy, capsize<span class="op">=</span><span class="dv">5</span>, lw<span class="op">=</span><span class="fl">1.8</span>)</span>
<span id="cb33-8"><a href="" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="fl">0.8</span>, color<span class="op">=</span>red, lw<span class="op">=</span><span class="dv">2</span>, ls<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="st">"target power 0.8"</span>)</span>
<span id="cb33-9"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"power at MDE = 5 UAH, n = 1005"</span>)</span>
<span id="cb33-10"><a href="" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Same data, same α — four analyses"</span>)</span>
<span id="cb33-11"><a href="" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb33-12"><a href="" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb33-13"><a href="" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src=".09-var-reduce_files/figure-revealjs/bench-plot-output-1.svg" id="bench-plot" class="quarto-figure quarto-figure-center r-stretch"><aside class="notes">
<p>Результати турніру на MDE = 5 грн, n = 1005: звичайний t-тест ≈ 0.26, стратифікація ≈ 0.41, CUPED ≈ 0.66, стратифікація+CUPED ≈ 0.68. Ті самі дані, той самий α — а відстань між найгіршим і найкращим аналізом два з половиною рази. Два уроки з графіка. Перший: найдорожча помилка — взагалі не використовувати додаткову інформацію. Другий, тонший: чому strat+CUPED майже нічого не додав понад CUPED? Бо в цьому світі передекспериментальне ARPU уже «знає» страту користувача: зареєстровані більші і за X, і за Y, тож θ·X виносить міжстратову різницю автоматично. Інформацію не можна порахувати двічі. Звідси практичне правило: додаючи метод чи коваріату, питайте не «чи корелює вона з метрикою», а «скільки НОВОЇ дисперсії вона пояснює понад те, що вже пояснено».</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-bill-in-users" class="slide level2 smaller">
<h2>💰 The bill in users</h2>
<p>Translate residual sd into the sample size the <em>same</em> design would need:</p>
<div id="bench-table" class="cell columns column-output-location" data-execution_count="24">
<div class="column">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="" aria-hidden="true" tabindex="-1"></a>sds <span class="op">=</span> {</span>
<span id="cb34-2"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"plain"</span>:       np.sqrt(sd_w<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> <span class="fl">0.25</span><span class="op">*</span>(mu_r<span class="op">-</span>mu_u)<span class="op">**</span><span class="dv">2</span>),</span>
<span id="cb34-3"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"stratified"</span>:  sd_w,</span>
<span id="cb34-4"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CUPED"</span>:       <span class="va">None</span>,   <span class="co"># measure below</span></span>
<span id="cb34-5"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="st">"strat+CUPED"</span>: sd_w<span class="op">*</span>np.sqrt(<span class="dv">1</span> <span class="op">-</span> r_xy<span class="op">**</span><span class="dv">2</span>),</span>
<span id="cb34-6"><a href="" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb34-7"><a href="" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">21</span>)</span>
<span id="cb34-8"><a href="" aria-hidden="true" tabindex="-1"></a>rc, xc, yc <span class="op">=</span> draw_arm_full(<span class="dv">200_000</span>, rng)</span>
<span id="cb34-9"><a href="" aria-hidden="true" tabindex="-1"></a>theta <span class="op">=</span> calculate_theta(xc, yc)</span>
<span id="cb34-10"><a href="" aria-hidden="true" tabindex="-1"></a>sds[<span class="st">"CUPED"</span>] <span class="op">=</span> (yc <span class="op">-</span> theta<span class="op">*</span>xc).std()</span>
<span id="cb34-11"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-12"><a href="" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"        method | eff. sd |  n per arm (MDE=5)"</span>)</span>
<span id="cb34-13"><a href="" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, sd <span class="kw">in</span> sds.items():</span>
<span id="cb34-14"><a href="" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>k<span class="sc">:&gt;14s}</span><span class="ss"> |   </span><span class="sc">{</span>sd<span class="sc">:5.1f}</span><span class="ss"> | </span><span class="sc">{</span>n_per_arm(sd, mde_small)<span class="sc">:&gt;6d}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>        method | eff. sd |  n per arm (MDE=5)
         plain |    79.6 |   3984
    stratified |    62.0 |   2414
         CUPED |    45.6 |   1308
   strat+CUPED |    44.3 |   1231</code></pre>
</div>
</div></div>
<div class="fragment">
<div class="callout callout-tip no-icon callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>The PM asked to <em>detect 5 UAH with ~1000 users</em>. The plain design needs <span class="math inline">\(\approx 4000\)</span>; strat+CUPED needs <span class="math inline">\(\approx 1200\)</span> — the impossible experiment became a <strong>one-week reality</strong>, with zero extra traffic. That’s the whole lecture in one table.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Той самий турнір мовою грошей. Ефективні sd: 79.6 → 62 → ~46 → 44.3; підставляємо в стару добру формулу розміру вибірки для MDE = 5: ≈3980 → ≈2410 → ≈1320 → ≈1230 користувачів на групу. PM просив «ловити 5 грн на ~1000 користувачів»: базовий дизайн вимагав учетверо більше, а стратифікація+CUPED вкладаються майже в наявний трафік. Неможливий експеримент став тижневою реальністю — без жодного додаткового користувача, лише за рахунок аналізу. Це вся лекція в одній таблиці. Еквівалентне формулювання для звітів: CUPED тут «коштує» як потроєння трафіку. Зверніть увагу, що CUPED і strat+CUPED знову майже нерозрізненні — та сама причина, що й на попередньому слайді.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section></section>
<section>
<section id="the-course-in-one-map" class="title-slide slide level1 center" data-background-iframe=".09-var-reduce_files/libs/colored-particles/index.html">
<h1>The course in one map</h1>

</section>
<section id="which-tool-when" class="slide level2 tiny">
<h2>🗺️ Which tool, when?</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Your situation</th>
<th>Reach for</th>
<th>Watch out for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>one proportion vs a benchmark</td>
<td><strong>binomial test</strong>, Wilson CI</td>
<td>peeking, multiple looks</td>
</tr>
<tr class="even">
<td>two proportions (conversion A/B)</td>
<td><strong>z-test</strong> / <code>proportion_confint</code></td>
<td>tiny <span class="math inline">\(n\)</span>, <span class="math inline">\(\hat p\)</span> near 0/1</td>
</tr>
<tr class="odd">
<td>means of a metric (ARPU, minutes)</td>
<td><strong>t-test</strong> (Welch by default)</td>
<td>heavy skew on small <span class="math inline">\(n\)</span></td>
</tr>
<tr class="even">
<td><em>any</em> criterion before you trust it</td>
<td><strong>Monte Carlo</strong>: simulate FPR &amp; power</td>
<td>Wilson CI on the rates</td>
</tr>
<tr class="odd">
<td>“does the data follow distribution <span class="math inline">\(F\)</span>?”</td>
<td><strong>KS / QQ-plots / GOF</strong></td>
<td>estimated parameters shift the null</td>
</tr>
<tr class="even">
<td>categories × arms (basket tiers)</td>
<td><strong>χ² homogeneity</strong>, Cramér’s V</td>
<td>tiny expected counts; big-<span class="math inline">\(n\)</span> triviality</td>
</tr>
<tr class="odd">
<td>skewed/ordinal, outliers, no means</td>
<td><strong>Mann–Whitney</strong></td>
<td>it tests order, not the mean</td>
</tr>
<tr class="even">
<td>CI for a weird statistic (P75, Gini)</td>
<td><strong>bootstrap</strong> (central CI)</td>
<td>edge quantiles, tiny <span class="math inline">\(n\)</span></td>
</tr>
<tr class="odd">
<td>metric = ratio with per-user structure</td>
<td><strong>user-level bootstrap / linearization</strong></td>
<td>unit of analysis = unit of randomization</td>
</tr>
<tr class="even">
<td>experiment too expensive to power</td>
<td><strong>stratification / CUPED</strong></td>
<td>covariate must be treatment-free</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Карта всього курсу — від першої лекції до сьогоднішньої. Пройдіться рядками: одна частка проти бенчмарка — біноміальний тест та інтервал Уілсона (і пастка підглядання); дві частки — z-тест; середні — t-тест Велча; БУДЬ-ЯКИЙ критерій перед використанням — Монте-Карло-перевірка FPR і потужності; відповідність розподілу — KS і компанія; категорії на групи — χ² з розміром ефекту Крамера і пастками малих очікуваних та величезних n; скошене/порядкове — Манн–Уітні (пам’ятаючи, що він про порядок, не про середнє); дивна статистика — бутстреп; ratio-метрики — сьогоднішні користувацький бутстреп і лінеаризація; дорогий експеримент — сьогоднішні стратифікація і CUPED. Ця таблиця — і є курс. Роздрукуйте, повісьте біля монітора, і половина робочих питань «а який тест» вирішується за десять секунд.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-meta-lessons" class="slide level2 smaller">
<h2>🧠 The meta-lessons</h2>
<p>Four habits worth more than any single test:</p>
<ol type="1">
<li><span class="hi">Validate with Monte Carlo.</span> A method without formulas is not a method without assumptions. Twenty lines of simulation tell you the truth about <em>your</em> data shape — no textbook required.</li>
<li><span class="hi">A confidence interval beats a verdict.</span> “p &lt; 0.05” is one bit; the CI reports direction, size and uncertainty — the things a decision actually needs.</li>
<li><span class="hi">Sensitivity is designed, not rescued.</span> Power lives at the <em>design</em> stage: MDE, <span class="math inline">\(\sigma\)</span>, <span class="math inline">\(n\)</span> — and, since today, variance reduction. Post-hoc “observed power” is a deterministic function of the p-value and carries no new information.</li>
<li><span class="hi">The unit of analysis is the unit of randomization.</span> Sessions inside users, orders inside users — resample and test at the level you randomized.</li>
</ol>
<aside class="notes">
<p>Чотири мета-уроки, що переживуть будь-який конкретний критерій. (1) Валідуйте Монте-Карло: метод без формул — не метод без припущень; двадцять рядків симуляції скажуть правду про ВАШУ форму даних. Ми робили це з t-тестом, KS, χ², Манном–Уітні, бутстрепом і сьогоднішніми методами — це головна професійна звичка курсу. (2) Довірчий інтервал сильніший за вердикт: «p &lt; 0.05» — один біт, а рішенню потрібні напрямок, розмір і невизначеність. (3) Чутливість проєктується, а не рятується: потужність живе на етапі дизайну — MDE, σ, n і, віднині, зниження дисперсії. Пост-хок «спостережена потужність» — детермінована функція p-value, вона не несе жодної нової інформації, женіть її зі звітів. (4) Одиниця аналізу = одиниця рандомізації: сесії всередині користувачів — ресемплimo і тестуємо на рівні, який рандомізували. Хто забере з курсу лише ці чотири звички — уже забере головне.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="where-to-go-next" class="slide level2 smaller">
<h2>🚀 Where to go next</h2>
<p>This course ends where three big roads begin:</p>
<ul>
<li><strong>Causal inference</strong> — what to do when you <em>cannot</em> randomize: difference-in-differences, instrumental variables, regression discontinuity, synthetic control.</li>
<li><strong>Sequential testing</strong> — peeking <em>done right</em>: always-valid p-values, mSPRT, group-sequential designs. (We learned <em>why</em> naive peeking burns <span class="math inline">\(\alpha\)</span>; there is a theory of how to peek legally.)</li>
<li><strong>Heterogeneous effects &amp; uplift</strong> — not “did it work on average?” but “<em>for whom</em> did it work?”: quantile effects you met in the bootstrap lecture, then causal forests and uplift models.</li>
</ul>
<p><br></p>
<center>
<em>Design honestly, simulate before you trust, report intervals — and may your denominators stay still.</em> 🎓
</center>
<aside class="notes">
<p>Куди далі. Три великі дороги, що починаються там, де закінчується цей курс. Перша — казуальний інферанс: що робити, коли рандомізувати НЕ МОЖНА, — difference-in-differences, інструментальні змінні, regression discontinuity, синтетичний контроль. Друга — секвенційне тестування: ми вивчили, ЧОМУ наївне підглядання спалює α, а існує теорія, як підглядати легально — always-valid p-values, mSPRT, групові секвенційні дизайни. Третя — гетерогенні ефекти й uplift: не «чи спрацювало в середньому», а «НА КОМУ спрацювало» — від квантильних ефектів з лекції про бутстреп до causal forests та uplift-моделей. Дякую за семестр. Проєктуйте чесно, симулюйте перед тим як вірити, звітуйте інтервалами — і нехай ваші знаменники стоять на місці.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section id="questions" class="title-slide slide level1 unnumbered unlisted center" data-background-iframe=".09-var-reduce_files/libs/colored-particles/index.html">
<h1>Questions?</h1>
<p><iconify-icon inline="" icon="solar:book-bold"></iconify-icon> <a href="https://teaching.kse.org.ua/course/view.php?id=4049">Course materials</a></p>
<p><iconify-icon inline="" icon="mdi:envelope"></iconify-icon> imiroshnychenko@kse.org.ua</p>
<p><iconify-icon inline="" icon="ic:baseline-telegram"></iconify-icon> <a href="https://t.me/araprof"><span class="citation" data-cites="araprof">@araprof</span></a></p>
<p><iconify-icon inline="" icon="mdi:youtube"></iconify-icon> <a href="https://www.youtube.com/@datamirosh"><span class="citation" data-cites="datamirosh">@datamirosh</span></a></p>
<p><iconify-icon inline="" icon="mdi:linkedin"></iconify-icon> <a href="https://www.linkedin.com/in/ihormiroshnychenko/">@ihormiroshnychenko</a></p>
<p><iconify-icon inline="" icon="mdi:github"></iconify-icon> <a href="https://github.com/Aranaur">@aranaur</a></p>
<p><iconify-icon inline="" icon="ion:home"></iconify-icon> <a href="https://aranaur.rbind.io">aranaur.rbind.io</a></p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="img/kse.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://teaching.kse.org.ua/course/view.php?id=4049">🔗Applied Statistics</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src=".09-var-reduce_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src=".09-var-reduce_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src=".09-var-reduce_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src=".09-var-reduce_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src=".09-var-reduce_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src=".09-var-reduce_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src=".09-var-reduce_files/libs/revealjs/plugin/verticator/verticator.js"></script>
  <script src=".09-var-reduce_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src=".09-var-reduce_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src=".09-var-reduce_files/libs/revealjs/plugin/search/search.js"></script>
  <script src=".09-var-reduce_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src=".09-var-reduce_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'verticator': {"themetag":"h1","color":"","inversecolor":"","skipuncounted":false,"clickable":true,"position":"auto","offset":"3vmin","autogenerate":true,"tooltip":false,"scale":1},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'h.v',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'default',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: true,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: true,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1350,

        height: 759.375,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, Verticator, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>