---
title: "Machine Learning"
author: "Посилання до варіантів"
lang: ua
date: 2024-06-14
date-format: iso
format: html
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(gt)
```

```{r echo=FALSE}
set.seed(20240614)
tibble(
  `ПІБ` = c(
    "Андрущенко Аліна Віталіївна",
    "Василенко Денис Павлович",
    "Верхогляд Анна Сергіївна",
    "Вікторова Ярослава Сергіївна",
    "Зубова Марина Сергіївна",
    "Климов Андрій Андрійович",
    "Коваленко Анастасія Арсеніївна",
    "Миколюк Владислав Русланович",
    "Мороз Данило Вікторович",
    "Настаулова Ольга Володимирівна",
    "Овчинников Ярослав Сергійович",
    "Онуфрієва Єлизавета Володимирівна",
    "Піценко Ірина Ігорівна",
    "Синюк Ростислав Валерійович",
    "Степаненко Юлія Олександрівна",
    "Ткачук Віталій Володимирович",
    "Шклярук Данило Сергійович"
    ),
  `Варіант` = c(sample(1:3, 17, replace = TRUE)
                )
  ) %>% 
  mutate(url = case_when(`Варіант` == 1 ~ "https://forms.office.com/r/yXkVMFhaTe",
                         `Варіант` == 2 ~ "https://forms.office.com/r/EmJpQKT6Ww",
                         `Варіант` == 3 ~ "https://forms.office.com/r/nNntAKncsk"),
         `Варіант` = NULL) %>%
  arrange(`ПІБ`) %>% 
  mutate(url = map(url, ~ htmltools::a(href = .x, "посилання")),
        url = map(url, ~ gt::html(as.character(.x)))) %>%
  gt()
```

