---
title: Лабораторна робота №2
subtitle: Порівняння середніх, t-критерій Стьюдента
---

::: {.callout-note}
Це орієнтовний план лабораторної роботи. Ви можете модифікувати завдання відповідно до ваших потреб та бажань.
:::

# Завдання

1. **Обрання теми:**
    - Оберіть економічну або бізнес-проблему, яка вимагає порівняння середніх значень двох груп. Наприклад, можна обрати середній дохід працівників двох різних компаній, чи середній час обробки замовлень до і після впровадження нової технології.
2. **Формулювання гіпотез:**
    - Сформулюйте нульову ($H_0$) та альтернативну ($H_1$) гіпотези щодо різниці між середніми груп.
3. **Збір даних:**
    - Зберіть дані для обох груп. Можна використовувати реальні дані, якщо вони доступні, або згенерувати випадкові дані для симуляції експерименту.
4. **Обробка даних:**
    - Розрахуйте середні значення, стандартні відхилення та інші необхідні статистичні параметри для обох груп.
5. **Побудова діаграм:**
    - Побудуйте графіки або діаграми, які ілюструють розподіл даних у кожній групі.
6. **Статистичний аналіз:**
    - Використовуючи t-тест, розрахуйте t-статистику та p-значення для порівняння середніх груп.
7. **Непараметричні методи:**
    - Використовуючи непараметричні методи, розрахуйте статистики та p-значення для порівняння середніх груп.
7. **Висновки:**
    - Зробіть висновки щодо статистичної значущості різниці між середніми груп. Прийміть чи відхильте нульову гіпотезу. Розгляньте практичну значущість результатів.

::: {.callout-important}
Напишіть звіт, який включає в себе усі кроки лабораторної роботи та отримані результати. Включіть графіки, таблиці та статистичні обчислення.
:::