---
title: Лабораторна робота №3
subtitle: Аналіз номінативних даних
---

::: {.callout-note}
Це орієнтовний план лабораторної роботи. Ви можете модифікувати завдання відповідно до ваших потреб та бажань.
:::

# Завдання

1. **Збір та створення бази даних:**
    - Обрати тематику дослідження (наприклад, споживчий ринок, галузь виробництва, фінансовий сектор, тощо).
    - Зібрати номінативні дані щодо двох або більше змінних (наприклад, задіяні категорії та їхні характеристики).
2. **$\chi^{2}$ Пірсона:**
    - Використовуючи статистичний критерій $\chi^{2}$ Пірсона, провести аналіз наявності статистично значущих зв'язків між обраними змінними.
    - Розрахувати значення статистики $\chi^{2}$ та визначити ступені свободи.
    - Зробити висновки.
3. **Розподіл частот та побудова таблиць спряженості:**
    - Побудувати таблиці спряженості для обраних змінних та визначити співвідношення між ними.
    - Розрахувати $\chi^{2}$ Пірсона для таблиць спряженості та визначити ступені свободи.
    - Зробити висновки.
4. **Поправка Йетса:**
    - Застосувати поправку Йетса до обчислень для таблиць спряженості з невеликою кількістю спостережень.
    - Порівняти результати з поправкою та без неї та зробити висновки щодо впливу поправки на аналіз.
5. **Підготовка звіту:**
    - Оформити звіт, в якому представити всі етапи аналізу та результати.
    - Пояснити висновки щодо взаємозв'язків між обраними змінними та їхнього економічного змісту.