---
title: Лабораторна робота №4
subtitle: ANOVA
---

::: {.callout-note}
Це орієнтовний план лабораторної роботи. Ви можете модифікувати завдання відповідно до ваших потреб та бажань.
:::

# Завдання

1. **Збір та створення бази даних:**
    - Вибрати конкретну економічну тему для аналізу за допомогою дисперсійного аналізу (ANOVA).
    - Зібрати або симулювати дані, які відповідають обраній темі. Наприклад, дані можуть включати продажі товарів у різних регіонах та за різних умов.
2. **Розрахунок ANOVA:**
    - Виконати розрахунки для дисперсійного аналізу, визначити внутрішньогрупову та міжгрупову дисперсії, ступені свободи, та інші необхідні параметри.
    - Використовуючи відповідні статистичні тести (наприклад, F-тест), визначити, чи є статистично значущі різниці між середніми значеннями в групах.
    - Провести множинні порівняння середніх значень в групах та визначити, чи є статистично значущі різниці між ними.
    - Провести пост-аналіз та зробити висновки (поправка Бонферроні, поправка Холма, тест Тьюки).
4. **Припущення ANOVA:**
    - Перевірити, чи виконуються припущення ANOVA (нормальність розподілу, однорідність дисперсій, незалежність спостережень).
    - Виконати необхідні перетворення даних, якщо припущення не виконуються.
5. **Підготовка звіту:**
    - Оформити звіт, в якому представити всі етапи аналізу та результати.
    - Пояснити висновки щодо взаємозв'язків між обраними змінними та їхнього економічного змісту.