---
title: Лабораторна робота №1
subtitle: Прикладний статистичний аналіз
subject: Статистичний критерій
lang: ua
---

## Завдання

### 1. Моделі та спостереження:

- Опишіть приклад простої статистичної моделі для реального процесу (бізнес-ідея, гра тощо).
- Сформулюйте задачу, яку ви хочете вирішити за допомогою статистичного аналізу.

### 2. Перевірка статистичних гіпотез:

- Сформулюйте нульову та альтернативну гіпотези для процесу (наприклад, монета є симетричною).
- Оберіть критерій перевірки.
- Розрахуйте критичне значення для обраного критерію на рівні значущості 0.05.

### 3. Використання статистичних функцій:

- Напишіть скрипт, який обчислює ймовірність успіху.
- Побудуйте функцію ймовірності та кумулятивну функцію розподілу для цього процесу.
- Знайдіть квантиль для заданого рівня ймовірності (наприклад, 0.95).

### 4. Розрахунок $p$-значення:

- Розрахуйте $p$-значення для перевірки нульової гіпотези.
- Інтерпретуйте отримане значення $p$-значення.

### 5. Двосторонні критерії[^Бонус]:

- Придумайте експеримент, де розподіл випадкової величини не є симетричним і потрібно використовувати двосторонній критерій.
- Напишіть функцію для обчислення $p$-значення для двостороннього тесту.
- Інтерпретуйте результати тесту.

[^Бонус]: Це завдання є додатковим і за нього можна отримати додаткові бали.