---
title: Лабораторна робота №2
subtitle: Прикладний статистичний аналіз
subject: Z-критерій Фішера
lang: ua
---

# Завдання 1

## Чи справді кава допомагає студентам краще здавати іспити?

Опис ситуації: В університеті X поширюється чутка, що кава допомагає студентам покращити результати іспитів. Щоб перевірити це твердження, група дослідників вирішила провести експеримент. Вони запросили ❓[^1] студентів і поділили їх на дві групи по ❓ осіб:

- Група 1 (контрольна): не вживала кави.
- Група 2 (експериментальна): випивала по чашці кави перед іспитом.

Після іспиту обидві групи написали тест, середній бал якого у контрольній групі був ❓ балів (з відомим стандартним відхиленням ❓), а в експериментальній групі — ❓ балів.

## Завдання:

1. Розробіть та перевірте гіпотезу.
2. Обчисліть значення $Z$-критерію для даних контрольної та експериментальної груп.
3. Візуалізуйте розподіл: Побудуйте нормальний розподіл з відміченими критичними значеннями для рівня значущості 0.05, та позначте отримане $Z$-значення.
4. Аналізуйте результати: Чи можемо ми відкинути нульову гіпотезу? Що це означає в контексті експерименту? Напишіть висновок, який можна було б розмістити на дошці оголошень університету, щоб студенти зрозуміли результати.

[^1]: ❓ --- випадкова величина, яку необхідно згенерувати самостійно. Не забувайте зафіксувати `seed` для відтворюваності результатів.

# Завдання 2

Відомо, що генеральна сукупність усіх балів тесту має стандартне відхилення 8.5. Факультет сподівається прийняти абітурієнтів з балами вище 210. Цього року середній бал тесту для 42 абітурієнтів склав 212.79 балів. Чи при значенні $\alpha = 0.05$ це нове середнє значення є значно більшим за бажане середнє значення 210?

# Завдання 3

Припустимо, ви заснували компанію, яка розробила ліки, що мають підвищувати IQ. Ви знаєте, що стандартне відхилення IQ у генеральній сукупності становить 15. Ви тестуєте свій препарат на 36 пацієнтах і отримуєте середній показник IQ 97.65. Використовуючи значення $\alpha = 0.05$, чи суттєво відрізняється цей показник IQ від середнього значення в популяції, яке дорівнює 100?