---
title: Лабораторна робота №6
subtitle: Прикладний статистичний аналіз
subject: Хі-квадрат
lang: ua
---

## Завдання

Вчені провели дослідження, в якому вивчали зв'язок між споживанням кофеїновмісної кави та ризиком виникнення депресії у жінок. Вони зібрали дані про 50 739 жінок, які не мали симптомів депресії на початку дослідження в 1996 році, і спостерігали за цими жінками до 2006 р. Дослідники використовували анкети для збору даних про споживання кофеїновмісної кави, запитували кожну жінку про діагностовану лікарем депресію, а також про вживання антидепресантів. У таблиці нижче наведено розподіл випадків депресії залежно від кількості спожитої кофеїновмісної кави.

| |$$<= 1 $$ cup/week|$$2-6 $$ cup/week|$$1 $$ cup/day|$$2-3$$ cup/day|$$>= 4$$ cup/day|Total
|---|---|---|---|---|---|---|
|Yes|670|373|905|564|95|2607|
|No|11545|6244|16329|11726|2288|48132|
|Total|12215|6617|17234|12290|2383|50739|

1. Сформулюйте нульову та альтернативну гіпотези.
2. Розрахуйте кількісні характеристики для кожної групи.
3. Перевірте гіпотезу про рівність розподілу в групах за допомогою критерію хі-квадрат.
4. Які висновки можна зробити на основі результатів аналізу?
5. Один з авторів цього дослідження був процитований в NYTimes як такий, що сказав, що було «занадто рано рекомендувати жінкам вживати додаткову каву», базуючись лише на цьому дослідженні[^foot]. Чи погоджуєтесь ви з цим твердженням? Поясніть свої міркування.

[^foot]: Anahad O'Connor. [Coffee Drinking Linked to Less Depression in Women](https://archive.nytimes.com/well.blogs.nytimes.com/2011/09/26/coffee-drinking-linked-to-less-depression-in-women/). In: New York Times (2011).

