---
title: "AE 01: Welcome to R"
subtitle: "Descriptive Statistics"
author: "Ihor Miroshnychenko"
institute: Kyiv School of Economics
format:
  html: 
    highlight-style: github
    theme: [default, custom.scss]
execute: 
  echo: true
  warning: false
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup
#| include: false

library(tidyverse)

# Define colors
red_pink   = "#e64173"
turquoise  = "#20B2AA"
orange     = "#FFA500"
red        = "#fb6107"
blue       = "#181485"
navy       = "#150E37FF"
green      = "#8bb174"
yellow     = "#D8BD44"
purple     = "#6A5ACD"
slate      = "#314f4f"
```

1. Compute  $\frac{75 + 5}{(2 \times 3)^5}$ and assign the name `calculation` to the result. Print `calculation` to the console.

2. Define a vector `months` containing the numbers `29`, `63`, `7`, `23`, `84`, `10` and `9`. Compute a vector `years` from it by dividing `months` by `12`. Print `years` to the console.

3. Create a function[^function] `circle_area()` that calculates the area of a circle by radius according to the formula $S = \pi r^2$. Test the function with radius `5`.

4. Create a list `my_list` with the following components:
    - `name` with your name,
    - `age` with your age,
    - `city` with the name of your city,
    - `is_student` with `TRUE` if you are a student and `FALSE` otherwise.
   
    Print your `city` from the list to the console.

5. Create a data frame using the following information about solar system planets from the table below:

| Planet | Diameter (km) | Rings | Moons | Mean Temperature (C) |
|--------|---------------|-------|-------|----------------------|
| Mercury | 4879 | False | 0 | 167 |
| Venus | 12104 | False | 0 | 464 |
| Earth | 12756 | False | 1 | 15 |
| Mars | 6792 | False | 2 | -65 |
| Jupiter | 142984 | True | 95 | -110 |
| Saturn | 120536 | True | 146 | -140 |
| Uranus | 51118 | True | 28 | -195 |
| Neptune | 49528 | True | 16 | -200 |

: [Planetary Fact Sheet](https://nssdc.gsfc.nasa.gov/planetary/factsheet/) {#tbl-solar}

6. Compare the diameter of the planets with the diameter of Earth. Print the result to the console.

[^function]: More on functions in R: [R for Data Science: Functions](https://r4ds.hadley.nz/functions)