---
title: "Lab 3"
subtitle: "Descriptive Statistics"
author: "Ihor Miroshnychenko"
institute: Kyiv School of Economics
format:
  html: 
    highlight-style: github
    theme: [default, custom.scss]
    toc: true
    toc-depth: 2
execute: 
  echo: true
  warning: false
editor_options: 
  chunk_output_type: console
---

# Part 1: IMS Exercises

The exercises in this section do not require code. Make sure to answer the questions in full sentences.

## Exercise 1 

::: border
IMS - [Chapter 11 exercises](https://openintro-ims.netlify.app/foundations-randomization#sec-chp11-exercises), #2: Identify the parameter, II.
:::

## Exercise 2

::: border
IMS - [Chapter 11 exercises](https://openintro-ims.netlify.app/foundations-randomization#sec-chp11-exercises), #6: Identify hypotheses, II.
:::

# Part 2: Paul the Octopus

## Exercise 1

[Octopus Paul](https://en.wikipedia.org/wiki/Paul_the_Octopus) tried 14 times to guess the winner of a soccer match. 12 times he guessed correctly, 2 times he guessed wrong. We want to test a hypothesis:

 - $H_0$: the octopus guesses the winner of the match with probability 0.5
 - $H_1$: the octopus picks the winner of the match with probability $\neq$ 0.5

You must develop a statistical criterion to test this hypothesis and calculate the $p$-value.

- $H_0: p = 0.5$
- $H_1: p \neq 0.5$
- $S(X) = \sum\limits_{i=1}^n X_i \sim Binom(n, 0.5)$ if hypothesis $H_0$ is true.  
- Criterion: $\bigl\{ S(X) \gt u_{1-\frac{\alpha}{2}} \bigr\} \cup \bigl\{ S(X) \lt u_{\frac{\alpha}{2}} \bigr\}$, where $u_{\beta}$ is the critical value equal to the $\beta$-quantile of $Binom(n, 0.5)$,  
- $p$-value = $2 \cdot \text{min}\bigl[P\bigl( S(X) \geqslant S_0 \, \, H_0\bigr), \, P\bigl( S(X) \leqslant S_0 \, \, H_0\bigr), \, P\bigl( S(X) \leqslant S_0 \, \, H_0\bigr)) \bigr]$, where $S_0$ is the value of a statistic from a given sample.

::: border

Implement the `check_paul_criterion(n, k, alpha)` function, where:

- `n` &mdash; the number of matches;
- `k` &mdash; the number of correct predictions from the octopus;
- `alpha` &mdash; the significance level of the criterion.

The function should return `PaulCheckResults` with the fields:

- `is_rejected`: whether or not hypothesis $H_0$ was rejected at significance level $\alpha$
- `pvalue`: the $p$-value of the test

:::

## Exercise 2

::: border
What conclusions can be drawn from the result obtained in Exercise 1?
:::

## Exercise 3

::: border
Determine the criterion's critical region for a given number of matches and a given significance level.

Visualize the critical region of the criterion.
:::

## Exercise 4

::: border
Construct a confidence interval for the probability of the octopus guessing the winner of the match.
:::

# Grading

- **Submission of Lab Report:** A complete and accurate submission of the lab assignment in the required format [(2 point)]{.hi}.
- **Understanding of Code and Correct Use of Methods:** Evaluation of your understanding of the code you submit and the appropriateness of the methods used in your solution [(4 point)]{.hi}.
- **Verbal Defense of the Lab:** An oral explanation of your solution to verify your understanding of the concepts and methods used. You may be asked to explain the logic of your code, the interpretation of results, or to make minor modifications to your solution during the defense [(4 point)]{.hi}.