---
title: "Lab 4"
subtitle: "Descriptive Statistics"
author: "Ihor Miroshnychenko"
institute: Kyiv School of Economics
format:
  html: 
    highlight-style: github
    theme: [default, custom.scss]
    toc: true
    toc-depth: 2
execute: 
  echo: true
  warning: false
editor_options: 
  chunk_output_type: console
---

# Pizza Delivery

Imagine you work as an analyst for a giant pizza delivery company on a courier app (yes, these companies usually have an app for couriers and a separate app for consumers).

You have several restaurants in different parts of the city and a whole staff of couriers. But there is one problem - the delivery speed drops by the evening because the couriers go home after working hours, and the number of orders only increases. This leads to the fact that our delivery is very much down in efficiency at the time of shift change. 

Our data scientists have developed a new algorithm that allows couriers to schedule their last orders before the end of the workday so that their delivery route matches their route home. That is so that the couriers deliver their previous orders of the day as if they were “on their way” home. 

You and your team decided to run an A/B test on two equal groups of couriers. Some couriers use the old algorithm without the “on the way” option, while others see this option in their app and can choose it. Your task is to analyze the data from the experiment and help the business decide whether to roll out the new feature to all couriers.

## Data Description

You can find the data in the [link](https://aranaur.rbind.io/datasets/ab_experiment/). The dataset contains the following columns:

* `order_id` --- order id
* `delivery_time` --- delivery time in minutes
* `district` --- delivery area
* `experiment_group` --- experimental group

::: {.callout-note}
Don't forget to visualize - it allows you to better interpret the results.
:::

## Exercise 1

::: border
First, let's formulate hypotheses to test. Select the statistical hypotheses that we can test in this experiment.
:::

## Exercise 2

::: border
Construct distribution plots and experimental groups' delivery time statistics. What can you say about the data?
:::

## Exercise 3

::: border
Count the number of observations in the test and control groups. How much does the number of observations in the test and control differ modulo?
:::

## Exercise 4

::: border
Calculate the average delivery time for the test and control groups. What can you say about the data?
:::

## Exercise 5

::: border
Calculate the standard deviation of delivery time for the test and control groups. What can you say about the data?
:::

## Exercise 6

::: border
Now it is time to compare the averages in the test and control. Use the t-test to test the hypothesis that the average delivery time in the test group is equal to the average delivery time in the control group. What can you say about the data?
:::

## Exercise 7

::: border
Calculate the 95% confidence interval for the difference in the average delivery time between the test and control groups. What can you say about the data?
:::

## Exercise 8

::: border
Calculate the power of the test for the difference in the average delivery time between the test and control groups. What can you say about the data?
:::

## Exercise 9

::: border
What conclusions can be drawn from the results of the A/B test?
:::

# Grading

- **Submission of Lab Report:** A complete and accurate submission of the lab assignment in the required format [(2 point)]{.hi}.
- **Understanding of Code and Correct Use of Methods:** Evaluation of your understanding of the code you submit and the appropriateness of the methods used in your solution [(4 point)]{.hi}.
- **Verbal Defense of the Lab:** An oral explanation of your solution to verify your understanding of the concepts and methods used. You may be asked to explain the logic of your code, the interpretation of results, or to make minor modifications to your solution during the defense [(4 point)]{.hi}.