---
title: "Project 1"
subtitle: "Descriptive Statistics"
author: "Ihor Miroshnychenko"
institute: Kyiv School of Economics
format:
  html: 
    highlight-style: github
    theme: [default, custom.scss]
    toc: true
    toc-depth: 2
execute: 
  echo: true
  warning: false
editor_options: 
  chunk_output_type: console
---

# Goals

The goals of this project are as follows:

- Discuss topics you’re interested in investigating and find data sets on those topics.
- Identify 3 data sets you’re interested in potentially using for the project.
- Get these datasets into R.
- Write up reasons and justifications for why you want to work with these datasets.


# Finding a dataset

## Criteria for datasets

The data sets should meet the following criteria:

- At least 500 observations
- At least 8 columns
- At least 6 of the columns must be useful and unique explanatory variables.
  + Identifier variables such as “name”, “social security number”, etc. are not useful explanatory variables.
  + If you have multiple columns with the same information (e.g. “state abbreviation” and “state name”), then they are not unique explanatory variables.
- You may not use data that has previously been used in any course materials, or any derivation of data that has been used in course materials.
- You can use web scraping to get data from the web.

If you set your hearts on a dataset that has fewer observations or variables than what’s suggested here, that might still be ok; use these numbers as guidance for a successful proposal, not as minimum requirements.

## Resources for datasets

You can find data wherever you like, but here are some recommendations to get you started. You shouldn’t feel constrained to datasets that are already in a tidy format, you can start with data that needs cleaning and tidying, scrape data off the web, or collect your own data.

-   [Awesome public datasets](https://github.com/awesomedata/awesome-public-datasets)
-   [CDC](https://www.cdc.gov/datastatistics/)
-   [Data.gov](https://www.data.gov/)
-   [Data is Plural](https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit#gid=0)
-   [Durham Open Data Portal](https://live-durhamnc.opendata.arcgis.com/)
-   [Election Studies](https://electionstudies.org//)
-   [European Statistics](https://ec.europa.eu/eurostat/)
-   [Google Dataset Search](https://datasetsearch.research.google.com/)
-   [Harvard Dataverse](https://dataverse.harvard.edu/)
-   [International Monetary Fund](https://data.imf.org/?sk=388DFA60-1D26-4ADE-B505-A05A558D9A42&sId=1479329328660)
-   [IPUMS survey data from around the world](https://ipums.org/)
-   [Los Angeles Open Data](https://data.lacity.org/browse)
-   [NHS Scotland Open Data](https://www.opendata.nhs.scot/)
-   [NYC OpenData](https://opendata.cityofnewyork.us/)
-   [Open access to Scotland's official statistics](https://statistics.gov.scot/home)
-   [Pew Research](https://www.pewresearch.org/download-datasets/)
-   [PRISM Data Archive Project](https://www.icpsr.umich.edu/icpsrweb/content/ICPSR/fenway.html)
-   [Statistics Canada](https://www.statcan.gc.ca/en/start)
-   [TidyTuesday](https://github.com/rfordatascience/tidytuesday)
-   [The National Bureau of Economic Research](https://www.nber.org/research/data?page=1&perPage=50)
-   [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php)
-   [UK Government Data](https://data.gov.uk/)
-   [UNICEF Data](https://data.unicef.org/)
-   [United Nations Data](http://data.un.org/)
-   [United Nations Statistics Division](https://unstats.un.org/UNSDWebsite/)
-   [World Bank Data](https://datacatalog.worldbank.org/home)
-   [Youth Risk Behavior Surveillance System (YRBSS)](https://chronicdata.cdc.gov/Youth-Risk-Behaviors/DASH-Youth-Risk-Behavior-Surveillance-System-YRBSS/q6p7-56au)
-   [FRED Economic Data](https://fred.stlouisfed.org/)

# Components

For each data set, include the following:

## Introduction and data

For each data set:

- Identify the source of the data.
- State when and how it was originally collected (by the original data curator, not necessarily how you found the data).
- Write a brief description of the observations.
- Address ethical concerns about the data, if any.

## Research question

Your research question should contain at least three variables, and should be a mix of categorical and quantitative variables. When writing a research question, please think about the following:

- What is your target population?
- Is the question original?
- Can the question be answered?

For each data set, include the following:

- A well formulated research question. (You may include more than one research question if you want to receive feedback on different ideas for your project. However, one per data set is required.)
- Statement on why this question is important.
- A description of the research topic along with a concise statement of your hypotheses on this topic.
- Identify the types of variables in your research question. Categorical? Quantitative?

## Glimpse of data

For each data set:

- Place the file containing your data in the data folder of the project.
- Use the `glimpse()` function to provide a glimpse of the data set.

## Data cleaning

For each data set:

- Describe the data cleaning steps you will need to take to get the data into a tidy format.
- Describe any missing data and how you plan to handle it.

## Data visualization

For each data set:

- Create a visualization of the data.
- Describe the visualization.
- Explain why you chose this visualization.

::: {.callout-important}
Communicating your vision of the data set through visualization is very important. Make sure to choose a visualization that best represents the data set and the research question you are trying to answer.
:::

# Submission

Use Quarto to create a report that includes the components listed above.

Submit your project as a single PDF/DOCX file or host your HTML file on [Quartopub](https://quartopub.com/) or any other platform of your choice.

You can create presentations, dashboards, or any other type of visualization to support your project. However, the main submission should be a written report.

# Grading

1. **Preparation**: Accuracy in data preparation and preprocessing for analysis, considering the specifics of the data set.
2. **Visualization of Results**: Quality of visualizations, readability of graphs, and correctness in representing the data.
3. **Interpretation of Results**: Correct interpretation of the results, including the ability to explain the data set and the results obtained.
4. **Report Quality**: Clarity and structure of the report, well-formulated conclusions, references to sources, and adherence to ethical guidelines.
5. **Team Participation**: Active participation in the project, including the ability to explain the data set and the results obtained.

**Total points:** 25

