---
title: "Lab 5: 👶 Infant Heart Study"
subtitle: "Applied Statistics"
affiliation: "Kyiv School of Economics"
format: 
  html: default
toc: true
number-sections: true
echo: false

---

```{r}
#| label: setup
#| include: false

red_pink   = "#e64173"
turquoise  = "#20B2AA"
orange     = "#FFA500"
red        = "#fb6107"
blue       = "#181485"
navy       = "#150E37FF"
green      = "#8bb174"
yellow     = "#D8BD44"
purple     = "#6A5ACD"
slate      = "#314f4f"
```

::: {.callout-note}
This is just one possible scenario. You can design your own hypothesis and compare other groups or distributions.
:::

## 🎯 Context

The data below contains the results of a randomized experiment conducted by surgeons at Harvard Medical School to compare "low-flow bypass" and "circulatory arrest" surgical procedures in the treatment of infants born with congenital heart defects. 

The study’s recorded outcomes are Psychomotor Development Index (`PDI`), a composite score measuring physiological development, with higher scores indicating greater development, and Mental Development Index (`MDI`), a composite score measuring mental development, with higher scores indicating greater development.

Dataset also includes:

- `Weight`: the weight of the infant at the time of the procedure.
- `Length`: the length of the infant at the time of the procedure.
- `Age`: the age of the infant at the time of the procedure
- `Sex`: the sex of the infant (male or female)

## 🧪 Goal

Your task is to analyze the data and determine whether there is a statistically significant difference in the PDI and MDI scores between the two surgical procedures.

## 👣 Steps

1. Load the data from the provided CSV file ([`infant_heart_study.csv`](data/infant_heart_study.csv)).
2. Perform exploratory data analysis (EDA) to understand the distribution of the PDI and MDI scores, as well as the characteristics of the infants in the study.
3. Formulate hypotheses to test whether there is a significant difference in the PDI and MDI scores between the two surgical procedures.
4. Use appropriate statistical tests to evaluate your hypotheses (I expect you to use bootstrapping, but you can also use other methods if you prefer).

::: {.callout-note}
You may be interested in exploring not only the differences in average values, but also the percentiles of the distributions, as well as the differences in the distributions themselves.
:::

5. Visualize the results of your analysis, including any relevant graphs or charts.
6. Write a short interpretation of your findings, including any limitations or considerations for future research.


## 📝 Result
Laboratory report in PDF/HTML[^html] format with:

- Code
- Graphs
- Hypotheses and decisions
- Short written interpretation

[^html]: If you choose HTML, please host it via GitHub Pages or similar service. You can use the `quarto publish` command to publish your report.