---
title: "Lab 6: 🧪 A/B Test Analysis"
subtitle: "Applied Statistics"
affiliation: "Kyiv School of Economics"
format: 
  html: default
toc: true
number-sections: true
echo: false

---

```{r}
#| label: setup
#| include: false

red_pink   = "#e64173"
turquoise  = "#20B2AA"
orange     = "#FFA500"
red        = "#fb6107"
blue       = "#181485"
navy       = "#150E37FF"
green      = "#8bb174"
yellow     = "#D8BD44"
purple     = "#6A5ACD"
slate      = "#314f4f"
```

::: {.callout-note}
This is just one possible scenario. You can design your own hypothesis and compare other groups or distributions.
:::

## 🎯 Context

We want to conduct an A/B test with two groups: a control group and a test group.

There is a key metric, CTR (clicks/views), and historical data for it:

- File `history_control.csv` --- data for when there were no A/B tests; we can assume that the metric is very stable.
- File `history_old_ab.csv` --- indicators for the test group of the previous A/B test, where CTR fell by 15%.

In an A/B test, we want to record a statistically significant 10% increase in CTR. The acceptable I type of error is 5%, and the II type of error is 20%.

1. Calculate the sample size required in each group if the control group contains 90% of users and the test group contains 10%.
2. We conducted the test and obtained the results (file `results.csv`, one row per user, no duplicate users). Calculate the $p$-value.
3. Based on the $p$-value, make a decision about the hypothesis.

## 🧪 Goal

Your task is to analyze the data and determine whether there is a statistically significant difference in the CTR between the control and test groups.

## 👣 Steps

1. Load the data from the provided CSV files (`history_control.csv`, `history_old_ab.csv`, and `results.csv`).
2. Perform exploratory data analysis (EDA) to understand the distribution of CTR in both groups.
3. Formulate hypotheses to test whether there is a significant difference in CTR between the control and test groups.
4. Use appropriate statistical tests to evaluate your hypotheses (I expect you to use bootstrapping, but you can also use other methods if you prefer).

## 📊 Data

- [`history_control.csv`](data/history_control.csv) --- historical data for the control group.
- [`history_old_ab.csv`](data/history_old_ab.csv) --- historical data for the test group of the previous A/B test.
- [`results.csv`](data/results.csv) --- results of the current A/B test.

## 📝 Result
Laboratory report in PDF/HTML[^html] format with:

- Code
- Graphs

- Hypotheses and decisions
- Short written interpretation

[^html]: If you choose HTML, please host it via GitHub Pages or similar service. You can use the `quarto publish` command to publish your report.