---
title: "Python: умовні оператори та цикли"
title-slide-attributes:
    data-background-iframe: colored-particles/index.html
subtitle: "Прикладна аналітика при розробці IT"
author: "Ігор Мірошниченко"
footer: <a href="https://aranaur.rbind.io/lectures/applied_analytics/">Прикладна аналітика при розробці IT</a>
# date: today
# date-format: iso
institute: КНУ імені Тараса Шевченка, ФІТ
language: _language-ua.yml
format:
  revealjs: 
    theme: [simple, custom.scss]
    logo: fit.png
    chalkboard: true
    slide-number: true
    toc: true
    toc-title: ЗМІСТ
    transition: fade
    mouse-wheel: true
    highlight-style: github
    mainfont: metropolis
    toc-depth: 1
    fig-width: 9
    fig-height: 5
  gfm:
    mermaid-format: png
    
preload-iframes: true
from: markdown+emoji

execute: 
  echo: true

jupyter: python3
        
# knitr: 
#   opts_chunk: 
#     echo: true
#     warnings: false
#     message: false
editor_options: 
  chunk_output_type: console
---

# Умовні оператори {background-iframe="colored-particles/index.html"}

## Оператори порівняння {.smaller}

- `x < y`:      `x` строго менше `y`,
- `x <= y`:     `x` менше або дорівнює `y`,
- `x > y`:      `x` строго більше `y`,
- `x >= y`:     `x` більше або дорівнює `y`,
- `x == y `:    `x` дорівнює `y`,
- `x != y`:     `x` не дорівнює `y`.

Для того, щоб ставити запитання з використанням цих символів нам знадобиться ще одне ключове слово в Python. І це ключове слово, досить просто, як і в англійській мові - `if`:

```{python}
#| eval: false

x = int(input('Введіть число x: ')) # 1
y = int(input('Введіть число y: ')) # 2

if x < y:
    print('x менше y')
if x > y:
    print('x більше y')
if x == y:
    print('x дорівнює y')
```

```{python}
#| echo: false

x = 1
y = 2

if x < y:
    print('x менше y')
if x > y:
    print('x більше y')
if x == y:
    print('x дорівнює y')
```

## Візуалізація коду

:::: {.columns}

::: {.column width="50%"}
```{python}
#| eval: false

x = int(input('Введіть число x: ')) # 1
y = int(input('Введіть число y: ')) # 2

if x < y:
    print('x менше y')
if x > y:
    print('x більше y')
if x == y:
    print('x дорівнює y')
```
:::

::: {.column width="50%"}
```{mermaid}
%%| echo: false
%%| fig-height: 6.5
%%{init:{"theme":"base", "flowchart": {"htmlLabels": true}}}%%

flowchart TB
    A(Початок) --> B{x < y}
    B -- True --> C["'x менше y'"]
    C --> D{x > y}
    B -- False --> D
    D -- True --> E["'x більше y'"]
    E --> F{x == y}
    D -- False --> F
    F -- True --> G["'x дорівнює y'"]
    G --> H(Кінець)
    F -- False --> H
```
:::

::::

## `elif`

Попередній код виконує свою задачу, але він не є найкращим. Якщо ви помітите, ми використовуємо три окремі запитання, щоб визначити, яке з двох чисел є більшим. Це можна зробити краще, використовуючи ключове слово `elif`.

`elif` - це скорочення від `else if`.

```{python}
#| eval: false

x = int(input('Введіть число x: ')) # 1
y = int(input('Введіть число y: ')) # 2

if x < y:
    print('x менше y')
elif x > y:
    print('x більше y')
elif x == y:
    print('x дорівнює y')
```

```{python}
#| echo: false

x = 1
y = 2

if x < y:
    print('x менше y')
elif x > y:
    print('x більше y')
elif x == y:
    print('x дорівнює y')
```

## Візуалізація коду

:::: {.columns}

::: {.column width="50%"}
```{python}
#| eval: false

x = int(input('Введіть число x: ')) # 1
y = int(input('Введіть число y: ')) # 2

if x < y:
    print('x менше y')
elif x > y:
    print('x більше y')
elif x == y:
    print('x дорівнює y')
```
:::

::: {.column width="50%"}
```{mermaid}
%%| echo: false
%%| fig-height: 6.5
%%{init:{"theme":"base", "flowchart": {"htmlLabels": true}}}%%

flowchart TB
    A(Початок) --> B{x < y}
    B -- True --> C["'x менше y'"]
    C --> H(Кінець)
    B -- False --> D{x > y}
    D -- True --> E["'x більше y'"]
    E --> H
    D -- False --> F{x == y}
    F -- True --> G["'x дорівнює y'"]
    G --> H
    F -- False --> H
```
:::

::::

## `else`

Чи є сенс задавати третє, останнє питання `x == y`? Напевно ні.

І тут нам на допомогу приходить ключове слово `else`.

```{python}
#| eval: false

x = int(input('Введіть число x: ')) # 1
y = int(input('Введіть число y: ')) # 1

if x < y:
    print('x менше y')
elif x > y:
    print('x більше y')
else:
    print('x дорівнює y')
```

```{python}
#| echo: false

x = 1
y = 1

if x < y:
    print('x менше y')
elif x > y:
    print('x більше y')
else:
    print('x дорівнює y')
```

## Візуалізація коду

:::: {.columns}

::: {.column width="50%"}
```{python}
#| eval: false

x = int(input('Введіть число x: ')) # 1
y = int(input('Введіть число y: ')) # 1

if x < y:
    print('x менше y')
elif x > y:
    print('x більше y')
else:
    print('x дорівнює y')
```
:::

::: {.column width="50%"}
```{mermaid}
%%| echo: false
%%| fig-height: 6.5
%%{init:{"theme":"base", "flowchart": {"htmlLabels": true}}}%%

flowchart TB
    A(Початок) --> B{x < y}
    B -- True --> C["'x менше y'"]
    C --> H(Кінець)
    B -- False --> D{x > y}
    D -- True --> E["'x більше y'"]
    E --> H
    D -- False --> F["'x дорівнює y'"]
    F --> H
```
:::

::::

## Логічний оператор `or`

Цього разу перевіримо, чи дорівнює `x` числу `y`. Для цього використаємо оператори `or`:

```{python}
#| eval: false

x = int(input('Введіть число x: ')) # 1
y = int(input('Введіть число y: ')) # 2

if x < y or x > y:
    print('x не дорівнює y')
else:
    print('x дорівнює y')
```

```{python}
#| echo: false

x = 1
y = 2

if x < y or x > y:
    print('x не дорівнює y')
else:
    print('x дорівнює y')
```

## Візуалізація коду

:::: {.columns}

::: {.column width="50%"}
```{python}
#| eval: false

x = int(input('Введіть число x: ')) # 1
y = int(input('Введіть число y: ')) # 2

if x < y or x > y:
    print('x не дорівнює y')
else:
    print('x дорівнює y')
```
:::

::: {.column width="50%"}
```{mermaid}
%%| echo: false
%%| fig-height: 6.5
%%{init:{"theme":"base", "flowchart": {"htmlLabels": true}}}%%

flowchart TB
    A(Початок) --> B{x < y}
    B -- True --> C["'x не дорівнює y'"]
    C --> H(Кінець)
    B -- False --> D{x > y}
    D -- True --> C
    D -- False --> F["'x дорівнює y'"]
    F --> H
```
:::

::::

## Логічний оператор `or`

Чи можемо ми покращити цей код? Так, за допомогою оператора заперечення `!=`:

```{python}
#| eval: false

x = int(input('Введіть число x: ')) # 1
y = int(input('Введіть число y: ')) # 2

if x != y:
    print('x не дорівнює y')
else:
    print('x дорівнює y')
```

```{python}
#| echo: false

x = 1
y = 2

if x != y:
    print('x не дорівнює y')
else:
    print('x дорівнює y')
```

## Візуалізація коду

:::: {.columns}

::: {.column width="50%"}
```{python}
#| eval: false

x = int(input('Введіть число x: ')) # 1
y = int(input('Введіть число y: ')) # 2

if x != y:
    print('x не дорівнює y')
else:
    print('x дорівнює y')
```
:::

::: {.column width="50%"}
```{mermaid}
%%| echo: false
%%| fig-height: 6.5
%%{init:{"theme":"base", "flowchart": {"htmlLabels": true}}}%%

flowchart TB
    A(Початок) --> B{x != y}
    B -- True --> C["'x не дорівнює y'"]
    C --> H(Кінець)
    B -- False --> D["'x дорівнює y'"]
    D --> H
```
:::

::::

## Логічний оператор `and`

Цей оператор дозволяє нам перевірити, чи виконуються обидві умови.

У змінну `score` будемо приймати значення балу. Система оцінювання в різних університетах може дещо відрізнятися, але в цілому вона виглядає так:



:::: {.columns}

::: {.column width="40%"}
- `90 <= score <= 100` - `A`
- `80 <= score < 90` - `B`
- `70 <= score < 80` - `C`
- `66 <= score < 70` - `D`
- `60 <= score < 66` - `E`
- `21 <= score < 60` - `FX`
- `score < 20` - `F`
:::

::: {.column width="60%"}
```{python}
#| eval: false

score = int(input('Введіть бал: ')) # 90

if score >= 90 and score <= 100:
    print('Оцінка: A')
elif score >= 80 and score < 90:
    print('Оцінка: B')
elif score >= 70 and score < 80:
    print('Оцінка: C')
elif score >= 66 and score < 70:
    print('Оцінка: D')
elif score >= 60 and score < 66:
    print('Оцінка: E')
elif score >= 21 and score < 60:
    print('Оцінка: FX')
else:
    print('Оцінка: F')
```

```{python}
#| echo: false
#| label: grade_echo

score = 90

if score >= 90 and score <= 100:
    print('Оцінка: A')
elif score >= 80 and score < 90:
    print('Оцінка: B')
elif score >= 70 and score < 80:
    print('Оцінка: C')
elif score >= 66 and score < 70:
    print('Оцінка: D')
elif score >= 60 and score < 66:
    print('Оцінка: E')
elif score >= 21 and score < 60:
    print('Оцінка: FX')
else:
    print('Оцінка: F')
```
:::

::::

## Логічний оператор `and`

Python дозволяє поміняти місцями `score` і відповідний бал при порівнянні. Такий код буде працювати так само, як і попередній:

```{python}
#| eval: false
#| label: grade_eval_swap

score = int(input('Введіть бал: ')) # 80

if 90 <= score and score <= 100:
    print('Оцінка: A')
elif 80 <= score and score < 90:
    print('Оцінка: B')
elif 70 <= score and score < 80:
    print('Оцінка: C')
elif 66 <= score and score < 70:
    print('Оцінка: D')
elif 60 <= score and score < 66:
    print('Оцінка: E')
elif 21 <= score and score < 60:
    print('Оцінка: FX')
else:
    print('Оцінка: F')
```

```{python}
#| echo: false
#| label: grade_echo_swap

score = 80

if 90 <= score and score <= 100:
    print('Оцінка: A')
elif 80 <= score and score < 90:
    print('Оцінка: B')
elif 70 <= score and score < 80:
    print('Оцінка: C')
elif 66 <= score and score < 70:
    print('Оцінка: D')
elif 60 <= score and score < 66:
    print('Оцінка: E')
elif 21 <= score and score < 60:
    print('Оцінка: FX')
else:
    print('Оцінка: F')
```

## Логічний оператор `and`

Або навіть об'єднувати діапазони:

```{python}
#| eval: false
#| label: grade_eval_range

score = int(input('Введіть бал: ')) # 70

if 90 <= score <= 100:
    print('Оцінка: A')
elif 80 <= score < 90:
    print('Оцінка: B')
elif 70 <= score < 80:
    print('Оцінка: C')
elif 66 <= score < 70:
    print('Оцінка: D')
elif 60 <= score < 66:
    print('Оцінка: E')
elif 21 <= score < 60:
    print('Оцінка: FX')
else:
    print('Оцінка: F')
```

```{python}
#| echo: false
#| label: grade_echo_range

score = 70

if 90 <= score <= 100:
    print('Оцінка: A')
elif 80 <= score < 90:
    print('Оцінка: B')
elif 70 <= score < 80:
    print('Оцінка: C')
elif 66 <= score < 70:
    print('Оцінка: D')
elif 60 <= score < 66:
    print('Оцінка: E')
elif 21 <= score < 60:
    print('Оцінка: FX')
else:
    print('Оцінка: F')
```

## Логічний оператор `and`

Якщо задуматись, то можна зробити ще краще:

```{python}
#| eval: false
#| label: grade_eval_optimized

score = int(input('Введіть бал: ')) # 70

if score >= 90:
    print('Оцінка: A')
elif score >= 80:
    print('Оцінка: B')
elif score >= 70:
    print('Оцінка: C')
elif score >= 66:
    print('Оцінка: D')
elif score >= 60:
    print('Оцінка: E')
elif score >= 21:
    print('Оцінка: FX')
else:
    print('Оцінка: F')
```

```{python}
#| echo: false
#| label: grade_echo_optimized

score = 70

if score >= 90:
    print('Оцінка: A')
elif score >= 80:
    print('Оцінка: B')
elif score >= 70:
    print('Оцінка: C')
elif score >= 66:
    print('Оцінка: D')
elif score >= 60:
    print('Оцінка: E')
elif score >= 21:
    print('Оцінка: FX')
else:
    print('Оцінка: F')
```

## Парність та оператор `%`

У змінну `x` будемо приймати значення числа. Якщо число ділиться на 2 без остачі, то воно є парним:

```{python}
#| eval: false
#| label: parity_eval

x = int(input('Введіть число: ')) # 2

if x % 2 == 0:
    print('Число парне')
else:
    print('Число непарне')
```

```{python}
#| echo: false
#| label: parity_echo

x = 2

if x % 2 == 0:
    print('Число парне')
else:
    print('Число непарне')
```

## Парність та оператор `%`

Рішення через власну функцію:

```{python}
#| eval: false
#| label: is_even_eval

def main():
    x = int(input('Введіть число: ')) # 2

    if is_even(x):
        print('Число парне')
    else:
        print('Число непарне')

def is_even(n):
    if x % 2 == 0:
        return True
    else:
        return False

main()
```

```{python}
#| echo: false
#| label: is_even_echo

def main():
    x = 2

    if is_even(x):
        print('Число парне')
    else:
        print('Число непарне')

def is_even(n):
    if x % 2 == 0:
        return True
    else:
        return False

main()
```

## Парність та оператор `%`

А можна ще краще? Так...

```{python}
#| eval: false
#| label: is_even_eval_pythonic

def main():
    x = int(input('Введіть число: ')) # 2

    if is_even(x):
        print('Число парне')
    else:
        print('Число непарне')

def is_even(n):
    return True if n % 2 == 0 else False

main()
```

```{python}
#| echo: false
#| label: is_even_echo_pythonic

def main():
    x = 2

    if is_even(x):
        print('Число парне')
    else:
        print('Число непарне')

def is_even(n):
    return True if n % 2 == 0 else False

main()
```

...або ще краще:

```{python}
#| eval: false
#| label: is_even_eval_pythonic_short

def main():
    x = int(input('Введіть число: ')) # 2

    if is_even(x):
        print('Число парне')
    else:
        print('Число непарне')

def is_even(n):
    return n % 2 == 0

main()
```

```{python}
#| echo: false
#| label: is_even_echo_pythonic_short

def main():
    x = 2

    if is_even(x):
        print('Число парне')
    else:
        print('Число непарне')

def is_even(n):
    return n % 2 == 0

main()
```

## Оператор `match`

`match` - це механізм зіставлення з шаблонами, дозволяє вам виконувати дії в залежності від значення змінної.

Напишемо код, який запитує у користувача його ім’я, а потім просто виводить гуртожиток, на якому він навчається у книгах про Гаррі Поттера:

```{python}
#| eval: false
#| label: house_eval

name = input('Введіть ім\'я: ') # Драко

if name == 'Гаррі':
    print('Ґрифіндор')
elif name == 'Герміона':
    print('Ґрифіндор')
elif name == 'Рон':
    print('Ґрифіндор')
elif name == 'Драко':
    print('Слизерин')
else:
    print('Хто?')
```

```{python}
#| echo: false
#| label: house_echo

name = 'Драко'

if name == 'Гаррі':
    print('Ґрифіндор')
elif name == 'Герміона':
    print('Ґрифіндор')
elif name == 'Рон':
    print('Ґрифіндор')
elif name == 'Драко':
    print('Слизерин')
else:
    print('Хто?')
```

## Оператор `match`

У попередньому коді є певна повторюваність: Гаррі, Герміона та Рон належать до Гріфіндору. Давайте об’єднаємо ці умови в одну:

```{python}
#| eval: false
#| label: house_eval_united

name = input('Введіть ім\'я: ') # Герміона

if name == 'Гаррі' or name == 'Герміона' or name == 'Рон':
    print('Ґрифіндор')
elif name == 'Драко':
    print('Слизерин')
else:
    print('Хто?')
```

```{python}
#| echo: false
#| label: house_echo_united

name = 'Герміона'

if name == 'Гаррі' or name == 'Герміона' or name == 'Рон':
    print('Ґрифіндор')
elif name == 'Драко':
    print('Слизерин')
else:
    print('Хто?')
```

## Оператор `match`

А тепер, нарешті, через `match`:

```{python}
#| eval: false
#| label: house_eval_match

name = input('Введіть ім\'я: ') # Рон

match name:
    case 'Гаррі':
        print('Ґрифіндор')
    case 'Герміона':
        print('Ґрифіндор')
    case 'Рон':
        print('Ґрифіндор')
    case 'Драко':
        print('Слизерин')
    case _:
        print('Хто?')
```

```{python}
#| echo: false
#| label: house_echo_match

name = 'Рон'

match name:
    case 'Гаррі':
        print('Ґрифіндор')
    case 'Герміона':
        print('Ґрифіндор')
    case 'Рон':
        print('Ґрифіндор')
    case 'Драко':
        print('Слизерин')
    case _:
        print('Хто?')
```

Зверніть увагу на те, що я використовую `_` для визначення варіанту за замовчуванням. Це означає, що якщо жоден з варіантів не відповідає значенню name, то виконається варіант за замовчуванням. Це дозволяє нам уникнути використання else в кінці.

## Оператор `match`

Можна краще? Так - об’єднання трьох операторів `case` ми можемо використовувати оператор `|`:

```{python}
#| eval: false
#| label: house_eval_match_or

name = input('Введіть ім\'я: ') # Гаррі

match name:
    case 'Гаррі' | 'Герміона' | 'Рон':
        print('Ґрифіндор')
    case 'Драко':
        print('Слизерин')
    case _:
        print('Хто?')
```

```{python}
#| echo: false
#| label: house_echo_match_or

name = 'Гаррі'

match name:
    case 'Гаррі' | 'Герміона' | 'Рон':
        print('Ґрифіндор')
    case 'Драко':
        print('Слизерин')
    case _:
        print('Хто?')
```


Варто зазначити, що Вам не потрібен оператор `break` для виходу з `case`, Ви просто використовуєте `_` як паличку-виручалочку в кінці коду.

## Порівняння рядків

Порівняння рядків влаштовано трохи хитріше. Почнемо з простого та розглянемо порівняння двох однакових рядків:

```{python}
print('abc' == 'abc')
```

А якщо записати так:

```{python}
print('abc' > 'abc')
```

Порівняння рядків у Python відбувається лексикографічно, тобто посимвольно зліва направо. Якщо символи збігаються, Python переходить до наступного символу в рядку і продовжує порівняти доти, доки не знайде різниця між символами в рядку.

```{python}
str1 = 'hello'
str2 = 'world'
print(str1 < str2 ) 
```

```{python}
str1 = 'apple'
str2 = 'banana'
print(str1 > str2) 
```

```{python}
str1 = 'abc'
str2 = 'aba'
print(str1 > str2 ) 
```

# Цикли {background-iframe="colored-particles/index.html"}

## Цикл `while`

Припустимо нам потрібно створити програму кота, який буде "нявкти" три рази:

:::: {.columns}

::: {.column width="40%"}
```{python}
#| label: cat

print("Няв!")
print("Няв!")
print("Няв!")
```
:::

::: {.column width="60%"}
```{mermaid}
%%| echo: false
%%| fig-height: 6.5
%%{init:{"theme":"base", "flowchart": {"htmlLabels": true}}}%%

flowchart TB
    A(Початок) --> B["'Няв!'"]
    B --> C["'Няв!'"]
    C --> D["'Няв!'"]
    D --> E(Кінець)
```
:::

::::

Якщо масштабувати задачу, то вочевидь це не найкращій варіант. Для цього існують цикли.

## Цикл `while`

Ключове слово `while` - це конструкція, яка дозволяє ставити питання знову і знову. 

:::: {.columns}

::: {.column width="40%"}
```{python}
#| label: cat-while

i = 3
while i > 0:
    print("Няв!")
    i = i - 1
```
:::

::: {.column width="60%"}
```{mermaid}
%%| echo: false
%%| fig-height: 6.5
%%{init:{"theme":"base", "flowchart": {"htmlLabels": true}}}%%

flowchart TB
    A(Початок) --> B["i = 3"]
    B --> C{"i > 0"}
    C -- True --> D["'Няв!'"]
    D --> E["i = i - 1"]
    E --> C
    C -- False --> F(Кінець)
```
:::

::::

## Цикл `while`

Або можна піти від зворотного і використати "синтаксичний цукор":

:::: {.columns}

::: {.column width="40%"}
```{python}
#| label: cat-while-2

i = 0
while i < 3:
    print("Няв!")
    i += 1
```
:::

::: {.column width="60%"}
```{mermaid}
%%| echo: false
%%| fig-height: 6.5
%%{init:{"theme":"base", "flowchart": {"htmlLabels": true}}}%%

flowchart TB
    A(Початок) --> B["i = 0"]
    B --> C{"i < 3"}
    C -- True --> D["'Няв!'"]
    D --> E["i += 1"]
    E --> C
    C -- False --> F(Кінець)
```
:::

::::

## Цикл `for` та списки

`list` - це структура даних, яка дозволяє зберігати декілька значень у одній змінній.

Списки в Python створюються за допомогою квадратних дужок `[]` і можуть містити будь-які значення, в тому числі інші списки.

Принцип роботи циклу `for` полягає в тому, що він дозволяє ітераційно перебирати список елементів, наприклад так:

```{python}
#| label: cat-for

for i in [0, 1, 2]:
    print("Няв!")
```

## Цикл `for` та списки

Що в попередньому варіанті коду не так? Якщо ми захочемо змінити кількість нявкань, нам доведеться змінювати список. Це не дуже зручно. Щоб цього уникнути, ми можемо скористатися функцією `range()`, яка дозволяє створити список послідовності чисел:

```{python}
#| label: cat-for-2

for i in range(3):
    print("Няв!")
```

Pythonic варіант:

```{python}
#| label: cat-for-3

for _ in range(3):
    print("Няв!")
```

А можна ще?

```{python}
#| label: cat-for-4

print("Няв!\n" * 3, end="")
```

## `while` + `for`

Давайте запитаємо користувача, скільки разів цей кіт має нявкнути:

```{python}
#| label: cat-for-5-eval
#| eval: false

while True:
    n = int(input("Скільки разів кіт має нявкнути? ")) # 3
        if n > 0:
            break

for _ in range(n):
    print("Няв!")
```

```{python}
#| label: cat-for-5-echo
#| echo: false

n = 3

for _ in range(n):
    print("Няв!")
```

## `while` + `for` + власна функція

Давайте ще трошки попрактикуємо писати власні функції:

```{python}
#| label: cat-for-6
#| eval: false

def main():
    number = get_number()
    cat(number)

def get_number():
    while True:
        n = int(input("Скільки разів кіт має нявкнути? "))
        if n > 0:
            break
    return n

def cat(n):
    for _ in range(n):
        print("Няв!")

main()
```

## Індексація списків

Потренуємося працювати з індексами списків.

До будь-якого елемента списку можна звернутися за його індексом. Запам’ятайте, що індексація починається з нуля:

```{python}
#| label: hogwarts

students = ["Гаррі Поттер", "Герміона Грейнджер", "Рон Уізлі"]
```

Як роздрукувати список студентів? Для цього я можу скористатися індексом, який вказує на позицію елемента у списку за допомогою квадратних [] дужок після назви змінної:

```{python}
#| label: hogwarts-2

students = ["Гаррі Поттер", "Герміона Грейнджер", "Рон Уізлі"]

print(students[0])
print(students[1])
print(students[2])
```

## Індексація списків

Але ж має бути кращий спосіб, чи не так?

```{python}
#| label: hogwarts-3

students = ["Гаррі Поттер", "Герміона Грейнджер", "Рон Уізлі"]

for student in students:
    print(student)
```

А що, якщо я хочу крім імені студента вивести його номер у списку? Для цього я можу скористатися функцією `enumerate()`, яка дозволяє мені отримати індекс елемента у списку:

```{python}
#| label: hogwarts-5

students = ["Гаррі Поттер", "Герміона Грейнджер", "Рон Уізлі"]

for i, student in enumerate(students):
    print(f"{i + 1}: {student}")
```

## Індексація списків

Можна робити зрізи списків:

```{python}
students = ["Гаррі Поттер", "Герміона Грейнджер", "Рон Уізлі"]

print(students[0:2])
```

## Методи списків

Методи - це функції, які можна викликати для списків. Методи списків дозволяють виконувати різні дії зі списками.

- `append()` - додає елемент у кінець списку

```{python}
students = ["Гаррі Поттер", "Герміона Грейнджер", "Рон Уізлі"]

students.append("Драко Малфой")
print(students)
```

- `clear()` - видаляє всі елементи списку

```{python}

students = ["Гаррі Поттер", "Герміона Грейнджер", "Рон Уізлі"]

students.clear()
print(students)
```

- `copy()` - повертає копію списку

```{python}

students = ["Гаррі Поттер", "Герміона Грейнджер", "Рон Уізлі"]

students_copy = students.copy()
print(students_copy)
```

## Методи списків

- `count()` - повертає кількість елементів списку

```{python}

house = ["Ґрифіндор", "Ґрифіндор", "Ґрифіндор", "Слизерин"]

print(house.count("Слизерин"))
```

- `extend()` - додає елементи іншого списку до поточного

```{python}
students = ["Гаррі Поттер", "Герміона Грейнджер", "Рон Уізлі"]

new_students = ["Драко Малфой", "Невілл Лонгботтом"]
print(students.extend(new_students))
```

- `index()` - повертає індекс першого елемента зі списку

```{python}
students = ["Гаррі Поттер", "Герміона Грейнджер", "Рон Уізлі"]

print(students.index("Герміона Грейнджер"))
```

## Методи списків

- `insert()` - додає елемент у список за індексом

```{python}
students = ["Гаррі Поттер", "Герміона Грейнджер", "Рон Уізлі"]

students.insert(1, "Драко Малфой")
print(students)
```

- `pop()` - видаляє та повертає елемент із заданим індексом

```{python}
students = ["Гаррі Поттер", "Герміона Грейнджер", "Рон Уізлі", "Драко Малфой"]

removed_student = students.pop(1)
print(removed_student)
print(students)
```

- `remove()` - видаляє елемент із списку за значенням

```{python}
students = ["Гаррі Поттер", "Герміона Грейнджер", "Рон Уізлі", "Драко Малфой"]

students.remove("Драко Малфой")
print(students)
```

## Методи списків

- `reverse()` - змінює порядок елементів у списку на зворотний

```{python}
students = ["Гаррі Поттер", "Герміона Грейнджер", "Рон Уізлі", "Драко Малфой"]

students.reverse()
print(students)
```

- `sort()` - сортує елементи списку

```{python}
students = ["Герміона Грейнджер", "Гаррі Поттер", "Драко Малфой", "Рон Уізлі"]

students.sort()
print(students)
```

## List comprehension

List comprehension в Python - це компактний спосіб створення нового списку на основі наявного списку або іншої ітерованої послідовності, наприклад, рядка.

Загальний синтаксис для створення list comprehension виглядає наступним чином:

```{.python}
new_list = [expression for item in iterable if condition]
```

де:

- `expression` - вираз, який застосовуватиметься до кожного елемента списку або послідовності
- `item` - змінна, що представляє поточний елемент послідовності, що ітерується;
- `iterable` - список або інша послідовність, що ітерується;
- `condition` (необов'язково) - умова, за якою буде фільтруватися вихідна послідовність.

## List comprehension

1. Припустимо, у нас є список із числами, ми хочемо створити новий список із квадратами цих чисел. Варіант рішення:

```{python}
numbers = [1, 2, 3, 4, 5]
squares = []
for i in numbers:
    squares.append(i**2)

print(squares)
```

А ось так виглядало б рішення за допомогою list comprehension:

```{python}
numbers = [1, 2, 3, 4, 5]
squares = [x ** 2 for x in numbers]

print(squares)
```

Інакше кажучи, результат роботи нашого циклу відразу поміщається в список.

## List comprehension

2. Створення нового списку, що містить тільки парні числа з вихідного списку:

Стандартний розв'язок:

```{python}
numbers = [1, 2, 3, 4, 5]
even_numbers = []
for i in numbers:
    if i % 2 == 0:
        even_numbers.append(i)

print(even_numbers)
```

List comprehension:

```{python}
numbers = [1, 2, 3, 4, 5]
even_numbers = [x for x in numbers if x % 2 == 0]

print(even_numbers)
```

## List comprehension

3. Створення нового списку, що містить довжини слів із вихідного списку:

```{python}
words = ["hello", "world", "python", "list"]
word_lengths = [len(word) for word in words]

print(word_lengths)
```

## Словники

Словники - це структура даних, яка дозволяє зберігати пари ключ-значення у одній змінній. Словники в Python створюються за допомогою фігурних дужок `{}` і можуть містити будь-які значення, в тому числі інші словники.

Припустимо, що ми хочемо відстежувати, хто до якого гуртожитку відноситься в Гоґвортсі. Для прикладу візьмемо чотирьох учнів:

| **Герміона Грейнджер** | **Гаррі Поттер** | **Рон Уізлі**   | **Драко Малфой** |
|--------------|-----------|-----------|-----------|
| Ґрифіндор    | Ґрифіндор | Ґрифіндор | Слизерин  |

<br>

```{python}
#| label: hogwarts-6

students = {
    "Герміона Грейнджер": "Ґрифіндор",
    "Гаррі Поттер": "Ґрифіндор",
    "Рон Уізлі": "Ґрифіндор",
    "Драко Малфой": "Слизерин"
}

print(students)
```

## Словники

Тепер давайте виведемо на екран ім’я та гуртожиток кожного учня. Для цього ми можемо скористатися циклом `for`:

```{python}
#| label: hogwarts-7

students = {
    "Герміона Грейнджер": "Ґрифіндор",
    "Гаррі Поттер": "Ґрифіндор",
    "Рон Уізлі": "Ґрифіндор",
    "Драко Малфой": "Слизерин"
}

for student in students:
    print(student)
```

Щоб вивести ім’я та гуртожиток кожного учня, ми можемо скористатися індексацією словника за ключем:

```{python}
#| label: hogwarts-8

students = {
    "Герміона Грейнджер": "Ґрифіндор",
    "Гаррі Поттер": "Ґрифіндор",
    "Рон Уізлі": "Ґрифіндор",
    "Драко Малфой": "Слизерин"
}

for student in students:
    print(f"{student}: {students[student]}")
```

## Словники {.smaller}

Давайте ускладнимо задачу і додамо ще одину характеристику до кожного учня - його Патронуса:

| **Ім'я**           | **Гуртожиток** | **Патронус** |
|--------------------|----------------|--------------|
| Герміона Грейнджер | Ґрифіндор      | Видра        |
| Гаррі Поттер       | Ґрифіндор      | Олень        |
| Рон Уізлі          | Ґрифіндор      | Тер'єр       |
| Драко Малфой       | Слизерин       |              |

<br>

```{python}
#| label: hogwarts-9

students = [
    {
        "ім'я": "Герміона Грейнджер",
        "гуртожиток": "Ґрифіндор",
        "патронус": "Видра"
    },
    {
        "ім'я": "Гаррі Поттер",
        "гуртожиток": "Ґрифіндор",
        "патронус": "Олень"
    },
    {
        "ім'я": "Рон Уізлі",
        "гуртожиток": "Ґрифіндор",
        "патронус": "Тер'єр"
    },
    {
        "ім'я": "Драко Малфой",
        "гуртожиток": "Слизерин",
        "патронус": None
    }
]
```

Зверніть увагу, що згідно канонічного варіанту Драко Малфой не має Патронуса. Тому ми вказали його значення як `None` - це спеціальне значення, яке означає “нічого”.

## Словники {.smaller}

Для виводу інформації про учнів ми можемо скористатися циклом `for`:

```{python}
#| label: hogwarts-10

students = [
    {
        "ім'я": "Герміона Грейнджер",
        "гуртожиток": "Ґрифіндор",
        "патронус": "Видра"
    },
    {
        "ім'я": "Гаррі Поттер",
        "гуртожиток": "Ґрифіндор",
        "патронус": "Олень"
    },
    {
        "ім'я": "Рон Уізлі",
        "гуртожиток": "Ґрифіндор",
        "патронус": "Тер'єр"
    },
    {
        "ім'я": "Драко Малфой",
        "гуртожиток": "Слизерин",
        "патронус": None
    }
]

for student in students:
    print(student["ім'я"], student["гуртожиток"], student["патронус"], sep=", ")
```

## Словники

Альтернативний варіант створення словника `students` - це використання вкладених словників:

```{python}
#| label: hogwarts-11

students = {
    "Герміона Грейнджер": {
        "гуртожиток": "Ґрифіндор",
        "патронус": "Видра"
    },
    "Гаррі Поттер": {
        "гуртожиток": "Ґрифіндор",
        "патронус": "Олень"
    },
    "Рон Уізлі": {
        "гуртожиток": "Ґрифіндор",
        "патронус": "Тер'єр"
    },
    "Драко Малфой": {
        "гуртожиток": "Слизерин",
        "патронус": None
    }
}

for student in students:
    print(student, students[student]["гуртожиток"], students[student]["патронус"], sep=", ")
```

## Створення словників {.smaller}

У Python є кілька способів створення словників:

1. **Літерали словника**

```{python}
my_dict = {'ім\'я': 'Аліса', 'вік': 25, 'місто': 'Київ'}
print(my_dict)
```

2. **Вбудована функція `dict()`**

```{python}
empty_dict = dict()
print(empty_dict)
```

```{python}
fruit_dict = dict([('яблуко', 5), ('банан', 3), ('апельсин', 2)])
print(fruit_dict)
```

3. **Генератор словників**

Генератори словників дозволяють створювати словники на основі інших послідовностей. Наприклад:

```{python}
fruit_list = ['яблуко', 'банан', 'апельсин']
fruit_dict = {fruit: len(fruit) for fruit in fruit_list}
print(fruit_dict)
```

4. **Метод `fromkeys()`**

Метод `fromkeys()` дає змогу створити словник із зазначеними ключами й одним і тим самим значенням для всіх ключів. Наприклад:

```{python}
fruit_list = ['яблуко', 'банан', 'апельсин']
fruit_dict = {}.fromkeys(fruit_list, 0)
print(fruit_dict)
```

## Методи словників

1. **`get()`** - дає змогу отримати значення за ключем, але на відміну від звернення через `[]`, не викликає виняток `KeyError`, якщо ключ відсутній у словнику:

```{python}
my_dict = {"one": 1, "two": 2, "three": 3}
print(my_dict.get("two"))
print(my_dict.get("four", "Key not found"))
```

2. **`keys()`** - дає змогу отримати список ключів словника:

```{python}
my_dict = {"one": 1, "two": 2, "three": 3}
print(my_dict.keys())
```

3. **`values()`** - дає змогу отримати список значень словника:

```{python}
my_dict = {"one": 1, "two": 2, "three": 3}
print(my_dict.values())
```

## Методи словників

4. **`items()`** - дає змогу отримати список пар ключ-значення словника:

```{python}
my_dict = {"one": 1, "two": 2, "three": 3}
print(my_dict.items())
```

5. **`pop()`** - дає змогу видалити пару ключ-значення за ключем. Якщо ключ відсутній, викликає виняток `KeyError` або повертає другий аргумент, якщо він переданий:

```{python}
my_dict = {"one": 1, "two": 2, "three": 3}
print(my_dict.pop("two"))
print(my_dict.pop("four", "Key not found"))
```

6. **`clear()`** - дає змогу видалити всі пари ключ-значення зі словника:

```{python}
my_dict = {"one": 1, "two": 2, "three": 3}
my_dict.clear()
print(my_dict)
```

## Методи словників

7. **`update()`** - дає змогу оновити словник із іншого словника або із послідовності пар ключ-значення:

```{python}
my_dict = {"one": 1, "two": 2, "three": 3}
new_dict = {"two": 22, "four": 4}
my_dict.update(new_dict)
print(my_dict)
```

8. **`copy()`** - дає змогу створити копію словника:
```{python}
my_dict = {"one": 1, "two": 2, "three": 3}
new_dict = my_dict.copy()
print(new_dict)
```

## Оператори `continue` та `break`

Оператор `continue` і оператор `break` є керуючими операторами в циклах, їх використовують для зміни поведінки виконання циклу. 

Оператор `continue` використовується для пропуску частини тіла циклу, що залишилася, і переходу до наступної ітерації циклу. Якщо зустрінеться оператор `continue`, то код нижче за нього в поточній ітерації циклу не буде виконано, а виконання циклу продовжиться відразу з наступної ітерації:

```{python}
for i in range(1, 6):
    if i == 3:
        continue
    print(i)
```

## Оператори `continue` та `break`

Оператор `break` використовується для переривання виконання циклу. Якщо зустрінеться оператор `break`, виконання циклу буде припинено і відбувається вихід із циклу:

```{python}
for i in range(1, 6):
    if i == 3:
        break
    print(i)
```

## Оператори `continue` та `break`

Приклад спільного використання:

```{python}
employees = [
    {'name': 'John', 'qualification': 'low'},
    {'name': 'Alice', 'qualification': 'high'},
    {'name': 'Bob', 'qualification': 'medium'},
    {'name': 'Eva', 'qualification': 'low'},
    {'name': 'Mike', 'qualification': 'high'},
    {'name': 'Lisa', 'qualification': 'medium'}
]

found_high_qualification_employee = False

for employee in employees:
    qualification = employee['qualification']
    if qualification == 'low':
        continue # Пропускаємо працівника з низькою кваліфікацією
    elif qualification == 'high':
        found_high_qualification_employee = True
        high_qualification_employee = employee
        break # Знайдено працівника з високою кваліфікацією, припиняємо пошук
if found_high_qualification_employee:
    print("Працівника з високою кваліфікацією знайдено!")
    print(high_qualification_employee)
else:
    print("Працівника з високою кваліфікацією не знайдено.")
```

# Дякую за увагу! {.unnumbered .unlisted background-iframe="colored-particles/index.html"}

<br>
<br>

{{< iconify solar book-bold >}} [Матеріали курсу](https://aranaur.rbind.io/lectures/applied_analytics/)

{{< iconify mdi envelope >}} ihor.miroshnychenko\@kneu.ua

{{< iconify ic baseline-telegram >}} [Data Mirosh](https://t.me/araprof)

{{< iconify mdi linkedin >}} [\@ihormiroshnychenko](https://www.linkedin.com/in/ihormiroshnychenko/)

{{< iconify mdi github >}} [\@aranaur](https://github.com/Aranaur)

{{< iconify ion home >}} [aranaur.rbind.io](https://aranaur.rbind.io)