---
title: "Лабораторна робота №2"
subtitle: "R для аналізу даних"
---

::: {.callout-note}
Це орієнтовний план лабораторної роботи. Ви можете модифікувати завдання відповідно до ваших потреб та бажань.
:::

# Завдання

1. **Знайомство з даними:**
    - Завантажте файл
    - Виведіть перші 6 строк таблиці
    - Виведіть останні 6 строк таблиці
    - Виведіть загальну інформацію про дані
    - Виведіть кількість рядків та стовпців
    - Виведіть назви стовпців
2. **Фільтрація та вибірка даних:**
    - Проведіть фільтрацію даних за допомогою функції `filter()` та математичних операцій
    - Відберіть 1, 3 та 5 стовпці даних за допомогою функції `select()
3. **Групування та агрегація:**
    - Згрупуйте дані за допомогою функції `group_by()`
    - Виконайте агрегацію даних за допомогою функції `summarise()`
4. **Сортування:**
    - Відсортуйте дані за допомогою функції `arrange()`
5. **Створення нових змінних:**
    - Створіть нову змінну за допомогою функції `mutate()`
6. **Збереження результатів:**
    - Збережіть результати одного із завдань у вигляді окремого файлу

::: {.callout-important}
Звіт з лабораторної роботи необхідно оформити за допомогою Quarto.
:::
